### ISSUE TITLE
Antivirus block xmrig github page

### ISSUE THREAD

**Issue by DeadManWalkingTO** [xmrig/xmrig#1000]
Avast antivirus continues to block the github page. (#883)
---
![001](https://user-images.githubusercontent.com/34924727/54767236-6c7a1b80-4c05-11e9-9ddc-63a892b4e2d3.png)
---
![002](https://user-images.githubusercontent.com/34924727/54767255-756aed00-4c05-11e9-88b0-ed93bd6ff048.png)
---
![003](https://user-images.githubusercontent.com/34924727/54767269-79970a80-4c05-11e9-921f-af9b887831be.png)

**Comment by xmrig** [comment]
You can report false positive detection, but personally I will never use antivirus works as middle man for TLS.
Thank you.
