### ISSUE TITLE
Config Xmrig.exe

### ISSUE THREAD

**Issue by 3d0n1** [xmrig/xmrig#1005]
Hi,
I'm trying to create one xmrig.exe file without json so I tried

> #608

this did not help me or does not work when I compile
I'm wondering if there were some changes which do not support this option anymore?

**Comment by 3d0n1** [comment]
@xmrig  What are you suggesting to do?

**Comment by xmrig** [comment]
Check v2.14.1 changelog, it contains modern replacement, or direct link https://github.com/xmrig/xmrig/issues/957#issuecomment-468890667
Thank you.
