### ISSUE TITLE
Support uPlexa ?

### ISSUE THREAD

**Issue by eddiewang927** [xmrig/xmrig#1016]
Dose xmrig and xmrig-proxy support uplexa-algorithmic?

https://medium.com/@uplexa/uplexa-algorithmic-change-upxtwo-7066e5b9237a

**Comment by xmrig** [comment]
Right now I have no interest to support fourth algorithm (by scratchpad size) in addition I was never support uplexa.
Thank you.

**Comment by extenami** [comment]
Hello!

Uplexa still not supported by xmrig/xmrig-proxy?
