### ISSUE TITLE
Hashrate drops when other threads are running.

### ISSUE THREAD

**Issue by seongung** [xmrig/xmrig#1023]
Xmrig runs with CPU 50% usage.
4 Cores, 8 Threads(logic processors)

It works fine when it runs alone. However, when other processes start to run and
its hashrate drops by 10~20%. (Even though xmrig process takes up 50% cpu consistently)

Does it happen because cores and logic processors don't work seperately and they interfere each other?

**Comment by 2010phenix** [comment]
other process used L2 \ L3 from CPU too ;)

**Comment by Spudz76** [comment]
Sometimes, you can set affinity to fence things.  Meaning not only the miner thread affinity but then also entire rest of system processes affinity to the non-mining cores (but not the SMT cores if you're mining on either half of that core)

This worked for me on windows, although not well enough to bother with how clunky setting a base-system-affinity is (needs unofficial tools, and you can only change existing processes not the rules for newly spawned ones, etc) - Linux should be easier to set a global affinity for all processes (that aren't explicitly told to run on the fenced off cores, the miner threads).
