### ISSUE TITLE
Bug in L2 Exclusive Logic in optimalThreadsCount?

### ISSUE THREAD

**Issue by brandonlehmann** [xmrig/xmrig#1025]
https://github.com/xmrig/xmrig/blob/1d4bc030fb4ccb366765cd4feb31b95ebd9db9a5/src/core/cpu/AdvancedCpuInfo.cpp#L100

If I'm reading this correctly, shouldn't this be `cache = m_L2_exclusive ? m_L2 : (m_L2 + m_L3);` ?

**Comment by xmrig** [comment]
It's correct if L2 cache exclusive, we can sum L2 and L3, otherwise effective cache size limited to L3 size.
Thank you.
