### ISSUE TITLE
Why no colors if log file is not null?

### ISSUE THREAD

**Issue by Balzhur** [xmrig/xmrig#103]
Why? Because you do not know how to strip colors before logging?

**Comment by mnik247** [comment]
+1

**Comment by xmrig** [comment]
That right, you know nice and safe code to strip ANSI color escape?
Thank you.

**Comment by Balzhur** [comment]
Not really, bu I'm not a programmer.
This is the way I do it in bash:
`debug() {
	[ "${DEBUG}" = "1" ] && echo -en "Debug: [\e[0;32m${@}\e[0m]\n"
	echo "`LANG=C /bin/date +'%b %e %H:%M:%S'` `/bin/hostname -s` ${@}" >> ${LOG}
}
`
e.g. you print output using some function which duplicates the output to screen with colors and to log in plain text adding regular 'unix style' timestamping. Hope this helps.

**Comment by merdecas** [comment]
+1
