### ISSUE TITLE
can add support for mipsel cpu?

### ISSUE THREAD

**Issue by 77pippofranco** [xmrig/xmrig#1033]
what think about BCM7346B2 cpu ?

cat /proc/cpuinfo 
system type             : BCM7346B2 STB platform
machine                 : Unknown
processor               : 0
cpu model               : Broadcom BMIPS5000 V1.1  FPU V0.1
BogoMIPS                : 733.18
cpu MHz                 : 1104.006
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 64
extra interrupt vector  : yes
hardware watchpoint     : no
isa                     : mips1 mips2 mips32r1
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : Broadcom BMIPS5000 V1.1  FPU V0.1
BogoMIPS                : 552.96
cpu MHz                 : 1104.006
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 64
extra interrupt vector  : yes
hardware watchpoint     : no
isa                     : mips1 mips2 mips32r1
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

i have try to build in debian quemu vmlinux-4.9.0-4-4kc-malta without success.. can help me? thx

**Comment by Spudz76** [comment]
You would have to disable all ASM and remove all incompatible optimizations (`-maes` and friends)
And even then it might not work, but if it does... you could be looking at a very maximum hashrate of 1.2H/s, probably worse.

In other words, no, not worth it, MIPS32 does not have the accels needed for present-day algos, and even worse is 32-bit.  Minimum 'embedded' type CPU is generally some form of ARM with Neon extensions.  Also fast local memory (cpu cache) is where the action happens, if it has to go out to external memory the hashrate is destroyed (part of ASIC resistance).  These have no cache and their memory is slow.

Designed for running large case/switch or if/then/else trees, but not really for "thinking" or "maths" besides arithmetic.  Less a CPU than a Logic Unit (one tiny step above a microcontroller).

**Comment by seisdr** [comment]
I want to do it though
nanostation has no enough storage for qemu and xmrig so I want static xmrig for mipsel
