### ISSUE TITLE
question: RandomX

### ISSUE THREAD

**Issue by plastkort** [xmrig/xmrig#1035]
will XMRig support RandomX or will this be something totally new ?

**Comment by xmrig** [comment]
I will follow Monero path, so if next algorithm will be RandomX I have no choice.
Thank you.

**Comment by snipeTR** [comment]
What kind of information do we have about randomX? Will 32bit be supported?

**Comment by xmrig** [comment]
https://github.com/tevador/RandomX

**Comment by tarris034** [comment]
Good to hear, I have always supported xmrig and would love to see it with RandomX support.
Thank you for all your work, best miner in the business.
