### ISSUE TITLE
How to point multiple xmrig miners to the monero daemon instead of a pool?

### ISSUE THREAD

**Issue by lexphor** [xmrig/xmrig#104]
Hello, 

I'd like to solo mine. I know you can do it with the default daemon miner but I have multiple computers and I don't want to maintain a node on each one of them. So I'd like to run the daemon on one of the computers and set up xmrig on the rest of the machines to point to the daemon. Any suggestions on how to do that?

Your help is greatly appreciated. Thanks.

**Comment by xmrig** [comment]
There not too much options:
* Setup own pool.
* Something like that https://github.com/sammy007/monero-stratum
* Use solo mining on this pool https://xmrpool.net

**Comment by kilid** [comment]
with the new XMR GUI wallet solo mining is added there I think its possible to forward rigs hashing power to that node if they are all connected on same local area network

**Comment by trasherdk** [comment]
@lexphor I have tested https://github.com/sammy007/monero-stratum, and it works OK.

@kilid XMR GUI Wallet mining works only on a local daemon. Just like mining in the console wallet.
You can connect to a remote wallet, but can't start mining remote.

**Comment by trasherdk** [comment]
@kilid 

I'm mining on a Windows 10 x64, xmr-stak.
And running monero-tratum and monerod on an old laptop, running Slackware 14.2 x64, 2GB RAM.
No problem.

**Comment by krisztian-zagonyi** [comment]
Is there any newer way to do that?
Is that still working? Worth a try? :)
Thank you.

**Comment by SChernykh** [comment]
@krisztian-zagonyi You can point https://github.com/xmrig/xmrig-proxy to your monerod and point all xmrig miners to this proxy.

**Comment by krisztian-zagonyi** [comment]
If I do on this way, should I see in my gui/cli wallet the higher hash rate?

**Comment by krisztian-zagonyi** [comment]
Thanks for you reply. :)
Proxy `config.json:
`{
    "autosave": true,
    "donate-level": 5,
    "cpu": true,
    "opencl": false,
    "cuda": false,
    "pools": [
        {
            "coin": "monero",
            "url": "127.0.0.1:18081",
            "user": "44G-XXXX",
            "daemon": true
        }
    ]
}`
Xmrig config.json:
`{
    "autosave": true,
    "donate-level": 5,
    "cpu": true,
    "opencl": false,
    "cuda": false,
    "pools": [
        {
            "url": "0.0.0.0:3333"
        }
    ]
}`
I created both jsons with https://xmrig.com/wizard
Currently I see my gui wallet hash is: 183 with 1 thread.
My proxy is connected to the local daemon and I see my worker but with 0.00kH/s.
My xmrig is connected to proxy with 2000h/s.
Is that correct?
Is my xmrig miner mining to my solo mining gui wallet? just because I cannot see the hash on the wallet nor on proxy.
Thanks for your help. :)

**Comment by SChernykh** [comment]
Wallet only shows its own hashrate. You should check xmrig and proxy hashrates. Proxy shows approximate hashrate based on how many accepted results xmrig submits to it. If the proxy difficulty is too high, it'll show 0 and occasionally something more than 0.

**Comment by krisztian-zagonyi** [comment]
Thank you. So you think my config is good? :)

**Comment by SChernykh** [comment]
`"url": "0.0.0.0:3333"` is not correct, you should use your proxy external IP in xmrig config.

**Comment by krisztian-zagonyi** [comment]
I am using my public IP, and opened the 3333 port on my router, but connect error: "operation canceled" :/

**Comment by trasherdk** [comment]
Another option, to mine with multiple xmrig, against own monerod is [jtgrassie / monero-pool](https://github.com/jtgrassie/monero-pool)
