### ISSUE TITLE
xmrig v2.16.0-beta

### ISSUE THREAD

**Issue by directdepot** [xmrig/xmrig#1041]
Trying to build new version of xmrig on windows but can not find RANDOMX.  (Could NOT find RANDOMX (missing: RANDOMX_LIBRARY RANDOMX_INCLUDE_DIR)).  Were can I get this include directory? Thx...

**Comment by xmrig** [comment]
RandomX included to recent xmrig-deps (for msvc2017 and gcc) if it's not your case, you should build library by yourself: https://github.com/wownero/RandomWOW after successful build, specify path to include directory and library on cmake phase `cmake .. -DRANDOMX_INCLUDE_DIR=... -DRANDOMX_LIBRARY=...`

Another option if you don't need RandomWOW support is disable this algorithm `cmake .. -DWITH_RANDOMX=OFF`.
Thank you.

**Comment by directdepot** [comment]
Thanks…

**Comment by Spudz76** [comment]
With msvc2017 x64 from xmrig-deps master:
```
c:\build\randomwow\src\randomx.cpp : fatal error C1083: Cannot open compiler generated file: 'x64\Release\randomx.asm': No such file or directory
```
But I have no `c:\build\` and there is no `randomx.asm`

**Comment by snipeTR** [comment]
![image](https://user-images.githubusercontent.com/31975916/60330776-e146b980-999b-11e9-95ad-ce5340ce9886.png)
![image](https://user-images.githubusercontent.com/31975916/60330808-edcb1200-999b-11e9-8cf4-b3cedb47b1f3.png)

**Comment by nssy** [comment]
Thanks for the response @xmrig
Have compiled and successfully started mining on wownero pool.
`git clone git@github.com:wownero/RandomWOW.git /tmp/RandomWOW`
`cd /tmp/RandomWOW && make`

Then on xmrig build folder
`cmake ..  -DRANDOMX_INCLUDE_DIR=/tmp/RandomWOW/src -DRANDOMX_LIBRARY=/tmp/RandomWOW/bin/librandomx.a`

**Comment by cryptonote-social** [comment]
This version doesn't seem to tell if you are using hugepages?

`[2019-06-28 16:46:02.008] READY (CPU) threads 3(3) memory 3072 KB
`

**Comment by xmrig** [comment]
@cryptonote-social Yep I removed huge pages information for RandomWOW algorithm, because it use own internal mechanism to allocate huge pages, it currently not integrated to miner source like other cryptonight algorithms.
Thank you.

**Comment by cryptonote-social** [comment]
Thanks @xmrig  ... what's confusing though is it seems to work in the feature-randomx branch?
