### ISSUE TITLE
Excuse me, I want to write down the parameters,

### ISSUE THREAD

**Issue by FrelDX** [xmrig/xmrig#1045]
Excuse me, I want to write down the parameters。I don't want to specify something on the command line。I have put this code into the linux kernel to do boot from the boot。who can help me i can give you some money tks

**Comment by FrelDX** [comment]
I don't want to specify parameters on the command line. I want to write some parameters in the code and then make it into a library and integrate it into Linux.  What code do I need to modify if I do this?

**Comment by Spudz76** [comment]
No, you can't have help to make a trojan kernel-miner

Thanks.
