### ISSUE TITLE
xmrig for android

### ISSUE THREAD

**Issue by totayma** [xmrig/xmrig#1047]
Hello
is there monero android miner? (xmrig for andorid ) "new update source"

**Comment by skuroedov** [comment]
Well, you can compile it from source, actually I am working on it. I want to mine on 32 bit CPU phones, I have managed it, but I have problems with linking libraries to ARM ones...

**Comment by totayma** [comment]
how can compile it for android?

**Comment by skuroedov** [comment]
The same way as for linux, but you have to set flags and link libraries for your platform

**Comment by BenjaminWegener** [comment]
https://twitter.com/BenjaminWegener/status/1141274273186816000?s=20
