### ISSUE TITLE
Anybody who can update my source code to the recent XMR algorithm contact me

### ISSUE THREAD

**Issue by baboda52525** [xmrig/xmrig#1054]
I have 'xmr-stak-cpu' (fireice-uk)  but update doesn't supported anymore. 
so hash result always rejected by pool.
Anybody who can update my source code to the recent XMR algorithm contact me
baboda52525@gmail.com
I'am willing to pay the proper money. 
thanks

**Comment by Spudz76** [comment]
Uh, it's because xmr-stak merged them all into one, use xmr-stak itself not the old deprecated separate projects?
