### ISSUE TITLE
Windows console colors don't work

### ISSUE THREAD

**Issue by Spudz76** [xmrig/xmrig#1057]
They do work if you use `--config` mode and edit the current running config file to turn color back on...

...which led to patches ignoring any tty_init return values on Windows (which makes color work normally)...

PR #1055 and PR #1056

**Comment by Spudz76** [comment]
See Also: [xmrig-nvidia issue #196](https://github.com/xmrig/xmrig-nvidia/issues/196)

**Comment by xmrig** [comment]
Is this issue still actual?
Thank you.

**Comment by Spudz76** [comment]
I still run this patch on my builds, will try without it and see if the problem still exists.  Win7 may have something to do with it (probably works fine either way with Win10) and I run inside the normal good old cmd.exe shell (not powershell or etc).

**Comment by Spudz76** [comment]
Must have been upstream bug in an older version of libuv, it works properly without this now.  Closing...
