### ISSUE TITLE
RandomX Seg Fault

### ISSUE THREAD

**Issue by Peterlustig420** [xmrig/xmrig#1063]
Compiled xmrig with RandomWOW Package on Arm8 device.
after starting xmrig i always get Segmentation fault (Memory is only 2gb)
My Question is:
How can i switch with RandomX algo between light and fast mode?
light requires only 256mb and fast 2gb, so at default xmrig is running with fast mode ?

**Comment by xmrig** [comment]
Current version always run in fast mode, next major release (v3+) will automatically switch to light mode if failed to allocate dataset. https://i.imgur.com/xr7G5hS.png but ARM code not optimized, it just works and very slow.
Thank you.
