### ISSUE TITLE
CentOS 7 instructions update

### ISSUE THREAD

**Issue by marcel-st** [xmrig/xmrig#1067]
Hi there,

there is a package missing in the CentOS7 instructions. The second "sudo yum install" should also include the openssl-devel package.

**Comment by paulpas** [comment]
It also needs to include the command to enable the SCL environment 

scl enable devtoolset-4 bash

**Comment by marcel-st** [comment]
@paulpas i didn't use that command and had no issues in compilation or running xmrig.
