### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by rnikolenko** [xmrig/xmrig#107]
1. In config.json in this file, I can not set the value of a variable log-file. Program does not start.
2. max-cpu-usage I think the percentage is somehow strange. at a value of 75% gives 100% load of real processor cores http://take.ms/jWKH0

**Comment by xmrig** [comment]
Log file option required string contains log filename
```json
"log-file": "xmrig.log",
```

`max-cpu-usage` limiting maximum **visible** CPU usage, in your case it limited by L3 cache (8 / 2 = 4 threads) it's about 50% and on your screenshot it 49% it's ok.
