### ISSUE TITLE
LNK2001	unresolved external symbol _randomx_program_end

### ISSUE THREAD

**Issue by joey-crypto** [xmrig/xmrig#1071]
when i build xmrig 2.99 in windows7 through cmake 3.15 and vs 2017, it shows these problem. 

Error	LNK2001	unresolved external symbol _randomx_program_end	xmrig-notls	D:\xmrig-2.99.0-beta\build\jit_compiler_x86.obj	1	
Error	LNK2001	unresolved external symbol _randomx_program_epilogue	xmrig-notls	D:\xmrig-2.99.0-beta\build\jit_compiler_x86.obj	1	
Error	LNK2001	unresolved external symbol _randomx_program_loop_begin	xmrig-notls	D:\xmrig-2.99.0-beta\build\jit_compiler_x86.obj	1	
Error	LNK2001	unresolved external symbol _randomx_program_loop_end	xmrig-notls	D:\xmrig-2.99.0-beta\build\jit_compiler_x86.obj	1

**Comment by joey-crypto** [comment]
how to solve these problems.

**Comment by xmrig** [comment]
32 bit builds for Visual Studio not supported.
Thank you.
