### ISSUE TITLE
Rx dataset not reinitialized when seed_hash change

### ISSUE THREAD

**Issue by minerrocks** [xmrig/xmrig#1072]
https://github.com/xmrig/xmrig/blob/02c03b0465e34b1430c440d095d1299e5709bd91/src/backend/cpu/CpuWorker.cpp#L82-L88

Rx dataset not reinitialized when seed_hash change.
Noticed when seed hash changed for loki at block 361600, and hashrate dropped on all pools.
Xmrig should check if seed hash changed and reinitialize rx dataset.
Right now only restart of xmrig helps.

**Comment by xmrig** [comment]
v2.99.1-beta released https://github.com/xmrig/xmrig/releases/tag/v2.99.1-beta
Thank you.
