### ISSUE TITLE
v2.99.1-beta issue with ryzen 7?

### ISSUE THREAD

**Issue by mind-io** [xmrig/xmrig#1075]
v2.99.1-beta works with intel CPU, but not with ryzen 7. 
![xmrig](https://user-images.githubusercontent.com/19650639/61993857-cfc7fe80-b07a-11e9-99d6-f1373a3a2023.png)
what could be a problem?

**Comment by xmrig** [comment]
Is this issue persists on each miner start?
Thank you.

**Comment by mind-io** [comment]
Basically yes, just takes different time before it stops. sometimes 10 sec. sometimes sucessfully hashing for 20 min. and then stops.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/issues/1089#issuecomment-518287218 overclocking (CPU and/or memory) can cause this issue.
