### ISSUE TITLE
How to xmrig and conceal ccx? cryptonight_conceal?

### ISSUE THREAD

**Issue by marcel1974** [xmrig/xmrig#1078]

**Comment by marcel1974** [comment]
I have worked through the algorithms and through the beta versions. Is ccx supported? :)

**Comment by xmrig** [comment]
ccx not supported.
Thank you.

**Comment by marcel1974** [comment]
Any plans doing so in the future? I would like to get into ccx with xmrig-amd befor coin gets to $1. It feels kind of strange to search for a program other than xmrig to mine cryptonight.
