### ISSUE TITLE
HOW TO USE THIS MINER ?

### ISSUE THREAD

**Issue by DragonixARP** [xmrig/xmrig#1079]
Hello everyone and thank you for helping me and reading me ,

1)First of all , since there is not much infos about this miner , is it a silent miner ?
2) How can I use it ? I didn't find anyone or anything saying how to use it ? It runs with kali ?

**Comment by seanwhe** [comment]
> Hello everyone and thank you for helping me and reading me ,
> 
> 1)First of all , since there is not much infos about this miner , is it a silent miner ?
> 2) How can I use it ? I didn't find anyone or anything saying how to use it ? It runs with kali ?

I got tired of doing all the CLI stuff manually so I wrote myself some scripts to install. Have a look at https://github.com/seanwhe/xmrig-bash-scripts

Hope this helps.

**Comment by DragonixARP** [comment]
Thank you my friend , add me on discord and maybe we can help each other ;)
.
Gwean#1326

Le mer. 31 juil. 2019 à 19:41, Sean Wheller <notifications@github.com> a
écrit :
