### ISSUE TITLE
What will be git clone for ubuntu

### ISSUE THREAD

**Issue by looplife55** [xmrig/xmrig#1081]
I am try to install new update for wownero/wow by xmrig but it not showing 
Error which i am getting will cloning::
git clone https://github.com/xmrig/xmrig/releases/tag/v2.99.1-beta
Cloning into 'v2.99.1-beta'...
Cloning: command not found
root@jusval-3:~# fatal: https://github.com/xmrig/xmrig/releases/tag/v2.99.1-beta/info/refs not valid: is this a git repository?
fatal:: command not found

**Comment by xmrig** [comment]
Use:
`git clone https://github.com/xmrig/xmrig.git`
`git checkout beta`

In future if you already on beta branch, just `git pull`.
Thank you.

**Comment by looplife55** [comment]
BY using
git clone https://github.com/xmrig/xmrig.git
It cloning only old version. 
Plz bro guide me using your miner from 2 month to mine monero now i want to switch  to wownero(random/wow)
Btw, i never change donation level always giving 5% of my share. 😊

**Comment by xmrig** [comment]
Second command `git checkout beta` do the thing.

**Comment by looplife55** [comment]
root@jusval-3:~# cd xmrig
root@jusval-3:~/xmrig# cd build
root@jusval-3:~/xmrig/build# git checkout beta
Already on 'beta'
Your branch is up to date with 'origin/beta'.
root@jusval-3:~/xmrig/build# ./xmrig -o loki.pool.mine2gether.com:3331 -u LCfrezxEYq1HHPj4tpinrqVCLMCMg2n4rfVQmsam5U3wWwrCX3eKEHAUM2phDhpgQqdGY8Jbuut11D6u6DUt5mXPQzCwGA7 -a rx/loki -k
unable to open "/root/xmrig/build/config.json".
No valid configuration found. Exiting.
root@jusval-3:~/xmrig/build#

**Comment by looplife55** [comment]
Really dude waiting for your guide badly

**Comment by looplife55** [comment]
Waiting for reply want to setup my rig

**Comment by looplife55** [comment]
root@jusval-3:~/xmrig# git checkout beta
error: Your local changes to the following files would be overwritten by checkout:
        src/config.json
Please commit your changes or stash them before you switch branches.
Aborting
root@jusval-3:~/xmrig#

**Comment by looplife55** [comment]
Any method to updated xmrig to random/wow version in ubuntu wait for your answer

**Comment by xmrig** [comment]
git contains only source, you need make a binary from it via `cmake` and `make` as usual.

**Comment by looplife55** [comment]
Yup!! Solve
