### ISSUE TITLE
xmrig-2.99.2-beta Algo-rx/loki dont work anymore (under WIN)

### ISSUE THREAD

**Issue by Cideg** [xmrig/xmrig#1082]
hello together, with the new update, the algo rx / loki no longer works under win.

the following error message is displayed:
incompatible / disabled algorithm rx / loki detected, reconnect

many thanks

**Comment by xmrig** [comment]
Please show:

1. First lines from miner start.
2. Config file, without wallets.

Thank you.

**Comment by xmrig** [comment]
Seems this issue happen because autoconfig fails, but I need requested above information to know why it exactly fails.
Thank you.

**Comment by Cideg** [comment]
Thank you for your prompt reply

```
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "colors": true,
    "randomx": {
        "init": -1,
        "numa": true
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "hw-aes": null,
        "priority": null,
        "asm": true,
        "cn": [],
        "cn-heavy": [],
        "cn-lite": [],
        "cn-pico": [],
        "cn/gpu": [],
        "rx": [],
        "rx/wow": [],
        "cn/0": false,
        "cn-lite/0": false
    },
    "donate-level": 1,
    "donate-over-proxy": 1,
    "log-file": null,
    "pools": [
        {
            "algo": null,
            "url": "167.86.103.145:3993",
            "user": "",
            "pass": "x",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "user-agent": null,
    "watch": true
}
```

First lines miner:
[](https://ibb.co/YfFY6HF)

**Comment by xmrig** [comment]
Can you download **hwloc-win64-build-1.11.13.zip** from https://www.open-mpi.org/software/hwloc/v1.11/ and run `lstopo.exe topo.xml` then share resulting `topo.xml` somehow.
Thank you.

**Comment by xmrig** [comment]
Fixed, binaries for this fix https://download.xmrig.com/xmrig/2.99.3-evo/6b3b1c3fc412981e51892bafd62b3dc4c1f87e7d/
`cpu` object in config should be removed to allow autoconfig fill it again.
Thank you.

**Comment by xmrig** [comment]
v2.99.3-beta released https://github.com/xmrig/xmrig/releases/tag/v2.99.3-beta
