### ISSUE TITLE
is it possible to create Standalone Xmrig.exe without config.json

### ISSUE THREAD

**Issue by tabish2112** [xmrig/xmrig#109]
hi
I want to make xmrig.exe without config file, means all the settings in predefined xmrig once it started it should mine through predefined configs, is it possible to do so as i am newbie please guide

**Comment by quartz010** [comment]
try to read the sourcecode

**Comment by calvintam236** [comment]
I think you can fork, edit those default values, and compile yourself. Otherwise, I would recommend using docke. I build docker images for miners and deployed it with my rigs.
