### ISSUE TITLE
Unknown/unsupported algorithm "(null)" detected - minexmr.com

### ISSUE THREAD

**Issue by derWahnsinn** [xmrig/xmrig#1098]
hi, having the problem that I can't connect to minexmr pool anymore. 

I'm running the current beta version **xmrig-2.99.4-beta-xenial-x64** without any special options and with hugepages activated

> [pool.minexmr.com:4444] Unknown/unsupported algorithm "(null)" detected, reconnect
> [pool.minexmr.com:4444] login error code: 6

the last working version for me is **xmrig-2.16.0-beta**

did I miss something?

thanks in advance

**Comment by xmrig** [comment]
#1066 This pool not support algorithm negotiation, so now you must specify algo option with value `cn/r`.
Thank you.

**Comment by derWahnsinn** [comment]
thanks very much!

**Comment by BigHuncho** [comment]
hello can anyone help me i am having the same problem still after i added `"cn/r"`
