### ISSUE TITLE
Compile for android 

### ISSUE THREAD

**Issue by losiel** [xmrig/xmrig#11]
Hi,
Is It possible to compile xmrig for android ?

Thanks a lot.

**Comment by losiel** [comment]
Any idea !?

**Comment by xmrig** [comment]
No it not possible at this moment. Mining part heavy optimized for x86 SSE2 and AES-NI instructions. No ARM CPUs supported.

For curiosity what user interface should be? Some android interface + native part in APK file or something else, because now only console interface available.

**Comment by tsudmi** [comment]
Is there in plans to support ARM CPUs or are there any updates on running the miner on Android?

**Comment by tsudmi** [comment]
@xmrig ?

**Comment by xmrig** [comment]
Plans https://github.com/xmrig/xmrig/issues/106 I added ARM to the list.
ARM would be nice, but it not scheduled at this moment.
Thank you.

**Comment by JuniorJPDJ** [comment]
I successfully run it in Linux Deploy app on android, If someone here is able to compile it with android sdk, please, show me how :<

**Comment by talobin** [comment]
@xmrig with this commit
https://github.com/xmrig/xmrig/commit/aa4f8b6fa78eb8331b5927ba5315b926ac75ce9c
Can we now compile for Android?
Could you give us some instruction to cross-build for Android?
Thank you so much

**Comment by cmorsucci** [comment]
Need instruction to compile for android.. pls

**Comment by btx3** [comment]
I haven't been successful with cross-compilation, but compiling on the phone worked flawlessly with [Termux](https://play.google.com/store/apps/details?id=com.termux). If you have a 64-bit Android device (run `uname -m` - if it says `aarch64` you do), I have a precompiled version of XMRig on my repo (I'll add 32-bit soon). Just run

`echo "deb [trusted=yes] http://188.226.188.252:9999 termux extras" >> $PREFIX/etc/apt/sources.list && apt update`

in the Termux shell. This will let you simply run `apt install xmrig` and use it normally.
If you want to compile it yourself, run the following commands in Termux:

```
apt update
apt upgrade
apt install clang libuv-dev cmake git
git clone https://github.com/xmrig/xmrig
mkdir xmrig/build
cd xmrig/build
cmake .. -DWITH_HTTPD=OFF
make
```

You can append `-j` to the `make` command to compile faster, but on some older phones I've tested it froze up the OS until the build was completed.

**Comment by cmorsucci** [comment]
Thank you ! Could you provide the list of commands you launched in Termux to get this compiled version?

**Comment by btx3** [comment]
> Could you provide the list of commands you launched in Termux to get this compiled version?

This version was compiled with the same commands above, but it's just a packaged in a .deb file (created using `termux-create-package`) with the binary inside.

**Comment by H3avyus3r** [comment]
+1 32-bit, Appreciated!

**Comment by Holmgrenstefan** [comment]
Works om Huawei p9plus not Sony Experia m2 as it is armv71

**Comment by btx3** [comment]
Just to let you all know, someone made a reddit post with both the 32 and 64-bit versions [here](https://www.reddit.com/r/MoneroMining/comments/7qcu93/mining_on_android_64_bit_or_32_bitxmrig/).

**Comment by H3avyus3r** [comment]
Thanks so much for that update!
