### ISSUE TITLE
Starting 

### ISSUE THREAD

**Issue by TenchuA** [xmrig/xmrig#110]
Hi,

I pretty new when it's about to write the file to run the miner.
Until now I just used NiceHash and CCMINER.
I wanted to try this XMRIG and I don't know how to start since windows tell me that XMRIG.EXE can't be found.
Any one of you would have the patience to explain me? mining without understanding does not interest me I'd like to learn.

thank people who would try to help me.

**Comment by klobymoby** [comment]
Windows defender delete that file.

**Comment by TenchuA** [comment]
Thank you,

I tried the CPU and GPU version and I am surprised my hash rate is around 55% lower for CPU than nice hash and the GPU 40% lower than CCminer.

**Comment by 2010phenix** [comment]
klobymoby, interesting what part of code used for detect Windows defender?
