### ISSUE TITLE
--max-cpu-usage issue

### ISSUE THREAD

**Issue by CapitolDev** [xmrig/xmrig#1100]
using
`xmrig.exe --url=pool.supportxmr.com:5555 --user=#replaceme1 --pass=#replaceme2 --threads=5 --cpu-priority=5 --max-cpu-usage=80 --donate-level=0%`

but getting
`xmrig.exe: unknown option -- max-cpu-usage=80`

**Comment by klamas1** [comment]
Problem probably due --donate-level=0%
;)

**Comment by xmrig** [comment]
Option `--max-cpu-usage` was deprecated and now removed.
Thank you.
