### ISSUE TITLE
2.99.x-evo api hugepages

### ISSUE THREAD

**Issue by doadin** [xmrig/xmrig#1106]
console shows huge pages 4/4 100% but web api shows hugepages: false, .

```
    "cpu": {
        "enabled": true,
        "huge-pages": true,
```

in config

**Comment by xmrig** [comment]
Huge pages in complicated thing now, it not just true or false, actual huge pages information can be found in `GET /2/backends` as 2 numbers for example:
```json
"hugepages": [1184, 1184],
```
First number is huge pages count, second is total pages count, in this example 100% of huge pages allocated, I did't make final decision about this information in `GET /1/summary` endpoint, so it always false now.
Thank you.

**Comment by xmrig** [comment]
Fixed, old endpoint `/1/summary` returns `true` if 100% of hugepages obtained, new endpoint `/2/summary` returns it as 2 numbers.
Thank you.

**Comment by doadin** [comment]
sounds like a good solution, thanks for that and the quick response.

**Comment by xmrig** [comment]
v2.99.5-beta released https://github.com/xmrig/xmrig/releases/tag/v2.99.5-beta
