### ISSUE TITLE
Argon2id support for trtl

### ISSUE THREAD

**Issue by ibrahimk157** [xmrig/xmrig#1107]
Hello,

I’m not sure if someone has already opened up an issue about this (I don’t see myself trying to look for such a post). 

Is argon2id support being worked on? I want the official xmrig to support it, I don’t want to use any forks.

Thanks

**Comment by bobbieltd** [comment]
+1 For both Argon2id Turtlecoin Chukwa and Chukwa variant WRKZ (Chukwa lite, currently ~ 2Mh/s nethash)

**Comment by xmrig** [comment]
I'm not sure, new algorithm is not cryptonight variant and not RandomX variant.
Thank you.

**Comment by brandonlehmann** [comment]
Here's where we've added support, although I'm sure there is a better way, in the TurtleCoin fork of xmrig: https://github.com/turtlecoin/trtlrig/commit/76ae2e503dfc7596519ed7528d11576d5494d435

**Comment by xmrig** [comment]
Any test pool available for it? with testnet wallet address (if required).
Thank you.

**Comment by ibrahimk157** [comment]
brandonlehmann I’m trying to avoid using a fork for several reasons:
1) More likely to be abandoned compared to using the real deal
2) Might have reduced performance 
3) Might be less secure

**Comment by ibrahimk157** [comment]
xmrig i heard they’ve got a argon2id test in the dev branch of the turtlecoin repo. (To see how your setup might perform with the new algo). Maybe try seeing what pool they’re using there?

**Comment by TurtleCoinCash-dev** [comment]
@ibrahimk157 the linked commit wasn’t for you :) 

#1: unlikely, as this is how we test to make sure that is possible to do pool miners before PoW forks
#2: plausible — it’s known that the arm argon2id work needs help
#3: review commit logs, always. Changes are transparent and open.

**Comment by fadatsai** [comment]
testnet
publicnode.ydns.eu:3420
 wallet address
TRTLuyJXVc9Ma7ffSaYQAGbkwf2LY2g8gHr2RdYDYiqyFrUtACmATLJGrs1pgd6mudft6uUMwdm2zWMo74P9bWKh6zjKFufhvGE

**Comment by xmrig** [comment]
@fadatsai `[publicnode.ydns.eu:3420] error: "invalid address used for login", code: -1`.

**Comment by xmrig** [comment]
Scheduled for v3.1 (next minor release), algorithm name will be `argon2/chukwa`, I still have bad feelings about it, many coins want own miners and Turtlecoin is not exception, but I got a lot of requests for support it, so lets add second non-cryptonight algorithms family.

**Comment by ibrahimk157** [comment]
Thank you so much! I wanted this badly and you added support for it at an extremely fast rate! I really cannot thank you enough ❤️

**Comment by bobbieltd** [comment]
Cool 👍👍👍. Thanks. xmrig number one !

**Comment by L1LjSHX** [comment]
Thanks :3

**Comment by xmrig** [comment]
Argon2 ready in dev branches for CPU miner and proxy, I will make release in 1 or 2 days.

### Notes
* Algorithm names: `argon2/chukwa` and `argon2/wrkz`.
* Config file is compatible with v3.0, miner will add new CPU profile with name `argon2`.
* Auto-configuration usually will use all available threads, because of small memory requirements of selected algorithm params.
* Algorithm switch on fork will work only if pool support algorithm negotiation, so if you not use https://turtle.hashvault.pro/en/ please contact to your pool support.

**Comment by bobbieltd** [comment]
Ohhhhhh yeahhhhhh ! Thanks xmrig 👍👍👍

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v3.1.0
https://github.com/xmrig/xmrig-proxy/releases/tag/v3.1.0

**Comment by ibrahimk157** [comment]
YESSSSS!!!!! THANK YOU SOOOO MUCH!!!!
