### ISSUE TITLE
Build error when disable WITH_AEON (dev branch)

### ISSUE THREAD

**Issue by yoyohip** [xmrig/xmrig#111]
Hi,
error occured.
    return memcmp(output, algo == Options::ALGO_CRYPTONIGHT_LITE ? test_output1 : test_output0, (Options::i()->doubleHash() ? 64 : 32)) == 0;

Thank you.

**Comment by xmrig** [comment]
I fixed it. Thank you.

**Comment by yoyohip** [comment]
Thank you!
