### ISSUE TITLE
 microhttpd NOT found: use `-DWITH_HTTPD=OFF` to build without http deamon

### ISSUE THREAD

**Issue by rainbow520lxr** [xmrig/xmrig#1112]
microhttpd NOT found: use `-DWITH_HTTPD=OFF` to build without http deamon

**Comment by xmrig** [comment]
Install dev package for libmicrohttpd (if you use Linux) or try v2.99 (beta or evo branch) it will be v3.0 release on next week and not require libmicrohttpd.
Thank you.
