### ISSUE TITLE
error: ‘hwloc_get_numanode_obj_by_os_index’ was not declared in this scope

### ISSUE THREAD

**Issue by duku1** [xmrig/xmrig#1115]
Hello. I try compile xmrig on CentOS 6. Use gcc 6.3 or 7.2 but got same result: 
`[ 87%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/rx/Rx.cpp.o /xmrig/src/crypto/rx/Rx.cpp: In function ‘void xmrig::bindToNUMANode(uint32_t)’: /xmrig/src/crypto/rx/Rx.cpp:68:24: error: ‘hwloc_get_numanode_obj_by_os_index’ was not declared in this scope hwloc_obj_t node = hwloc_get_numanode_obj_by_os_index(topology, nodeId); ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ /xmrig/src/crypto/rx/Rx.cpp:68:24: note: suggested alternative: ‘hwloc_get_pu_obj_by_os_index’ hwloc_obj_t node = hwloc_get_numanode_obj_by_os_index(topology, nodeId); ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ hwloc_get_pu_obj_by_os_index At global scope: cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’ make[2]: *** [CMakeFiles/xmrig.dir/build.make:2415: CMakeFiles/xmrig.dir/src/crypto/rx/Rx.cpp.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/xmrig.dir/all] Error 2 make: *** [Makefile:84: all] Error 2`

**Comment by xmrig** [comment]
Probably hwloc version is too old, minimum tested version is 1.10.0.
You have 2 options:
1. Build without hwloc support, cmake option `-DWITH_HWLOC=OFF`.
2. Somehow get new hwloc version, for example build from it source https://github.com/xmrig/xmrig/issues/1099#issuecomment-518089405
