### ISSUE TITLE
Is it wrong with me?

### ISSUE THREAD

**Issue by Vip4pt** [xmrig/xmrig#1119]
![image](https://user-images.githubusercontent.com/21324892/63182069-38a40480-c084-11e9-9786-d3a227ec0ced.png)
![image](https://user-images.githubusercontent.com/21324892/63182080-3c378b80-c084-11e9-92ea-0efd1bb8f952.png)
Version 3.0 has low computing power and the same configuration

**Comment by xmrig** [comment]
This is virtual or physical machine?
Thank you.
