### ISSUE TITLE
What is the best GCC compiler and compiler options for compiling XMrig 3.0.0

### ISSUE THREAD

**Issue by kio3i0j9024vkoenio** [xmrig/xmrig#1124]
As seen in another issue:
https://github.com/xmrig/xmrig/issues/1122#issuecomment-522254002

using the compiler option "-funroll-loops" speeds up BLAKE2b by 40%.

So my question is what is the best GCC compiler to use for compiling XMrig 3.0.0?

and what are the best compiler options to use?

Obviously I am looking to have the fastest XMrig RandomX implementations on my various rigs:

Opteron 63xx Servers, HP Xeon 8837 Servers, etc

**Comment by xmrig** [comment]
Whole Argon2/Blake2 not performance critical as it answered, in upcoming v3.1.0 Argon2 added as standalone algorithm with up to AVX512F optimizations #1107 but RandomX still use old/reference implementation, also use AVX2 for RandomX might be bad idea https://software.intel.com/en-us/forums/intel-isa-extensions/topic/710248 also compiler version is not important too.
Thank you.

**Comment by kio3i0j9024vkoenio** [comment]
What about compiler options?

If using the compiler option "-funroll-loops" speeds up BLAKE2b by 40% doesn't that mean that certain options can improve RandomX?

**Comment by xmrig** [comment]
You can add it here https://github.com/xmrig/xmrig/blob/master/cmake/flags.cmake#L18 but if blake2b will get 200% (any number here) speedup it's still nothing, it not performance critical part of algorithm.

**Comment by kio3i0j9024vkoenio** [comment]
Doing "-funroll-loops" speeds up 4x Xeon E7-8837's by 200 H/s which is a gain of 2.3%.
On 4x Opteron 6387's there is no change.
