### ISSUE TITLE
wrong cpu info with xeon e3-1240 under windows

### ISSUE THREAD

**Issue by NmxMilk** [xmrig/xmrig#113]
First, let me congratulate you on the excellent work your doing and for sharing it!

I was user xmr-stak on my xeon e3-1240 and was getting 270 H/s.
Today i gave xmrig a chance to see if i get better performance but seems difficult to do more than that.

By the way, Xmrig was giving the wrong number of sockets and L2/L3 cache info (all zero in fact).
After investigating with libcpuid, it gives:
  num_cores  : 4
  num_logical: 8
  tot_logical: 4
The CPU is really 8 threads but hyper-threading is disabled under windows.
Taskmanager shows only four logical processors.

The problem seems to come from the fact that your deducing the number of sockets by :  tot_logical/ num_logical.
I suggest adding the following line after line 112 in cpu.cpp:
if (m_sockets == 0) m_sockets = 1; // at least one !

Thanks again

**Comment by xmrig** [comment]
Closed #86
