### ISSUE TITLE
xmrig-notls what is this process and why is it taking up all my CPU?

### ISSUE THREAD

**Issue by hybmg57** [xmrig/xmrig#1130]
I have this process xmrig-notls which is owned by Plesk.

I'm not sure why this is taking up more than 100% of my CPU resources for a few days now.
```
psaadm    20   0  461440   5188    800 S 111.3  0.1  12246:26 xmrig-notls
```

Does anyone know what it is and how I can manage this so it doesn't take up all my resources?

**Comment by qutimqqcom** [comment]
if the software is not installed by you, use an antivirus

if other read manual

**Comment by rjacksix** [comment]
It is a cryptocurrency miner.  It has probably been dropped on your box by a bot.  Check your crontab for a base64 encoded job that is responsible for persistence.

Hope this helps

Happy hunting

**Comment by jangondol** [comment]
FYI (for those coming here through web search): https://hub.docker.com/_/redis?tab=reviews (see the description of the infection through the official Redis Docker container and info about the fix).
