### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by vergotle** [xmrig/xmrig#1132]
Hi

When compiling Xmrig 3.1.0 on Centos 7 using Cmake v3, the compiler exits with the following error

/tmp/xmrig-3.1.0/src/crypto/randomx/reciprocal.c: In function ‘randomx_reciprocal’:
/tmp/xmrig-3.1.0/src/crypto/randomx/reciprocal.c:57:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (uint64_t bit = divisor; bit > 0; bit >>= 1)
  ^
/tmp/xmrig-3.1.0/src/crypto/randomx/reciprocal.c:57:2: note: use option -std=c99 or -std=gnu99 to compile your code
/tmp/xmrig-3.1.0/src/crypto/randomx/reciprocal.c:60:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (unsigned shift = 0; shift < bsr; shift++)

**Comment by TheCHIM** [comment]
I confirm, I have the same error!

**Comment by CyberMix** [comment]
Me to

**Comment by srax47** [comment]
Same error here

**Comment by xmrig** [comment]
Compiler version? `gcc -v`

**Comment by xmrig** [comment]
Fixed in dev branch.
