### ISSUE TITLE
3.1.0 how to set CPU usage？

### ISSUE THREAD

**Issue by expressups** [xmrig/xmrig#1139]
"max-cpu-usage": 50,
How should arrays be set？

**Comment by xmrig** [comment]
You can change threads count in cpu object https://github.com/xmrig/xmrig/blob/master/doc/CPU.md
Main reason why this option removed is most of users don't ever understand how this option works (or not works), but likely this option will come back with new less confusing name, together with OpenCL backend.
Thank you.

**Comment by expressups** [comment]
My usage scenarios are more complex, maybe multi-core cpus, maybe multiple cpus, and I try to set up threads, but it doesn't always work well. You can add a friendlier option.

**Comment by qutimqqcom** [comment]
its works  well 
        "cn/r":{
            "intensity": 1,
            "threads": 48,
            "affinity": -1
            },

**Comment by qutimqqcom** [comment]
so  need  set up cpu usage  whitout  set number of threads
hardware  has different   cpu  units

"max-cpu-usage": 50  or other precent,
still   best chalange

**Comment by shubell** [comment]
Well this option was a necessity for my environment where i have different a different cpu on every rig and have one startup script for everyone.

**Comment by MrCook1es** [comment]
@xmrig 

I always use 50% on different systems and it works well.
For me it is fundamental to use a percentage value, so as not to have to personalize each combination by setting the number of threads by hand.

What parameter should I set in the new config.json file layout to have 50% CPU usage?

**Comment by CrazyBoyFeng** [comment]
if you are using multi-core cpu, maybe set the affinity mask of xmrig.exe process can help you.

on windows:
`start /affinity 0xAAAAAAAAAAAAAAAA xmrig.exe`
`0xA` is the hex form of binary `1010`, it means just use the 2nd and 4th core for the process. so the command above means only use half of my cores.
i dont know how many cores you have. i have 64, so i need 64 bits mask (16 hex digits "A") for the mask.

on linux please 'man taskset' or 'taskset -h'

**Comment by xmrig** [comment]
`max-cpu-usage` option reverted back in v4.2 with new name, please read docs carefully https://github.com/xmrig/xmrig/blob/beta/doc/CPU_MAX_USAGE.md
