### ISSUE TITLE
v3.1.0 is not using latest RandomX code change CBRANCH #118

### ISSUE THREAD

**Issue by kio3i0j9024vkoenio** [xmrig/xmrig#1143]
RandomX code was changed on 8/27/2019 and may effect the hashrate of Intel/AMD CPUs.

Increase the frequency of CBRANCH #118
https://github.com/tevador/RandomX/pull/118

**Comment by xmrig** [comment]
Pull request not merged yet.
Thank you.

**Comment by SChernykh** [comment]
#1142 has this change

**Comment by kio3i0j9024vkoenio** [comment]
As SChernykh has stated #1142 has this change along with Optimized RandomX JIT compiler.

Updated and optimized RandomX #1142
https://github.com/xmrig/xmrig/pull/1142

I look forward to testing XMrig with these changes.

**Comment by kio3i0j9024vkoenio** [comment]
Implemented in XMrig V3.1.1

https://github.com/xmrig/xmrig/releases/tag/v3.1.1
