### ISSUE TITLE
how to ? multiply pools definition and priority 

### ISSUE THREAD

**Issue by qutimqqcom** [xmrig/xmrig#1145]
need example

**Comment by xmrig** [comment]
Only failover strategy supported, first pool is primary.
Thank you.

**Comment by qutimqqcom** [comment]
where  can i read about  failover  strategy   describe

    "retries": 5,
    "retry-pause": 5,

change  pool,   if come back  switch  to  primary,    if down switch   secondary
where   end of  cycle ?
