### ISSUE TITLE
ubuntu 16.04 8 gb ram

### ISSUE THREAD

**Issue by zhekafun** [xmrig/xmrig#1151]
[2019-08-30 09:41:11.639]  cpu  use argon2 implementation XOP
[2019-08-30 09:41:11.639]  cpu  use profile  argon2  (6 threads) scratchpad 512 KB
[2019-08-30 09:41:11.647]  cpu  READY threads 6(6) huge pages 0/6 0% memory 3072 KB (8 ms)

memory freed
hugepages enabled by sysctl -w vm.nr_hugepages=128

**Comment by xmrig** [comment]
Please show output for `cat /proc/meminfo | grep HugePages`.
Thank you.

**Comment by zhekafun** [comment]
cat /proc/meminfo | grep HugePages
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0

**Comment by xmrig** [comment]
`HugePages_Total` and `HugePages_Free` should be 128, `sysctl -w vm.nr_hugepages=128` for some reason not applied.

**Comment by zhekafun** [comment]
solved runned enabler without su privs
