### ISSUE TITLE
Embedded config unable to open "/xmrig/build/config.json"

### ISSUE THREAD

**Issue by stinkefisch** [xmrig/xmrig#1152]
Hi,
I have updated /xmrig/src/core/config/Config_default.h with my config and compile via 
cmake .. -DWITH_HTTPD=OFF -DWITH_EMBEDDED_CONFIG=ON

However when I start xmrig it gives me
unable to open "/xmrig/build/config.json"

**Comment by xmrig** [comment]
Miner first try load external config if it fails, used embedded config.
Thank you.

**Comment by stinkefisch** [comment]
Thanks for the reply,

I haven't got external config why is it still failing and not using the embedded one ?

**Comment by xmrig** [comment]
If you like disable external config and remove warning, you should remove this line https://github.com/xmrig/xmrig/blob/master/src/base/kernel/Base.cpp#L109 but why embedded one not used I can't say, are you sure config valid?
Thank you.

**Comment by stinkefisch** [comment]
No problems, just me.
Config was wrong
Thanks
