### ISSUE TITLE
hwloc issue

### ISSUE THREAD

**Issue by xday3** [xmrig/xmrig#1159]
I tried to compile xmrig static - cmake .. -DUV_LIBRARY=/usr/local/lib/libuv.a -DBUILD_STATIC=-ON

 * ABOUT        XMRig/3.1.1 gcc/5.4.0
 * LIBS         libuv/1.31.1-dev hwloc/1.11.2
 * CPU          Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz (1) x64 AES
                L2:0.0 MB L3:0.0 MB 2C/2T NUMA:1
 * DONATE       5%
 * ASSEMBLY     auto:intel
 * POOL #1      104.140.201.42:80:3333 algo cn/r
 * COMMANDS     hashrate, pause, resume
[2019-09-03 19:17:03.169] use pool 104.140.201.42:80  104.140.201.42
[2019-09-03 19:17:03.169] new job from 104.140.201.42:80 diff 10000 algo cn/r height 1915339

The problem what I got is, when I am using my miner to another machine I got this error:
./xmrig-notls: error while loading shared libraries: libhwloc.so.5: cannot open shared object file: No such file or directory

Can anyone know how can I fix it?

**Comment by xday3** [comment]
Any update :)

**Comment by trasherdk** [comment]
You need to compile a static libhwloc from source.

**Comment by xmrig** [comment]
You have 2 options:
1. Use own hwloc build https://github.com/xmrig/xmrig/issues/1099#issuecomment-518089405 (better option)
2. Disable it `-DWITH_HWLOC=OFF`

Please note hwloc may not work well in virtual environment, zero cache detected `L2:0.0 MB L3:0.0`
Thank you.

**Comment by trasherdk** [comment]
@xmrig VirtualBox 6.0.10 guest, running Slackware 14.2
```
 * ABOUT        XMRig/3.1.0 gcc/5.5.0
 * LIBS         libuv/1.23.2 OpenSSL/1.0.2s hwloc/1.11.0
 * CPU          Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz (1) x64 AES
                L2:1.0 MB L3:32.0 MB 4C/4T NUMA:1
 * DONATE       1%
 * ASSEMBLY     auto:intel
 * POOL #1      localhost:8000 algo cn/r
 * COMMANDS     hashrate, pause, resume
[2019-09-04 02:59:47.865] use pool localhost:8000  127.0.0.1
[2019-09-04 02:59:47.868] new job from localhost:8000 diff 1000 algo cn/r height 1291897
[2019-09-04 02:59:47.868]  cpu  use profile  cn  (4 threads) scratchpad 2048 KB
[2019-09-04 02:59:48.745]  cpu  READY threads 4(4) huge pages 4/4 100% memory 8192 KB (876 ms)
[2019-09-04 02:59:52.876] accepted (1/0) diff 1000 (98 ms)
[2019-09-04 03:00:03.363] accepted (2/0) diff 1000 (169 ms)
[2019-09-04 03:00:09.688] accepted (3/0) diff 1000 (190 ms)
[2019-09-04 03:00:10.983] Ctrl+C received, exiting
[2019-09-04 03:00:11.025]  cpu  stopped (41 ms)
```
Looks OK to me :)

**Comment by kio3i0j9024vkoenio** [comment]
LIBS libuv/1.23.2 OpenSSL/1.0.2s hwloc/1.11.0

You will get terrible hash rates with hwloc v1.11.0.

You need at least V2.0.4

wget https://download.open-mpi.org/release/hwloc/v2.0/hwloc-2.0.4.tar.gz
tar xvzf hwloc-2.0.4.tar.gz

cd hwloc-2.0.4

sudo apt install autoconf
sudo apt install libtool-bin

Note that GNU autoconf >=2.63, automake >=1.11 and Libtool >=2.2.6 are required when building from a Git clone.

autoconf -V
automake --version
libtool --version

./configure

make
sudo make install

**Comment by xday3** [comment]
Thank you very much for your helps, finally I compiled my miner fully static with hwloc 2.0 and libuv.

**Comment by RizkiRama99** [comment]
This is the way http://bit.ly/364s24H

**Comment by zrayburn** [comment]
This can also be fixed using the apt package manager.
`sudo apt install hwloc`
I don't know if this library is present in other package managers but it worked for me.

**Comment by TheColetrain** [comment]
`sudo apt install hwloc` is a winner

**Comment by SteaceP** [comment]
I build it on Ubuntu 20.04.2 but transfered it to many more PCs with also Ubuntu 20.04.2
It would start for the same reason
just install this:
`sudo apt-get install libhwloc-dev`
on the other PCs and good to go
