### ISSUE TITLE
Error using v3.1.1!

### ISSUE THREAD

**Issue by ttsite** [xmrig/xmrig#1161]
* ABOUT        XMRig/3.1.1 MSVC/2017
 * LIBS         libuv/1.31.0 OpenSSL/1.1.1c hwloc/2.0.4
 * HUGE PAGES   permission granted
 * CPU          Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz (2) x64 AES
                L2:0.5 MB L3:16.0 MB 4C/4T NUMA:1
 * DONATE       5%
 * ASSEMBLY     auto:intel
 * POOL #1      pool.minexmr.com:7777 algo auto
 * COMMANDS     hashrate, pause, resume
[2019-09-04 08:44:56.489] [pool.minexmr.com:7777] Unknown/unsupported algorithm
"(null)" detected, reconnect
[2019-09-04 08:44:56.493] [pool.minexmr.com:7777] login error code: 6
[2019-09-04 08:45:02.536] [pool.minexmr.com:7777] Unknown/unsupported algorithm
"(null)" detected, reconnect
[2019-09-04 08:45:02.544] [pool.minexmr.com:7777] login error code: 6

**Comment by xmrig** [comment]
You must specify `-a cn/r` or `"algo": "cn/r"` in pools object.
Thank you.

**Comment by xday3** [comment]
Add in your config "algo": "cn/r" if you are mining xmr...if not try o use the correct algo

**Comment by xmrig** [comment]
#1160

**Comment by ttsite** [comment]
Thank you! We have solved the problem as you said.
