### ISSUE TITLE
Does v3.1.1 support the latest XMR algorithm in October?

### ISSUE THREAD

**Issue by ttsite** [xmrig/xmrig#1162]
Whether v3.1.1 supports the latest algorithm of XMR in October! If we use the updated algorithm in October now, do we need to reconfigure it? Can we switch to the new algorithm automatically as before? Thank you!

**Comment by xmrig** [comment]
Final decision not made yet, algorithm may change or may not, status of this in unknown.

Miner can switch algorithm automatically if pool support algorithm negotiation (supportxmr.com right now not support it), whole v3 designed for easy switching between very different algorithms.
Thank you.
