### ISSUE TITLE
macOS static build ?!

### ISSUE THREAD

**Issue by furiousteam** [xmrig/xmrig#1165]
I'm trying to make a static build for macOS using the following command:

cmake .. -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2s -DBUILD_STATIC=ON -DUV_INCLUDE_DIR=/usr/local/Cellar/libuv/1.31.0/lib/

also tried this:

cmake .. DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2s -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl/1.0.2s/lib -DBUILD_STATIC=ON -DUV_INCLUDE_DIR=/usr/local/Cellar/libuv/1.31.0 -DUV_LIBRARY=/usr/local/Cellar/libuv/1.31.0/lib/libuv.a

But i get the following error after 100% at compile:

ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [xmrig] Error 1
make[1]: *** [CMakeFiles/xmrig.dir/all] Error 2
make: *** [all] Error 2

CMakeError.log:
[CMakeError.log](https://github.com/xmrig/xmrig/files/3588225/CMakeError.log)

Thank you.

**Comment by djfinch** [comment]
OSX version? Xcode version?
It's linker issue. I was not able to build miner with Xcode's Clang but used Homebrew's one and build passing. Currently on Elcap with X8 & llvm7, unable to install llvm9. Also, do not use absolute paths for libs --> use symlinks created by Homebrew instead...

`cmake .. -DUV_LIBRARY=/usr/local/lib/libuv.a -DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl/lib/libssl.a -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl/lib/libcrypto.a -DCMAKE_C_COMPILER=/usr/local/Cellar/llvm/7.0.0/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/Cellar/llvm/7.0.0/bin/clang++`

**Comment by xmrig** [comment]
Also please check new build docs https://xmrig.com/docs/miner/macos-build custom static build required only for hwloc.
Thank you.

**Comment by ZeppLu** [comment]
I tried to link statically to brew's `libhwloc.a`, and finally come up with this configuration:

```
LDFLAGS="-framework OpenCL $(xml2-config --libs)" cmake .. -DOPENSSL_ROOT_DIR=$(brew --prefix openssl) -DHWLOC_INCLUDE_DIR=$(brew --prefix hwloc)/include -DHWLOC_LIBRARY=$(brew --prefix hwloc)/lib/libhwloc.a
```
