### ISSUE TITLE
-t parameter is not work

### ISSUE THREAD

**Issue by mike2001** [xmrig/xmrig#1167]
hello,my cpu have 6 cores 12 threads ,i set the -t 6 in command line.  but it always work in 12 threads.

**Comment by xmrig** [comment]
Please show miner output and command line.
Thank you.

**Comment by mike2001** [comment]
![image](https://user-images.githubusercontent.com/4592658/64746660-11cfd580-d53f-11e9-9232-be946a26fb08.png)

**Comment by xmrig** [comment]
This bug already fixed in v3.1.1 and special thanks for donation.
