### ISSUE TITLE
Libuv library dependency

### ISSUE THREAD

**Issue by erotavlas85** [xmrig/xmrig#117]
Hi,
I know that xmrig requires libuv library in order to be built. I successfully compiled libuv with msys2 and autotools and with standard method with MSVC compiler as suggested by the maintainers [here](https://github.com/libuv/libuv).
However, in both cases I get some errors during the make check/test phase as I reported [here](https://github.com/libuv/libuv/issues/1549). 
I do not know if I have to care about such errors. What method do you use?
Thank you

**Comment by NmxMilk** [comment]
Well, if you run xmrig and get good results you can !
It is though good reflex to have signaled your problems to the libuv dev team.
