### ISSUE TITLE
CL_BUILD_PROGRAM_FAILURE

### ISSUE THREAD

**Issue by Wacholek** [xmrig/xmrig#1177]
Any hint about what is wrong?
[CL_BUILD_PROGRAM_FAILURE](https://github.com/xmrig/xmrig/files/3625614/ERROR.txt)

2x HD6990 Windows 7 Catalyst 14.4
RandomX algo.

**Comment by xmrig** [comment]
Fixed in evo branch, but this GPU will be very slow, JIT mode not implemented.
Thank you.

**Comment by Wacholek** [comment]
> Fixed in evo branch, but this GPU will be very slow, JIT mode not implemented.
> Thank you.
I am aware of the low speed. I have several that kind of rigs. I will be more profitable to mine on CPU but those card are there and can mine something. 
I cannot test how slow it would because, I cannot run the miner.

**Comment by Wacholek** [comment]
Using xmrig v4.5.0 I get this:
[2019-11-03 17:46:45.371]  ocl  error CL_INVALID_KERNEL_NAME when calling clCrea
teKernel for kernel fillAes1Rx4_scratchpad
[2019-11-03 17:46:45.373]  ocl  thread #1 failed with error CL_INVALID_KERNEL_NAME

The same system and drivers as before.
