### ISSUE TITLE
Debian cmake error

### ISSUE THREAD

**Issue by MarcCrams** [xmrig/xmrig#1186]
cmake ..
-- Use ARM_TARGET=7 (armv7l)
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find HWLOC (missing: HWLOC_LIBRARY HWLOC_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindHWLOC.cmake:25 (find_package_handle_standard_args)
  src/backend/cpu/cpu.cmake:29 (find_package)
  src/backend/backend.cmake:1 (include)
  CMakeLists.txt:29 (include)

-- Configuring incomplete, errors occurred!
See also "/home/pi/xmrig/build/CMakeFiles/CMakeOutput.log".

**Comment by xmrig** [comment]
Disable hwloc by `-DWITH_HWLOC=OFF` (for ARM it not necessary) or install or build hwloc.
Thank you.

**Comment by MarcCrams** [comment]
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/xmrig-notls.dir/build.make:1662: xmrig-notls] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/xmrig-notls.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by xmrig** [comment]
Output not contains full information, but if you compile for Android this issue might be fixed in evo branch.

**Comment by MarcCrams** [comment]
How to compile for android?
