### ISSUE TITLE
Optimized JSON config for 8th Gen i7

### ISSUE THREAD

**Issue by Xavien01** [xmrig/xmrig#1187]
So a few things. Trying to optimize a json config for the CPU ver of XMRIG. I have it down ok currently running 4 threads each assigned to the core I specified to make sure and load balance this as much as possible. Now the issue, previously I was able to use the option of the "max-cpu-usage" which I had set at 50% which would mine and not pin the CPU and make it unusable. I dont see that option in ver 4.0.1 and I have succesfully used it in the 2.15.1 with no issue. Is this no longer valid on the new ver. How can I cap the workload on. 4.0+. Lastly how many threads would u say would be the cap on an 8th gen i7 without getting too wild. Any help is appreciated, Thanks!

**Comment by xmrig** [comment]
`max-cpu-usage` option reverted back in v4.2 with new name, please read docs carefully https://github.com/xmrig/xmrig/blob/beta/doc/CPU_MAX_USAGE.md
