### ISSUE TITLE
XMRig crash when mining RandomXL (rx/loki) on ubuntu 14.04

### ISSUE THREAD

**Issue by dragelecpc** [xmrig/xmrig#1188]
Hi, I'm using xmrig (lastest release) to mine Loki on ubuntu 14.04. But the xmrig process killed after some minute. Do anyone have the same problem with me? And how can i fix it?
Thanks

**Comment by xmrig** [comment]
Please provide little more information:
1. How you build the miner, this Ubuntu version has no libuv1-dev at least.
2. Hardware information.

Better if you can obtain backtrace of crash using `gdb`.
Thank you.

**Comment by dragelecpc** [comment]
Hi, i used the Binary releases: https://github.com/xmrig/xmrig/releases
try v3.1.3, v3.1.2, v4.0 but all of them crashed after run a minute without any error (just show killed).
Do i need to install any required lib or package?

**Comment by xmrig** [comment]
Check the logs `/var/log/syslog` likely process killed by OOM killer.
Thank you.

**Comment by dragelecpc** [comment]
![failed](https://user-images.githubusercontent.com/39180136/65389583-f73cfe00-dd81-11e9-895f-97c9d313ced0.jpg)
Can you help to check it

**Comment by xmrig** [comment]
How much RAM do you have? `free -h` output, and is it virtual machine?

Disable NUMA support, it should fix the crash https://github.com/xmrig/xmrig/blob/master/src/config.json#L19 but if this is virtual machine autoconfig might wrong.

**Comment by dragelecpc** [comment]
Hi, i disabled NUMA and now the xmrig mining is working now, thank you so much

**Comment by oozmark8535** [comment]
Sir how to disable the numa i using virtual but i dont know how to edit please help thanks

**Comment by wayae222** [comment]
how to disable NUMA?

**Comment by SChernykh** [comment]
In config.json: https://github.com/xmrig/xmrig/blob/master/doc/CPU.md#numa

**Comment by Xyanc** [comment]
> Merhaba, NUMA'yı devre dışı bıraktım ve şimdi xmrig madenciliği çalışıyor, çok teşekkür ederim

How did you disable NUMA?

**Comment by Xyanc** [comment]
> Ne kadar RAM'in var? `free -h`çıktı ve sanal makine mi?
> 
> NUMA desteğini devre dışı bırakın, kilitlenmeyi düzeltmelidir https://github.com/xmrig/xmrig/blob/master/src/config.json#L19 ancak bu sanal makine ise otomatik yapılandırma yanlış olabilir.

How did you disable NUMA?
