### ISSUE TITLE
multiple pool url?

### ISSUE THREAD

**Issue by dayaki** [xmrig/xmrig#119]
Am all new to the world of crypto minning and am enjoying your software. I want to ask if I can use multiple pool, as the pool in the config file is an array, can i add multiple like this:

`"pools": [
        {
            "url": "",
            "user": "",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        },
        {
            "url": "",
            "user": "",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        }
    ]`

If possible, is there any disadvantage to using multiple pool? Will it affect my hash rate to each pool?

2. Does the value in dev donate affect my hash rate, speed or anything? Will I notice any difference if i put 1% or 10%?

Thanks for helping out.

**Comment by NmxMilk** [comment]
lo, this has already been answered. Please read #104
