### ISSUE TITLE
Is there a monero testnet server for randomX?

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig#1197]
Is there a platform where I can do monero testnet for XMRIG miner's RANDOMX?

**Comment by xmrig** [comment]
As I known no testnet pool announced yet, another hard and long way is mine against testnet daemon.
Thank you.

**Comment by snipeTR** [comment]
i love you

**Comment by snipeTR** [comment]
Can you tell the community when testnet opens?

**Comment by 2010phenix** [comment]
announcing that he had concluded testing on the private RandomX testnet successfully..... 
.... stated that the public testnet fork will likely occur at around 12:00 UTC on 27 September. Chu added

**Comment by 2010phenix** [comment]
-- testnet block Explore
https://testnet.xmrchain.net/

**Comment by xmrig** [comment]
RandomX migration guide #1204
