### ISSUE TITLE
[v4.1.0-beta] Xmrig hangs after a minute

### ISSUE THREAD

**Issue by YetAnotherRussian** [xmrig/xmrig#1199]
CPU: i3-9100F
GPU: RX570-4Gb
OS: Win10 1903

Running from cli:
xmrig.exe --donate-level 4 --no-cpu --opencl -a cn-lite/1 -o ... -u ... -p x --print-time=5

Jobs are received from pool, but no hashrate prints (all nulls) for about a minute, then driver hangs and gets restored.

AMD driver v. 19.9.2

Xmrig-AMD v2.14.6 works perfectly! Of course, w/o specific cli keys.

I checked the launch with config file, and xmrig-amd works perfectly with the same 2-thread-per-gpu config.

**Comment by xmrig** [comment]
Please show miner output from both versions.
Thank you.

**Comment by komatom** [comment]
I also couln't get it to work with my miners.. it compiles for each GPU but it doesn't actually start mining on RandomX(rx) with benchmark pool.

**Comment by xmrig** [comment]
Compile may take very long time, depends of CPU, many minutes, once it completed miner should cache compilation result for future use.

**Comment by komatom** [comment]
here is a screenshot of 8x rx580 rig.. after all the compilation completed, from time to time it mines with 12.3 hashes/s, this rig with xmrig-amd does 7300 hashes per second..

it looks like only one of the cards actually tries to mine.. driver is version 19.5.2

<img width="544" alt="rig" src="https://user-images.githubusercontent.com/42557814/65822655-906f8700-e250-11e9-89b9-a4a983995eb7.png">

**Comment by xmrig** [comment]
Please show config file, you mention you try mine RandomX, but 7300 H/s not possible on 8 rx580.
Thank you.

**Comment by komatom** [comment]
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "version": 1,
    "background": false,
    "colors": true,
    "randomx": {
        "init": -1,
        "numa": true
    },
    "cpu": {
        "enabled": false,
        "huge-pages": true,
        "hw-aes": null,
        "priority": null,
        "asm": true,
        "argon2-impl": null,
        "argon2": [0, 1],
        "cn": [
            [1, 0]
        ],
        "cn-heavy": [
            [1, 0]
        ],
        "cn-lite": [
            [1, 0],
            [1, 1]
        ],
        "cn-pico": [
            [2, 0],
            [2, 1]
        ],
        "cn/gpu": [0, 1],
        "rx": [0],
        "rx/wow": [0, 1],
        "cn/0": false,
        "cn-lite/0": false
    },
    "opencl": {
        "enabled": true,
        "cache": true,
        "loader": null,
        "platform": "AMD",
        "cn/0": false,
        "cn-lite/0": false
    },
    "donate-level": 5,
    "donate-over-proxy": 1,
    "log-file": null,
    "pools": [
        {
            "algo": null,
            "url": "randomx-benchmark.xmrig.com:7777",
            "user": "YOUR_WALLET_ADDRESS",
            "pass": "x",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "user-agent": null,
    "watch": true
}

**Comment by xmrig** [comment]
It not looks good, miner should fill `opencl` object in config, like it done in `cpu` object, I requested config for view generated result, but it missing.

**Comment by komatom** [comment]
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "version": 1,
    "background": false,
    "colors": true,
    "randomx": {
        "init": -1,
        "numa": true
    },
    "cpu": {
        "enabled": false,
        "huge-pages": true,
        "hw-aes": null,
        "priority": null,
        "asm": true,
        "argon2-impl": null,
        "argon2": [0, 1],
        "cn": [
            [1, 0]
        ],
        "cn-heavy": [
            [1, 0]
        ],
        "cn-lite": [
            [1, 0],
            [1, 1]
        ],
        "cn-pico": [
            [2, 0],
            [2, 1]
        ],
        "cn/gpu": [0, 1],
        "rx": [0],
        "rx/wow": [0, 1],
        "cn/0": false,
        "cn-lite/0": false
    },
    "opencl": {
        "enabled": true,
        "cache": true,
        "loader": null,
        "platform": "AMD",
        "cn-heavy": [
            {
                "index": 0,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 1,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 2,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 3,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 4,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 5,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 6,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 7,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            }
        ],
        "cn-lite": [
            {
                "index": 0,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 1,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 2,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 3,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 4,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 5,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 6,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 7,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [1, 2],
                "threads": [-1, -1],
                "unroll": 8
            }
        ],
        "cn-pico": [
            {
                "index": 0,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 1,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 2,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 3,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 4,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 5,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 6,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 7,
                "intensity": 1728,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            }
        ],
        "cn/2": [
            {
                "index": 0,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 1,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 2,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 3,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 4,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 5,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 6,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            },
            {
                "index": 7,
                "intensity": 864,
                "worksize": 8,
                "strided_index": [2, 2],
                "threads": [-1, -1],
                "unroll": 8
            }
        ],
        "cn/gpu": [
            {
                "index": 0,
                "intensity": 1728,
                "worksize": 8,
                "threads": [-1],
                "unroll": 1
            },
            {
                "index": 1,
                "intensity": 1728,
                "worksize": 8,
                "threads": [-1],
                "unroll": 1
            },
            {
                "index": 2,
                "intensity": 1728,
                "worksize": 8,
                "threads": [-1],
                "unroll": 1
            },
            {
                "index": 3,
                "intensity": 1728,
                "worksize": 8,
                "threads": [-1],
                "unroll": 1
            },
            {
                "index": 4,
                "intensity": 1728,
                "worksize": 8,
                "threads": [-1],
                "unroll": 1
            },
            {
                "index": 5,
                "intensity": 1728,
                "worksize": 8,
                "threads": [-1],
                "unroll": 1
            },
            {
                "index": 6,
                "intensity": 1728,
                "worksize": 8,
                "threads": [-1],
                "unroll": 1
            },
            {
                "index": 7,
                "intensity": 1728,
                "worksize": 8,
                "threads": [-1],
                "unroll": 1
            }
        ],
        "rx": [
            {
                "index": 0,
                "intensity": 864,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 1,
                "intensity": 864,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 2,
                "intensity": 448,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 3,
                "intensity": 864,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 4,
                "intensity": 448,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 5,
                "intensity": 864,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 6,
                "intensity": 864,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 7,
                "intensity": 864,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            }
        ],
        "rx/wow": [
            {
                "index": 0,
                "intensity": 576,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 1,
                "intensity": 576,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 2,
                "intensity": 576,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 3,
                "intensity": 576,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 4,
                "intensity": 576,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 5,
                "intensity": 576,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 6,
                "intensity": 576,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            },
            {
                "index": 7,
                "intensity": 576,
                "worksize": 8,
                "threads": [-1, -1],
                "bfactor": 6,
                "gcn_asm": true,
                "dataset_host": false
            }
        ],
        "cn/0": false,
        "cn-lite/0": false
    },
    "donate-level": 5,
    "donate-over-proxy": 1,
    "log-file": null,
    "pools": [
        {
            "algo": null,
            "url": "randomx-benchmark.xmrig.com:7777",
            "user": "YOUR_WALLET_ADDRESS",
            "pass": "x",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "user-agent": null,
    "watch": true
}

**Comment by xmrig** [comment]
On GPUs with 4 GB of memory (where `"intensity": 448`), try change `dataset_host` option to `true`, likely it helps.

Another option, run only one 1 thread on that GPUs `"threads": [-1],`, `intensity` can be increased.

I mark this issue as bug, due workaround of another AMD bug, miner use more memory that expected by autoconfig and 4 GB GPUs running out of memory.

**Comment by xmrig** [comment]
@komatom can you confirm suggestions works for you or not.
Thank you.

**Comment by komatom** [comment]
@xmrig I have done several tests with the settings with your recommendations

it turns out 1 thread but higher intesity is the best performing, each test was around 5 min long. And they run without need of the dataset_host enabled in that case..

1) Test 1 [dataset_host = true, threads 2, intesity 448]
- max  3290.6 h/s

2) Test 2 [dataset_host = true, theads 1, intesity 864]
- max 3618 h/s

3) Test 3 [dataset_host = false, threads 1, intesity 864]
- max 3650.9

**Comment by xmrig** [comment]
Fixed in evo branch, now original configuration with 2 threads should work, however hashrate seems ok, according earlier reports https://github.com/SChernykh/RandomX_OpenCL/issues/5
Thank you.

**Comment by komatom** [comment]
Thank you very much.. Can you point me out to the workaround issue that caused 4GB VRAM to not be enough on rx580 carads?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/commit/6bc217e985d933223756237396fd9b80bde9e45c but this commit part of much larger refactoring https://github.com/xmrig/xmrig/commit/f60118ee79262d09e8042927574762753a80354c

AMD driver not release memory buffers bellow 1 GB, it some kind of optimization and not issue when use similar algorithms, memory not actually leak in this case, but if switch between very different algorithms in runtime (cn <-> rx <-> cn) it make GPU out of memory.

intesity 448 it about 896 MB of memory, but miner was increase buffer size to 1024 MB, so 1024 + 1024 + 2080 (RandomX dataset) is larger that 4 GB, now memory buffer shared between threads and this is already larger than 1 GB ((448 + 448) * 2 = ~1792 MB), so no extra unexpected memory required.

**Comment by komatom** [comment]
@xmrig so I have built the latest evo branch. Should I expect autoconfig to set dataset_host to true or the workaround above was changed so 4GB can run. GPUs still can't run  out of the box..

I also rely on the command options instead of the config file, so each rig autoconfig can set the appropriate settings, without me having to enter a separate config.

I am not sure if we have applied a solution for this..

Thanks

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.2.1-beta

**Comment by komatom** [comment]
After 5 minutes of activity

**Comment by komatom** [comment]
To continue on this issue, I have tested on the other rigs too, only 8GB GPUs work.. definetely 4GB VRAM is not enough

**Comment by bizlevel** [comment]
@komatom 
> To continue on this issue, I have tested on the other rigs too, only 8GB GPUs work.. definetely 4GB VRAM is not enough

I have some RX580 with 4Gb and some with 8Gb.
Test is still actual?
How much your 580 get Hashes?

**Comment by komatom** [comment]
@bizlevel more on the same issue is on https://github.com/xmrig/xmrig/issues/1336

rx580 gets around ~400/420 hash/s
