### ISSUE TITLE
.

### ISSUE THREAD

**Issue by x052** [xmrig/xmrig#12]

**Comment by xmrig** [comment]
ARM сcurrently not supported.

**Comment by xmrig** [comment]
What hardware do you want to use? Maybe related issue https://github.com/xmrig/xmrig/issues/11

**Comment by x052** [comment]
Trying to get it to run one one of [these](http://www.ebay.com/itm/Cubieboard4-CC-A80-Allwinner-ARM-2GB-DDR3-8GB-eMMC-Octa-Core-Processor-Mini-PC-/251873648531) things
