### ISSUE TITLE
How can i put config inside In xmrig-4.1.0-beta?

### ISSUE THREAD

**Issue by know212130172** [xmrig/xmrig#1201]
How can i punt my personal config In xmrig-4.1.0-beta
i need modfity which file ?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/issues/957#issuecomment-468890667

**Comment by know212130172** [comment]
if i want to set embedded config Highest priority ,like i have config.json and  embedded config, the xmrig.exe just load embedded config ,how can i do

**Comment by xmrig** [comment]
Use search https://github.com/xmrig/xmrig/issues/1152#issuecomment-526561862
