### ISSUE TITLE
Problem with Opencl on gtx 760

### ISSUE THREAD

**Issue by iEsse** [xmrig/xmrig#1207]
Hello, here is the problem with opencl on gtx760, how can i solve it ?
![Безымянный](https://user-images.githubusercontent.com/35467897/65834671-dda63400-e2f6-11e9-86fd-cede39d74271.png)

**Comment by xmrig** [comment]
Probably should reduce `intensity`, I still no checked OpenCL implementation on NVIDIA hardware, anyway CUDA is coming for it.
Thank you.

**Comment by iEsse** [comment]
Reducing intensity didn't help. Moreover it caused another error, in addition when i set intensity lower then 64 it drops till 56. It all happens on "rx/wow" algo, but only on "cn/gpu" opencl works normally. 
![Безымянный2](https://user-images.githubusercontent.com/35467897/65902369-b8d3be80-e3d3-11e9-976c-abb3b43cdf42.png)

**Comment by Spudz76** [comment]
You don't have enough memory to run RandomX, it requires >2GB to even begin

**Comment by iEsse** [comment]
> You don't have enough memory to run RandomX, it requires >2GB to even begin
Gtx 760 has 2gb of vram, so it's a bug

**Comment by iEsse** [comment]
> You don't have enough memory to run RandomX, it requires >2GB to even begin

Gtx 760 has 2gb of ram, so it's a bug

**Comment by Spudz76** [comment]
`>2GB` means more than, like 4GB
2GB == 2048MB which is smaller than the 2080MB minimum before scratchpads, and even then that's without the OS or other stuff reserving some of the memory (never seen a 2GB show 2048MB free even when display is not connected and no GUI running...)
So really 3GB is the minimum probably but I'm not sure there were any 3GB nVidias.

The CUDA version currently in `evo` branch works nicely for me, on 4GB+ card (970GTX), with RandomX algos working fine.
I have not tried the OpenCL-on-nVidia as it has never worked (or if it did it worked badly) with any of the other miners so it didn't seem like worth trying.  I might toss a test at it on my 4GB to see if it works when given enough memory, but doubtful it will be as fast as raw CUDA.

For the new CUDA backend on xmrig (unified) which is in the `evo` branch now, you need to checkout the `xmrig-cuda` project and build from that the so/dll for the unified CUDA backend (different than OpenCL which is fully unified).
