### ISSUE TITLE
Connect from multiple locations

### ISSUE THREAD

**Issue by minerteam** [xmrig/xmrig#121]
Good morning, we are a group of friends and we want to use our personal computers directed to the same wallet. It's possible? Thank you.

**Comment by NmxMilk** [comment]
yes, offcourse!
The miner sends out whatever you specify to the pool.

**Comment by minerteam** [comment]
And it does not influence mine speed by using the same wallet address?

**Comment by dorimanx** [comment]
More miners you have, more bonus on average you get, me and my friends have 25kh/s farm team mining, and its great! Want to join us?

**Comment by minerteam** [comment]
Thank you very much for your clarifications. 
Yuri.Sh regarding your proposal, I will consult with my friends, thank you.
