### ISSUE TITLE
Auto threads config doesn’t work correctly on Ryzen 7 3700x/RandomX 

### ISSUE THREAD

**Issue by vegaman64** [xmrig/xmrig#1214]
On 3700x it’s seems 15 threads do the best job even if it seems there is enough L2 and L3 cache to  feed all 16 threads. I think for CPUs having L3 = cpu threads x 2 and L2 = cpu threads x 256 miner thread count should be cpu threads-1. It seems there must be some free headroom in L3 to effectively work. Someone with similar cache/threads setup could confirm this though

**Comment by SChernykh** [comment]
I have 3700X and 16 threads is the best setting. I just don't have anything running in the background and I've gone to great lengths tweaking Windows and disabling unnecessary services.

**Comment by vegaman64** [comment]
Even on Linux I’m getting 7100hs as a max using 16 threads and 7800hs using 15. Thanks for your reply. Can you share how much did you get with 16 threads?

**Comment by SChernykh** [comment]
I've just tested at fixed 4.1 GHz clock speed to get more stable hashrate. 16 threads are a bit faster: https://imgur.com/a/CXpN4LF

**Comment by vegaman64** [comment]
Thanks again.. Except memory settings and cpu OC, isn’t  there some trick on bios ? I’m playing on 4 different boards, windows, Linux.. all the same. 8.5+kh sounds more  reasonable for 3700x

**Comment by SChernykh** [comment]
Memory tweaked with timings from Ryzen DRAM calculator (fast preset), CPU overclocked in Ryzen Master, that's it. And Windows just cleaned of garbage as I mentioned before.

**Comment by vegaman64** [comment]
Thanks! Playing on windows I managed to get all threads working and even on Linux there’s small, but benefit running 16 threads of memory is pushed to its max.

**Comment by vegaman64** [comment]
One last question about Linux - is there still something wrong with kernel (4.15 and 5.4 rc1 tested) or xmrig/rx-benchmark isn’t jet fully optimized for ryzen+Linux? Getting less Hashrate on Ubuntu no matter what I do. (At 4.1ghz/1.085v 9050hs Win, 8750hs Linux and at 4.4ghz/1.35v 9500hs Win, 9150hs Linux)

**Comment by k0ngl0ng** [comment]
How do you solve this problem? I have the same problem.
thank you.

**Comment by k0ngl0ng** [comment]
how to push the memory to its max？
