### ISSUE TITLE
dataset.hpp(61): error C2338: randomx_cache must be a standard-layout struct

### ISSUE THREAD

**Issue by xmska** [xmrig/xmrig#1215]
I am unable to compile in visual studio 2017

> dataset.hpp(61): error C2338: randomx_cache must be a standard-layout struct

But it will compile in MSYS2 MinGW.
How can I compile this corectly in visual studio?

**Comment by xmrig** [comment]
Use release build or remove this check.
Thank you.

**Comment by xmska** [comment]
Could you explain what that is and why it does not work in debugging mode? Is it gonna work properly in debug mode with this check removed?

**Comment by SChernykh** [comment]
It doesn't work in debug in Visual Studio. Removing the check will make it compile, but it will crash when trying to mine RandomX.

**Comment by xmska** [comment]
Under what circumstances does it crash? I let it mine LOKI in debug and it worked without crashing.

**Comment by xmrig** [comment]
This check should be unnecessary since RandomX code embedded into miner and don't need to be strictly compatible with C (unlike official library), but if you need debug build it means you known what you do and all possible crashes is your responsibility.
Thank you.

**Comment by chase2222** [comment]
hi
sorry for being a noob but which check should remove exactly in order to debug this in Visual Studio 2019?..
