### ISSUE TITLE
RandomX dataset memory usage and initialization speed improvements for NUMA machines

### ISSUE THREAD

**Issue by xmrig** [xmrig/xmrig#1221]
In upcoming version 4.3 NUMA support for RandomX dataset improved, second and subsequent nodes now require 2080 MB (instead of 2336 MB) and greatly improved initialization speed for that nodes.

Initial implementation, used fully independent RandomX datasets on each NUMA node, it require 2080 MB for dataset and 256 MB for cache, new implementation use cache and initialize dataset only on first node and after initialization done, just copy full dataset memory to another nodes, it much faster and not require extra cache allocation.

In addition `"numa"` option in config extended now possible specify numa nodes to use (instead of all available, it might useful for some corner cases and debug), example `"numa": [0, 1]`

**Comment by 2010phenix** [comment]
@xmrig, maybe in this case (now require 2080 MB - just copy full dataset memory to another nodes ) do some part solution(split)... like 2080 \2 - 2080\4 or similar....

**Comment by xmrig** [comment]
1. Not possible split dataset to pieces.
2. If target is memory usage, simple `"numa": false` or choice fastest node should be enough.

Thank you.

**Comment by xmrig** [comment]
@a905770 because RandomX algorithm require it, there is no direct option to reduce it, miner will use  256 MB only if fails to allocate 2 GB, but it will be 10x slower.
Thank you.
