### ISSUE TITLE
Add option to disable old CryptoNight variation

### ISSUE THREAD

**Issue by du0ngpv** [xmrig/xmrig#1225]
Could you consider add this option in futre release ?

**Comment by xmrig** [comment]
Isn't that what you are looking for? https://github.com/xmrig/xmrig/blob/master/src/config.json#L28
Thank you.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/blob/master/doc/build/CMAKE_OPTIONS.md#algorithms but currently not possible complete disable all cryptonight algorithms.

**Comment by du0ngpv** [comment]
Thanks for your answer
