### ISSUE TITLE
(Error) Unable to set affinity. Windows supports only affinity up to 63

### ISSUE THREAD

**Issue by sirwin89** [xmrig/xmrig#1228]
I have 72 CPUs how to use them all.

Image
<img src="https://i.imgur.com/mStXohD.jpg" />

**Comment by Spudz76** [comment]
Windows decided to be dumb and requires a large pile of additional code to support more than 64 cores.  There are no miners I know of that bothered to support the silly ProcessorGroup stuff.  Most of those people just install Linux which handles hundreds of cores properly without any additional system calls or tracking which process is in which virtual group.

[https://docs.microsoft.com/en-us/windows/win32/procthread/processor-groups](https://docs.microsoft.com/en-us/windows/win32/procthread/processor-groups)

Sometimes Windows will force Processor Groups even with less than 64 cores, depending on the layout of the motherboard (dual CPU etc), which is even more annoying.

**Comment by xmrig** [comment]
Recent versions correctly supports affinity above 63.
Thank you.
