### ISSUE TITLE
Cmake Error could not find HWLOC

### ISSUE THREAD

**Issue by OhoTV1** [xmrig/xmrig#1230]
pi@raspberrypi:~/xmrig/build $ cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Use ARM_TARGET=7 (armv7l)
-- Looking for syslog.h
-- Looking for syslog.h - found
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find HWLOC (missing: HWLOC_LIBRARY HWLOC_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindHWLOC.cmake:25 (find_package_handle_standard_args)
  src/backend/cpu/cpu.cmake:29 (find_package)
  src/backend/backend.cmake:1 (include)
  CMakeLists.txt:29 (include)

-- Configuring incomplete, errors occurred!
See also "/home/pi/xmrig/build/CMakeFiles/CMakeOutput.log".

**Comment by 0xman** [comment]
did you install HWLOC ?

**Comment by RizkiRama99** [comment]
This is the way http://bit.ly/364s24H

**Comment by 0xman** [comment]
> This is the way http://bit.ly/364s24H

what's with the link?

**Comment by RizkiRama99** [comment]
It contains articles about hwloc problems

**Comment by xmrig** [comment]
@RizkiRama99 no one like short links, it looks and may dangerous by the way, I edited your comments.

**Comment by MarcKarasek** [comment]
This is not closed..  If you are compiling your own hwloc and try to set XMRIG_DEPS it fails..

**Comment by demonsoul34** [comment]
CHECK THIS LINK, IT MAYBE HELPS SOME OF YOU GUYS: https://programmerah.com/xmr-could-not-find-hwloc-missing-hwloc_library-hwloc_include_dir-33513/
