### ISSUE TITLE
Drop hashrate on amd with multiple threads

### ISSUE THREAD

**Issue by Amf1k** [xmrig/xmrig#1233]
A config with 2 threads is generated on my RX580 and the total hash is about 400 h/s, when I leave one thread the hash is about 650 h/s. Is it a calculation error or is it faster mined with one thread? this is repeated on all versions with opencl xmrig-beta or xmrig-amd

[config and screens](https://mega.nz/#F!zpUzgQQD!dpMXlYVcsm27k2PfzsiaoA)

**Comment by xmrig** [comment]
Please show Sensors tab from GPU-Z before and after start mining, it might be memory issue, OpenCL API not provide information about free memory, in case if your GPU is not dedicated for mining, Windows can take over 500 MB of GPU memory, `864 * 2 * 2 + 500 = 3956` it very close to memory limit, solution is use less intensity for double threads mode.

Also don't need change `strided_index`, second value in array is option was known as `mem_chunk`.
Thank you.

**Comment by Amf1k** [comment]
[screens](https://mega.nz/#F!GhlQgCLQ!wUDMrSvOwV8DE5cUeUMUNw)

Some kind of bug in GPU-Z, shows loading 100% always. Or maybe the problem is in my map. Memory seems to allocate correctly.

**Comment by Amf1k** [comment]
@xmrig  hi! is there any news?
