### ISSUE TITLE
  Could NOT find UV (missing: UV_LIBRARY UV_INCLUDE_DIR)	

### ISSUE THREAD

**Issue by wcsmomo** [xmrig/xmrig#1236]
I made a mistake when using vs 2019 to connect GitHub to import xmrig projects:

CMake Error at E:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Common Extensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/FindPackageHandleStandard Args.cmake:137 (message):

Can NOT find UV (missing: UV_LIBRARY UV_INCLUDE_DIR) E:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common 7/IDE/Common Extensions/Microsoft/CMake/share/cmake-3.15/Modules/FindPackage Args.cmake 137

**Comment by Spudz76** [comment]
Windows external deps are in the [xmrig-deps](https://github.com/xmrig/xmrig-deps/) project

You checkout that tree and then provide CMake definition:
`XMRIG_DEPS=C:\src\xmrig-deps\msvc2019\x64`
...but of course using your actual pathspec for where `xmrig-deps` is checked out, and then it should find everything.

I have never used the builtin VS cmake much less the VS IDE (just the build tools, CMake from their site, and a cmd shell) unsure how to add that define to its CMake properties so hopefully you can find it.

My shell cmd for building is:
`cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DXMRIG_DEPS=C:\src\xmrig-deps\msvc2019\x64 -DCMAKE_VERBOSE_MAKEFILE=ON -DWITH_OPENCL=OFF -DWITH_CUDA=OFF -DWITH_ARGON2=OFF ..`

**Comment by Neuroelectric86** [comment]
I'm running the same issue on Mac OS X 10.11.6.

**Comment by NineWoranop** [comment]
I also try to search this answer. I discover that. If you do the [steps](https://xmrig.com/docs/miner/build/windows) for compile code with Visual Studio 19. If we already got the generated solution and project. You need to use those projects. Not need to create your own project.

**Comment by navasquillo** [comment]
Hello,
I'll do the same steps as [but](https://xmrig.com/docs/miner/build/windows) except install Git because I had installed. My question is, is the steps correct?

**Comment by navasquillo** [comment]
The error is is related with CMake

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find UV (missing: UV_LIBRARY UV_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindUV.cmake:25 (find_package_handle_standard_args)
  CMakeLists.txt:178 (find_package)

**Comment by Spudz76** [comment]
If you missed downloading and unpacking (or, git-checkout) the [xmrig-deps](https://github.com/xmrig/xmrig-deps), and the `-DXMRIG_DEPS=c:\xmrig-deps\msvc2019\x64` piece for cmake (or where your xmrig-deps folder is), it will be unable to find multiple things.

**Comment by Fooughhy** [comment]
I'm having this issue aswell. 
CMake version 3.20.2
MSVC version 19.28.29914.0

Structure is:
C:\Mining\xmrig
C:\Mining\xmrig-deps
Running `cmake .. -G "Visual Studio 16 2019" -A x64 -DXMRIG_DEPS=c:\Mining\xmrig-deps\msvc2019\x64` give the same output as @navasquillo.

**Comment by Spudz76** [comment]
I use:
`cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DXMRIG_DEPS=D:\src\xmrig-deps\msvc2019\x64 -DCMAKE_VERBOSE_MAKEFILE=ON -DWITH_OPENCL=OFF -DWITH_ADL=OFF -DWITH_CUDA=OFF -DWITH_NVML=OFF -DWITH_KAWPOW=OFF ..`
and it works, followed by:
`cmake --build . --config Release`
and it builds

**Comment by Fooughhy** [comment]
Thank you! That seems to have worked. Wonder which parameter fixed it 🤔

**Comment by Spudz76** [comment]
Dunno, I've used the same build bat file for years and it always works.  Maybe specifying the build type helps.  Or, don't specify architecture (`-A x64`) which only matters if you have more than just VS-x64 installed.

**Comment by navasquillo** [comment]
I cannot compile.
My structure:
C:/xmrig
C:/xmrig-deps
(both cloned from github)
![imagen](https://user-images.githubusercontent.com/61295506/117512831-aac32800-af90-11eb-9425-368631f61284.png)
I've create C:/xmrig/build
Using the Git Bash I pasted the command cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DXMRIG_DEPS=D:\src\xmrig-deps\msvc2019\x64 -DCMAKE_VERBOSE_MAKEFILE=ON -DWITH_OPENCL=OFF -DWITH_ADL=OFF -DWITH_CUDA=OFF -DWITH_NVML=OFF -DWITH_KAWPOW=OFF ..

and... error!!!

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find UV (missing: UV_LIBRARY UV_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindUV.cmake:25 (find_package_handle_standard_args)
  CMakeLists.txt:178 (find_package)

**Comment by Spudz76** [comment]
BASH doesn't accept backslash, change to `\\` or `/` in paths.

Or use CMD.EXE like normal.

**Comment by dday9** [comment]
@Spudz76 - I spent about an hour until I realized that my issue was related to the backslash. Once I changed it, it worked. For those of you who want to have a step-by-step guide of what I did after installing cmake and Git BASH:

1. Open up Git BASH
2. Change the directory to C (if necessary) by running: `cd C:/`
3. Clone the XMRig dependencies project ([repo link](https://github.com/xmrig/xmrig-deps)) by running: `git clone https://github.com/xmrig/xmrig-deps.git`
4. Clone the XMRig project ([repo link](https://github.com/xmrig/xmrig)) by running: `git clone https://github.com/xmrig/xmrig.git`
5. Make the "build" directory by running: `mkdir build`
6. Change the directory to the "build" directory by running: `cd build`
7. Compile the project by using the Visual Studio 2019 compiler by running: `cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DXMRIG_DEPS=C:/xmrig-deps/msvc2019/x64 -DCMAKE_VERBOSE_MAKEFILE=ON -DWITH_OPENCL=OFF -DWITH_ADL=OFF -DWITH_CUDA=OFF -DWITH_NVML=OFF -DWITH_KAWPOW=OFF ..`
8. Build the project by running: `cmake --build . --config Release`

Hopefully this clears it up for someone else who ran into the same issue I did.

**Comment by Spudz76** [comment]
I believe CMake in general accepts `/` regardless of shell type, so it may be best practice to always use `/`

**Comment by vladkras** [comment]
on macos this error was fixed with
`brew install libuv `

**Comment by Spudz76** [comment]
Except now you're using whatever (probably older) version of libuv that comes from homebrew, defeating the purpose of using the bundled deps.
