### ISSUE TITLE
Not a issue but a qestion on monero.

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [xmrig/xmrig#1244]
Hello i haven't mine monero in a long time and i just only recently heard that monero is going back to Cpu mining instead of GPU mining. I'm not sure if this is true or not But i was wondering my old mnero wallet will it still work for this new miner or would i have to get something else. And if i need a new wallet which one would i need for this miner?

Joseph

**Comment by 2010phenix** [comment]
all in: https://www.reddit.com/r/Monero/comments/d884zt/preliminary_information_thread_regarding_the/

**Comment by Spudz76** [comment]
Monero never "allowed" GPU mining, in fact every hardfork has been to destroy GPU and ASIC efficiency to keep it CPU only.  RandomX basically puts CPU back into the best H/W power band and injures GPU and ASIC to the point they are useless (unless you like running at a loss).

You will be unable to run with less than 4GB as well, RandomX requires 2080MB baseline locked memory (not just the scratchpad space like other CN algos).
