### ISSUE TITLE
Segmentation Fault (core dumped) on Ubuntu 19.10 or upgraded 18.04 to 5.4 RC1

### ISSUE THREAD

**Issue by jims23211** [xmrig/xmrig#1250]
Just a heads up, but running xmrig on the newer ubuntu release (19.10) or 5.4 RC1 or greater will generate "Segmentation Fault (core dumped) after running for 20 minutes or more.  I compile the xmrig code on both systems.  Same result.

**Comment by xmrig** [comment]
Please provide full information, config file, miner log (at least start and end right before crash)
Thank you.

**Comment by jims23211** [comment]
Gathering requested information.

**Comment by jims23211** [comment]
miner@amd3900x:~/xmrig/build$ uname -a
Linux amd3900x 5.4.0-050400rc1-lowlatency #201909301433 SMP PREEMPT Mon Sep 30 18:52:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

[debug.zip](https://github.com/xmrig/xmrig/files/3780370/debug.zip)

Please find attached zip file with hopefully requested data.

Jim

**Comment by jims23211** [comment]
Update I also have a core dump and kern.log.  If you want the core dump, I will need a place to upload it to, compressed its over 2.5G zipped.  Attached is the kern.log

[kern.zip](https://github.com/xmrig/xmrig/files/3780430/kern.zip)

**Comment by xmrig** [comment]
It might be overclocking issue, especially memory clocks/timing, try reset memory settings to default and check it again.
Thank you.

**Comment by jims23211** [comment]
Question is why does this not occur on 18.04 when running the overclock settings?  Only reason I was looking at the 5.4 was to monitor cpu temps since 18.04 does not have the right monitoring drivers.

**Comment by lss4** [comment]
As what I wrote on #1266, it seems the latest 5.4 kernel RCs (from rc6 onwards) might have issues with xmrig.

I'm using latest Manjaro Testing and xmrig segfaults after about an hour of mining with 5.4-rc6 kernel (and higher). With 5.3.11 kernel I do not get any segfault after more than 20 hours of consecutive mining (even with ocl enabled for Radeon RX 5700 XT, although the hashrate from ocl is quite unstable). The CPU is a single EPYC 7551 (not engineering sample). Before 5.4-rc6 kernel I never had any issue with xmrig. Also, I do not use any overclock options.

I think we need to confirm whether upstream changes in the 5.4 kernel is indeed the culprit and report this issue to the kernel bugzilla instead if it's indeed the case.
