### ISSUE TITLE
OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR

### ISSUE THREAD

**Issue by Conan-Wolf** [xmrig/xmrig#1257]
how can i fix OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR?
this is happening when i am doing cmake

``-- Use ARM_TARGET=7 (armv7l)
-- Found HWLOC: /usr/lib/arm-linux-gnueabihf/libhwloc.so
-- Found UV: /usr/lib/arm-linux-gnueabihf/libuv.a
-- Looking for __builtin___clear_cache
-- Looking for __builtin___clear_cache - found
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR)
CMake Error at cmake/OpenSSL.cmake:21 (message):
  OpenSSL NOT found: use `-DWITH_TLS=OFF` to build without TLS support
Call Stack (most recent call first):
  CMakeLists.txt:160 (include)
``
do note i am newer to linux

**Comment by Conan-Wolf** [comment]
solved it myself

**Comment by GayathriBabu98** [comment]
same error i have...please help me how to solve it??
