### ISSUE TITLE
libc.so.6: version <GLIBC_2.17 How do I run,

### ISSUE THREAD

**Issue by Likelym** [xmrig/xmrig#126]
libc.so.6: version <GLIBC_2.17 How do I run,

![qq 20170928201132](https://user-images.githubusercontent.com/29804337/30965914-a4ad2972-a489-11e7-8f10-9e03d8693cfc.png)

Thank you.

**Comment by xmrig** [comment]
You use binary build? looks like you trying run it on old system. You need rebuild it from source.
