### ISSUE TITLE
Xmrig with dual Epyc 32core not possible ? Segmentation fault

### ISSUE THREAD

**Issue by theshadowpeople** [xmrig/xmrig#1266]
I want to test my server with xmrig / RandomX but it fails.
![xmrig](https://user-images.githubusercontent.com/57456171/68324954-c19d6b80-00c8-11ea-9611-9aee27f227c9.png)

here is the topology

[topology.txt](https://github.com/xmrig/xmrig/files/3816067/topology.txt)

Does anyone have an idea why it doesn´t work?

With my dual Opteron 2x12core it works without any problems.

**Comment by theshadowpeople** [comment]
Now i have install Ubuntu Mate 18.04.03 LTS and it doesn't work too.
![pic](https://user-images.githubusercontent.com/57456171/68395819-c87fb900-0170-11ea-9b4c-13cfe445e2aa.png)

**Comment by ari2asem** [comment]
probably because it is ES cpu?

try another pool..
look ar reddit -->> moneromining -->> supportxmr testnet pool for more info

i am running dual socket epyc 7551 (retail, not ES) without problems

**Comment by theshadowpeople** [comment]
Another Pool doesn't work too .... Maybe XMRIG don't like my engineering sample
Which mainboard do you have ?
With Ubuntu i get the massage "Speicherzugriffsfehler" i think the english translation is "segmentatio fault" but i have test my rams with memtest without any errors .....

**Comment by ari2asem** [comment]
i have h11dsi, rev 1.0. ddr4-2666 MHz ecc-reg 10*  8gb RAM. w;ndows 10 v1903, 64 bit....try windows version xmrig msvc...maybe that should work....
yet another question...in general, is your system stable?? can you stress test your system (or cpu only) to exclude your cpu (or system) is having another problems except xmrig?

**Comment by theshadowpeople** [comment]
yes my system are stable (tested with prime95) 
in Ubuntu Syslog i get this massage "kernel: [ 2220.824402] traps: xmrig[10126] general protection fault ip:7f2eb6379ac2 sp:7f2e9f7fddb0 error:0"

**Comment by ari2asem** [comment]
can you try precompiled binaries of xmrig-msvc version on windows 10?

**Comment by theshadowpeople** [comment]
I already tested and it doesn't work too. :(

**Comment by ari2asem** [comment]
can you try randomx benchmark tool? also available on github...and try also without large pages, so disable large pages....otherwise, mistery. probably becaus of ES

**Comment by pawelantczak** [comment]
@theshadowpeople did you try with benchmark tool from RandomX github page?

**Comment by theshadowpeople** [comment]
![xmrig3](https://user-images.githubusercontent.com/57456171/68652659-3ee23980-052a-11ea-9e4a-7740095843f6.png)
If i start RandomX benchmark v.1.1.1 with --nonces 5000 i get an result but if i start with --nonces 50000 that i get the same like xmrig .... nothing

**Comment by ari2asem** [comment]
you need new cpu

**Comment by theshadowpeople** [comment]
I can not explain it.... everything else is perfect .... Memtest86x, prime95 all benchmarks run without errors and normal score.
Is there any way to find out what exactly causes the crash?

**Comment by lss4** [comment]
Not sure about you CPU. I'm having this issue about 2 weeks ago on latest Manjaro Testing.

I've a 7551 and mine doesn't look like an engineering sample. It happened since kernel 5.4-rc6, before this everything was okay. Since this kernel onwards, xmrig would segfault after mining for about an hour.

I'm currently mining on 5.3 kernel (5.3.11) and I'm able to mine for at least 10 hours without a single segfault so far, with v4.5.0-beta.

This is only CPU. I haven't tested OpenCL yet as I couldn't produce any hashrate with my Radeon RX 5700 XT (with opencl-amdgpu-pro-pal package), despite the workers are running.

**Comment by SChernykh** [comment]
@theshadowpeople Can you try to compile and test https://github.com/SChernykh/xmrig/tree/ryzen-fix ?

**Comment by xmrig** [comment]
Disabling opcache in BIOS should fix the issue, not sure it possible on server motherboard, but please try https://github.com/xmrig/xmrig/pull/1348#issuecomment-560122919

**Comment by theshadowpeople** [comment]
For me it doesn't work but the H11DSI has the option only with MOD BIOS and i am not sure if this option work correct.

**Comment by xmrig** [comment]
Try recent version with `"wrmsr": ["0xc0011020:0x0", "0xc0011021:0x60", "0xc0011022:0x510000", "0xc001102b:0x1808cc16"]` more details about MSR https://xmrig.com/docs/miner/randomx-optimization-guide/msr
Thank you.

**Comment by SChernykh** [comment]
@theshadowpeople XMRig 5.5.0 has a workaround for 1st gen Ryzen/Threadripper/EPYC crashes, you should be able to mine even with enabled Opcache.
