### ISSUE TITLE
Huge pages

### ISSUE THREAD

**Issue by ITsenhong** [xmrig/xmrig#127]
In my case, Huge page is available but unenable. I hear someone say huge enable wI'll double hashrate, does it right? If yes how do i do it? Thanks!

**Comment by ITsenhong** [comment]
My CPU is Xeon 8 core

**Comment by stoffu** [comment]
Try restarting your computer and launching the miner immediately when the system starts.

**Comment by ITsenhong** [comment]
I will try your suggestions and reply soon. I have another question, My CPU is xeon 8 core with ~46MB L3 cache( using lscpi | grep "cache"). I set config with 8 thread now, when i set 16 thread, hashrate decrease. Does 8 thread best for me? Would you like suggest better confif for me!

**Comment by stoffu** [comment]
I can't say much since I don't own any Xeon processors, but in general you find the best optimal setting by just trying various parameters.

**Comment by ITsenhong** [comment]
After reset. Huge pages still disable. But thanks for help
