### ISSUE TITLE
Sigma algo support for Gulden coin

### ISSUE THREAD

**Issue by KL0nLutiy** [xmrig/xmrig#1270]
Hello, @xmrig, could you please add support of sigma algo for Gulden coin.

https://github.com/Gulden/gulden-official

**Comment by trasherdk** [comment]
I'm not a lawyer, but:
[The Gulden license](https://github.com/Gulden/gulden-official/blob/master/COPYING_gulden) would prevent anybody doing anything related to or derived from that thing.

And then there is: https://github.com/Gulden/gulden-official/commit/87dea27b11c2f041c678e6c26c52e0490982bf35
