### ISSUE TITLE
Mine to daemon

### ISSUE THREAD

**Issue by TheDevMinerTV** [xmrig/xmrig#1275]
How can I mine to my Turtlecoin daemon?

The option is in the config.json file but it's not being used
![image](https://user-images.githubusercontent.com/29845135/68580495-c53d4380-0476-11ea-80ae-0f194137a34a.png)

(don't tell me, that they forked, I know that...)

**Comment by xmrig** [comment]
Default JSON RPC port for TurtleCoin **11898** according the docs https://docs.turtlecoin.lol/developer/api/daemon-json-rpc-api and they forked so you should use `argon2/chukwa` algorithm and this algorithm supported only by CPU backend.
Thank you.

**Comment by TheDevMinerTV** [comment]
I know that, the thing is that I don't get any shares or blocks.
I'm working on a fork of Turtlecoin whihch uses `cn-pico/trtl`

**Comment by xmrig** [comment]
What exactly fork?

If miner successfully connected to daemon you should saw lines like:
`...use daemon...`
`...new job...`

or errors like: `[192.168.189.69:32769] connect error: "connection timed out"`.

If nothing above happens, something wrong, unexpected API response, etc.
Thank you.

**Comment by TheDevMinerTV** [comment]
There's no output after the header
![Output of XMRig](https://user-images.githubusercontent.com/29845135/68775019-307d4600-062e-11ea-9343-3fecab0dcb3b.png)

![Config for pools](https://user-images.githubusercontent.com/29845135/68775074-40952580-062e-11ea-93a7-4a3dc4745f87.png)

**Comment by Spudz76** [comment]
Doesn't seem like port 32769 is speaking JSON-RPC

**Comment by TheDevMinerTV** [comment]
We have forked to port 32779 as JSON-RPC about four days ago, still not working.

**Comment by TheDevMinerTV** [comment]
I tried this again in version v5.5.0 and it works fine. Closing.
