### ISSUE TITLE
[BUG] xmrig 4.6.1 beta "Invalid configuration argument" for cn-pico auto configuration

### ISSUE THREAD

**Issue by RainbowMiner** [xmrig/xmrig#1276]
If using the auto-configuration for CryptonightTurtle aka cn-pico on GTX1070 with xmrig v4.6.1 beta, I get the following json:
```
    "cn-pico": [
    {
      "index": 0,
      "threads": 228,
      "blocks": 45,
      "bfactor": 6,
      "bsleep": 25,
      "affinity": -1
    },
```

.. which results in the following error:
![image](https://user-images.githubusercontent.com/39437538/68611453-70232100-04ba-11ea-9d0c-35c15fcec186.png)

It looks like too many threads: the maximum value seems to be 128 for "threads".

**Comment by xmrig** [comment]
Fixed https://github.com/xmrig/xmrig-cuda/commit/15b9ed65fef01de98e60c1a702cb98dcf8184593
Actually limit to 128 was already here, but i was works only arch 70+.
Thank you.

**Comment by xmrig** [comment]
Fixed in v5.
