### ISSUE TITLE
error: 'randomx::JitCompilerA64' has not been declared on ARM

### ISSUE THREAD

**Issue by OTLabs** [xmrig/xmrig#1281]
I am compiling v5.0.0 for Alpine Linux, https://github.com/alpinelinux/aports/pull/12102,  and get following error for aarch64, armv7, and armhf:

`/home/buildozer/aports/testing/xmrig/src/xmrig-5.0.0/src/crypto/randomx/randomx.cpp:212:38: error: 'randomx::JitCompilerA64' has not been declared`

Build logs are available here:
aarch64 - https://cloud.drone.io/alpinelinux/aports/13302/3/1 (build is stalled at the time of writing)
armv7 - https://cloud.drone.io/alpinelinux/aports/13302/5/1
armhf - https://cloud.drone.io/alpinelinux/aports/13302/4/1

**Comment by andypost** [comment]
aarch64 still fails to build https://cloud.drone.io/alpinelinux/aports/13356/3/1

**Comment by xmrig** [comment]
Something wrong with builder, in log just warnings and no single error and seems build was killed by timeout.
Thank you.
