### ISSUE TITLE
Windows Defender Sever Alert on xmrig.exe with Program:Win32/Unwaders.A!ml

### ISSUE THREAD

**Issue by LeMoussel** [xmrig/xmrig#1288]
I build `xmrig` on Win 10/VS 2019  with [prebuilt dependencies](https://github.com/xmrig/xmrig-deps/releases)
Windows Defender is detecting that `xmrig.exe` is infect by [Program:Win32/Unwaders.A!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Program%3aWin32%2fUnwaders.A!ml&threatid=242872)

Do you know whats up with that?

**Comment by pawelantczak** [comment]
Just whitelist xmrig folders in AV.

**Comment by Spudz76** [comment]
Standard idiocy due to trojan-payload miners.  "Average Moron Users" don't run miners so the safety shields all complain about them, you have to tell it you know what you're doing (whitelist all your mining source/build/run folders)
