### ISSUE TITLE
RandomX on x86?

### ISSUE THREAD

**Issue by passnet** [xmrig/xmrig#1289]
Trying to build xmrig 5.0.0 on msys-mingw32 I get the following warning:

```
xmrig-5.0.0/src/crypto/rx/RxDataset.cpp: In member function 'void xmrig::RxDataset::setRaw(const void*)':
xmrig-5.0.0/src/crypto/rx/RxDataset.cpp:154:11: warning: 'void* memcpy(void*, const void*, size_t)' specified bound 2181038080 exceeds maximum object size 2147483647 [-Wstringop-overflow=]
  154 |     memcpy(randomx_get_dataset_memory(m_dataset), raw, maxSize());
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

Not sure what it means but seems like it can cause mem overflow on 32-bit systems.

`gcc.exe (Rev2, Built by MSYS2 project) 9.2.0`

**Comment by passnet** [comment]
It still works with slow mode:
```
[2019-11-15 12:36:32.150]  rx   failed to allocate RandomX dataset, switching to slow mode (4 ms)
[2019-11-15 12:36:34.259]  rx   dataset ready (2109 ms)
```

If the warning can be safely ignored then probably that is not an issue.

**Comment by xmrig** [comment]
I didn't deep look why allocation of a dataset does not work on 32 bit systems as it not too much useful for mining anyway, at least linker flag added `-Wl,--large-address-aware`.

`RxDataset.cpp:154:11: warning` this code works on NUMA machines for copy initialized dataset to other nodes.
Thank you.
