### ISSUE TITLE
Alpine linux compilation failed

### ISSUE THREAD

**Issue by axsoftshi** [xmrig/xmrig#1291]
localhost:~/xmrig/b# cmake -DCMAKE_BUILD_TYPE=Release ..
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find HWLOC (missing: HWLOC_LIBRARY HWLOC_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindHWLOC.cmake:25 (find_package_handle_standard_args)
  src/backend/cpu/cpu.cmake:30 (find_package)
  src/backend/backend.cmake:1 (include)
  CMakeLists.txt:34 (include)

-- Configuring incomplete, errors occurred!
See also "/root/xmrig/b/CMakeFiles/CMakeOutput.log".

**Comment by y0bagu1** [comment]
add -DWITH_HWLOC=OFF in cmake and it will be ok.

**Comment by axsoftshi** [comment]
> 在cmake中添加-DWITH_HWLOC = OFF即可。
Can I compile statically in other Linux

**Comment by xmrig** [comment]
You should install `hwloc-dev` package, in general disabling hwloc not so good idea, without it auto-configuration will be limited. Exceptions are ARM targets and some virtual machines where hwloc not much useful itself.
Thank you.

**Comment by l-we** [comment]
install hwloc-dev
```
apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing hwloc-dev
cmake .. -DBUILD_STATIC=ON -DUV_LIBRARY=/usr/lib/libuv.so -DHWLOC_LIBRARY=/usr/lib/libhwloc.so
make
```
error
```
[100%] Linking CXX executable xmrig
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lhwloc
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/xmrig.dir/build.make:2585: xmrig] Error 1
make[1]: *** [CMakeFiles/Makefile2:116: CMakeFiles/xmrig.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by BourgeoisBear** [comment]
It builds easily enough from source--needs GNU autotools though.

https://github.com/open-mpi/hwloc
