### ISSUE TITLE
xmrig-5.0.0 crash with windows 10 randomx rx/0 ryzen 1700X

### ISSUE THREAD

**Issue by maxfreemax** [xmrig/xmrig#1297]
I try test on randomx, but xmrig 5.0.0 crash after few seconds. 
I have windows 10 and ryzen 1700X

 note , all seem  ok with cn/0 

last screen just before crash
![xmrig](https://user-images.githubusercontent.com/44138963/69004447-aaa21900-0913-11ea-9daf-a0a028c1264b.png)

config.json:
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "colors": true,
    "randomx": {
        "init": -1,
        "numa": false
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "hw-aes": null,
        "priority": null,
        "memory-pool": false,
        "asm": true,
        "argon2-impl": null,
        "argon2": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "cn": [
            [1, 0],
            [1, 2],
            [1, 4],
            [1, 6],
            [1, 8],
            [1, 10],
            [1, 12],
            [1, 14]
        ],
        "cn-heavy": [
            [1, 0],
            [1, 2],
            [1, 8],
            [1, 10]
        ],
        "cn-lite": [
            [1, 0],
            [1, 1],
            [1, 2],
            [1, 3],
            [1, 4],
            [1, 5],
            [1, 6],
            [1, 7],
            [1, 8],
            [1, 9],
            [1, 10],
            [1, 11],
            [1, 12],
            [1, 13],
            [1, 14],
            [1, 15]
        ],
        "cn-pico": [
            [2, 0],
            [2, 1],
            [2, 2],
            [2, 3],
            [2, 4],
            [2, 5],
            [2, 6],
            [2, 7],
            [2, 8],
            [2, 9],
            [2, 10],
            [2, 11],
            [2, 12],
            [2, 13],
            [2, 14],
            [2, 15]
        ],
        "cn/gpu": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "rx": [0, 2, 4, 6, 8, 10, 12, 14],
        "rx/wow": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "cn/0": false,
        "cn-lite/0": false,
        "rx/arq": "rx/wow"
    },
    "opencl": {
        "enabled": false,
        "cache": true,
        "loader": null,
        "platform": "AMD",
        "cn/0": false,
        "cn-lite/0": false
    },
    "cuda": {
        "enabled": false,
        "loader": null,
        "nvml": true,
        "cn/0": false,
        "cn-lite/0": false
    },
    "donate-level": 5,
    "donate-over-proxy": 1,
    "log-file": null,
    "pools": [
        {
            "algo": "rx/0",
            "coin": null,
            "url": "randomx-benchmark.xmrig.com:7777",
            "user": "BENTCHMARK.TEST",
            "pass": "",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false,
            "self-select": null
        }
    ],
    "print-time": 60,
    "health-print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "user-agent": null,
    "watch": true
}

**Comment by ivarsdzalbs** [comment]
Have exact same problem, can reproduce it on both 1700 and 1700x cpus.

**Comment by SChernykh** [comment]
Can you try https://github.com/SChernykh/xmrig/tree/ryzen-fix ? Compile it from source and check if it crashes.

**Comment by theshadowpeople** [comment]
It doesn't work too

**Comment by SChernykh** [comment]
We'll keep looking for a workaround then.

**Comment by maxfreemax** [comment]
it crash after 1 minute. (note algo is rx/wow)

![xmrig_wow](https://user-images.githubusercontent.com/44138963/69566415-55bb6e00-0fb7-11ea-85ac-7fef68c58b14.png)

**Comment by DiamondLovesYou** [comment]
@maxfreemax mind trying PR #1348 ?

**Comment by Possums** [comment]
Tried PR #1348, still crashing on Epyc 7551 engineering sample CPU.

**Comment by kenshirothefist** [comment]
Same issue here, can reproduce it on 1700x.

**Comment by Samoflan** [comment]
I am having the issue on my 1700x. Keeps crashing after less then a minute.

**Comment by maxfreemax** [comment]
I have update my bios. no change.
after I have install  this:
https://www.amd.com/en/support/cpu/amd-ryzen-processors/amd-ryzen-7-desktop-processors/amd-ryzen-7-1700x

after multi start of xmrig (v5.0.1) and multi crash, xmrig finish to be stable (actually 12 hours ok at 4200h/s).

after each reboot windows 10, i have to do the same multi start of xmrig(and multi crash) to have a stable xmrig.

i have not try yet proposal  #1348

**Comment by xmrig** [comment]
Disabling opcache in BIOS should fix the issue https://github.com/xmrig/xmrig/pull/1348#issuecomment-560122919

**Comment by maxfreemax** [comment]
as suggested (proposal #1348) i have disabled opcache (auto --> disabled) on motherboard BIOS
xmrig start with no crash at the first time

thanks.

**Comment by kenshirothefist** [comment]
I can confirm disabling opcache resolves the issue, but then again I only get 4650 H/s (1700X @4.0GHz), therefore I guess there is a 5-10% performance penalty when disabling opcache.

**Comment by kenshirothefist** [comment]
I wouldn't consider this as closed ... disabling opcache is only a (bad) workaround since it significantly impacts performance ...

**Comment by maxfreemax** [comment]
ok i reopen

**Comment by kimxilxyong** [comment]
Opcache disabled did not help. Segfault on 1700x after a few seconds

**Comment by tevador** [comment]
> disabling opcache is only a (bad) workaround since it significantly impacts performance

It's a hardware bug, so I don't think there is a better workaround than this. It seems that AMD has been replacing the faulty processors in some cases: https://www.reddit.com/r/Amd/comments/c3377v/ryzen_1700_segfault_rma/

**Comment by xmrig** [comment]
Try recent version with `"wrmsr": ["0xc0011020:0x0", "0xc0011021:0x60", "0xc0011022:0x510000", "0xc001102b:0x1808cc16"]` more details about MSR https://xmrig.com/docs/miner/randomx-optimization-guide/msr
Thank you.

**Comment by SChernykh** [comment]
@maxfreemax XMRig 5.5.0 has a workaround for 1st gen Ryzen/Threadripper/EPYC crashes, you should be able to mine even with enabled Opcache.
