### ISSUE TITLE
generic code for randomX

### ISSUE THREAD

**Issue by amitceder** [xmrig/xmrig#1299]
Hi,
Is there a possibility to release a generic code and not platform sepcific?
in variant 4 there was a generic one, but for randomx it seems there's a source for jit_compiler only for arm64 bit or for x86.

**Comment by SChernykh** [comment]
JIT compiler will be used on supported platform (ARM64 and x86-64), all other platforms will automatically use VM interpreter (what you call "generic code").

**Comment by amitceder** [comment]
Thanks for your quick reply.

Will this (VM interpreter) be supported in the future or already in version 5.0.0 ?

Are the relevant files for other platforms are the one starting with vm_interpreted and vm_compiled?

Amit

 �

 �

**Comment by amitceder** [comment]
more precisely - is there a define or any build instructions for other platforms?

**Comment by SChernykh** [comment]
You just build it normally, JIT compiler files are only included in the build on supported platforms. Then at runtime XMRig will check if JIT compiler is available and select VM interpreter if there is no JIT.

**Comment by amitceder** [comment]
another related question:
Is there a way to run the function "randomx_calculate_hash" which is under randomx.cpp on a separate machine? (connecting them with simple udp connection for example).

**Comment by trasherdk** [comment]
@amitceder Something like a [proxy](https://github.com/xmrig/xmrig-proxy)?

**Comment by amitceder** [comment]
not exactly. more like running a pc for the linux connectivity to the ethernet, protocol handling etc, while the other runs the virutal machine.
