### ISSUE TITLE
c++11 support in debian

### ISSUE THREAD

**Issue by lamba84** [xmrig/xmrig#130]
Hi, testing around with dev branch.
probably debian is not the most used distro for rigs, but c++11 is still an option in g++ 4.9.
Flag like this in CMakeLists.txt make build flawless:

`if(UNIX)
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
endif()`

even better would be to check g++ version and see if it required.

Thanks for great job you're doing with this software!

**Comment by xmrig** [comment]
What version of CMake you use? Probably older than 3.1, so `set(CMAKE_CXX_STANDARD 11)` doesn't work, I wasn't check minimum cmake version when add this option, I will fix it.
Thank you.

**Comment by lamba84** [comment]
yes, you are right. cmake 3.0.2 is default on debian. thanks

**Comment by xmrig** [comment]
Fixed.
