### ISSUE TITLE
Dev donation unpauses

### ISSUE THREAD

**Issue by jagerman** [xmrig/xmrig#1300]
If xmrig is paused and the donation timer kicks in then xmrig unpauses mining for the dev donation, then returns to the configured pool.

The internal state, however, isn't quite right: the "p" key to pause doesn't work (presumably because it thinks it is already paused) and hitting "r" print "resumed" (though its already mining).

A couple of potential ideas:
- the donation mining should just not start when currently paused
- pausing should also pause the donation timer

**Comment by xmrig** [comment]
Confirmed. Thank you.

**Comment by xmrig** [comment]
What algorithm do yo mine? I start fixing this issue, and yes miner connects to donation and then switch back to user pool, but it not unpause miner, so is only negative impact I lose this donation round, proper fix however required a lot of changes.

Miner handle donation job like regular user job (with some extra logic, but it not important in this case), and regular jobs not unpause the miner (CPU, GPU is still idle).
Thank you.
