### ISSUE TITLE
light mode or randomx

### ISSUE THREAD

**Issue by axsoftshi** [xmrig/xmrig#1308]
How to make the compiled program use light mode without randomx, enough memory in time and without randomx

**Comment by xmrig** [comment]
If you like complete disable RandomX support use option cmake option `-DWITH_RANDOMX=OFF` full list of options: https://xmrig.com/docs/miner/cmake-options

Light mode useless for mining, there is no direct option to enable this mode, miner will switch to light mode if fails to allocate dataset.
Thank you.

**Comment by 2010phenix** [comment]
> Light mode useless for mining, there is no direct option to enable this mode, miner will switch to light mode if fails to allocate dataset.

confirm about speed but is some.... one off.., have few server with CPU 24 core and 8GB but 6-7GB used by Oracle base+system, CPU load only with full backup DB(1 hrs), other time CPU load 2-5%, maybe copy code part with **fails allocate dataset**(light mode) and do with cmake option compile miner only with light mode?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/blob/master/src/crypto/rx/RxDataset.cpp#L43 after removing this line `allocate(hugePages);` miner will always use light mode.
Thank you.

**Comment by xmrig** [comment]
In next version it will be available via config or command line https://github.com/xmrig/xmrig/issues/1318#issuecomment-559676080

**Comment by 2010phenix** [comment]
@xmrig, man you are code master!
Thx.
