### ISSUE TITLE
GetLargePageMinimum is not supported by Windows XP

### ISSUE THREAD

**Issue by peredozo** [xmrig/xmrig#1314]
Fast slove

src\crypto\common\VirtualMemory_win.cpp (167):

`#if defined(_WIN64)`
`    const size_t min = GetLargePageMinimum();`
`#else`
`    const size_t min = 0;`
`#endif`

Maybe it have a more correct way?

**Comment by hotaru2k3** [comment]
> Maybe it have a more correct way?

there is no more correct way. Windows XP has been EOL for more than half a decade.

**Comment by peredozo** [comment]
> Windows XP has been EOL for more than half a decade.
Like a 32-bit apps. But they still exist.

**Comment by hotaru2k3** [comment]
most 32-bit apps don't have severe security vulnerabilities that have been known and not fixed for 5 years.
