### ISSUE TITLE
[questions] alternative approaches to mine RandomX?

### ISSUE THREAD

**Issue by Josevora** [xmrig/xmrig#1315]
Hello guys,

I've been wondering about alternative ways to mine RandomX (still theoretical) and I wanted to consult with you to see if it is worth it even my time...

1 - Allocating the data on the GPU(s)[because of GDDR6 or HBM2] and mining with CPU...
- Is it possible? (probably yes)
- Is it efficient? (probably no...but what would be the bottlenecks ?)
- Can we use multiple GPUs and access the data in parallel? (probably yes, but will it help?)

2 - Having the Work split into categories, like GPU Work vs CPU Work...
- Is it possible? (probably yes)
- Is it efficient? (probably no...but what would be the bottlenecks ?)
- Can we just let the CPU handle the part of the Algo that is specific for CPU and the GPU handle more generic Tasks?

Thank you in advance!

**Comment by hvr1** [comment]
Hi Jose, Totally unrelated. But I would be grateful if you could help me out with how to run xmrig on a Xeon Phi 7220a that I have?

**Comment by CoCuCkuH-007** [comment]
Hi Jose.. i come here with the same question - can you explait to a no linus user how you was able to run xmrig on a PCI-E xeon PHI?
