### ISSUE TITLE
RandomX crash on ARM

### ISSUE THREAD

**Issue by willwill85** [xmrig/xmrig#1318]
I build 5.0.0 version 
and test the application
After the line “ rx allocated 2336MB（2080+256） huge pages 0%/1168 +JIT（3ms）”
the application is killed

CPU is  ARM （4 core A53） 512MB RAM

**Comment by SChernykh** [comment]
Maybe because 512 MB RAM is not enough for mining? XMRig will try to mine only with 256 MB in light mode, but even this can fail if you only have 512 MB.

**Comment by willwill85** [comment]
> Maybe because 512 MB RAM is not enough for mining? XMRig will try to mine only with 256 MB in light mode, but even this can fail if you only have 512 MB.

how can i switch to light mode?  with what parameters? Thanks

**Comment by SChernykh** [comment]
XMRig tries to switch to light mode automatically but fails in your case. You probably need to add 512 MB swap file to make it work.

**Comment by xmrig** [comment]
In next version v5.1 (code available in dev branch) added new option `mode` for RandomX, with 3 possible values:

- `auto` new behavior, miner will not try allocate dataset if system has not enough free memory memory.
- `fast` old behavior, miner will try allocate dataset and only if it fails and system did't kill miner, switch to light mode.
- `light` force light (slow) mode.

However, `auto` mode required additional testing.

In addition miner will print information about memory on startup and this information also added to API.
Thank you.

**Comment by willwill85** [comment]
> In next version v5.1 (code available in dev branch) added new option `mode` for RandomX, with 3 possible values:
> 
> * `auto` new behavior, miner will not try allocate dataset if system has not enough total memory.
> * `fast` old behavior, miner will try allocate dataset and only if it fails and system did't kill miner, switch to light mode.
> * `light` force light (slow) mode.
> 
> However, `auto` mode required additional testing.
> 
> In addition miner will print information about memory on startup and this information also added to API.
> Thank you.

I built 5.1 version, and test light mode and auto mode.
But the application killed..

**Comment by willwill85** [comment]
> In next version v5.1 (code available in dev branch) added new option `mode` for RandomX, with 3 possible values:
> 
> * `auto` new behavior, miner will not try allocate dataset if system has not enough total memory.
> * `fast` old behavior, miner will try allocate dataset and only if it fails and system did't kill miner, switch to light mode.
> * `light` force light (slow) mode.
> 
> However, `auto` mode required additional testing.
> 
> In addition miner will print information about memory on startup and this information also added to API.
> Thank you.

I built 5.1.1 version, and test light mode and auto mode.
But the application killed..

**Comment by SChernykh** [comment]
With only 512 MB RAM you have to add swap file (512 MB or bigger) to fix the crash. You just don't have enough memory for XMRig even in light mode.

**Comment by 1265578519** [comment]
windows版本randomx经常导致突然切换 rx/0 算法后爆掉内存引起死机

关键日志
[2022-03-09 00:58:48.923] randomx init dataset algo rx/0 (2 threads) seed 32edb000247493a7...
[2022-03-09 00:58:48.923] randomx allocated 2336 MB (2080+256) huge pages 0% 0/1168 +JIT (0 ms)
[2022-03-09 00:59:12.524] randomx dataset ready (23601 ms)
[2022-03-09 00:59:48.667] net new job from mine.c3pool.com:80 diff 8532 algo rx/0 height 2575216 (12 tx)
[2022-03-09 00:59:48.889] net dev donate finished
[2022-03-09 00:59:48.898] net new job from mine.c3pool.com:17777 diff 2897 algo astrobwt height 6665492
[2022-03-09 00:59:48.912] cpu stopped (5 ms)

配置文件randomx字段
```
    "randomx": {
        "init": -1,
        "init-avx2": 0,
        "mode": "auto",
        "1gb-pages": false,
        "rdmsr": true,
        "wrmsr": true,
        "cache_qos": false,
        "numa": true,
        "scratchpad_prefetch_mode": 1
    },
```
https://github.com/xmrig/xmrig/issues/1318#issuecomment-559676080
https://xmrig.com/docs/miner/randomx-optimization-guide
https://xmrig.com/docs/miner/command-line-options
找到了些资料，表明出在 Windows 上 4GB 内存可能没有足够的内存运行系统进程，auto（fast）模式下单路CPU需要2080+256MB开销。

默认值auto，可选值auto, fast, light
所以解决办法就是改成 light ，或者禁掉rx/0算法，，，此时运行过程就不会占用任何内存了。
性能对比，差了快十倍
auto（fast）模式下570H/s
light模式下74H/s

**Comment by UnixCro** [comment]
> XMRig will try to mine only with 256 MB in light mode

What exactly is light mode? How does XMRIG work in it compared to fast mode? Why does XMRIG use 2MB of RAM when it already has 2MB of L3 cache? And why doesn't XMRIG access the 2MB of L2 cache directly as L3? This is especially helpful with M1. Why don't Apple Silicon users get a message that MSR hasn't been set?

Sorry for all the questions.

Thank you for everything!
