### ISSUE TITLE
RandomX and AMD HD7950 (OpenCL) on Ubuntu 18.04

### ISSUE THREAD

**Issue by RipZ** [xmrig/xmrig#1319]
XMRig/5.0.2-dev. Testpool on rx.minexmr.com:4444

Hashrate on both threads is zero. xmrig run with arguments -
xmrig -a rx/0 --opencl --opencl-no-cache --donate-level=1 --no-cpu -o rx.minexmr.com:4444 -u 47wcnDjCDdjATivqH9GjC92jH9Vng7LCBMMxFmTV1Ybf5227MXhyD2gXynLUa9zrh5aPMAnu5npeQ2tLy8Z4pH7461vk6uo

![Screenshot from 2019-11-27 11-52-45](https://user-images.githubusercontent.com/54253/69708518-cf18a500-110c-11ea-846d-075c59a964c7.png)

**Comment by bizlevel** [comment]
Which one AMD driver?
