### ISSUE TITLE
issue with --max-cpu-usage=

### ISSUE THREAD

**Issue by ragekillen** [xmrig/xmrig#132]
hello i have set my .bat file with these settings
xmrig -o stratum+tcp://pool.minexmr.com:4444 -u user -p x --donate-level=5 -t 4 --max-cpu-usage=50

but my cpu is still at 100%, am i configuring it wrong or is there something wrong with the program. 

ps it was working correctly the first day but then stopped

**Comment by xmrig** [comment]
You manually specify threads count `-t 4` it overrides `--max-cpu-usage`.
Thank you.

**Comment by van7hu** [comment]
My command is:
`xmrig -o pool.supportxmr.com:5555 -u [address] -p x --donate-level=5 --max-cpu-usage=50
`
and, cpu usage is 100% always.

**Comment by van7hu** [comment]
Even, if I have 
`--max-cpu-usage=10`

The Cpu is always 100%

**Comment by xmrig** [comment]
How many cores do you have? this option just change thread count.
If you have just one core, will used one thread, so it will be always 100%
For 2 cores, minimum is 50%
For 4, 25%.
