### ISSUE TITLE
Static build with TLS support

### ISSUE THREAD

**Issue by miki-bgd-011** [xmrig/xmrig#1320]
It's about time someone figures out how to compile a fully static build on Alpine linux with TLS support. I'm giving a 2 XMR bounty to whoever provides instructions here. 

Xmrig would you like to act as an escrow?

**Comment by 0xlang** [comment]
@miki-bgd-011 I have compiled the source fully static with TLS support. I can provide you the binary through a way of contact and I don't need 2 XMR for that.

**Comment by icodeface** [comment]
add
```
# Compile and install the static OpenSSL library
ENV OPENSSL_VERSION=1.1.1
RUN wget -O /tmp/openssl-${OPENSSL_VERSION}.tar.gz https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz && \
    cd /tmp && \
    tar xzvf /tmp/openssl-${OPENSSL_VERSION}.tar.gz && \
    rm /tmp/openssl-${OPENSSL_VERSION}.tar.gz && \
    cd /tmp/openssl-${OPENSSL_VERSION} && \
    ./Configure -static --static no-shared no-async no-hw no-zlib no-pic no-dso \
                no-engine no-threads linux-x86_64 && \
    make ${MAKE_ARGS} && \
    make install && \
    cd /tmp && \
    rm -rf /tmp/openssl-${OPENSSL_VERSION}
```
to your dockerfile should works

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/build/alpine
