### ISSUE TITLE
rx dataset uses cpu thread count instead of config thread count

### ISSUE THREAD

**Issue by YetAnotherRussian** [xmrig/xmrig#1326]
Cpu thread count: 24
Config file params:
"rx": [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]

Code:
int m_threads   = -1;

return m_threads < 1 ? static_cast<uint32_t>(Cpu::info()->threads()) : static_cast<uint32_t>(m_threads);

Miner output (cut-off):
[2019-11-28 17:18:17.268]  rx   init dataset algo rx/0 (24 threads) 
[2019-11-28 17:18:19.674]  cpu  use profile  rx  (12 threads) scratchpad 2048 KB
[2019-11-28 17:18:19.676]  cpu  READY threads 12/12 (12) huge pages 100% 12/12 memory 24576 KB (1 ms)

This makes a slow CPU or VM dead for some time. Maybe a better solution is to use thread count from config or make a separate config param.

**Comment by SChernykh** [comment]
Dataset initialization doesn't need 2 MB memory, so it can be parallelized across all available cores. CPU/VM shouldn't die or freeze when all cores are used, so it's some misconfiguration on your side.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/blob/master/src/config.json#L18 you can change `"init": -1,` (auto = all threads) to another thread count.
Thank you.
