### ISSUE TITLE
SOS,how to config 5.0?

### ISSUE THREAD

**Issue by smzwsz** [xmrig/xmrig#1330]
I used xmrig-proxy.

Here is my xmrig config.json:

"cpu": {
        "enabled": true,
        "huge-pages": true,
        "hw-aes": null,
        "priority": null,
        "memory-pool": false,
        "max-threads-hint": 50,
        "asm": true,
        "argon2-impl": null,
        "cn/0": false,
        "cn-lite/0": false
    },
    
"opencl": {
        "enabled": false,
        "cache": true,
        "loader": null,
        "platform": "AMD",
        "cn/0": false,
        "cn-lite/0": false
    },
    
"cuda": {
        "enabled": false,
        "loader": null,
        "nvml": true,
        "cn/0": false,
        "cn-lite/0": false
    },
    
"donate-level": 5,
    
"donate-over-proxy": 1,
    
"log-file": null,
    
"pools": [
        {
            "algo": null,
            "coin": "monero",
            "url": "hk01.supportxmr.com:3333",
            "user": "YOUR_WALLET_ADDRESS",
            "pass": "x",
            "rig-id": null,
            "nicehash": true,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false,
            "self-select": null
        }
    ],
    
"print-time": 60,
    
"health-print-time": 60,
    
"retries": 5,
    
"retry-pause": 5,
    
"syslog": false,
    
"user-agent": null,
    
"watch": true
}

That's something wrong.how to config it?

**Comment by SChernykh** [comment]
It's probably a typo somewhere. Try to use https://xmrig.com/wizard
