### ISSUE TITLE
ocl_generic_rx_generator.cpp: config->ScratchpadL3_Size random value

### ISSUE THREAD

**Issue by komatom** [xmrig/xmrig#1331]
This below is output of inialization of ocl_generic_rx_generator.cpp:

device_mem and dataset_mem are in Megabytes.
per_thead is in bytes

Is it normal config->ScratchpadL3_Size to varies between 2129920, 1081344 and 294912 for the different cards, which btw are the same model

`
const auto config      = RxAlgo::base(algorithm);
const uint32_t per_thread_mem = config->ScratchpadL3_Size + 32768;
`

===========
device mem: 4096 : dataset_mem: 2207
per_thread: 2129920

device mem: 4096 : dataset_mem: 2207
per_thread: 2129920

device mem: 4096 : dataset_mem: 2207
per_thread: 2129920

device mem: 4096 : dataset_mem: 2207
per_thread: 1081344

device mem: 4096 : dataset_mem: 2207
per_thread: 1081344

device mem: 4096 : dataset_mem: 2207
per_thread: 1081344

device mem: 4096 : dataset_mem: 2207
per_thread: 1081344

device mem: 4096 : dataset_mem: 2207
per_thread: 1081344

device mem: 4096 : dataset_mem: 2207
per_thread: 1081344

device mem: 4096 : dataset_mem: 2207
per_thread: 1081344

device mem: 4096 : dataset_mem: 2207
per_thread: 1081344

device mem: 4096 : dataset_mem: 2207
per_thread: 294912

device mem: 4096 : dataset_mem: 2207
per_thread: 294912

device mem: 4096 : dataset_mem: 2207
per_thread: 294912

device mem: 4096 : dataset_mem: 2207
per_thread: 294912

device mem: 4096 : dataset_mem: 2207
per_thread: 294912

device mem: 4096 : dataset_mem: 2207
per_thread: 294912

device mem: 4096 : dataset_mem: 2207
per_thread: 294912

device mem: 4096 : dataset_mem: 2207
per_thread: 294912

**Comment by SChernykh** [comment]
These are per thread requirements for rx/0, rx/wow, rx/arq algorithms. It configures them one after another.

**Comment by komatom** [comment]
Thanks, for clarifying.
