### ISSUE TITLE
config.json<offset:1680>: "Invalid value." RandomX with monero

### ISSUE THREAD

**Issue by smzwsz** [xmrig/xmrig#1338]
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "version": 1,
    "background": false,
    "colors": true,
    "randomx": {
        "init": -1,
        "numa": true
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "hw-aes": null,
        "priority": null,
        "memory-pool": false,
        "max-threads-hint": 50,
        "asm": true,
        "argon2-impl": null,
	"rx/0": [-1, -1, -1, -1],
     },
    "opencl": {
        "enabled": false,
        "cache": true,
        "loader": null,
        "platform": "AMD",
        "cn/0": false,
        "cn-lite/0": false
    },
    "cuda": {
        "enabled": false,
        "loader": null,
        "nvml": true,
        "cn/0": false,
        "cn-lite/0": false
    },
    "donate-level": 1,
    "donate-over-proxy": 1,
    "log-file": null,
    "pools": [
        {
            "algo": null,
            "coin": "monero",
            "url": "192.168.10.58:9999",
            "user": "1",
            "pass": "x",
            "rig-id": null,
            "nicehash": ture,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false,
            "self-select": null
        }
    ],
    "print-time": 60,
    "health-print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "user-agent": null,
    "watch": true
}

How To resolve

**Comment by xmrig** [comment]
`"nicehash": ture,` should be `true`, also if on another end is xmrig-proxy don't need change this option, it will be done automatically.
Thank you.

**Comment by smzwsz** [comment]
Yes ,it's my mistake
But," end of file" now

**Comment by norsehealer** [comment]
"self-select": null
}
],
"print-time": 60,

the ] should be {
