### ISSUE TITLE
Add more pools

### ISSUE THREAD

**Issue by minerteam** [xmrig/xmrig#134]
Good morning, 
how can I add another pool in the config.json file in case the first one fails? 
Thank you.

**Comment by xmrig** [comment]
Something like that:
```json
    "pools": [
        {
            "url": "primary:5555",
            "user": "",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        },
        {
            "url": "backup:5555",
            "user": "",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        }
    ]
```

**Comment by xmrig** [comment]
Duplicate #90

**Comment by minerteam** [comment]
Adding another pool in config.json gives me this error: [pool.xxxxxx.com:5555] "No login / password especified", code -1 
Never connect to the primary pool, connect to the backup pool.

**Comment by minerteam** [comment]
It was my fault, I solved it

**Comment by sailei00** [comment]
xmrig always connect to the broken primary pool ,never try to connect the backup pool. why
