### ISSUE TITLE
max-threads-hint issue [VERY IMPORTANT]

### ISSUE THREAD

**Issue by XeroProg** [xmrig/xmrig#1342]
Hi.When i enter 100 in max-threads-hint it doesn't work and it use just 75% of my system.
my system has 4 cores
for 25% , 50% , 75% it doesn't have any problem but for this one (100%) it doesn't work and it just uses 75% of my computer cpu
what is the problem ? how i can fix it?

**Comment by xmrig** [comment]
Did you read docs carefully? https://github.com/xmrig/xmrig/blob/master/doc/CPU_MAX_USAGE.md likely your CPU limited by L2/L3 cache.
Thank you.
