### ISSUE TITLE
XMR RandomX Radeon 7970 succesfuly initialise but crash the driver ( blackscreen for one second ) and is not mining

### ISSUE THREAD

**Issue by deuws** [xmrig/xmrig#1346]
XMR RandomX Radeon hd 7970 ghz  succesfuly initialise but crash the driver ( blackscreen for one second ) and is not mining
I tried with many different drivers

Latest build and windows 10 updated

**Comment by Ronnier33** [comment]
the same with hd 7750 1G ...

**Comment by badbulgarian** [comment]
The same with Radeon hd 7970...

**Comment by dedizones** [comment]
same with AMD 280X
i hae notification: "Default Radeon WattMan Settings Have been Restored due to...."

**Comment by dedizones** [comment]
I put in the configuration file: database host = true the graphics card loads well and the memory but as soon as I look at the hashrate still in n/a 
I lower the intensity, read on a thread always the same...
someone has found a solution since?
