### ISSUE TITLE
Six GPU Vega 56 Hashrate issue

### ISSUE THREAD

**Issue by gotminer** [xmrig/xmrig#1347]
Only getting around 500ish H/s on each thread. I've adjusted the intensity with no success. It will run stable up to about 1200, but it doesn't change the hash rate. I've also tested worksize at 8 and 16 with no change in hash rate.

Screenshots and full config file are attached.

[config.txt](https://github.com/xmrig/xmrig/files/3907714/config.txt)

![Capture](https://user-images.githubusercontent.com/44104559/69907751-fc817f00-13a8-11ea-8db7-bdf5a05c476e.JPG)
![sample](https://user-images.githubusercontent.com/44104559/69907752-ff7c6f80-13a8-11ea-941b-119ec524155a.JPG)

**Comment by wisnia37** [comment]
I have the same trouble. Did you solve it?

**Comment by torreto12** [comment]
I have the same trouble. Did you solve it?

**Comment by gotminer** [comment]
No I haven't figured out how to fix the issue. It has been said that mining randomx with gpu is a waste of electricity. Is this possibly because it is not possible to achieve the same hash rate with the same hardware mining the randomx algo? I have experienced a 5% decline in hash rate after other xmr hard forks, but never anything this dramatic. This drop is approx. 45%.
