### ISSUE TITLE
Add "uptime" 

### ISSUE THREAD

**Issue by mnik247** [xmrig/xmrig#135]
Is possible add "uptime" to stat row?
Now: [2017-09-27 09:17:13] speed 2.5s/60s/15m 252.6 252.2 252.2 H/s max: 253.6 H/s
New: [2017-09-27 09:17:13] speed 2.5s/60s/15m 252.6 252.2 252.2 H/s max: 253.6 H/s uptime HH:MM

**Comment by ketamina** [comment]
it will be very helpful!
