### ISSUE TITLE
Crash since moved to randomx

### ISSUE THREAD

**Issue by christgelinas** [xmrig/xmrig#1360]
FX8300 and Vega frontier
crash after 5-30 minutes
never had problem before moving to randomx algo

**Comment by xmrig** [comment]
Please show miner log.
Thank you.

**Comment by christgelinas** [comment]
where is is located  ? or how to enable ?

**Comment by christgelinas** [comment]
updated amd driver to 19.11 and disabling cpu overclock seam to solve problem.

**Comment by christgelinas** [comment]
my problem is cpu mining, returning to stock clock and voltage  fix partialy.  had crash after 24h

**Comment by christgelinas** [comment]
now testing other miner
