### ISSUE TITLE
light mode for opencl ?

### ISSUE THREAD

**Issue by thagrisu** [xmrig/xmrig#1361]
Hey is there something like a light mode for opencl machines ? 
Even when its slow .. maybe interesting for dualmining options ? 

thanks

**Comment by xmrig** [comment]
Miner can use dataset from system memory, `dataset_host` option, it save 2080 MB of GPU memory with performance impact as well.
Thank you.

**Comment by thagrisu** [comment]
thanks .. does this create one 2080 file for every gpu in host memory then, or do they share one dataset file ?

Is it possible to run a light version in gpu memory ? ( with 256 MB like light version for cpu ? ) since my gpus only have 600 MB free space.

**Comment by xmrig** [comment]
One dataset shared across all GPUs and CPU, but true light mode for GPUs not supported and will not be supported.
Thank you.

**Comment by thagrisu** [comment]
ok thanks.
