### ISSUE TITLE
faild to allocate RandomX dataset , switching to slow mode!!!

### ISSUE THREAD

**Issue by vivin321** [xmrig/xmrig#1362]
after compiling the miner from v5.0.1 source on windows and start mining I got this message
failed to allocate RandomX dataset, switching to slow mode!!!
with very little hash a rate 

![Capture](https://user-images.githubusercontent.com/36386618/69922632-aeeb3c00-14a6-11ea-8cc4-d4d905c63d03.PNG)

but when I tested the pre-launched miner 
I got a very good hash rate without this message 

![Capture3](https://user-images.githubusercontent.com/36386618/69922636-b90d3a80-14a6-11ea-9dbc-7d92de51b788.PNG)

the command I used for compiling the miner is :
cmake .. -G "Unix Makefiles" -DXMRIG_DEPS=c:/xmrig-deps/gcc/x86 -DWITH_TLS=OFF
cmake .. -DWITH_CN_GPU=OFF
cmake .. -DWITH_EMBEDDED_CONFIG=ON
cmake .. -DWITH_RANDOMX=ON
make

where is the wrong with my compiling

**Comment by xmrig** [comment]
On first screenshot is 32 bit version.
Thank you.

**Comment by vivin321** [comment]
> On first screenshot is 32 bit version.
> Thank you.

do you mean that RandomX Algo. works only on 64 bit OS?
I tested it on a PC "with 3 GB memory and 32 bit OS"  but the miner ran on a slow mode !!!
check this 
![Capture](https://user-images.githubusercontent.com/36386618/69936778-774db580-14e1-11ea-9b55-13246e37780a.PNG)

what is the best alternative Algo. to get the best hash rate from 32bit PCs?
