### ISSUE TITLE
v5.1.0 Linux "nice" command doesn't work.

### ISSUE THREAD

**Issue by Desmond168** [xmrig/xmrig#1363]
Hi 
The V5.1.0 is pretty good for RandomX, but I could not use "nice" command to control process priority anymore when I upgrade to V5.1.0.
Please help me to figure out this problem.

※The V5.0.1 & V5.0.0 is workable about "nice" command.
![not_work](https://user-images.githubusercontent.com/40748523/69924047-360ad500-14e4-11ea-8127-5c9a2bd7a35a.jpg)
![workable](https://user-images.githubusercontent.com/40748523/69924048-360ad500-14e4-11ea-9911-5c41f378f2e9.jpg)

**Comment by xmrig** [comment]
Actually it strange nothing related to this changed, I just checked and `nice -n 19` works fine. Also there option `"priority": 0,` in `cpu` object, it works like `nice -n 19` for mining threads, but not change  niceness of main thread.
Thank you.

**Comment by Desmond168** [comment]
Hi Sir
Thanks for your quickly reponse.
I have tried the option " priority": 0, but top command show nice values are "-15".
Do you have any recommendations? I would like to nice value is "-19" show on top command.

![nice_issue](https://user-images.githubusercontent.com/40748523/69927178-1da1b700-14f2-11ea-94ad-d43aec71a9ae.jpg)

**Comment by xmrig** [comment]
Fixed in dev branch, if priority not set in config `"priority": null,` miner not will not change any priority by self.
If priority set in config main miner thread will always use higher priority than mining threads.
Thank you.

**Comment by xmrig** [comment]
Fix included into v5.1.1 release https://github.com/xmrig/xmrig/releases/tag/v5.1.1
Thank you.
