### ISSUE TITLE
[Request] Add schedule to enable/disable mode of work

### ISSUE THREAD

**Issue by shehi** [xmrig/xmrig#1366]
If possible, it'd be great to have some kind of scheduler in config.json, which would enable us to schedule the hours of the day when CPU/OpenCL/CUDA gets enabled or disabled. At work, I'd like to get my machine into Cuda mining when I am afk during evenings/nights, and off of it when I am back in the office during daytime. Thanks.

**Comment by xmrig** [comment]
It can be done by using external tools via HTTP API, `GET /1/config` and `POST /1/config`, or by replacing config file.
