### ISSUE TITLE
Question: RandomX on DDR3 with speed 1600 vs 1866

### ISSUE THREAD

**Issue by minzak** [xmrig/xmrig#1369]
Any one have DDR3 both speed 1600 and 1866?
To check hashrate?

I have DDR3 with 1600 speed:
```
 * CPU          Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz (2) x64 AES
                L2:4.0 MB L3:40.0 MB 16C/32T NUMA:2
 * MEMORY       7.6/251.8 GB (3%)
...
 speed 10s/60s/15m 5663.1 5677.9 n/a H/s max 5682.0 H/s
```

How much Hashes will be with DDR3 1866 ?
Thanks.

**Comment by pawelantczak** [comment]
Hi.
Your CPU doesn't support 1866.

**Comment by bizlevel** [comment]
E5 v1 - yes maximum 1600.
But E5 v2 some CPUs - can use at maximum:
Intel XeonE5-2609 v2 processor 1333
Intel XeonE5-2630 v2 processor 1600
Intel XeonE5-2650 v2 processor 1866

But how much will be different on 1333/1600/1866 ?

**Comment by Ca2F** [comment]
I have a single socket 2680 v1 server with 1600Mhz dual channel i get 279 H/s with one thread.
On my Dual socket 2680 v2 server with 1866Mhz quad channel i get 550 H/s with one thread. 
So there is a decent difference, i am running right now 8 threads on each 2680 v2 right now in vm's on ESXI and the total hashrate is  7400 H/s.

**Comment by x151973** [comment]
> 
> 
> I have a single socket 2680 v1 server with 1600Mhz dual channel i get 279 H/s with one thread.
> On my Dual socket 2680 v2 server with 1866Mhz quad channel i get 550 H/s with one thread.
> So there is a decent difference, i am running right now 8 threads on each 2680 v2 right now in vm's on ESXI and the total hashrate is 7400 H/s.

Quick question, for dual socket system the term dual or quad channel mean each socket or both? in another word, assume one socket have only one slot each channel,  in your current successful quad channel implementation , how many physical mems you inserted into mobo?4 or 8?

**Comment by Ca2F** [comment]
Quad channel is the memory configuration, dual socket refers to that i have two cpu's on that motherboard.  
https://en.wikipedia.org/wiki/Quad-channel_architecture
