### ISSUE TITLE
AES / AVX Optimizations: any way to improve performance

### ISSUE THREAD

**Issue by erotavlas85** [xmrig/xmrig#137]
Hi,
at the moment xmrig is the fastest CPU mining for monero. It uses AES instructions that are 128 bit registers, what about using AVX 2 instructions that are 256 bit registers?
Some miners for other cryptocurrencies use them [link](https://github.com/elmad/darkcoin-cpuminer-1.3-avx-aes).
Thank you

**Comment by xmrig** [comment]
AVX won't help, other people try use AVX2, but it slower.
SSE2 for renaming parts of the loop won't help too.
128 bit registers used only for AES related parts, because there no choice.

Bottleneck for Monero is memory/cache latency.
Thank you.

**Comment by erotavlas85** [comment]
Ok I see, so it seems that we cannot get any further improvement.
Did you tried to compile with Profile-Guide Optimization (pogo)?

**Comment by xmrig** [comment]
I was use in first releases, I stop do it long time ago, there is no noticeable difference.

**Comment by erotavlas85** [comment]
Ok thank you.
