### ISSUE TITLE
Slow Crash on 5.1.0 - Memory Leakage??

### ISSUE THREAD

**Issue by NCarter84** [xmrig/xmrig#1370]
Ryzen Rig - Windows 1903, 12 gb RAM, running XMRIG 5.1

5 different times - the miner has been "shut off/closed" - GPU miners still running, no issue. I've fallen back to 5.0 and have been stable for 2 hours now... 

Also, Intel CPU, i7 xxx 16 GB RAM, Running XMRIG 5.1

Logged into PC to find a slow decrease in mining speed over time.. Went from 1.9 khs down to under 500 hs... Restarted miner, back to 1.9 khs

**Comment by JeffreyChu2009** [comment]
Similar crashing issues for the radical 5.1.0 version on TR2920X@3.9GHz with 64GB DDR4-3200@2933 system.
Using back to 5.0.1-- even though the hashrate is about 3% lower than the latest version.

**Comment by FabioFrmg** [comment]
Similar issue here. 
Most of my miners auto shutdown after a few minutes mining with V5.1.0

**Comment by xmrig** [comment]
v5.1.1 released https://github.com/xmrig/xmrig/releases/tag/v5.1.1 no changes in config file required, please confirm is this issue fixed or not.
Thank you.

**Comment by NCarter84** [comment]
Has not been fixed. Ran for under 3 hours prior to shutting down at unknown time.

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/randomx-stability-troubleshooting-guide
