### ISSUE TITLE
Compile with VS2019 error, new libuv-1.33

### ISSUE THREAD

**Issue by ValoWaking** [xmrig/xmrig#1376]
Hi i tried to compile xmrig 5.1 with VS2019 + xmrig-deps-3.5. But have error about libuv. I think your libuv compiled with VS2017? I can't compile last libuv 1.33.1 with VS2019. Can you help me?

**Comment by xmrig** [comment]
Seems recent VS2019 update breaks libs compatibility again, libuv compiled for earlier VS2019 version.
Thank you.

**Comment by ValoWaking** [comment]
Why you didn't update libuv to last ver.1.33.1 ?

**Comment by ValoWaking** [comment]
and what version of VS2019 you use?
