### ISSUE TITLE
Information: Where can I find detailed documentation on the settings in config.json

### ISSUE THREAD

**Issue by kio3i0j9024vkoenio** [xmrig/xmrig#1378]
There are lots of configurable settings in the config.json file.

https://github.com/xmrig/xmrig/blob/master/src/config.json

Where can I find detailed documentation on what the settings do?

**Comment by xmrig** [comment]
I still have no time to describe all options (it in TODO for long time)

* API settings https://github.com/xmrig/xmrig/blob/master/doc/API.md
* CPU settings https://github.com/xmrig/xmrig/blob/master/doc/CPU.md
* Most of global config options has same name with command line options, available via `--help` or in README.
* Search in issues.

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/config
