### ISSUE TITLE
 ocl  error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram

### ISSUE THREAD

**Issue by redmac68** [xmrig/xmrig#1380]
Updated from 5.1.0 to 5.1.1 and now get " ocl  error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram". Was OK. GPUs are rx 470s

**Comment by corgiRex** [comment]
Hi, 
I have the same problem "ocl error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram".
I have HP ProBook 4530s with dGPU - AMD, Win 10.

![Snímka](https://user-images.githubusercontent.com/62467683/77225917-1c18ff00-6b74-11ea-94a7-2a96b2a9c722.PNG)

Full listing
[ocl_error.txt](https://github.com/xmrig/xmrig/files/4362822/ocl_error.txt)

What can I do ?

**Comment by SChernykh** [comment]
@corgiRex Your GPU (Radeon HD 7400M) doesn't support 64-bit floating point, so it can't run RandomX.

**Comment by corgiRex** [comment]
@SChernykh 
When i install Win 10  32-bit and run XMRig 5.5.0 32-bit,
will it work with my GPU ?

**Comment by bizlevel** [comment]
similar issues - https://github.com/xmrig/xmrig/issues/1734
