### ISSUE TITLE
Ryzen 3600 XMRIG crashes after a few seconds

### ISSUE THREAD

**Issue by kike818** [xmrig/xmrig#1384]
Hi Guys,

I am using xmrig v5.1.1, The miner crashes after a few seconds of mining.
Had same issue with version V5.1.0 and V5.0.1 
Large pages are enabled and virtual memory is at 8gb min 24gb Max

PC is the following
Ryzen 3600
Asus X470 mini itx
16GB or 3000Mhz memory
GTX 1070 Ti

![Capture](https://user-images.githubusercontent.com/47010842/70202789-94e07200-16cf-11ea-9247-b31a1b846d1a.PNG)

**Comment by xmrig** [comment]
It might be general stability issue especially if v5.0.1 affected too, please check your CPU temperatures, remove overclocking, increase memory timings, try move memory sticks to place recomented by motherboard manual, for example from A1 B1 to A2 B2.
Thank you.

**Comment by FabioFrmg** [comment]
Something happened after change for RandomX algo specialy with AMD Ryzens. 
Im not mining from 30/11.
Many computers in my farm have the same issue here. 
xmrig.exe process autoclose after a little time of mining 
No matter if you use default system settings without overclock and good temps.

**Comment by aa-delite** [comment]
It's ryzen segmentation fault issue. They think it only affects ryzen 1xxx series, but it's not. There are problems on different ryzen machines.
If you can find "opcache" in BIOS, you're lucky. You can disable it and everything will be ok. There is no another solution for today. You can also install latest amd chipset drivers and reboot few times. Sometimes it works for a while till next boot.

**Comment by list1999** [comment]
The system on Ryzen 1600 xmrig 5.1 disabling "opcache" in BIOS did not help me, but xmrig 5.1.1 works for 12 hours so far.

**Comment by FabioFrmg** [comment]
> Sometimes it works for a while till next boot.
Why not make xmrig.exe compatible as windows service? 
In this way will be possible to set autorestart process forever.

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/randomx-stability-troubleshooting-guide
