### ISSUE TITLE
system hangs for 10 sec and miner consume all memory and cpu

### ISSUE THREAD

**Issue by vivin321** [xmrig/xmrig#1385]
hello
I edit the "max-threads-hint" and make the value  25
but when running the miner my system hangs and I can not do anything to stop it
the miner consume 100% of CPU and memory at the start of work 
especially when a certain line show up 
after 10 sec it dropped down to the value I determined in the config file but the system keep hang a little bit
How to fix this?

![Capture](https://user-images.githubusercontent.com/36386618/70210257-ea059d80-173a-11ea-8f79-037ae37a1073.PNG)

**Comment by 2010phenix** [comment]
confirm, only CPU with AES
miner start with 100% CPU load
after few sec go to config param (in my case 50% CPU load)

reproduce:
1.
option(WITH_LIBCPUID        "Enable libcpuid support" OFF)
option(WITH_HWLOC           "Enable hwloc support" OFF)
2. 
`
    "randomx": {
        "init": -1,
        "mode": "light",
        "numa": true
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "hw-aes": null,
        "priority": null,
        "memory-pool": false,
        "yield": true,
        "max-threads-hint": 100,
        "asm": true,
        "argon2-impl": null,
        "cn/0": false,
        "cn-lite/0": false
    },
`
huge-pages true but not available
cpu

**Comment by xmrig** [comment]
You are right, priority should be applied to dataset initialization threads too, I missed that part.
Thank you.

**Comment by xmrig** [comment]
About priority, right place for it #1386 (looks like I need some rest).

`"init": -1,` controls how many threads used to initialize dataset, `-1` means all threads (100% CPU) it can be changed to a number of threads.

@vivin321 RandomX required 2+ GB of memory, so you must close another heavy applications like browsers or install more memory.

**Comment by xmrig** [comment]
Reddit discussion https://www.reddit.com/r/MoneroMining/comments/e6f8y7/system_hangs_for_10_sec_and_miner_consume_all/
