### ISSUE TITLE
xmrig 5.1.1 config “priority” No effect

### ISSUE THREAD

**Issue by jindyzhao** [xmrig/xmrig#1386]
update xmrig 5.1.1
MSVC/2017 Compile version
windows（7+10） “priority” set 0 and 1 is No effect，maybe bug？

**Comment by manianac** [comment]
I confirmed this issue as well.  RandomX threads are priority 7 despite whatever is in the config.

I hardcoded a priority level in Worker.cpp to verify that overrides it, was going to look through the call stack to see what is garbling it.

**Comment by xmrig** [comment]
v5.1.1 sets priority to main miner thread to one level higher that worker threads, example with `"priority": 0,`
![nFraGEI](https://user-images.githubusercontent.com/27528955/70298794-65437e00-1825-11ea-8215-2f70e7668693.png)

**Comment by jindyzhao** [comment]
> v5.1.1 sets priority to main miner thread to one level higher that worker threads, example with `"priority": 0,`
> ![nFraGEI](https://user-images.githubusercontent.com/27528955/70298794-65437e00-1825-11ea-8215-2f70e7668693.png)

thank！
So only the priority of the main miner thread remain the same, does the worker thread take effect?

**Comment by xmrig** [comment]
For worker threads nothing changed all works exactly same as before.
For main thread used +1 priority, for example if config set `0` main thread use `1`, 1 -> 2, etc.
