### ISSUE TITLE
build for xmrig on raspberry pi 4

### ISSUE THREAD

**Issue by amitceder** [xmrig/xmrig#1387]
Hi,
I'm trying to build the ubuntu build sequence on raspberry with raspbian.
trying to run it shows it recognized arm v7 and not v8 for some reason, though raspberry uses ARM A72 which is V8.
I also needed to run the cmake with some changes:
down graded the gcc-5 and g++-5 compilers to complete the make.
also running the cmake with flag:
-DOPENCV_EXTRA_EXE_LINKER_FLAGS=-latomic

if I don't do that - the make compile fails due to neon issues.
If I do use the V7, it uses interpreter mode - which of course sucks... (don't even get a single hash).
any suggestions?

**Comment by SChernykh** [comment]
You have to install 64-bit OS to be able to compile for ARMv8.

**Comment by amitceder** [comment]
I’m pretty sure Raspbian is 64 bit – why would that team create an OS for a 64 bit processor with 32 bit?

 �

**Comment by amitceder** [comment]
Oops – I think I understand what you mean – 

 �

From  this I learned that : https://raspberrypi.stackexchange.com/questions/100926/64-bit-os-on-raspberry-pi-4

Seems the user space is 32 bit although the kernel is 64 bit.

 �

**Comment by grahamreeds** [comment]
A 64bit Kernal + 64bit userland was released today. I can confirm that the 3b+ builds and runs xmrig with no editing of the cmake files needed.

**Comment by amitceder** [comment]
I was able to do that with gentoo 64b server for pi4 a week ago.
it required to install on it ubuntu server with virtual machine, and that
actually worked as 64b.

**Comment by grahamreeds** [comment]
Yes, and I was able to do it using nspawn last week or installing d64.

Point is: no VM's needed or convoluted jumping through hoops.
