### ISSUE TITLE
DIfferent

### ISSUE THREAD

**Issue by anitagemilangs** [xmrig/xmrig#14]
Hello,

what is different xmrig-1.0.0-gcc-win64.zip and xmrig-1.0.0-msvc-win64.zip ?

Thanks

**Comment by xmrig** [comment]
Different compiler:

* gcc = gcc 6.3.0 from MSYS2
* msvc = Microsoft Visual C++ 2017

Performance of both very close. In my tests msvc little bit faster less than 1%.

**Comment by anitagemilangs** [comment]
Thanks

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
@xmrig is still performance of msvc and gcc versions very close (less than 1%) or...?
