### ISSUE TITLE
Help need with xmrig and minemonero.pro

### ISSUE THREAD

**Issue by petervalencic** [xmrig/xmrig#140]
Hi,
have setup monero wallet and modified xmrig config.json file..

have setup like this:
 "url": "pool.minemonero.pro:5555",
            "user": "43kwC3YXzj42qdT1uoGbS97TUqbNE43r5jnPFnJ4cwGjZa4U9G5mCL2VEbJywoSw62RFqbt9hiAwLQsGzAFAvQkcSykCn6N",
            "pass": "xxxx",

When I like to sign into minemonero.pro with user and pass I get error: please check your login..

Can someone tell me what I'am doing wrong?

**Comment by MineMoneroPRO** [comment]
Hi!
You should set your password in xmrig like "worker_id:password".
In this case the password from web interface would be just "password".
Please note that you can set the password as an email (eg. "worker_id:email@email.com") and you will be receiving email notifications in this case.
