### ISSUE TITLE
Error mining cn/gpu on GTX 1080ti

### ISSUE THREAD

**Issue by UselessGuru** [xmrig/xmrig#1402]
Version 5.11

Hardware Nvidia GTX 1080Ti, driver version 441.12

Command line:

`XmrigCryptonight-v5.1.1\xmrig.exe --algo=cn/gpu --http-host=127.0.0.1 --http-port=4002 --api-worker-id=Blackbox --url=stratum+tcp://cryptonight_gpu.mine.zergpool.com:4445 --user=******************** --pass=ID=*********,c=BTC --donate-level 1 --cuda-bfactor-hint=8 --no-cpu --no-nvml --cuda --cuda-loader=xmrig-cuda.dll --cuda-devices 0`

**Error thread #0 failed with error <cryptonight_core_gpu_hash_gpu>:846 "too many resources requested for launch"**

Same config with works well on a Nvidia 1060 6GB

**Comment by xmrig** [comment]
If you interesting to this algorithm use xmr-stak instead.
Thank you.

**Comment by UselessGuru** [comment]
@xmrig 

But why is GT 1060 6GB working then?

**Comment by zonalimitatore** [comment]
same with 750ti
