### ISSUE TITLE
xeon phi optimizations

### ISSUE THREAD

**Issue by xrataj00** [xmrig/xmrig#1405]
Hello, are there any possible optimizations of randomx for xeon phi x200? Are any if its features like AVX512 any help here? Thanks.

**Comment by tevador** [comment]
RandomX only uses 128-bit SIMD, so anything wider than SSE2 is not useful (including AVX and AVX512). The Xeon Phis also don't have sufficient on-chip cache and their core clock is very low. I'd be surprised if any substantial optimizations were possible.
