### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by John-xmrig** [xmrig/xmrig#1407]
1-cmake .. -G "Visual Studio 15 2017 Win64" -DXMRIG_DEPS=C:\Users\John\Desktop\xmrig-deps-3.1\msvc2019\x64
2-cmake --build . --config Release

"C: \ Users \ John \ Desktop \ xmrig-deps-3.1 \ xmrig-5.2.0 \ build \ ALL_BUILD.vcxproj" (default
Recognize goals
) (1)->
"C: \ Users \ John \ Desktop \ xmrig-deps-3.1 \ xmrig-5.2.0 \ build \ xmrig.vcxproj" (default
Standard) (1
0)->
(Link target)->
   LINK: fatal error C1007: Unrecognized flag "-pdbrpc" (in "p2") [C: \ Users \ John
\ Desktop \ xmr
ig-deps-3.1 \ xmrig-5.2.0 \ build \ xmrig.vcxproj]
   LINK: fatal error LNK1257: Code generation failed [C: \ Users \ John \ Desktop \ xmrig-deps-3.1
\ xmri
g-5.2.0 \ build \ xmrig.vcxproj]

     89 warnings
     2 errors

Elapsed time 00: 03: 47.32

**Comment by flippp0** [comment]
Did you try the latest release of xmrig-deps?
It was updated for VS 2019 a few days ago.
