### ISSUE TITLE
XMRig does not work with RX 460, RX 560 

### ISSUE THREAD

**Issue by senski7** [xmrig/xmrig#1409]
Is this normal ?

[2019-12-12 19:12:12.779]  ocl  use profile  rx  (2 threads) scratchpad 2048 KB
|  # | GPU |  BUS ID |    I |  W | SI | MC |  U |  MEM | NAME
|  0 |   0 | 01:00.0 |  160 |  8 |  0 |  - |  8 |  320 | Radeon(TM) RX 460 Graphics (Baffin)
|  1 |   0 | 01:00.0 |  160 |  8 |  0 |  - |  8 |  320 | Radeon(TM) RX 460 Graphics (Baffin)
[2019-12-12 19:12:13.521]  ocl  error CL_MEM_OBJECT_ALLOCATION_FAILURE when calling clCreateBuffer with buffer size 2181038080
[2019-12-12 19:12:13.523]  ocl  error CL_MEM_OBJECT_ALLOCATION_FAILURE when calling clCreateBuffer with buffer size 2181038080
[2019-12-12 19:12:13.591]  ocl  thread #0 failed with error RandomX dataset is not available
[2019-12-12 19:12:13.652]  ocl  thread #1 failed with error RandomX dataset is not available
[2019-12-12 19:12:13.702]  ocl  thread #0 self-test failed
[2019-12-12 19:12:13.720]  ocl  thread #1 self-test failed
[2019-12-12 19:12:13.722]  ocl  disabled (failed to start threads)

**Comment by dedizones** [comment]
Hi,
Which version xmrig do you use?
RX 4GO or 8GB

**Comment by senski7** [comment]
I tried all versions after 5.0.0

**Comment by setuidroot** [comment]
> I tried all versions after 5.0.0

He meant how much RAM does your GPU have?

You need a GPU with at least 4GB of RAM to allocate the 2080 MB RandomX dataset, otherwise you'll need to turn on the dataset-host option so that the RandomX dataset will run on your motherboard's RAM instead (you'd need at least 4GB of system RAM for that to work.)

It's impossible to help you without more information... like a copy of your config.json file and information about your hardware.  Without that, I can only answer: No, that is not normal.  Albeit errors can be fairly common depending on your hardware and config.json file.

**Comment by D0nVitalio** [comment]
Hi. I have same problem. XMrig version 6.8.1, RX460 4Gb, Win10x64.
ocl error CL_MEM_OBJECT_ALLOCATION_FAILURE when calling clCreateBuffer with buffer size 2181038080

**Comment by SChernykh** [comment]
I have RX560 4GB on Windows 7 and it works there, but there's little point to mine RandomX with GPU. It's only 260 h/s.

**Comment by ScardracS** [comment]
Mining Monero on GPU is not a good idea as RandomX is specifically for CPU hashing.

OT

Considering that GPU I personally suggest to mine Firo or ETC

**Comment by Spudz76** [comment]
Probably need to set the envvars
```
export GPU_FORCE_64BIT_PTR=1
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
```

It's saying OpenCL only sees 320KB of memory which is what it would do without the above settings.

**Comment by rsalvo77** [comment]
Sounds like a config issue, possibly drivers or mining software ext not setup properly. Just my 2 cents :)
