### ISSUE TITLE
Pause mining when using computer

### ISSUE THREAD

**Issue by Valke88** [xmrig/xmrig#141]
Hi,

Is it possible to stop mining for x amount of minutes after mouse or keyboard input?

Regards, Valke

**Comment by xmrig** [comment]
Now it possible only manually, press p/r in miner window.
Thank you.

**Comment by xmrig** [comment]
Duplicate #141

**Comment by Twanislas** [comment]
Hi !

I would also love this, a little bit like how the NiceHash Legacy miner does. Wait for computer to be idle for at least <x> seconds then start/resume mining, and pause mining whenever the computer is not idle anymore or there is peripheral input (mouse, keyboard, whatever (so this includes remote input such as RDP, VNC, etc..)

Thanks for the great work out there, xmrig is a big perf increase for me ! ;)

**Comment by EUA** [comment]
I have 8/16 cores and I don't like pausing, instead want to pause threads when necessary!
I open issue #195 due this purpose.
Regards.

**Comment by dunklesToast** [comment]
Would be nice if there is also an (POST) API Endpoint to change the miners state - have some great ideas for little scripts with that :)

**Comment by untoreh** [comment]
is there any meaningful difference between issuing `STOP`/`CONT` signals and sending literal `h`/ `p` key events?

**Comment by MetallianFR68** [comment]
+1 for this feature.
I have 10 employees.
I ask them to run the miner manually at the end of their workday but they always forget.
With such a feature, I could run the miner in background and set it to launch after 5mn idle time.

**Comment by Zelecktor** [comment]
anyone working on this? some miner like Silent Miner got this feature.
https://xmrminer.net/
If someone risk in buy and apply reverse engineering to got the source code of that miner, would be great

**Comment by Zelecktor** [comment]
I found that this feature is used by lots of miners
https://www.reddit.com/r/EtherMining/comments/6eip9a/automatic_mining_in_windows_while_idle_task/

Just add Task Scheduler at the source code and make a custom configure
@xmrig can you have a look to this? thanks in advance

**Comment by Zambi9** [comment]
Even better will be - use x threads for idle time, y threads for non-idle time.

**Comment by leonelsr** [comment]
> Even better will be - use x threads for idle time, y threads for non-idle time.

At least on Windows, I've just implemented a AutoHotkey script that does this by changing **config.json** file on the fly. Pretty easy to improve, tweak and extend. It currently uses PowerShell Core 7.0 `pwsh.exe` to modify the JSON file more easily, but should work with `powershell.exe` as well.

The gist has a suitable `config.json` sample for reference

https://gist.github.com/leonelsr/25e06a88cd8fc4efc6f0a9a9568ef27e

**Comment by jaga3421** [comment]
I am trying to implement pause/resume from a node environment. Right now, my option is to identify the keyboard/mouse inputs from a node module like iohook and then kill the process/start the process. Would like the expert mind's input on this approach.

**Comment by exclm** [comment]
Sample solutions [here](https://stackoverflow.com/a/68681090/4246799)

**Comment by G2G2G2G** [comment]
This was already marked as won't fix, so they're not going to fix/add it. It's been years of milestone pushback etc. To add this functionality is very basic and exclm linked one example.

**Comment by SChernykh** [comment]
https://xmrig.com/docs/miner/config/misc#pause-on-active
