### ISSUE TITLE
failed to load OpenCL runtime

### ISSUE THREAD

**Issue by agentpatience** [xmrig/xmrig#1415]
I installed XMRIG on Ubuntu 19 and trying to use a old RX580 card to mine. I get this error:

OPENCL       disabled (failed to load OpenCL runtime)

I could not find any instructions about using amd gpu with xmrig. Any help would be appreciated.,

**Comment by Keitarono** [comment]
I had this issue a while ago, for me I was able to fix the issue by re-installing Radeon software and graphics drivers

**Comment by molnarjoe** [comment]
I am having the same problem. When I went to AMD, their software does not support later than Ubuntu 16.04. What is the source of your Radeon software and drivers, please?
Thank you in advance,
