### ISSUE TITLE
Returning MSR to Default value

### ISSUE THREAD

**Issue by cmlau** [xmrig/xmrig#1419]
Will the MSR setting return to default value after xmrig is stopped in Windows OS?? If not, any way to do this without rebooting Windows?

For Linux, can I just use "modprobe -r msr" to return to default value  or do I need to set another value other than "6" (i.e. wrmsr -a 0x1a4 _X_) to return it to default ?

Thanks.

**Comment by xmrig** [comment]
It not implemented right now, for revert to default values need save it first and apply them back on exit.
Module is just interface to MSR registers, you need set another value to revert it back, read current value by `sudo rdmsr 0x1a4` usually it `0` or `3` and write it back `sudo wrmsr -a 0x1a4 0`.

Please note for Ryzen value of 4 registers changed https://github.com/xmrig/xmrig/blob/master/scripts/randomx_boost.sh

**Comment by xmrig** [comment]
Implemented in dev branch, the miner will restore initial values on exit by default, it controlled by new option `rdmsr`.
In case If something bad happen, eg the miner crashed, you still need to reboot to restore default values.
Thank you.

**Comment by j1warren** [comment]
would be nice to have this in script, too
save original values in file via rdmsr, and have an option to restore them

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v5.4.0
