### ISSUE TITLE
windows mingw64 compile error

### ISSUE THREAD

**Issue by usoppx** [xmrig/xmrig#142]
[ 68%] Building CXX object CMakeFiles/xmrig.dir/src/xmrig.cpp.obj
[ 70%] Building RC object CMakeFiles/xmrig.dir/res/app.rc.obj
The system cannot find the file specified.
C:\msys64\mingw64\bin\windres.exe: preprocessing failed.
make[2]: *** [CMakeFiles/xmrig.dir/build.make:738: CMakeFiles/xmrig.dir/res/app.rc.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/xmrig.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

file is physically there in C:\msys64\home\user\xmrig-master\res

not sure what to do. 

running commands:
user@comp MINGW64 ~/xmrig-master
$ cmake -G "Unix Makefiles" -DUV_INCLUDE_DIR="c:\<path>\gcc\libuv\x86\include" -DUV_LIBRARY="c:\<path>\gcc\libuv\x86\lib\libuv.a" -DMHD_INCLUDE_DIR="c:\<path>\gcc\libmicrohttpd\x86\include" -DMHD_LIBRARY="c:\<path>\gcc\libmicrohttpd\x86\lib\libmicrohttpd.a"

make

**Comment by xmrig** [comment]
`C:\msys64\mingw64\bin\windres.exe` file exists?
Also you can comment/remove this line https://github.com/xmrig/xmrig/blob/master/CMakeLists.txt#L109 just lose icon and version information in exe file.
Thank you.

**Comment by usoppx** [comment]
C:\msys64\mingw64\bin\windres.exe exists.

commenting the line allowed it to proceed further.

**Comment by evaexe** [comment]
Same issues, some ppl have a solution ?

make[2]: *** No rule to make target 'C://gcc/libuv/x64/lib/libuv.a', needed by 'xmrig.exe'. Stop.

**Comment by briancosie** [comment]
![screenshot 10](https://user-images.githubusercontent.com/39021200/39670766-b2605a2a-5114-11e8-93ef-3a532129fa65.png)

me too having the same error
