### ISSUE TITLE
MSR - WinRing0x64.sys Dependencies

### ISSUE THREAD

**Issue by yesilcimenahmet** [xmrig/xmrig#1420]
Hi,

I'm using a 64-bit version of XMRig compiled with GCC to avoid MSVCR dependencies. Is there any dependency of the WinRing0x64.sys file? or specific operating system version?

**Comment by xmrig** [comment]
This driver added to support write to MSR registers on Windows https://xmrig.com/docs/miner/randomx-optimization-guide/msr however miner can work without this file.
Thank you.

**Comment by SChernykh** [comment]
We tested WinRing0x64.sys in Windows 7 (64-bit) and Windows 10 (64-bit). There are no additional dependencies.

**Comment by yesilcimenahmet** [comment]
Thanks a lot.

I mean, if the WinRing0x64.sys file cannot be loaded due to dependencies or some other reason, will the application crash? The application should continue to run against each scenario.

**Comment by SChernykh** [comment]
It it fails to load, MSR mod will not be applied, but XMRig will continue to run.

**Comment by yesilcimenahmet** [comment]
Thanks.
