### ISSUE TITLE
safex-rig.exe

### ISSUE THREAD

**Issue by swa74** [xmrig/xmrig#1422]
Build a ready-made safex-rig.exe for Windows users so that people don’t suffer

**Comment by flippp0** [comment]
SFX (SafeX) support is now coded in the dev branch.
You can compile the dev branch on your own now or wait for the next release of the master branch for the binaries.

**Comment by xmrig** [comment]
Implemented in v5.4.0 https://github.com/xmrig/xmrig/releases/tag/v5.4.0
Thank you.
