### ISSUE TITLE
Cannot UPX compress anymore

### ISSUE THREAD

**Issue by plastkort** [xmrig/xmrig#1427]
I Like using UPX to compress my compiled xmrig. this worked very well until the 2.xx versions. but now I am having the following error:

upx: D:\Visual Studio\xmrig\build\Release\xmrig.exe: CantPackException: size of Load Configuration directory unexpected

is there anything I can do about this ?

this is the entire UPX log

C:\Users\stian>"D:\Visual Studio\xmrig\build\Release\upx.exe" "D:\Visual Studio\xmrig\build\Release\xmrig.exe"
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95w       Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: D:\Visual Studio\xmrig\build\Release\xmrig.exe: CantPackException: size of Load Configuration directory unexpected

Packed 1 file: 0 ok, 1 error.

**Comment by mukesh-610** [comment]
I was able to compress XMRig using UPX.

I compiled XMRig myself on a 64-bit Linux PC (gcc 8.3), and used UPX 3.95 with `--force` flag.

**Comment by xmrig** [comment]
It UPX bug https://github.com/upx/upx/issues/245 nothing I can do with it.
Thank you.
