### ISSUE TITLE
error 1061 and error 1072

### ISSUE THREAD

**Issue by wyzdic** [xmrig/xmrig#1428]
[2019-12-16 09:06:08.131]  msr  failed to stop WinRing0 driver, error 1061
[2019-12-16 09:06:08.131]  msr  failed to remove WinRing0 driver, error 1072

-----

Windows 2016 and Windows 2019,EPYC 7451 and EPYC 7601,admin privileges

**Comment by wyzdic** [comment]
Find the cause of the problem
I used the process tracking query to find that ZenStatesAll uses WinRing0x64.sys, but when I close the Zenstates program, xmrig still reports 1061 and 1072;
ZenStatesAll, which is a tool to overclock the epyc processor.

**Comment by xmrig** [comment]
Duplicate #1423 can you check dev branch?
Thank you.

**Comment by wyzdic** [comment]
It has worked for me. https://github.com/xmrig/xmrig/issues/1425#issuecomment-566664690
Use dev and "wrmsr": ["0xc0011020:0x0", "0xc0011021:0x60", "0xc0011022:0x510000","0xc001102b:0x1808cc16"]
It not only solves the 1061 1072 problem, but also resolves the xmrig crash of the EPYC ES CPU.
