### ISSUE TITLE
Failed to compile on ppc64le

### ISSUE THREAD

**Issue by nithinswarrier** [xmrig/xmrig#143]
I am using OpenPower PC's for mining. But I can't get xmrig to compile on it. It just says there is some error on sysinfos.c
impossible register constraint in 'asm'. Please help me compile. To reproduce the error compile on ppc64le.

**Comment by xmrig** [comment]
Only x86(64) architectures supported.
Thank you/

**Comment by nithinswarrier** [comment]
Is there anyway to port this on ppc64le. I searched for cpuid opcode on ppc64le platform but found nothing on it.

**Comment by atarate** [comment]
Intrinsics of the code are X86 and AES-NI Specific. You will have to rewrite the code as such mate.
