### ISSUE TITLE
XMRig 5.3.0 - enabling 1GB leads to significant hashrate reducing

### ISSUE THREAD

**Issue by Shekelme** [xmrig/xmrig#1430]
After I executed the `enable_1gb_pages.sh` I've got the following result:

![image](https://user-images.githubusercontent.com/26449500/70880136-772dd980-1ffa-11ea-9843-68a76820b126.png)

And the hashrate lowered from 9150 to 5613...

**Comment by xmrig** [comment]
You not set `"1gb-pages": true,` in `"randomx"` object in config file.
Thank you.

**Comment by Spudz76** [comment]
the 1GB script reduces your 2MB hugepages
and you didn't turn on 1GB mode so it is running on not-enough 2MB hugepages

**Comment by Shekelme** [comment]
Looks like I understand - there will be less hugepages but hugepages will be of bigger size.

**Comment by Spudz76** [comment]
No, some parts of the miner use the 2MB hugepages either way.  The script sets the count of 2MB hugepages to number of processors which is not enough for all algos

Only RandomX and its variants can use 1GB hugepages.  And even then it uses a few 2MB ones, I think.

So for best multi-algo results you would need both the full allocation of 1280 hugepages and the 3 1GB hugepages.  Either edit the enable script to change the hugepages from nproc to 1280, or do `sysctl vm.nr_hugepages=1280` after running the enable script.

Also check `ulimit -l` which should be at least `5905580032` which is `(1280*2 + 3072)*1048576`
