### ISSUE TITLE
0 Hashrate

### ISSUE THREAD

**Issue by septuig** [xmrig/xmrig#1432]
Hi
When I started xmrig 5.3 with default config file, the Hashrate is 0, My CPUs are Intel  2*E5-2680v2@Win10 64x. 4g memory. What's the optimized configuration for XMR? Thank you. 
![image](https://user-images.githubusercontent.com/38321812/70910348-83da1e00-204a-11ea-9365-588a6b72099e.png)

**Comment by pawelantczak** [comment]
Too less RAM I believe.

**Comment by dedizones** [comment]
Virtualisation ?

**Comment by SChernykh** [comment]
You have 4 GB of memory and 2 NUMA nodes, so you need 4 GB for datasets and some more memory (1+ GB) for the OS. You'll have to disable NUMA in config.json to be able to get more than 0 h/s.

**Comment by Spudz76** [comment]
Or upgrade to 8GB

**Comment by septuig** [comment]
Thank you all, upgraded to 16G, got 8.1K h/s.  any parameter can be changed to obtain more hare?

**Comment by SChernykh** [comment]
Run XMRig with administrator privileges to get more hashrate.

**Comment by septuig** [comment]
To got more hashrate, whether need to set affinity or threads? if so, how to config, thank you.

![image](https://user-images.githubusercontent.com/38321812/71176167-2fca7600-22a4-11ea-9346-d682575cae52.png)
