### ISSUE TITLE
Intel MSR optimizations - 6 is maybe not the best?

### ISSUE THREAD

**Issue by jfikar** [xmrig/xmrig#1433]
Hi,

I've tried all the possible values X=0-15 in `wrmsr -a 0x1a4 X` . Then I let the xmrig working for at least 15 minutes, pressed H and recorded the max cumulative hash rate (the very last number when you press H).

I have found that **6** is not the best value. It is **13** and sometimes **12**. I've tried 5 different Intel CPUs from these families: SandyBridge, IvyBridge, and Haswell.

Did anyone else try all the values? The guy in the original reddit thread shows a picture, where **14** is actually the fastest, but he uses for some reason **6**, the second fastest. He also looked at the speed of the single fastest thread, not at the cumulative hash rate.  I also observed a smaller gain of the total hash rate of only 0.5-5%, not 30%.

**Comment by xmrig** [comment]
`6` is maybe not the best and it main reason why option `wrmsr` is not just accept `true` or `false`, it also accept the number too.

For old CPUs like yours hashrate improvements is lower and it expected.
Thank you.

**Comment by jdmpro** [comment]
Can you add random rx/v algorithm

**Comment by ValoWaking** [comment]
for my the best is 15 (z97 4690k, windows 10)

**Comment by kio3i0j9024vkoenio** [comment]
`I've tried all the possible values X=0-15 in wrmsr -a 0x1a4 X . Then I let the xmrig working for at least 15 minutes, pressed H and recorded the max cumulative hash rate (the very last number when you press H).

I have found that 6 is not the best value. It is 13 and sometimes 12. I've tried 5 different Intel CPUs from these families: SandyBridge, IvyBridge, and Haswell.`

Could you post the results of your tests or a link to the results.

I have various Intel machines and would like to use the most optimal value for wrmsr.

Thanks

**Comment by jfikar** [comment]
The best is to try it by yourself, as the result may depend on your CPU and other things. Just try all the settings, let xmrig run for 15 mins, press "h" and record the max. Here are results for Haswell-E i7-5930K:

```
0    3198.8
1    3208.1
2    3206.7
3    3205.8
4    3271.7
5    3257.3
6    3254.1
7    3251.2
8    3210.7
9    3181.1
10   3195.5
11   3206.3
12   3260.7
13   3256.9
14   3254.2
15   3238.8
```

**Comment by kio3i0j9024vkoenio** [comment]
Quote: The best is to try it by yourself, as the result may depend on your CPU and other things. Just try all the settings, let xmrig run for 15 mins, press "h" and record the max.

Well I was hoping to not have to replicate results if it was already done on for the different Intel families: SandyBridge, IvyBridge, and Haswell.

Quote: Here are results for Haswell-E i7-5930K:

Using "6" as the base setting for the msr registers I have added the percent differences for the other settings:

0    3198.8 -1.7%
1    3208.1 -1.4%
2    3206.7 -1.46%
3    3205.8 -1.48%
4    3271.7 +0.54%
5    3257.3 +0.1%
6    3254.1 0.0% - base
7    3251.2 -0.1%
8    3210.7 -1.3%
9    3181.1 -2.2%
10   3195.5 -1.8%
11   3206.3 -1.5%
12   3260.7 +0.2%
13   3256.9 +0.09%
14   3254.2 0.0%
15   3238.8 -0.47%

This article discloses the MSR setting that can be used to control the various hardware prefetchers that are available on Intel processors based on the following microarchitectures: Nehalem, Westmere, Sandy Bridge, Ivy Bridge, Haswell, and Broadwell.

https://software.intel.com/en-us/articles/disclosure-of-hw-prefetcher-control-on-some-intel-processors

So the base setting 0f 6 equates to 0110b which disables the "L2 adjacent cache line prefetcher" and the "DCU prefetcher".

Focusing on the only positive gain of any significance the "4" 0100b +0.54% it looks like re-enabling the "DCU prefetcher" is the reason for the gain at least for the Haswell.

In the 4 0100b vs the 5 0101b the disabling of the "L2 hardware prefetcher" caused the loss.

In the 6 0110b vs the 12 1110b the disabling of the "DCU IP prefetcher" caused the loss.

At least for Haswell it is best not to disable the "L2 hardware prefetcher" or the "DCU IP prefetcher" and that only re-enabling the "DCU prefetcher" gives slightly better results.

Using the base "6" 0110b for Intel may be good overall for Intel but I will be testing The "4", "6" and "12" on other Intel processors and post the results here.

**Comment by jfikar** [comment]
It seems I missed **4** was the fastest for this one. Also, it seems the max hash rate can easily vary by as much as +/- 3h/s, so it difficult to obtain stable results.

I suspect it depends not only on the CPU family, but also on the L2 cache size (more cache, more threads, which somehow compete for the resources) and also on RAM speed, etc. The IvyBridge and SandyBridge Xeons (large L2, ECC memory) have max hash rate for **13**, you may also want to include that.

**Comment by jfikar** [comment]
I've done more testing and it seems it is better to look at the 15 min average. It is more reliable than the max hash rate. You can also change the MSR setting while xmrig runs, just wait 15 minutes and record the new average. And before I had not optimal thread count for the i7-5930K, now the hashrate is better.

Results for more CPUs:

|  | i5-2520M | E3-1230 | E3-1265L v2 | E5-1607 | i7-5930K| 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| 0 | 705.3  | 1817.4 | 1926.3 | 1651.8 | 3404.8 |
| 1 | 705.3  | 1828.4 | 1932.2 | 1655.5 | 3415.1 |
| 2 | 680.1  | 1816.4 | 1926.3 | 1650.2 | 3404.2 |
| 3 | 678.3 | 1829.4 | 1932.4 | 1652.9 | 3413.1 |
| 4 | 705.1 | 1888.3 | 1955.5 | 1650.8 | 3485.9 |
| 5 | 692.9  | 1898.9 | 1963.1 | 1653.5 | **3496.5** |
| 6 | 710.8  | 1887.8 | 1955.6 | 1649.0 | 3483.9 |
| 7 | 708.8  | 1897.8 | 1962.9 | 1652.5 | 3495.4 |
| 8 | 704.3  | 1820.2 | 1926.6 | 1651.0 | 3405.0 |
| 9 | 705.4  | 1829.8 | 1932.5 | **1654.5** | 3415.6 |
| 10 | 705.3 | 1818.4 | 1926.6 | 1650.5 | 3403.9 |
| 11 | 704.8 | 1831.0 | 1932.7 | 1653.3 | 3412.0 |
| 12 | **716.5**  | 1889.1 | 1956.5 | 1653.0 | 3487.4 |
| 13 | 713.9  | 1899.0 | **1964.2** | 1651.8 | 3495.4 | 
| 14 | 716.4  | 1894.6 | 1956.3 | 1651.5 | 3484.1 |
| 15 | 713.4  | **1900.4** | 1963.9 |1653.2 | 3494.9 |

**Comment by SChernykh** [comment]
It seems that 15 is the best setting overall for Intel CPUs - it disables all 4 prefetchers.

**Comment by jfikar** [comment]
Yes, indeed **15** is fastest overall for the 5 CPUs measured, followed by **13**, **14**, **12**, and **7**.
