### ISSUE TITLE
How can I disable donations

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [xmrig/xmrig#1436]
Is there a way for me to disable donations?
I tried making --donate-level 0 but it doesn't work

**Comment by pawelantczak** [comment]
Easiest way would be to read readme.  https://github.com/xmrig/xmrig#donations

**Comment by FAB1150** [comment]
you would need to edit the source code and compile it by yourself, but i think it's fair to give something to the developer, as it's publishing all the work for free.
If you want you can set it to 1 with donate-level.

**Comment by GjBrutello** [comment]
lol 1% donate it's 1min of 100 min, there's nothing to lose

**Comment by wwinter86** [comment]
Does the donating levels  affect anything such as the speed of the mining etc?

**Comment by danger89** [comment]
Do it doesn't.

Also you could also use my fork, if you don't want to build the code from scratch: https://github.com/danger89/xmrig/releases
