### ISSUE TITLE
Support nicehash

### ISSUE THREAD

**Issue by minerteam** [xmrig/xmrig#144]
Good morning, 
What is the function of --nicehash?
Thank you

**Comment by xmrig** [comment]
This option explicitly enables [nicehash.com](https://www.nicehash.com) and [xmrig-proxy](https://github.com/xmrig/xmrig-proxy) support. Nicehash has small difference in protocol, just one byte, but it required special handle of it.
Thank you.

https://github.com/nicehash/Specifications/blob/master/NiceHash_CryptoNight_modification_v1.0.txt

**Comment by minerteam** [comment]
This is hard to understand for me. I use xmrig.exe with config.json by default on several computers located in different locations. 
Would it be nice to use the --nicehash function for me? 
Thank you

**Comment by xmrig** [comment]
If you use the miner with nicehash.com or xmrig-proxy you must add this option. In all other cases it not need.

**Comment by minerteam** [comment]
Thank you very much.
