### ISSUE TITLE
Can I use cpu & gpu at the same time?

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [xmrig/xmrig#1442]
So I was wondering if it's possible to use GPU and CPU mining at the same time and if it's possible how can I do it

**Comment by Spudz76** [comment]
Enable both backends (see [here](https://github.com/xmrig/xmrig/blob/master/src/config.json) for a basic default config file).  The `"cpu"` and either `"opencl"` or `"cuda"` backend should have `"enabled": true` - note for CUDA you also need `xmrig-cuda` built to `libxmrig-cuda.so` or `libxmrig-cuda.dll` and placed in your run location.

They will be locked to the same algo (which probably sucks, GPU can't do RandomX very well).  But works if you are mining some algo that is useful on both.

I run it in two instances, one set for cpu only, and the other with cpu off and whichever gpu on.  That way they can join the pool under different algos (using MoneroOcean).

**Comment by jacksonkr** [comment]
Doing this on windows is easy. Update your config to have both cpu:true and opencl:true (for amd) or cuda:true (for nvidia).

If you have an nvidia card you may need to install the cuda driver separately
https://developer.nvidia.com/cuda-downloads

NOTE! this does not work with 5.3.0 - I personally use 5.1.0
