### ISSUE TITLE
Error when compiling for Raspberry Pi 4

### ISSUE THREAD

**Issue by ibrahimk157** [xmrig/xmrig#1446]
Hello,

Raspbian recently added 64bit support (aarch64), so I figured it would now yield a better hash rate.

However, when trying to compile xmrig,
I end up with the following error:

[ 76%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/cn/CnHash.cpp.o
In file included from /home/pi/xmrig/src/crypto/cn/CnHash.cpp:35:
/home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h: In function ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’:
/home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:86:31: warning: requested alignment 16 is larger than 8 [-Wattributes]
     alignas(16) const __m128i zero = { 0 };
                               ^~~~
/home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h: In function ‘__m128i aes_round_tweak_div(const __m128i&, const __m128i&)’:
/home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:400:29: warning: requested alignment 16 is larger than 8 [-Wattributes]
     alignas(16) uint32_t k[4];
                             ^
/home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:401:29: warning: requested alignment 16 is larger than 8 [-Wattributes]
     alignas(16) uint32_t x[4];
                             ^
In file included from /home/pi/xmrig/src/crypto/cn/SSE2NEON.h:123,
                 from /home/pi/xmrig/src/crypto/cn/soft_aes.h:31,
                 from /home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:34,
                 from /home/pi/xmrig/src/crypto/cn/CnHash.cpp:35:
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h: In function ‘__m128i _mm_set_epi32(int, int, int, int)’:
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h:10369:1: error: inlining failed in call to always_inline ‘int32x4_t vld1q_s32(const int32_t*)’: target specific option mismatch
 vld1q_s32 (const int32_t * __a)
 ^~~~~~~~~
In file included from /home/pi/xmrig/src/crypto/cn/soft_aes.h:31,
                 from /home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:34,
                 from /home/pi/xmrig/src/crypto/cn/CnHash.cpp:35:
/home/pi/xmrig/src/crypto/cn/SSE2NEON.h:357:42: note: called from here
/home/pi/xmrig/src/crypto/cn/SSE2NEON.h:230:2:
  (x)
  ~~~                                      
/home/pi/xmrig/src/crypto/cn/SSE2NEON.h:357:42:
  return vreinterpretq_m128i_s32(vld1q_s32(data));
/home/pi/xmrig/src/crypto/cn/SSE2NEON.h:230:3: note: in definition of macro  vreinterpretq_m128i_s32’
  (x)
   ^
make[2]: *** [CMakeFiles/xmrig.dir/build.make:1740: CMakeFiles/xmrig.dir/src/crypto/cn/CnHash.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/xmrig.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
pi@raspberrypi:~/xmrig/build $ 
/home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:In function ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’:
/home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:86:31:warning: requested alignment 16 is larger than 8 [-Wattributes]
alignas(16) const __m128i zero= { 0 };
^~~~
/home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:In function ‘__m128i aes_round_tweak_div(const __m128i&, const __m128i&)’:
/home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:400:29:warning: requested alignment 16 is larger than 8 [-Wattributes]
alignas(16) uint32_t k[4];
^
/home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:401:29:warning: requested alignment 16 is larger than 8 [-Wattributes]
alignas(16) uint32_t x[4];
^
In file included from /home/pi/xmrig/src/crypto/cn/SSE2NEON.h:123,
from /home/pi/xmrig/src/crypto/cn/soft_aes.h:31,
from /home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:34,
from /home/pi/xmrig/src/crypto/cn/CnHash.cpp:35:
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h:In function ‘__m128i _mm_set_epi32(int, int, int, int)’:
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h:10369:1:error: inlining failed in call to always_inline ‘int32x4_t vld1q_s32(const int32_t*)’: target specific option mismatch
 vld1q_s32(const int32_t * __a)
^~~~~~~~~
In file included from /home/pi/xmrig/src/crypto/cn/soft_aes.h:31,
from /home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:34,
from /home/pi/xmrig/src/crypto/cn/CnHash.cpp:35:
/home/pi/xmrig/src/crypto/cn/SSE2NEON.h:357:42:note: called from here
/home/pi/xmrig/src/crypto/cn/SSE2NEON.h:230:2:
(x)
~~~
/home/pi/xmrig/src/crypto/cn/SSE2NEON.h:357:42:
return vreinterpretq_m128i_s32(vld1q_s32(data));
/home/pi/xmrig/src/crypto/cn/SSE2NEON.h:230:3:note: in definition of macro  vreinterpretq_m128i_s32’
(x)
^
make[2]: *** [CMakeFiles/xmrig.dir/build.make:1740: CMakeFiles/xmrig.dir/src/crypto/cn/CnHash.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/xmrig.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
pi@raspberrypi:~/xmrig/build $ 

Not sure what’s wrong nor what to do.

This is on a Raspberry Pi 4B (4GB RAM model) running Raspbian Buster with the experimental 64bit mode.

**Comment by jfikar** [comment]
Additionally to the 64-bit kernel you also need 64-bit user-space. The Raspbian is still 32-bit. Easiest is to do [schroot with Debian aarch64](https://www.raspberrypi.org/forums/viewtopic.php?t=208314&start=299).

**Comment by ibrahimk157** [comment]
> Additionally to the 64-bit kernel you also need 64-bit user-space. The Raspbian is still 32-bit. Easiest is to do [schroot with Debian aarch64](https://www.raspberrypi.org/forums/viewtopic.php?t=208314&start=299).

I don’t think that it’s necessary. The post from the raspbian devs which is wayyy newer than the one you linked specifically stated that 64bit programs will work. 

https://www.raspberrypi.org/forums/viewtopic.php?t=250730

In addition, i don’t think this has anything to do with the error I’m getting when trying to compile xmrig. Correct me if I’m wrong.

**Comment by jfikar** [comment]
You are wrong, I'm right. You definitely need aarch64 compiler and libraries to compile xmrig now. I know, because I've successfully done it.

And it does not matter, which message is newer and which is older. You need two things, 64-bit kernel (your link) AND 64-bit compiler and libraries (my link). Otherwise it will not compile and if you compile it somewhere else, it will even not run.

**Comment by ibrahimk157** [comment]
> You are wrong, I'm right. You definitely need aarch64 compiler and libraries to compile xmrig now. I know, because I've successfully done it.
> 
> And it does not matter, which message is newer and which is older. You need two things, 64-bit kernel (your link) AND 64-bit compiler and libraries (my link). Otherwise it will not compile and if you compile it somewhere else, it will even not run.

Aha, apologies. I’m quite confused as to what to do. Can you please guide me step by step? I don’t quite under the post you’ve linked me to.

**Comment by jfikar** [comment]
You just use these instructions and you'll get 64-bit schroot. You can enter the schroot anytime by the last command. There you compile and run the xmrig. Probably you would need to install additional libraries, I don't remember all of them. Anyway, it is not very fast, as RPi is missing AES instructions. Max 110 H/s.

```
sudo apt install -y debootstrap schroot
cat << EOF | sudo tee /etc/schroot/chroot.d/pi64
[pi64]
description=VC4 arm64 testing
type=directory
directory=/srv/chroot/pi64
users=pi
root-groups=root
profile=desktop
personality=linux
preserve-environment=true
EOF
sudo debootstrap --arch arm64 /srv/chroot/pi64
sudo schroot -c pi64 -- apt install -y sudo gcc libssl-dev libuv1-dev libnuma-dev libhwloc-dev cmake

schroot -c pi64
```

**Comment by ibrahimk157** [comment]
> You just use these instructions and you'll get 64-bit schroot. You can enter the schroot anytime by the last command. There you compile and run the xmrig. Probably you would need to install additional libraries, I don't remember all of them. Anyway, it is not very fast, as RPi is missing AES instructions. Max 110 H/s.
> 
> ```
> sudo apt install -y debootstrap schroot
> cat << EOF | sudo tee /etc/schroot/chroot.d/pi64
> [pi64]
> description=VC4 arm64 testing
> type=directory
> directory=/srv/chroot/pi64
> users=pi
> root-groups=root
> profile=desktop
> personality=linux
> preserve-environment=true
> EOF
> sudo debootstrap --arch arm64 /srv/chroot/pi64
> sudo schroot -c pi64 -- apt install -y sudo gcc libssl-dev libuv1-dev libnuma-dev libhwloc-dev cmake
> 
> schroot -c pi64
> ```

This is what i get with the last 3 commands:

pi@raspberrypi:~/turtle-wallet-proton $ sudo debootstrap --arch arm64 /srv/chroot/pi64
I: usage: [OPTION]... <suite> <target> [<mirror> [<script>]]
I: Try `debootstrap --help' for more information.
E: You must specify a suite and a target.
pi@raspberrypi:~/turtle-wallet-proton $ sudo schroot -c pi64 -- apt install -y sudo gcc libssl-dev libuv1-dev libnuma-dev libhwloc-dev cmake
E: 10mount: error: Directory '/srv/chroot/pi64' does not exist
E: 10mount: warning: Mount location /var/run/schroot/mount/pi64-96f2c35a-20fa-43c9-aa16-c24ef6bcdf66 no longer exists; skipping unmount
E: pi64-96f2c35a-20fa-43c9-aa16-c24ef6bcdf66: Chroot setup failed: stage=setup-start
pi@raspberrypi:~/turtle-wallet-proton $ 
pi@raspberrypi:~/turtle-wallet-proton $ schroot -c pi64
E: 10mount: error: Directory '/srv/chroot/pi64' does not exist
E: 10mount: warning: Mount location /var/run/schroot/mount/pi64-df7228ac-2518-4684-a14c-e86bf305ca82 no longer exists; skipping unmount
E: pi64-df7228ac-2518-4684-a14c-e86bf305ca82: Chroot setup failed: stage=setup-start
pi@raspberrypi:~/turtle-wallet-proton $

**Comment by jfikar** [comment]
What is in the /etc/schroot/chroot.d/pi64 file? Does /srv/chroot/pi64 exist?

`sudo mkdir -p /srv/chroot/pi64`

**Comment by ibrahimk157** [comment]
The contents of /etc/schroot/chroot.d/pi64 are:


[pi64]
description=VC4 arm64 testing
type=directory
directory=/srv/chroot/pi64
users=pi
root-groups=root
profile=desktop
personality=linux
preserve-environment=true

And no,  /srv/chroot doesn’t exist. Let alone /srv/chroot/pi64

I’ve gone ahead and created it

**Comment by ibrahimk157** [comment]
After creating it, i still get the same exact error running the last three commands you mentioned earlier

**Comment by jfikar** [comment]
I see, the syntax of debootstrap changed, you need now

`sudo debootstrap --arch arm64 stable /srv/chroot/pi64`

**Comment by ibrahimk157** [comment]
> I see, the syntax of debootstrap changed, you need now
> 
> `sudo debootstrap --arch arm64 stable /srv/chroot/pi64`
> 
> And I think `/srv/chroot/ `should exist and `/srv/chroot/pi64` should not exist. If I'm not mistaken.
> I apologize for misleading you.

That worked like a charm! I was able to successfully compile xmrig.

However, i came across another issue. In order for me to run xmrig on 64bit mode, i need to run it in schroot. I want xmrig to automatically start in 64bit mode on boot up. I couldn’t figure out how to make it start in schroot using systemctl. Can you please help with that?

**Comment by jfikar** [comment]
You can fo example use `/etc/rc.local` and put there:

```
cd /home/pi/xmrig
schroot -c pi64 -- ./xmrig
```

in config.json change `"background": true,`

**Comment by ibrahimk157** [comment]
> You can fo example use `/etc/rc.local` and put there:
> 
> ```
> cd /home/pi/xmrig
> schroot -c pi64 -- ./xmrig
> ```
> 
> in config.json change `"background": true,`

Works beautifully! Can’t thank you enough!

**Comment by ijason** [comment]
When I run `sudo debootstrap --arch arm64 stable /srv/chroot/pi64`
I get: Unable to execute target architecture

Any suggestions?

**Comment by jondwillis** [comment]
@ijason I see you found the answer, [linking your blog](https://blog.ijasoneverett.com/2020/08/cpu-mining-on-a-raspberry-pi/) for posterity & future search engine-ers

**Comment by amiltonjr** [comment]
> When I run `sudo debootstrap --arch arm64 stable /srv/chroot/pi64`
> I get: Unable to execute target architecture
> 
> Any suggestions?

First you need to run the command below:

`sudo apt-get install -y raspbian-nspawn-64`

You'll be prompted to enable 64-bit. Select **Yes**, hit **Enter** and reboot the system. Then you should be good to go and run:

`sudo debootstrap --arch arm64 stable /srv/chroot/pi64`
