### ISSUE TITLE
"Low Difficulty share" 

### ISSUE THREAD

**Issue by ChildishJack** [xmrig/xmrig#145]
I'm getting all shares rejected by minexmr for "Low Difficulty share". I'm running xmrig

`./xmrig -o pool.minexmr.com:3333 -u me4real.computer -p x -k -a cryptonight-lite --donate-level=1 -t 4 >> hello.txt
jack@xserve2:~/xmrig/build$ ./xmrig -o pool.minexmr.com:3333 -u me4real.computer -p x -k -a cryptonight-lite -t 4`

Ubuntu 16.04 Server, libuv/1.15.1-dev, gcc/5.4.0. The default difficulty on that port worked on the system in the past. Any ideas?

**Comment by xmrig** [comment]
Please remove `-a cryptonight-lite`. This option must be used only with AEON pools.
Thank you.
