### ISSUE TITLE
How to reduce the volume of compilation

### ISSUE THREAD

**Issue by axsoftshi** [xmrig/xmrig#1450]
How to reduce the compilation volume to about 800KB without UDX shell Microsoft Visual Studio 2017

**Comment by axsoftshi** [comment]
@xmrig

**Comment by xmrig** [comment]
1. Remove unused algorithms/features https://xmrig.com/docs/miner/cmake-options
2. Change flags https://github.com/xmrig/xmrig/blob/master/cmake/flags.cmake#L60 to prefer smaller size.

But I not sure is 800KB still possible.
Thank you.
