### ISSUE TITLE
XMRig does not submit any share on AMD Radeon HD 8500M

### ISSUE THREAD

**Issue by thephp1over** [xmrig/xmrig#1463]
**Describe the bug**
XMRig does not submit any share on AMD Radeon HD 8500M while CPU mining is OK.

I run the miner with following parameters:

> xmrig.exe --no-cpu --opencl -o pool.supportxmr.com:443 -u ... -p ... -k --tls

---

- Software Version - 2019.1204.2025.36760
- Driver Version - 19.50.02-191204a-349781C-RadeonSoftwareAdrenalin2020
- Provider - Advanced Micro Devices, Inc.
- 2D Driver Version - 8.1.1.1634
- Direct3D® Version - 9.14.10.01432
- OpenGL® Version - 26.20.11000.13586
- AMD Audio Driver Version - Not Available
- Vulkan™ Driver Version - 2.0.116
- Vulkan™ API Version - 1.1.125
- Windows Version - Windows 10 (64 bit)

---

- GPU - AMD Radeon HD 8500M - Discrete/Hybrid
- VRAM - 2048 MB - DDR3 900 MHz
- Graphics Card Manufacturer - Powered by AMD
- Graphics Chipset - AMD Radeon HD 8500M
- Device ID - 666F
- Vendor ID - 1002
- SubSystem ID - 380C
- SubSystem Vendor ID - 17AA
- Revision ID - 00
- Bus Type - PCI Express 2.0
- Current Bus Settings - PCI Express 2.0 x4
- BIOS Version - 015.043.000.016
- BIOS Part Number - 113-xxx-Xxx
- BIOS Date - 2014/09/21 22:20
- Usable Memory Size - 2048 MB
- Memory Type - DDR3
- Memory Clock - 900 MHz
- Core Clock - 850 MHz
- Total Memory Bandwidth - 14 GByte/s
- Memory Bit Rate - 1.80 Gbps
- 2D Driver File Path - /REGISTRY/MACHINE/SYSTEM/CurrentControlSet/Control/Class/{4d36e968-e325-11ce-bfc1-08002be10318}/0002
- OpenGL® API Version - Not Available
- OpenCL™ API Version - 1.2

---

![image](https://user-images.githubusercontent.com/59211472/71425831-cfc63c00-26b6-11ea-8dfc-ebac03d52cb0.png)

---

If any further information needed, just ask me.

Thank you so much.

Looking for your reply.

**Comment by SChernykh** [comment]
XMRig doesn't have GCN assembly for this GPU, so it will run RandomX in interpreter mode. It's very slow - probably less than 1 h/s on HD 8500M. It's unlikely you'll see any accepted shares with pool diff 50000.

**Comment by thephp1over** [comment]
I apologize for re-opening the issue.
I could get a single share after 5 minutes of mining on CPU but it didn't submit even one in the same period on GPU.
**Do you mean that currently my 1.7 GHz Pentium CPU has more performance than my GPU for mining?**
Before monero's migration to RandomX, My CPU's hashrate was about 15 H/s and GPU's was about 60 H/s!
RandomX seems weird!

**Comment by SChernykh** [comment]
RandomX was designed to be the fastest on CPU. Compared to Cryptonight, CPU gets much faster and GPU gets much slower.
