### ISSUE TITLE
Xmrig  Improvements

### ISSUE THREAD

**Issue by sakorc** [xmrig/xmrig#1468]
Xmrig shows GPU temperature and health but should be added to show CPU temperature as this is also important.
Thank You

**Comment by xmrig** [comment]
Recent discussion about this https://www.reddit.com/r/MoneroMining/comments/eggny2/add_cpu_temperature_to_xmrig/

**Comment by sakorc** [comment]
If xmrig 5.3 is available cpu temperature, how to enable it in config file?
Using windows 7 / 64 bit

**Comment by trasherdk** [comment]
Not `xmrig 5.3` but [Linux Kernel 5.4](https://itsfoss.com/linux-kernel-5-4/)

**Comment by SChernykh** [comment]
There is no unified interface to get CPU temperatures, this is why programs like CoreTemp/RealTemp exist for Windows and lm-sensors for Linux. It's much much bigger task than it seems, I'm not sure if it's worth it compared to just running CoreTemp/RealTemp alongside XMRig.

**Comment by x151973** [comment]
Try to use hwinfo64 instead, will effect some hashrate
