### ISSUE TITLE
Not compatible stratum

### ISSUE THREAD

**Issue by sammy007** [xmrig/xmrig#147]
> xmrig checks jobid in setId() method of the class JobID which must be at least 4 bytes long to pass the check.

https://github.com/sammy007/monero-stratum/issues/60#issuecomment-335088449

Such requirement is incorrect.

```c
diff -ur xmrig_orig/src/net/JobId.h xmrig/src/net/JobId.h
--- xmrig_orig/src/net/JobId.h	2017-10-09 03:22:24.733266554 -0400
+++ xmrig/src/net/JobId.h	2017-10-09 03:23:04.392712944 -0400
@@ -63,7 +63,7 @@
         }
 
         const size_t size = strlen(id);
-        if (size < 4 || size >= sizeof(m_data)) {
+        if (size >= sizeof(m_data)) {
             return false;
         }
 
```

**Comment by xmrig** [comment]
I fixed it. Please don't close this issue I will install your monero-stratum to verify all works fine in other places.
Thank you.

**Comment by sammy007** [comment]
Very nice, thank you.

**Comment by 2010phenix** [comment]
Xmrig, maybe we have this bug and in old, written on C (classic) miner?

**Comment by xmrig** [comment]
@2010phenix good catch. I check it now, classic miner unaffected.
Also this bug was in proxy too, after update, miners behind proxy will be unaffected.
I will make bugfix release in 1-2 days.
Thank you.

**Comment by xmrig** [comment]
v2.4.1 with the fix released.
