### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by woytu** [xmrig/xmrig#1470]
![image](https://user-images.githubusercontent.com/30252550/71565171-f933fd00-2ae6-11ea-88ed-28aafdf4a167.png)

![image](https://user-images.githubusercontent.com/30252550/71565189-1ff23380-2ae7-11ea-8960-363bfba77d1d.png)

**Comment by SChernykh** [comment]
@woytu XMRig is a miner, i.e. just a tool for mining - it's not malicious on its own, you can check the source code. We can't control how a tool is used. If your server is infected with malware, contact https://mrw.getmonero.org/

You can also contact nanopool and complain about botnet mining to that address: https://help.nanopool.org/conversation/new
I've already reported it to nanopool, but more independent reports will make it banned faster.

**Comment by woytu** [comment]
> @woytu XMRig is a miner, i.e. just a tool for mining - it's not malicious on its own, you can check the source code. We can't control how a tool is used. If your server is infected with malware, contact https://mrw.getmonero.org/
> 
> You can also contact nanopool and complain about botnet mining to 46sfbbM3XSjBo54d5a8PYUU5yQ31x6Rpv6tBhe22Cd7VYeJUyFUhzBF5rTf1oTB1d8MqgHxX5RbbEEKZd8fBAAmcFfv9Y5c - https://help.nanopool.org/conversation/new
> I've already reported it to nanopool, but more independent reports will make it banned faster.

thanks，I have contacted nanopool

**Comment by KevinZonda** [comment]
@woytu 这个好像最近在国内很流行，全部指向同一个钱包，找到两个可能疑似的脚本。
https://pastebin.com/rsdzW7C7
https://pastebin.com/CdqtXq2Z
朋友服务器也中招了，伪造成了**aliyun-service**等，也就是云盾相关进程。
