### ISSUE TITLE
Cannot open source file uv.h

### ISSUE THREAD

**Issue by Ala360** [xmrig/xmrig#148]
Hi,
when I try to debug I get these errors:

>     cannot open source file "uv.h"
> 
>     Cannot open include file: 'microhttpd.h': No such file or directory

I'm using Visual Studio 2017 15

How i can solve them? thank you!

**Comment by Ala360** [comment]
No one didn't bother himself to even reply!!

**Comment by AlexanderKozhevin** [comment]
I have the same problem :)

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/wiki/Windows-Build You can download prebuilt library's or build it byself.
