### ISSUE TITLE
Bus error RandomX

### ISSUE THREAD

**Issue by AndreyTheHacker** [xmrig/xmrig#1481]
![Screenshot_2020-01-04-16-21-55](https://user-images.githubusercontent.com/47180136/71780883-58c06a00-300b-11ea-9bb2-16bfc3436ee1.png)

Bus error...

**Comment by GjBrutello** [comment]
Ты хакер недоделанный, там же написано, недостаточно оперативной памяти. Надо как минимум 2.5GB. П.С Нашел на чем майнить,

**Comment by AndreyTheHacker** [comment]
> Ты хакер недоделанный, там же написано, недостаточно оперативной памяти. Надо как минимум 2.5GB. П.С Нашел на чем майнить,

Ты не видишь что он в медленный режим переходит , и он уже готов майнить (стресс тест) , глаза раскрой!

**Comment by GjBrutello** [comment]
> Ты не видишь что он в медленный режим переходит , и он уже готов майнить (стресс тест) , глаза раскрой!

Видимо, потому что даже в слоу моде не хватает памяти, да и еще система 32-битная. Bus error, что-то связано с  шиной памяти. Даже если бы и запустился на такой системе, то там максимум давало 10h/s. Майнер даже его L кэш не отображает, видимо потому что нет минимальных 2mb, чтобы реализовать поток, наверное.
