### ISSUE TITLE
How does http api work?

### ISSUE THREAD

**Issue by TheUnity** [xmrig/xmrig#149]
How does http api work? I wrote port, token and id in config. Show me example of GET, plz.

**Comment by xmrig** [comment]
1. Choice some port for api, for example `8080`.
2. Set `access-token` to `null` it important.
3. Run the miner, if try access to API from same machine, open in browser http://127.0.0.1:8080/

For how use access token please check sample page https://gist.github.com/xmrig/c75fdd1f8e0f3bac05500be2ab718f8e

**Comment by TheUnity** [comment]
Thank you
