### ISSUE TITLE
Using only one core on 64+ threads dual xeon systems

### ISSUE THREAD

**Issue by c-corazza** [xmrig/xmrig#150]
It is using only one cpu on dual Xeon with more than 64 threads. I have a dual 2683v3 56threads and everything works fine. On my dual 2699v4, it is using only one core. I guess it's because windows make processor groups above 64threads, and it's not handled by the program.

**Comment by xmrig** [comment]
You meant used only one physical CPU? Probably it 2 NUMA nodes, please check #86 and related issues.
Thank you.

**Comment by c-corazza** [comment]
Yes, it use one physical CPU only. There are 2 NUMA nodes for sure as I have 88 threads on this computer. I looked #86 but did not helped much. Is there a way to fix it on my own ?

**Comment by xmrig** [comment]
If this issue still actual, please check v2.99.2-beta release #1077.
Thank you.
