### ISSUE TITLE
linux static compiler

### ISSUE THREAD

**Issue by huai201208** [xmrig/xmrig#152]
I would like to run under linux xmrig, how can I static compiler?

**Comment by mnik247** [comment]
+1
I tried on Ubuntu 16 and can only witn libuv:
cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libuv.a
Try build with:
-DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libmicrohttpd.a 
Get make ERROR:
/build/libmicrohttpd-FgwLTb/libmicrohttpd-0.9.44+dfsg/src/microhttpd/connection_https.c:157: undefined reference to `gnutls_record_check_pending'
/build/libmicrohttpd-FgwLTb/libmicrohttpd-0.9.44+dfsg/src/microhttpd/connection_https.c:154: undefined reference to `gnutls_bye'
collect2: error: ld returned 1 exit status
CMakeFiles/xmrig.dir/build.make:1137: recipe for target 'xmrig' failed
make[2]: *** [xmrig] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig.dir/all' failed
make[1]: *** [CMakeFiles/xmrig.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

And how can I static buid with glibc?

**Comment by xmrig** [comment]
Easy way, build without libmicrohttpd `-DWITH_HTTPD=OFF`
If you need HTTP API you should build custom libmicrohttpd without extra dependencies (TLS, etc).
