### ISSUE TITLE
Share above target

### ISSUE THREAD

**Issue by hackerzade** [xmrig/xmrig#1523]
Hello,i have a little idea about mining and i met this issue. I am mining XMR via nicehash.While i am mining i allways see red letters with 'Share above target' and i am adding photo too. I found a solution about it via forums but i could not understood what to do. it is here : https://github.com/xmrig/xmrig/issues/458 

I dont know how to set --variant 0. i need some help about it. i got no idea how to do it.
Thank you.
![help](https://user-images.githubusercontent.com/60521964/73566935-3c7ee400-4476-11ea-9c09-e956e1399d3e.jpg)

**Comment by hackerzade** [comment]
And i do not know why my ms is high like that. I am using GPU mining same time with CPU mining. is it causes that high ms?

**Comment by ValoWaking** [comment]
do you have any overclocked parts in your system?

**Comment by hackerzade** [comment]
No,i did not.

**Comment by xmrig** [comment]
I just check I works fine, is this issue still persists? if case if it nicehash.com related issue. Make sure you enable nicehash in config `"nicehash": true,`

You use GPU for mine another coin or for RandomX? Anyway you can disable it temporary and please note nicehash.com will not pay you in XMR.
Thank you.

**Comment by hackerzade** [comment]
There was no config as "nicehash": true in general.json file . I am using my GPU for random highest rated coins but i am mining XMR with my CPU.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/blob/master/src/config.json#L63

**Comment by hackerzade** [comment]
There are too much difference between this json and mine. its interesting.

**Comment by hackerzade** [comment]
I will copy old one to somewhere else and i will use new one with making changes for wallet adress.
Thank you.

**Comment by implodnik** [comment]
There was a problem on the EU Nicehash servers on Jan. 31st, everyone got there 100% rejects with "share about target" reason, then just "internal server error"s . US servers worked fine.
