### ISSUE TITLE
v5.5.1 Crash on AMD Radeon 5700 XT

### ISSUE THREAD

**Issue by BARUCHER777** [xmrig/xmrig#1524]
The video card crashes when you try to pass the benchmark, freezes, and then gives a blue screen!
AMD drivers for the latest version!

**Comment by xmrig** [comment]
What coin/algorithm you trying to mine?
Thank you.

**Comment by BARUCHER777** [comment]
Monero

**Comment by xmrig** [comment]
1. This GPU not supported for RandomX (only generic OpenCL code available)
2. Compatibility with recent drivers is known issue #1417
