### ISSUE TITLE
Verbose Options in Config file

### ISSUE THREAD

**Issue by adriancheok** [xmrig/xmrig#1528]
What should be the options for Verbose in the Config File ? I am not sure it is only 0 and 1 or can it be another number?

**Comment by xmrig** [comment]
Right now only `0` (or `false`) and `1` (or `true`) supported, any other number above `1` reserved for future use and equivalent to `1` in current version.
Thank you.

**Comment by adriancheok** [comment]
Thank you so much,
Adrian
