### ISSUE TITLE
lots of rejected shares with 2.4.0 on dwarfpool [no issue. it's the pool]

### ISSUE THREAD

**Issue by McChickn** [xmrig/xmrig#153]
It starts with the duplicate job error message, and after that the next shares get rejected ("low difficulty"), until a new job is recieved. Caused ~3% rejected shares. 
Switched back to 2.3.1 - duplicate jobs msg (~2 per hour) is never followed by rejected shares.

**Comment by McChickn** [comment]
nvm, happens with 2.3.1 too, just too longer and seems less frequent. So maybe a problem with the pool?

**Comment by mnik247** [comment]
It's not problem xmrig.
Its's pool problem.
I have same problem with ver.2.3.0 yet, and finally left this pool.

**Comment by McChickn** [comment]
Ah damnit. Thanks, good to know.

**Comment by xmrig** [comment]
That weird I was think I fix this dwarf issue in 2.4.0, sometimes pool send job with duplicate ids but different blob. What address did you use (usa/eu) and port?
Thank you.

**Comment by McChickn** [comment]
I'm on the eu server port 8005

**Comment by xmrig** [comment]
Definitely something wrong with pool, sometimes received fully duplicated jobs.
Also I get about same rejection ratio in xmr-stak-cpu, but errors is not verbose, need press `r` to see it.
Thank you.

**Comment by McChickn** [comment]
Could this rejecting be worked around by making the miner reconnect or switch to fallback url whenever a duplicate job is recieved? When establishing a new connection the recieved new job should be valid at least.

**Comment by xmrig** [comment]
Good idea, disconnect from pool if duplicated job received probably best solution.
Thank you.

**Comment by xmrig** [comment]
Your idea works well, about 12 hours of run, 0 rejected shares.

**Comment by McChickn** [comment]
I selflessly offer to test it for an even longer time, with a win64 binary.

**Comment by klobymoby** [comment]
have same problems on pool.supportxmr.com getting lots of "[pool.supportxmr.com:7777] duplicate job received, ignore" using xmrrigproxy 2.4.1 and workers use xmrig 2.4.1

**Comment by xmrig** [comment]
It well known issue for nodejs-pool based pools, has no negative impact, no rejected shares, etc.
But connection will be force closed as well in next release.
Thank you.

**Comment by xmrig** [comment]
Fixed in 2.4.2 release.
