### ISSUE TITLE
Nvidia 2070 Super low hashrate (?

### ISSUE THREAD

**Issue by kekojeda** [xmrig/xmrig#1534]
How much hashrate should a 2070 super mining monero give?
I think 922h / s is very little. I want to know if I'm doing something wrong
![2070](https://user-images.githubusercontent.com/31479202/73773153-6713ba00-4760-11ea-93ff-23d3926178ac.jpg)

**Comment by SChernykh** [comment]
922 h/s is a bit low hashrate for GTX 2070, it should be closer to 1000 h/s. You can probably tune your config, but don't expect more than 100 h/s increase.
