### ISSUE TITLE
Hashrate Slow Down On VPS

### ISSUE THREAD

**Issue by rizkikober** [xmrig/xmrig#1539]
OS : Ubuntu 18.0.4 LTS
CPU : Xeon E-2686 V4 1C/1T NUMA:1
RAM : 512 MB :-( Sad
![Screenshot_2020-02-06-22-23-46](https://user-images.githubusercontent.com/54048440/73951923-3b2a3d00-48f6-11ea-9514-8f3ffa0e0fe7.png)
Please Help Mee !

**Comment by 2010phenix** [comment]
are you in mind? minirgate, really?? ))

**Comment by rizkikober** [comment]
> 
> 
> are you in mind? minirgate, really?? ))

help me bro

**Comment by 2010phenix** [comment]
@rizkikober You have 1 core quota, with this hardware you can't mine RandomX with good H/s... try something(algo) else

**Comment by cryptonius** [comment]
Priority? Try the default one.

**Comment by Spudz76** [comment]
Likely VPS provider has script to reduce priority on high CPU users, triggered by high CPU usage for whatever they decide is "too long".

Also 512M is not enough for much of anything.
