### ISSUE TITLE
API /1/threads no longer functional

### ISSUE THREAD

**Issue by delawr0190** [xmrig/xmrig#1541]
**Describe the bug**
The API endpoint /1/threads seems to no longer exist.  Was the endpoint changed, or removed?  If removed, would it be possible to get it back?  Otherwise, from the API endpoint, there's no way to differentiate between CPU threads and GPU threads.

**To Reproduce**
Run xmrig with the API enabled.

**Expected behavior**
/1/threads returns threads.

**Required data**
N/A

**Additional context**
N/A

**Comment by xmrig** [comment]
It replaced to `/2/backends`.
Thank you.

**Comment by delawr0190** [comment]
I found it.  Thank you for the information.
