### ISSUE TITLE
Issue with trying to compile xmrig with Intel Clear Linux

### ISSUE THREAD

**Issue by agentpatience** [xmrig/xmrig#1542]
I have installed GCC and HWloc package for clear linux but I get this error when I try to run "cmake .." to configure compiler with xmrig.

-- Looking for syslog.h - found
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find HWLOC (missing: HWLOC_LIBRARY HWLOC_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindHWLOC.cmake:25 (find_package_handle_standard_args)
  src/backend/cpu/cpu.cmake:30 (find_package)
  src/backend/backend.cmake:1 (include)
  CMakeLists.txt:37 (include)

-- Configuring incomplete, errors occurred!

**Comment by agentpatience** [comment]
jeff@clr-bd71aad388f64c998025694e7c636eeb~/xmrig/build $ whereis hwloc
hwloc: /usr/share/hwloc /usr/share/man/man7/hwloc.7

**Comment by xmrig** [comment]
I am not familiar with clear linux, but you need hwloc-dev or hwloc-devel or something like that, as alternative you can build own hwloc (use examples for Ubuntu https://xmrig.com/docs/miner/ubuntu-build) or build miner without hwloc `-DWITH_HWLOC=OFF`.
Thank you.

**Comment by agentpatience** [comment]
Thanks that resolved the hwloc error (installing sudo swupd bundle-add devpkg-hwloc) but now I am trying to find the bundle for UV as I get this error now:

-- Found HWLOC: /usr/lib64/libhwloc.so  
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find UV (missing: UV_LIBRARY UV_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindUV.cmake:25 (find_package_handle_standard_args)
  CMakeLists.txt:175 (find_package)

**Comment by agentpatience** [comment]
Solved with sudo swupd bundle-add devpkg-libuv now:
Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
CMake Error at cmake/OpenSSL.cmake:23 (message):
  OpenSSL NOT found: use `-DWITH_TLS=OFF` to build without TLS support
Call Stack (most recent call first):
  CMakeLists.txt:180 (include)


-- Configuring incomplete, errors occurred!

**Comment by agentpatience** [comment]
solved with sudo swupd bundle-add devpkg-openssl

cmake .. completed without error. I will post my benchmarks later.

**Comment by ValoWaking** [comment]
did u use icc compiler? I'm interest Visual Studio vs GCC (ICC) on Clear linux...

**Comment by agentpatience** [comment]
I am using GCC only for now... I will have some benchmarks soon.

**Comment by agentpatience** [comment]
Manjaro - 11314 h/S avg
Clear Linux - 11116 h/s avg :(

**Comment by ValoWaking** [comment]
> 
> 
> Manjaro - 11314 h/S avg
> Clear Linux - 11116 h/s avg :(

Amazing! Manjaro faster than Clear Linux!?
Did you try something from BSD? OpenBSD, FreeBSD etc...

**Comment by ValoWaking** [comment]
How do you run tests? Are you using virtual machine, or install OS directly?

**Comment by agentpatience** [comment]
Server install the tests used GCC as the default compiler. Manjaro seems a little faster. I will try FreeBSD next.

**Comment by ValoWaking** [comment]
> 
> Server install the tests used GCC as the default compiler. Manjaro seems a little faster. I will try FreeBSD next.
> […](#)
> Sent from my iPhone
> On Feb 9, 2020, at 8:42 PM, ValoWaking ***@***.***> wrote: ﻿ How do you run tests? Are you using virtual machine, or install OS directly? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

did u try BSD OS?

**Comment by agentpatience** [comment]
Yes. On E5-2699 V4 I get marginally better performance with Manjaro.

FreeBSD 12.1   - 16648 h/S
Manjaro 18.1.5   - 16908  h/S

**Comment by ValoWaking** [comment]
I will try OpenBSD with xfce. The most performance i have with Linux Mint (Debian edition). But i never tried Manjaro

**Comment by agentpatience** [comment]
I get comparable results with Clear Linux however the system seems quicker with Clear Linux under mining load. FWIW I used GCC 9.2 to build xmrig in all OS tests.

**Comment by agentpatience** [comment]
Clear Linux on dual 2699 V4 - 16559 h/S
