### ISSUE TITLE
Mac OS X build

### ISSUE THREAD

**Issue by Neuroelectric86** [xmrig/xmrig#1543]
I'm running Mac OS X El Capitan on a 2009 Macbook, I was gonna partion my HD to run Windows but I think I can get Xmrig to work. My issues seem to be average with Windows users, my first issue is; CMake Error at /usr/local/Cellar/cmake/3.16.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find UV (missing: UV_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.16.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindUV.cmake:25 (find_package_handle_standard_args)
  CMakeLists.txt:175 (find_package)....

**To Reproduce**
After downloading the master and all deps from Homebrew:
mkdir xmrig
cd xmrig
mkdir build
cd build
cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl

I expected the executable would be created so I can create the conf.json to make configurations. 

mkdir xmrig
cd xmrig
mkdir build
cd build
cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
Ryans-MacBook:build Neuroelectric$ cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found HWLOC: /usr/local/lib/libhwloc.dylib  
CMake Error at /usr/local/Cellar/cmake/3.16.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find UV (missing: UV_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.16.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindUV.cmake:25 (find_package_handle_standard_args)
  CMakeLists.txt:175 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/Neuroelectric/xmrig/xmrig/build/CMakeFiles/CMakeOutput.log".
Ryans-MacBook:build Neuroelectric$ make
make: *** No targets specified and no makefile found.  Stop.
Ryans-MacBook:build Neuroelectric$ 

 OS X 10.11.6
 Nvidia Geforce 9400M 256 MB

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/macos-build
Very likely you missed `brew install libuv`, anyway this error means development files for libuv not found.
Thank you.

**Comment by Neuroelectric86** [comment]
I got it to work, thanks.
