### ISSUE TITLE
Unable to set thread count in newest Nicehash program for Windows

### ISSUE THREAD

**Issue by minerlady49** [xmrig/xmrig#1548]
**Describe the bug**
It's not a bug per-say I am simply unable to successfully edit the config file(s) to reduce the threads used by xmrig in the newest NH mining program 3.0.0.4

If you could please let me know how to do this I would truly appreciate it. At this time, I am having to set affinity for each program after every update (which has been more frequent than usual). I understand this is not Nicehash program support however I am unable to locate any help on their website for adjusting this in the newest release. There was a place in the old style to add extra parameters however they do not make that accessible in the windows gui version.

Thank you so much for any help you can provide.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/blob/master/doc/CPU.md
