### ISSUE TITLE
MacOS - dyld: Library not loaded: /usr/local/opt/hwloc/lib/libhwloc.15.dylib

### ISSUE THREAD

**Issue by prismspecs** [xmrig/xmrig#1552]
Is it possible to link a static libhwloc as with libuv? When I try to run a compiled binary on another Mac system it gives me this error: dyld: Library not loaded: /usr/local/opt/hwloc/lib/libhwloc.15.dylib

**Comment by xmrig** [comment]
Please take look to advanced build https://xmrig.com/docs/miner/macos-build
Thank you.
