### ISSUE TITLE
Software boggs down system

### ISSUE THREAD

**Issue by Zeal0usD** [xmrig/xmrig#156]
I am running GTX 1060 G1 6GB and using standard settings but the entire computer becomes slows to respond to anything, is this normal that the rest of the computer is slow to respond?

**Comment by xmrig** [comment]
If you use Windows increase bfactor to 12 and bsleep 100, default values 6 and 25.
Thank you.

**Comment by xmrig** [comment]
This issue should placed here https://github.com/xmrig/xmrig-nvidia/issues
