### ISSUE TITLE
Build libuv with VS 2019

### ISSUE THREAD

**Issue by ValoWaking** [xmrig/xmrig#1561]
Any one help with build libuv by VS 2019

**Comment by BlankerL** [comment]
The prebuild one has already been provided [here](https://github.com/xmrig/xmrig-deps/releases). No need to build it on your own.

**Comment by ValoWaking** [comment]
Prebuild pack is update very slowly...

**Comment by BlankerL** [comment]
> Prebuild pack is update very slowly...

Yes, but they work and the latest version doesn't seems to have any hashrate enhancement.

**Comment by xmrig** [comment]
libuv version not affect hashrate at all and not to much important, unless you found bug in specific version.
Thank you.
