### ISSUE TITLE
compile xmrig in linux with shared libs ... anyone ?!?!

### ISSUE THREAD

**Issue by ras2xm** [xmrig/xmrig#1564]
Hi to y'all 
I want to compile xmrig with shared libs, why ? easy ... after compiling with shared libs you can take the 'exe' and run it over distributions without having to install again and again resources and compiling it on each individual machine again and again and again ... how can we do that ?

**Comment by trasherdk** [comment]
I think you got it backwards. If compiled with shared libraries, you need to have those libraries, with matching version, installed on every target machine. With static compile, you don't.

**Comment by ras2xm** [comment]
> I think you got it backwards. If compiled with shared libraries, you need to have those libraries, with matching version, installed on every target machine. With static compile, you don't.

so what u're telling me to compile with static ? let me tell you this : I want to make an "exe" ( xmrig ) including all libs and everything that xmr needs in order to use that "exe" to use it in debian/ubuntu/centos without installing / compile on every distro everytime from scratch if I have different machines , I know it ca be done but like you... there are others saying one thing and others another thing  ... not sure what to believe anymore!!!

**Comment by BlankerL** [comment]
> > I think you got it backwards. If compiled with shared libraries, you need to have those libraries, with matching version, installed on every target machine. With static compile, you don't.
> 
> so what u're telling me is to compile with static ? let me tell you this : I want to make an "exe" ( xmrig ) including all libs and everything that xmr needs in order to use that "exe" on debian/ubuntu/centos without installing packets libs etc.... or to compile it on every distro everytime from scratch ... I have different machines... one is debian one is ubuntu ... centos ... one is from 2017 , another from 2018 / 2015 .... I know it can be done but like you... there are others saying one thing and others another thing ... not sure what to believe anymore!!!

Actually, I think what you are talking about is static compiling.

**Comment by xmrig** [comment]
@ras2xm do advanced build on oldest system https://xmrig.com/docs/miner/ubuntu-build eg 16.04 it will likely work almost elsewhere.
Than you.

**Comment by ras2xm** [comment]
./xmrigexe
./xmrigexe: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./xmrigexe)
./xmrigexe: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./xmrigexe)
so I think you did not understand what I want and that link you provided is no good , yeah it is compiling but when I change the distro from debian to centos it doesn't wotk it doesn't have everything in order to run it on whatever distro with the same x64 arch , and I know you can do this but ..... nevermind , if you guys DO NOT KNOW then ....

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/build/alpine
