### ISSUE TITLE
Build error: uv.h: No such file or directory

### ISSUE THREAD

**Issue by yazeed44** [xmrig/xmrig#1565]
List of the commands I used:
 cmake .. -DUV_LIBRARY=/usr/lib64/libuv.a
make

xmrig/xmrig/src/base/io/Console.h:32:10: fatal error: uv.h: No such file or directory
 #include <uv.h>
          ^~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/xmrig.dir/build.make:89: CMakeFiles/xmrig.dir/src/base/io/Console.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:141: CMakeFiles/xmrig.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Trying to build within Fedora 30. I have libuv.x86_64, libuv-devel.x86_64, libuv-static.x86_64 on my machine

**Comment by xmrig** [comment]
Probably you need specify `-DUV_INCLUDE_DIR=` or not specify both options at all.
Thank you.
