### ISSUE TITLE
Trouble with s775 and huge pages 11/100%

### ISSUE THREAD

**Issue by ValoWaking** [xmrig/xmrig#1566]
Hi, i have trouble with s775 and huge pages 11/100%
I have 4gb RAM and "huge pages permission granted" but huge pages loaded less than 10%
any fix?

forgot, cpu - q6600, possible use 4 threads

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/hugepages 

> Please note on Windows no way to reserve huge pages for future use and the miner still can fail to allocate all required huge pages, because other applications use memory, if you got less than 100% of huge pages best option is reboot.

Also please check https://www.reddit.com/r/MoneroMining/comments/f18825/windows_10_tuning_guide_for_randomx_mining/

**Comment by ValoWaking** [comment]
That PC has win7x64. I also try start miner after reboot - and have same result. Also i try run miner with Admin rights. Usage memory after run windows is 700MB, totally i have 3300MB free memory.

**Comment by Spudz76** [comment]
4GB is tight, you may have to boot with most startup garbage disabled (virus scanners, etc, wasting memory before you can launch miner).

**Comment by ValoWaking** [comment]
i didn't have any garbage virus scanners, etc. After Windows load i have 3.3GB free memory.

**Comment by Spudz76** [comment]
Yes but, you want 2.3GB of hugepages.  One app loading at startup could allocate even one small page in the middle of that 2.3GB and then you get no hugepages.  Has to be contiguous memory.  Startup apps don't need to be large just allocating before miner has a chance to reserve.

**Comment by ValoWaking** [comment]
I do cleaned my autostart from all and disable some unneeded windows services, it's no fix. Maybe try to install some linux distro and try "1GB linux huge pages"?

**Comment by Spudz76** [comment]
That probably won't work either, you have to reserve 3*1GB pages (with kernel args so it's done before userspace starts) which means entire system has to fit in 1GB remaining.  You don't get to use the leftover part of the third GB then (blowing 3GB for 2.3 usage, lose 700MB).  But it could work with normal 2MB hugepages but still maybe not.

4GB is really really really tight like probably not enough.
