### ISSUE TITLE
cross build for armv7?

### ISSUE THREAD

**Issue by esrrhs** [xmrig/xmrig#1583]
hi, can somebody tell me how to build xmrig for armv7 on centos x64 or ubuntu x64?  I had search in the issues and did not find it. thanks!

**Comment by DocDrydenn** [comment]
This is what I made to help me. Maybe it will work for you too.

[https://github.com/DocDrydenn/xmrig-build](https://github.com/DocDrydenn/xmrig-build)

**Comment by xmrig** [comment]
@DocDrydenn thanks for sharing the link, but author asking for cross build not sure if it even possible.

**Comment by DocDrydenn** [comment]
Ah... You're right. I saw "ARMv7" and my brain immediately went to the `-DARM_TARGET` parameter.

So cross-compiling.... interesting...
