### ISSUE TITLE
WITH_HTTP=OFF cmake option fails to link

### ISSUE THREAD

**Issue by turtleminor13** [xmrig/xmrig#1585]
**Describe the bug**
Using cmake option WITH_HTTP=OFF fails to link with undefined reference errors

**To Reproduce**
xmrig v5.8.2 on ubuntu with gcc 8.3, link fails 

![image](https://user-images.githubusercontent.com/49797136/76153235-28825f80-607e-11ea-9372-4a23a9fd6317.png)

![image](https://user-images.githubusercontent.com/49797136/76153211-e35e2d80-607d-11ea-88d4-05188be2b836.png)

**Comment by xmrig** [comment]
Fixed https://github.com/xmrig/xmrig/releases/tag/v5.9.0
