### ISSUE TITLE
Script killed 

### ISSUE THREAD

**Issue by jhankz** [xmrig/xmrig#1589]
![Screenshot_20200309-171508](https://user-images.githubusercontent.com/61969060/76203667-9b7c0980-6229-11ea-9c8c-bac037f4fc0d.png)

**Comment by SChernykh** [comment]
It says `Memory 2.6/2.6 GB (98%)` on startup. You don't have enough free memory, so Android kills XMRig when it tries to allocate 2 GB dataset.

**Comment by Spudz76** [comment]
You can't use RandomX based coins due to not enough memory, require 2336MB for dataset even before any scratchpads.

Other coins should work?
