### ISSUE TITLE
Algorithm Request: Cryptonight Dynamic

### ISSUE THREAD

**Issue by cogitocat** [xmrig/xmrig#1591]
Hello,

I'd like to request that crytonight dynamic be added.  This is particularly used by blur (https://blur.cash) and has good development happening.

https://github.com/blur-network/blur

**Comment by fart-master** [comment]
https://github.com/fart-master/blur-miner

Already exists. Nvidia only. AMD needs some love, but I don't have the hardware

**Comment by who-biz** [comment]
Official support by XMRig would be great.  Happy to help out with the code, if desired.

**Comment by who-biz** [comment]
I already spoke with bendr0id over at XMRigCC about official support for CN-Dynamic as well. 

Happy to help with code, if desired. 

You’ll find pretty well annotated code here, on the algorithm: https://github.com/blur-network/blur/blob/master/src/cryptonote_basic/cryptonote_format_utils.cpp#L945

Don’t mind fart-master. He likes to follow our team around... But feel free to use his code as a reference implementation, too. However, note that his code’s `rapidjson` doesn’t appear to play nice with our `epee` library.

All of our miners run at least one full node. So pool/stratum support would not be necessary.

**Comment by fart-master** [comment]
So why not just submit a PR if you are happy to help with code? The code already exists and is not lengthy, just put it into a PR instead of asking people to do it for you

**Comment by fart-master** [comment]
BTW, I made no modifications to rapidjson. Dimwit

**Comment by who-biz** [comment]
I may end up PRing it. But I’m not familiar with XMRig code. I’ll let other weigh in before doing so.

Perhaps you should PR your changes, if you’re here to help. No need for the animosity. 

But, should serve as evidence of why we are requesting official XMRig support, instead of going with a persistently malicious author’s implementation.

**Comment by fart-master** [comment]
Malicious? You're a moron. It isn't malicious to point that out. Is it malicious to say the sky is blue?

**Comment by who-biz** [comment]
🙄

**Comment by fart-master** [comment]
Just to point out the code already exists and you don't need to be wasting more people's time by asking someone else to do it for you

**Comment by who-biz** [comment]
I’ve been working on integrating DPoW for 11 months now. You’re aware of this. 

Since we are entering the final stage of that rewrite, I’m short on time. The work will be easier for someone familiar with XMRig. However, as I’ve said, I’m happy to help, if necessary.

**Comment by fart-master** [comment]
You mean that dpow that was meant to be finished in June last year? Seems like an excuse. You can't find a few hours in 11 months? I wasn't familiar with xmrig either till I downloaded it an looked at it for half an hour. Real programmers don't use "I'm unfamiliar with the code" as an excuse. You are clearly just not a real programmer. And that is fine, but don't pretend otherwise.

**Comment by who-biz** [comment]
Entitled to your opinion. 

But since others said “it couldn’t be done”... I’d say a year of time is pretty good for a near-full rewrite.

Nice try, though. Have a good night.

If someone from XMRig could let me know if the modifications are too much for your group to manage... I’ll devote the time, when I have some to spare.

**Comment by fart-master** [comment]
Sources? You keep saying people said it couldn't be done. I am yet to see anyone who said that. I have however seen many people who think it's a stupid idea

**Comment by cogitocat** [comment]
Fart is a shameless paid shrill.  I'm more than one occurrence he has said that he is getting paid to naysay. He likes to interject his negativity to distract progress on this project.

**Comment by fart-master** [comment]
So funny. You think you're important enough that people are paying others to say bad things about you. What progress am I hindering? You are 9 months past deadlines you imposed. Seems you're doing just fine at not delivering results all by yourself

**Comment by cogitocat** [comment]
There is no think.  You've flat out said it.  Let's stay on track and
respect the XMrig project, and this request.

**Comment by fart-master** [comment]
Lulz. Such silly people. So who is paying me? The deep state scared your little shitcoin is going to overthrow the almighty dollar? Maybe it's the Monero fans scared your coin with no trading volume is going to become the foremost cryptonote coin? Who exactly do you believe is financing a fud campaign against you?

Want xmrig support? Just do it yourself. Use the miner that exists or submit a PR. asking someone else to do your dev work is weak.

**Comment by Spudz76** [comment]
Unless it's already popular and has a certain level of network hashrate (not sure of current limits) nobody is going to add it, unless it's you with a PR and even then it probably won't be accepted unless again, network hashrate is there already.

**Comment by who-biz** [comment]
@Spudz76 any idea what a threshold is for network hashrate?

“Hated” sounds a bit arbitrary.

**Comment by Spudz76** [comment]
Network hashrate total, like from the coins main explorer, or a pool.  I have no idea what the current limit is I knew it when CN-R was a thing before RX.  Essentially if it's not already popular and has a bunch of activity and also probably can be traded somewhere to a more mainstream coin, it doesn't get added.  They have to be past the infant-mortality point, most new coins disappear.

> “Hated” sounds a bit arbitrary.
It is completely arbitrary.  Such as if the coin creator is a toxic jackass, etc.  Or just don't like the coin.  I don't even know why defyx won't be accepted other than it won't.

**Comment by who-biz** [comment]
I understand what network hashrate means. I was asking about what you refer to as “limits,” it seems. 

Alright. Thanks for the info
