### ISSUE TITLE
Major TLS (Transport Layer Security) subsystem update

### ISSUE THREAD

**Issue by xmrig** [xmrig/xmrig#1596]
Version 5.10.x brings major TLS (Transport Layer Security) subsystem update since it was firstly implemented.

Major changes:
* Automatic TLS certificate generation for xmrig-proxy and the miner.
* TLS zero configuration for the proxy out of box. https://xmrig.com/docs/proxy/tls
* HTTPS support for API (automatic detection).
* Automatic TLS detection for the proxy ports.
* Multiple other fixes and improvements.

**Comment by Spudz76** [comment]
@1601 may be related

**Comment by ttsite** [comment]
Can you just enable this TLS in xmrig proxy? It should also be enabled in xmrig How to change the specific configuration file
