### ISSUE TITLE
Further optimizing AstroBWT hash skipping

### ISSUE THREAD

**Issue by nYrXvcpk2l47ciid** [xmrig/xmrig#1597]
Regarding commit eeadea53e2ee0841927e23fbf97bd26848b8dc86, how can one benchmark their hardware to find what range of values may be most optimal for the --astrobwt-max-size flag? Seeing as the default of 550 is a middle ground of sorts between cpus, it would be nice if one could fine-tune it. @SChernykh, did you happen to get the values for the different cpus from some benchmarking program?

**Comment by SChernykh** [comment]
I found little difference between all values in 500-600 range on my CPUs (both AMD and Intel), values outside that range were worse.

**Comment by nYrXvcpk2l47ciid** [comment]
Thanks for the closure.
