### ISSUE TITLE
compiler xmrig %99 and errors occured

### ISSUE THREAD

**Issue by muyuxx** [xmrig/xmrig#1599]
hi guys,how can i fix it
centos6.8
gcc6.1
cmake3

[ 96%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/astrobwt/sha3.cpp.o
[ 96%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/astrobwt/Salsa20.cpp.o
[ 97%] Building CXX object CMakeFiles/xmrig.dir/src/base/io/log/backends/SysLog.cpp.o
[ 97%] Building CXX object CMakeFiles/xmrig.dir/src/base/net/stratum/Tls.cpp.o
[ 98%] Building CXX object CMakeFiles/xmrig.dir/src/base/net/http/HttpsClient.cpp.o
[ 98%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/common/Assembly.cpp.o
[ 99%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/cn/r/CryptonightR_gen.cpp.o
[ 99%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/cn/gpu/cn_gpu_avx.cpp.o
[100%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/cn/gpu/cn_gpu_ssse3.cpp.o
[100%] Linking CXX executable xmrig
/usr/lib/../lib64/libuv.a: error adding symbols: Malformed archive
collect2: error: ld returned 1 exit status
make[2]: *** [xmrig] Error 1
make[1]: *** [CMakeFiles/xmrig.dir/all] Error 2
make: *** [all] Error 2

**Comment by trasherdk** [comment]
Install, or compile, a recent version of `libuv`.
My version is `libuv-1.23.2` [compiled from source](https://dist.libuv.org/dist/).
