### ISSUE TITLE
gcc-win64 compile gives hasrate drop

### ISSUE THREAD

**Issue by YetAnotherRussian** [xmrig/xmrig#16]
Hi, just to inform that gcc-win64 compile gives hasrate drop when compared to msvc version.

As for numbers, it's 774H/s vs 749H/s on stock i5-4570 CPU for cryptonight-light (3 double threads). It's win7 x64 system.

So I guess it's no point to compile x64 binary using gcc, and maybe you should try msvc for x32 as well.

**Comment by xmrig** [comment]
You right, for x64 msvc version faster than gcc, according my tests too.

But for x32 situation is different, msvc version 10% slower than gcc.

**Comment by YetAnotherRussian** [comment]
Hmm, OK then :) I guess I shouldn't test x32 version on x64 system.
