### ISSUE TITLE
Mining, or is it?

### ISSUE THREAD

**Issue by imrecsoka** [xmrig/xmrig#160]
![image](https://user-images.githubusercontent.com/25494601/31812214-8bcc5c8e-b582-11e7-84e9-b9fd4c198bd6.png)

Hi, i dont understand this, i am not sure if it is mining?
I tried to mine cryptonight-light also for 7 hours and nothing shows in my wallet, it just shows 0.000000
i typed balance in the command line.

My screenshot shows cryptonight though, is that seemingly working?

**Comment by xmrig** [comment]
Green accepted messages means your shares successfully accepted by pool.
You need check your pending balance on pool side, your wallet balance will be updated only after you reach minimum payment threshold.

**Comment by imrecsoka** [comment]
Okay, i will see how it goes. 
I previously used XMR-STAK-AMD from Fierce UK and i let it mine all night and i got bugger all the next day , i dont understand if i am being robbed.

Please can you suggest a reliable AEON and XMR pool....
Can i use my own AEOND.exe Simplewallet.exe address?  and Monerod.exe Monero Wallet Gui.exe  address?

I know some pools use the username.worker and then revert that to your wallet address.
I am just checking in case i dont understand this.
I have been wanting to mine these directly for a long time and never got to understand it, such a real pain.

**Comment by xmrig** [comment]
All pools works same, first your balance updated on pool, usually pools require you put your wallet address, after limit reached pool pay you.

**Comment by imrecsoka** [comment]
Hi, i hope so.
If i have 2  RX470 running normal speed no overclocking, how long should it be for the first fraction?
Any guess will be good...

**Comment by xmrig** [comment]
If minimum payment limit is 0.3 XMR about 2 weeks.

**Comment by imrecsoka** [comment]
Oh my goodness, okay well thanks.
But I can actually see the 0.0000whatever building up surely?
I mean i can keep track of this right ?

**Comment by xmrig** [comment]
Yep, put your wallet address or whatever on pool website to see your stats.

**Comment by imrecsoka** [comment]
Okay. I guess that Payment ID address is a different thing? i dont need to worry about that for now?
In my Monero wallet or my Aeon wallet i just use that receive address there and thats it ?

**Comment by xmrig** [comment]
Yep.

**Comment by imrecsoka** [comment]
*sharp* thanks

**Comment by murtiraya** [comment]
If i stop the program, what will happen? And if i start again, i'll continue my last mining or i lose it and start from beginning again?

**Comment by MaxQiu0108** [comment]
idk

**Comment by MaxQiu0108** [comment]
![image](https://user-images.githubusercontent.com/102963434/161941380-6a1ce113-2bd3-4918-a81c-7eb174ef7084.png)
am i mining
