### ISSUE TITLE
[dev] TLS changes break libssl 1.0.x

### ISSUE THREAD

**Issue by Spudz76** [xmrig/xmrig#1601]
**Describe the bug**
Compilation fails to locate function `DH_set0_pqg` @ [this line](https://github.com/xmrig/xmrig/commit/5b610e4dfe9ee022c57c94924b89ef5f20284881#diff-dce132ce071d432681108966c4ed9a46R82)

**To Reproduce**
Compile on old system with `libssl 1.0.2g`

**Expected behavior**
Compile and work even with libssl 1.0.x, as before this change

**Additional context**
Workarounds (polyfill) documented here (search for `DH_set0_pqg`):
https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes#Compatibility_Layer

Compilation works `WITH_TLS=OFF` but that disables Pool TLS along with API TLS.

**Comment by xmrig** [comment]
Fixed. Thank you.

**Comment by Spudz76** [comment]
Testing now on affected ancient Gentoo system

**Comment by Spudz76** [comment]
Works great, API TLS untested though.
