### ISSUE TITLE
Astrobwt algorithm is not working correctly

### ISSUE THREAD

**Issue by paolosezart** [xmrig/xmrig#1646]
The astrobwt algorithm does work not correctly when config.json is auto-configured. Tested on the Win7 intel G2030 2 cores and Win10 intel core i7 8 cores, with the parameter "max-threads-hint": 50, in both cases the processor runs at 100% power, that is, all cores are involved. When launched from the command line with the parameter --cpu-max-threads-hint = 50 or with the parameter --threads = 1 / - threads = 4, the processor works as it should, at half the power.

**Comment by backamblock** [comment]
for me it works with none of these on windows 10 64 bit

i have 4 threads but astrobwt does NOT honour my max thread hint 50, no matter where I set it. all other things work with 2 threads as told, but not astrobwt. 

please fix or tell me what to change to fix myself. thank you!

**Comment by SChernykh** [comment]
https://github.com/xmrig/xmrig/pull/2606 should fix it
