### ISSUE TITLE
Not working on AMD Opteron

### ISSUE THREAD

**Issue by solucaojp** [xmrig/xmrig#165]
I configured iqual to another server with Xeon processor, but is not getting speed from H / s, could you help me?

**Comment by solucaojp** [comment]
I configured exactly as on another server with Xeon processor, but not getting speed from H / s, could they help me?

**Comment by ght3d** [comment]
Same here, speed on old 6 core Opterons HE series doesnt display at the beginning , but after a while starts to mine with speed of max 20h/sec, 10 times slower compared to cpuminer-opt.

**Comment by xmrig** [comment]
Old Opterons without hardware AES? Might something wrong with software AES implementation.
Also huge pages enabled? If yes try disable it `--no-huge-pages`, otherwise enable it.
Thank you.

**Comment by ght3d** [comment]
In my case the opterons are 2423 HE without hardware AES, only SSE, but the huge pages are available and enabled.

**Comment by xmrig** [comment]
If this issue still actual, please check v2.99.2-beta release #1077.
Thank you.
