### ISSUE TITLE
cost large memory when build on raspberry ubuntu?

### ISSUE THREAD

**Issue by esrrhs** [xmrig/xmrig#1651]
I found it use a large memory to build RxDataset.cpp, is this normal?

# uname -a
Linux ubuntu 5.3.0-1022-raspi2 #24-Ubuntu SMP Fri Mar 27 21:32:13 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

# make
[  3%] Built target argon2
[  3%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/rx/RxDataset.cpp.o

# top
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                 
 2431 root      20   0 2748644 656504   1484 D  12.9  70.7  17:21.48 cc1plus

**Comment by xmrig** [comment]
This issue should be fixed in dev branch https://github.com/xmrig/xmrig/pull/1926
Thank you.
