### ISSUE TITLE
Nvidia GPU mining low hashrate

### ISSUE THREAD

**Issue by km0342** [xmrig/xmrig#1653]
I am using Xmrig 5.11.0 and I got an issue in Nvidia mining that my GTX 1070ti is giving me low hashrate of 600 h/s which is too low. As my corei3 6th gen cpu is giving me 700+ h/s. Nvidia card is best for mining and best from cpu but issue is cpu giving high hashrate and gpu's are giving low hashrate.  I am mining Monero on RandomX. In other mining softwares GPU is giving more hashrate mostly in MH/s. 2nd issue is that I got 12gb Ram and mining use only 2 gb and no load on cpu , and same like gpu , no load on gpu. I only got 10% load on my gpu and same as cpu. I think this is issue because if the miner use atleast 50% of our gpu and cpu it will give us high hashrates.  See the pic and tell me my configuration is wrong or what. Please Help
![Hash](https://user-images.githubusercontent.com/64122674/79945407-2128e100-8487-11ea-8495-63177092ce4c.jpg)

**Comment by km0342** [comment]
Also my Cpu got 4 cores and alot of cores on gpu. Why this software is using only 1 core of my cpu and gpu.

**Comment by firemax13** [comment]
> Also my Cpu got 4 cores and alot of cores on gpu. Why this software is using only 1 core of my cpu and gpu.

Mining monero on any gpu is useless even that gpu is very high end or very strong nor fast, still slow on monero. Actually mining monero using cpu is much better. Just disable the gpu to mine monero then start mining on the different algo/coins instead(eth, etc or zcoin). Hashrates.com visit that site to see what is the best coin to mine using gpu.
