### ISSUE TITLE
My Nvidia GPU not getting any accepted hashes but only CPU

### ISSUE THREAD

**Issue by OMGitsMohaYT** [xmrig/xmrig#1657]
There's no accepted hashes, I only see CPU accepting hashes plus the GPU is barely mining because the hashrates are very low, any advice?

**Comment by firemax13** [comment]
> There's no accepted hashes, I only see CPU accepting hashes plus the GPU is barely mining because the hashrates are very low, any advice?

Please provide log of your miner. Mining monero using CPU is way more better and faster. Also mining monero using gpu is way more useless nor slow. If I were you, I'm gonna mine using my gpu on the other algo/coins instead(zcoin, eth and etc). But before you do that, kindly send your log.

**Comment by OMGitsMohaYT** [comment]
Hello thanks for the response, May I know which log you're talking about? config or what?

**Comment by firemax13** [comment]
> Hello thanks for the response, May I know which log you're talking about? config or what?

Start your miner then wait for a few minutes then try to copy all of the context ang paste it here or paste it on .txt and send it here. Send your config file too

**Comment by OMGitsMohaYT** [comment]
Ok here it is:
https://pastebin.com/sxa0tmVt

**Comment by OMGitsMohaYT** [comment]
Any help?

**Comment by firemax13** [comment]
> Any help?

You have the very low end gpu tho. My old gtx 580 doesn't accept any work nor hashes, it doesn't start to mine other coins too.

**Comment by SChernykh** [comment]
@OMGitsMohaYT You GPU (GT 430) does mine some hashes, you can see it in the end of the log you posted. But the GPU hashrate is less than 10 h/s.
