### ISSUE TITLE
Don't compile on RPI3

### ISSUE THREAD

**Issue by CitoplasmaX** [xmrig/xmrig#166]
pi@ELR-RPI3B:~/Downloads/xmrig/build $ cmake ..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib/arm-linux-gnueabihf/libuv.so  
-- Looking for syslog.h
-- Looking for syslog.h - not found
-- Found mhd: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Downloads/xmrig/build
pi@ELR-RPI3B:~/Downloads/xmrig/build $ make
Scanning dependencies of target cpuid
[  2%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
cc: error: unrecognized command line option '-maes'
src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/build.make:62: recipe for target 'src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o' failed
make[2]: *** [src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/all' failed
make[1]: *** [src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by CitoplasmaX** [comment]
The same error https://github.com/monero-project/monero/issues/954

You need to remove the -maes flag when compiling on ARM, that flag is x86-specific.

**Comment by xmrig** [comment]
ARM not supported #94

**Comment by dunklesToast** [comment]
It also makes no sense to mine on a Pi - you would get about 1$ per Year which is much more than the Price of the Pi and the Power Consumption Costs

**Comment by xmrig** [comment]
ARMv7 support recently added.
Thank you.
