### ISSUE TITLE
AMD GPU tries to compile itself but fails

### ISSUE THREAD

**Issue by OMGitsMohaYT** [xmrig/xmrig#1662]
When I turn on open cl (make it true) in the config.json, It says: GPU compiling and after some seconds, It gives me bunch of errors, so the CPU is mining alone, I need help here please

**Comment by firemax13** [comment]
> When I turn on open cl (make it true) in the config.json, It says: GPU compiling and after some seconds, It gives me bunch of errors, so the CPU is mining alone, I need help here please

Try to open again the website of the xmrig (xmrig.com) then go to the wizard and complete your all details (don't forget to turn on the open-cl that you can found on the backend), then download it and paste it on xmrig directory. Try it
