### ISSUE TITLE
Unable to compile for android using the android ndk cmake toolchain.

### ISSUE THREAD

**Issue by realPiyush** [xmrig/xmrig#1663]
**Describe the bug**
I am on a ubuntu machine trying to cross compile xmrig for android using android ndk cmake toolchain. libuv was compiled for android using the same toolchain and was used to compile xmrig.

XMRig source was taken from the release 5.11.1.

CMake is able to generate the make files successfully with the following command:

`cmake ../.. \`
`-DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake \`
`-DANDROID_ABI=armeabi-v7a \`
`-DANDROID_NATIVE_API_LEVEL=android-22 \`
`-DWITH_CUDA=OFF \`
`-DWITH_OPENCL=OFF \`
`-DWITH_HWLOC=OFF \`
`-DWITH_TLS=OFF \`
`-DUV_LIBRARY=../../../libuv-1.37.0/build/ARMv7a/libuv_a.a \`
`-DUV_INCLUDE_DIR=../../../libuv-1.37.0/include/`

CMake Output:

`-- Use ARM_TARGET=7 (armv7-a)
-- Found UV: /root/sources/libuv-1.37.0/build/ARMv7a/libuv_a.a
-- Looking for __builtin___clear_cache
-- Looking for __builtin___clear_cache - not found
-- WITH_MSR=OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /root/sources/xmrig-5.11.1/build/ARMv7a`

![image](https://user-images.githubusercontent.com/47710035/80396284-0cf34280-88d2-11ea-869e-c45c5a9a9e41.png)

When running make to build using the Makefile generated by cmake it gives an error at the following line:

`[100%] Linking CXX executable xmrig-notls
/root/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lpthread
/root/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lrt
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/xmrig-notls.dir/build.make:1930: recipe for target 'xmrig-notls' failed
make[2]: *** [xmrig-notls] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/xmrig-notls.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-notls.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

![image](https://user-images.githubusercontent.com/47710035/80396197-ee8d4700-88d1-11ea-9531-0544be2402d3.png)

**Comment by mymirai-nikki** [comment]
did you figure it out?

**Comment by mymirai-nikki** [comment]
nevermind, I figure it out (https://github.com/xmrig/xmrig/issues/2525) ^.^
