### ISSUE TITLE
RYO still using cn/gpu

### ISSUE THREAD

**Issue by kammychan** [xmrig/xmrig#1665]
Dear project holder,

Please enable back cn/gpu on new version as RYO mining still using cn/gpu

Thanks!

**Comment by xmrig** [comment]
Sorry but the decision is already made, I don't like any relationship with Ryo devs and this is the final statement.

1. You can use older versions, nothing related to `cn/gpu` changed for a while.
2. Still possible enable this algorithm on compile time.
3. You can use their official miner or other miners.
