### ISSUE TITLE
Huge Pages +JIT randomly runs at only 11%

### ISSUE THREAD

**Issue by GoGitIt1** [xmrig/xmrig#1666]
When I first boot and start XMrig, I have no problem running huge pages at 100%. However, I am having a frequent error on 5.11.0 and the last few versions where it will only start with less than the full 1168/1168 huge pages.

I am using Windows 8.1 with a Ryzen 3950X and 16GB of RAM. RAM usage was only around 4GB, the last time I encountered this issue. Reseting the computer seems to be the only thing that temporarily fixes this. Any ideas?

**Comment by noebranco** [comment]
I have been seeing this problem in a couple of PC's also... :-(

**Comment by miningnome** [comment]
For me it's clear, you have a 16cores processor with 32threads and only 16Gb or RAM. If you want to use the real power of your CPU you need 1Gb per each thread or at least 16Gb to use the 50% of your CPU with will make temp lower. Details of your CPU: https://www.pccomponentes.com/amd-ryzen-9-3950x-470-ghz

**Comment by imadoggy** [comment]
> For me it's clear, you have a 16cores processor with 32threads and only 16Gb or RAM. If you want to use the real power of your CPU you need 1Gb per each thread or at least 16Gb to use the 50% of your CPU with will make temp lower. Details of your CPU: https://www.pccomponentes.com/amd-ryzen-9-3950x-470-ghz

I have seen this quoted several times, but find no evidence you need 1GB of ram per thread. Even the xmrig documents say 1028x2mb of RAM for hugepages and 3x1GB ram for 1GB hugepages in linux. 

For anyone finding this issue from google search, if you are running any Window Home OS hugepages are not always reserved, even if you "run as admin", you will have to reboot nearly every time you close XMRig and open it again. Solution: Reboot every time, run Windows Pro, or install Linux on your PC or USB drive.

**Comment by d4f5409d** [comment]
Same issue here on Linux, but I have found a workaround to restart on and on until it starts with 100% again.
