### ISSUE TITLE
incompatible/disabled algorithm "cn/0" detected

### ISSUE THREAD

**Issue by imrecsoka** [xmrig/xmrig#1667]
I am trying to mine against a pool , the Algorithm Masari.
So i am using 
-a cn as the algo in the command line :

I keep getting this error:
incompatible/disabled algorithm "cn/0" detected

I have tried XM-Rig 5.5 and 5.11 i dont know what the hell i am doing wrong here.

I tried -a half-fast and i tried to use --variant msr

I can successfully mine Loki and Monero though as a test.
However i would like to test other algorithms to i can contribute to speed stats .

Thank you

**Comment by SChernykh** [comment]
The algorithm for Masari is called `cn/half`
