### ISSUE TITLE
closing miner,

### ISSUE THREAD

**Issue by overunme** [xmrig/xmrig#1671]
For the last few days I have been trying mine monero with CPU. Ive had the following issues: at first PC thought it was a virus, I deativated windows security. I was then able to download the file. Then I processed the changes to create JSON file using the wizazrd.  The rig opened for a few seconds then would close. I tried opening from CMD but it would close once again. The file would eventually disapear from where i had unziped it. I have tried everything.  I am on windows 10 running ryze 3600.

**Comment by Masterbob79** [comment]
Probably json file is missing a comma or something. Or its saved as a .txt instead of .json

**Comment by 2010phenix** [comment]
add to exclusive in defender windows security miner (xmrg.exe)
start file and miner build config(JSON) for your hardware
if use CMD and want look on error... add PAUSE in last line to bat file
