### ISSUE TITLE
connect error: "operation canceled"

### ISSUE THREAD

**Issue by kamael0909** [xmrig/xmrig#1672]
OS：Ubuntu 18.04 LTS 

* ABOUT XMRig/5.11.1 gcc/5.4.0
* LIBS libuv/1.34.0 OpenSSL/1.1.1d hwloc/2.1.0
* HUGE PAGES supported
* 1GB PAGES disabled
* CPU Intel(R) Xeon(R) Gold 6266C CPU @ 3.00GHz (2) x64 AES
L2:32.0 MB L3:60.5 MB 32C/64T NUMA:2
* MEMORY 7.5/251.9 GB (3%)
* DONATE 5%
* ASSEMBLY auto:intel
* POOL #1 xmr.f2pool.com:13531 algo auto
* COMMANDS hashrate, pause, resume
* OPENCL disabled
* CUDA disabled
[2020-05-08 02:51:43.988] [xmr.f2pool.com:13531] connect error: "operation canceled"
[2020-05-08 02:52:09.016] [xmr.f2pool.com:13531] connect error: "operation canceled"

**Comment by 0xman** [comment]
Having the same issue

**Comment by SChernykh** [comment]
The same issue as in can't connect to xmr.f2pool.com:13531? Try other pools, maybe your providers blocks some connections. In this case, pools that enable mining to ports 80 or 443 might work better.

**Comment by david-serrano** [comment]
having this same issue as of last night, tried using the latest release, and also ports 5555 and 443, with tls and without, with worker name as password and without, but nothing seems to work..
