### ISSUE TITLE
read error "end of file" no active pools, stop mining

### ISSUE THREAD

**Issue by rarmob** [xmrig/xmrig#1678]
Hello,
as the title say i have an issue with xmrig v5.11.1 
after a couple of minutes comes a error message 
xmr.pool.minergate.com read error "end of file" 
net: no active pools stop mining
after that it will repeat mining but wont connect back to my wallet

How can i fix this issue ?

**Comment by mobrine-mob** [comment]
Try other pool. Minergate is not advisable

**Comment by Kudabelangfx** [comment]
which os? 
had same problem with hiveos connect to miningrigrental and use xmrig for mining to any pool. “no active pool” keep happens. miner restarting everytime.

**Comment by Masterbob79** [comment]
I have had this on hiveos before. What I found is TLS is on when it doesnt need to. Or it's off when it should be on.

**Comment by Kudabelangfx** [comment]
> I have had this on hiveos before. What I found is TLS is on when it doesnt need to. Or it's off when it should be on. 


by default it is off. 
how much accurate of your findings? any log? how did you get solve?

**Comment by Masterbob79** [comment]
I use supportxmr. When use pool.supportxmr.com:7777 with tls on I get the error. If I use pool.supportxmr.com:443 without tls, same error. 443 is their tls port. I asked the pool about it.

**Comment by Kudabelangfx** [comment]
i see. thought tls from miner conf.
