### ISSUE TITLE
Update build instructions for Fedora

### ISSUE THREAD

**Issue by mssc89** [xmrig/xmrig#1682]
Build instructions for Fedora are stuck on version 25/26, they are quite ancient. I've compiled xmrig on Fedora 32, and there are two new depediencies which need to be installed with dnf before building:
`hwloc-devel openssl-devel`
Since i cannot make pull requests to wiki, can someone from team please update it to include these depediencies? Adding `-DUV_LIBRARY=/usr/lib64/libuv.a` to the cmake is also not required anymore.

**Comment by downystreet** [comment]
I agree.

**Comment by agentpatience** [comment]
Hi Mssc89:

 #1796 I added a documentation update request for this. Can you share your instructions on a XMRig Build on Fedora 32?

**Comment by mssc89** [comment]
@agentpatience  you need to install `hwloc-devel openssl-devel` and remove `-DUV_LIBRARY=/usr/lib64/libuv.a` flag from the cmake. The rest is exactly the same as in wiki.

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/build/fedora
