### ISSUE TITLE
AMD Epyc msr mod

### ISSUE THREAD

**Issue by geriweb** [xmrig/xmrig#1685]
The msr mod settings are not working on amd epyc.
Can you fix it in the next release please?
Thank you

**Comment by SChernykh** [comment]
The MSR mod works on all Ryzen series CPUs, including EPYC. Make sure you run xmrig as admin (if using Windows) or as root (Linux). You also need to have `msrtools` installed on Linux.

**Comment by Unnameless** [comment]
Is there any other way to avoid running xmrig as root on Linux but still get pages and most mods?

**Comment by SChernykh** [comment]
Yes, run https://github.com/xmrig/xmrig/blob/master/scripts/randomx_boost.sh as root before starting xmrig

**Comment by Unnameless** [comment]
> Yes, run https://github.com/xmrig/xmrig/blob/master/scripts/randomx_boost.sh as root before starting xmrig

Thanks!

**Comment by geriweb** [comment]
[2020-05-21 17:03:09.546]  msr  cannot read MSR 0xc0011020
[2020-05-21 17:03:09.546]  msr  cannot read MSR 0xc001102b
[2020-05-21 17:03:09.546]  msr  cannot set MSR 0xc0011020 to 0x00000000

**Comment by geriweb** [comment]
root@localhost:~# cat /proc/cpuinfo
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 1
model name	: AMD EPYC 7501 32-Core Processor

**Comment by geriweb** [comment]
There is no "AMD Ryzen" in the cpuinfo file...

**Comment by SChernykh** [comment]
@geriweb Did you install `msrtools` and run xmrig as root? If you prefer the randomx_boost script, you can change `AMD Ryzen` to `EPYC` and it will work.

**Comment by geriweb** [comment]
Yes I installed, but it is not working:
wrmsr: CPU 0 cannot set MSR 0xc001102b to 0x000000001808cc16
wrmsr: CPU 0 cannot set MSR 0xc0011020 to 0x0000000000000000
wrmsr: CPU 0 cannot set MSR 0xc0011021 to 0x0000000000000040

:(

**Comment by SChernykh** [comment]
Are you running in a VM? It works only on physical CPU.

**Comment by geriweb** [comment]
VM

**Comment by TimoC1982** [comment]
Hi, well is there a way to work that for virtual enviroments?

**Comment by SChernykh** [comment]
@TimoC1982 No, it's impossible in a VM. Writing to MSR registers can be used to get full access to the physical machine, so it would be a security vulnerability if it could be done in a VM.
