### ISSUE TITLE
RandomX init setting being overwritten by max-threads-hint

### ISSUE THREAD

**Issue by Miner9009** [xmrig/xmrig#1689]
Applies to embedded config and outside config.

When using setting:
`  "max-threads-hint": 25, `

The initialization setting to use all threads is not working and is overwritten by 25% setting:
```
 "randomx": {
        "init": -1,  
```

Expecting initialization data to run on all available threads and then use 25% to mine.

OS: Windows 10

**Comment by downystreet** [comment]
I'm not quite understanding your question here. If what you're trying to say is that you want xmrig to initialize with all threads and then only mine 25%, I don't think that's possible. What you can do is go down below the "cpu" option and where you see "rx": [ ], you can put in this box the number of threads you want to use. When you start mining this box usually gets prefilled with what xmrig thinks is the optimal configuration. This option varies depending on your available L3 and L2 Cache. For example if you have a 4 core CPU with 8MB of L3 cache then rx will probably look something like this "rx": [0, 1, 2, 3]. It creates 4 threads for each 2mb of L3 cache. A 4 core cpu with 6mb L3 cache might only use [0, 1, 2]. So lets say you have a 4 core cpu with 8mb L3 cache and your config looks like "rx": [0, 1, 2, 3], you can basically set it to only use 3 cores or 75% by using [0, 1, 2] or you can set it to 50% using [0, 1] or 25% using [0]. This is basically what the "max-threads-hint" option is doing for you. I think you can also configure it to use the cores at a certain priority but I'm not 100% sure how this works and I haven't done much testing with it except i have used the setting "rx": [-1, -1, -1, -1]. Where each number represents the core priority. I can't remember if -1 is low priority or high priority but there is a doc somewhere in the docs section about this. I'm assuming this means if you wanted to set your cores to low priority they wouldn't be as much of a burden on the system when you are doing other tasks which is what I assume you are trying to accomplish with this.

**Comment by Miner9009** [comment]
> I'm not quite understanding your question here. If what you're trying to say is that you want xmrig to initialize with all threads and then only mine at 25%, I don't think that's possible. 

It's not possible due to bug, otherwise why there would be separate option for it... 
It is possible when you're not using percentage (max-threads-hint) and instead use constant to set threads to how u want for example use all threads to init and then two cores on a four core processor (50%) to mine.
