### ISSUE TITLE
Adjust Pool #1 Settings, problem connecting to other pools with XMRIG 2.4.2 

### ISSUE THREAD

**Issue by Apokolopsis** [xmrig/xmrig#169]
Hello,
I have attached screen shot this morning of the XMRIG. Pool #1 pointing to XMrig.com. How do I change that Pool #1 setting to other mining pools?
![xmrig 2 4 2 screenshot 10 24 2017](https://user-images.githubusercontent.com/33058940/31941924-8ed746ca-b891-11e7-8f7c-881e4a9c4ab0.JPG)

Thank you

**Comment by xmrig** [comment]
Please edit the config.json file near exe file or specify pool via command
line options.
Tnank you.
