### ISSUE TITLE
New hasharate logging creates extra line after getting 15m avg value

### ISSUE THREAD

**Issue by YetAnotherRussian** [xmrig/xmrig#17]
![xmrig1](https://user-images.githubusercontent.com/4670472/27282777-1cfe3162-54fa-11e7-9beb-c75753dcee87.png)

When 15m avg speed is calculated, console output creates extra line with 1 symbol. Write new line or reduce string length for output. Win7 x64.

**Comment by xmrig** [comment]
Ok thanks, on Windows 10 default size of console bigger and I forgot about older systems.

**Comment by xmrig** [comment]
I just simple rename `highest` to `max`.
