### ISSUE TITLE
Add build instuctions for CentOS 8

### ISSUE THREAD

**Issue by downystreet** [xmrig/xmrig#1706]
I noticed there were no build instructions for CentOS 8 and I happen to have them. Several repositories have to be added to get a few of the packages as they are not included in the main repositories.
1. sudo dnf install epel-release
2. sudo dnf config-manager --set-enabled PowerTools
3. sudo rpm -ivh http://repo.okay.com.mx/centos/8/x86_64/release/okay-release-1-3.el8.noarch.rpm?
4. sudo dnf install git make gcc gcc-c++ libstdc++-static hwloc-devel openssl-devel libuv-devel
5. git clone https://github.com/xmrig/xmrig.git
6. mkdir xmrig/build && cd xmrig/build
7. cmake ..
8. make -j$(nproc)

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/build/centos8

**Comment by fadsel** [comment]
Now these Build Instructions are not working any more
Please change **PowerTools** to `powertools`

Thankfully, the CentOS.org organization has [posted ](https://wiki.centos.org/Manuals/ReleaseNotes/CentOS8.2011#Yum_repo_file_and_repoid_changes) confirming and detailing the naming change.

Now the command should be 
`sudo dnf config-manager --set-enabled powertools`

Thanks
