### ISSUE TITLE
Coinbase message

### ISSUE THREAD

**Issue by Relaxo143** [xmrig/xmrig#1707]
How can one add a message to the coinbase transaction for solo mining?

**Comment by SChernykh** [comment]
You can't do it in xmrig right now, but you can https://monero.stackexchange.com/questions/11049/how-to-use-the-extra-messages-file-option

**Comment by Relaxo143** [comment]
thanks for the info. So that works only from the GUI wallet miner which is very slow. Do you plan to add the option to xmrig as well? It sure is interesting.
