### ISSUE TITLE
How to remove the display of the program name at the top of the running window?

### ISSUE THREAD

**Issue by etsam** [xmrig/xmrig#1708]
May I ask the latest 5.11.2 version How to delete the XMRING+version number at the top of the running window?

After editing with resource_hacker, you can only modify the file attributes and remove the LOGO, and cannot delete the program name on the window, but version 5.3.0 does not have this trouble. Is there any way to remove it? Thank you!
![818](https://user-images.githubusercontent.com/24689501/83705347-42185080-a647-11ea-9a72-6859e4418d50.png)

**Comment by xmrig** [comment]
Without changed source not possible remove this.

Next beta version (6.0.1) will support `title` option (code already in evo branch) with following values:
* `"title": true` current behavior, default title: miner name + version.
* `"title": false` or `--no-title` disable this feature, same as old versions.
* `"title": "Custom title"` or `--title "Custom title"`.

**Comment by alex-s-m** [comment]
а нельзя ли такую же опцию и для xmrig-proxy?
