### ISSUE TITLE
KawPow support

### ISSUE THREAD

**Issue by enigmen** [xmrig/xmrig#1709]
Hello, pls help. I creat bat file
xmrig --no-cpu --cuda -a kawpow -o kawpow.eu.nicehash.com:3385 -u wallet.name -p x
but speed "n\a". What did I do wrong?
![изображение](https://user-images.githubusercontent.com/39157390/83741122-d7780c80-a668-11ea-873d-9b7c64740ff6.png)

**Comment by xmrig** [comment]
Please show full log from miner start.
Thank you.

**Comment by enigmen** [comment]
![изображение](https://user-images.githubusercontent.com/39157390/83744684-8cacc380-a66d-11ea-83f3-2fb63c8a8c7f.png)

**Comment by SChernykh** [comment]
@enigmen Can you try to start with only 1 GPU? Remove the second GPU from the generated config.json and start without command line parameters. It might be a bug with multiple GPUs, be we need to confirm it first.

**Comment by enigmen** [comment]
i remove own gpu, creat a new config.json, but speed again n\a
![изображение](https://user-images.githubusercontent.com/39157390/83766447-80d0f980-a68d-11ea-9bef-f5edc2a54787.png)

**Comment by SChernykh** [comment]
I think the problem is that you have only 2482 MB available GPU memory when starting xmrig. I'll add more diagnostics for DAG initialization errors.

**Comment by enigmen** [comment]
ok, thanks.
Other miner (e.c. t-rex, gminer, nbminer) works, not problem.

**Comment by SChernykh** [comment]
Yes, I need to make DAG initialization less memory consuming on GPU. But your GPU is on the edge already - 5-10 more epochs and even other miners won't work. You need to figure out how to make all GPU memory available for mining.

**Comment by enigmen** [comment]
on two rx570 4gb working right :)

**Comment by SChernykh** [comment]
@enigmen Can you try [release 6.0.1-beta](https://github.com/xmrig/xmrig/releases/tag/v6.0.1-beta) with [cuda plugin 6.1.0](https://github.com/xmrig/xmrig-cuda/releases/tag/v6.1.0)? It should work on your GPU. If it doesn't work, it should print some error message instead of just not mining.

**Comment by enigmen** [comment]
hello, works

**Comment by enigmen** [comment]
v.6.2.0 crazy
![изображение](https://user-images.githubusercontent.com/39157390/84353396-1f9ab000-abd0-11ea-8824-53bafefb97c6.png)
but v. 6.1.0. conect
![изображение](https://user-images.githubusercontent.com/39157390/84353510-5a9ce380-abd0-11ea-9363-edb98c9934d5.png)

**Comment by Quake4** [comment]
@enigmen first screen CPU mining. KawPaw isnt supported on CPU.

**Comment by SChernykh** [comment]
@enigmen Check your config, or just copy your config from 6.1.0 folder.

**Comment by enigmen** [comment]
i copy config from 6.1.0 to 6.2.0
![изображение](https://user-images.githubusercontent.com/39157390/84356622-7fe02080-abd5-11ea-8cc2-9daefc4a7892.png)
![изображение](https://user-images.githubusercontent.com/39157390/84356661-91292d00-abd5-11ea-801c-3be61ffe2942.png)
but miner not see cuda device

**Comment by SChernykh** [comment]
CUDA 10.2 requires 440.33 or newer driver, CUDA 11 requires 450.36 - can you check it?

**Comment by enigmen** [comment]
thanks, my driver 431.86

**Comment by enigmen** [comment]
i update driver, miner work, but auto exit(

**Comment by SChernykh** [comment]
Did you compile the latest evo branch with the fix #1729 ? It won't work on your CPU without this fix.

**Comment by enigmen** [comment]
how to t'his used i no understend?

**Comment by SChernykh** [comment]
Just wait for the next release with the fix for your CPU.
