### ISSUE TITLE
COMPUTE ERROR CUDA

### ISSUE THREAD

**Issue by LiStopaD45** [xmrig/xmrig#1710]
Hello!
 I installed version xmrig 5.11.12, updated xmrig-cuda. I get a "COMPUTE ERROR." 
I had used version xmrig 5.11.6 before and I did not encounter such a mistake.
I use GPU: GTX 1050 TI and GTX 750 ti, CUDA 10.2, NVML 10.440.64.00. OS - Ubuntu 16.04
Algorithm - RandomX, for GPU - default setting.
I was doing a new installation of CUDA and xmrig, but the mistake didn 't go away. 
I ask for help.

**Comment by SChernykh** [comment]
Can you try older versions of xmrig-cuda and find the last one that works?

**Comment by LiStopaD45** [comment]
I 'll try to check it out. But it will take time. I 'm moving now and I won 't be able to check quickly. After the result - I will inform

**Comment by LiStopaD45** [comment]
I tried today with other versions of xmrig and xmrig-cuda. I was able to run the GPU with the following combination: xmrig 5.6.0 and xmrig-cuda 2.1.0.
