### ISSUE TITLE
Low hashrate with AMD FX 6350

### ISSUE THREAD

**Issue by Vivilatulipe** [xmrig/xmrig#1714]
Hi everybody,

I just tried XMRig yesterday, and i saw something unusual...
I used an Amd fx 6350 -6 Core and 8 Go RAM on XMRig 5.11.2 on W7 and it shows me:
![15914495504172682017118707771512](https://user-images.githubusercontent.com/26848402/83945164-2197f400-a809-11ea-8ce1-becce92aafb5.jpg)

Is that possible to have to have that max hashrate??

I did not put any spécial parameters on the configuration file, i used the xmrig config for cpu miner on web.

Thanks for help.

Vivilatulipe 

PS: Sorry for english

**Comment by downystreet** [comment]
I've noticed that on some AMD processors, when you start mining and the config.json file gets prefilled, it's not set at the optimal setting. Open your config.json file and go to "cpu": . Below this you will see the different algorithms listed out. Go to "rx": . I noticed on a 4 core AMD processor I was using it was prefilled with [-1,-1] which was not the optimal config. With your particular processor you will need to manually enter this into the file where the "rx" is "rx": [0, 1, 2, 3, 4, 5]. This is the setting for using all six cores of your processor. You can adjust accordingly by removing a number to use less cores.

**Comment by Vivilatulipe** [comment]
Thanks! That's working perfectly!

![15914612636282610577163013753772](https://user-images.githubusercontent.com/26848402/83949495-6bda9e80-a824-11ea-8726-c435f55ab48f.jpg)

With ram clock adjustments,  i think it will increase a lil bit more.
Thx.
