### ISSUE TITLE
_clock_gettime not available in OSX 10.11.x

### ISSUE THREAD

**Issue by atomize** [xmrig/xmrig#172]
Trying to run latest release xmrig-2.4.2 on OSX 10.11.6 I receive the runtime error:

dyld: Symbol not found: _clock_gettime
Expected in: /usr/lib/libSystem.B.dylib

Any fix for this?

**Comment by xmrig** [comment]
Please check version available via Homebrew http://www.brewformulas.org/Xmrig 2.4.1 at this moment.
Thank you.

**Comment by atomize** [comment]
Works! Thx <3!
