### ISSUE TITLE
compile error xmrig 5.11.2 dev 4.1

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig#1723]
i dont pass %73
![image](https://user-images.githubusercontent.com/31975916/84060064-3d93c500-a9c4-11ea-911b-8f26e364237d.png)

**Comment by xmrig** [comment]
Don't use path with spaces and special characters or remove this line https://github.com/xmrig/xmrig/blob/master/CMakeLists.txt#L135.
Thank you.

**Comment by snipeTR** [comment]
u'r rock

**Comment by snipeTR** [comment]
x86 compile complate but not run xmrig.exe 
no error. no log. no dry run. yes --help. yes "no config error". but not run command.
