### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by FurryOneLove** [xmrig/xmrig#1727]
I don’t know what to do!

![9F71899F-3F7F-4359-926E-7455007226AA](https://user-images.githubusercontent.com/35347245/84241680-7b016b00-ab08-11ea-98b2-30fec72964aa.jpeg)

**Comment by downystreet** [comment]
I'm not sure if you're joking or not but that CPU doesn't have the specs to mine with the randomX dataset.

**Comment by Spudz76** [comment]
Needs 2082MB free RAM to run RandomX.  You have 2048MB total and barely any free.
Maybe other algos can do better (cn=pico? can fit in cache) but still probably not powerful enough even though they sip watts - the hash per watt ratio is still bad.  Can not earn more than input power cost unless somehow very free power but even then very low payout.  CN-Pico based coins generally don't trade up for much real value compared to other coins.  The scratchpad should be able to fit in cache, and that CPU has 512KB of L1 and that is all (very not much room) and is missing most cool x64 features (cut speed in half a few times even though it's 1.6GHz).
