### ISSUE TITLE
message came the password was cracked

### ISSUE THREAD

**Issue by theshadowpeople** [xmrig/xmrig#1738]
Hello,
i use xmrig v6.2.0-beta and got the message that my password was cracked.

There was a transaction and my account is empty.

I use my own Linux-Pool-Server and some CPU with XMRIG. My Windows 10 with XMRIG close the programm and give me the massage .......

**Comment by snipeTR** [comment]
your own fault.
mnemonics seed, private key / spend key, you couldn't protect your information. Did you write your private key in miner or your own pool?
you couldn't protect your wallet.
please read. https://www.crypto-news-flash.com/monero-wallet-test-guide-review/

**Comment by theshadowpeople** [comment]
I also think it was my mistake.
The private key was not saved anywhere.
It was not an external attack but an internal one.
On this client was only xmrig and no password.
On this client I had a small window saying that the key was cracked. unfortunately i closed it because i didn't think there was an attack.
Is it possible that the password was hacked if i didn't use encryption internally like SSL/TLS?

**Comment by snipeTR** [comment]
Coins cannot be stolen without private key? if you are using local wallet. the situation is more complicated if you are using online wallet. There is no way to steal your coins related to xmrig. it may be related to the pool you have set up. Did you write your private key to pool? Is your private key registered in any file on pc?
