### ISSUE TITLE
is there anyway evade antivirus?

### ISSUE THREAD

**Issue by kalifan** [xmrig/xmrig#174]
I only download it binaries for windows and antivirus detect it like a trojan, how could i must bypass av? i dont want excluding in list, i mean trying another way. thanks great job.

**Comment by xmrig** [comment]
It happens to all miners, some people put it into botnets, etc. You can report the false positive happen, to your antivirus vendor.
Thank you.

**Comment by kalifan** [comment]
@xmrig have you got any guide to put into a botnet please.

**Comment by xmrig** [comment]
Botnets it law violation in all countries, I can't help you with it.
