### ISSUE TITLE
difference between versions?

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig#1740]
Will there be a revolutionary difference between version 6.2.X and version 5.11.X? According to what do you name the version? what will be the biggest difference.

**Comment by xmrig** [comment]
v6 includes GPU only KawPow algorithm, it is completely different from other algorithms including network protocol, so it major change, but config format is compatible.

* v6 can use v5 config.
* v5 can use v6 config but kawpow profiles will be silently ignored and not saved.

https://github.com/xmrig/xmrig/pull/1694#issuecomment-638310915
