### ISSUE TITLE
6.2.1 API cause segfault

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [xmrig/xmrig#1742]
at first connection to API using below command line
curl -s http://127.0.0.1:3333/1/summary
...the miner crash with segfault
without using API script....miner works fine.

running miner using this command:
./xmrig --opencl --cuda --no-cpu -o stratum.ravenminer.com:3838 -a kawpow -u xxxxxxxxxxx -p x --http-port=3333

using Ubuntu16

miner was compiled using those options:
cd cmake && cmake .. -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 && make

all prev versions was compiled and running in same way without this issue

**Comment by xmrig** [comment]
Fixed, v6.2.2 will be released soon.
Thank you.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v6.2.2
