### ISSUE TITLE
Release v6.2.2, x86 version

### ISSUE THREAD

**Issue by lyayusheva** [xmrig/xmrig#1747]
The release description says that the 32-bit version has been fixed. But there is no x86 version in the release list. It's just that not everyone has compilers and not everyone knows how to compile. Could you, with the other releases, also do 32 bit? I don’t think it will take much of your time. Thank you in advance.

**Comment by xmrig** [comment]
32 bit version is useless for mining especially for RandomX algorithms and we no longer provide downloads for it on github to avoid confusing.
You can still download it https://download.xmrig.com/xmrig/6.2.2/16863763d3d3796cfef5ac06013e26244627145b/xmrig-6.2.2-gcc-win32.zip username `xmrig` password `download`, every commit has binaries created by buildbot https://buildbot.xmrig.com/
Thank you.
