### ISSUE TITLE
Run on WindowsXp error , I build to 32bit 

### ISSUE THREAD

**Issue by worawutboy** [xmrig/xmrig#175]
Error "The procedure entry point_time32 could not be located in the dynamic link library msvcrt.dll", But download  from Release gcc-win32 V2.4.0
https://github.com/xmrig/xmrig/releases/download/v2.4.0/xmrig-2.4.0-gcc-win32.zip
not error.
help me please.

**Comment by xmrig** [comment]
Looks like some MSYS2 related bug, I updated my MSYS2 installation and now get exactly same error as you.
Thank you.
