### ISSUE TITLE
Best Share Stats

### ISSUE THREAD

**Issue by NCarter84** [xmrig/xmrig#1756]
Can we get some data on best shares? For us who solo mine coins? :)

**Comment by NCarter84** [comment]
XMR-Stak provides this data and would like to continue to use XMRig.

**Comment by xmrig** [comment]
This data is available only via HTTP API by `GET /1/summary` or `GET /2/summary`, if you are looking for an equivalent of `r` console command, this feature is missing, I will add it to the next release.
Thank you.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v6.2.3
