### ISSUE TITLE
anonymously performance database

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig#1757]
On a page named bencmark.xmrig.com, there must be a property that can be opened by setting from the config file. CPU type and hashrate and version and library information must be collected anonymously at bencmark.xmrig.com. it works and can be a nice pile of data. in this way, we can track the impact of the changes we have made at miner on total performance.

**Comment by xmrig** [comment]
https://xmrig.com/benchmark but it works as dedicated benchmark mode so user explicitly accept sharing.
