### ISSUE TITLE
Remove xmrig icon

### ISSUE THREAD

**Issue by ichunichu** [xmrig/xmrig#1758]
hello ! I need to remove the xmrig icon . I download "ressournce hacker" and delete the icon folder. the .exe file as no icon but when i run xmrig , the icon is here in my task manager. can you help me to remove xmrig icon ?
![image](https://user-images.githubusercontent.com/67644676/86138165-648a7600-baee-11ea-82d0-6c7bcdba6115.png)

**Comment by snipeTR** [comment]
dont delete. just clange

**Comment by kerinlive** [comment]
Icon and other meta data succesful change in resource hacker. If you want to hide xmrig from taskmanager you may get any system executable file such as explorer.exe, export all resources data from it as *.res file, and next you need to import res file to xmrig.exe. make sure that you select all need resources to change. And check the Overwrite point on popup window when you make selection of resources that you want to import. Resources hacker success do this changes all time with xmrig. Process Name that shows in taskmgr, software vendor, licensing data, and other data of process can be changed in manifest tab in reshack. Try.

**Comment by kerinlive** [comment]
And dont use *.rc resource file. It may not import res data correctly. Only .*res files
