### ISSUE TITLE
msys64 build error.

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig#1764]
mkdir build
cd build
cmake .. -G "Unix Makefiles" -DXMRIG_DEPS=c:/xmrig-deps/gcc/x86
make
i dont change source code.

![image](https://user-images.githubusercontent.com/31975916/86514500-56549680-be1b-11ea-9d8e-5f59973e8733.png)
![image](https://user-images.githubusercontent.com/31975916/86514747-949e8580-be1c-11ea-97ae-8007087a7a9f.png)
![image](https://user-images.githubusercontent.com/31975916/86514780-f363ff00-be1c-11ea-91a3-c49fedcfca49.png)
![image](https://user-images.githubusercontent.com/31975916/86514788-01198480-be1d-11ea-9032-4539ecabcc12.png)

**Comment by xmrig** [comment]
If you try build 64 bit version, remove all generated cmake files and use `-DXMRIG_DEPS=c:/xmrig-deps/gcc/x64`

Otherwise use `mingw32.exe` shell instead of `mingw64.exe`.
Thank you.

**Comment by snipeTR** [comment]
ohhh shit!! again u'r rock
