### ISSUE TITLE
Support for Intel Xeon Phi x100?

### ISSUE THREAD

**Issue by siyy123** [xmrig/xmrig#1765]
Does xmrig support mining randomx on a Xeon Phi x100? Since Intel Xeon Phi x100 (Knights Corner) include x86 ISA, 4-way SMT per core, 512-bit SIMD units and IMCI instruction set, It may be possible to mine randomx algorithm.

**Comment by Unnameless** [comment]
Genuinely curious about this too, although I wouldn’t hold my breath

**Comment by mobrine-mob** [comment]
I think all modern cpus (2012-onward) can mine Randomx, although the hr will be lower for older cpus

**Comment by Unnameless** [comment]
@mobrine-mob I think the phi is more than an old cpu
