### ISSUE TITLE
Kowpow issue...

### ISSUE THREAD

**Issue by needhelp101** [xmrig/xmrig#1767]
Hi, 

So trying to test out some Kowpow mining and keep getting hit with this error..

 * ASSEMBLY     auto:intel
 * POOL #1      solo-rvn.2miners.com:7070 algo kawpow
 * COMMANDS     hashrate, pause, resume
 * OPENCL       disabled (failed to load OpenCL runtime)
 * CUDA         disabled
[2020-07-08 19:12:00.950]  net      use pool solo-rvn.2miners.com:7070  51.89.96.116
[2020-07-08 19:12:00.951] [solo-rvn.2miners.com:7070] incompatible/disabled algorithm "kawpow" detected, reconnect
[2020-07-08 19:12:00.951]  net      no active pools, stop mining

using xmrig 6.2.2

Any help would be great... thanks

**Comment by snipeTR** [comment]
try this config.json
{
    "autosave": true,
    "donate-level": 1,
    "cpu": true,
    "opencl": false,
    "cuda": false,
    "pools": [
        {
            "coin": "raven",
            "algo": "kawpow",
            "url": "solo-rvn.2miners.com:7070",
            "user": "your wallet adress",
            "pass": "x",
            "tls": false,
            "keepalive": true,
            "nicehash": false
        }
    ]
}

**Comment by needhelp101** [comment]
same problem, am confused as hell other miners work just fine and seems to be xmrig on its own having an issue

**Comment by Spudz76** [comment]
I thought kawpow/rvn is GPU only in general.  It is GPU only with xmrig at least...

**Comment by STSMiner** [comment]
> 
> 
> I thought kawpow/rvn is GPU only in general. It is GPU only with xmrig at least...
> #1694

The issue is with AMD cards, the app fails to load the OpenCL part.

**Comment by snipeTR** [comment]
![image](https://user-images.githubusercontent.com/31975916/87002074-86a48800-c1c1-11ea-81e9-2ca3239bc670.png)

**Comment by needhelp101** [comment]
I can clearly see that, but works perfectly fine on all other miners.. and only seems to have an issue with XMRig

**Comment by needhelp101** [comment]
so why is it failing, when on all the others it opens fine and runs... recompiled, updated, added, reinstalled a million times by now & still same issue only with XMRig

**Comment by snipeTR** [comment]
https://github.com/xmrig/xmrig-cuda

**Comment by needhelp101** [comment]
i got amd cards... why would i be using cuda ???

**Comment by xmrig** [comment]
This error means the miner failed to load **OpenCL.dll** (Windows) or **libOpenCL.so** (Linux) try find it in your system, make sure `"loader"` in `"opencl"` object set to `null`.
Thank you.

**Comment by needhelp101** [comment]
heh, perfect thank you for the help xD
