### ISSUE TITLE
Bestshare

### ISSUE THREAD

**Issue by needhelp101** [xmrig/xmrig#1769]
Hi,

Bit confused in the bestshare display for kawpow... so for example while mining Raven i get 

- TOP 10
  # | DIFFICULTY | EFFORT % |
  1 |       140G |    27.60 |
  2 |     18700M |   206.71 |
  3 |     10392M |   371.96 |
  4 |      9487M |   407.44 |
  5 |      6181M |   625.39 |
  6 |      5656M |   683.37 |
  7 |      5598M |   690.50 |
  8 |      4774M |   809.58 |
  9 |      4502M |   858.47 |

now what size would my bestshare need to be in order to secure a block ???

**Comment by needhelp101** [comment]
the display system of the bestshare is bit confusing

**Comment by xmrig** [comment]
Seems need to add a special case for Raven, unlike all other coins it does not use absolute difficulty.
Thank you.
