### ISSUE TITLE
Performance Degradation on Kawpow With Latest Release - GTX 1080

### ISSUE THREAD

**Issue by breadsax** [xmrig/xmrig#1773]
I first noticed this building from source on Windows with Visual Studio 2019 and Cuda 11 latest release. I then ran the binary from the latest xmrig release with the latest cuda extension release and confirmed it wasn't just my compilation.

Performance went from 17 MH/S to 13 MH/S.

These cards are not great mining cards, but I am at a loss as to why this is happening. Cards on another rig had very nice increases when I compiled from source with the software above.

Any thoughts?

**Comment by SChernykh** [comment]
@breadsax Can you try setting `"threads" : 128` for KawPow in config.json? This is the only major thing that changed with the latest release (increased from 128 to 256).

**Comment by breadsax** [comment]
Hello @SChernykh and thank you for your response.

I did some more testing today and found that using the CUDA 10_2 .dll files from the extension worked to get the hashrate back up. I was using those before on the previous version. For some reason, GTX 1080 does not perform as well with the CUDA 11 .dll files.

I am using the latest Nvidia driver 451.67. 

Any ideas why?
