### ISSUE TITLE
API with per GPU not per thread results

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [xmrig/xmrig#1778]
Hi, we are using this command line for fetching results
curl -s http://127.0.0.1:3333/1/summary
but see there is only per threads results with hashrates, nor per GPU.
Sometimes there are more threads than GPUs in rig and from this info we dont know which treads is to which GPU cards.

Could you help us or add another array in results with per gpu results or threads to GPUs relations?

Thanks

**Comment by xmrig** [comment]
You can use http://127.0.0.1:3333/2/backends for it.

For OpenCL where possible multiple threads per GPU you must combine results on your side to view summary per GPU, example how it looks like http://workers.xmrig.info/
Thank you.

**Comment by tymoteuszrogalewski** [comment]
Thank you very much. The "backends" is good information and now our script is working good ;-)
