### ISSUE TITLE
Feature request: miner should stop in battery mode

### ISSUE THREAD

**Issue by Lonnegan** [xmrig/xmrig#1781]
Hi,

there is a feature I've appreciated in the distributed computing scene (BOINC, F@H) for years: you can set up the software to stop if the system is in battery mode. So you can compute in the background with a notebook and don't have to care when you unplug it, because the software stops calculating then. Same on servers with UPS. If the power fails and the system runs on battery, the software pauses to not suck the UPS empty within seconds under full load.

That's a feature I'd like to have in xmrig, too; for the same reasons :)

**Comment by ffleur** [comment]
This is something you can easily do yourself on linux, you can write a script to periodically check the content of /sys/class/power_supply/BAT0/status (or BAT1 if you have an internal battery) and stop xmrig if it says "Discharging"

**Comment by Lonnegan** [comment]
Well, most of my systems are Windows systems, so it would be a nice feature to have :)

**Comment by xmrig** [comment]
Next version will support boolean option `pause-on-battery`, code already in dev branch.
Thank you.

**Comment by Lonnegan** [comment]
Great, THX! 👍

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v6.3.1

**Comment by Lonnegan** [comment]
Tested and works great on a UPS supported server system. 👍
