### ISSUE TITLE
xmrig vs Ryzen 3600

### ISSUE THREAD

**Issue by andrexTI** [xmrig/xmrig#1782]
Hello everyone, my xmrig is stuck on this screen. What can I do to make it work?

![error](https://user-images.githubusercontent.com/60714578/87823386-95d2a800-c849-11ea-96cc-a43536c19559.png)

**Comment by Lonnegan** [comment]
Hi,

I see you are using xmrig compiled with gcc. Have you counter-tested with xmrig in the MS version?

**Comment by andrexTI** [comment]
Yes, I tested both. I think I found the solution, disable "opcache" in BIOS. So far it's working. It seems that this is a problem for the ryzens.

look this https://github.com/xmrig/xmrig/issues/1384

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/randomx-stability-troubleshooting-guide
