### ISSUE TITLE
xmrig x64 on W2K3

### ISSUE THREAD

**Issue by escal3x** [xmrig/xmrig#1785]
I try run x64 xmrig (gcc) on W2K3 and got this error:
"Entry point ... ConvertInterfaceIndexToLuid ... DLL IPHLPAPI.DLL"
Why?
x86 version (gcc)  ( xmrig 6,2,2 and older) runs without problems.

**Comment by snipeTR** [comment]
https://support.microsoft.com/en-in/help/823256
