### ISSUE TITLE
Worker in config.json

### ISSUE THREAD

**Issue by gboelter** [xmrig/xmrig#179]
Is there a way to add the worker to my address using the environment variable from Windows or Linux in config.json? Something like 

"user": "48edfHu7V9Z84YzzMa6fUueoELZ9ZRXq9VetWzYGzKt52XU5xvqgzYnDK9URnRoJMk1j8nLwEVsaSWJ4fhdUyZijBGUicoD.%computername%",

**Comment by xmrig** [comment]
You can use command line options for environment variables, it can be used with or instead of config file.

Actually it not hard to add support for it on Windows, there has `ExpandEnvironmentStrings` function, on Linux need write some custom code with regex or something like that.
Thank you.

**Comment by NmxMilk** [comment]
What would be nice is to have a new option --user-extension that when specified would be concatenated to the user.
This will allow to run on several machines, using a shared config file,  with a simple command like
$ xmrig -c config.json --user-extension `hostname`

This would be usefull for people running xmrig on different similar machines.

**Comment by xmrig** [comment]
How to specify worker id depends of pool, for some pools it simple added to wallet address, for others it should specified in password. Also some pools don't support worker id at all.
Thank you.

**Comment by gboelter** [comment]
Ok, what about a config.txt instead where I can add some placeholders like '.%computername%' or '$hostname'?
This file could be easily converted by xmrig to a valid config.json file during startup using my placeholders?

**Comment by djdomi** [comment]
Hi

To be easy:

- Windows uses: %hostname%
-Linux useses: $HOSTNAME (UPPERCASE!) or `hostname` with the > ` < which will execute hostname command and return entry

**Comment by xmrig** [comment]
Implemented in dev branch, docs https://xmrig.com/docs/miner/environment-variables
Thank you.
