### ISSUE TITLE
Feature-request: show difficulty for the found share (logging)

### ISSUE THREAD

**Issue by YetAnotherRussian** [xmrig/xmrig#18]
Hi, this is very easy to implement. Useful for low-user-count pools, unable to find current difficulty in cli log which has already been cut from top.

E.g. "SHARE FOUND, diff: 12345"

**Comment by xmrig** [comment]
I will add more detailed output for found shares, current text something like stub.

**Comment by xmrig** [comment]
http://i.imgur.com/EP5lC3a.png add count for accepted/rejected shares, diff and network latency.
