### ISSUE TITLE
Setting hash limit!

### ISSUE THREAD

**Issue by hayzamjs** [xmrig/xmrig#180]
Title has it all, is there any way I could set a hash limit, my servers could provide upto 300h/s but I want them to give me no more than 135h/s. I've tried -t and --max-cpu arguments both are either going wayyy up or wayy down. If there is any way please do tell me, thank you!

**Comment by 2010phenix** [comment]
yes, -t do this for you if add to config...
no any other magic things

**Comment by hayzamjs** [comment]
Oh okay, thanks!
