### ISSUE TITLE
Random "Aborted" / "Segmentation Fault" / "Bus error" messages and miner stops

### ISSUE THREAD

**Issue by codedracula4ec** [xmrig/xmrig#1803]
I'm getting these messages after mining for some time
![image](https://user-images.githubusercontent.com/62944284/89680372-335d4c80-d8c9-11ea-83b7-ea8518824816.png)
![image](https://user-images.githubusercontent.com/62944284/89680421-496b0d00-d8c9-11ea-898d-f02c5bc84d27.png)
![image](https://user-images.githubusercontent.com/62944284/89681038-8552a200-d8ca-11ea-903e-81e4f269b9e5.png)

I'm mining on cpu only. My PC:
- ryzen 5 1600 stock clocks
- 24gb 2666mhz ram
- ubuntu 20.04

I built xmrig from source. First I thought it could be debugging stuff happening, so i compiled with the `-DCMAKE_BUILD_TYPE=Release` tag, but no luck here.

Miner startup screen:
![image](https://user-images.githubusercontent.com/62944284/89680808-16754900-d8ca-11ea-86d9-c454fecdb2c0.png)

**Comment by Lonnegan** [comment]
There are two versions of the Ryzen 5 1600. The original Ryzen 5 1600 "Summit Ridge", introduced in mid 2017, and the new Ryzen 5 1600 "Pinnacle Ridge", introduced only in late 2019 as a cheaper version of the Ryzen 5 2600. Which one is yours?

The very eary version of the Summit Ridge had problems with segment faults. It was so heavy, that AMD offered to replace this devices :o
https://www.extremetech.com/computing/254750-amd-replaces-ryzen-cpus-users-affected-rare-linux-bug

Perhaps your system is affected by this?

**Comment by codedracula4ec** [comment]
Thanks Lonnegan, I'm going to investigate that. I have the first gen ryzen 5 1600, not the AF

**Comment by SChernykh** [comment]
@codedracula4ec You could try to disable Opcache in BIOS. First gen Ryzens have this problem sometimes.

**Comment by codedracula4ec** [comment]
@SChernykh I didn't find that option in my b350 tomahawk arctic bios.
@Lonnegan my ryzen is one of the latest 1st gen ryzen lot, so it might be some other problem

**Comment by codedracula4ec** [comment]
Fixed! Thank you guys @SChernykh  @Lonnegan 
I built xmrig with opcache disabled and now it's working for 1 hour long in full speed without any crashes
