### ISSUE TITLE
"FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW" on start.

### ISSUE THREAD

**Issue by kyngs** [xmrig/xmrig#1805]
For some reason on the start, the miner is unable to apply MSR mod.
![log](https://user-images.githubusercontent.com/38181667/89727887-f4460d00-da28-11ea-8bfc-138e6c3a53ba.png)
Config: https://drive.google.com/file/d/1kQAHj8xCeZ_rW7wSJ84_7BlQtWoMDFmZ/view?usp=sharing

**Comment by SChernykh** [comment]
Do you run xmrig as root?

**Comment by kyngs** [comment]
> Do you run xmrig as root?

Of course I do.

**Comment by SChernykh** [comment]
MSR mod doesn't work in a VM. I've just noticed that you have `4C/4T` at startup whereas EPYC 7282 is 16C/32T CPU.

**Comment by kyngs** [comment]
> MSR mod doesn't work in a VM. I've just noticed that you have `4C/4T` at startup whereas EPYC 7282 is 16C/32T CPU.

So am I doomed?

**Comment by SChernykh** [comment]
You can still mine, but not at max speed. VMs restrict access to MSR registers because they can be used for getting full access to the physical machine, so you can't do anything here.

**Comment by kyngs** [comment]
I guess I will search for a new algorithm. Because those mining speeds are poor.
