### ISSUE TITLE
Best configuration for 4x cpu, E7-4850

### ISSUE THREAD

**Issue by xtrojan1** [xmrig/xmrig#181]
Hi,

I do not know what and the best configuration for E7-4850., i have 4 cpu(Processor) in the server.
Performance
of Cores 10,     10 x 4cpu =40 core
of Threads 20,     20 x 4cpu = 80 threads
Processor Base Frequency 2.00 GHz
Max Turbo Frequency 2.40 GHz
Cache 24 MB SmartCache
I do not know how to compute the (cpu inffinty) for my 4x, E7-4850.

I also think that if I put too many hearts sela works less well.

Is there a best practice for windows OS servers 2012R2?

do you have an answer or a link to my questions.

thank you in advance

**Comment by NmxMilk** [comment]
the bottleneck being cache size (2M = 1 thread), you should go for 12 threads per CPU.
CPU affinity is a bitwise mask for your logical cores:
1 cpu = 20 threads = 20 bit mask
mask = 1111 1111 1111 1111 1111
use   = 1010 1010 10 10 1010 1010   =  use 10 out of the twenty
hexa affinity = 0xAAAAA

For a double socket this will be 0xAAAAAAAAAA
and for a quad socket : 0xAAAAAAAAAAAAAAAAAAAA

**Comment by xtrojan1** [comment]
thanks a lot, i will try it..

**Comment by angel12** [comment]
I have 4x e7 4860, and currently I can only get about 40% - 50% cpu usage, even when max cpu set at 100. I also see this in my xmrig window:

CPU: Intel(R) Xeon(R) CPU E7- 4860 @ 2.27GHz (2) x64 AES-NI

Does this mean it is only using (2) of the 4 CPU's?

**Comment by NmxMilk** [comment]
You should have a look at the NUMA issue #86.
Maybe your case too.

**Comment by xtrojan1** [comment]
start /node 0 xmrig.exe --threads=11
start /node 1 xmrig.exe --threads=11
start /node 2 xmrig.exe --threads=11
start /node 3 xmrig.exe --threads=11

for all i have 1.360 h/s
https://drive.google.com/file/d/0B4yy8QDExEZ1anNxQVlvRjBIeTQ/view

but i do not use cpu affinity,

how to add cpu affinity on my configure?
do you have an answer or a link to my questions.

thank you in advance

**Comment by xmrig** [comment]
If this issue still actual, please check v2.99.2-beta release #1077.
Thank you.
