### ISSUE TITLE
Add build instructions for Alpine Linux

### ISSUE THREAD

**Issue by samedamci** [xmrig/xmrig#1810]
# Alpine Linux
Disclaimer: You need to enable testing repository to download some dependencies.
+ Install build dependencies.
```
# apk add git cmake libuv-dev libstdc++ openssl-dev gcc g++ hwloc-dev make
```
+ Clone repo.
```
$ git clone https://github.com/xmrig/xmrig 
$ mkdir xmrig/build && cd xmrig/build
```
## Dynamic linked
+ Build XMRig.
```
$ cmake ..
$ make -j$(nproc)
```
## Static linked
+ Install additional build dependencies.
```
# apk add bzip2 automake libtool autoconf linux-headers
```
+ Build dependencies.
```
$ cd ../scripts && ./build_deps.sh
```
+ Build XMRig.
```
$ cd ../build && cmake .. -DXMRIG_DEPS=scripts/deps
$ make -j$(nproc)
```

**Comment by samedamci** [comment]
Disclaimer: You need to enable testing repository to download some dependencies.

**Comment by xmrig** [comment]
Would be nice if you add commands to enable testing repository too or maybe a better way is use `scripts/build.hwloc.sh` I'm not sure.

For static build there is also a useful cmake option `-DBUILD_STATIC=ON` to create a fully static executable, thanks to musl it should work without side effects.
Thank you.

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/build/alpine
