### ISSUE TITLE
Why no more "notls" builds?

### ISSUE THREAD

**Issue by Cyber-Criminal** [xmrig/xmrig#1824]
Hi
i like xmrig, it's opensource, standalone, portable, low size, have compiled releases, good hashrate, etc.
and i always using notls file for reasons
idk why you don't compile notls builds anymore
if there is a problem that made you do this, it's OK
but if you are able to compile notls builds, do this please
thank you

**Comment by xmrig** [comment]
If notls builds will be available only as separate downloads on https://download.xmrig.com/xmrig/ user `xmrig` password `download` is it OK for you? also you don't mention the OS I guess it's Windows?
Thank you.

**Comment by Cyber-Criminal** [comment]
Yes, i meant Windows, and It's OK
😘

**Comment by Cyber-Criminal** [comment]
idk i have to Close this issue or not :|
do it yourself ☹️❤️

**Comment by xmrig** [comment]
https://download.xmrig.com/xmrig/6.3.3/ba336122c0cae2345e568cba63c2ca691301b8f0/xmrig-6.3.3-notls-gcc-win64.zip
https://download.xmrig.com/xmrig/6.3.3/ba336122c0cae2345e568cba63c2ca691301b8f0/xmrig-6.3.3-notls-msvc-win64.zip

**Comment by DeadManWalkingTO** [comment]
You can always compile "notls" builds with `-DWITH_TLS=OFF` disable SSL/TLS support (secure connections to pool). This feature add external dependency to OpenSSL.

**Comment by Cyber-Criminal** [comment]
@xmrig would you please add "gcc win64 notls"?

**Comment by xmrig** [comment]
@Cyber-Criminal They is still in the same place for every commit https://download.xmrig.com/xmrig/6.12.2/80ae339343f6004ae105e27c71180c0220c939b8 (password mentioned above) just not in github releases.
Thank you.

**Comment by Cyber-Criminal** [comment]
sorry, i asked because i looked at another folder and it was not there
but it is there in the folder that you linked
thank you
