### ISSUE TITLE
6.3.3 low hashrate i7-4770

### ISSUE THREAD

**Issue by jututt** [xmrig/xmrig#1837]
On latest 6.3.3 I'm getting around 1250 H/s with cpu frequency locked at 2500 MHz.
With 6.3.1 I was getting around 1700 H/s at the same 2500 Mhz frequency.
BTW I'm also around 3° C down on temperature CPU Core / Package.
![1](https://user-images.githubusercontent.com/29811680/93321386-62dd6e00-f812-11ea-926e-9d6f07b8b773.png)

**Comment by SChernykh** [comment]
`huge pages 0% 0/1168` is the reason. Try starting xmrig right after reboot.

**Comment by jututt** [comment]
Thank you, a simple reboot solved my issue
