### ISSUE TITLE
CPU not mining on xmrig

### ISSUE THREAD

**Issue by OMGitsMohaYT** [xmrig/xmrig#1848]
It was working fine yesterday but today, I can't mine with it as it shows 0 hashrate and I even used the latest version which is 6.3.4, and I waited 60 seconds but didn't work, my cpu is i5 2410M

**Comment by xmrig** [comment]
Please show miner log.
Thank you.

**Comment by DeadManWalkingTO** [comment]
Please give more details about that.
Thank you!
