### ISSUE TITLE
Invalid Shares

### ISSUE THREAD

**Issue by andrexTI** [xmrig/xmrig#1851]
34.511 / 6
Valid / Invalid Shares

Hello everyone, is it bad that I have these Invalid Shares?

Version 6.3.3

Thanks  =D

**Comment by xmrig** [comment]
Invalid shares can happen for various reasons in the whole mining chain including your pool, a small amount of these shares is not an error, since you do not provide any other details this is a common answer to common question.
Thank you.

**Comment by DeadManWalkingTO** [comment]
If you want give more details about that.
```
My stats:
Accepted Shares
55.608.014.215
Expired Shares
249.186.746
Invalid Shares
51.229.348
```
Like @xmrig  says `Invalid shares can happen for various reasons`
