### ISSUE TITLE
Is TLS 1.3 support by XMRig miner?

### ISSUE THREAD

**Issue by BKdilse** [xmrig/xmrig#1855]
Just a question, I see XMRig using TLS 1.2.  Is TLS 1.3 supported or will it be at some point?

**Comment by xmrig** [comment]
It already supported with 2 conditions:
1. Miner built with OpenSSL 1.1.1.
2. Pool support, for example https://minexmr.com/.

**Comment by BKdilse** [comment]
Thanks, I've confirmed TLS 1.3 is working with minxmr, but not with my pool.  Would you know if there is additional configuration required on the pool side?  The pool website and certificate show TLS 1.3 is enabled.

**Comment by xmrig** [comment]
I guess this article contains all answers https://developer.ibm.com/blogs/migrating-to-tls13-in-nodejs/
Thank you.

**Comment by BKdilse** [comment]
Yeah, just saw that, it looks like my old Node version may not support it.  Thanks for your help, I'll do some testing.
