### ISSUE TITLE
xmrig through proxy

### ISSUE THREAD

**Issue by RiderA7** [xmrig/xmrig#186]
Hi. Can you tell me what should I do to make xmrig working through proxy?
Here is the situation: My main computer is sit behind corporate proxy and has Win10 onboard and Proxifier to connect ANY application through corporative proxy. There is installed some proxy-server for receiving requests from other computer (witn Linux Mint18.2 onboard).
I configured main settings on it to connect through main machine (so browsers, apt, synaptic works fine with internet). But xmrig always tells me "[pool] DNS error: temporary failure". I think it can't work through my improvized tunnel?
I can't find any settings for work with proxy in xmrig. Does it able to work with proxy?
May be exist some things like proxifier for linux?
(Sorry for my bad english)

**Comment by RiderA7** [comment]
Now I using xmrig-proxy to mine on some monero pool but not on nicehash.

**Comment by ght3d** [comment]
A http or socks4/5 proxy feature like in cpuminer-opt would be really great. Xmrig would've worked on nicehash and would've mined other coins properly. As for now, using xmrig with xmrig proxy doesnt work when mining other cryptonight coins like bytecoin and electroneum. Also an internal http proxy feature would allow users to overcome problems like firewalls (in case there's a separate gateway with internet and outside the firewall in the same network). 

Dev, please consider adding and http or socks proxy feature into xmrig, it would make xmrig the best miner of all (xmrig speed is much more superior to other mining software).

**Comment by dagmoller** [comment]
I agree, socks proxy would be great...

**Comment by xmrig** [comment]
I agree, but it need more complicated, all cpuminer-* use libcurl and this lib has proxy support out of box, just need wrap it, but libuv not support proxy, it need be implemented by self (or maybe someone else already did it).
Thank you.

**Comment by yongmuh** [comment]
Please let me know if you find a way to make it work through a proxy server. Just wonder any third party program can help the job.

**Comment by dreamlant** [comment]
please add xmrig through proxy

**Comment by enwillyado** [comment]
I have implemented afunction to allow _parent proxy_ (Outbound over "CONNECT" command of HTTP) in the "xmrig-proxy" project. It works! Would someone be interested to see it?

**Comment by 2010phenix** [comment]
enwillyado, yes Thx.

**Comment by enwillyado** [comment]
@2010phenix See the poll request. @xmrig, this funtionality is already contained in the roadmap https://github.com/xmrig/xmrig/issues/106.

**Comment by direngley** [comment]
plz. update HTTP/SOCKS proxy support #186

**Comment by moralrebuild** [comment]
When can we have this funtionality?

**Comment by enwillyado** [comment]
@moralrebuild @direngley You can use my last fork version: https://github.com/enwillyado/xmrig/releases
