### ISSUE TITLE
What does --nicehash do ?

### ISSUE THREAD

**Issue by leovarmak** [xmrig/xmrig#187]
Hey,

What does --nicehash do ? I mean one can mine even on nicehash servers without using --nicehash right ? So what exactly does it do ?
A detailed explanation would be much appreciated.

**Comment by xmrig** [comment]
Check this issue https://github.com/xmrig/xmrig-proxy/issues/24

**Comment by dwright1542** [comment]
How to specify even and odd NUMA nodes in Linux to xmirg? It's easy when it's 0-11 and 12-23. These are 0,2,4,6,8,10,12,14,16,18,20,22 and 1,3,5,7,9,11,13,15,17,19,21,23... Opteron 6238 CPU's.
