### ISSUE TITLE
xmr.nanopool.org and xmrig

### ISSUE THREAD

**Issue by mastermks** [xmrig/xmrig#188]
Hi,

Can i use xmrig with xmr.nanopool.org.
i have a lot of disconnect with xmr.nanopool.org and with all my workers.

![image](https://user-images.githubusercontent.com/32941246/32419406-a0006426-c279-11e7-8d97-d9a13cac768b.png)

there is a sepecial configuration?

**Comment by xmrig** [comment]
What you hashrate? nanopool use high diff 120000, it can cause timeouts.
Thank you.
