### ISSUE TITLE
cannot set MSR 0x000001a4 to 0x0000000f

### ISSUE THREAD

**Issue by dangfuyidabai** [xmrig/xmrig#1891]
When I ran the command, xmrig starts mining. But I am receiving that message with yellow line.

cannot set MSR 0x000001a4 to 0x0000000f

MSR Tools has been automatically installed.  I put in all necessary wrmrs combinations for  CPU from randomx_boost.

**Comment by dangfuyidabai** [comment]
![20201013191535](https://user-images.githubusercontent.com/52128945/95853768-8a2f4880-0d88-11eb-8396-cc4472cf0056.jpg)

**Comment by dangfuyidabai** [comment]
![20201013191901](https://user-images.githubusercontent.com/52128945/95854084-088bea80-0d89-11eb-8ef5-c6775b101267.jpg)

**Comment by dangfuyidabai** [comment]
![20201013192309](https://user-images.githubusercontent.com/52128945/95854469-9667d580-0d89-11eb-9cf1-2bc400c4431a.jpg)

**Comment by Saikatsaha1996** [comment]
Run xmrig 6.3.5 exe..
Don't start run application

**Comment by Saikatsaha1996** [comment]
> When I ran the command, xmrig starts mining. But I am receiving that message with yellow line.
> 
> cannot set MSR 0x000001a4 to 0x0000000f
> 
> 
> MSR Tools has been automatically installed.  I put in all necessary wrmrs combinations for  CPU from randomx_boost.

Don't start run command
Just start xmrig .exe

**Comment by dangfuyidabai** [comment]
> > When I ran the command, xmrig starts mining. But I am receiving that message with yellow line.
> > cannot set MSR 0x000001a4 to 0x0000000f
> > MSR Tools has been automatically installed.  I put in all necessary wrmrs combinations for  CPU from randomx_boost.
> 
> Don't start run command
> Just start xmrig .exe

Under linux system

**Comment by Saikatsaha1996** [comment]
> > > When I ran the command, xmrig starts mining. But I am receiving that message with yellow line.
> > > cannot set MSR 0x000001a4 to 0x0000000f
> > > MSR Tools has been automatically installed.  I put in all necessary wrmrs combinations for  CPU from randomx_boost.
> > 
> > Don't start run command
> > Just start xmrig .exe
> 
> Under linux system

Give me all files screen shot..

**Comment by mesche** [comment]
Unfortunately I get the same error with Version v6.4.0 on Intel Xeon

Result of `cat /proc/cpuinfo | grep "Intel"`

> vendor_id	: GenuineIntel
> model name	: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
> ...

**Comment by SChernykh** [comment]
MSR requires root/administrator privileges. Run as `sudo ./xmrig`

**Comment by mesche** [comment]
@SChernykh yes! But this is not the cause of the problem, because XMRig runs as root.

Result of `sudo wrmsr -a 0x1a4 0xf`
> wrmsr: CPU 0 cannot set MSR 0x000001a4 to 0x000000000000000f

The simple shell-script  "randomx_boost.sh" does not work for me.

**Comment by SChernykh** [comment]
@mesche It also must be a dedicated server, not a VM. MSR mod works only on the real hardware.

**Comment by ShineSmile** [comment]
Same issue on my laptop
```
➜  ~ cat /proc/cpuinfo | grep "Intel"
vendor_id	: GenuineIntel
model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
vendor_id	: GenuineIntel
model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
vendor_id	: GenuineIntel
model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
vendor_id	: GenuineIntel
model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
vendor_id	: GenuineIntel
model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
vendor_id	: GenuineIntel
model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
vendor_id	: GenuineIntel
model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
vendor_id	: GenuineIntel
model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
```

**Comment by ShineSmile** [comment]
> Same issue on my laptop
> 
> ```
> ➜  ~ cat /proc/cpuinfo | grep "Intel"
> vendor_id	: GenuineIntel
> model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
> vendor_id	: GenuineIntel
> model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
> vendor_id	: GenuineIntel
> model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
> vendor_id	: GenuineIntel
> model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
> vendor_id	: GenuineIntel
> model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
> vendor_id	: GenuineIntel
> model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
> vendor_id	: GenuineIntel
> model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
> vendor_id	: GenuineIntel
> model name	: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
> ➜  ~ uname -a
> Linux ss-uptop 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> with root privileges
> 
> ```
> [2020-11-11 14:56:56.415]  msr      cannot set MSR 0x000001a4 to 0x0000000f
> [2020-11-11 14:56:56.415]  msr      FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW
> ```

I solved it by disabling Security Boot in BIOS.
https://xmrig.com/docs/miner/randomx-optimization-guide/msr
https://stackoverflow.com/questions/44362796/wrmsr-operation-not-permitted-exception

**Comment by dnandz** [comment]
i am using ubuntu 18.04
in config.json
`"randomx": {
        "init": -1,
        "init-avx2": -1,
        "mode": "auto",
        "1gb-pages": true,
        "rdmsr": true,
        "wrmsr": "-a 0x1a4 0xf",
        "cache_qos": false,
        "numa": true,
        "scratchpad_prefetch_mode": 1
    },
`then save the text
go to terminal type sudo ./xmrig parameter 
xmrig need root permit to run config.json
sorry my english

**Comment by Shahnewaz1996** [comment]
Just a tip for people facing the same error on Windows: You need to disable "Memory Integrity" in Windows Security settings.
Windows Security -> Device Security -> Core isolation settings -> Turn Memory integrity off -> Restart.

I figured this out after the script from this [Reddit guide from u/sech1](https://www.reddit.com/r/MoneroMining/comments/e9tuvd/randomx_boost_guide_for_ryzen_on_windows_9100_hs/) output "no such msr" for all registers.

My setup works with Secure Boot enabled.

**Comment by ScardracS** [comment]
The dev branch should have fixed this problem

**Comment by Avnsx** [comment]
Same thing for me too

**Comment by SChernykh** [comment]
@Avnsx Did you read the messages and try the listed solutions?

**Comment by Avnsx** [comment]
> @Avnsx Did you read the messages and try the listed solutions?

Yes didn't work for me at all, but I guess it's because I'm running on a VM

**Comment by Koesters** [comment]
on some Atom prefetch is not accessible and seemingly  N3050 too. Safe boot is disabled and all run as sudo.

see;
https://stackoverflow.com/questions/36608310/how-to-disable-prefetcher-in-atom-n270-processor

sudo ./boost.sh 

Detected Intel
wrmsr: CPU 0 cannot set MSR 0x000001a4 to 0x000000000000000f
MSR register values for Intel applied
sudo lsmod | grep msr
msr                    16384  0

cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 76
model name	: Intel(R) Celeron(R) CPU  N3050  @ 1.60GHz
stepping	: 3
microcode	: 0x368
cpu MHz		: 950.625
cache size	: 1024 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat md_clear
bugs		: cpu_meltdown spectre_v1 spectre_v2 mds msbds_only
bogomips	: 3199.87
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 76
model name	: Intel(R) Celeron(R) CPU  N3050  @ 1.60GHz
stepping	: 3
microcode	: 0x368
cpu MHz		: 1370.937
cache size	: 1024 KB
physical id	: 0
siblings	: 2
core id		: 2
cpu cores	: 2
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat md_clear
bugs		: cpu_meltdown spectre_v1 spectre_v2 mds msbds_only
bogomips	: 3199.87
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
`
This is just for info.

**Comment by revdeluxe** [comment]
> on some Atom prefetch is not accessible and seemingly N3050 too. Safe boot is disabled and all run as sudo.
> 
> see; https://stackoverflow.com/questions/36608310/how-to-disable-prefetcher-in-atom-n270-processor
> 
> sudo ./boost.sh
> 
> Detected Intel wrmsr: CPU 0 cannot set MSR 0x000001a4 to 0x000000000000000f MSR register values for Intel applied sudo lsmod | grep msr msr 16384 0
> 
> cat /proc/cpuinfo processor : 0 vendor_id : GenuineIntel cpu family : 6 model : 76 model name : Intel(R) Celeron(R) CPU N3050 @ 1.60GHz stepping : 3 microcode : 0x368 cpu MHz : 950.625 cache size : 1024 KB physical id : 0 siblings : 2 core id : 0 cpu cores : 2 apicid : 0 initial apicid : 0 fpu : yes fpu_exception : yes cpuid level : 11 wp : yes flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat md_clear bugs : cpu_meltdown spectre_v1 spectre_v2 mds msbds_only bogomips : 3199.87 clflush size : 64 cache_alignment : 64 address sizes : 36 bits physical, 48 bits virtual power management:
> 
> processor : 1 vendor_id : GenuineIntel cpu family : 6 model : 76 model name : Intel(R) Celeron(R) CPU N3050 @ 1.60GHz stepping : 3 microcode : 0x368 cpu MHz : 1370.937 cache size : 1024 KB physical id : 0 siblings : 2 core id : 2 cpu cores : 2 apicid : 4 initial apicid : 4 fpu : yes fpu_exception : yes cpuid level : 11 wp : yes flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat md_clear bugs : cpu_meltdown spectre_v1 spectre_v2 mds msbds_only bogomips : 3199.87 clflush size : 64 cache_alignment : 64 address sizes : 36 bits physical, 48 bits virtual power management: ` This is just for info.

IDK why i find this funny 
what a coincidence
`processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 76
model name	: Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz
stepping	: 4
microcode	: 0x411
cpu MHz		: 1146.036
cache size	: 1024 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb pti ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat md_clear
vmx flags	: vnmi preemption_timer invvpid ept_x_only flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest
bugs		: cpu_meltdown spectre_v1 spectre_v2 mds msbds_only
bogomips	: 3200.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 76
model name	: Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz
stepping	: 4
microcode	: 0x411
cpu MHz		: 480.000
cache size	: 1024 KB
physical id	: 0
siblings	: 2
core id		: 2
cpu cores	: 2
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb pti ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat md_clear
vmx flags	: vnmi preemption_timer invvpid ept_x_only flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest
bugs		: cpu_meltdown spectre_v1 spectre_v2 mds msbds_only
bogomips	: 3200.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
`

**Comment by GVCrypto** [comment]
> Just a tip for people facing the same error on Windows: You need to disable "Memory Integrity" in Windows Security settings. Windows Security -> Device Security -> Core isolation settings -> Turn Memory integrity off -> Restart.
> 
> I figured this out after the script from this [Reddit guide from u/sech1](https://www.reddit.com/r/MoneroMining/comments/e9tuvd/randomx_boost_guide_for_ryzen_on_windows_9100_hs/) output "no such msr" for all registers.
> 
> My setup works with Secure Boot enabled.

correct

**Comment by Tronixxx88** [comment]
> > > > Cuando ejecuta el comando, xmrig comienza un minar. Pero estoy recibiendo ese mensaje con línea amarilla. 
> > > > no se puede configurar MSR 0x000001a4 a 0x0000000f 
> > > > MSR Tools se instaló automáticamente. Utilice todas las combinaciones de wrmrs necesarias para la CPU de randomx_boost.
> > > 
> > > 
> > > No iniciar el comando de ejecución 
> > > Simplemente iniciar xmrig .exe
> > 
> > 
> > sistema bajo linux
> 
> Dame todos los archivos captura de pantalla ..

Puedes ayudarme un poco?

**Comment by dustybookshelf** [comment]
![preset ok Ryzen 7](https://github.com/xmrig/xmrig/assets/34599947/f6b94205-c916-44ab-96b2-cf0133447540)

**Comment by dustybookshelf** [comment]
![preset ok Ryzen 7](https://github.com/xmrig/xmrig/assets/34599947/4a367418-fafd-4ffc-9589-4d48000b1865)

**Comment by dustybookshelf** [comment]
![image](https://github.com/xmrig/xmrig/assets/34599947/81fec7fd-5f99-489d-92e7-38e929797c7f)
