### ISSUE TITLE
#Huge page problem in android

### ISSUE THREAD

**Issue by Saikatsaha1996** [xmrig/xmrig#1892]
![Screenshot_20201013-173252](https://user-images.githubusercontent.com/72664192/95858508-d6738c00-0d7a-11eb-88ac-0780db8ca685.png)
Anyone can help me?
Its xmrig 6.3.5 in android
I got 340 h/s in my mobile
And showing huge page supported but showing huge page 0% how can I solve it please help..

**Comment by Lonnegan** [comment]
To lock huge pages, the RAM mustn't be fragmented. When an Android device has been on already for a few days, there isn't a free contiguous RAM section anymore. Reboot your smartphone and it should work :)

**Comment by Saikatsaha1996** [comment]
If i reboot my mobile so my all termux data gone.. how can i saved my termux data?

**Comment by Lonnegan** [comment]
Google for "Backing up Termux" ;)

**Comment by xerox87** [comment]
where to get xmrig-notls on linux?

**Comment by paypur** [comment]
> To lock huge pages, the RAM mustn't be fragmented. When an Android device has been on already for a few days, there isn't a free contiguous RAM section anymore. Reboot your smartphone and it should work :)

This is not working for me, my phone has 8gbs of ram so It should work

**Comment by FrankHB** [comment]
> This is not working for me, my phone has 8gbs of ram so It should work
8 GB won't work after a few days, esp. the miner can be killed frequently. In my experience, even a 16 GB device would probably fail. 40 GB can work without worry.

**Comment by Spudz76** [comment]
You can reserve hugepages at boot time (or early after boot) with sysfs or kernel args, google about it (not sure exact methods for Android) ...  But then nothing else but the miner can use that region ever, which might make OOM for other things, or even boot failure.

Some CPUs don't get any gains from it anyway, it might not be a real problem.

**Comment by abyssbad** [comment]
Hola cuál es el procedimiento por favor quisiera saber

**Comment by abyssbad** [comment]
Necesito el procedimiento exacto para habilitar hugepages en mi Android estoy usando app userland Ubuntu... Con xmrig... Actualmente minando con 194h/s pero si ha levantado un poco más en un solo dispositivo... Coloco varios pero quiero usar más memoria y levantar más los h/s

**Comment by ChaoLine892** [comment]
for enable hugepages use kernel with support hugepages and su with magisk or supersu
