### ISSUE TITLE
version 6.3.5 does not work

### ISSUE THREAD

**Issue by andrexTI** [xmrig/xmrig#1902]
Hello everyone, version 6.3.5 does not work on my computers. See the error:

![1](https://user-images.githubusercontent.com/60714578/96276715-bece1a80-0fa9-11eb-85aa-687ef8709d74.png)

With version 6.3.3 everything works fine.

![2](https://user-images.githubusercontent.com/60714578/96276970-0d7bb480-0faa-11eb-9ac7-597324b1eccb.png)

Could someone help me make the new version work?

**Comment by xmrig** [comment]
Seems you use a different config for both versions and didn't enable TLS `"tls": true,` for 6.3.5.
Thank you.

**Comment by andrexTI** [comment]
That was it, now the new version works. 

Thanks =]

**Comment by DeadManWalkingTO** [comment]
Problem solved.
Now this issue can be closed.
Thank you!
