### ISSUE TITLE
cannot compile 6.4.0 on centos 7

### ISSUE THREAD

**Issue by solpodein** [xmrig/xmrig#1908]
src/crypto/randomx/vm_compiled.hpp:41:8: error: converting to ‘const randomx::JitCompilerX86’ from initializer list would use explicit constructor ‘randomx::JitCompilerX86::JitCompilerX86(bool)’

**Comment by cohcho** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58930
That's due to bug in old version of GCC.

**Comment by cohcho** [comment]
@solpodein 
https://github.com/cohcho/xmrig/commit/d38042f515245681c4ef6cf5db1c038da2323841
Try this branch with 1 commit on top of v6.4.0 tag.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v6.5.2
