### ISSUE TITLE
chukwa algo upgrade to chukwa2

### ISSUE THREAD

**Issue by bkmy625** [xmrig/xmrig#1909]
chukwa updated to chukwa v2 and no longer can mine TRTL

https://blog.turtlecoin.lol/archives/turtlecoin-v1-0-0-upgrade/

**Comment by SChernykh** [comment]
Version 6.4.0 has support for chukwa v2.

**Comment by Lonnegan** [comment]
But only CPU, not GPU?

**Comment by SChernykh** [comment]
Chukwa never had GPU support in XMRig.

**Comment by bkmy625** [comment]
yes 6.4.0 has the support, but the xmrig-proxy has to be updated

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig-proxy/releases/tag/v6.4.0
Thank you.
