### ISSUE TITLE
Even Odd NUMA affinity?

### ISSUE THREAD

**Issue by dwright1542** [xmrig/xmrig#191]
How to specify even and odd CPU's in Linux to xmrig? It's easy when it's 0-11 and 12-23. These are 0,2,4,6,8,10,12,14,16,18,20,22 and 1,3,5,7,9,11,13,15,17,19,21,23... Opteron 6238 CPU's.

**Comment by xmrig** [comment]
`0,2,4,6,8,10,12,14,16,18,20,22` `0x555555` https://i.imgur.com/XyChITh.png
`1,3,5,7,9,11,13,15,17,19,21,23` `0xAAAAAA`

if you use config file value should in quotes as string `"0x555555"` or as number in decimal form.
Not sure it will work correctly with NUMA nodes, still have issues with it, check roadmap #106
Thank you.

**Comment by xmrig** [comment]
If this issue still actual, please check v2.99.2-beta release #1077.
Thank you.
