### ISSUE TITLE
When to use nicehash mode on xmrig and xmrig-proxy

### ISSUE THREAD

**Issue by bkmy625** [xmrig/xmrig#1914]
I use xmrig-proxy with 17 miners with xmrig, they have various hashrates, from 300h/s to 2500h/s.
My question is where is it needed to use the mode nicehash on the workers or in the xmrig-proxy or in both?
Which configs are correct
1. workers with active nicehash mode and xmrig-proxy with simple mode
2. workers with DISABLED nicehash mode and xmrig-proxy with enabled nicehash mode
3. Both workers with enabled nicehash mode and xmrig-proxy with enabled nicehash mode too

what are the differences and which is the best for my situation?

**Comment by dvershinin** [comment]
I'd rather have this documented rather than closed :p
