### ISSUE TITLE
./xmrig: cannot execute binary file: Exec format error


### ISSUE THREAD

**Issue by Saikatsaha1996** [xmrig/xmrig#1922]
![IMG_20201031_005210.jpg](https://user-images.githubusercontent.com/72664192/97748571-aa466200-1b13-11eb-97b2-9f2eef0f4d20.jpg)
Please help me how can i solve

**Comment by xmrig** [comment]
Disable your antivirus, likely it corrupted the executable. In overall, native windows executable (*.exe) recommended, run Linux binary with virtualization layer not looks like the right idea.
Thank you.

**Comment by Saikatsaha1996** [comment]
Ok.. thank you
