### ISSUE TITLE
Nvdia Quadro k1200

### ISSUE THREAD

**Issue by CyborgGenos** [xmrig/xmrig#193]
Hi, please help, getting the following error when trying to mine with GPU. I cannot figure out why. BTW thanks for this awesome piece of software
![2017-11-08_224740]

(https://user-images.githubusercontent.com/32089229/32573677-6b104d66-c4d7-11e7-9bb4-4277ab501d11.png)

As a side note, I have not experienced this before with an AMD

**Comment by xmrig** [comment]
Try decrease threads number in `config.json` and/or increase bfactor.
Also it wrong place for this issue, should be here https://github.com/xmrig/xmrig-nvidia/issues
Thank you.
