### ISSUE TITLE
Remove unable to open config warning

### ISSUE THREAD

**Issue by Maz4id** [xmrig/xmrig#1930]
So I'm using 'Systemd' on linux to start xmrig with embedded config on it. It used to work perfectly until the last update. Now when I run xmrig it says:
**[2020-11-05 00:08:21.368] unable to open "/var/tmp/config.json".
[2020-11-05 00:08:21.369] unable to open "/root/.xmrig.json".
[2020-11-05 00:08:21.369] unable to open "/root/.config/xmrig.json".**
Systemd considers this an error and basically, it doesn't start anymore. I just want to know how to remove that message thanks.

**Comment by xmrig** [comment]
You can remove this message, by removing this line https://github.com/xmrig/xmrig/blob/master/src/base/io/json/JsonChain.cpp#L90 but it is strange this message was in all previous versions, but just one not 3.
Thank you.
