### ISSUE TITLE
Load WinRing0x64.sys from other path?

### ISSUE THREAD

**Issue by ghost** [xmrig/xmrig#1933]
It's possible to load WinRing0x64.sys from another path other than where the xmrig's exe resides?
Thanks

**Comment by Technetium1** [comment]
@ghost It's hardcoded, you would need to recompile https://github.com/xmrig/xmrig/blob/4e671a945d52c5a803fa0e19436c7c58e8ac59c7/src/hw/msr/Msr_win.cpp#L125
