### ISSUE TITLE
GetTickCount64 could not be located in the dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by febriyan1302** [xmrig/xmrig#194]
Hi, i am running with windows server 2003 (64-bit), when i start program it show "GetTickCount64 could not be located in the dynamic link library KERNEL32.dll".

can you solve this problem ? or xmrig does not support for Win Server 2003 ?

![screen shot 2017-11-12 at 3 55 04 am](https://user-images.githubusercontent.com/18423871/32693469-ded9fbd8-c75d-11e7-9762-5bf24aedd039.png)

**Comment by snorlax212** [comment]
sup
