### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by maribun20** [xmrig/xmrig#1943]
Why the source code can't be compiled on armv8 (Android)...?
What's wrong...?

**Comment by SChernykh** [comment]
What error do you get?

**Comment by AlexanderIreland** [comment]
For arm8 systems I've generally had some success with the following cmake options:

`-DCMAKE_SYSTEM_PROCESSOR=arm -DWITH_RANDOMX=OFF -DARM_TARGET=8`

I haven't tried to run a build on arm7 or arm8 in the last 15-20 days or so with randomx on, but for the life of me I wasn't able to get it to work on arm7 or 8 target systems previously.

Hope this helps! - Alexander

**Comment by maribun20** [comment]
my be add option conmand --xmrig-mode=light to run xmrig on arm v7 or arm v8 (Android) with small memories under 4 gb.
But, xmrig's work in fast mode on 5 to 8 gb ram memories.
