### ISSUE TITLE
 xmrig-6.5.1-msvc-cuda10_2-win64.zip shows up as Trojan on 40 different engines on virustotal

### ISSUE THREAD

**Issue by RaisingAgent** [xmrig/xmrig#1945]
https://www.virustotal.com/gui/file/4b8f9dc5c4db4bad5aa712b8f3dd29543376c5e71e42e8d0990dda954074ab98/detection

what the actual fork?

**Comment by RaisingAgent** [comment]
how are there soo many false positives?

**Comment by Lonnegan** [comment]
Have you ever read what the AV software reported? They claim to have found a coin miner! Wow. What is xmrig after all? ;)

**Comment by xmrig** [comment]
Seems Sophos AV is most precise: `XMRig Miner (PUA)`
