### ISSUE TITLE
Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by chughta1** [xmrig/xmrig#196]
Hi

The build instructions don't seem to work for 14.04 as the essential packages: 
`sudo apt-get install git build-essential cmake libuv1-dev libmicrohttpd-dev`

Are not available for 14.04 or LTS versions. Is there any alternative build instructions for lower versions of ubuntu?

**Comment by luca-nardelli** [comment]
I've managed to make it work by compiling libuv from sources https://github.com/libuv/libuv

**Comment by Algeroth123** [comment]
got the same problem, 
libuv is not a problem

xmrig/src/Summary.cpp: In function ‘void print_versions()’:
xmrig/src/Summary.cpp:45:85: error: ‘snprintf’ was not declared in this scope
     snprintf(buf, 16, " gcc/%d.%d.%d", __GNUC__, __GNUC_MINOR__, __GNUC_PATCHLEVEL__);
                                                                                     ^
xmrig/src/Summary.cpp: In function ‘void print_threads()’:
xmrig/src/Summary.cpp:95:76: error: ‘snprintf’ was not declared in this scope
         snprintf(buf, 32, ", affinity=0x%" PRIX64, Options::i()->affinity());
                                                                            ^
make[2]: *** [CMakeFiles/xmrig.dir/src/Summary.cpp.o] Error 1

gcc5, 6 ,7 the same error

**Comment by xmrig** [comment]
Issue with `snprintf` should be fixed in https://github.com/xmrig/xmrig/commit/4b00eb4a9fbb68392a316d8ac6c36a0931567d74
Thank you.
