### ISSUE TITLE
Pretty sure this is at least memory leak

### ISSUE THREAD

**Issue by ViralTaco** [xmrig/xmrig#1961]
Might be UB. In any case this is bad style so now I have to fork the whole repo. 
```
void xmrig::Buffer::move(Buffer &&other)
{
    if (m_size > 0) {
        delete [] m_data; // <-- m_data (char*)
    }

    m_data = other.m_data; // :sigh: 
    m_size = other.m_size;  // legit would be faster to use std::string. 

    other.m_data = nullptr; // <-- not freed
    other.m_size = 0;
}
```
Anyway… I'll make a pull request when I come to it

**Comment by xmrig** [comment]
This is part of the move operator, so free is not supposed to be here.
Sooner or later whole `Buffer` class will be replaced to https://github.com/xmrig/xmrig-nonces-heatmap/blob/master/src/base/tools/Buffer.h
Thank you.

**Comment by SChernykh** [comment]
Memory leak is by definition when memory is not freed and there's no pointers left pointing to it. This is not the case here, `m_data` still points to it. This function implements standard move semantics operation and takes rvalue reference in the first parameter.

**Comment by ViralTaco** [comment]
> Memory leak is by definition when memory is not freed and there's no pointers left pointing to it. This is not the case here, `m_data` still points to it. This function implements standard move semantics operation and takes rvalue reference in the first parameter.

Yeah but given the type of m_data is char pointer and not char array I'm not sure. Maybe there's an overload for this scenario that I missed.
other.m_data is never released/deleted/freed, is it? The Buffer is (presumably) moved into the function, when is it destroyed? 
If it is then there is the problem of use after move since m_data, again, is a raw pointer to char. 
Now I've not done c++ in a while so I'll ask smarter people to have a look.

**Comment by SChernykh** [comment]
You don't need to release other.m_data because it's a nullptr after the call. Current buffer release its own pointer first and then takes ownership of other.m_data. There's no memory leak here.

**Comment by ViralTaco** [comment]
> You don't need to release other.m_data because it's a nullptr after the call. Current buffer releases its own m_data first and then takes ownership of other.m_data. There's no memory leak here.

Yeah… I finally managed to wrap my head around that. There's no indication that ownership is transferred. 
Thank you for the explanation. I'll close this thread since the "issue" is solved.
