### ISSUE TITLE
各位大佬，这个 xmrig 怎样 在 android 下编译？

### ISSUE THREAD

**Issue by kungsoft** [xmrig/xmrig#1963]
有国内的 挖矿爱好者吗？ kungsoft@qq.com 
Q我一下

**Comment by kungsoft** [comment]
没人回应，呜呜~

**Comment by FrankHB** [comment]
Termux 下 proot 装个包够用的发行版。Arch Linux ARM 无压力。

**Comment by XZiar** [comment]
termux下可以直接编译。
https://xmrig.com/docs/miner/build/ubuntu
按advanced build来。
不过安卓下libuv编译有点问题，`./build_deps.sh`完成后要单独去libuv目录下用cmake再编译一次，然后把生成的libuv_a.a替换script/deps/lib下的libuv.a。
