### ISSUE TITLE
Hashrate Loss

### ISSUE THREAD

**Issue by septuig** [xmrig/xmrig#1965]
While xmrig is started, the Hashrate is about 8.5k, but after about 0.5hr, it drops to 4k. and then restarts again to 8.5k, after 0.5hr it drops again to 4k. the issue occurs on multiple PCs. 

CPU miners 2xE2680v2, 16G memory. 
Pool: SupportXMR:3333/5555. 

Thank you.

**Comment by xmrig** [comment]
Please check it first https://xmrig.com/docs/miner/randomx-stability-troubleshooting-guide
Thank you.

**Comment by SChernykh** [comment]
If on Windows, disable all tasks in Task Scheduler -> Microsoft -> Windows -> MemoryDiagnostic section. You can open task scheduler by pressing Win+R, typing `taskschd.msc` and pressing Enter.
