### ISSUE TITLE
Xeon E5-2630 v4 best config?

### ISSUE THREAD

**Issue by enigmen** [xmrig/xmrig#1972]
Hello, what best config for this cpu (monero) default run - 4050h\s it's max or no?

**Comment by SChernykh** [comment]
4 kh/s is a good hashrate for this CPU, see https://xmrig.com/benchmark?cpu=Intel%28R%29+Xeon%28R%29+CPU+E5-2630+0+%40+2.30GHz

**Comment by Zorg33** [comment]
Also try to play with the MSR mod bits. The default 15 for Intel is not always the best for Xeons...
