### ISSUE TITLE
Failed to load OpenCL runtime this is not bug && unofficial issue

### ISSUE THREAD

**Issue by Saikatsaha1996** [xmrig/xmrig#1978]
**Describe the bug**
Not bug

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: [e.g. Windows]
 - For GPU related issues: information about GPUs and driver version.

**Additional context**
![Screenshot_20201214-184632](https://user-images.githubusercontent.com/72664192/102174306-2548b980-3ec3-11eb-839a-123fedd54562.png)
![Screenshot_20201215-104718](https://user-images.githubusercontent.com/72664192/102174315-2843aa00-3ec3-11eb-8887-655e30635b36.png)
![Screenshot_20201214-195733](https://user-images.githubusercontent.com/72664192/102174316-28dc4080-3ec3-11eb-9239-94dcf3465b89.png)

Android mobile
Android 10
Ram 6gb
Gpu Qualcomm Adreno TM 514
In my device already available OpenCL 2.0
But i face problem with failed to load OpenCL runtime
This is testing purposes only
Please help me
How can i solve it?
![Screenshot_20201214-182224](https://user-images.githubusercontent.com/72664192/102182573-81ffa080-3ed2-11eb-8daf-53f06898c867.png)

**Comment by Saikatsaha1996** [comment]
No one available for help 😑

**Comment by FrankHB** [comment]
The default library name `libOpenCL.so` is hard-coded in `xmrig::OclLib::defaultLoader`. Seems a different name?
