### ISSUE TITLE
Ryzen Threadripper 1950X

### ISSUE THREAD

**Issue by hammuh1911** [xmrig/xmrig#198]
I use Nicehash Legacy Miner and have very low hash rate with xmrig.
(xmr-stak-cpu is working fine with more than 1 kH/s)
I am using Ryzen Threadripper 1950x. Specs:
16 cores
32 threads
32 MB L3 cache
What settings do I use to improve hashrate? I think there needs to be CPU affinity but am not sure how to figure the value. Thanks!

**Comment by Algeroth123** [comment]
show us numactl --hardware

**Comment by TechniumUnlimited** [comment]
Hi I'm having a similar issue. I have 2 TR pc's, 1950X's. One is running and earning over 3.50$/day , while my other one that is similarly cooled (slightly higher temp though), is only earning 0.11$/day. Both are stock... What could be causing the degraded performance? 

Good Hashrate PC has 128GB RAM, while slower one has only 8GB, but the one earning more has 2 GPU's also mining while this one that's slow has no GPU's mining. Same PSU, similarly priced boards, and SSD's slow one while NVME is in fast one.

Both win10, both same version of nicehash

**Comment by xmrig** [comment]
Probably CPU running in NUMA mode, in that case you need run miner on each node.
It know issue, check related #86, and already in roadmap.

**Comment by xmrig** [comment]
If this issue still actual, please check v2.99.2-beta release #1077.
Thank you.
