### ISSUE TITLE
xmr-stak-amd much faster with AMD Vega 56 

### ISSUE THREAD

**Issue by helbadini** [xmrig/xmrig#199]
Hi, 

The above easily outperforms by up to 25% with the following settings. Can these be replicated here? 

"gpu_thread_num" : 2,
"gpu_threads_conf" : [ 
    { "index" : 0, "intensity" : 2016, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 0, "intensity" : 1736, "worksize" : 8, "affine_to_cpu" : false },

Thanks!

Hugh

**Comment by helbadini** [comment]
Never mind, this works. 

    "opencl-platform": 1,
    "threads": [
        {
            "index": 0,
            "intensity": 2016,
            "worksize": 8,
            "affine_to_cpu":
			false
        },
		{
            "index": 0,
            "intensity": 1736,
            "worksize": 8,
            "affine_to_cpu": false
        },
    ],

**Comment by nazarimilad** [comment]
Don't forget to close the issue.
