### ISSUE TITLE
Apple M1 processor

### ISSUE THREAD

**Issue by xmrig** [xmrig/xmrig#1991]
v5.7.0 brings official support for Apple M1 processor on macOS for [compile from source](https://xmrig.com/docs/miner/build/macos) and binary downloads.
ARMv8 architecture is already supported, but macOS disallows fast Just-In-Time (JIT) compiler support required for RandomX, so [secure JIT mode](https://developer.apple.com/documentation/apple_silicon/porting_just-in-time_compilers_to_apple_silicon?language=objc) was added, it has negative performance impact.

Hashrate slightly above 2300 H/s https://xmrig.com/benchmark?cpu=Apple+M1 + [Reddit discussion
](https://www.reddit.com/r/MoneroMining/comments/keg3ch/apple_m1_hashes_2330_hs_175_watts/)

ARM macOS has the following disadvantages which reduce the hashrate:

* Enforced Hardened Runtime, it means RandomX JIT compiler can work only in slow secure mode.
* Any kind of CPU affinity not supported.
* Huge pages not supported.

**Comment by iComUA** [comment]
why does not it work Apple M1 GPU?
when turned on OpenCL I get an error

**Comment by NEUcc** [comment]
> why does not it work Apple M1 GPU?
> when turned on OpenCL I get an error

Because OpenCL is special for AMD GPUs for mining. According to the section "Beckends" from the site: https://xmrig.com/wizard

**Comment by SpiritedByte** [comment]
Is there no way to enable the JIT entitlement?

**Comment by xmrig** [comment]
@SpiritedByte You can create Xcode project by adding `-G Xcode` to cmake command and change entitlements, but all it useless on ARM.
Thank you.

**Comment by AndyRPH** [comment]
Apple's documentation seems to say that you can waive the hardened runtime issues and allow JIT code to create, write, and execute memory.  Is there more that is needed to allow randomX to run in fast mode beyond the first two entitlements listed in this doc?   

https://developer.apple.com/documentation/security/hardened_runtime

**Comment by rovo79** [comment]
@xmrig
Recent RandomX release improves execution related to JIT limitations on M1?

https://github.com/tevador/RandomX/releases/tag/v1.1.9

> Benchmark v1.1.9
> his release brings support for the new ARM-based Apple silicon and a small speed-up for all CPUs.
> 
> Full list of changes:
> 
> Apple silicon: force W^X, enable hardware AES #198
> Remove unnecessary first-load initialization code #201
> Fix illegal instruction crash on some ARM systems #202
> Optimized dataset read #211
> Faster W^X policy for apple silicon macs #212
> Fix typo for M1 Mac build #213
>

**Comment by SChernykh** [comment]
It's all already implemented in xmrig.

**Comment by rovo79** [comment]
@SChernykh I didn't realize. I thought because v1.19 was released 4 days ago, it hadn't made its way into XMrig yet.

**Comment by SChernykh** [comment]
xmrig uses its own implementation which diverged from tevador's repository long time ago.

**Comment by rovo79** [comment]
> xmrig uses its own implementation which diverged from tevador's repository long time ago.

TodayILearned
