### ISSUE TITLE
CL_OUT_OF_HOST_MEMORY with AMD Radeon Vega 8 (gfx902)

### ISSUE THREAD

**Issue by ulitosCoder** [xmrig/xmrig#1993]
When i start xmrig in windows 10 with command line I get eventually get CL_OUT_OF_HOST_MEMORY.

xmrig won't stop but would disable opencl backend.

![image](https://user-images.githubusercontent.com/17461642/102839687-ad98f400-43c6-11eb-9869-db9d8980c535.png)

**Required data**
 - Config file or command line (without wallets)
 - Windows 10
 - AMD Radeon Vega 8 (gfx902)
 - command line: xmrig.exe --no-cpu -a Kawpow -o rvn-eu1.nanopool.org:12222 -u WALLET/worker/email@example.com -p x --opencl -k

**Comment by Spudz76** [comment]
How much host memory do you have free?

**Comment by ulitosCoder** [comment]
45% free, using 2.9GB out of 5.9GB
