### ISSUE TITLE
[ 70%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/cn/CnHash.cpp.o In file included from /root/XTDS/av/xmrig-master/src/crypto/cn/soft_aes.h:31:0, from /root/XTDS/av/xmrig-master/src/crypto/cn/CryptoNight_arm.h:35, from /root/XTDS/av/xmrig-master/src/crypto/cn/CnHash.cpp:35: /root/XTDS/av/xmrig-master/src/crypto/cn/sse2neon.h:65:10: fatal error: arm_neon.h:

### ISSUE THREAD

**Issue by 1756816846** [xmrig/xmrig#1999]
[ 70%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/cn/CnHash.cpp.o
In file included from /root/XTDS/av/xmrig-master/src/crypto/cn/soft_aes.h:31:0,
from /root/XTDS/av/xmrig-master/src/crypto/cn/CryptoNight_arm.h:35,
from /root/XTDS/av/xmrig-master/src/crypto/cn/CnHash.cpp:35:
/root/XTDS/av/xmrig-master/src/crypto/cn/sse2neon.h:65:10: fatal error: arm_neon.h:

**Comment by xmrig** [comment]
Duplicate #1997
