### ISSUE TITLE
The new software AES algo 4 is slower than the old one

### ISSUE THREAD

**Issue by sfrode** [xmrig/xmrig#2]
Hello,
with the old software AES implementation, I used to get approximately 140 H/s on my dual E5520 with kernel 4.4.0 (VMware VM, 8 cores allocated). With the new one committed in 21c243ed8f5e67a08170cef1b1fbcf7a2167190b, I'm getting around 110-115 H/s. Is there any way you can keep the old algo around as well?

Btw, good work on the miner!

**Comment by xmrig** [comment]
Interesting result, old software AES is not so good, sometimes was broken due compiler optimization and was slower on i7 6700. I will check it again.

Anyway E5520 supports AES-NI. Sometimes virtual cpus is not contains for all available cpuid flags. If you manually select `--av=1` it may work. I already had a similar case.

**Comment by sfrode** [comment]
Unfortunately for me who has loads of the Xeon 5500 series CPUs, AES-NI wasn't introduced until the Xeon 5600 series.

I pulled master again and recompiled with gcc 6.2.0 (ubuntu use 5.4.0 as default on 16.04); but that didn't change anything.

**Comment by esfomeado** [comment]
With the latest commit i have about 5% drop on algo 3 (BMI2).
