### ISSUE TITLE
log file

### ISSUE THREAD

**Issue by Blisk** [xmrig/xmrig#2002]
**Describe the bug**
How can I set logfile in this miner? And how can I set mining intension? 
Your readme have nothing about it.

**Comment by Spudz76** [comment]
The readme clearly says go use the config generator wizard, so maybe [go use the generator](https://xmrig.com/wizard) to have a starting point

I'd bet the logfile location might be set with the `log-file` config option, but that's probably too obvious.  Better complain about not documenting it instead.  Nobody could ever figure that option out without docs for sure.  Oh wait `--help` has docs:
```
  -l, --log-file=FILE           log all output to a file
```
Protip: command line options roughly translate to the same config file entries, except when it's a backend option inside its own json sub-block and then you remove the backend name.  So the command line `--help` is actually also the docs for the config file, in a way.

Do you mean intensity?  Well once you've made a config.json with the wizard, and then run it once on your rig, it will autofill all the mining configurations, and then you quit and edit them if you don't like the automatic intensities.

**Comment by Blisk** [comment]
thank you.
Intensity I don't want it to use max when I use my PC so I want to reduce it, when I use word or excell
