### ISSUE TITLE
how to enable 1gb page in tinycore

### ISSUE THREAD

**Issue by seisdr** [xmrig/xmrig#2003]
according to https://github.com/xmrig/xmrig/blob/master/scripts/enable_1gb_pages.sh
there's no "node" directory in /sys/devices/system/ in tinycore

**Comment by xmrig** [comment]
This issue related to tinycore probable to achieve small size, sysfs and maybe hugepages is disabled. Anyway I can't provide support for systems I never used.
Thank you.

**Comment by seisdr** [comment]
well it's linux related  doesn't matter what os 
Ignore that

**Comment by seisdr** [comment]
well it's linux related  doesn't matter what os 
Ignore that issue
