### ISSUE TITLE
AstroBWT crashes rig (6800 XT)

### ISSUE THREAD

**Issue by fm407** [xmrig/xmrig#2005]
**Describe the bug**
When using astrobwt algo the rig bluscreens or freezes and then reboots

**To Reproduce**
mine Dero with 6800XT + cpu

**Expected behavior**
not crash the system

**Required data**
Windows v. 1909 latest patch level, 

* OPENCL       #0 AMD Accelerated Parallel Processing/OpenCL 2.1 AMD-APP (3188.4)
* OPENCL GPU   #0 0e:00.0 AMD Radeon RX 6800 XT (gfx1030) 2015 MHz cu:36 mem:13695/16368 MB

**Additional context**
it happens only with astrobwt algo

**Comment by Spudz76** [comment]
AstroBWT doesn't actually work with OpenCL at all, so that is not surprising.

**Comment by fm407** [comment]
> AstroBWT doesn't actually work with OpenCL at all, so that is not surprising.

so, what's all of this for? https://github.com/xmrig/xmrig/pull/1602/commits/fbedf197aba11b24b3389818ffa45041d34d72d7

**Comment by SChernykh** [comment]
It used to work before but now it crashes for me too. I guess it's a problem with newer AMD drivers.

**Comment by fm407** [comment]
[Details](https://i.imgur.com/6Ft72YY.png)

Not sure if its of any use, but i have attached my system specs

**Comment by SChernykh** [comment]
https://github.com/xmrig/xmrig/pull/2009 should fix it
