### ISSUE TITLE
after installing xmrig on ubuntu

### ISSUE THREAD

**Issue by spitrip82** [xmrig/xmrig#2013]
after installing xmrig on the vps i managed to change the config and run xmrig, a few days passed and i would like to change the pools and doors, how do i get to
came from config.jason?
sorry for my ignorance i never worked with linux and i don't understand anything. ubuntu linux use on vps
thanks for help my friends, and happy xmas to all
![Capture](https://user-images.githubusercontent.com/76714275/103252903-47841200-496e-11eb-9b57-04964a636daf.PNG)

**Comment by nthon** [comment]
Hi, could you rename config.jason to config.json.

The command: mv config.jason config.json

and put it in same folder with xmrig file.

**Comment by spitrip82** [comment]
> Hi, could you rename config.jason to config.json.
> 
> The command: mv config.jason config.json
> 
> and put it in same folder with xmrig file.

thanks mate
