### ISSUE TITLE
mining cn-heavy / xhv at 128 core

### ISSUE THREAD

**Issue by Tom68-cz** [xmrig/xmrig#2014]
I have a 128 thread processor. When I want a mining cn-heavy / xhv processor it runs only 64 threads and is minig 5500 H / s. If I reset mining in config to 120 threads, mining is only 2200 H / s. All threads run 4000 Mhz in both cases. I have 64 Gb of RAM. Does anyone know why this is so?

**Comment by Lonnegan** [comment]
CN Heavy uses 4 MB scratchpad size per thread. Do you have enough last level cache to run 120 or 128 threads without flooding the cache? What's your CPU?

**Comment by Tom68-cz** [comment]
Threadriper 3990x

**Comment by Tom68-cz** [comment]
Ok I get it. Is there a way to fix it?

**Comment by Lonnegan** [comment]
You cpu has 256 MB last level cache. 4 MB for each thread makes 64 threads. So running 64 threads gives you the best performance, because it can mine without accessing the slow DRAM.

If you want to use all your logical CPUs, you have to mine a CN coin with 2 MB scratchpad size, for example Monero.

**Comment by Tom68-cz** [comment]
thank you
