### ISSUE TITLE
Dockerhub image is badly outdated

### ISSUE THREAD

**Issue by h8llama** [xmrig/xmrig#2019]
https://hub.docker.com/r/xmrig/xmrig exists but was last updated 3years ago

I've submitted a PR with a Dockerfile that will allow configuring auto building docker images whenever master is pushed (after it gets merged to master obv.): https://github.com/xmrig/xmrig/pull/2018

a demobuild  using Dockerfile in PR and current master (v6.7.0) is available at https://hub.docker.com/repository/docker/h8llama/xmrig

Alternatively the stale image should be removed from Dockerhub

**Comment by xmrig** [comment]
This Dockerhub image is not official and was created by someone else.
Thank you.

**Comment by h8llama** [comment]
Ah, understood. unfortunate it was posted as xmrig/xmrig ....

Still think the Dockerfile in the pr would be a good add and only ongoing maintenance would be verifying the Alpine package dependencies but ¯\_(ツ)_/¯
