### ISSUE TITLE
Kawpow disabled ?

### ISSUE THREAD

**Issue by PvtSec** [xmrig/xmrig#2021]
* Issued these arguments to start. But it shows the following error:

```xmrig -o asia.ravenminer.com:3838 -u xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -k -a kawpow```
Output:
```[asia.ravenminer.com:3838] incompatible/disabled algorithm "kawpow" detected, reconnect```

**Comment by SChernykh** [comment]
Kawpow mining is supported only for GPUs, so you need to add `--opencl` for AMD or `--cuda` for NVIDIA to your command line.
