### ISSUE TITLE
Support for Cryptonight Fast v1/v2

### ISSUE THREAD

**Issue by shopglobal** [xmrig/xmrig#2022]
Is there any easy way in the existing code base to add back support for cn-fast v1? There's several CN-Fast v1 coins out now.

**Comment by Lonnegan** [comment]
Why not using an old version for that old algo?

**Comment by shopglobal** [comment]
So you're suggesting devs to change algos? There are 7 or 8 coins using CNFast v1.

**Comment by xmrig** [comment]
What coins exactly?
Thank you.
