### ISSUE TITLE
Türkçe olarak yada Google translet ile yardımcı olur musunuz

### ISSUE THREAD

**Issue by bysoclose** [xmrig/xmrig#2024]
AMD ryzen 9 işlemci ile bu maden işini yapmak ne kadar kazanç sağlar
Yada Intel i5 9.nesil bir donanım ile mümkünmu

**Comment by snipeTR** [comment]
kardeşim indireceksin çalıştıracaksın sonra orda görücen kaç hash ile yaptığını sormana gerek yok ayrıca dökümanlara bak. orada benchmark sitesi var oradan istediğin işlemcide kaç hash aldığını görebilirsin

**Comment by snipeTR** [comment]
@xmrig please close this issues

**Comment by bysoclose** [comment]
Tşk ederim bilgi için
