### ISSUE TITLE
Updating --max-threads-hint and --threads while running doesn't change CPU usage!

### ISSUE THREAD

**Issue by 88plug** [xmrig/xmrig#2029]
I am trying to update the threads and/or the max-threads-hint while xmrig is running, without a full restart. The changes to the json are detected by xmrig, but the software does not reduce or increase the amount of cores used, even when the value changes in the json. 

Is there a better/any other way to update the cores while running?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/blob/master/doc/CPU_MAX_USAGE.md
https://github.com/xmrig/xmrig/blob/master/doc/CPU.md
