### ISSUE TITLE
cpu usage

### ISSUE THREAD

**Issue by sametyuksel** [xmrig/xmrig#203]
hi

i cannot use all my cpus to hash more.
i have "Dual Intel Xeon X5650 2.66GHz HexaCore 24 cores".

Here what i tried on config.json;

cpu-affinity: null, cpu-priority: 5, max-cpu-usage: 100, threads: null (random 12 cores, 453 H/s)
cpu-affinity: 0xFFF, cpu-priority: 5, max-cpu-usage: 100, threads: null (first 12 cores, 450 H/s)
cpu-affinity: 0xFFF, cpu-priority: 5, max-cpu-usage: 100, threads: 24 (first 12 cores, 390 H/s)
cpu-affinity: 0xFFFFFF, cpu-priority: 5, max-cpu-usage: 100, threads: 24 (all 24 cores, 111 H/s)

what should i do to use all cores and get more hashrate.

**Comment by xmrig** [comment]
12 threads is optimal, because performance limited by CPU cache, not cores, each thread required 2 MB, so 24 / 2 = 12.

Option `max-cpu-usage` ignored if you manually specify threads and this option limited first by cache too.
Thank you.

**Comment by m1911** [comment]
I'm a double Xeon X5650.
Ubuntu 16.04 System.
It can only use one CPU.
@xmrig

**Comment by sametyuksel** [comment]
m1911 how much hashpower do you have?

**Comment by m1911** [comment]
speed 2.5s/60s/15m 457.0 456.2 455.3 H/s max: 457.2 H/s
@xmrig

**Comment by yyfong0918** [comment]
IBM X3550 M2, 4G RAM x4, dual X5650
Ubuntu 17.10

Run xmrig in 2 instance, each 6 threads, get total hashrate ~480H/s.

**Comment by m1911** [comment]
@yyfong0918  My configuration
{
    "algo": "cryptonight",  // cryptonight (default) or cryptonight-lite
    "av": 0,                // algorithm variation, 0 auto select
    "background": false,    // true to run the miner in the background
    "colors": true,         // false to disable colored output    
    "cpu-affinity": 0x00003f,   // set process affinity to CPU core(s), mask "0x3" for cores 0 and 1
    "cpu-priority": 5,   // set process priority (0 idle, 2 normal to 5 highest)
    "donate-level": 1,      // donate level, mininum 1%
    "log-file": null,       // log all output to a file, example: "c:/some/path/xmrig.log"
    "max-cpu-usage": 80,    // maximum CPU usage for automatic mode, usually limiting factor is CPU cache not this option.  
    "print-time": 60,       // print hashrate report every N seconds
    "retries": 5,           // number of times to retry before switch to backup server
    "retry-pause": 5,       // time to pause between retries
    "safe": false,          // true to safe adjust threads and av settings for current CPU
    "syslog": false,        // use system log for output messages
    "threads": null,        // number of miner threads
    "pools": [
        {
            "url": "xmr-us-east1.nanopool.org:14444", // URL of mining server
            "user": "",
            "pass": "x",                       // password for mining server
            "keepalive": true,                 // send keepalived for prevent timeout (need pool support)
            "nicehash": false                  // enable nicehash/xmrig-proxy support
        }
    ],
    "api": {
        "port": 0,                             // port for the miner API https://github.com/xmrig/xmrig/wiki/API
        "access-token": null,                  // access token for API
        "worker-id": null                      // custom worker-id for API
    }
}

But run an error.
/root/xmrig/build/config.json:300: Missing a comma or '}' after an object member.
No pool URL supplied. Exiting.

**Comment by yyfong0918** [comment]
@m1911 
WINDOWS or LINUX?

**Comment by sametyuksel** [comment]
@yyfong0918 

"cpu-affinity": 0x00003f,
>>
"cpu-affinity": "0x00003f",

**Comment by sametyuksel** [comment]
@yyfong0918 how do you open "turbo" on your processor?

**Comment by yyfong0918** [comment]
@sametyuksel 
In the BIOS setting

**Comment by m1911** [comment]
@yyfong0918 Ubuntu 16.04

**Comment by yyfong0918** [comment]
By the way, at the time I write this message, mining AEON (cryptonight-light algo) get more earning than XMR.

**Comment by sametyuksel** [comment]
in which pool? @yyfong0918

**Comment by yyfong0918** [comment]
@sametyuksel 
aeon-pool.com
But you have to reconfigure the setting, cryptonight-light use 1M cache instead of 2M for cryptonight.
I use 20 threads in one instance including HT, without cpu-affinity, i.e. or 0xffffff.

**Comment by sametyuksel** [comment]
@yyfong0918 where will you exchange it, i cant see it on poloniex?

**Comment by yyfong0918** [comment]
@sametyuksel 
I use HitBTC.com.
Poloniex drop the coin.

**Comment by yyfong0918** [comment]
For the same machine, checking at whattomine.com:
XMR = 12700 sato/day (480H/s)
AEON = 20500 sato/day (1550H/s)

Of course, this value only valid at the time I write this message.

**Comment by sametyuksel** [comment]
would you please tell us your server's hashrate, not whattomine. @yyfong0918 
do you have this hashpower with cryptonight-lite?

**Comment by m1911** [comment]
@yyfong0918 Why does Ubuntu 16.04 run the error?

**Comment by yyfong0918** [comment]
@sametyuksel 
I got 4XIBM X3550 M2,
Each dual X5650,
Total hashrate 1550x4 = 6200H/s.

**Comment by sametyuksel** [comment]
do you rent it?if yes how much? :) @yyfong0918

**Comment by yyfong0918** [comment]
@sametyuksel 

1550 is for crypto night-light.
I bought the servers last month in CHINA.
Each at RMB1000, ~USD150-160.
Total RMB4000

**Comment by sametyuksel** [comment]
wow its expensive.i bought it 39.99$.
if you would like to buy it annually its 29.99$

**Comment by yyfong0918** [comment]
@sametyuksel 
You mean rent?

**Comment by sametyuksel** [comment]
what you mean? did you buy it for this prices?

**Comment by yyfong0918** [comment]
@sametyuksel 
Yes, 4 physical servers.

**Comment by sametyuksel** [comment]
@yyfong0918 im very surprised.So you can rent it on miningrigrentals, you can earn more.

**Comment by yyfong0918** [comment]
@sametyuksel 
I don’t think so.
I can use these machine to mine without paying monthly rental.
The electricity price is less than USD0.08 here.
After all, I can trade my machine to get back part of my cost.

**Comment by sametyuksel** [comment]
miningrigrental is a different system.you can take a look.

miningrigrentals.com @yyfong0918

**Comment by yyfong0918** [comment]
@sametyuksel 

I have a look already.
For XMR, 48000sato/KH/day.

**Comment by sametyuksel** [comment]
ok you said
you can earn; XMR = 12700 sato/day (480H/s) * 2 for KH 25400 sato/day.

also after you put your servers on the site, you have an option that, you can forward your hashpower to any mining pool when its not rented.

**Comment by yyfong0918** [comment]
@sametyuksel 

Ok I get your idea, will have a deeper look, thx.

**Comment by yyfong0918** [comment]
@sametyuksel 
Sign up already, and try to do one machine first.

**Comment by sametyuksel** [comment]
i can help you, if you have questions. @yyfong0918

**Comment by yyfong0918** [comment]
@sametyuksel 
I already forwarded 2 servers, 970H/s.
It is not rented yet just mining on my pool.
Wait and see.

**Comment by sametyuksel** [comment]
i cant see it, did you activate it?

**Comment by yyfong0918** [comment]
@sametyuksel 
OK, tested for an hour, no rental.
The service is just like a joke, at least for cryptonight algo.
Switched back to mine AEON.
THANK YOU for your advice.

**Comment by sametyuksel** [comment]
i have two servers rented.
@yyfong0918

**Comment by yyfong0918** [comment]
@sametyuksel

Good luck and hope you get rich soon!

**Comment by gtimeg77** [comment]
kind of same topic
limiting cpu on one machine works fine
same os/build it doesnt

**Comment by pepecachivache** [comment]
@sametyuksel where did u rent?

**Comment by sametyuksel** [comment]
turnkeyinternet.net @pepecachivache

**Comment by pepecachivache** [comment]
@sametyuksel what service do u recommend me to mine monero? with xmrig

**Comment by sametyuksel** [comment]
im going to rent 25 of x5650 today or tomorrow and i will use xmrig on ubuntu 16.04.
If your provider let, overclock.

**Comment by pepecachivache** [comment]
@sametyuksel how u overclock it?

**Comment by sametyuksel** [comment]
not me, ask to your provider.

**Comment by pepecachivache** [comment]
how is the way to ask them to overclock it?

**Comment by sametyuksel** [comment]
open a support ticket and tell them to overclock on BIOS.

**Comment by pepecachivache** [comment]
you are earning for like 4 dolar each with 450 h per sec? excluding cost of hexacore server

**Comment by sametyuksel** [comment]
yes @pepecachivache

**Comment by pepecachivache** [comment]
u paid plan for one year no? and pool fee? what cripto are u mining?

**Comment by sametyuksel** [comment]
im mining monero, 29.99 yearly is ok.But 39.99 is not unprofitable for just mining.

**Comment by pepecachivache** [comment]
@sametyuksel do you have a cellphone to talk? thanks

**Comment by sametyuksel** [comment]
@pepecachivache im not available for call.you can mail me sametyuksel@gmail.com

**Comment by pepecachivache** [comment]
let me know when you are online!

2017-11-27 18:05 GMT-03:00 sametyuksel <notifications@github.com>:

**Comment by shrewdacumen** [comment]
This happens on MacOS.
./xmrig -c some.file.json  --> produces an error if I removed config.json file.
cp some.file.json config.json
./xmrig --> run without problem.

xmrig does not recognize multi-cores on MacOS High Sierra.
Thus it runs sluggishly using 1-core only. (Intel i7 process felt useless with xmrig on MacOS)
