### ISSUE TITLE
Is it possible to set up a proxy server for connection?

### ISSUE THREAD

**Issue by wallisonfgt** [xmrig/xmrig#2032]
Hello, I want to congratulate you on the project, it's just wonderful, amazing !!!

My situation is as follows:
I would like to use the miner in my work environment when the machine is idle, but the internet goes through a proxy and is blocking the connection, I would like to know if it is possible to configure the proxy server settings from where I work in the configuration files.

Thank you very much!!!

**Comment by SChernykh** [comment]
Check with your employer to see if they can add exception on their proxy. All other options mean you're doing it without approval and risk getting fired for $15-20/month from mined XMR.

**Comment by wallisonfgt** [comment]
SChernykh, Thank You!
I thought I could manually insert the proxy, because the address via the web I can reach because the proxy is configured in the browser, but within the application I cannot, because it does not have proxy information for it to reach the destination.

**Comment by SChernykh** [comment]
XMRig only supports socks5 proxies, not http proxies.
