### ISSUE TITLE
How can I play xmrig processing on AMD's dedicated GPU?

### ISSUE THREAD

**Issue by wallisonfgt** [xmrig/xmrig#2034]
How can I play xmrig processing on AMD's dedicated GPU?

Processing is only recognized on my integrated GPU, my dedicated GPU is an AMD Radeon R8 M445DX.

Thank you!

**Comment by Spudz76** [comment]
If it supports OpenCL and all the stuff is installed, it should work.
Linux, or Windows?  On Linux you'd install AMDGPU-Pro but it might not support OpenCL on some embedded graphics.  On Windows, I know nothing.

**Comment by ScardracS** [comment]
On Windows should be enought enable OpenCL flag (or use --opencl if you run from cmd)
