### ISSUE TITLE
Add memory specifications to benchmark information

### ISSUE THREAD

**Issue by BillGatesIII** [xmrig/xmrig#2038]
It would be nice to have the memory specifications shown on the benchmark page.

For example:
. | AMD Ryzen Threadripper 3970X 32-Core Processor (1)
-- | --
Threading | 32 cores / 64 threads / 1 CPU / 1 node
Caches | L2: 16.0 MB / L3: 128.0 MB
CPUID | 830F10 / Family: 17 / Model: 31 / Stepping: 0
Memory | 4 x 8GB DDR4 @ 3200Mhz CL 13-12-14-27
Flags | aes, avx, avx2, bmi2, osxsave, pdpe1gb, sse2, ssse3, sse4.1, popcnt, cat_l3
Backend | hwloc/2.1.0

**Comment by Spudz76** [comment]
Not sure how system memory specs matter since most algos avoid using it anyway (cache resident only).

**Comment by xmrig** [comment]
@Spudz76 Memory is very important for RandomX algorithms, all top results achieved with fine tuned memory. Online benchmark also accept only RandomX algorithms so it is useful information.

Seems possible to get almost all information about memory modules via SMBIOS on Linux and Windows. What information available can be viewed by `dmidecode -t 17` command.

2 disadvantages:
1. Memory timings not available.
2. On Linux super user permissions required to read data.

**Comment by BillGatesIII** [comment]
I did some research and as far as I understand it is possible for DDR4 to read the SPD data which also has the memory timings.
[https://manpages.debian.org/buster/i2c-tools/decode-dimms.1.en.html](url)

I couldn't find a better code example than this one.
[https://github.com/xabar/spd_utils](url)

And here is some background information.
[https://damieng.com/blog/2020/02/08/ddr4-ram-spd-linux](url)

I always run xmrig with 'sudo xmrig' because of the WSMR writes so then it should be possible to read this data also? Or doesn it work that way?

**Comment by xmrig** [comment]
Thank you for links especially last one. I going to implement DMI/SMBIOS reader first, at least it is most portable solution, without timings but better than nothing. `sudo xmrig` is fine.

**Comment by Spudz76** [comment]
Oh right, RandomX uses large dataset, guess it would matter then.  Used to thinking CN where everything is cache and system ram doesn't matter.

Come to think of it adding a second DIMM to some rigs recently and updating from 1066 to 1333 did make their RX work better.

**Comment by Spudz76** [comment]
libsensors should be able to pick up the SPD info
bonus maybe the miner could show CPU therms and stuff similar to how it does on GPUs...

**Comment by xmrig** [comment]
Implemented in dev branch.
Thank you.

**Comment by BillGatesIII** [comment]
> Implemented in dev branch.
> Thank you.

Looks great, thank you.
