### ISSUE TITLE
NVML disabled (failed to load NVML)

### ISSUE THREAD

**Issue by spitrip82** [xmrig/xmrig#2044]
some one can help on this issue ? i am using win10 and i have install CUDA Toolkit 11.2
![Capturar](https://user-images.githubusercontent.com/76714275/104831464-17e76c00-5881-11eb-8684-b5ed2cea5bd0.PNG)

**Comment by xmrig** [comment]
This error does not affect mining speed (using GPU for RandomX is not the best idea though), but without NVML information about GPU health (clocks, power, temps, fans) is not available. Can you try to find nvml.dll or your C: drive?
Thank you.

**Comment by spitrip82** [comment]
yes I managed to locate
![2](https://user-images.githubusercontent.com/76714275/104832076-3b60e580-5886-11eb-9f58-1c489473eb6d.PNG)

**Comment by xmrig** [comment]
I unable to reproduce this issue, on almost same software/hardware configuration it just works https://i.imgur.com/qr4Fk8f.png
Thank you.

**Comment by spitrip82** [comment]
problem fixed ! 
solution : "cuda": { "enabled": false, "loader": null, "nvml": true, "cn/0": false, "cn-lite/0": false

**Comment by Pafolo** [comment]
For anyone that has this issue and is still trying to figure it out search your pc for the nvml.dll file and copy paste that file into your folder with the xmrig.exe
