### ISSUE TITLE
<AstroBWT_Dero::hash>:188 "an illegal memory access was encountered"

### ISSUE THREAD

**Issue by M4shy** [xmrig/xmrig#2045]
This following error is happening,
**'thread #0 failed with error <AstroBWT_Dero::hash>:188 "an illegal memory access was encountered"'**

It occcurs when i'm simply moving the command prompt window to my second display (dual screen), this happens when i'm slightly overclocking my video card as well. 

I'm working with a thunderbolt/eGPU and Nvidia CUDA 11.1 dsiplay drivers.
Here is my command line : **xmrig.exe -a astrobwt --no-cpu --cuda -o DOMAIN:PORT -u WALLET -p w=123 -k**

**Comment by Spudz76** [comment]
What GPU though

**Comment by M4shy** [comment]
It's an Asus GTX 970

**Comment by M4shy** [comment]
Any flag to set in case of debug from command line ?

**Comment by M4shy** [comment]
Issue not resolved
