### ISSUE TITLE
Thread #0 failed with error

### ISSUE THREAD

**Issue by Pafolo** [xmrig/xmrig#2046]
I was having issues with it not loading nvml but got that figured out and assumed that issue was what was causing me to have this error pop up.

**"thread #0 failed with error <RandomX_Monero::hash>:37 "no kernel image is available for execution on the device"**

Anyone know how to resolve this?

![Capture](https://user-images.githubusercontent.com/70542624/104851621-c6a89e00-58bb-11eb-93dc-a1163dd898c4.JPG)

**Comment by SChernykh** [comment]
You could try CUDA 8 plugin `xmrig-cuda-6.5.0-cuda8-win64.zip`. I don't think GTX-660 supports all CUDA 11 features when you start RandomX mining with CUDA 11 plugin.

**Comment by Pafolo** [comment]
I tried cuda 8 and got a different error, tried cuda 9 and it worked. I'm able to go all the way up to 10.2. One issue I have is it doesn't display the GPU wattage.

Do all GPUs get this poor performance? Is there something I can change to make it better? HWinfo says I'm at 100% load.

Also can the temp be changed from C to F?
![Capture](https://user-images.githubusercontent.com/70542624/104855592-3fffbb00-58d3-11eb-8bf7-1546cb879f74.JPG)

**Comment by SChernykh** [comment]
RandomX is designed to be slow on GPUs (basically slow on anything that isn't a CPU) and it uses 2 GB dataset which is more memory than GTX 660 has. So it's very slow.

**Comment by Pafolo** [comment]
The gtx660 is a 2GB card. Am I looking at the wrong info?

**Comment by SChernykh** [comment]
You can't allocate all 2 GB with CUDA and dataset is actually 2080 MB which is more than 2 GB. Also you need a number of 2 MB scratchpads to calculate hashes (320 scratchpads x 2 MB = 640 MB on your screenshot), so 2 GB cards can only run with dataset in system memory which is very slow.

**Comment by Pafolo** [comment]
Does this apply to ALL GPUs or just nvidia models?
If I was to use a 8gb card would I be limited to the same processing power?

**Comment by SChernykh** [comment]
All GPUs are bad at RandomX. You can go to https://whattomine.com/ and see where RandomX is on the list for any GPU.

**Comment by Pafolo** [comment]
Whats the difference between huge-pages and huge-pages-jit? I have them both enabled along with memory pool. I'm just not sure what they do.

**Comment by Spudz76** [comment]
That original error simply means the cuda-plugin was not compiled with "arch 30" code.  It is impossible with CUDA newer than when they dropped arch30.  Build your own CUDA plugin, using the latest CUDA Toolkit that still supported arch30.  And I would run the LTS nvidia-390 branch not the newer drivers (no point, on old cards).

MoneroOcean lets you mine algos that are good for GPU, but always pays out XMR as if you had been mining RX/0
This way you can run a CPU-only miner which mines what it is good at, and a separate CUDA-only miner that does what it's good at, and then the pool pays out autochanged coin in XMR regardless.  I catch 15.8KH of RX/0 equivalence mining KawPow on Vega64's.  I never bothered benchmarking RX/0 directly but it's definitely nowhere near 15.8KH...
