### ISSUE TITLE
xmrig is not taking all available threads on GPU. Debian 10

### ISSUE THREAD

**Issue by arrdguez** [xmrig/xmrig#2048]
Hi!

I am testing the xmrig on my Laptop: Debian 10 with a Nvidia GTX 1050. Xmrig is running OK with both CPU and GPU. The problem is that the GPU is taking only one thread of 36 ... see the picture below. 
There is no way in --help so see a possible solution. 

I am using this command line:
./xmrig  --cuda -o pool.minexmr.com:443 -u <XMRADDRES>  -p WORKERNAME  -k --tls

I am using CPU and GPU at the same time for this example but I tried using only the GPU.
I share a picture just to help to help me.

All the best ...

![Screenshot_2021-01-19_20-21-34](https://user-images.githubusercontent.com/12154883/105118531-3cfff880-5a94-11eb-8441-d4850d4da2f9.png)

**Comment by snipeTR** [comment]
Please use config wizard.

**Comment by Lonnegan** [comment]
Don't mine Monero with a GPU. RandomX is ja pure CPU algo, GPUs do very bad on RandomX. Mine something with you GPU, which is made for GPUs like ETH, Haven or Ravencoin.

**Comment by SChernykh** [comment]
GPU mining uses 1 CPU thread, that's correct. You can see Intensity = 320 (GPU threads) which is also correct for GTX 1050.

**Comment by Spudz76** [comment]
As the CPU does no "work" in close involvement with the GPU it only needs one thread, for communications.
The CPU simply double-checks the result the GPU sent back after sending it a job, which does not need additional threading.
There are a whole bunch of threads (warps) happening on the GPU.  Think of the single CPU thread handling the GPU as a network connection, nothing more.
