### ISSUE TITLE
Bake options into binary

### ISSUE THREAD

**Issue by pamlloyd** [xmrig/xmrig#2053]
Not really an issue, just a question.  I have a set of options, such as coin, tls, log-file, etc, that I use across my machines.  I was wondering if there is a way I can "bake" them into the compiled binary instead of using a config file or additional command line options.  I just want to run it as  is: ./xmrig

Thanks, 
Pam

**Comment by snipeTR** [comment]
https://github.com/xmrig/xmrig/blob/master/src/core/config/Config_default.h

**Comment by pamlloyd** [comment]
Thanks, I altered the values in the Config_default.h and rebuilt, but it was still asking for the a config file.  :(

./xmrig
[2021-01-21 15:44:39.834] unable to open "/tmp/config.json".
[2021-01-21 15:44:39.835] unable to open "/home/lloyd/.xmrig.json".
[2021-01-21 15:44:39.835] unable to open "/home/lloyd/.config/xmrig.json".
[2021-01-21 15:44:39.835] no valid configuration found, try https://xmrig.com/wizard

**Comment by snipeTR** [comment]
#957

**Comment by pamlloyd** [comment]
Thanks snipeTR!  Just needed to added -DWITH_EMBEDDED_CONFIG=ON after editing Config_default.h
