### ISSUE TITLE
Mac OSX error

### ISSUE THREAD

**Issue by dhan000** [xmrig/xmrig#206]
Mac OSX error
Mac OSX 10.11.6

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/asd/Downloads/xmrig-2.4.2 2/xmrig (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/asd/Downloads/xmrig-2.4.2 2/xmrig (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by xmrig** [comment]
For macOS please use [Homebrew](http://www.brewformulas.org/Xmrig) to install.
Thank you.

**Comment by dhan000** [comment]
thank you.
