### ISSUE TITLE
v6.7.2 stopped working right after the launch of v6.8.0

### ISSUE THREAD

**Issue by matheusbach** [xmrig/xmrig#2062]
Software was running normally before the update. Right after the release of the new version, when closing and reopening XMRig it displays the error read error: "end of file"

Screenshot:
![xmrig-v6 7 2-error](https://user-images.githubusercontent.com/35426162/105841005-b32fbe00-5fb2-11eb-8eeb-a1f0588bfba4.png)

My Config File:
[config.json](https://github.com/xmrig/xmrig/files/5873067/config.json.txt)

Tested with the same configuration file model on several computers and all presented the same error

**Comment by matheusbach** [comment]
I tested dozens of combinations of settings in my configuration file and found that the error happens at line  ``"url": "xmr-us-west1.nanopool.org:14433",`` of my config.json file. It always worked using the ``xmr-us-west1.nanopool.org:14433`` url, but now it is no longer working, but using the XMRig donation url ``donate.v2.xmrig.com:3333`` it works.

**Comment by xmrig** [comment]
Seems this issue with nanopool and at least `xmr-us-east1.nanopool.org:14433` works. This is not related to the miner.
Thank you.

**Comment by matheusbach** [comment]
Very thanks. Sorry for the mistake caused by the coincidence of the facts. Working now

**Comment by FibreFoX** [comment]
Using `Stratum Port` (14444) instead of `SSL/TLS Port` (14433) works fine, maybe something wrong with the TLS/SSL of nanopool. Had the same problem, but got this working without secure connection.
