### ISSUE TITLE
Compile Error with -DWITH_ARGON2=OFF

### ISSUE THREAD

**Issue by johanneshahn** [xmrig/xmrig#2065]
If you compile with Option "-DWITH_ARGON2=OFF" i got following error:

`/src/core/config/ConfigTransform.cpp:153:55: error: no member named 'kArgon2Impl' in 'xmrig::CpuConfig'`

there is simple missing a "ifdef XMRIG_ALGO_ARGON2" around the code lines

```
#   ifdef XMRIG_ALGO_ARGON2
    case IConfig::Argon2ImplKey: /* --argon2-impl */
        return set(doc, CpuConfig::kField, CpuConfig::kArgon2Impl, arg);
#   endif
```

**Comment by SChernykh** [comment]
That option is really off only when you also use `-DWITH_RANDOMX=OFF` because RandomX uses Argon2 for dataset initialization. I checked with just `-DWITH_ARGON2=OFF` and it compiles fine because RandomX enables it back again.

**Comment by SChernykh** [comment]
Should be fixed in https://github.com/xmrig/xmrig/pull/2067
