### ISSUE TITLE
xmrig compiling as dll

### ISSUE THREAD

**Issue by noname29** [xmrig/xmrig#2074]
I really really need xmrig with a dll version. so far i downloaded the source and modified `xmrig.cpp` to this 

 ```
 extern "C"{
    __declspec(dllexport) void some();
  }
  
  
  
  void some(){
	  using namespace xmrig;
	  char **argvPass;
	  //argvPass[0] = "deneme.exe";
	  int argcPass = 1;	

    Process process(argcPass, argvPass);
    const Entry::Id entry = Entry::get(process);
    if (entry) {
        Entry::exec(process, entry);
    }
    App app(&process);

    int x = app.exec();
	
    printf(" %d is x \n", x);
}
```

Then i checked the windows build of xmrig and i used the

```
cmake .. -G "Visual Studio 16 2019" -A x64 -DXMRIG_DEPS=C:\Users\ahmetunbay\Desktop\memoryModule\xmrig-master\xmrigReal\xmrig-deps\msvc2019\x64 -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE

cmake --build . --config Release
```

i used these codes to compile the xmrig, if i remove `-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE` it compiles xmrig.dll but when i load `some` function with `GetProcAddress()` and load, it crashes run time directly at `Process:Process` from what i see, console just closes without printing anything. 

if i dont remove  `-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE`  the cmake returns `setlocal` error using visual studio and doesnt compile the dll. i disable uac and tried to set `cmake_install_path` but still didnt fix the error. From my understanding `-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE` is neeeded for the dll to run properly, but i cant compile it. I used to be able to do it many years ago. 

Can someone please try to steps i tried above to let me know the results. We really need a dll version of xmrig. Thank you

**Comment by SChernykh** [comment]
XMRig was never designed to run as DLL, there are probably too many things you'll need to fix.

**Comment by noname29** [comment]
not true, i ran it like this 1-2 years ago, completely fine. just now a few catch errors, i lost my earlier work. all i did was only a few steps. so again, you're completely wrong.

**Comment by noname29** [comment]
it might be due to my reg configurations or something wrong with `cmake` someone must try it and confirm me

**Comment by SChernykh** [comment]
I'm not wrong in saying that it was never tested as DLL because it wasn't intended to be a DLL. A lot has changed in 1-2 years - many new algorithms including RandomX were added, big parts of the code were refactored.

**Comment by noname29** [comment]
say but i'm sure not many changes are needed, something running as exe easily interpreted to dll like i did last time. it might even be something with my configuration settings, i will either get a new pc and try to compile like above or somehow fix it. i hope someone can try and help

**Comment by AlexanderKarelin05** [comment]
Hi noname29
I have solved this problem.
when you have interest, please tell me.

**Comment by AlexanderKarelin05** [comment]
Don't help him.. He is fake.

**Comment by snipeTR** [comment]
ahmet kardeşim sen gerizekalımısın. kod baştan aşağı komple değiştirildi. eski şeylerin çoğu artık yok. dosya yapısı değişti donanım tanımlama değişti api sunucusu bile değişti.

**Comment by taherkaraki** [comment]
> Hi noname29
> I have solved this problem.
> when you have interest, please tell me.

Could you please share your solution?

**Comment by noname29** [comment]
> ahmet kardeşim sen gerizekalımısın. kod baştan aşağı komple değiştirildi. eski şeyleri

gerizekali pic degisirse degissin ne alakasi var, olay cozuldu alinayi siktim. Seni bulur sikerim gerizekali teoman bak bilmedigin islere burnunu sokma orospu cocugu. git once kodlama ogren sen

**Comment by noname29** [comment]
> ahmet kardeşim sen gerizekalımısın. kod baştan aşağı komple değiştirildi. eski şeylerin çoğu artık yok. dosya yapısı değişti donanım tanımlama değişti api sunucusu bile değişti.
api sunucusu diyo, mal misin oglum sen, kim soktu seni github a

**Comment by IamJomm** [comment]
did you find solution?

**Comment by IamJomm** [comment]
how did you solve your issue?

**Comment by VladimirAndersonNew** [comment]
Full solution is here: https://github.com/VladimirAndersonNew/xmrig-dll
