### ISSUE TITLE
Termux support not available or removed.

### ISSUE THREAD

**Issue by Surajkumarsaw1** [xmrig/xmrig#2079]
[ 76%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/common/VirtualMemory_unix.cpp.o
/data/data/com.termux/files/home/xmrig/src/crypto/common/VirtualMemory_unix.cpp:153:124: error: use of undeclared identifier 'hugePagesFlag'
        mem = mmap(0, align(size), PROT_READ | PROT_WRITE | SECURE_PROT_EXEC, MAP_PRIVATE | MAP_ANONYMOUS | MAP_POPULATE | hugePagesFlag(hugePageSize()), -1, 0);

     ^
/data/data/com.termux/files/home/xmrig/src/crypto/common/VirtualMemory_unix.cpp:173:114: error: use of undeclared identifier 'hugePagesFlag'
    void *mem = mmap(0, size, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_HUGETLB | MAP_POPULATE | hugePagesFlag(hugePageSize()), 0, 0);

                                                      ^
2 errors generated.

**Comment by SChernykh** [comment]
Can you try https://github.com/xmrig/xmrig/pull/2080 ?

**Comment by SChernykh** [comment]
I've just checked and #2080 fixed it for me.

**Comment by Surajkumarsaw1** [comment]
No it gives same error.

**Comment by SChernykh** [comment]
I repeat - I had the same compile error in Termux and it fixed the error. Try the latest dev branch now.

**Comment by Surajkumarsaw1** [comment]
I have xmrig build for termux arm aarch64 in my [repository xmrig](https://github.com/Surajkumarsaw1/xmrig.git)

**Comment by dimonDDL** [comment]
As @SChernykh said I just copied the new VirtualMemory_unix.cpp file in to my failed build and tried again. After that it finished without a problem.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v6.8.2
