### ISSUE TITLE
Hi/problem

### ISSUE THREAD

**Issue by xxlxxlxxl** [xmrig/xmrig#208]
hi, i open xmrig.exe
and it appear a error that says no login/password provided, i also provide a login password, but also says there is no wallet specified
can you help ?

**Comment by xmrig** [comment]
Add your wallet and optional on most pools password, to your config.json file.
Thank you.

**Comment by xxlxxlxxl** [comment]
{
    "algo": "cryptonight",
    "av": 0,
    "background": false,
    "colors": true,
    "cpu-affinity": null,
    "cpu-priority": null,
    "donate-level": 5,
    "log-file": null,
    "max-cpu-usage": 1000000,
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "safe": false,
    "syslog": false,
    "threads": null,
    "pools": [
        {
            "url": "pool.minemonero.pro:5555",
            "user": "wallet adress*",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        }
    ]
}



i make config like this is it ok?

and after how much hours payment are credited in my wallet?
