### ISSUE TITLE
KawPow failed to initialize DAG

### ISSUE THREAD

**Issue by M4shy** [xmrig/xmrig#2088]
I'm having this kind of problem with a GTX 780 (3GB) and setted my virtual memory like : GPU mem size * number of GPU. Am i right ?

Here the logs,
KawPow light cache for epoch 215 calculated (8488ms)
KawPow failed to initialize DAG: <kawpow_prepare>:62 "out of memory"

Anyone ?

**Comment by SChernykh** [comment]
@M4shy KawPow DAG size is 2.7 GB now, it's not enough memory on a 3 GB card if you're running Windows 10. Try Windows 7 or Linux, they leave more GPU memory available for mining.

**Comment by M4shy** [comment]
Thanks for reply. I've using linux distros as server, my gnome desktop stills somewhere on a older laptop... I didn't know for the memory size. What do you mean by leaving more GPU memory ? With win10, I've tested a min and a max pagefile size [3000, 5000] (mb), the err remains the same.

**Comment by SChernykh** [comment]
NVIDIA drivers on Windows 10 reserve 20% of GPU memory so you only have 2.4 GB available on a 3 GB GPU.

**Comment by M4shy** [comment]
Doh!
