### ISSUE TITLE
C API

### ISSUE THREAD

**Issue by alanhoff** [xmrig/xmrig#209]
Hello there, I had this crazy idea about building a software that uses user's idle CPU to mine Monero for charity. For that I would need a C API so I could easily use it as a library into another program. Do you know if that's possible?

Cheers!

**Comment by xmrig** [comment]
It possible, but I don't sure how high level shoud be library API.
For example, load config, start mine, maybe pause/resume, etc.
Thank you.

**Comment by alanhoff** [comment]
An external function for configurating, starting, pausing and resuming looks like all I need :-)
