### ISSUE TITLE
Task Manager doens't show RAM used for xmrig 

### ISSUE THREAD

**Issue by moneroist** [xmrig/xmrig#2092]
I have just downloaded and tested newest xmrig and I realized that my task manager doesn't show RAM usage for xmrig process, it shows just 10MB but mining is working with this same hashrate like on xmrig 6.5.3, 6.5.3 version normally shows RAM usage in Task Manager

**Comment by SChernykh** [comment]
Windows task manager doesn't show huge pages allocations for some reason. If you run xmrig without huge pages it'll show more than 2 GB used.
