### ISSUE TITLE
Mac GPU Death!

### ISSUE THREAD

**Issue by UEFI-code** [xmrig/xmrig#2093]
I had mining on Mac Pro and iMac Pro with Opencl  options, then cause macOS crash!
How can we fix it?

**Comment by ScardracS** [comment]
Did you mine RandomX? It is not profitable with OpenCL

**Comment by UEFI-code** [comment]
So how can I mine on the Mac Pro with GPU?

**Comment by ScardracS** [comment]
If you are going to mine with integrated GPU I personally don't think it's a good idea because iGPUs aren't enought powerful.

**Comment by agentpatience** [comment]
What is the point of mining on a MacBook 💻 it will be slow and can cause damage.

**Comment by UEFI-code** [comment]
So the AMD Vega series GPU in the iMac/Mac Pro are not suitable for mining XMR?
How about the new M1 chip, the CPU can got hash rate at 2100KH/s, and GPU not work

**Comment by UEFI-code** [comment]
> What is the point of mining on a MacBook 💻 it will be slow and can cause damage.
> […](#)
> Sent from my iPhone
> On Feb 11, 2021, at 9:40 PM, UEFI-code ***@***.***> wrote: ﻿ So how can I mine on the Mac Pro with GPU? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I'm not mining on a 💻, but on a 🖥 and Mac Pro "Server", so I think it's have a expensive GPU, may get much hash rate

**Comment by Spudz76** [comment]
You can mine Cryptonight-Heavy types or some other Cryptonights that are still profitable.

RandomX of any type will never work fast on GPU by design (it is a CPU only algorithm).  Even latest GPU.

Find pool that pays XMR for other types of work if you want to earn XMR from GPU power.
