### ISSUE TITLE
msr: Write to unrecognized MSR 0xc0011020 by xmrig (AMD Ryzen 5 - 4600H)

### ISSUE THREAD

**Issue by Bogdan107** [xmrig/xmrig#2098]
This is message in my syslog:
```msr: Write to unrecognized MSR 0xc0011020 by xmrig (pid: 68425). Please report to x86@kernel.org.```

$ uname -p
```AMD Ryzen 5 4600H with Radeon Graphics```
$ uname -r
```5.10.15-gentoo-x86_64```

Some messages from xmrig:
```
* ABOUT        XMRig/6.8.1 gcc/10.2.0
* LIBS         libuv/1.40.0 OpenSSL/1.1.1i hwloc/2.4.0
* CPU          AMD Ryzen 5 4600H with Radeon Graphics (1) 64-bit AES
               L2:3.0 MB L3:8.0 MB 6C/12T NUMA:1
* MOTHERBOARD  HP - 87B1
* ASSEMBLY     auto:ryzen
cpu      use argon2 implementation AVX2
msr      register values for "ryzen_17h" preset have been set successfully (21 ms)
 ```

May be this report will help.

**Comment by coolhaircut** [comment]
The linux kernel is disabling userspace writes to MSR in version 5.9 :(

For now, you should be able to fix this by adding `msr.allow_writes=on` to the kernel cmdline (`GRUB_CMDLINE_LINUX` variable in `/etc/default/grub')
