### ISSUE TITLE
Jason Error need help please.

### ISSUE THREAD

**Issue by Talos11** [xmrig/xmrig#2102]
Hrello,
I need help with this error. 
![XMR_ERROR](https://user-images.githubusercontent.com/32502521/107870740-53616000-6e58-11eb-9a1e-e01d780271b0.PNG)
I do not know why this has happened, it happened all of a sudden.  I did just upgrade my internet but don't think that has anything to do with it but i could be wrong.  It was mining fine after the install.  I am at a loss.  Please someone help.
Thank you

**Comment by snipeTR** [comment]
https://xmrig.com/wizard

**Comment by xmrig** [comment]
Please make sure you enable tls. If it is enabled but still not working, try another port, for example 9000. Likely your ISP somehow affected traffic between the miner and pool.
Page https://pool.supportxmr.com/ should show text `Mining Pool Online` after you allow insecure TLS connection in your browser.
Thank you.

**Comment by Talos11** [comment]
Thank you for responding so quickly.  Well it seems it was the tls setting.  Very strange, I didn’t change anything but the modem.  I upgraded to 80Mbps from 20.  Would changing the modem and upgrading be the cause of this?  That was the only thing that changed.  I didn’t change anything in my .bat file.  I have now added the tls setting and it works.  Just really odd that it worked after my service was installed but then just decided to not.
Thanks again for helping me out.  I have to say that over the years of mining I have met some good people and projects, and XMR and the XMRING TEAM are among the nicest and coolest people.
Thanks again,
Dan  :0)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Talos11** [comment]
Need help again.  So after I go and do the setup wizard all is good.  I can mine with no problem.  However after I shut the miner down and try to restart it it will not work and I get the same error message.  I am at my wits end.  I can not figure out what is going on here.  It must be something in my modem.  Are there settings in the modem that I need to change?
Dan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Spudz76** [comment]
The pool is sending garbage, or unrecognized fields.  Pool communication is JSON-RPC therefore this JSON parse error has nothing to do with the JSON config file, but what is coming from the pool packets.

You can switch to non-SSL and tcpdump the pool traffic to see what garbage it's sending - OR - recompile with debugging enabled to dump the packets inside the xmrig (you can't sniff SSL traffic).

Ask pool support why their JSON is invalid.
