### ISSUE TITLE
Feature request: miner should pause on activity

### ISSUE THREAD

**Issue by Del4ev** [xmrig/xmrig#2103]
Hi, thanks for your work! 
Is it possible to implement feature like --pause-on-activity
I am use my computer for work and for mining. It would be great, if no mouse move longer than 3 min (timeout can be configurabled)  start mining.
If I'm work with my PC, miner will pause. Other way, if I'm not at the computer, miner will work.   

I know about option "pause-on-battery", so half of feature code already implemented.

**Comment by SChernykh** [comment]
#2104

**Comment by Del4ev** [comment]
Huge Thanks! 

I have test it, work like a charm!  Hope it gets into the master branch

**Comment by Lonnegan** [comment]
Thanks for that feature!
