### ISSUE TITLE
To Access MSR Registers Admin Rights Required From Where?

### ISSUE THREAD

**Issue by imshaniqbal** [xmrig/xmrig#2105]
I'm using Hash Miner and I'm new to this.. I just simply want to increase the Hashrate so

I'm using Windows 10 64BIT Latest Version, 

CPU: Core i5 10400
Ram: 16GB 2666
MotherBoard: MSI B460 Mag Wifi
**GPU: not using I will add later just mining on cpu...** 

Now if anyone can tell me how to add MSR registers admin rights?

or should I start Quick Miner from Hash

**Comment by ScardracS** [comment]
Run it as administrator, reboot (this will enable HUGE PAGES) and then run every time as administrator: this will set MSR automatically.

**Comment by mcg0** [comment]
I've tried to run as administrator and even activated the administrator account to install and run on Win10 Home, but still getting: 
failed to start WinRing0 driver, error 183
FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW
Is there something else I'm missing?

**Comment by SChernykh** [comment]
Error 183 means you run some other software that uses WinRing0 driver - something like hardware monitor or RGB control software. Try to close it. If it doesn't help, uninstall it.

**Comment by CarveTechElect** [comment]
...well for me, I closed the xmrig running process, then simply right click on the icon I placed on the desktop, then clicked on 'run as administrator'. xmrig process restarted and msr was granted successfully
