### ISSUE TITLE
XMrig 6.8.1 with Nicehash gets "failed to allocate RandomX dataset, switch to slow mode"

### ISSUE THREAD

**Issue by D0nVitalio** [xmrig/xmrig#2106]
Hi.
**Describe the bug**
When Nicehash running and mining, I start XMrig 6.8.1 and get lower hashrate and get "failed to allocate RandomX dataset, switch to slow mode". Get 129H/s when both running and 500+H/s (without "failed to allocate..") when only XMrig running. Huge pages enabled.

**Required data**
 - OS: Win10x64, 1909.
 - For GPU related issues: rx460 4gb, driver ver.21.1.1. Nicehash uses ~75% of vram. Total ram 8gb, CPU Q9450.

Is it possible to run XMrig and Nicehash without getting slow mode?

**Comment by ScardracS** [comment]
Have you tried to move to 6.8.2?

**Comment by D0nVitalio** [comment]
> Have you tried to move to 6.8.2?

Yes, just now and it is "failed"

**Comment by SChernykh** [comment]
Reboot and try to start XMRig first, before Nicehash.

**Comment by D0nVitalio** [comment]
> Reboot and try to start XMRig first, before Nicehash.

This was first what I did. NBMiner crashes

**Comment by D0nVitalio** [comment]
Just tried on Win7 - works good without fails.
This issue can be closed.
Thanks

**Comment by D0nVitalio** [comment]
+
