### ISSUE TITLE
[SUGGESTION] Add support for dinamically chage which threads are working

### ISSUE THREAD

**Issue by ScardracS** [xmrig/xmrig#2109]
As in title, I think using same threads/cores all the time would damage CPU/s faster than changing dinamically them.

My original idea was based on changing it every tot time, but then I have thinkd it would be better to change on every new work, in order to maintain threads occupied for the time needed on complete a work.

Do you think this could be a good idea?

**Comment by Spudz76** [comment]
Silicon does not wear from usage.

If anything, moving the hot spot (active cores) around the die would damage it faster than constant heat in the same place due to thermal cycling.
