### ISSUE TITLE
credits

### ISSUE THREAD

**Issue by xxlxxlxxl** [xmrig/xmrig#211]
{
"algo": "cryptonight",
"av": 0,
"background": false,
"colors": true,
"cpu-affinity": null,
"cpu-priority": null,
"donate-level": 5,
"log-file": null,
"max-cpu-usage": 1000000,
"print-time": 60,
"retries": 5,
"retry-pause": 5,
"safe": false,
"syslog": false,
"threads": null,
"pools": [
{
"url": "pool.minemonero.pro:5555",
"user": "wallet adress*",
"pass": "x",
"keepalive": true,
"nicehash": false
}
]
}

i make config like this is it ok?

and after how much hours payment are credited in my wallet?

**Comment by xmrig** [comment]
Check answers in #160 issue.
Thank you.

**Comment by xxlxxlxxl** [comment]
I want to know if the i put the wallet correctly?

**Comment by xmrig** [comment]
`"user": "wallet adress*",`
Yep.

**Comment by xxlxxlxxl** [comment]
Also please last question, how do i check my total mining balance and limit of mining to withdraw?

**Comment by xmrig** [comment]
So If you use pool.minemonero.pro open https://monero.hashvault.pro/en/#!/dashboard and enter your wallet address in `Track Live Stats` block. Withdraw limit is 0.3 XMR.

**Comment by xxlxxlxxl** [comment]
Total Due
0.0057123778 XMR

this is total mining till now
correct?

**Comment by xmrig** [comment]
Yep

**Comment by xxlxxlxxl** [comment]
@xmrig , please i want to know
maxcpu usage = 75
is this maximum usage of cpu
or 50% usage?

**Comment by xmrig** [comment]
Your CPU usage limited by L3 cache.
