### ISSUE TITLE
[Idea] Add 1% donation to Monero Core Team general fund for MRL

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [xmrig/xmrig#2113]
Idea to add a 1% donation to the Monero Core Team general fund that can be optionally increased through config or removed by changing the source code.

At current issuance rates and Monero prices, this is approximately $650,000 / year if the total Monero hashrate donated. Even with lower % hashrate commitment, this is enough to fund the Monero Research Lab. Some MRL full-timers express significant stress in opening a CCS for donations every several months. This donation would give the MRL full-timers the fund cushion they need to feel job-secure while also dispersing the costs widely and optionally.

**Comment by Spudz76** [comment]
Why didn't they invest in coins and make a few million to cover this? :)

**Comment by SChernykh** [comment]
This smells too much "devtax" for me, I don't want to hear accusations of "Monero is a devtax coin now" everywhere. It's better to keep XMRig and Monero core devs separate. If anything, this def fund donation should be integrated in monerod mining.

**Comment by SamsungGalaxyPlayer** [comment]
> This smells too much "devtax" for me, I don't want to hear accusations of "Monero is a devtax coin now" everywhere. It's better to keep XMRig and Monero core devs separate. If anything, this dev fund donation should be integrated in monerod mining.

I understand your concerns, but I don't see it this way personally. People can always yank it out in the source code, or use different mining software (eg: monerod). The only way a "dev tax" could be enforced is through a consensus change (not gonna happen). Some mining pools donate a portion of their income to the general fund, but no one reasonably believes that Monero has a "dev tax" as a result.

**Comment by SChernykh** [comment]
It's not my concerns, but I can already imagine how you-know-who will spin this. Maybe if it's opt-in instead of opt-out it could work.

**Comment by Virepri** [comment]
Alternate suggestion: Perhaps allow users to specify whether they want to donate to xmrig or the core team general fund?

**Comment by benhall847** [comment]
lol "wont fix"

cool bro

The alternative suggestion was perfect...

idk why xmrig wouldnt want to support XMR ...
better xmr = more users = more xmrig miners... so stupid lmao

add the option to opt-in to donating.

**Comment by snipeTR** [comment]
The project is open source, you can create a fork and add it and create your own miner however you want. You cannot criticize the developers for not making changes to their projects.
