### ISSUE TITLE
I have two AMD Epyc CPU each has 32 core, total 64 core ,but only used 32 core

### ISSUE THREAD

**Issue by toplinuxsir** [xmrig/xmrig#2119]
I have two AMD Epyc CPU each has 32 core, total 64 core ,but only used 32 core
How to use all the 64 core to mine ?
Thanks!

**Comment by ScardracS** [comment]
Add -t 64 on your line of code (if you have them on the same motherboard)

**Comment by Lonnegan** [comment]
Which Epyc model? Which coin?

**Comment by toplinuxsir** [comment]
@ScardracS  , add -t 64 It doese not work !
@Lonnegan.  AMD EPYC 7502P 32-Core

**Comment by ScardracS** [comment]
> @ScardracS , add -t 64 It doese not work !
> @Lonnegan. AMD EPYC 7502P 32-Core

What it said?

**Comment by Lonnegan** [comment]
-t is deprecated. You have to edit the config.json file.

Eypc 7502P has 128 MB L3 cache and therefor enough cache for 64 RandonX threads (2 MB scratchpad per thread). If you mine RandomX (e.g. Monero) your EPYC should run with 64 threads automatically.

Unless you mine a CN-heavy coin like Haven. CN-Heavy has 4 MB scratchpads per thread. Here Epyc 7502P can only start 32 threads without flooding the cache!

**Comment by toplinuxsir** [comment]
@Lonnegan I mine Monero ， But only one CPU (32 core) used, how to configure

**Comment by SChernykh** [comment]
Use https://xmrig.com/wizard to create minimal config and XMRig will automatically generate optimal config out of it when it starts.

**Comment by Lonnegan** [comment]
@toplinuxsir The Epyc 7502P is a single socket CPU. You can't use it in a dual socket system! The suffix P stands for single socket. If you want to use two you have to drop in 2x Epyc 7502 w/o suffix P.

**Comment by toplinuxsir** [comment]
@Lonnegan  Thanks , I got it!

**Comment by toplinuxsir** [comment]
@Lonnegan I have another question : I have Epyc 7502p CPU , but the hashrate only： 
![image](https://user-images.githubusercontent.com/1111353/109573206-8af32c00-7b29-11eb-836b-c315cd9f9c4a.png)
，
But the randomx benchmark(https://xmrig.com/benchmark) hashrate is : 26698.21, Huge difference 
What's the problem ? Thanks

**Comment by Lonnegan** [comment]
@toplinuxsir Can you post the whole window, including the initial lines at the beginning? :)

**Comment by toplinuxsir** [comment]
@Lonnegan 
![image](https://user-images.githubusercontent.com/1111353/109576651-2509a300-7b2f-11eb-9edc-a419fd548171.png)

**Comment by Lonnegan** [comment]
@toplinuxsir You are not mining RandomX algo (Monero), you are mining Cryptonight-Heavy (Haven). Here for the 
32C cpu EPYC 7502P the hashrate ~2300 H/s is quite normal :)

**Comment by toplinuxsir** [comment]
@Lonnegan  How to mining RandomX algo ?  how to configure ? Thanks !

**Comment by xmrig** [comment]
I guess the answer to your last question is more simple than disable donation and you can figure it out by yourself. 10 days ago it was already said that you might mine wrong algorithm.
Thank you.
