### ISSUE TITLE
NVIDIA CARD NOT WORKING

### ISSUE THREAD

**Issue by aamir0000** [xmrig/xmrig#2120]
Hello;

I am mining TURTLE coin through XMRig 6.6.1.  My Nvidia graphic card is not supporting during mining. I have configure every thing as per information available. But it shows **nvidia: disable (no suitable configuration found)**. Please see attachment
![Untitled](https://user-images.githubusercontent.com/75328147/108624836-266d0880-7469-11eb-9edd-6aea82f3078f.jpg)

My configuration is also attached
![Untitled 1](https://user-images.githubusercontent.com/75328147/108624845-3be23280-7469-11eb-9faa-e06a49ebf44e.jpg)

If I use YouTube than Nvidia card works properly. It is not working with XMRig.

Kindly support me. Thanks

**Comment by SChernykh** [comment]
argon2/chukwav2 mining is supported only for CPU.

**Comment by aamir0000** [comment]
If it so than why they have mentioned nvidia mining on website
![Untitled 2](https://user-images.githubusercontent.com/75328147/108625263-c1ff7880-746b-11eb-88b6-88e2ca6f23aa.jpg)

**Comment by SChernykh** [comment]
It's probably from the time when Turtlecoin used Cryptonight.

**Comment by aamir0000** [comment]
OK Thanks for your feedback and support.
