### ISSUE TITLE
Error : regex_error

### ISSUE THREAD

**Issue by xguya** [xmrig/xmrig#2123]
**Describe the bug**
when I run ./xmrig  I get this error: what():  regex_error

**To Reproduce**
yum install -y git make cmake gcc gcc-c++ libstdc++-static libuv-static hwloc-devel openssl-devel
git clone https://github.com/xmrig/xmrig.git
mkdir xmrig/build && cd xmrig/build
cmake ..
make -j$(nproc) 

**Required data**
Error: 
./xmrig 
 * ABOUT        XMRig/6.9.0 gcc/4.8.5
 * LIBS         libuv/1.40.0 OpenSSL/1.0.2k hwloc/1.11.8
 * HUGE PAGES   supported
 * 1GB PAGES    unavailable
 * CPU          Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (1) 64-bit AES
                L2:1.0 MB L3:8.0 MB 4C/8T NUMA:1
 * MEMORY       15.2/15.5 GB (98%)
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error

OS - CentOS Linux release 7.9.2009 (Core) 
Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
NO GPU 

Default config.json (added just my ewallet)

**Comment by xguya** [comment]
solved with: Static, CPU only https://xmrig.com/download

**Comment by guoshuaifeng** [comment]
But i need to build from source,How to solve it ?

**Comment by xmrig** [comment]
gcc 4.8 has bad incomplete c++ regex support as a temporary solution you can disable DMI support by using `-DWITH_DMI=OFF` CMake option.
Thank you.

**Comment by xmrig** [comment]
Fixed in dev branch.
