### ISSUE TITLE
make command issues on ubuntu

### ISSUE THREAD

**Issue by fgsoftware1** [xmrig/xmrig#2124]
Building C object src/3rdparty/libethash/CMakeFiles/ethash.dir/ethash_internal.c.o
cc: error: unrecognized command line option '-maes'; did you mean '-mapcs'?
src/3rdparty/libethash/CMakeFiles/ethash.dir/build.make:62: recipe for target 'src/3rdparty/libethash/CMakeFiles/ethash.dir/ethash_internal.c.o' failed
make[2]: *** [src/3rdparty/libethash/CMakeFiles/ethash.dir/ethash_internal.c.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'src/3rdparty/libethash/CMakeFiles/ethash.dir/all' failed
make[1]: *** [src/3rdparty/libethash/CMakeFiles/ethash.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fgsoftware1** [comment]
> Building C object src/3rdparty/libethash/CMakeFiles/ethash.dir/ethash_internal.c.o
> cc: error: unrecognized command line option '-maes'; did you mean '-mapcs'?
> src/3rdparty/libethash/CMakeFiles/ethash.dir/build.make:62: recipe for target 'src/3rdparty/libethash/CMakeFiles/ethash.dir/ethash_internal.c.o' failed
> make[2]: *** [src/3rdparty/libethash/CMakeFiles/ethash.dir/ethash_internal.c.o] Error 1
> CMakeFiles/Makefile2:178: recipe for target 'src/3rdparty/libethash/CMakeFiles/ethash.dir/all' failed
> make[1]: *** [src/3rdparty/libethash/CMakeFiles/ethash.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

I resolved this issue.
the issue is the flag -maes this flag need remove on arm devices

**Comment by Mertenrobson** [comment]
Linking C static library libethash.a
Error running link command: No such file or directory
make[2]: *** [src/3rdparty/libethash/CMakeFiles/ethash.dir/build.make:114: src/3rdparty/libethash/libethash.a] Error 2
make[1]: *** [CMakeFiles/Makefile2:171: src/3rdparty/libethash/CMakeFiles/ethash.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
