### ISSUE TITLE
-maes flag need remova on arm devices

### ISSUE THREAD

**Issue by fgsoftware1** [xmrig/xmrig#2125]
**Describe the bug**
make command fails due to flag -maes flag -maes is only supported by x86

**To Reproduce**
run make on arm devices

**Expected behavior**

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: ubuntu
 - For GPU related issues: information about GPUs and driver version.

**Additional context**

error: unrecognized command line option '-maes'; did you mean '-mapcs'?
src/3rdparty/argon2/CMakeFiles/argon2.dir/build.make:62: recipe for target 'src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/argon2.c.o' failed
make[2]: *** [src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/argon2.c.o] Error 1
CMakeFiles/Makefile2:123: recipe for target 'src/3rdparty/argon2/CMakeFiles/argon2.dir/all' failed
make[1]: *** [src/3rdparty/argon2/CMakeFiles/argon2.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by SChernykh** [comment]
XMRig compiles fine on all my ARM devices. Note that you need to compile it for ARMv8 or ARMv7l and use recent GCC/clang compiler.

**Comment by SChernykh** [comment]
ARMv6 and older architectures are not supported.

**Comment by fgsoftware1** [comment]
I try build on armv8l

**Comment by SChernykh** [comment]
-maes flag is not used on armv8/armv7, see https://github.com/xmrig/xmrig/blob/master/cmake/flags.cmake#L25
Maybe your cmake doesn't work properly.

**Comment by fgsoftware1** [comment]
> -maes flag is not used on armv8/armv7, see https://github.com/xmrig/xmrig/blob/master/cmake/flags.cmake#L25
> Maybe your cmake doesn't work properly.

src/3rdparty/argon2/CMakeFiles/argon2.dir/build.make:62

Makefile:83: recipe for target 'all' failed
