### ISSUE TITLE
Xmrig Miners Receive 50 New Jobs In 1 Minute Multiple Times Per day

### ISSUE THREAD

**Issue by downystreet** [xmrig/xmrig#2127]
xmrig version: 6.8.2 & 6.9.0

I'm mining to the monero daemon in my own network through the xmrig proxy. I created a log file on 2 different machines and noticed that several times per day they are receiving mass amounts of jobs in the span of a minute. For example I counted over 50 new jobs in the span of a minute for one instance. Every instance occurs at the same time on both machines. I'm not sure if this issue was addressed with the recent update but I wanted to point it out. Here is a picture of the log file.

Update: also occurs on version 6.9.0

![proxy5](https://user-images.githubusercontent.com/63488055/108811143-b484e400-757a-11eb-8377-30bd5799e82d.png)

**Comment by alanhasgari** [comment]
I'm getting the same mining to minexmr pool... It's been present in the last couple releases, for sure... Have to close xmrig and start again to correct the behavior...

**Comment by venze** [comment]
Hey, what pool is this and how is your config file set up? Thanks!

**Comment by alanhasgari** [comment]
> Hey, what pool is this and how is your config file set up? Thanks!

OP said they're mining to monerod, I'm mining to minexmr pool.
I've experienced this one 3 of my 5 rigs... It's most noticable on my i5 and Ryzen5 rigs...

You'll see in my screenshots the sharp peaks followed by sharp drops; the issue corrects itself when I close and restart xmrig. As I mentioned, it's been happening the last 2 or 3 releases. I did not have this issue previously...

![Screenshot_20210223-215815](https://user-images.githubusercontent.com/5217983/108940985-45fb6100-7622-11eb-9ed9-1d5421a0f457.png)
![Screenshot_20210223-215824](https://user-images.githubusercontent.com/5217983/108940996-498ee800-7622-11eb-9bab-8e7b58b40e68.png)

**Comment by Lonnegan** [comment]
@alanhasgari Are you sure you have the same problem as @downystreet ? Can you see the jobs coming quickly in the xmrig window? Otherwise it could be the Windows 10 v1903+ scheduler problem, as well:
https://github.com/xmrig/xmrig/issues/1506#issuecomment-609043467

**Comment by alanhasgari** [comment]
> @alanhasgari Are you sure you have the same problem as @downystreet ? Can you see the jobs coming quickly in the xmrig window? Otherwise the frequently droping hashrates could be the Windows 10 v1903+ scheduler problem, as well:
> #1506

The cause may be different, but the description is very much the same. It'll mine fine for awhile, then the jobs switch so rapidly that it doesn't submit a share, then it'll submit several share when the height changes, then repeats until I close xmrig and relaunch it.

**Comment by snipeTR** [comment]
it looked like the wrong "difficulty calculation" to me.

**Comment by 2010phenix** [comment]
it can be wrong auto detect option, old(CN R) one before RandomX... same problem I see in proxy (drop hashrate x4 - x5)

**Comment by downystreet** [comment]
I just checked the logs again. The mass of new jobs corresponds to the proxy giving the connection error: connect error: "connection timed out", #000 no active pools, stop ,connect error: "connection timed out". So when the proxy is giving the connect error the miners are getting lots of new jobs for the same block. I submitted the connection issue in #2118.

**Comment by alanhasgari** [comment]
My ryzen system freaked out again. I switched to to idleminer, which calls xmrig to mine when idle... The method works great on my Xeon which is only a part time miner, but we will see if this solves my problem...

**Comment by snipeTR** [comment]
![Adsız](https://user-images.githubusercontent.com/31975916/159523610-58cfd243-b8ff-4def-90e5-2f9ab54fd8cb.png)

same problem.

**Comment by SChernykh** [comment]
This is how Dero mining works, these are real new jobs.

**Comment by snipeTR** [comment]
is there a way to turn off this new jobs message?  such as the -silent command.  or like pressing the g key on the keyboard :)
