### ISSUE TITLE
Help best configuration

### ISSUE THREAD

**Issue by gorunks2001** [xmrig/xmrig#2132]
Hi, we have 3 machines with 2x Xeon E5-2640 v2 @ 2ghz 64bit
L2 0.5MB  L3 40MB
256gb ram each

We have 3 virtual machines Linux Ubuntu, one for each machine

Could you help us for the best setting for mining?

actually we use this string:
sudo ./xmrig/build/xmrig -o pool.minexmr.com:443 -u OurWallet -k --hugepage-size=1000000 --cpu-no-yield --tls --rig-id Ale1

thanks

**Comment by gorunks2001** [comment]
we just installed ubuntu in the phisical machine... but when we start xmrig it use only 16 threads instead 32.  and have an hashrate of 5000

how we can increase it?

thanks

**Comment by SChernykh** [comment]
> only 16 threads instead 32

This is correct for this CPU. Your hashrate is also correct, see benchmark for a single CPU system: https://xmrig.com/benchmark/3rNuVu

**Comment by gorunks2001** [comment]
> > only 16 threads instead 32
> 
> This is correct for this CPU. Your hashrate is also correct, see benchmark for a single CPU system: https://xmrig.com/benchmark/3rNuVu

thanks for the answer, is there a way for use all the 32 threads?

thanks

**Comment by SChernykh** [comment]
Yes, but 32 threads will be slower. Add `-t 32` to the command line.

**Comment by gorunks2001** [comment]
oh ok, so in 5300 is the max hash for this machine .
thanks
