### ISSUE TITLE
I want to use my raspberry pi but can not build success

### ISSUE THREAD

**Issue by GouMingAnKang** [xmrig/xmrig#2137]
## Device
Raspberry Pi 4B
## OS
Cent OS 8 stream
## Matters
Some packages cant be found before i build
Do you consider publish a linux-arm64 version?

**Comment by Gray-Zero** [comment]
follow this guide [https://blog.ijasoneverett.com/2020/08/cpu-mining-on-a-raspberry-pi/](url) that is what i did to get it on my pi

**Comment by grahamreeds** [comment]
I had it working a while back with just raspberry os, no dspawn needed.

However something has changed and the latest version no longer compiles on Pi4.

I suspect the sse2neon update Tobe the culprit.
