### ISSUE TITLE
CentOS6,How to build from source ?

### ISSUE THREAD

**Issue by guoshuaifeng** [xmrig/xmrig#2138]
My OS is CentOS6.9,then how to build from source ?
Thanks!

**Comment by xmrig** [comment]
Minimum supported CentOS for compile from source is 7 and it is already too old. For this OS you can use [official static build](https://github.com/xmrig/xmrig/releases/download/v6.9.0/xmrig-6.9.0-linux-static-x64.tar.gz)  or build static executable on [Alpine](https://xmrig.com/docs/miner/build/alpine).
Thank you.
