### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by gtimeg77** [xmrig/xmrig#214]
i this supposed to auto run/use when miner run from command line?
none of my settings are working

**Comment by xmrig** [comment]
* Without options miner looking for config file near executable.
* You can specify path to config file via command line option `-c, --config=FILE`.
* Config file is not mandatory, all configuration can be done only by command line options.

**Comment by gtimeg77** [comment]
have tried via command always errors. need max cpu reduced cant figure it out'
