### ISSUE TITLE
Compiling error on arm

### ISSUE THREAD

**Issue by entick** [xmrig/xmrig#215]
[  2%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
cc: error: unrecognized command line option ‘-maes’
src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/build.make:62: recipe for target 'src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o' failed
make[2]: *** [src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/all' failed
make[1]: *** [src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Raspberry pi 2 m. B, Raspbian os, gcc7.

**Comment by xmrig** [comment]
Please use arm branch, ARM support currently not merged into master branch. Also please check issue #94 for more details.
Thank you.

**Comment by entick** [comment]
When im trying to clone arm branche, i get the same err. In the proposed issue, I could not find a solution

**Comment by gennadicho** [comment]
@entick you not switch to the arm. Do "git clone https://github.com/xmrig/xmrig ; cd xmrig ; git fetch origin arm ; git checkout arm ; cmake . ; make" and all be ok.

**Comment by xmrig** [comment]
Merge this issue with #216
