### ISSUE TITLE
Question: Is there Anyway of Making the rig-id in config_default.h a random number

### ISSUE THREAD

**Issue by sapmi** [xmrig/xmrig#2155]
I guess the parameters here are in a JSON format, similar to the normal config file. When running xmrig with command line parameters I used --rig-id %uname% no problem - which contains a string and a random number. 

I tried changing the parameter to %random% which is an environmental variable in windows, but the exe file will not run. If I put it in quotes within the parameters - it lists my rig ID as just %random% - 

"rig-id": %random%,   - program won't run
"rig-id": "%random%"   - rig ID is not a random number - its just random

Maybe a clue to solving this is, when I look at  Config_platform.h, I see this: { "rig-id",  1, nullptr, IConfig::RigIdKey   },

Any ideas? I am now completely stuck

**Comment by xmrig** [comment]
For config file you should use different syntax https://xmrig.com/docs/miner/environment-variables for example `"rig-id": "${random}"`.
Thank you.

**Comment by sapmi** [comment]
Hello XMRIG, sorry for not saying thank you, had computer issues. So thank you!!!!!!
