### ISSUE TITLE
out of memory,being killed

### ISSUE THREAD

**Issue by johnrosen1** [xmrig/xmrig#2160]
**Describe the bug**

linux machine 2c 4g

when xmrig starts

it is then being killed by the kernal

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

run normally

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: [e.g. Windows]
 - For GPU related issues: information about GPUs and driver version.

linux debian 10

**Additional context**

**Comment by johnrosen1** [comment]
1gb page related,turn off .

**Comment by sodo100** [comment]
Thanks for all of you !
