### ISSUE TITLE
can't build file

### ISSUE THREAD

**Issue by cytogon** [xmrig/xmrig#2167]
I have multiple programs saying that .h files are missing. Is this not a complete source code?

**Comment by Spudz76** [comment]
What error messages?  yes it's complete source I build it multiple times a week

**Comment by alehti** [comment]
That was my bad. I didn't download the dependencies on this computer. However, now CMAKE is giving me issues. I have updated the path files. I can run CMAKE to compile other programs. It will not work for XMRIG though. I keep getting "No CMAKE_CXX_COMPILER could be found"

**Comment by alehti** [comment]
A way around it was opening the CMAKELISTS with Visual Studio, and it finds the CXX compiler, but then I get the error "is not able to compile a simple test program" which is weird because it compiles everything else just fine. Just wondering if you ran into anything of the sort and if you had a solution.

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/build/windows

**Comment by alehti** [comment]
yes, that's the one giving me errors. I am reinstalling VS right now to see if there was an issue with the installation.

**Comment by alehti** [comment]
reinstalling fixed the issue

**Comment by alehti** [comment]
A question though. I built Kawpow, but it only shows me its dependencies like Ethash and Keccak. I guess I am a bit confused as I am not familiar with Kawpow. I am trying to study the algorithm. Can you tell me which file is used to start the Kawpow algorithm, and what main function is called?

**Comment by alehti** [comment]
Found it. I didn't realize it built multiple projects. My bad. I am a java/PHP programmer. Just learning C++ lol

**Comment by browolf** [comment]
I've got that error  "No CMAKE_CXX_COMPILER could be found"  using msys.

**Comment by browolf** [comment]
> I've got that error "No CMAKE_CXX_COMPILER could be found" using msys.

Figured out this happens from just running msys2 exe. 

whereas it works if you run the mingw64 shell which is either a shortcut in the start menu or 
\msys64\msys2_shell.cmd -mingw64

**Comment by Spudz76** [comment]
Note KawPow does not actually mine in the CPU miner, it is only there to be able to verify results from GPU backends and avoid sending invalids to the pool.
