### ISSUE TITLE
DNS error: "unknown node or service"

### ISSUE THREAD

**Issue by sunk818** [xmrig/xmrig#217]
Ran into this error after I power cycled my router. Is there a way for xmrig to recover more gracefully when there is a DNS error?

```
[2017-11-22 20:01:22] speed 2.5s/60s/15m n/a n/a 151.0 H/s max: 152.7 H/s
[2017-11-22 20:01:25] [pool.xxxx.com:3333] DNS error: "unknown node or service"
[2017-11-22 20:01:31] [pool.xxxx.com:3333] DNS error: "unknown node or service"
[2017-11-22 20:01:36] [pool.xxxx.com:3333] DNS error: "unknown node or service"
```

**Comment by gennadicho** [comment]
Soo. May you write ip and domain into /etc/hosts directly? But is a dumb way. Just try to set up normal DNS-server on your router. Or you talking about xmrig not accepted dns-record on-the-air while it change?

**Comment by xmrig** [comment]
Yep, unclear issue, something wrong with router? or the miner.
Need more details what DNS server used, buildin in router or some externals and other network tools is working or not, eg ping.

Also possible add feature to cache last successful ip address set and reuse it if get DNS errors.
Thank you.

**Comment by sunk818** [comment]
Yes, I could put a hosts entry. It'd be nice if DNS fails, xmrig tries to renegotiate address again. I have wireless connection to router if it matters. DNS I use is whatever the router provides and not direct to a public DNS like 8.8.8.8 (Google Public DNS).

**Comment by sunk818** [comment]
So any update to this? Will xmrig renegotiate connection again? I prefer your product over xmr-stak and donate 1%

**Comment by xmrig** [comment]
Probably will be added to v2.6.
Thank you.

**Comment by lucasff** [comment]
I'm having this problem now :(

**Comment by CistelicanCatalin** [comment]
Same problem

**Comment by HankFit247** [comment]
Starting to have this same issue on one of my miners, Windows 10 Pro XMRig v6.3.3.  

Happens after about 4-6 hours of mining.  Need to pay attention to the logs to get a better idea...

Changes I have made so far:
- I have both Google DNS Servers programmed into my miners IP Stack.  After a couple of days, I added my ISP (Comcast) to the stack for a total of 4 now.
- Better, not creating the DNS Error as often.  I was away at work for over 9 Hours today, and was still up and running.  Then about an hour later I got it.

- I just changed my DNS in my Router from "Get from ISP" to specifying them directly.

Network:
Netgear CAX80
Comcast over 300MB down

**Comment by HankFit247** [comment]
Unfortuneatly this issue has returned.

**Comment by HankFit247** [comment]
Issue has returned.  :(
v6.3.3

**Comment by HankFit247** [comment]
I found that Betterhash, which was also mining XMR via CPU on two of my Windows 10 Pro rigs was causing the issue.

Removed BETTER_TRASH lol, issue resolved!

**Comment by jishnunand** [comment]
I am having this issue again :(

**Comment by pedroplanet** [comment]
The same here,    xmrpool.eu:443 DNS error: "unknown node or service"
tried all the ports 3333 9999 etc

**Comment by SChernykh** [comment]
> The same here, xmrpool.eu:443 DNS error: "unknown node or service" tried all the ports 3333 9999 etc

Try different DNS server (8.8.8.8 and 8.8.4.4 for example). Your ISP is most likely blocking xmrpool.eu.

**Comment by HankFit247** [comment]
Run as Administrator

**Comment by pedroplanet** [comment]
> > The same here, xmrpool.eu:443 DNS error: "unknown node or service" tried all the ports 3333 9999 etc
> 
> Try different DNS server (8.8.8.8 and 8.8.4.4 for example). Your ISP is most likely blocking xmrpool.eu.

Yes, my ISP is blocking xmrpool. I've changed the DNS sever on the ISP router, now the blocked sites work on my browsers, but xmrig is still giving error.
