### ISSUE TITLE
(not bug) Please add aarch64 on ubuntu for L4T and rpi

### ISSUE THREAD

**Issue by leonpano2006** [xmrig/xmrig#2173]
**Describe the bug**
(Not bug)
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: [e.g. Windows]
 - For GPU related issues: information about GPUs and driver version.

**Additional context**
Please add aarch64 on ubuntu for L4T and rpi

**Comment by benthetechguy** [comment]
You can easily compile xmrig for aarch64, and I've done so on both my raspberry pi 4 and my nintendo switch (L4T). I don't believe xmrig will be compiled for aarch64 on every release because of the low demand.

**Comment by leonpano2006** [comment]
> You can easily compile xmrig for aarch64, and I've done so on both my raspberry pi 4 and my nintendo switch (L4T). I don't believe xmrig will be compiled for aarch64 on every release because of the low demand.

I don't have switch 
L4T for jetson nano or jetson Xavier nx or agx

**Comment by benthetechguy** [comment]
xmrig compiled for aarch64 works on any aarch64 device, so I don't know exactly what you mean.
If you're talking about cuda compatibility, I don't know if xmrig's cuda module will build for arm, but I can try.

**Comment by leonpano2006** [comment]
yes about cuda compatibility 
can you test please

**Comment by benthetechguy** [comment]
I have compiled xmrig for aarch64 with CUDA for you [here](https://github.com/xmrig/xmrig/files/6138232/xmrig-6.10.0-linux-cuda10_2-arm64.tar.gz). Keep in mind that you can always compile this for yourself, it's not very hard. I doubt that xmrig aarch64 cuda will be included in every release because of the low demand, and the dev might not even have an arm machine with an nvidia gpu to compile it with as they are not very common.

**Comment by leonpano2006** [comment]
> I have compiled xmrig for aarch64 with CUDA for you [here](https://github.com/xmrig/xmrig/files/6138232/xmrig-6.10.0-linux-cuda10_2-arm64.tar.gz). Keep in mind that you can always compile this for yourself, it's not very hard. I doubt that xmrig aarch64 cuda will be included in every release because of the low demand, and the dev might not even have an arm machine with an nvidia gpu to compile it with as they are not very common.

Link says something is wrung

**Comment by leonpano2006** [comment]
> I have compiled xmrig for aarch64 with CUDA for you [here](https://github.com/xmrig/xmrig/files/6138232/xmrig-6.10.0-linux-cuda10_2-arm64.tar.gz). Keep in mind that you can always compile this for yourself, it's not very hard. I doubt that xmrig aarch64 cuda will be included in every release because of the low demand, and the dev might not even have an arm machine with an nvidia gpu to compile it with as they are not very common.

Thank you very much
I have no clue to edit source code
Again thank you a lot

**Comment by benthetechguy** [comment]
You don't need to edit any source code, just follow the [compilation instructions](https://xmrig.com/docs/miner/build/ubuntu), very simple.

**Comment by benthetechguy** [comment]
@xmrig safe to close this probably

**Comment by leonpano2006** [comment]
> @xmrig safe to close this probably

Closed
