### ISSUE TITLE
AMD Radeon RX 640

### ISSUE THREAD

**Issue by patrick101010** [xmrig/xmrig#2174]
Have a AMD Radeon RX640. Try to run Minergate, but only get a "not Available GPU" 

Any advice or help ?

Thanks in advance.

**Comment by Virepri** [comment]
Hey there, Patrick!

I wouldn't recommend trying to mine XMR on your GPU. It's not exactly profitable, and the RandomX algorithm is optimized for CPUs. You'd be best off mining against GPU pools that can pay in XMR.

Even the best GPUs offer a mere fraction of what a good CPU can pull (but that's the intent, to strive for 1 CPU = 1 vote).
