### ISSUE TITLE
XMRig fails to compile on armv7 on three different distros

### ISSUE THREAD

**Issue by benthetechguy** [xmrig/xmrig#2175]
**Describe the bug**
XMRig fails to compile on armv7 on ubuntu, raspbian, and arch.

**To Reproduce**
Attempt to compile XMRig with static dependencies (dependencies build fine)

**Expected behavior**
XMRig successfully compiles.

**Required data**
An excerpt of the compilation output. The full output is [attached](https://github.com/xmrig/xmrig/files/6127649/compilation-output.txt).
```
In file included from /home/ben/xmrig/src/crypto/cn/soft_aes.h:31,
                 from /home/ben/xmrig/src/crypto/cn/CryptoNight_arm.h:35,
                 from /home/ben/xmrig/src/crypto/cn/CnHash.cpp:35:
/home/ben/xmrig/src/crypto/cn/sse2neon.h: In function 'uint8x16x4_t _sse2neon_vld1q_u8_x4(const uint8_t*)':
/home/ben/xmrig/src/crypto/cn/sse2neon.h:362:12: error: 'vld1q_u8_x4' was not declared in this scope; did you mean 'vld1q_u64'?
  362 |     return vld1q_u8_x4(p);
      |            ^~~~~~~~~~~
      |            vld1q_u64
```

**Additional context**
I attempted to compile XMRig on a raspberry pi 4 with armv7 (I know it supports aarch64 but i'm compiling for other devices) and on three different distros it has failed, with the same error. Note that I compiled the depends statically (the depends compiled just fine and this error looks like it's unrelated to that).

**Comment by SChernykh** [comment]
Try to use newer GCC version (GCC 10 at least).

**Comment by benthetechguy** [comment]
I compiled using GCC 10.2

**Comment by SChernykh** [comment]
I see the problem now, will submit a PR that fixes it soon.

**Comment by benthetechguy** [comment]
Cool, when I get back to my PC i'll try to compile and see what happens.

**Comment by benthetechguy** [comment]
Update: The build went successfully. Thanks for the quick response and pull request.
