### ISSUE TITLE
Please provide a helm chart

### ISSUE THREAD

**Issue by vanthome** [xmrig/xmrig#2176]
Please provide a helm chart for xmrig, ideally with a diversity rule so that tow instances are not started on the same machine.

**Comment by Lonnegan** [comment]
Why not? I'm mining Monero with the CPU and Haven with the GPU. Therefore I have to start two instances of xmrig.

**Comment by vanthome** [comment]
Good point in that case it should be configurable. The point is, if I just start a certain number of replicas (let's say for just CPU mining), K8s will have no problem scheduling them on the same machine, which is ofc not desirable. there are primitives in K8s however to control this. It must just be exposed through the helm chart.

**Comment by SChernykh** [comment]
XMRig doesn't provide Kubernetes container images in releases, so there is no point to ask anything related.

**Comment by vanthome** [comment]
Good point but then they should do that, given that they are paid for this, I think it's fair to ask for it.
