### ISSUE TITLE
i am getting connection error when opening miner. I have pinged the servers and that is ok so must be my config? I am quite new to this mining software so I am running out of ideas and my research is not finding any help

### ISSUE THREAD

**Issue by mnm279** [xmrig/xmrig#2180]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: [e.g. Windows]
 - For GPU related issues: information about GPUs and driver version.

**Additional context**

**Comment by mnm279** [comment]
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "colors": true,
    "title": true,
    "randomx": {
        "init": -1,
        "init-avx2": -1,
        "mode": "auto",
        "1gb-pages": false,
        "rdmsr": true,
        "wrmsr": true,
        "cache_qos": false,
        "numa": true,
        "scratchpad_prefetch_mode": 1
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "huge-pages-jit": false,
        "hw-aes": null,
        "priority": null,
        "memory-pool": false,
        "yield": true,
        "asm": true,
        "argon2-impl": null,
        "astrobwt-max-size": 550,
        "astrobwt-avx2": false,
        "argon2": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "astrobwt": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "cn": [
            [1, 0],
            [1, 1],
            [1, 2],
            [1, 3],
            [1, 4],
            [1, 5],
            [1, 6],
            [1, 7],
            [1, 8],
            [1, 9],
            [1, 10],
            [1, 11],
            [1, 12],
            [1, 13],
            [1, 14],
            [1, 15]
        ],
        "cn-heavy": [
            [1, 0],
            [1, 2],
            [1, 4],
            [1, 6],
            [1, 8],
            [1, 10],
            [1, 12],
            [1, 14]
        ],
        "cn-lite": [
            [1, 0],
            [1, 1],
            [1, 2],
            [1, 3],
            [1, 4],
            [1, 5],
            [1, 6],
            [1, 7],
            [1, 8],
            [1, 9],
            [1, 10],
            [1, 11],
            [1, 12],
            [1, 13],
            [1, 14],
            [1, 15]
        ],
        "cn-pico": [
            [2, 0],
            [2, 1],
            [2, 2],
            [2, 3],
            [2, 4],
            [2, 5],
            [2, 6],
            [2, 7],
            [2, 8],
            [2, 9],
            [2, 10],
            [2, 11],
            [2, 12],
            [2, 13],
            [2, 14],
            [2, 15]
        ],
        "rx": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "rx/wow": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        "cn/0": false,
        "cn-lite/0": false,
        "rx/arq": "rx/wow",
        "rx/keva": "rx/wow"
    },
    "opencl": {
        "enabled": false,
        "cache": true,
        "loader": null,
        "platform": "AMD",
        "adl": true
    },
    "cuda": {
        "enabled": false,
        "loader": null,
        "nvml": true
    },
    "log-file": null,
    "donate-level": 1,
    "donate-over-proxy": 1,
    "pools": [
        {
            "algo": null,
            "coin": null,
            "url": "xmrpool.eu:9999",
            "user": "84WDVV2QmeU1A1gjdFtVdjYZZGqoUB89wCVrTyptAfbwgrayvw6vuUoE4NwxrvbTzsaT8J41d1H1gdFBTV5E7vGM8ujo9CG",
            "pass": null,
            "rig-id": null,
            "nicehash": false,
            "keepalive": true,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false,
            "socks5": null,
            "self-select": null,
            "submit-to-origin": false
        }
    ],
    "retries": 5,
    "retry-pause": 5,
    "print-time": 60,
    "health-print-time": 60,
    "dmi": true,
    "syslog": false,
    "tls": {
        "enabled": false,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "verbose": 0,
    "watch": true,
    "pause-on-battery": false,
    "pause-on-active": false
}

**Comment by mnm279** [comment]
that is my config.json

**Comment by mnm279** [comment]
os is windows 10 64 bit

![image](https://user-images.githubusercontent.com/72933544/111027715-dd65ff80-83e9-11eb-9203-7aa9df0d6506.png)

**Comment by SChernykh** [comment]
> Port: 9999
 Starting Difficulty: 50000
 Description: SSL for Claymore > 9.7

Why are you trying to connect to Claymore-specific port with XMRig? Use port 7777

**Comment by mnm279** [comment]
do you mean "url" xmrpoll.eu:9999 to 7777? sorry i am vew to this. it was working yesterday

**Comment by mnm279** [comment]
*new

**Comment by xmrig** [comment]
It is a network issue, try open http://xmrpool.eu:9999/ and https://xmrpool.eu:9999/ in your browser, if it also timeouts, nothing can be done on the miner side.
Thank you.

**Comment by mnm279** [comment]
i have four other miners running fine but when i click your links the message reads :"the server xmrpool.eu:9999 is online but is not responding to connection requests." so does that mean my config is ok and there is an issue that cannot be resolved as there is some other issue out of my control?

**Comment by mnm279** [comment]
rigs running xmr through hiveos seem unaffected. they are running great

**Comment by mnm279** [comment]
so its not something on my end as everything has been reset and re-configured. is xmrpool.eu having some issues?

**Comment by mnm279** [comment]
ok so i cant even view my xmrpool.eu wallet earnings either. so the pool must have an issue with something.

**Comment by mnm279** [comment]
authenticity of data could not be verified. and that is on tor browser. it does not matter how i try to connect with anything. it just wont connect on web or in miner but i can ping them

**Comment by mnm279** [comment]
all miners now down. you seem to have a big problem at the moment. ill watch pool status pages and wait. thamks for your earlier help. I now know I have not done anything wrong in config at least. hope it is sorted soon.

**Comment by Lonnegan** [comment]
xmrpool.eu doesn't support algo auto detection. You have to change

"coin": null,

to

"coin": "monero",

in your config file.

But appart from that, something seems to be wrong with that pool atm:

![xmrpool](https://user-images.githubusercontent.com/60088495/111053658-dbda1d00-8465-11eb-8ca3-e96844a000f2.png)

**Comment by DeeDeeRanged** [comment]
xmrpool.eu does support algo auto automatically see my start line:
sudo ./xmrig --api-worker-id dranged --http-enabled -o xmrpool.eu:9999 -u whatever -k --tls
