### ISSUE TITLE
EulerOS How to use it 

### ISSUE THREAD

**Issue by oneoy** [xmrig/xmrig#2186]
user@r90yglzvzkh-machine:~$ cat /etc/os-release 
NAME="EulerOS"
VERSION="2.0 (SP8)"
ID="euleros"
ID_LIKE="rhel fedora centos"
VERSION_ID="2.0"
PRETTY_NAME="EulerOS 2.0 (SP8)"
ANSI_COLOR="0;31"

**Comment by oneoy** [comment]
bash: ./xmrig: cannot execute binary file: Exec format error

**Comment by Lonnegan** [comment]
Typ uname -a into your console to check which kernel you are running. And then double check if you downloaded the right version of xmrig for your system. EulerOS is just a variant of CentOS which is a variant of Red Hat Linux. So it should work if you've chosen the right binary :)
