### ISSUE TITLE
Help to disable visibility of embedded config data file in Hex Editor or viewer

### ISSUE THREAD

**Issue by hirdeshsaxena** [xmrig/xmrig#2187]
my embedded config file data is being displayer/viewed in hex editor and viewer how to disable the visibility 

Image attached

![img](https://user-images.githubusercontent.com/24962418/111377648-21f9d100-865e-11eb-8f83-f5d789a09ffa.jpg)

**Comment by timk74** [comment]
UPX

**Comment by hirdeshsaxena** [comment]
what upx?

**Comment by timk74** [comment]
https://github.com/upx/upx
