### ISSUE TITLE
Help with multi core

### ISSUE THREAD

**Issue by yanke1311** [xmrig/xmrig#2197]
**Describe the bug**
I set max-threads-hint = 100
and my machine has two cpu-core
but I found that when binary is running , it can only run with one cpu

**Expected behavior**
I need it run with all two cores

**Required data**
 - OS: centos 8

**Additional context**
![图片](https://user-images.githubusercontent.com/23717792/111891677-930b0100-8a2f-11eb-8978-9f59c27b28c2.png)
pic below is total usage, only 50%:
![图片](https://user-images.githubusercontent.com/23717792/111891707-c3eb3600-8a2f-11eb-8f3a-c2f22dbe7e42.png)

**Comment by SChernykh** [comment]
Most likely your CPU doesn't have enough cache to run 2 mining threads. Also, your machine has less than 2 GB RAM, it can't run RandomX at full speed. Read https://xmrig.com/docs/miner/randomx-optimization-guide for more information.
