### ISSUE TITLE
issue after build macOS BigSur MBP 16" (AMD 5500m)

### ISSUE THREAD

**Issue by AmroJaber** [xmrig/xmrig#2198]
**Describe the bug**

Steps to reproduce the behavior.
- building successfully but the "xmrig" can't compile GPU!

 - Miner log as text or screenshot
![Screen Shot 2021-03-21 at 5 51 44 PM](https://user-images.githubusercontent.com/931567/111914939-c0ca6700-8a7c-11eb-9146-d49f74bc5b2a.png)

 - Config file or command line (without wallets)
 - without config file

 - OS: 
 - MacOS Big Sur (lasted Version)

 - For GPU related issues: information about GPUs and driver version:
-AMD Redoen Pro 5500M 4GB

**Comment by SChernykh** [comment]
If you google `cvms_element_build_from_source` you'll see it has been a common problem with MacOS OpenCL for a long time, not only with XMRig. OpenCL support is very bad on MacOS.

**Comment by A-M-j** [comment]
> If you google `cvms_element_build_from_source` you'll see it has been a common problem with MacOS OpenCL for a long time, not only with XMRig. OpenCL support is very bad on MacOS.

but Ethminer working well!

**Comment by SChernykh** [comment]
ETH is a different algorithm with different code, also you gave a link to CUDA version, how does it work on your AMD GPU?

**Comment by A-M-j** [comment]
> ETH is a different algorithm with different code, also you gave a link to CUDA version, how does it work on your AMD GPU?

>Ethereum miner with OpenCL, CUDA and stratum support

look: https://github.com/ethereum-mining/ethminer

**Comment by SChernykh** [comment]
ETH is not Kawpow though, Kawpow is much more complex. MacOS OpenCL driver is unreliable and can fail at compiling different code. There error it printed (`cvms_element_build_from_source`) is a bug in driver, not a problem with the source code.

**Comment by AmroJaber** [comment]
no, I don't think the bug in the `OpenCL` driver, see this article shows how error after building `Xmrig` and how has fix print the GPU devices:

https://s4m0ht.medium.com/how-to-mine-monero-on-your-macbook-and-tweak-the-source-code-although-you-shouldnt-8d57d966ac26

**Comment by SChernykh** [comment]
The error described in that article is totally unrelated.
