### ISSUE TITLE
Only recognize 1 CPU in my 2 physical CPU machine?

### ISSUE THREAD

**Issue by kaiwu-astro** [xmrig/xmrig#2201]
My machine has 2 Physical Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz, which has 24 cores x 2 = 48 cores

https://xmrig.com/benchmark?cpu=Intel%28R%29+Xeon%28R%29+CPU+E5-2678+v3+%40+2.50GHz

when I press h during mining, it seems the program just recognize 24 cores, which is 1 CPU

![2021-03-23 2 17 35](https://user-images.githubusercontent.com/18334656/112102249-f1c4ac00-8be2-11eb-879d-231ab6bda0a7.png)

htops shows half cores are not working

![2021-03-23 2 22 31](https://user-images.githubusercontent.com/18334656/112102434-38b2a180-8be3-11eb-9127-2cbda8c6f52d.png)

At the beginning the program said

![2021-03-23 2 18 22](https://user-images.githubusercontent.com/18334656/112102286-fbe6aa80-8be2-11eb-84de-8a5217d51459.png)

I run it in Ubuntu 16.04, **with sudo**, and this is my profile

```
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "colors": true,
    "title": true,
    "randomx": {
        "init": -1,
        "init-avx2": -1,
        "mode": "auto",
        "1gb-pages": true,
        "rdmsr": true,
        "wrmsr": true,
        "cache_qos": false,
        "numa": true,
        "scratchpad_prefetch_mode": 1
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "huge-pages-jit": false,
        "hw-aes": null,
        "priority": null,
        "memory-pool": false,
        "yield": true,
        "max-threads-hint": 48,
        "asm": true,
        "argon2-impl": null,
        "astrobwt-max-size": 550,
        "astrobwt-avx2": false,
        "cn/0": false,
        "cn-lite/0": false
    },
    "opencl": {
        "enabled": false,
        "cache": true,
        "loader": null,
        "platform": "AMD",
        "adl": true,
        "cn/0": false,
        "cn-lite/0": false
    },
    "cuda": {
        "enabled": false,
        "loader": null,
        "nvml": true,
        "cn/0": false,
        "cn-lite/0": false
    },
    "donate-level": 1,
    "donate-over-proxy": 1,
    "log-file": null,
    "pools": [
        {
            "algo": null,
            "coin": null,
            "url": "donate.v2.xmrig.com:3333",
            "user": "YOUR_WALLET_ADDRESS",
            "pass": "x",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false,
            "socks5": null,
            "self-select": null,
            "submit-to-origin": false
        }
    ],
    "print-time": 60,
    "health-print-time": 60,
    "dmi": true,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "tls": {
        "enabled": false,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "verbose": 0,
    "watch": true,
    "pause-on-battery": false,
    "pause-on-active": false
}

```

**Comment by kaiwu-astro** [comment]
turning `"huge-pages-jit": false,` to `on` does not help

**Comment by SChernykh** [comment]
It uses all 24 cores (it's cores 0-23 in Linux, 24-47 are just virtual cores on Intel CPUs with HT), you most likely need to enable huge pages and MSR mod: https://xmrig.com/docs/miner/randomx-optimization-guide/

**Comment by kaiwu-astro** [comment]
Thanks for your reply. I have just switched on MSR, and huge pages says "supported", but in `htop` result, only half CPU is used.

![Uploading 截屏2021-03-23 下午4.47.24.png…]()

**Comment by kaiwu-astro** [comment]
Thanks for your reply. I have just switched on MSR, and huge pages says "supported", but in htop result, only half CPU is used.

![2021-03-23 4 47 24](https://user-images.githubusercontent.com/18334656/112118910-d0ba8600-8bf7-11eb-990b-2a02bc60a2de.png)

**Comment by SChernykh** [comment]
You have `huge pages 0%` on one of CPUs, this is why you get low hashrate. Normally, running xmrig as root should enable huge pages, but you might need to also enable them manually: https://xmrig.com/docs/miner/hugepages - 1280 pages per NUMA node, so you need 2560 pages.

**Comment by SChernykh** [comment]
You have 24 cores, and XMRig runs 24 threads on 24 cores. The other 24 are virtual threads because you have CPUs with HT. You probably need to reboot and allocate a bit more huge pages because it says `huge pages 62% 15/24` in the last line.

**Comment by kaiwu-astro** [comment]
Thanks for the solution.

I rebooted my machine and gave 5120 pages. Now the hashrate is 10057 H/s, which matches the highest hashrate (two E5-2678 v3) in the benchmark. 

Many thanks again!

**Comment by agn-7** [comment]
@kaiwu-astro 
The problem is `"max-threads-hint"` is not the number of threads configuration, actually it is the portion (percentage) of numbers of threads that you've set that on `48` which means 48% or half of your thread amount. So you should set it on `100` and then restart the app.

**Comment by kaiwu-astro** [comment]
Thanks for your reply, but unfortunately this did not help. I have 11KHashes/s when I have max-threads-hint set to 48, and 10.9KHashes/s when it is 100 and the program is restarted.
