### ISSUE TITLE
Fails to identify raspberry pi 4 as aarch64

### ISSUE THREAD

**Issue by grahamreeds** [xmrig/xmrig#2202]
When compiling, compilation fails with an error from within sse2neon.h
According to the error message it is "Unsupported target. Must be either ARMv7-A+NEON or ARMv8-A."

Running uname-a gives
```Linux raspberrypi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux```

Running cmake
```-- Use ARM_TARGET=8 (aarch64)
-- WITH_MSR=OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/xmrig/build```

make
[  1%] Built target ethash
[  4%] Built target argon2
[  4%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/cn/CnHash.cpp.o
In file included from /home/pi/xmrig/src/crypto/cn/soft_aes.h:31,
                 from /home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:35,
                 from /home/pi/xmrig/src/crypto/cn/CnHash.cpp:35:
/home/pi/xmrig/src/crypto/cn/sse2neon.h:122:2: error: #error "Unsupported target. Must be either ARMv7-A+NEON or ARMv8-A."
 #error "Unsupported target. Must be either ARMv7-A+NEON or ARMv8-A."
  ^~~~~
In file included from /home/pi/xmrig/src/crypto/cn/soft_aes.h:31,
                 from /home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:35,
                 from /home/pi/xmrig/src/crypto/cn/CnHash.cpp:35:
/home/pi/xmrig/src/crypto/cn/sse2neon.h:7150:9: warning: ‘#pragma GCC pop_options’ without a corresponding ‘#pragma GCC push_options’ [-Wpragmas]
 #pragma GCC pop_options
         ^~~
In file included from /home/pi/xmrig/src/crypto/cn/CnHash.cpp:35:
/home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h: In function ‘__m128i aes_round_tweak_div(const __m128i&, const __m128i&)’:
/home/pi/xmrig/src/crypto/cn/CryptoNight_arm.h:367:29: warning: requested alignment 16 is larger than 8 [-Wattributes]
     alignas(16) uint32_t k[4];
                             ^
```
Raspberry Pi 4/8 with fresh copy of Raspberry Os. Update and upgrade ran. arm_64bit added to config.txt.

**Comment by killamah** [comment]
Same here , but in my case it's a T585 Samsung with 2 A53 Cortex 64b. 
Whit this cmake the compilation is full done but when run xmrig i get : Bus Error:

cmake .. -DARM_TARGET=7

**Comment by grahamreeds** [comment]
Even with the -DARM_TARGET option I get the exact same issue.

**Comment by Spudz76** [comment]
The compiler toolchain must also be 64-bit or `__aarch64__` will not be defined, leading to that error on ARMv8.

Does `gcc -v` say for target?  It probably says something like `arm-linux-gnueabihf` which means 32-bit (even though you have the `aarch64` kernel and OS in general).  It should say `aarch64-linux-gnu`... or of course `__aarch64__` won't be defined.  If it is wrong then you need to locate and install the 64-bit toolchain, I don't know anything about RPi so have no tips on that part - also likely different depending which version of the OS you've installed.

Source: [random blog](https://qengineering.eu/install-raspberry-64-os.html) scroll down slightly to the "Version check" section.

**Comment by grahamreeds** [comment]
D'OH!  My bad.

 I had installed 32bit RaspbianOS not the 64bit.  If you download the image [here](https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2020-08-24/2020-08-20-raspios-buster-arm64-lite.zip) and use the imager tool to write it to the sd card, Xmrig will compile fine.

**Comment by jgabriel98** [comment]
I've installed the 32bit OS imagem.
but upgraded with `rpi-update` and enabled 64bit kernel by adding `arm_64bit=1` into **/boot/config.txt**

So now `uname -a` gives _aarch64_: 
`Linux raspberrypi 5.10.31-v8+ #1412 SMP PREEMPT Wed Apr 21 15:47:05 BST 2021 aarch64 GNU/Linux`

but `gcc -v gives` _armv6_: 
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 8.3.0-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1) 
```

how can i upgrade de build toolchain to 64bit ?

**Comment by Spudz76** [comment]
Install actual 64-bit image.  Sometimes that doesn't even come with the 64-bit compiler, as some form of evil trolling.  There does exist an image with 64-bit everything, people have found it...

**Comment by grahamreeds** [comment]
https://downloads.raspberrypi.org/raspios_lite_arm64/images/

There's even been a release a couple of weeks ago.

GR
