### ISSUE TITLE
Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by jonz113** [xmrig/xmrig#2206]
Hi All, I'm a total novice and trying to learn so I can demonstrate in a college class.  I have Ubuntu 20.04 on a Odroid C4 and I downloaded xmrig-6.10.0-focal-x64.tar.gz.  I am recieving the below message in terminal

odroid@odroid:~/Desktop/xmrig-6.10.0$ sudo ./xmrig
[sudo] password for odroid: 
./xmrig: 1: Syntax error: "(" unexpected
odroid@odroid:~/Desktop/xmrig-6.10.0$

Any help is greatly appreciated.  Thanks!

**Comment by SChernykh** [comment]
> xmrig-6.10.0-focal-x64.tar.gz

This is for x86 CPUs, not for ARM. You have to download source code and compile it yourself: https://xmrig.com/docs/miner/build
