### ISSUE TITLE
macOS unable to connect to miner with workers.xmrig.info after 6.10.0 update

### ISSUE THREAD

**Issue by AntlerDM** [xmrig/xmrig#2207]
Since upgrading to 6.10.0, I am no longer able to connect via http via http://workers.xmrig.info/ or add the worker. With version 6.9.0 and prior, I simply needed to add the xmrig binary to my firewall exceptions to get it to work. Now, the only option is to disable the firewall.

I am using macOS (Big Sur) and I am using the following command to launch xmrig:
./xmrig --api-worker-id xmrig_V --http-host 0.0.0.0 --http-port 18888 -o 192.168.xx.xx:18089 -u <wallet> --coin monero --daemon

I have tried using different IPs (127.0.0.1, 192.168.xx.xx) and also tried leaving out --http-host entirely.

The release notes for 6.10.0 refer to a change with http parsing. Could this be related?

**Comment by siptruk** [comment]
I was able to add and connect to http://workers.xmrig.info/ but unable to change the configuration with the response `FAILED TO APPLY THE CONFIGURATION` or in the console` net :: ERR_EMPTY_RESPONSE`. Configuration in json is the same as v6.9.0 and works without any problems but only in v6.10.0 it doesn't work

**Comment by AntlerDM** [comment]
It seems to be working now. No changes in configuration.

Maybe a change to workers.xmrig.info?

**Comment by xmrig** [comment]
Fixed https://github.com/xmrig/xmrig/releases/tag/v6.11.2

There was a bug when migrating from http parser to llhttp: fragmented on TCP level HTTP requests was parsed incorrectly, only the first chunk of data was parsed.
