### ISSUE TITLE
Xmrig with built-in TOR

### ISSUE THREAD

**Issue by paolosezart** [xmrig/xmrig#2209]
Is an xmrig version with built-in TOR expected? That is, without an intermediate proxy. It would be very convenient and more anonymous if xmrig already had the ability to mine directly to onion addresses. There would be no need to install a separate program for TOR.

**Comment by 00-matt** [comment]
Embedding Tor is quite difficult. You could bundle the Tor daemon with XMRig, and use a script to launch it if the system doesn't already have Tor running, which I believe is how the Feather wallet works.

**Comment by paolosezart** [comment]
So what about embedding tor into xmrig?
Are there any decisions on this matter?
