### ISSUE TITLE
xmrig stops working at suprnova pool

### ISSUE THREAD

**Issue by calvintam236** [xmrig/xmrig#221]
I pointed my miners to suprnova pool, and today I notice errors: `connect error: "connection timed out` on `xmr-us.suprnova.cc:5222`, no hash rate reported at the miner ("n/a") or pool.

Original settings are: `nicehash=true`, and `keepalive=true`. This settings worked for months. Tried with either and both set to `false`. Tried port 5223 as well. I can ping the target domain, so I don't think it is a network issue.

Looks like some changes made on the pool side broke the `xmrig` connect ability.

**Comment by xmrig** [comment]
Looks like it pool issue, for me both us and eu servers no work, I also tried other miner. Same timeout issue.
Thank you.

**Comment by calvintam236** [comment]
Because the XMR pool still have ~850 kH/s, I don't think it is a pool issue.

**Comment by calvintam236** [comment]
Just tried `xmr.suprnova.cc:5222`, and it works.. I guess something wrong on their config.
