### ISSUE TITLE
Fails to build on Octa Core Cortex A53 - Android tablet T585 

### ISSUE THREAD

**Issue by killamah** [xmrig/xmrig#2211]
Hi i have error to make on **Octa Core Cortex A53** 

**cmake ..     done
make         get error something about 'maes'** 

If i add :

**cmake .. -DARM_TARGET=8 
make          get error : Unsupported target. Must be either ARMv7-A+NEON or ARMv8-A**

So i try :

**cmake .. -DARM_TARGET=7 
make            Done ! xmrig Compiled but when i run it:**

**CPU       ARM Cortex A53 (1) 32-bit -AES**

then it's kill:

**Bus Error**

Sure because of bad CPU setting.
I see many guy that successfully compiled for Octa Core cpu.
Any help?

Thanks

**Comment by Spudz76** [comment]
Must be a 64-bit OS with 64-bit compiler.  That error occurs when `__aarch64__` is not defined, which would happen if you are in 32-bit compiler.

Logic is [here](https://github.com/xmrig/xmrig/blob/master/src/crypto/cn/sse2neon.h#L122)

**Comment by killamah** [comment]
Thanks , How i can do termux usinng GCC 64 compiler?

**Comment by Spudz76** [comment]
Unknown, would depend on your Android revision among ROM build, whether it's rooted, and other specs.

Compiling on the tablet may not be the best way, also consider finding a cross-compile toolchain for aarch64 with whichever Android SDK matches your ROM, on a regular Linux computer build xmrig there targeted for the other type of CPU, and then copy the binary over for execution on the tablet.  Tablet may not have enough memory and finding usable toolchain for install could be more difficult, and it must be slow compared to a desktop processor doing the compile work.

**Comment by killamah** [comment]
Thanks 
I fix it by installing lineage OS 64bit. Now xmrig work great! Thanks
