### ISSUE TITLE
JSON decode failed

### ISSUE THREAD

**Issue by dodois** [xmrig/xmrig#2221]
**Describe the bug**
JSON decode failed
read error: "end of file"
![image](https://user-images.githubusercontent.com/73285310/113155241-647cf980-926b-11eb-95c8-1713896945ad.png)

**To Reproduce**
```
xmrig.exe --url pool.doisnet.com:2052 --userpass 44VTGz9oAYWUrVHgJ8Kk924CCR3svcefEXD1EwtTuL5YEsnEprscGvn6sdjYGSHbxfKCQg4vBycVPYM1FyWXAGKKLuJcS95:tester -k --coin monero
```

**Expected behavior**

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: Windows 10
 - For GPU related issues: information about GPUs and driver version.

**Additional context**
```
root@HEY13233121:~# telnet pool.doisnet.com 2052
Trying 104.21.94.246...
Connected to pool.doisnet.com.
Escape character is '^]'.

root@HEY13233121:~# curl pool.doisnet.com:2052
Mining server online
```

**Comment by dodois** [comment]
This is not a json problem, but a bug.
![image](https://user-images.githubusercontent.com/73285310/113176678-546f1500-927f-11eb-891f-26c1cb8fe208.png)
I deleted the config.json and executed it using the command line and encountered the same error

**Comment by SChernykh** [comment]
You get an incorrect answer from the pool, it's not the problem with config.json

**Comment by dodois** [comment]
@SChernykh 
```
root@HEY13233121:~# curl pool.doisnet.com:2052
Mining server online
```

**Comment by SChernykh** [comment]
It's useless to check with curl. You need to see what pool sends to xmrig. But I'll take a wild guess and say that you configured the pool to use TLS and didn't enable it in config.json, or vice versa.

**Comment by dodois** [comment]
Please keep this issue for now, I will finish checking tomorrow

**Comment by dodois** [comment]
@SChernykh Is there any way to view the return of pool ？

**Comment by SChernykh** [comment]
You need to add `-DWITH_DEBUG_LOG=ON` to cmake command line.

**Comment by dodois** [comment]
I succeeded, it was a tcp connection and I used http by mistake.
