### ISSUE TITLE
usning config file

### ISSUE THREAD

**Issue by Blisk** [xmrig/xmrig#2230]
**Describe the bug**
I have config.json in folder where executable is, but whatever I change in config.json doesn't affect miner.
Do I need to configure in cmd to select config.json file or exe will automatically find it if exist in the same folder??
I didn't find any info about that.

**Comment by Spudz76** [comment]
If you only run the exe (not some batch file, with extra arguments) then it will read config.json from same folder as the exe

Command line arguments always override config.json contents

**Comment by Blisk** [comment]
I have batch with exe in it. Is there a way to have a log file?
Where I can find more Command line arguments?

**Comment by SChernykh** [comment]
https://xmrig.com/docs/miner/command-line-options

**Comment by Blisk** [comment]
thank you
