### ISSUE TITLE
Minergate Support

### ISSUE THREAD

**Issue by andress134** [xmrig/xmrig#2231]
**Describe the bug**
I dont know what happen but, it stopped working for minergate, im testing on linux, ubuntu/debian and nothing, is not starting mining

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Required data**

 * ABOUT        XMRig/6.10.0 gcc/9.3.0
 * LIBS         libuv/1.41.0 OpenSSL/1.1.1j hwloc/2.4.1
 * HUGE PAGES   supported
 * 1GB PAGES    disabled
 * CPU          Intel(R) Xeon(R) CPU E3-1230 v6 @ 3.50GHz (1) 64-bit AES
                L2:1.0 MB L3:8.0 MB 4C/8T NUMA:1
 * MEMORY       12.7/15.6 GB (81%)
 * DONATE       1%
 * ASSEMBLY     auto:intel
 * POOL #1      xmr.pool.minergate.com:45700 algo auto
 * COMMANDS     hashrate, pause, resume, results, connection
[2021-04-03 06:15:18.824] no active connection

here is my command ./xmrig --opencl -o xmr.pool.minergate.com:45700 -u user --tls -k --coin monero -a argon2/chukwa

**Additional context**

**Comment by Spudz76** [comment]
Coin Monero with Algo argon2/chukwa is a mismatch?  Specify one or the other instead of both, or use `--coin monero --algo rx/0` so they match correctly.

**Comment by andress134** [comment]
> Coin Monero with Algo argon2/chukwa is a mismatch? Specify one or the other instead of both, or use `--coin monero --algo rx/0` so they match correctly.

I tried also ./xmrig -o stratum+tcp://xmr.pool.minergate.com:45700 -u user -p x --donate-level 1 --max-cpu-usage 75

**Comment by andress134** [comment]
so i think some wrong on this xmrig version, im using same servers, same command that have used with other version and it has working fine, but now, i run it and keep blocked

./xmrig-o stratum+tcp://xmr.pool.minergate.com:45700 -u user -p x --donate-level 1 --max-cpu-usage 75
 * ABOUT        XMRig/6.10.0 gcc/5.4.0
 * LIBS         libuv/1.41.0 OpenSSL/1.1.1j hwloc/2.4.1
 * HUGE PAGES   supported
 * 1GB PAGES    disabled
 * CPU          Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (1) 64-bit AES VM
                L2:4.0 MB L3:27.5 MB 1C/1T NUMA:1
 * MEMORY       1.7/1.8 GB (95%)
 * DONATE       1%
 * ASSEMBLY     auto:intel
 * POOL #1      stratum+tcp://xmr.pool.minergate.com:45700 algo auto
 * COMMANDS     hashrate, pause, resume, results, connection
 * OPENCL       disabled
 * CUDA         disabled

**Comment by Spudz76** [comment]
All your memory is gone somehow, which could be why that last run didn't work.  1.8GB total while RandomX needs a free minimum of 2.3GB.

Also gcc5 is really antique and likely has been untested for a while, should be gcc7 or newer.

**Comment by andress134** [comment]
> All your memory is gone somehow, which could be why that last run didn't work. 1.8GB total while RandomX needs a free minimum of 2.3GB.
> 
> Also gcc5 is really antique and likely has been untested for a while, should be gcc7 or newer.

I am 100% convinced that the problem is from xmrig, not the servers
I used the same servers until xmrig version 6.8 and it worked perfectly, since the launch of 6.9 I started to lose the hash, and now 6.10 doesn't work at all.
I tried another test, on a much larger server and it doesn't work

```js
./xmrig -o stratum+tcp://xmr.pool.minergate.com:45700 -u user -p x --donate-level 1 --max-cpu-usage 75
 * ABOUT        XMRig/6.10.0 gcc/5.4.0
 * LIBS         libuv/1.41.0 OpenSSL/1.1.1j hwloc/2.4.1
 * HUGE PAGES   supported
 * 1GB PAGES    disabled
 * CPU          AMD EPYC 7281 16-Core Processor (3) 64-bit AES VM
                L2:0.0 MB L3:0.0 MB 3C/3T NUMA:1
 * MEMORY       1.2/3.8 GB (32%)
 * DONATE       1%
 * ASSEMBLY     auto:ryzen
 * POOL #1      stratum+tcp://xmr.pool.minergate.com:45700 algo auto
 * COMMANDS     hashrate, pause, resume, results, connection
 * OPENCL       disabled
 * CUDA         disabled
```

Still not working, i can't mining on minergate, using same servers that have used for mining long time  utill version 6.8xmrig

**Comment by SChernykh** [comment]
Don't mine on minergate. It's a scam pool that steals 30% of your hashrate. That said, it is a pool problem, not xmrig problem. Try another pool.

**Comment by andress134** [comment]
> Don't mine on minergate. It's a scam pool that steals 30% of your hashrate. That said, it is a pool problem, not xmrig problem. Try another pool.

could you recommend a better alternative than minergate?

**Comment by SChernykh** [comment]
List of pools: https://miningpoolstats.stream/monero
Try a pool not in top 3. Hashvault and MoneroOcean are good pools.

**Comment by andress134** [comment]
> List of pools: https://miningpoolstats.stream/monero
> Try a pool not in top 3. Hashvault and MoneroOcean are good pools.

Okay, thank you
