### ISSUE TITLE
Your code is being used to attack github repositories.   Your repo is basically a virus.

### ISSUE THREAD

**Issue by Lothrazar** [xmrig/xmrig#2236]
Example

https://github.com/Lothrazar/Cyclic/actions/runs/719171490

https://github.com/Lothrazar/Cyclic/actions/runs/719171490/workflow

**Comment by SChernykh** [comment]
xmrg is NOT a virus, read wikipedia for the definition of a virus.
Also read https://dev.to/thibaultduponchelle/the-github-action-mining-attack-through-pull-request-2lmc and https://www.bleepingcomputer.com/news/security/github-actions-being-actively-abused-to-mine-cryptocurrency-on-github-servers/

**Comment by Aaron-Mann** [comment]
@I can use a screwdriver to drive a screw, or I can use a screwdriver to kill someone. The original purpose of the tool is to do good, but just like any other tool, the screwdriver can be used maliciously. This code is not a virus. Rather, the virus is the malicious individuals using this code unethically.
Also, just like @SChernykh stated, this software is inherently not a virus. A virus starts with malicious intent, and spreads itself. XMRig on the contrary, has a perfectly ethical purpose.

**Comment by forkpoweroutlet** [comment]
One of my repositories was recently targeted by one of these attacks. I promptly looked into the suspicious runs and reported the creator of the PR for abuse.

That being said, I do not believe that the issue stems from this software and I would agree with others that this repository, used primarily in a non-abusive manner, is not a virus.

I've reached out to GitHub support about my incident in particular and the articles I've found also mention being in touch with GitHub; we'll see how they go from there.

**Comment by snipeTR** [comment]
Since you are using github, you understand programming languages.  In the code in xmrig, can you show us the part that makes the virus you are talking about?

**Comment by SChernykh** [comment]
I think I found the suspect: https://www.reddit.com/r/MoneroMining/comments/mks43t/github_mining_guide/

**Comment by chron0** [comment]
How dare you question the master of math...

**Comment by forkpoweroutlet** [comment]
GitHub knows of these attacks and how they're being carried out, but I haven't seen them address it directly and publicly other than playing whack-a-mole by banning the offending accounts as they pop up.

As far as I can tell, any long-term solution would involve breaking changes to how GitHub Actions works with pull requests.

I have an idea on how these attacks can be prevented, **but I have no idea if this actually works**.

Public repositories can either disable Actions or [change the settings](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository) to establish a whitelist of Actions.

Hopefully this disables the creation and execution of new checks on pull requests, but again, I'm not sure if it will help in the slightest. I reached out to GitHub support on this, and they have yet to respond.

And to the opener of this issue: I understand your concern. Attacks like this on our own repositories are detrimental, and we're all looking for a solution. We just think that solution should allow this legitimate open source software to remain open.

**Comment by SChernykh** [comment]
Honestly, the whole idea of executing random scripts and allowing things like curl and compilation there is a giant security hole waiting to be abused. So it is abused - if not with xmrig then it will use something else, but it WILL be abused.

**Comment by ThiefMaster** [comment]
The whole point of GitHub actions is to let people run code - in an environment that's highly temporary and thus anything malicious you do there has no lasting impact. There's a reason why `pull_request` actions triggered from a fork get a `GITHUB_TOKEN` that has no write access whatsoever..

**Comment by ThiefMaster** [comment]
> Public repositories can either disable Actions or change the settings to establish a whitelist of Actions.

That won't work. It's about whitelisting the sources of third-party actions. As long as the malicious code is in the local action itself, it won't help at all.

**Comment by forkpoweroutlet** [comment]
> > Public repositories can either disable Actions **or change the settings to establish a whitelist of Actions**.
> 
> That won't work. It's about whitelisting the sources of third-party actions. As long as the malicious code is in the local action itself, it won't help at all.

Got it. Guess what's left to do is cancel the workflows as they appear, lock the malicious PR, and then block and report the user.

Or do nothing.
