### ISSUE TITLE
segmentation fault on openbsd

### ISSUE THREAD

**Issue by swrangsar** [xmrig/xmrig#2247]
managed to compile xmrig on openbsd with -DMAP_POPULATE=0 -DMAP_HUGETLB=0 but as soon as it is run, xmrig seg faults and dumps core

**Comment by SChernykh** [comment]
XMRig doesn't support OpenBSD, it hasn't been tested there. Even if you manage to compile, it'll likely crash and even if it runs, there's no support for huge pages and thread affinity in OpenBSD which will result in poor performance.

**Comment by xmrig** [comment]
CMake option `-DWITH_SECURE_JIT=ON` might help, but as answered above OpenBSD is not really supported.
Thank you.
