### ISSUE TITLE
segmentation fault on centos 6.01

### ISSUE THREAD

**Issue by NirHeaven** [xmrig/xmrig#2248]
I download xmrig-6.11.1-linux-x64.tar.gz and run ./xmrig on centos 6.1, I get segmentation fault

**Comment by xmrig** [comment]
You should use `xmrig-6.11.1-linux-static-x64.tar.gz` on such old system.
Thank you.

**Comment by NirHeaven** [comment]
I have tried, but also got segmentation fault, by the way , the centos version is release 7.2.1511 (Core)

**Comment by NirHeaven** [comment]
hello, is there anyone can help me?

**Comment by xmrig** [comment]
Unlikely, you did not provide any other details and the OS is very old.

**Comment by NirHeaven** [comment]
How can I get the informations you want to check this problem?all I get is segmentation fault when I ran the bin

**Comment by NirHeaven** [comment]
CPU version is Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz

**Comment by NirHeaven** [comment]
the number of unique physical cpu id is [0,1] and the number of processor is 16
