### ISSUE TITLE
KAWPOW not working on windows 6.11.1

### ISSUE THREAD

**Issue by raspy313** [xmrig/xmrig#2249]
**Describe the bug**
Starting the miner using kawpow is not recognized

**To Reproduce**
xmrig.exe -kawpow -o *pool* -u *wallet* returns *incompatible or disabled algorithm*

**Comment by Spudz76** [comment]
KawPow does not mine on CPU, do you have CUDA or OpenCL?

**Comment by SChernykh** [comment]
`xmrig.exe -a kawpow -o pool -u wallet`
https://xmrig.com/docs/miner/command-line-options

**Comment by raspy313** [comment]
For the project I'm currently working on I need to use CPU for mining, I was hoping to use RVN if possible

**Comment by raspy313** [comment]
> KawPow does not mine on CPU, do you have CUDA or OpenCL?

For the project I'm currently working on I need to use CPU for mining, I was hoping to use RVN if possible

**Comment by Spudz76** [comment]
You'll have to find some old Ravencoin miner that supports CPU still, maybe doesn't exist.  You probably will never score a hash.  What are you trying to do?  If you just want to mine CPU+GPU to maximum profit on a single box, then get on a pool with multicoin autoswitch like MoneroOcean and run one on CPU and another on GPU they will run different algos whichever is most profitable at the time.  You do need their fork of xmrig to support the extended algo-perf function so the pool knows your hashrates per algo and can decide which algo is best to send.  Vanilla xmrig won't autoswitch.  They pay out in XMR with autochanging which makes mining different coins less hassle.  Then if you want RVN trade the XMR for it.
