### ISSUE TITLE
i386 Issues (Ubuntu 14.04)

### ISSUE THREAD

**Issue by pdkkid** [xmrig/xmrig#225]
I know we have win32 & win64 bit support in the releases, anyway we can add the same to the linux releases, i have a ton of old IBM machines sitting around and ive loaded i386 ubuntu 14.04 on them all to mine on (I know its inefficient, my electric is a flat rate lol), currently attempting to just build xmrig on the machine, but posting here to see if its a simple re-release

**Comment by unawarecitizen** [comment]
I've built and run xmrig on i386 ubuntu server 17+. If you run into issues on 14.04, try upgrading and then building xmrig.
