### ISSUE TITLE
Very low hashrate, unstable connection, since 6.10 on win10 with Ryzen 3600

### ISSUE THREAD

**Issue by thaneb** [xmrig/xmrig#2250]
My hashrate dropped to 780h/s since 6.10 (and 6.11 still same) with an incredible number of "connection closed by server" on my mining pc (nanopool, configured with the xmrig wizard).
I disable PBO in my BIOS (in case of) , and I followed guides often gave here.
I just came back to xmrig 6.09 and my 6700h/s on average is back !
Any idea ?

**Comment by SChernykh** [comment]
To check if it's a pool or miner problem:
- Try another pool
- Try to run embedded benchmark

**Comment by thaneb** [comment]
I already tried with the included miner pool. Bat included, it was working well, so it seems to be an issue between last 2 releases of xmrig and nanopool, anyway, I posted here so maybe someone else could see "he's not alone, and the solution is to use an older release"

**Comment by SChernykh** [comment]
xmrig 6.10 was released more than a month ago. I'm also testing xmrig 6.11 + nanopool right now and I don't have any problems.

**Comment by thaneb** [comment]
so much weird, i updated the xmrig.exe and the winring0x64.sys, and now it seems to work well...
