### ISSUE TITLE
compile issue 

### ISSUE THREAD

**Issue by zhekafun** [xmrig/xmrig#2251]
cmake optios

cmake .. -G "Unix Makefiles" -DWITH_CUDA=OFF -DWITH_NVML=OFF -DWITH_CN_LITE=OFF -DWITH_ARGON2=OFF -DWITH_ADL=OFF -DWITH_OPENCL=OFF -DWITH_CN_HEAVY=OFF -DWITH_CN_PICO=OFF -DWITH_ASTROBWT=OFF -DWITH_KAWPOW=OFF -DXMRIG_DEPS=c:/xmrig-deps-master/gcc/x64

result
[ 69%] Building C object CMakeFiles/xmrig.dir/src/crypto/cn/c_blake256.c.o
/home/zheko/xmrig/src/crypto/common/VirtualMemory_unix.cpp: In static member function ‘static void* xmrig::VirtualMemory::allocateExecutableMemory(size_t, bool)’:
/home/zheko/xmrig/src/crypto/common/VirtualMemory_unix.cpp:148:109: error: ‘MAP_POPULATE’ was not declared in this scope; did you mean ‘MAP_PRIVATE’?
  148 |         mem = mmap(0, align(size), PROT_READ | PROT_WRITE | SECURE_PROT_EXEC, MAP_PRIVATE | MAP_ANONYMOUS | MAP_POPULATE | hugePagesFlag(hugePageSize()), -1, 0);
      |                                                                                                             ^~~~~~~~~~~~
      |                                                                                                             MAP_PRIVATE
/home/zheko/xmrig/src/crypto/common/VirtualMemory_unix.cpp: In static member function ‘static void* xmrig::VirtualMemory::allocateLargePagesMemory(size_t)’:
/home/zheko/xmrig/src/crypto/common/VirtualMemory_unix.cpp:168:85: error: ‘MAP_HUGETLB’ was not declared in this scope; did you mean ‘MAP_HUGE_MASK’?
  168 |     void *mem = mmap(0, size, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_HUGETLB | MAP_POPULATE | hugePagesFlag(hugePageSize()), 0, 0);
      |                                                                                     ^~~~~~~~~~~
      |                                                                                     MAP_HUGE_MASK
/home/zheko/xmrig/src/crypto/common/VirtualMemory_unix.cpp:168:99: error: ‘MAP_POPULATE’ was not declared in this scope; did you mean ‘MAP_PRIVATE’?
  168 |     void *mem = mmap(0, size, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_HUGETLB | MAP_POPULATE | hugePagesFlag(hugePageSize()), 0, 0);
      |                                                                                                   ^~~~~~~~~~~~
      |                                                                                                   MAP_PRIVATE
make[2]: *** [CMakeFiles/xmrig.dir/build.make:1356: CMakeFiles/xmrig.dir/src/crypto/common/VirtualMemory_unix.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:133: CMakeFiles/xmrig.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Comment by SChernykh** [comment]
```
1. pacman -S mingw-w64-x86_64-gcc git make
2. git clone https://github.com/xmrig/xmrig.git
3. mkdir xmrig/build && cd xmrig/build
4. "c:\Program Files\CMake\bin\cmake.exe" .. -G "Unix Makefiles" -DXMRIG_DEPS=c:/xmrig-deps/gcc/x64
5. make -j$(nproc)
```
Step 4 uses cmake you have to install separately. The one in msys64 doesn't work with xmrig.

**Comment by snipeTR** [comment]
Why msys64 cmake doesn't work with xmrig.

**Comment by xmrig** [comment]
@snipeTR It works, but not always, so the safest option is use external cmake. I didn't really investigate what exactly was wrong with msys64 cmake.
Thank you.

**Comment by Spudz76** [comment]
I've never gotten it to work, same error.  It seems to think it's on Linux, probably because the compiler isn't defining any of the Windows OS defines.  Seems there was some flag to get it to act like it's Windows.  At some point they changed the default so Linux code would more likely just work out-of-the-box without knowing about windows at all (the primary use of msys64 is to run simple Linux code without porting).  But VirtualMemory things are very very different.  I may have been trying to compile under cygwin64 but same issue, it thought it was Linux.

Easy enough to just install VS2019 Build Tools which is how I solved the problem, haha.
