### ISSUE TITLE
1 GB pages lowers the hashrate in benchmark mode

### ISSUE THREAD

**Issue by DocBrown101** [xmrig/xmrig#2253]
**Describe the bug**
If the benchmark is started with 1gb pages, the hashes reduce drastically.

**To Reproduce**
Simply compare both calls with each other.
./xmrig --bench=1M --randomx-1gb-pages
and without 1gb
./xmrig --bench=1M

**Comment by SChernykh** [comment]
Define "drastically". Do you get any red text for huge pages when starting the benchmark?

**Comment by DocBrown101** [comment]
Approximately 441 H/s less.

https://i.imgur.com/WnuSRoc.png
vs
https://i.imgur.com/2Ao5N6R.png

**Comment by SChernykh** [comment]
Do you have any variance between tests runs, i.e. maybe there are other programs running in the background that use CPU? 1 GB pages shouldn't cause more than 1-2% difference anyway.

**Comment by DocBrown101** [comment]
No, there is definitely nothing running in the background that requires CPU.

I also noticed that my system has about **5 watts less power consumption** when I run it with 1gb-pages.

**Comment by DocBrown101** [comment]
No, it always occurs with me, even without benchmark. So I have closed it now.
