### ISSUE TITLE
SSL/TLS support

### ISSUE THREAD

**Issue by zDEATHz** [xmrig/xmrig#226]
Hello,

I am very glad to use your miner, thank you to your software!
Please, can you add a SSL/TLS support? It will be perfect.

Best regards,
E.V.

**Comment by mxjoe** [comment]
Is SSL/TLS support anywhere near? Currently I am using Claymore's solution but I would like to switch.

**Comment by enwillyado** [comment]
https://github.com/xmrig/xmrig-proxy/issues/8

**Comment by moralrebuild** [comment]
This is a must have feature considering for the sake of security and privacy. XMRIG has nice self tuning feature but lacking TLS comparing with more popular alternative xmr-stak.

**Comment by aleqx** [comment]
Adding my vote. I just posted a new issue about this as I didn't find this one at first.

A lot of miners definitely want SSL and are already using SSL (via xmr-stak). Major pools support it, see supportxmr, hashvault, nanopool, etc ...

@xmrig, you'd be getting more income via the fee/donations if you added SSL. Many SSL miners who currently use xmr-stak because of SSL would switch to xmrig.

**Comment by ariadarkkkis** [comment]
use xmrigCC with TLS support instead
Its only for CPU for now but I think the developer can fork GPU version with TlS and other awesome features.
@bendr0id
https://github.com/Bendr0id/xmrigCC

**Comment by aleqx** [comment]
I took a look at xmrigCC and that does not support SSL. It seems it just sets up a local SSL proxy which connects to the SSL server, and then you connect xmrig to this local SSL proxy.

I can already do all that with stunnel + xmrig. That doesn't mean that xmrig supports SSL. A system admin can still sniff/mangle the packets xmrig sends to the loopback interface before they are SSL encrypted.

The request in this thread is for a true SSL support in the xmrig client, like xmr-stak does, i.e. xmrig is an actual SSL client.

**Comment by Bendr0id** [comment]
Hi alexq,

It seems that you either did not read carefully or misunderstood something. XMRigCC isn't and hasn't any proxy features. It is a full SSL/TLS client exactly like xmr-stak with an optional remote control feature. No local loopback device or tunneling is involved. It does end-to-end TLS for the whole communication with the pool.

And also the optional remote control feature is full end-to-end encrypted when enable it.


Am 22.04.2018 16:39 schrieb aleqx <notifications@github.com>:

I took a look at xmrigCC and that does not support SSL. It seems it just sets up a local SSL proxy which connects to the SSL server, and then you connect xmrig to this local SSL proxy.

I can already do all that with stunnel + xmrig. That doesn't mean that xmrig supports SSL. A system admin can still sniff/mangle the packets xmrig sends to the loopback interface before they are SSL encrypted.

The request in this thread is for a true SSL support in the xmrig client, like xmr-stak does, i.e. xmrig is an actual SSL client.

**Comment by aleqx** [comment]
@Bendr0id But that's not what your Howto is showing: https://github.com/Bendr0id/xmrigCC/wiki/tls

It seems you need to first launch a server locally, which connects to the pool with SSL, and then you connect the miner to the local server unsecured. I want to connect the miner directly to the pool with SSL (not via any server/proxy).

What am I missing?

**Comment by Bendr0id** [comment]
No you're mixing things up.

XMRigCCServer is a remote control tool for the miner. But you can completely use the miner without that.

On the wiki is nothing mentioned that you need a XMRigCCServer.

Put a pool there enable TLS and you're done.

The only relevant part for your case is this:

XMRigCCMiner
<https://github.com/Bendr0id/xmrigCC/wiki/tls#using-tls-for-miner-pool-communication>Using TLS for Miner->Pool communication

To turn on TLS make sure you're using a Pool+Port which is able to handle TLS requests.

Then change the miner config this way:

"pools": [
        {
            "url": "serverwhichsupportstls.com:443",
            "use-tls" : true,
...
        }
    ],

Am 22.04.2018 20:53 schrieb aleqx <notifications@github.com>:

@Bendr0id<https://github.com/Bendr0id> But that's not what your Howto is showing: https://github.com/Bendr0id/xmrigCC/wiki/tls

It seems you need to first launch a server locally, which connects to the pool with SSL, and then you connect the miner to the local server unsecured. I want to connect the miner directly to the pool with SSL (not via any server/proxy).

What am I missing?

**Comment by enwillyado** [comment]
I implemented SSL in my pre-release: https://github.com/enwillyado/xmrig/releases/tag/VW-3.4.0-6

**Comment by Bendr0id** [comment]
@enwillyado I had a look in your repo. Why you need the cert and key? On client side you don't need that. 

And it seems that you are using "evt-tls" library. 

I used it in the past aswell but it's realy buggy when using with libuv, you'll get a lot of crashes and reconnect issues.

**Comment by enwillyado** [comment]
@Bendr0id Some servers may require client authentication through SSL. But, in the final release the use of pair of client certificates will be optional!

**Comment by xmrig** [comment]
SSL/TLS will be available in next v2.8 release #758.
Thank you.
