### ISSUE TITLE
error "no suitable configuration found"

### ISSUE THREAD

**Issue by robinfoxnan** [xmrig/xmrig#2267]
i compiled the cuda.dll, and config json like this:
"cuda": {
"enabled": true,
        "loader": "xmrig-cuda.dll",
        "nvml": true,
   "cn/0": false,
        "cn-lite/0": false
    }

but i got an error :
"no suitable configuration found"

Is there someone can tell me how to config the cuda config section?

Thanks a lot

**Comment by Spudz76** [comment]
if you used latest CUDA Toolkit but have an older than Pascal GPU it won't work.  May need CUDA 10.2.

if you used the latest driver but have an older than Kepler GPU it also won't work (and you need CUDA 8.0 maximum, driver series 390 maximum for Fermi)

What's the actual output at startup / does it list the GPU?  What GPU model is it and how much memory and what algo are you trying to use?
