### ISSUE TITLE
ARM Cortex-A72 64-bit can't enable 1GB PAGES

### ISSUE THREAD

**Issue by TylerMMcFarlane** [xmrig/xmrig#2271]
**Describe the bug**
I can't get 1GB pages enabled.

**To Reproduce**
I have made a custom kernel with Linux for a Raspberry Pi 4 I have pre allocated 4 1GB hugepages in addition to 1168 2MB hugepages. I can attach if required just let me know.

**Expected behavior**
I was expecting the disabled 

**Screeenshots**
<img width="368" alt="Screenshot2" src="https://user-images.githubusercontent.com/82615933/114941107-a052ba00-9e3a-11eb-9f37-2d976fddbeb5.PNG">
<img width="619" alt="Screenshot3" src="https://user-images.githubusercontent.com/82615933/114941110-a183e700-9e3a-11eb-8aca-330c6b46721e.PNG">
<img width="609" alt="Screenshot1" src="https://user-images.githubusercontent.com/82615933/114941111-a183e700-9e3a-11eb-8337-367d2789ef55.PNG">

**Comment by TylerMMcFarlane** [comment]
Hello, this is my first time using GitHub & Linux. Just let me know if I need to attach more info/ what info. Thanks.

**Comment by SChernykh** [comment]
Either add `--randomx-1gb-pages` to the command line or use config.json instead of command line options.

**Comment by Spudz76** [comment]
The code for ARM sets the feature flag (`FLAG_PDPE1GB`) only when the miner can open the sysfs file at `/sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages`; with x86_64 there is an actual flag in `/proc/cpuinfo` so this sysfs check is emulating that.

What does `cat /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages` do?  I see you are running as root so it would be weird if it were permission related... maybe that doesn't exist for some reason (sysfs related kernel options missing in your custom build?)

Also if the above doesn't exist for some reason check for the alternate location with:
`grep . /sys/devices/system/node/node*/hugepages/hugepages-1048576kB/nr_hugepages`

Might as well include output of `cat /proc/cpuinfo` for completeness.

**Comment by TylerMMcFarlane** [comment]
> Either add `--randomx-1gb-pages` to the command line or use config.json instead of command line options.

It's work!!, I added  `--randomx-1gb-pages` to the command line. The hashrate is amazing but it's been fun trying to optimise it. Thanks of the help!!

![image](https://user-images.githubusercontent.com/82615933/114992869-200c7300-9e93-11eb-82f6-6feae5a02b56.png)

**Comment by Shai0Hulud** [comment]
> > Either add `--randomx-1gb-pages` to the command line or use config.json instead of command line options.
> 
> It's work!!, I added `--randomx-1gb-pages` to the command line. The hashrate is amazing but it's been fun trying to optimise it. Thanks for the help!!
> 
> ![image](https://user-images.githubusercontent.com/82615933/114992869-200c7300-9e93-11eb-82f6-6feae5a02b56.png)

I see that the hashrate is still as high/low as before.

What is the size of the L2 cache of your A72?

Scratchpad size per thread is 2048KB, if all threads combined dont fit inside the L2 Cache, hashrate suffers a LOT!

Wikipedia says something about 512 to 4096 L3 cache size, so 2 threads would be maximum? Just try it out!

According to https://xmrig.com/benchmark, an A72 can reach 100H/s for a single thread!

Or try another coin/algorithm ^^

**Comment by Shai0Hulud** [comment]
> it's been fun optimizing this far. 

Yeah, I can relate to that. ^^ 

> Again from what I've found on the raspberry pi 4, it doesn't have a AES

Still I'm confused as this A72 seems to have AES: [https://xmrig.com/benchmark/63bxi6](https://xmrig.com/benchmark/63bxi6), but googling for ARM chips, they seem to be something like construction kits. ^^ Or surprise Kinder Eggs ^^

**Comment by Spudz76** [comment]
> Still I'm confused as this A72 seems to have AES

Yes some do, but the Raspberry Pi Foundation refuses to pay the AES licensing thus their CPUs never have it.  AES is a separately licensed feature, available for use, but not when the system integrator doesn't pay for it.

Similar to how many low power and cheaper Intels have all the silicon in them for AES but then just have the flag shut off.  L55xx xeons for example, or many i3/i5.
