### ISSUE TITLE
Problems making XMRig in Raspberry PI

### ISSUE THREAD

**Issue by fintan226** [xmrig/xmrig#2281]
/home/pi/xmrig/src/crypto/cn/sse2neon.h:122:2: error: #error "Unsupported tar. Must be either ARMv7-A+NEON or ARMv8-A."
 #error "Unsupported target. Must be either ARMv7-A+NEON or ARMv8-A."
  ^~~~~
^Cmake[2]: *** [CMakeFiles/xmrig.dir/build.make:2403: CMakeFiles/xmrig.dir/srrypto/cn/CnHash.cpp.o] Interrupt
make[1]: *** [CMakeFiles/Makefile2:118: CMakeFiles/xmrig.dir/all] Interrupt
make: *** [Makefile:84: all] Interrupt
This is the error I get when trying to make XMRig.

**Comment by jsonkey1** [comment]
crazy guy. Raspberry PI can earn 1$ in one year?

**Comment by SChernykh** [comment]
`#error "Unsupported target. Must be either ARMv7-A+NEON or ARMv8-A."`
Compile for ARMv8-A - install 64-bit Linux and 64-bit compiler.

**Comment by fintan226** [comment]
> `#error "Unsupported target. Must be either ARMv7-A+NEON or ARMv8-A."`
> Compile for ARMv8-A - install 64-bit Linux and 64-bit compiler.



> crazy guy. Raspberry PI can
