### ISSUE TITLE
OSX running xmrig.exe

### ISSUE THREAD

**Issue by danpilgrim** [xmrig/xmrig#229]
So, when I run xmrig.exe on OSX.. I get this error
![screen shot 2017-11-29 at 2 41 46 am](https://user-images.githubusercontent.com/15642286/33369268-39907948-d4b1-11e7-9b7f-62ee73f401a9.png)
So, when I copy the config.json to that folder, I run it again and get this new error..
![screen shot 2017-11-29 at 2 43 09 am](https://user-images.githubusercontent.com/15642286/33369279-40c88052-d4b1-11e7-9dae-0040acdac432.png)

Any help?

**Comment by xmrig** [comment]
Please show your config.json, config file must be valid JSON.
Thank you.

**Comment by sanminsoe** [comment]
I have same issue. Help us to show the right direction.
