### ISSUE TITLE
the xmrig don't inicialize

### ISSUE THREAD

**Issue by gutamen** [xmrig/xmrig#2290]
I try many things but this window stay equal ( I am from Brazil, sorry by my poor english)
and after push enter the window simply close
![Captura de Tela (4)](https://user-images.githubusercontent.com/82832154/115321651-a4444c00-a15a-11eb-81d9-950722a31f69.png)

![Captura de Tela (5)](https://user-images.githubusercontent.com/82832154/115321637-9e4e6b00-a15a-11eb-9171-578392a44ee6.png)
![Captura de Tela (2)](https://user-images.githubusercontent.com/82832154/115321644-a0b0c500-a15a-11eb-8a37-287fe943e959.png)
![Captura de Tela (3)](https://user-images.githubusercontent.com/82832154/115321648-a27a8880-a15a-11eb-84b3-9caf4315edb9.png)

**Comment by alexandregf4** [comment]
Hi,

I'm also experiencing the same issue. I tried changing pools and even miner versions. xmrig.exe did not start in any of those tries.

When executing from terminal I see return code 0 coming out from xmrig.exe. I tested everything with my antivirus and Windows Defender both disabled.
