### ISSUE TITLE
CPU consumption of OpenCL vs CUDA

### ISSUE THREAD

**Issue by clflush** [xmrig/xmrig#2294]
Hi, I am mining XMR on 2 Xeon machines. On these 2 machines, I had to put in GPUs, one with 750Ti, the other with RX550. Since they are there, I thought might as well mine Astrobwt. That was when I noticed a significant randomx hashrate dropping when i started the xmrig opencl mining (no-cpu option), which is not happening on the machine mining Astrobwt using xmrig cuda. Any ideas why it is like that?

**Comment by clflush** [comment]
Further testing (with MoneroOcean and its modified algo switching xmrig) showed that mining using AMD GPU, regardless of the algo, will take away RandomX hashrates. I suspect something similar for Nvidia too but the effect is less obvious. I wonder if it is the devices itself or is the mining code's issue? 

If it is the devices, I would just switch out my AMD with Nvidia. If it is the code, would it be fixable?

**Comment by Spudz76** [comment]
You can set the affinity of the GPU handler thread to stay on a cpu/core that is not mining.  Otherwise it jumps around or parks wherever it likes, whenever it likes.

Linux or Windows?  Sometimes the Windows drivers freak out when there is also an Intel iGPU and driver.  DDU to the ground and install only the AMD driver.  Possibly also use the option in DDU to block automatic driver installation through Windows Update (or it will put the Intel driver back).  I have never noticed any problem dual-wield with Linux.

**Comment by clflush** [comment]
> You can set the affinity of the GPU handler thread to stay on a cpu/core that is not mining. Otherwise it jumps around or parks wherever it likes, whenever it likes.
> 
> Linux or Windows? Sometimes the Windows drivers freak out when there is also an Intel iGPU and driver. DDU to the ground and install only the AMD driver. Possibly also use the option in DDU to block automatic driver installation through Windows Update (or it will put the Intel driver back). I have never noticed any problem dual-wield with Linux.

Hey thanks! Will try to set the affinity. 
Linux.

**Comment by clflush** [comment]
hey, Just want to give a quick update on my test. So setting affinity works!! 

And I verified that xmrig opencl is consuming cpu compared to xmrig cuda, the latter being almost negligible. Verified on 4 different machines, 2 cuda and 2 opencl.

**Comment by Spudz76** [comment]
CPU mining is sensitive to being cache-evicted as most of its speed happens by loading cache once and then operating on it with ultra low latency.  Other tasks step in on that core and interrupt the miner forcing it to reload cache again.

I have never bothered to set affinity, maybe I should.  Sometimes mining actually uses all cores so there is nowhere to park the GPU-xfer thread.  But usually there is at least a "fakecore" from HT that doesn't help mining (on most algos)...

**Comment by clflush** [comment]
Thanks for your suggestion. Prob true for Ryzen, with less cores but large L2 (yes, not L3). Intel, on the other hand, because of L2, cannot make full use of all the cores. Its almost like RandomX was targeted for Ryzen. 

In any case, if a Ryzen user whom setting affinity did not help, can re-open the case.
