### ISSUE TITLE
Xmrig on iSH Shell (iOS ) it’s posible?

### ISSUE THREAD

**Issue by deancastill** [xmrig/xmrig#2308]
Do any professional friends know how to set config to run the mining

I've seen instruction of this 

https://xmrig.com/docs/miner/build/alpine

Because I realized iSH shell based on Alpine that showed upside.but I don't know when I Paste on the same config when I run the Android' phone with the same code but didn't worked. Does anyone can help or give an advice to run the mining thank you all guys!

![image](https://user-images.githubusercontent.com/83043770/115950535-d0890100-a4a9-11eb-8b38-e457e38c6e1d.png)

**Comment by NobelEvil** [comment]
try this one: ./xmrig -a cryptonight -o us-west.minexmr.com:4444 -u your_wallet_id -p × --rig-id ProMax11

**Comment by deancastill** [comment]
> try this one: ./xmrig -a cryptonight -o us-west.minexmr.com:4444 -u your_wallet_id -p × --rig-id ProMax11 

Thank u so much but it didn't work ![image](https://user-images.githubusercontent.com/83043770/116950488-2486a900-ac53-11eb-9e3c-c6e24f8ddb4b.png)

**Comment by deancastill** [comment]
This is where I followed those instructions 
![image](https://user-images.githubusercontent.com/83043770/116952126-e475f500-ac57-11eb-9005-87d4b215501c.png)

**Comment by deancastill** [comment]
> try this one: ./xmrig -a cryptonight -o us-west.minexmr.com:4444 -u your_wallet_id -p × --rig-id ProMax11 

Thank u but it didn't worked, did I do something wrong? I've posted on above comentes please could you can help about ?
