### ISSUE TITLE
Hi, I have some questions regarding this project

### ISSUE THREAD

**Issue by Joe23232** [xmrig/xmrig#2311]
Hi, I have some questions regarding this project:

1. Am I able to import it as a library/crate into my own [Rust](https://www.rust-lang.org/) programming language code and integrate it into my own software so I can compile all into a single executable?
2. Does it support either [Beam](https://beam.mw/),  [Zcash](https://z.cash/) or [Monera](https://www.getmonero.org/) or any other privacy respecting cryptocurrency?
3. How efficient is it compared to something like [gminer](https://github.com/develsoftware/GMinerRelease)?
4. Do you guys get a commission from my cryptomining if I were to use this library/crate?
5. How well maintained is this project? How many people are working on it?

**Comment by Spudz76** [comment]
1. Not easily I'd guess, but then again this is the first time I've heard of Rust.  Also, why?
2. No, the supported coins/algos are always [listed here](https://github.com/xmrig/xmrig/blob/master/doc/ALGORITHMS.md#algorithm-names)
3. Generally equal, but gminer supports some additional algos (c29 types, Ethash).  It might be slightly faster on KawPow
4. Not if you hack the donation minimum limit in the code and set donation to 0, which should be easy once you've learned enough C++ to Rust it up (can't be done on gminer, so your hashrate can be donation percent better, gminer has various donation percentages per algo)  Somewhat prefer if you've donated some other way to the project then, though (such as I lurk the Issues, occasionally submit useful Pull Requests... try to give back some value)
5. Very, updates are almost annoyingly often.  Between several and many.

**Comment by Joe23232** [comment]
> Not easily I'd guess, but then again this is the first time I've heard of Rust. Also, why?

Can I at least import it into a C++ library at least so that I can then generate one executable and tightly integrate it within my software for my own PC?

> No, the supported coins/algos are always listed here

Do you happen to know which one is a privacy oriented focused cryptocurrency?

> Not if you hack the donation minimum limit in the code and set donation to 0, which should be easy once you've learned enough C++ to Rust it up (can't be done on gminer, so your hashrate can be donation percent better, gminer has various donation percentages per algo) Somewhat prefer if you've donated some other way to the project then, though (such as I lurk the Issues, occasionally submit useful Pull Requests... try to give back some value)

Right I see thanks.

> Very, updates are almost annoyingly often. Between several and many.

Thanks man.

**Comment by weixianfenzi** [comment]
It's GPL 3.0 license

**Comment by Joe23232** [comment]
Thanks mate

**Comment by AndyRPH** [comment]
To correct the above, this absolutely supports Monero, although I think the reply you for was because you spelled it MonerA but linked to monero's info.

**Comment by Joe23232** [comment]
@AndyRPH Right my mistake :)
