### ISSUE TITLE
Limit the CPU usage web browsing while mining

### ISSUE THREAD

**Issue by hss78** [xmrig/xmrig#2316]
Hey i am using "--cpu-priority 0" but it is still laggy for web browsing.Is it possible to use example %80 CPU usage for mining,so we can web browsing without lag ? Thanks.

**Comment by snipeTR** [comment]
cmd.exe /c start /LOW "xmrig" xmrig.exe

**Comment by hss78** [comment]
Will we add this to start.cmd ? Thanks

**Comment by hss78** [comment]
Thanks for the info
