### ISSUE TITLE
How to compile for android?

### ISSUE THREAD

**Issue by misebek** [xmrig/xmrig#232]
What should I do (step by step) to compile this for Android? My devices are "armeabi-v7a" architecture and have android-19 (4.4) and android-22 (5.1). (If possible, I want to do everything in command line / terminal emulator)

**Comment by Halo07** [comment]
An android package is on working at the developer list

**Comment by cmorsucci** [comment]
Any news?

**Comment by wjchen** [comment]
My android version: https://github.com/wjchen/xmrig

**Comment by cmorsucci** [comment]
Could you update the guide to be able to compile on android?

**Comment by Halo07** [comment]
Please update the guide or make a new quick guite on how to compile!

**Comment by kaiwenjui** [comment]
@wjchen armeabi-v7a can't be run. android4.4.4
