### ISSUE TITLE
./xmrig:  /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by xliquid808** [xmrig/xmrig#2326]
Compiling works, tested on an Ubuntu x64 VM, executing in the same VM still works, then when the program is executed on another laptop I get the error ./xmrig:  /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

**To Reproduce**
Compile on an Ubuntu VM, start the compiled file on another physical linux device.

**Expected behavior**
Miner starts mining.

**Comment by SChernykh** [comment]
I don't know what you really expect... If you compiled it with newer GLIBC and tried to run on a system with older GLIBC, of course it won't run. Compile it again on that system.

**Comment by xliquid808** [comment]
> I don't know what you really expect... If you compiled it with newer GLIBC and tried to run on a system with older GLIBC, of course it won't run. Compile it again on that system.

Yes, I way too sleepy when I opened this issue, everything works now
