### ISSUE TITLE
Problem building for freebsd arm64

### ISSUE THREAD

**Issue by NoResponse13** [xmrig/xmrig#2330]
```
root@generic:~/xmrig/build # uname -a
FreeBSD generic 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 06:10:43 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/arm64.aarch64/sys/GENERIC  arm64
```

```
root@generic:~/xmrig/build # cmake ..
-- The C compiler identification is Clang 11.0.1
-- The CXX compiler identification is Clang 11.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Use ARM_TARGET=8 (aarch64)
-- Performing Test XMRIG_ARM_CRYPTO
-- Performing Test XMRIG_ARM_CRYPTO - Success
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found HWLOC: /usr/local/lib/libhwloc.so
-- Found UV: /usr/local/lib/libuv.a
-- Looking for __builtin___clear_cache
-- Looking for __builtin___clear_cache - not found
-- WITH_MSR=OFF
-- Found OpenSSL: /usr/local/lib/libcrypto.so (found version "1.1.1k")
-- Configuring done
-- Generating done
-- Build files have been written to: /root/xmrig/build
```

```
root@generic:~/xmrig/build # make -j4
Scanning dependencies of target ethash
Scanning dependencies of target argon2
[  1%] Building C object src/3rdparty/libethash/CMakeFiles/ethash.dir/ethash_internal.c.o
[  1%] Building C object src/3rdparty/libethash/CMakeFiles/ethash.dir/keccakf800.c.o
[  1%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/core.c.o
[  1%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/argon2.c.o
[  2%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/encoding.c.o
...
[ 40%] Building CXX object CMakeFiles/xmrig.dir/src/backend/cpu/platform/BasicCpuInfo_arm.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig.dir/src/backend/cpu/platform/lscpu_arm.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig.dir/src/backend/opencl/cl/OclSource.cpp.o
/root/xmrig/src/backend/cpu/platform/BasicCpuInfo_arm.cpp:31:13: fatal error: 'asm/hwcap.h' file not found
#   include <asm/hwcap.h>
            ^~~~~~~~~~~~~
[ 41%] Building CXX object CMakeFiles/xmrig.dir/src/backend/opencl/generators/ocl_generic_cn_generator.cpp.o
1 error generated.
--- CMakeFiles/xmrig.dir/src/backend/cpu/platform/BasicCpuInfo_arm.cpp.o ---
*** [CMakeFiles/xmrig.dir/src/backend/cpu/platform/BasicCpuInfo_arm.cpp.o] Error code 1
...

```

**Comment by RS102839** [comment]
You are doing better than people tring to build for the arm64 on the Mac M1, as at least the scripts are recognizing:
    
    -- Use ARM_TARGET=8 (aarch64)
    -- Performing Test XMRIG_ARM_CRYPTO
    -- Performing Test XMRIG_ARM_CRYPTO - Success

...watching this thread for hints on solving the M1 arm64 build problem.

**Comment by Spudz76** [comment]
Disable OpenCL and CUDA (using cmake args `-DWITH_OPENCL=OFF -DWITH_CUDA=OFF`)

**Comment by NoResponse13** [comment]
> 
> 
> Disable OpenCL and CUDA (using cmake args `-DWITH_OPENCL=OFF -DWITH_CUDA=OFF`)

`root@generic:~/xmrig/build # rm -rf ./*
root@generic:~/xmrig/build # ls
root@generic:~/xmrig/build #`

`root@generic:~/xmrig/build # cmake .. -DWITH_OPENCL=OFF -DWITH_CUDA=OFF
-- The C compiler identification is Clang 11.0.1
-- The CXX compiler identification is Clang 11.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Use ARM_TARGET=8 (aarch64)
-- Performing Test XMRIG_ARM_CRYPTO
-- Performing Test XMRIG_ARM_CRYPTO - Success
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found HWLOC: /usr/local/lib/libhwloc.so
-- Found UV: /usr/local/lib/libuv.a
-- Looking for __builtin___clear_cache
-- Looking for __builtin___clear_cache - not found
-- WITH_MSR=OFF
-- Found OpenSSL: /usr/local/lib/libcrypto.so (found version "1.1.1k")
-- Configuring done
-- Generating done
-- Build files have been written to: /root/xmrig/build
root@generic:~/xmrig/build #`

`root@generic:~/xmrig/build # make -j4
-- Use ARM_TARGET=8 (aarch64)
-- WITH_MSR=OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /root/xmrig/build
Scanning dependencies of target ethash
Scanning dependencies of target argon2
[  1%] Building C object src/3rdparty/libethash/CMakeFiles/ethash.dir/keccakf800.c.o
[  1%] Building C object src/3rdparty/libethash/CMakeFiles/ethash.dir/ethash_internal.c.o
[  2%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/argon2.c.o
[  2%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/core.c.o
[  2%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/encoding.c.o
[  3%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/genkat.c.o
...
[ 52%] Building CXX object CMakeFiles/xmrig.dir/src/backend/cpu/CpuThread.cpp.o
[ 53%] Building CXX object CMakeFiles/xmrig.dir/src/backend/cpu/CpuThreads.cpp.o
[ 53%] Building CXX object CMakeFiles/xmrig.dir/src/backend/cpu/CpuWorker.cpp.o
[ 54%] Building CXX object CMakeFiles/xmrig.dir/src/backend/cpu/platform/HwlocCpuInfo.cpp.o
[ 54%] Building CXX object CMakeFiles/xmrig.dir/src/backend/cpu/platform/BasicCpuInfo_arm.cpp.o
[ 55%] Building CXX object CMakeFiles/xmrig.dir/src/backend/cpu/platform/lscpu_arm.cpp.o
[ 56%] Building CXX object CMakeFiles/xmrig.dir/src/App.cpp.o
[ 56%] Building CXX object CMakeFiles/xmrig.dir/src/core/config/Config.cpp.o
/root/xmrig/src/backend/cpu/platform/BasicCpuInfo_arm.cpp:31:13: fatal error: 'asm/hwcap.h' file not found
#   include <asm/hwcap.h>
            ^~~~~~~~~~~~~
[ 57%] Building CXX object CMakeFiles/xmrig.dir/src/core/config/ConfigTransform.cpp.o
1 error generated.
--- CMakeFiles/xmrig.dir/src/backend/cpu/platform/BasicCpuInfo_arm.cpp.o ---
*** [CMakeFiles/xmrig.dir/src/backend/cpu/platform/BasicCpuInfo_arm.cpp.o] Error code 1

make[2]: stopped in /root/xmrig/build
In file included from /root/xmrig/src/core/config/ConfigTransform.cpp:20:
/root/xmrig/src/core/config/ConfigTransform.h:43:10: warning: private field 'm_opencl' is not used [-Wunused-private-field]
    bool m_opencl           = false;
         ^
1 warning generated.
1 error

make[2]: stopped in /root/xmrig/build
--- CMakeFiles/xmrig.dir/all ---
...`

**Comment by Spudz76** [comment]
This might help that part, for FreeBSD 12 or higher (noting you have 13)
[arm64-fbsd-try1.patch.txt](https://github.com/xmrig/xmrig/files/6410808/arm64-fbsd-try1.patch.txt)

**Comment by NoResponse13** [comment]
```
root@generic:~/xmrig/build # cmake ..
...
root@generic:~/xmrig/build # make -j4
...
[ 40%] Building CXX object CMakeFiles/xmrig.dir/src/backend/cpu/platform/HwlocCpuInfo.cpp.o
[ 40%] Building CXX object CMakeFiles/xmrig.dir/src/backend/cpu/platform/BasicCpuInfo_arm.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig.dir/src/backend/cpu/platform/lscpu_arm.cpp.o
/root/xmrig/src/backend/cpu/platform/BasicCpuInfo_arm.cpp:36:12: warning: 'HWCAP_AES' macro redefined [-Wmacro-redefined]
#   define HWCAP_AES (1 << 3)
           ^
/usr/include/machine/elf.h:98:9: note: previous definition is here
#define HWCAP_AES               0x00000008
        ^
/root/xmrig/src/backend/cpu/platform/BasicCpuInfo_arm.cpp:71:27: error: use of undeclared identifier 'getauxval'
    m_flags.set(FLAG_AES, getauxval(AT_HWCAP) & HWCAP_AES);
                          ^
1 warning and 1 error generated.
--- CMakeFiles/xmrig.dir/src/backend/cpu/platform/BasicCpuInfo_arm.cpp.o ---
*** [CMakeFiles/xmrig.dir/src/backend/cpu/platform/BasicCpuInfo_arm.cpp.o] Error code 1

make[2]: stopped in /root/xmrig/build
1 error

make[2]: stopped in /root/xmrig/build
--- CMakeFiles/xmrig.dir/all ---
*** [CMakeFiles/xmrig.dir/all] Error code 2
....
```

**Comment by SChernykh** [comment]
@NoResponse13 This is because `getauxval` is not available on FreeBSD on ARM. Can you try this better fix: https://github.com/xmrig/xmrig/pull/2340 ?

**Comment by NoResponse13** [comment]
perfect
