### ISSUE TITLE
XmRig don't open

### ISSUE THREAD

**Issue by samjviana** [xmrig/xmrig#2336]
I'm trying to configure two low end processor to mine with XmRig, one is intel core i3-4170 and an i7-4770k. The thing is that xmrig start and closes and don't even show any error messages. Even using "xmrig.exe --help" the help message don't show up. Funny thing, I have another machine with an i3-4170 that is working fine. 
How can I see the cause of the error.

**Comment by Spudz76** [comment]
Likely some antivirus garbage, set your miner folder to whitelisted in everything.

**Comment by samjviana** [comment]
After some testing i found out that the it was the firewall that was blocking the miner, silly me lol.
thanks anyway.

**Comment by Spudz76** [comment]
Also running a command prompt and running xmrig (or your launcher bat file) from there will avoid the window just closing...
