### ISSUE TITLE
Missing xmrig execution file in xmrig-6.12.1-macos-x64.tar.gz release

### ISSUE THREAD

**Issue by Sammed98** [xmrig/xmrig#2342]
**Describe the bug**
The download the xmrig-6.12.1-macos-x64.tar.gz file, unzip it and open the folder but cannot find the xmrig execution file or something with a Terminal image or application. It just has a config.json and a SHA256 file. 

**To Reproduce**
Download xmrig-6.12.1-macos-x64.tar.gz and unzip

**Expected behavior**
It should have the terminal app

**Required data**
 - OS: [Mac Intel processor]

**Comment by SChernykh** [comment]
Add the folder where you unpack it to antivirus exceptions.

**Comment by RS102839** [comment]
FYI:  It installed for me a few days ago.

**Comment by harireddy05** [comment]
I've listed the folder as an exclusion where i'm downloading the source (https://github.com/fireice-uk/xmr-stak/archive/refs/tags/1.0.5-rx.zip). Still missing the exe file. am i missing anything?

**Comment by Sammed98** [comment]
Ok. I understood the issue here. The execution file or the application with the terminal image is not present in the "x64" in the latest version. Download from the release 6.12.0. You will get the application.

**Comment by harireddy05** [comment]
I got it to work using this link here - https://xmrig.com/download
Also checked the 6.12.0 version. Works too.
