### ISSUE TITLE
Mining on android using ubuntu

### ISSUE THREAD

**Issue by Clerisa** [xmrig/xmrig#2359]
I try experiment mining using my android phone.
Realme 6 pro, ROG 2 and ROG 3.
Its work, but i don't know how to setting my configuration for mining, like how to set my cpu core for mining, its use (8 threads) make my phone lag and hot especially for ROG PHONE.😂
Let me know how to set my thread to 5 or 6
![P_20210509_160257](https://user-images.githubusercontent.com/83861587/117564887-f5ec5080-b0e0-11eb-914c-c8a49d7900d3.jpg)

**Comment by SChernykh** [comment]
If you use command line, add `--threads=5` to it. If you use config.json, find threads list for RandomX that should look like `"rx": [0, 1, 2, 3, 4, 5, 6, 7],` and remove some threads from it.

**Comment by Clerisa** [comment]
> If you use command line, add `--threads=5` to it: https://xmrig.com/docs/miner/command-line-options If you use config.json, find threads list for RandomX that should look like `"rx": [0, 1, 2, 3, 4, 5, 6, 7],` and remove some threads from it.

**Comment by Clerisa** [comment]
Ty let me try its, i hope i know what doing there, i'm newbie 😂

**Comment by Monsluxe** [comment]
Please let me know when yoyr phone is blowing up, please just think before
using xmrig on smartphone and DYOR about how dangerous and useless it is

**Comment by Clerisa** [comment]
I know that, I'm just wondering how it works on phone 😂
I am not a man if I am afraid of danger.
That right it useless for you, but not for some people out there who don't have enough funds to build their own rig, a lot of people like that on YouTube all know the dangers of doing that, so we need proper settings so we don't endanger ourselves.
