### ISSUE TITLE
info about failover.xmrig.com

### ISSUE THREAD

**Issue by kintaro1981** [xmrig/xmrig#237]
is failover.xmrig.com a working pool?
what's the payment threshold?
where can I find more info?

**Comment by xmrig** [comment]
It not a pool, it's proxy. Old node.js version of https://github.com/xmrig/xmrig-proxy
Thank you.

**Comment by kintaro1981** [comment]
oh... I set it as a pool and was working (without payment).
Do I need to use another one to get payments?

**Comment by xmrig** [comment]
Yep you need choice some pool http://moneropools.com/ or https://www.hashvault.pro/

**Comment by tank46** [comment]
I have 4 days mining in failover.xmrig.com. I wonder if I'm loosing my time using this pool? When I configured the config.json file, I set my wallet address....That was useless?

**Comment by xmrig** [comment]
Miner on start show you what pools will be used. You can use https://config.xmrig.com/xmrig to generate config.json. Thanks for your 4 days donation.

**Comment by tank46** [comment]
Dear @xmrig, I already knew that site and that wasn't actually my question, thanks anyway. Then let me clarify my concerns: I have by now more than a week using a config.json apparently wrong-configured  (...."failover.xmrig.com:443"....). That bring me a couple of questions:

1) Did I loos all the work (effort) provide so far if I change pool at the config file now?
2) If I do not loos my time, what can I do to retrieve the coins mined or to compute the "Accepted" so far ?
3) When you say "failover.xmrig.com:443" is a proxy, what exactly does it means?
