### ISSUE TITLE
DNS error: "temporary failure" on a VPS

### ISSUE THREAD

**Issue by MernGG** [xmrig/xmrig#2372]
Mining on a VPS and receiving an error
I am mining on a CPU optimized vultr VPS and getting the error "us-west.minexmr.com:443 DNS error: "temporary failure"". To set up the rig I used the advanced ubuntu setup. 

How to reproduce:
Not sure but you could try the free trial on vultr since they offer a 100 dollar starter credit.

Expected Behavior: 
The rig to mine xmr as intended.

Data: 
![image](https://user-images.githubusercontent.com/46382789/118147156-27f10180-b3c4-11eb-90ff-d4bcf8c07729.png)
 - OS: Ubuntu

Additional Context: 
I used the exact same setup process on another VPS service and it works just fine so it might be a problem with the VPS provider.

**Comment by xmrig** [comment]
They blocked DNS requests to major pools, so you can switch to a smaller pool (better option) or add IP addresses to `/etc/hosts` file.
Thank you.

**Comment by MernGG** [comment]
> They blocked DNS requests to major pools, so you can switch to a smaller pool (better option) or add IP addresses to `/etc/hosts` file.
> Thank you.

Thank you very much worked perfectly!

**Comment by avasantha** [comment]
I am also trying the same with vultr with the free credits. Can you please let me know what would be the IP I need to add in the hosts file? May be you could show me how does the hosts file would look like. 

Thanks in advance.

**Comment by MernGG** [comment]
> I am also trying the same with vultr with the free credits. Can you please let me know what would be the IP I need to add in the hosts file? May be you could show me how does the hosts file would look like.
> 
> Thanks in advance.

add this to the etc/hosts file
51.81.151.235 us-west.minexmr.com
147.135.37.31 us-west.minexmr.com

also in advance don't use too many computers at once because they will limit your CPU and it won't be as profitable.

**Comment by wule108** [comment]
Specifying the domain name as a fixed IP is a stupid practice，In order to prevent the mining pool from being ddos, multiple ips were resolved with dns，Therefore, the IP corresponding to the domain name will change，so the correct approach should be like this echo 'nameserver 8.8.8.8' >> /etc/resolv.conf. Don't add IP addresses to /etc/hosts file.

> Mining on a VPS and receiving an error
> I am mining on a CPU optimized vultr VPS and getting the error "us-west.minexmr.com:443 DNS error: "temporary failure"". To set up the rig I used the advanced ubuntu setup.
> 
> How to reproduce:
> Not sure but you could try the free trial on vultr since they offer a 100 dollar starter credit.
> 
> Expected Behavior:
> The rig to mine xmr as intended.
> 
> Data:
> ![image](https://user-images.githubusercontent.com/46382789/118147156-27f10180-b3c4-11eb-90ff-d4bcf8c07729.png)
> 
> * OS: Ubuntu
> 
> Additional Context:
> I used the exact same setup process on another VPS service and it works just fine so it might be a problem with the VPS provider.

Specifying the domain name as a fixed IP is a stupid practice，In order to prevent the mining pool from being ddos, multiple ips were resolved with dns，Therefore, the IP corresponding to the domain name will change，so the correct approach should be like this echo 'nameserver 8.8.8.8' >> /etc/resolv.conf. Don't add IP addresses to /etc/hosts file.

**Comment by xmrig** [comment]
@wule108 When last time I checked, changing a nameserver didn't help, but I may remember it wrong, it was a few years ago or maybe they relaxed filtration. Right now changing a nameserver works fine.
Thank you.
