### ISSUE TITLE
Cannot open in windows 10 anymore

### ISSUE THREAD

**Issue by Abaraxe** [xmrig/xmrig#2374]
Hello, 

I used to be able to run the program without issues, now with the new windows update all of a sudden i got this message:

You are trying to open a (.sys) file. files like this are part of the operating system and can harm your system.

Then it gives me the option to pick a program to run the file, but nothing works. Please help me fix the issue, i would love to get mining aggain.

greetings,

Dennis

**Comment by SChernykh** [comment]
Add xmrig folder to antivirus exceptions and download it there again.
