### ISSUE TITLE
Standalone xmrig without configuration failed to compile

### ISSUE THREAD

**Issue by Halo07** [xmrig/xmrig#239]
I try to compile my own version of xmrig without configuration file. 
But i can't because i got an error: fatal error: uv.h: No such file or directory
How can i fix this? Or if is there another way to make a standalone version of xmrig?

**Comment by xmrig** [comment]
libuv mandatory dependency, you can use precompiled libuv version.
Thank you.

**Comment by Halo07** [comment]
but if i used precompiled libuv verssion (latest) after copile, xmrig request libuv.dll in the same dir

**Comment by xmrig** [comment]
Did you check compile docs https://github.com/xmrig/xmrig/wiki/Windows-Build ?
You can use https://github.com/xmrig/xmrig-deps/releases or build libuv byself, it's not too hard.
Official precompiled libuv provide only dynamic library (not static) so dll file required.
Thank you.

**Comment by Halo07** [comment]
i need to compile libuv on x64... That was the problem! Thank you!
