### ISSUE TITLE
3970x hashrate only 14kh/s

### ISSUE THREAD

**Issue by LianghaoLi-Hust** [xmrig/xmrig#2399]
I use two CPU (3950x and 3970x) to mine XMR
hashrate of 3950x is stable, always around 14kh/s
but two days ago hashrate of 3970x drop from 26kh/s to 14kh/s
I didn't change any setting

![49 235 112 100_7002 - 远程桌面连接 2021_5_21 10_50_54 (2)](https://user-images.githubusercontent.com/32161863/119075322-2c9c6200-ba23-11eb-9171-50caed325d3a.png)

**Comment by inkookz** [comment]
Your cpu is broken, consider selling it to me.

**Comment by SChernykh** [comment]
@LianghaoLi-Hust Your RAM is installed in wrong slots, you're not running in 4-channel mode. Check your motherboard manual and install in correct slots.

**Comment by LianghaoLi-Hust** [comment]
> @LianghaoLi-Hust Your RAM is installed in wrong slots, you're not running in 4-channel mode. Check your motherboard manual and install in correct slots.

Thanks

**Comment by Spudz76** [comment]
Make sure Memory Compression task and Memory Disagnostics task are all disabled, or it will run randomly sometimes and fight the hashrate (due to clogging memory bus).

Along with other wasteful background junk.
