### ISSUE TITLE
Cryptonight light FX8350

### ISSUE THREAD

**Issue by coulix** [xmrig/xmrig#241]
It detects 6 threads as the optimum, but 8 is the right number.
Out of the box, 6 threads, 650 mh/s

8 threads, 950 mh/s

AEON stak does 1320 mh/s

**Comment by xmrig** [comment]
It rare case when `--max-cpu-usage` option really works, 75% by default.
Thank you.

**Comment by coulix** [comment]
I had this one set to 100% but I will try again and report. Thks.

**Comment by lisergey** [comment]
I've seen hashrate 1235 H/s with
VERSIONS:     XMRig/2.4.2 libuv/1.14.1 gcc/7.2.0
HUGE PAGES:   available, enabled
CPU:          AMD FX(tm)-8350 Eight-Core Processor            (1) x64 AES-NI
THREADS:      4, cryptonight-lite, av=2, donate=2%, affinity=0xCA
or affinity=0xAA

**Comment by RyokoZekem** [comment]
I run into issues trying to run it on cryptonight-lite. It says share is above target. The hash rate is 900 h/s with cryptonight-lite but it just doesnt want to play nice.  I've tried disabling huge pages, changing thread count, changing to av=4 ect. Its the cryptonight-lite settings. Am I doing something wrong here?

**Comment by lisergey** [comment]
@RyokoZekem, try to reboot. It's weird, it should not be so, but my FX8350 sometimes slows with no reason. Simple stupid reboot helps, sometimes several times until hashrate is normal.
I tried many options, diagnosis, anything to find reasons why - not yet found.

with
    "algo": "cryptonight-lite", // cryptonight (default) or cryptonight-lite
    "av": 2,                    // algorithm variation, 0 auto select
    "threads": 4,               // number of miner threads
    "cpu-affinity": "0x55",     // set process affinity to CPU core(s), mask "0x3" for cores 0 and 1
it's stable 1234 h/s

**Comment by xmrig** [comment]
`cryptonight-lite` only for AEON coin, not usable for other coins like Monero, etc.
Spontaneous slow down can caused because background activity in OS, updates, antivirus scans or something like that.
Thank you.

**Comment by lisergey** [comment]
@xmrig, it is not slow down during run, it is when launched, and keeping it low. Re-launch does not help. Reboot usually helps, but sometimes two or three times.
I think it's kinda bug in the CPU handling/assinging L3 cache to cores.
I've seen in per-thread reports through API that some threads were running with "double cache" speed while in config was av=1. I think it does not relate to xmrig.

@xmrig, thank you for the great program! It's awesome, while simple and effective. My deep respect to you.
