### ISSUE TITLE
License question: Allowed to create repository with customized XMRig?

### ISSUE THREAD

**Issue by Shai0Hulud** [xmrig/xmrig#2413]
Hey there, Is it allowed that I open a repository where there is the program customized for my favorite mining pool?

Customized being only the config.json with pool url and so on, so users only have to add Wallet address?

Cheers!

**Comment by Spudz76** [comment]
Yeah like most open source licenses you can do whatever if the code is still public including your mods.

Just can't go wrapping it into Microsoft EZMiner 3.0 and sell that.

**Comment by Shai0Hulud** [comment]
Thank you!
