### ISSUE TITLE
xmrig wikipedia update info

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig#2416]
https://xmrig.com/docs/algorithms wrkz missing.

**Comment by xmrig** [comment]
It was renamed to `argon2/ninja` by request from Ninjacoin, this seems fair since WrkzCoin now uses `cn/upx2`. Old name `argon2/wrkz` is still supported just new primary alias added https://github.com/xmrig/xmrig/commit/1ce059da1ca3ee548a1b59119b68a4d54deddadf.
Thank you.
