### ISSUE TITLE
I have issues on mining a ovh vps

### ISSUE THREAD

**Issue by RobertIsaic** [xmrig/xmrig#2418]
I open my ovh vps and i put the xmrig 6.3.2, i make config and i have errors:
  msr kernel is not available
  FAILED TO APPLY MSR MOD, HASHRATE WIIL BE LOW

Vps info: 
-Make on a dedicat server
-2 CPU(amd epyc)
-8GB ram
-50GB SSD
-uname -r: 4.19-ovh-xxxx-std-ipv6-64

Ovh vps use CentOs but on ubuntu on this vps is same error but on my pc on Ubuntu isn't this error.

Sorry for my english, i am from Romania!

**Comment by SChernykh** [comment]
MSR mod works only on physical hardware, not inside a virtual machine.

**Comment by RobertIsaic** [comment]
Ok, but is posible mining Monero with xmrig on vps?

**Comment by SChernykh** [comment]
Possible, but without MSR. Also you need to check with your hoster if mining is allowed on vps.

**Comment by RobertIsaic** [comment]
![Captură de ecran de la 2021-06-03 08-50-46](https://user-images.githubusercontent.com/77294018/120594013-f3171e00-c448-11eb-8c44-4364051d822d.png)

**Comment by RobertIsaic** [comment]
How to mine with not 'Killed' without MSR?

**Comment by xmrig** [comment]
8 GB of memory is not enough for a CPU configured to use 4 NUMA nodes. You may disable NUMA in miner config https://github.com/xmrig/xmrig/blob/master/src/config.json#L25 or in motherboard bios if it is really physical hardware. Don't expect any significant hashrate without multiple memory channels filled and as result much more memory. New version of XMRig also will show information about memory modules installed.
Thank you.

**Comment by xmrig** [comment]
@Spudz76 8 GB of memory and 8+ GB of datasets it's no way to go.

**Comment by Spudz76** [comment]
Well yes that is also very true, but mostly ToS / I think even with 8GB to use (or hwloc disabled) it would still be killed by policy.

**Comment by RobertIsaic** [comment]
I have 16GB its ok

**Comment by RobertIsaic** [comment]
I resolve this problem, now i have 16GB ram

**Comment by spj2401Dev** [comment]
I have this problem too on my Rig. It isnt a VPS, but It still shows that. I have 128 GB ram installed in that thing and a AMD Ryzen 9 3950X running on Windows 10.

**Comment by Spudz76** [comment]
If you have some virtualization installed and active, it can turn the whole system to VM mode.

**Comment by XfedeX** [comment]
> 
> 
> I have this problem too on my Rig. It isnt a VPS, but It still shows that. I have 128 GB ram installed in that thing and a AMD Ryzen 9 3950X running on Windows 10.

Maybe the CPU doesn't have enough cache?
Also did you meant 12.8 GB of RAM? Or 128 GB of hard disk?

**Comment by spj2401Dev** [comment]
128 GB of ram.
