### ISSUE TITLE
failed to start WinRing0x64.sys driver: "WinRing0x64.sys not found"

### ISSUE THREAD

**Issue by XfedeX** [xmrig/xmrig#2419]
**Describe the bug**
MSR is not working even if i run as administrator. It says:

```
failed to start WinRing0x64.sys driver: "WinRing0x64.sys not found"
FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW
```

**To Reproduce**
Run xmrig.exe as administrator.

**Required data**
- OS: Windows 10
- CPU: Intel(R) Core(TM) i7-1065G7 @1.30 GHz 1.50 GHz (8 cores)

**Comment by XfedeX** [comment]
CLOSED: Mea culpa, i accidentaly deleted the file :(

**Comment by bears0** [comment]
What happened to me was antivirus quarantined it. Check Defender if this happens
