### ISSUE TITLE
'hwloc_get_numanode_obj_by_os_index' was not declared in this scope

### ISSUE THREAD

**Issue by code1010111** [xmrig/xmrig#2420]
[ 10%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/rx/RxNUMAStorage.cpp.o
/root/xmrig/xmrig/src/crypto/rx/RxNUMAStorage.cpp: In function 'bool xmrig::bindToNUMANode(uint32_t)':
/root/xmrig/xmrig/src/crypto/rx/RxNUMAStorage.cpp:49:24: error: 'hwloc_get_numanode_obj_by_os_index' was not declared in this scope
     hwloc_obj_t node = hwloc_get_numanode_obj_by_os_index(cpu->topology(), nodeId);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/xmrig/xmrig/src/crypto/rx/RxNUMAStorage.cpp:49:24: note: suggested alternative: 'hwloc_get_pu_obj_by_os_index'
     hwloc_obj_t node = hwloc_get_numanode_obj_by_os_index(cpu->topology(), nodeId);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        hwloc_get_pu_obj_by_os_index
make[2]: *** [CMakeFiles/xmrig.dir/build.make:2871: CMakeFiles/xmrig.dir/src/crypto/rx/RxNUMAStorage.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:163: CMakeFiles/xmrig.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by xmrig** [comment]
hwloc version? Oldest supported hwloc version is 1.10 which is already pretty ancient.
Thank you.

**Comment by code1010111** [comment]
my hwloc is 1.9
Thanks for help!

**Comment by code1010111** [comment]
use current stable version for hwloc - problem solved
