### ISSUE TITLE
Mining on NVIDIA Tesla K80

### ISSUE THREAD

**Issue by radimkohout** [xmrig/xmrig#2426]
Hello,
I've compiled your cuda plugin(https://github.com/xmrig/xmrig-cuda) for my Debian VM with Tesla K80 GPU. I've installed drivers for the GPU and nvidia-detect can see it... But the xmrig writes "No GPU found". Where is the problem?

**Comment by Spudz76** [comment]
what does `nvidia-smi` say

which CUDA Toolkit version did you compile against?

**Comment by Spudz76** [comment]
Also you may need cmake option `-DCUDA_ARCH=37` for it to build the perfect kernels.

**Comment by Spudz76** [comment]
And capability 3.7 was deprecated in v11.0 so it could be broken or abandoned in subsequent versions (will be gone in v12)

I might use CUDA Toolkit 10.2 for it / there are no new features or gains by using newer really (for mining, for Kepler).  It should run against whatever driver (are you on 460.80?) but there is a listing [here](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility__table-toolkit-driver) that tells which minimum driver for each Toolkit.

**Comment by radimkohout** [comment]
I've installed incorrect drivers. I've found that by running the nvidia-smi command... Now everything works...

**Comment by Spudz76** [comment]
It seemed like the current driver should have still worked according to readme's but yes the alternative is the nvidia-390 series which is still maintained to compile on current kernels.  It works even for Pascal series.

**Comment by ributmaestro** [comment]
> I've installed incorrect drivers. I've found that by running the nvidia-smi command... Now everything works...

hello can you teach how to make the xmrig-cuda on tesla k80?

**Comment by Spudz76** [comment]
Obtain CUDA Toolkit 10.2

Build according to instructions except also add `-DCUDA_ARCH=37` to the cmake command so it doesn't waste time building kernels for GPUs you don't have.

Copy result dll/so to xmrig run folder, enable cuda backend, should detect...
