### ISSUE TITLE
config server failover

### ISSUE THREAD

**Issue by warcries** [xmrig/xmrig#243]
hi guys,

how can I setup a server failover on config.json?

Sample config:

"pools": [
        {
            "url": "crypto01.server.com:443",   // URL of mining server
            "user": "asdf",                        // username for mining server
            "pass": "x",                       // password for mining server
            "keepalive": true,                 // send keepalived for prevent timeout (need pool support)
            "nicehash": false                  // enable nicehash/xmrig-proxy support
        }
    ],
// How do I add another sever failover here? Thanks in advance guys.

**Comment by xmrig** [comment]
Please check this comment https://github.com/xmrig/xmrig/issues/90#issuecomment-327483294
Thank you.
