### ISSUE TITLE
Topology became empty, aborting!

### ISSUE THREAD

**Issue by Tulasinathreddy** [xmrig/xmrig#2439]
**Describe the bug**
I `wget https://github.com/xmrig/xmrig/releases/download/v6.12.2/xmrig-6.12.2-linux-x64.tar.gz`
and tried running it on my new VPS 16GB RAM [ 9.60 GHz (4 x 2.40 GHz) ].

I am getting this error 
```
root@3dm3:~/xmrig# ./xmrig --help
Topology became empty, aborting!
Segmentation fault
root@3dm3:~/xmrig#
```

**To Reproduce**
I tried `./xmrig` with config same error , also tried `./xmrig --help` same error.

**Expected behavior**
./xmrig with config should start mining and ./xmrig --help should give list of commands avaliable.

**Required data**

 - Error when i run xmrig `Topology became empty, aborting!
     Segmentation fault`
 - Ubuntu 20.04

.... | ....
-- | --
Guaranteed CPU | 9.60 GHz (4 x 2.40 GHz)
RAM | 16384 MB + MB SWAP (used 241 MB)
Storage | 160 GB RAID (used 0.8 GB)
RAID Speed | 50 MB/s, 200 IOPS
Inode Limit | 0 (20000 per GB of storage) (used 0)
Port Speed | 100 Mbps

**Comment by Spudz76** [comment]
Probably need to build without hwloc

**Comment by Tulasinathreddy** [comment]
how can I get it?

**Comment by Spudz76** [comment]
Follow [build docs](https://xmrig.com/docs/miner/build) and use `-DWITH_HWLOC=OFF`...

**Comment by Tulasinathreddy** [comment]
thank you so much for the help its working now 😍😍
