### ISSUE TITLE
Unable to build xmrig for Windows.

### ISSUE THREAD

**Issue by Joe23232** [xmrig/xmrig#2452]
Hi I am trying to build it on Windows and I am having some issues with it.

I am following the MSYS method.

![image](https://user-images.githubusercontent.com/34926497/122917127-014dbf80-d3a1-11eb-8743-8bbe033fe46c.png)

I am doing number `4`.

```cmd
$ "c:\Program Files\CMake\bin\cmake.exe" .. -G "Unix Makefiles" -DXMRIG_DEPS=c:/xmrig-deps/gcc/x64
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/usr/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/usr/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find HWLOC (missing: HWLOC_LIBRARY HWLOC_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindHWLOC.cmake:25 (find_package_handle_standard_args)
  src/backend/cpu/cpu.cmake:30 (find_package)
  src/backend/backend.cmake:1 (include)
  CMakeLists.txt:44 (include)
```

I want to be able to build with HWLOC.

I am not too sure how to build this?

**Comment by FullStack116** [comment]
What operating system of windows are you using?

Best regards.

**Comment by Joe23232** [comment]
@FullStack116   This is Windows 10 mate.

**Comment by FullStack116** [comment]
> @FullStack116 This is Windows 10 mate :)

updated me previous post

**Comment by FullStack116** [comment]
> @FullStack116 This is Windows 10 mate :)

Also steps i did to make it work

Create folder c:\xmrig-deps
[Download ](https://xmrig.com/download) the most recent version of xmrig prebuilt dependencies  by using the green Code button and Download ZIP
Get cmake [here ](https://cmake.org/download/), unzip it.


Get msys2. Then run it (c:\msys64\mingw64.exe). You get a prompt.

Per https://xmrig.com/docs/miner/build/windows:

1. pacman -S mingw-w64-x86_64-gcc git make

2. git clone https://github.com/xmrig/xmrig.git

3. mkdir xmrig/build && cd xmrig/build

4. cmake/bin/cmake.exe .. -G “Unix Makefiles” -DXMRIG_DEPS=/j/crypto/monero/git/xmrig-deps/gcc/x64

5. make -j$(nproc)

**Comment by Joe23232** [comment]
@FullStack116 Hey man thanks for your response

> Download the most recent version of xmrig prebuilt dependencies by using the green Code button and Download ZIP

So am I able to still disable the donate level?

**Comment by FullStack116** [comment]
> @FullStack116 Hey man thanks for your response
> 
> > Download the most recent version of xmrig prebuilt dependencies by using the green Code button and Download ZIP
> 
> So am I able to still disable the donate level?

yes

Prebuilt xmrig requires 1% donation. To get rid of this:

git clone xmrig’s repo. Change src/donation.h to:

constexpr const int kDefaultDonateLevel = 0;
constexpr const int kMinimumDonateLevel = 0;

**Comment by Joe23232** [comment]
@FullStack116  Thanks for that mate :)

> Download the most recent version of xmrig prebuilt dependencies by using the green Code button and Download ZIP

Hey man sorry I don't quite understand what do you mean by _green code button_?

**Comment by Joe23232** [comment]
@FullStack116 

That seems to work, thanks :)
