### ISSUE TITLE
How to disable donation?

### ISSUE THREAD

**Issue by Joe23232** [xmrig/xmrig#2458]
![image](https://user-images.githubusercontent.com/34926497/123537475-fca75380-d772-11eb-9bb4-f8dc7f1398bc.png)

Hi I wanted to enquire like when I tried to type `0` it will change it to a `1`, how would I change it back to `0`?

**Comment by Spudz76** [comment]
You don't because 1% is the minimum unless you figure out where to change the minimums to 0.

Nobody will tell you where.  But the file happens to be named quite appropriately...

**Comment by Lonnegan** [comment]
It's pretty brazen to ask the developer how to disable developer fee. 👎
