### ISSUE TITLE
How do I chose RandomX algorithim in the config?

### ISSUE THREAD

**Issue by Joe23232** [xmrig/xmrig#2459]
So I am using [QRL](https://www.theqrl.org/) which supports RandomX.

![image](https://user-images.githubusercontent.com/34926497/123537794-aa673200-d774-11eb-9258-5fcbf624afb0.png)

In the config file configuration, how do I set it for RandomX?

**Comment by cmxhost** [comment]
if not available in preset mode pools mean you can retry at custom pool configuration

**Comment by Joe23232** [comment]
@cmxhost Where would I go to create a custom pool configuration?

**Comment by cmxhost** [comment]
just start from begining wizard
you will see at pool selection

**Comment by Joe23232** [comment]
@cmxhost 

![image](https://user-images.githubusercontent.com/34926497/123544355-3c336700-d796-11eb-8f2d-085393b9b0f6.png)


Ok so I can't seem to find RandomX in the Algorithm section and also I thought it would work with QRL as under the coin section I can't find QRL support.

**Comment by cmxhost** [comment]
just select rx/0

**Comment by Joe23232** [comment]
@cmxhost  And what about the Coin support, should I keep it at unspecified?

**Comment by cmxhost** [comment]
just leave it blank

**Comment by Joe23232** [comment]
@cmxhost THanks mate :)

ANother thing, 

[https://www.theqrl.org/](https://www.theqrl.org/) I am going here now and how do I find out the host and port number as it asks over here:

![image](https://user-images.githubusercontent.com/34926497/123544638-93860700-d797-11eb-963b-a82753073cae.png)


Also you see the three options `NiceHash` etc, which one should I pick?

**Comment by cmxhost** [comment]
if pool provider support nicehash then you can tick nicehash and as per pool address and port

**Comment by Joe23232** [comment]
@cmxhost Since I don't really understand how this stuff works,

I ALWAYS need a host and port number, am I correct?

**Comment by cmxhost** [comment]
yeah both are must

**Comment by Joe23232** [comment]
I see, thanks mate @cmxhost  :)

**Comment by Joe23232** [comment]
@cmxhost Sorry another thing.

From QRL wallet, I was provided a `json` file which gives me the `address` and `addressB32`, I would assume I would be putting the `address` (from the `*.json` file) into the `User` field, am I correct?

**Comment by cmxhost** [comment]
just fill in and try first

**Comment by Joe23232** [comment]
@cmxhost Thanks man,

Another question, I noticed that on this website that allows you to create the config file: http://pool.qrlmining.com/#getting_started

It asks for the hardware specification as shown in the image:

![image](https://user-images.githubusercontent.com/34926497/123545383-0f358300-d79b-11eb-9f43-2c85a68a8e8d.png)

but with xmrig's version it does not. So what is the hardware specification set to by default?

**Comment by cmxhost** [comment]
yes either way you can generate the config.json file

**Comment by Joe23232** [comment]
@cmxhost Sorry I meant like becase xmrig does not ask you the hardware specification, what is the default hardware specification set to?

**Comment by cmxhost** [comment]
> @cmxhost Sorry I meant like becase xmrig does not ask you the hardware specification, what is the default hardware specification set to?
check on your system

**Comment by Joe23232** [comment]
@cmxhost I mean like inside the `json` file, what is the hardware specificaiton set to since xmrig's own wizard does not give such options?

**Comment by cmxhost** [comment]
will autodetect by xmrig just start sudo ./xmrig

**Comment by Joe23232** [comment]
@cmxhost Thanks mate :)

In regards to [this](https://github.com/xmrig/xmrig/issues/2462#issuecomment-869611773) post that I made, what default `config.json` elements do I need to change?
