### ISSUE TITLE
amd gpu mining not working

### ISSUE THREAD

**Issue by arya6345** [xmrig/xmrig#2469]
CL_INVALID_HOST_PTR when calling clCreateBuffer with buffer size 2181038080

run the xmrig.exe to reproduce the behavior

just an error message like i said

![image](https://user-images.githubusercontent.com/86840789/124287572-5eecc380-db7a-11eb-87d7-b1745fb9ae5f.png)
OS is windows 7
![image](https://user-images.githubusercontent.com/86840789/124287791-a2dfc880-db7a-11eb-9103-b222537bbfb9.png)
![image](https://user-images.githubusercontent.com/86840789/124287847-b2f7a800-db7a-11eb-9291-fee61faefc9f.png)
![image](https://user-images.githubusercontent.com/86840789/124287916-c440b480-db7a-11eb-9e78-b4b40745dc7a.png)
![image](https://user-images.githubusercontent.com/86840789/124287981-d7ec1b00-db7a-11eb-822c-2593490a4db9.png)

The gpu is a Ati radeon hd 5570

**Comment by SChernykh** [comment]
RandomX dataset is 2 GB. Your GPU has 1 GB, system memory is 2 GB with only 0.5 GB free. Of course it can't allocate dataset anywhere.

**Comment by arya6345** [comment]
> RandomX dataset is 2 GB. Your GPU has 1 GB, system memory is 2 GB with only 0.5 GB free. Of course it can't allocate dataset anywhere.

can you tell me how to edit random dataset ?

**Comment by Spudz76** [comment]
You don't it's a requirement.  2080MB of dataset for RandomX.

Also Turks based GPUs don't work right with any driver newer than 15.x

**Comment by arya6345** [comment]
> You don't it's a requirement. 2080MB of dataset for RandomX.
> 
> Also Turks based GPUs don't work right with any driver newer than 15.x

ok but can you tell how to change the algo to cryptonight ?

**Comment by Spudz76** [comment]
Well you find a pool that serves your desired algorithm and configure it as your pool.  When it sends a job in a cryptonight algorithm, xmrig will follow along.

Currently you're mining on the donation pool because you've used the default/example config.json file. So even if you forced the algo it would just not work right (jobs being served by the pool are still `rx/0`).

**Comment by arya6345** [comment]
> Well you find a pool that serves your desired algorithm and configure it as your pool. When it sends a job in a cryptonight algorithm, xmrig will follow along.
> 
> Currently you're mining on the donation pool because you've used the default/example config.json file. So even if you forced the algo it would just not work right (jobs being served by the pool are still `rx/0`).

yeah but i'm gonna mine on hashvault

**Comment by arya6345** [comment]
or what pool should i use then sends the the job in cryptonight ?

**Comment by arya6345** [comment]
Closing this issue..
