### ISSUE TITLE
All-in-one (cpu-amd-nvidia) miner

### ISSUE THREAD

**Issue by hamstertheminer** [xmrig/xmrig#247]
Hi,
what about developing an all-in-one (cpu-amd-nvidia) mining software?
[xmr-stak](https://github.com/fireice-uk/xmr-stak) does it and it is very nice feature.
Thank you

**Comment by howTOdoIT2** [comment]
indeed will be an awesome feature

**Comment by xmrig** [comment]
I thinking about it, probably first milestone will be cpu+amd because CUDA is pain, strict compiler requirements and fat binary.
Thank you.

**Comment by hamstertheminer** [comment]
Hi,
it is a very important feature in my opinion. Of course, AMD GPU have better performance on cryptonight compared to nVidia GPU and so they have the priority.
Thank you

**Comment by QwertyJack** [comment]
I am now mining with 2 amd gpu and the cpu. I have to run 2 xmrig, one for cpu and the other for gpu.
I can't wait for a all-in-one xmrig 🥇

**Comment by NicNull** [comment]
With xmr-stak misbehaving behind proxy, xmrig unified is really what I need.
A lot of 3rd party software for running miner in idle mode and monitoring performance of cards require one binary to start/stop. makes it hard when having many instances of miner on same PC.

**Comment by xmrig** [comment]
Done in v5.
