### ISSUE TITLE
xmrig not working on Linux 

### ISSUE THREAD

**Issue by TimyIsCool** [xmrig/xmrig#2470]
if i try running xmrig i get this error 
![image](https://user-images.githubusercontent.com/74112751/124368721-ac8d2d00-dc5b-11eb-9f1c-1010e2924859.png)

**Comment by cmxhost** [comment]
Syntax is missing in config.json just recheck configuration.

**Comment by TimyIsCool** [comment]
ok im using the config wisard on the site 

This is my config

{
    "autosave": true,
    "cpu": true,
    "opencl": false,
    "cuda": false,
    "pools": [
        {
            "url": "xmrpool.eu:9999",
            "user": "42rrP8MT5mXAY4HRhH7ojv1jMtWe1wdDD4QjRnJyQ5ViPtSYHf1CzNNERD49b6p4yLdB8kveRzoVvbqFn5oebbFPEpHygjR",
            "keepalive": true,
            "tls": true
        }
    ]
}

**Comment by SChernykh** [comment]
If you downloaded xmrig binary from github, it won't work on Raspberry Pi. You need to build it yourself.

**Comment by TimyIsCool** [comment]
> If you downloaded xmrig binary from github, it won't work on Raspberry Pi. You need to build it yourself.

ok, will update you on how it goes

**Comment by cmxhost** [comment]
> If you downloaded xmrig binary from github, it won't work on Raspberry Pi. You need to build it yourself.
Confirm  particular ssl stratum wont work in xmrig

**Comment by cmxhost** [comment]
Confirm  particular ssl stratum wont work in xmrig and it's only works on clayminer

**Comment by TimyIsCool** [comment]
![image](https://user-images.githubusercontent.com/74112751/124393262-903bcf80-dcf1-11eb-9f64-da2922a3be6d.png)
what do i do with the xmrig.json

**Comment by TimyIsCool** [comment]
ok fixed it but i got this 
![image](https://user-images.githubusercontent.com/74112751/124393401-40113d00-dcf2-11eb-8387-b8e2bd39786e.png)
i have 1gb on my pi, how do i configure gpu mem on ubuntu server 21.04.1

**Comment by cmxhost** [comment]
In my cases I just playing around CPU not in GPU cause it won't support GPU acceleration

**Comment by TimyIsCool** [comment]
> In my cases I just playing around CPU not in GPU cause it won't support GPU acceleration

ok but how do i fix the bus error?

**Comment by cmxhost** [comment]
> > In my cases I just playing around CPU not in GPU cause it won't support GPU acceleration
> 
> ok but how do i fix the bus error?

It's like you not enough memory and try set threads to 1 should be working

**Comment by TimyIsCool** [comment]
will try now

**Comment by TimyIsCool** [comment]
> will try now

how do i do that again?

**Comment by cmxhost** [comment]
> > will try now
> 
> how do i do that again?

Find rx/0 in configuration and from 0,1,2,3 just set 0

**Comment by TimyIsCool** [comment]
can u change what to change for me cuz i cant get it to work

{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "colors": true,
    "title": true,
    "randomx": {
        "init": -1,
        "init-avx2": -1,
        "mode": "auto",
        "1gb-pages": false,
        "rdmsr": true,
        "wrmsr": false,
        "cache_qos": false,
        "numa": true,
        "scratchpad_prefetch_mode": 1
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "huge-pages-jit": false,
        "hw-aes": null,
        "priority": null,
        "memory-pool": false,
        "yield": true,
        "argon2-impl": null,
        "astrobwt-max-size": 550,
        "astrobwt-avx2": false,
        "argon2": [0, 1, 2, 3],
        "astrobwt": [0, 1, 2, 3],
        "cn": [0, 1, 2, 3],
        "cn-heavy": [0, 1, 2, 3],
        "cn-lite": [0, 1, 2, 3],
        "cn-pico": [0, 1, 2, 3],
        "cn/upx2": [0, 1, 2, 3],
        "rx": 0 [0, 1, 2, 3],
        "rx/wow": [0, 1, 2, 3],
        "cn/0": false,
        "cn-lite/0": false,
        "rx/arq": "rx/wow",
        "rx/keva": "rx/wow"
    },
    "opencl": {
        "enabled": false,
        "cache": true,
        "loader": null,
        "platform": "AMD",
        "adl": true
    },
    "cuda": {
        "enabled": false,
        "loader": null,
        "nvml": true
    },
    "log-file": null,
    "donate-level": 1,
    "donate-over-proxy": 1,
    "pools": [
        {
            "algo": null,
            "coin": null,
            "url": "xmrpool.eu:9999",
            "user": "42rrP8MT5mXAY4HRhH7ojv1jMtWe1wdDD4QjRnJyQ5ViPtSYHf1CzNNERD49b6p4yLdB8kveRzoVvbqFn5oebbFPEpHygjR",
            "pass": null,
            "rig-id": null,
            "nicehash": false,
            "keepalive": true,
            "enabled": true,
            "tls": true,
            "tls-fingerprint": null,
            "daemon": false,
            "socks5": null,
            "self-select": null,
            "submit-to-origin": false
        }
    ],
    "retries": 5,
    "retry-pause": 5,
    "print-time": 60,
    "health-print-time": 60,
    "dmi": true,
    "syslog": false,
    "tls": {
        "enabled": false,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "dns": {
        "ipv6": false,
        "ttl": 30
    },
    "user-agent": null,
    "verbose": 0,
    "watch": true,
    "pause-on-battery": false,
    "pause-on-active": false
}

**Comment by cmxhost** [comment]
Change "rx": 0 [0, 1, 2, 3], to "rx": [0],

**Comment by TimyIsCool** [comment]
oh ok

**Comment by TimyIsCool** [comment]
still doesnt work :(

**Comment by cmxhost** [comment]
dont try ssl

just copy paste this and see



{
    "cpu": true,
    "pools": [
        {
            "algo": "rx/0",
            "coin": "monero",
            "url": "xmrpool.eu:3333",
            "user": "42rrP8MT5mXAY4HRhH7ojv1jMtWe1wdDD4QjRnJyQ5ViPtSYHf1CzNNERD49b6p4yLdB8kveRzoVvbqFn5oebbFPEpHygjR",
            "pass": "x",
            "rig-id": "PI-3",
            "nicehash": false,
            "keepalive": true,
            "enabled": true,
        }
    ],

}

**Comment by TimyIsCool** [comment]
![image](https://user-images.githubusercontent.com/74112751/124396359-fa0fa580-dd00-11eb-82a5-8e2c5531f6a2.png)
nope

**Comment by cmxhost** [comment]
ok now go change again this will work
"rx": 0 [0, 1, 2, 3], to "rx": [0],

**Comment by TimyIsCool** [comment]
still nope

**Comment by cmxhost** [comment]
try this

{
    "autosave": true,
    "background": false,
    "colors": true,
    "title": true,
    "randomx": {
        "init": -1,
        "init-avx2": -1,
        "mode": "auto",
        "1gb-pages": false,
        "rdmsr": false,
        "wrmsr": false,
        "cache_qos": false,
        "scratchpad_prefetch_mode": 1
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "huge-pages-jit": false,
        "hw-aes": null,
        "priority": null,
        "memory-pool": false,
        "yield": true,
        "argon2-impl": null,
        "astrobwt-max-size": 550,
        "astrobwt-avx2": false,
        "argon2": [-1, -1, -1, -1],
        "astrobwt": [-1, -1, -1, -1],
        "cn": [-1, -1, -1, -1],
        "cn-heavy": [-1, -1, -1, -1],
        "cn-lite": [-1, -1, -1, -1],
        "cn-pico": [-1, -1, -1, -1],
        "cn/upx2": [-1, -1, -1, -1],
        "rx": [-1],
        "rx/wow": [-1, -1, -1, -1],
        "cn/0": false,
        "cn-lite/0": false,
        "rx/arq": "rx/wow",
        "rx/keva": "rx/wow"
    },
    "log-file": null,
    "donate-level": 1,
    "donate-over-proxy": 1,
    "pools": [
        {
            "algo": "rx/0",
            "coin": "monero",
            "url": "xmrpool.eu:3333",
            "user": "42rrP8MT5mXAY4HRhH7ojv1jMtWe1wdDD4QjRnJyQ5ViPtSYHf1CzNNERD49b6p4yLdB8kveRzoVvbqFn5oebbFPEpHygjR",
            "pass": "x",
            "rig-id": "PI-3",
            "nicehash": false,
            "keepalive": true,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false,
            "socks5": null,
            "self-select": null,
            "submit-to-origin": false
        }
    ],
    "retries": 5,
    "retry-pause": 5,
    "print-time": 60,
    "dmi": true,
    "syslog": false,
    "dns": {
        "ipv6": false,
        "ttl": 30
    },
    "user-agent": null,
    "verbose": 0,
    "watch": true,
    "pause-on-battery": false,
    "pause-on-active": false
}

**Comment by cmxhost** [comment]
does it work ???

if yes then you can close this issues tq

**Comment by TimyIsCool** [comment]
nope i think its a bus error or something
![image](https://user-images.githubusercontent.com/74112751/124397541-47434580-dd08-11eb-8df0-bc2a116b4d3c.png)

**Comment by cmxhost** [comment]
did you reboot and try ?

**Comment by TimyIsCool** [comment]
oke
