### ISSUE TITLE
how you custom build xmrig like dev releases here ..

### ISSUE THREAD

**Issue by arifsha** [xmrig/xmrig#2476]
i want to learn how to custum build  xmring for ubunut linux  

with cmake flag -DWITH_DMI=OFF.

because the  release build not working on aws  and i have to build with cmake flag -DWITH_DMI=OFF. every time and it takes time

can any one help me with custome build with with cmake flag -DWITH_DMI=OFF.   like dev releases  here they are fast to put on mining ...

**Comment by xmrig** [comment]
What type of AWS instance? Better to fix this issue without disabling DMI, but I need to know how to reproduce the crash.
Thank you.

**Comment by arifsha** [comment]
> What type of AWS instance? Better to fix this issue without disabling DMI, but I need to know how to reproduce the crash.
> Thank you.

aws c5a.xlarge instances 

and the error is :- segmentation fault (core dumped) error

![aws error](https://user-images.githubusercontent.com/28896109/124597547-41bd3b00-de81-11eb-8ded-4a731581d64b.PNG)

**Comment by xmrig** [comment]
Fixed in dev branch, but you can use any current version with command line option `--no-dmi`.
Thank you.

**Comment by arifsha** [comment]
> Fixed in dev branch, but you can use any current version with command line option `--no-dmi`.
> Thank you.

ok thank you sir ..
