### ISSUE TITLE
Help wanted ..!!! Asking some helpful questions..

### ISSUE THREAD

**Issue by Saikatsaha1996** [xmrig/xmrig#2477]
I have doubts...
Can anyone please explain me...!..
Asus twinker board vs android phone
Armv7.                  |.       Armv8
Mali GPU.             |.       Adreno gpu
Comput unit 4,.   |.       Compute unit 3,
Mem available.   |.       Memory available
497/1991 MB.    |.       951/3807 MB

But I am confused for this...
Arm v7 with OpenCL 1.2 , asus twinker board mining successful .... I don't care about hast rate because I am not doing for profit....

Arm v8 with OpenCL 2.0 , android mobile not successful....
Problem ....
1) with cn/upx2 algo segmentation fault
2) with randomx algo...
opencl   error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer with buffer size 2181038080
[2021-07-06 22:13:46.657]  opencl   thread #0 failed with error RandomX dataset is not available
[2021-07-06 22:13:46.660]  opencl   thread #0 self-test failed
[2021-07-06 22:13:46.660]  opencl   disabled (failed to start threads

3) with kawpow algo ..
Compile complete
But not mining ... Got error...

Asus twinker board.  

![IMG_20210706_221257](https://user-images.githubusercontent.com/72664192/124640005-709bd700-deaa-11eb-880f-553ffb6ecb06.jpg)

Android mobile

![Screenshot_2021-07-04-22-37-06-121_com termux](https://user-images.githubusercontent.com/72664192/124640086-8f01d280-deaa-11eb-967e-6f02c12eb331.jpg)
![Screenshot_2021-07-04-20-41-38-586_com termux](https://user-images.githubusercontent.com/72664192/124640096-90cb9600-deaa-11eb-8aa0-3050991bd6dd.jpg)

**Comment by Saikatsaha1996** [comment]
Please reply me..... Thank you

**Comment by snipeTR** [comment]
![image](https://user-images.githubusercontent.com/31975916/124641829-cca93000-de97-11eb-8acc-3f04f8d6d700.png)

**Comment by Saikatsaha1996** [comment]
See max memory available 951mb
![Screenshot_2021-07-18-22-09-49-357_com miui gallery](https://user-images.githubusercontent.com/72664192/126075262-cf774729-4df6-4ee2-8835-ad3b5907bb19.jpg)

**Comment by Saikatsaha1996** [comment]
I understand Rx/0 want 2gb + memory 
But cn/upx2?
Its also shown same problem
![Screenshot_2021-07-18-22-24-56-855_com termux](https://user-images.githubusercontent.com/72664192/126075724-1a25a9e7-2532-428a-a14c-b26398a30ce7.jpg)
