### ISSUE TITLE
Hash Rate Drop, Processor Core and Thread shown are incorrect

### ISSUE THREAD

**Issue by sewell8664** [xmrig/xmrig#2481]
![Capture](https://user-images.githubusercontent.com/87204276/125119899-4d7c5c00-e124-11eb-88b4-2b0465adeaaf.PNG)

Th hash-rate drop significantly. Only 8 threads have been detected, there are 32 threads for AMD 3950X.

**Comment by SChernykh** [comment]
This is cn-heavy algorithm, number of threads is correct for it. Also check what Task Manager shows and your BIOS settings, maybe you disabled half of the cores.

**Comment by Spudz76** [comment]
Heavy uses 4MB cache per thread so it is maxing out at 8*4=32MB cache total

Detection may be bios or kernel options limiting cores.  But even if it said `16c/32t` it would still only do 8 threads due to cache.

**Comment by SChernykh** [comment]
To be fair, it should be doing 16 cn-heavy threads on 3950X because it should have 64 MB cache.

**Comment by Spudz76** [comment]
Did not notice cache was halved too, so there would be room for 16 threads once debugged.

**Comment by sewell8664** [comment]
![image](https://user-images.githubusercontent.com/87204276/125149028-06fd2080-e169-11eb-9f0a-c5ebe11313ac.png)

The issue was resolved. Thank you so much guys!

**Comment by Valtsuh** [comment]
What's a good average(most users) hashrate to compare to, per thread? Bottom / top?

**Comment by Spudz76** [comment]
@Valtsuh the total hashrate, 1380.3H/s

Also of note this is `cn-heavy/xhv` not `rx/0` and hashrates do not cross-compare across algos.

**Comment by Valtsuh** [comment]
> @Valtsuh the total hashrate, 1380.3H/s
> 
> Also of note this is `cn-heavy/xhv` not `rx/0` and hashrates do not cross-compare across algos.

Okay, I'm jus figuring out if my hashrate is slow, fast or somewhere in the middle. 

rx (not /0 if it makes a difference) jumpa somewhere between 100-350 / thread, topping at around 1200ish 3-4 threaded.
