### ISSUE TITLE
Donate server for xhv is broken

### ISSUE THREAD

**Issue by Lonnegan** [xmrig/xmrig#2487]
xmrig tries to mine the dev fee for 1 minute every 100 minutes. When mining Haven (xhv), that seems to be broken atm.

![donate-xhv](https://user-images.githubusercontent.com/60088495/126517744-b6f71ffc-48fe-437a-8714-7452feb187e9.png)

So you don't get dev fee atm when people mine Haven. Please fix your donate pool in order to get your well deserved dev fee! :)

**Comment by xmrig** [comment]
Fixed, thank you. This bug was caused by too much aggressive user agent filtering.
