### ISSUE TITLE
How do I enable "1GB PAGES"?

### ISSUE THREAD

**Issue by Joe23232** [xmrig/xmrig#2490]
When I start `xmrig` on Windows, I get the following information:

```
 * ABOUT        XMRig/6.12.2 gcc/10.3.0
 * LIBS         libuv/1.38.0 OpenSSL/1.1.1g hwloc/2.2.0
 * HUGE PAGES   permission granted
 * 1GB PAGES    unavailable
```

How would I get `1GB PAGES` to work if anyone knows by any chance?

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/hugepages#onegb-huge-pages it supported only on Linux.
Thank you.

**Comment by Joe23232** [comment]
@xmrig THank you.
