### ISSUE TITLE
Enable huge pages on OSX

### ISSUE THREAD

**Issue by kurakin-oleksandr** [xmrig/xmrig#25]
When I run miner huge pages support sometimes is enabled, sometimes - not.
Would be good to have instructions how to activate it on OSX

**Comment by xmrig** [comment]
If hugepages disabled it means allocation failed and used failback, There many reasons why it can happen, memory fragmentation, system load, other applications, ... Only after reboot there is a maximum chance of getting hugepages. Longer system works less chance. Unfortunately there is no guaranteed way to get them.

**Comment by kurakin-oleksandr** [comment]
Thanks!

**Comment by iexa** [comment]
how much memory does it try to allocate with hugepages anyway?
