### ISSUE TITLE
Issue during make using g++-7

### ISSUE THREAD

**Issue by sam08016** [xmrig/xmrig#251]
[  2%] Building CXX object CMakeFiles/xmrig.dir/src/net/Client.cpp.o
g++-7: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/xmrig.dir/build.make:278: recipe for target 'CMakeFiles/xmrig.dir/src/net/Client.cpp.o' failed
make[2]: *** [CMakeFiles/xmrig.dir/src/net/Client.cpp.o] Error 4
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig.dir/all' failed
make[1]: *** [CMakeFiles/xmrig.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xmrig** [comment]
Looks like internal gcc error. You need submit this bug to gcc team.
Thank you.
