### ISSUE TITLE
OS X Build Issue/Question

### ISSUE THREAD

**Issue by taylovision** [xmrig/xmrig#252]
Whenever I pull up terminal and get xmrig running, I get the following:
```
$ make

[ 12%] Built target cpuid
[100%] Built target xmrig
```
When I run my mining pool and all right after, it all looks normal and runs fine. (seemingly)

My questions is this, is that 12% target cpuid an issue? Should I be concerned it's not mining at all?

**Comment by xmrig** [comment]
You no need make after succeful build. Run ./xmrig.
Thank you.
