### ISSUE TITLE
Build on aarch64 fails in DaemonClient.cpp

### ISSUE THREAD

**Issue by OTLabs** [xmrig/xmrig#2527]
**Describe the bug**
Build on aarch64 fails in DaemonClient.cpp

**To Reproduce**
Build on aarch64

**Expected behavior**
Successful build

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: [e.g. Windows]
 - For GPU related issues: information about GPUs and driver version.

**Additional context**
Build on aarch64 fails in DaemonClient.cpp with following error message:
```
297 /builds/otlabs/aports/testing/xmrig/src/xmrig-6.14.0/src/base/net/stratum/DaemonClient.cpp:68:98: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
298   68 | static const char kZMQGreeting[64] = { -1, 0, 0, 0, 0, 0, 0, 0, 0, 127, 3, 0, 'N', 'U', 'L', 'L' };
299      |                                                                                                  ^
```
Full build log is available here:
https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/458898#L297

**Comment by xmrig** [comment]
Should be [fixed](https://github.com/xmrig/xmrig/commit/f4cdc527b00571150e8521331928c75b44e071f9) in dev branch.
Thank you.

**Comment by arunAK47AK** [comment]
/root/xmrig/src/base/net/stratum/DaemonClient.cpp:68:98error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ [-Wnarrowing]
   68 | 0, 0, 0, 0, 0, 127, 3, 0, 'N', 'U', 'L', 'L' };
      |                                              ^

make[2]: *** [CMakeFiles/xmrig.dir/build.make:1031: CMakeFiles/xmrig.dir/src/base/net/stratum/DaemonClient.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/xmrig.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v6.14.1

**Comment by OTLabs** [comment]
xmrig 6.14.1 biulds fine on aarch64. Thank you!
