### ISSUE TITLE
aarch63,cortex a53 android cmake error 

### ISSUE THREAD

**Issue by arunAK47AK** [xmrig/xmrig#2536]
/root/xmrig/src/base/net/stratum/DaemonClient.cpp:68:98error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ [-Wnarrowing]
68 | 0, 0, 0, 0, 0, 127, 3, 0, 'N', 'U', 'L', 'L' };
| ^

make[2]: *** [CMakeFiles/xmrig.dir/build.make:1031: CMakeFiles/xmrig.dir/src/base/net/stratum/DaemonClient.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/xmrig.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Comment by SChernykh** [comment]
#2537

**Comment by arunAK47AK** [comment]
Simple use nano use replace one line script #2537

**Comment by LouTom91** [comment]
The given script is not accessible
