### ISSUE TITLE
I can't mine more than 1 time with xmrig

### ISSUE THREAD

**Issue by Cris7015** [xmrig/xmrig#2539]
Hello I need help and I have tried to mine with xmrig and minexmr I already have 1 machine running that is mining but at the moment I want to mine with another machine the program starts without problems but it does not register the 2 machines but only 1 that may be I need help I would appreciate it
![Captura de pantalla (464)_LI](https://user-images.githubusercontent.com/76759272/129430662-2b4f96c8-6e4a-4221-ace3-9337ed9e1b92.jpg)
![Screenshot (9)](https://user-images.githubusercontent.com/76759272/129430667-6b0fa72a-b0dd-4594-8a70-38c1004abbb7.png)
The second image that I sample is the second machine that doesn't want to appear on minexmr's mining list, I don't really know if it's their problem, mine, or yours.

**Comment by freakovision** [comment]
They are mining under the same name. 
Use different rig-id for each worker.
`--rig-id=ID` - ` rig identifier for pool-side statistics`
