### ISSUE TITLE
Use with AEON

### ISSUE THREAD

**Issue by minerteam** [xmrig/xmrig#254]
Hello, does it work with the crypto currency AEON?
Thank you

**Comment by erotavlas85** [comment]
Hi,
yes it does. You have to set --algo=cryptonight-lite instead of --algo=cryptonight.

**Comment by jimboo364** [comment]
Hi,
What happening if i set --algo=cryptonight-lite for XMR?

**Comment by xmrig** [comment]
@jimboo364 all your shares will be rejected by pool.

**Comment by minerteam** [comment]
Thank you erotavlas85
