### ISSUE TITLE
How to cure this?

### ISSUE THREAD

**Issue by CEDREXCYBERG95** [xmrig/xmrig#2540]
![Screenshot_2021-08-14-02-26-42-75](https://user-images.githubusercontent.com/37187357/129452810-63e8909b-ff33-41da-969c-22f509dd6a7e.png)
![Screenshot_2021-08-14-23-58-59-17](https://user-images.githubusercontent.com/37187357/129452817-86ed1783-06c5-4d4b-b08d-a7dc186166fb.png)

Please Developers help me to fix it.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v6.14.1
