### ISSUE TITLE
Extended low power mode for L4 cache

### ISSUE THREAD

**Issue by hamstertheminer** [xmrig/xmrig#255]
Hi,
I just discovered that [xmr-stak](https://github.com/fireice-uk/xmr-stak/pull/168) is able to use big L4 cache of some CPU in order to improve hashing performance.
It would be interesting to see it also into xmrig.
Thank you

**Comment by xmrig** [comment]
Added to TODO #106 
Thank you.

**Comment by xmrig** [comment]
Implemented. More details #563
