### ISSUE TITLE
use HTTP API Program Exit

### ISSUE THREAD

**Issue by Zy143L** [xmrig/xmrig#2551]
![image](https://user-images.githubusercontent.com/21352718/130340540-759396ac-2637-4cc7-99b7-946ab153abed.png)
![image](https://user-images.githubusercontent.com/21352718/130340547-f6c28fed-9b35-4d4e-8a88-d9de42f70f95.png)
## The program exits abnormally after clicking apply

**Comment by xmrig** [comment]
Please show your config and new config if you make changes and not just click the button.
Thank you.

**Comment by Zy143L** [comment]
Click apply and xmrig exits with no change in config.json

**Comment by xmrig** [comment]
Already did it and all works fine, so need more details to reproduce this bug.
Thank you.

**Comment by Zy143L** [comment]
I changed `src\base\kernel\Base.cpp` #140
        chain.addFile(Process::location(Process::DataLocation, "config.json"));
Change to
     chain.addFile(Process::location(Process::DataLocation, "config.dat"));

**Comment by Zy143L** [comment]
Problem Resolution
