### ISSUE TITLE
Stupid question: how to disable 1gb hugepage

### ISSUE THREAD

**Issue by hxuchen** [xmrig/xmrig#2566]
how to disable 1gb hugepage 0.0

**Comment by DeeDeeRanged** [comment]
In config.json file

    "cpu": {
        "enabled": true,
        "huge-pages": false,
        "huge-pages-jit": false,

"randomx": {
        "init": -1,
        "init-avx2": -1,
        "mode": "auto",
        "1gb-pages": false,

**Comment by chenjiaqi001** [comment]
好像只有Linux可以使用1GB-HUGEPAGE

**Comment by Spudz76** [comment]
正确的
