### ISSUE TITLE
[BUG] ./xmrig: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./xmrig)

### ISSUE THREAD

**Issue by danuonuo** [xmrig/xmrig#2572]
**Describe the bug**
When I try to compile it myself using the advanced compilation tutorial and then run it on other machines, it does not run and reports the following error:
**./xmrig: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./xmrig)**

**To Reproduce**
Use the advanced compilation tutorial to complete the compilation and run it on another machine

**Expected behavior**
./xmrig: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./xmrig)

**Required data**
 - Logs:**./xmrig: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./xmrig)**
 - OS: Ubuntu20.04LTS

**I use the official tutorial**

**Comment by Spudz76** [comment]
You have to compile on the machine it will run on, or at least the identical Linux Distro.  Otherwise set `-DBUILD_STATIC=ON` so it includes more libraries and is more portable (but that still might not work).

Also build the included deps (openssl/libuv/hwloc) with `./scripts/build_deps.sh` as those tend to work more guaranteed than any distro-provided dev packages.  May be required to do static build.

**Comment by danuonuo** [comment]
> You have to compile on the machine it will run on, or at least the identical Linux Distro. Otherwise set `-DBUILD_STATIC=ON` so it includes more libraries and is more portable (but that still might not work).
> 
> Also build the included deps (openssl/libuv/hwloc) with `./scripts/build_deps.sh` as those tend to work more guaranteed than any distro-provided dev packages. May be required to do static build.

_1. sudo apt-get install git build-essential cmake automake libtool autoconf
2. git clone https://github.com/xmrig/xmrig.git
3. mkdir xmrig/build && cd xmrig/scripts
4. ./build_deps.sh && cd ../build
5. cmake .. -DXMRIG_DEPS=scripts/deps
6. make -j$(nproc)_

Are these incorrent?Thanks.

**Comment by Spudz76** [comment]
Not if you're running it where you compiled it.  Copying the executable off to some other Linux won't work that way.

**Comment by danuonuo** [comment]
> Not if you're running it where you compiled it. Copying the executable off to some other Linux won't work that way.

So what should I do if I want to compile xmrig to run on other linux?

**Comment by Spudz76** [comment]
Replace step 5 with: `cmake .. -DXMRIG_DEPS=../scripts/deps -DBUILD_STATIC=ON`

**Comment by danuonuo** [comment]
> Replace step 5 with: `cmake .. -DXMRIG_DEPS=../scripts/deps -DBUILD_STATIC=ON`

OK,I will try.Thanks.
