### ISSUE TITLE
Unable to find entry point GetHostNameW in WS2_32.dll

### ISSUE THREAD

**Issue by jututt** [xmrig/xmrig#2574]
When trying launching latest 6.15.0 on my Win7 x64 machines, both GCC and MSVC, it crashes and displays error message as per title (roughly translated to english by me).
Previous 6.14.1 works fine

**Comment by xmrig** [comment]
Seems libuv dropped support for Windows 7 https://github.com/libuv/libuv/issues/3260 
Thank you.

**Comment by Spudz76** [comment]
Thanks for the heads-up, I will be running Win7 until the end of ESU ([January 10, 2023](https://docs.microsoft.com/en-us/lifecycle/faq/extended-security-updates)) guess the workaround is to not upgrade libuv unless they reverse their terrible decision.

**Comment by SChernykh** [comment]
#2586

**Comment by jututt** [comment]
closed with 6.15.1
