### ISSUE TITLE
log rotate compatibility : no new log file created after rotating log.

### ISSUE THREAD

**Issue by ZwaZo22** [xmrig/xmrig#2579]
**Describe the bug**

When using logrotate on the XMrig log, a new empty log file is not created, leaving XMrig without log output when ran in background.

**To Reproduce**

Run logrotate against XMrig log file.

**Expected behavior**

A new empty xyz.log file should be created to continue the logging.

**Required data**

relevant lines in config.json : 

 "background": true,
 "log-file": "/home/xmr/xmrig/xmrig.log",

logrotate configuration file for XMrig in /etc/logrotate.d/ : 

/home/xmr/xmrig/*.log
{
    rotate 7
    daily
    missingok
    delaycompress
    nocreate
}

 - OS: [e.g. Windows]
Ubuntu 20.04 server

 - For GPU related issues: information about GPUs and driver version.
N/A

**Additional context**
headless server

**Comment by SChernykh** [comment]
Did you try to remove `nocreate` from logrotate config?

**Comment by ZwaZo22** [comment]
It works without the `nocreate` option. Thanks !
