### ISSUE TITLE
Thanks for this awesome XMR-Miner! 

### ISSUE THREAD

**Issue by Band1to** [xmrig/xmrig#260]
Thanks for this awesome XMR-Miner! 
Best Regards, Band1to

**Comment by QwertyJack** [comment]
That's exactly what I wanna say.

**Comment by LlTECOIN** [comment]
#Agree @Band1to

**Comment by BYTECOlN** [comment]
#Agree @Band1to

**Comment by DOGECOlN** [comment]
#Agree @Band1to
