### ISSUE TITLE
Mining rate is 50-70 times (64 hash/s) less than regular 3500-4000 hash/s

### ISSUE THREAD

**Issue by nuriyevn** [xmrig/xmrig#2605]
**Describe the bug**
Mining rate is 50-70 times (64 hash/s) less than regular 3500-4000 hash/s

**To Reproduce**
Start miner,  wait undefined amount of time.  Last launch:  it takes 8 minutes to reproduce

**Expected behavior**
Mining rate should  be stable and in accordance with the  hardware performance

**Required data**
 - Miner log as text or screenshot
![image](https://user-images.githubusercontent.com/6706940/134765949-2d85db75-7cd4-4b79-80de-00c888b7a2fc.png)

 - Config file or command line (without wallets)
{
    "api": {
        "id": "Ryzen 5",
        "worker-id": "Ryzen 5"
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "colors": true,
    "title": true,
    "randomx": {
        "init": -1,
        "init-avx2": -1,
        "mode": "auto",
        "1gb-pages": false,
        "rdmsr": true,
        "wrmsr": true,
        "cache_qos": false,
        "numa": true,
        "scratchpad_prefetch_mode": 1
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "huge-pages-jit": false,
        "hw-aes": null,
        "priority": 1,
        "memory-pool": false,
        "yield": true,
        "asm": true,
        "argon2-impl": null,
        "astrobwt-max-size": 550,
        "astrobwt-avx2": false,
        "argon2": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        "astrobwt": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        "cn": [
            [1, 0],
            [1, 2],
            [1, 4],
            [1, 5],
            [1, 6],
            [1, 8],
            [1, 10],
            [1, 11]
        ],
        "cn-heavy": [
            [1, 0],
            [1, 2],
            [1, 6],
            [1, 8]
        ],
        "cn-lite": [
            [1, 0],
            [1, 1],
            [1, 2],
            [1, 3],
            [1, 4],
            [1, 5],
            [1, 6],
            [1, 7],
            [1, 8],
            [1, 9],
            [1, 10],
            [1, 11]
        ],
        "cn-pico": [
            [2, 0],
            [2, 1],
            [2, 2],
            [2, 3],
            [2, 4],
            [2, 5],
            [2, 6],
            [2, 7],
            [2, 8],
            [2, 9],
            [2, 10],
            [2, 11]
        ],
        "cn/upx2": [
            [2, 0],
            [2, 1],
            [2, 2],
            [2, 3],
            [2, 4],
            [2, 5],
            [2, 6],
            [2, 7],
            [2, 8],
            [2, 9],
            [2, 10],
            [2, 11]
        ],
        "rx": [0, 2, 4, 5, 6, 8, 10, 11],
        "rx/wow": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        "cn-lite/0": false,
        "cn/0": false,
        "rx/arq": "rx/wow",
        "rx/keva": "rx/wow"
    },
    "opencl": {
        "enabled": false,
        "cache": true,
        "loader": null,
        "platform": "AMD",
        "adl": true,
        "cn-lite/0": false,
        "cn/0": false
    },
    "cuda": {
        "enabled": false,
        "loader": null,
        "nvml": true,
        "cn-lite/0": false,
        "cn/0": false
    },
    "log-file": "log.txt",
    "donate-level": 1,
    "donate-over-proxy": 1,
    "pools": [
        {
            "algo": "RandomX",
            "coin": null,
            "url": "xmr-eu1.nanopool.org:14444",
            "user": "HIDDEN_WALLET",
            "pass": "x",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false,
            "socks5": null,
            "self-select": null,
            "submit-to-origin": false
        }
    ],
    "retries": 5,
    "retry-pause": 5,
    "print-time": 60,
    "health-print-time": 60,
    "dmi": true,
    "syslog": false,
    "tls": {
        "enabled": false,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "dns": {
        "ipv6": false,
        "ttl": 30
    },
    "user-agent": null,
    "verbose": 0,
    "watch": true,
    "pause-on-battery": false,
    "pause-on-active": false
}

 - OS: [e.g. Windows]
Windows 10 Pro
 - For GPU related issues: information about GPUs and driver version.

**Additional context**
Energy consumption is set to BALANCED.
This is PC not a laptop.

** Already tried **
Switched energy consumption to HIGH PERFORMANCE

**Comment by SChernykh** [comment]
https://xmrig.com/docs/miner/randomx-stability-troubleshooting-guide
Turn off `memory compression and RunFullMemoryDiagnostic task`

**Comment by nuriyevn** [comment]
modified from
"rx": [0, 2, 4, 5, 6, 8, 10, 11],
to 
"rx": [-1, -1, -1, -1, -1, -1, -1, -1],

also disabled memory compression.
Closing for now. Will reopen if it reappears.

**Comment by SChernykh** [comment]
You don't need to modify to `"rx": [-1, -1, -1, -1, -1, -1, -1, -1],`, disabling memory compression and RunFullMemoryDiagnostic should be enough.

**Comment by nuriyevn** [comment]
maybe, who know what I need. I've not tested yet. You can't know as well for sure, software is complex stuff.  I will better do everything which is not bring harm. Hashrate didn't dropped after rx array so let it be,

**Comment by nuriyevn** [comment]
RunFull  +

**Comment by nuriyevn** [comment]
Windows Search  is also disabled.

Hope this will help.
thanks
