### ISSUE TITLE
issue with compiled xmrig

### ISSUE THREAD

**Issue by chri121** [xmrig/xmrig#261]
Hello, i got the follwing problem:

i compiled it with vs2017 and if I start the xmrig.exe, it closes right after the start without any error code. 

I tried to debug it says "File: minkernel\crts\ucrt\src\appcrt\stdio\fdopen.cpp
Line 29
Expression: _osfile(fh) & FOPEN

The precompiled binaries work without any other issue.

**Comment by xmrig** [comment]
Looks like same issue, just in wrong place https://github.com/fireice-uk/xmr-stak/issues/296
Release builds not affected.
Thank you.
