### ISSUE TITLE
Set -DWITH_EMBEDDED_CONFIG=ON, Switching algorithm problem

### ISSUE THREAD

**Issue by JieSinTime** [xmrig/xmrig#2625]
After setting the built-in configuration file, using the moneroocean mining pool, every time you switch the algorithm, you need to STARTING ALGO PERFORMANCE CALIBRATION (with 20 seconds round)

**Comment by Spudz76** [comment]
MO-xmrig support is over on the [MO fork](https://github.com/MoneroOcean/xmrig/issues)

The bug doesn't exist here since there is no algo-perf feature.

**Comment by JieSinTime** [comment]
Everything is normal for external files. Every time the mining pool changes the algorithm, the built-in configuration file will start to test again

**Comment by JieSinTime** [comment]
![image](https://user-images.githubusercontent.com/86323541/136868666-0dff752f-27c6-4f53-8fc4-0de2a8c4f00c.png)

**Comment by JieSinTime** [comment]
@xmrig
