### ISSUE TITLE
[Feature request] Link GPU to one pool, CPU to another

### ISSUE THREAD

**Issue by Letme** [xmrig/xmrig#2628]
I am mining Monero with RandomX and as already mentioned couple of times the GPU mining for RandomX is just waste of energy. So what I would love to have is that monero would be mined by CPU, but something else (lets say dero) would be mined by GPU at the same time. I would assume that all would run the same, just a bit more configuration?

**Comment by Spudz76** [comment]
Run separate folders and xmrigs.  One config.json set up for CPU enabled GPUs disabled, and the other GPU enabled and CPU disabled.  And change the miner rig-id or identifier in the password, if you are sending both to the same pool (like `rig-gpu` or something).

**Comment by Letme** [comment]
I ran it twice with different configurations using `--config` flag. For me this solution is good enough, so I am closing the ticket.
