### ISSUE TITLE
XMrig keeps crashing (ARM processor) (XMrig 6.15.2)

### ISSUE THREAD

**Issue by utauyo** [xmrig/xmrig#2629]
for some reason after the log "allocated 2336 MB (1080+256) huge pages 0% 0/1168 +JIT (1 ms)" the miner just gets killed, i cant figure out why 

Algo: RandomX
CPU: Octa-core 2.36 GHz ARM Cortex-A53
RAM: 2780 MB

**Comment by kaisarm5** [comment]
That seems to have fixed it. Though it is still weird that i have run the same miner comfiguration on even worse arm processors and less ram and they would mine just fine
