### ISSUE TITLE
DNS error unknown node or service

### ISSUE THREAD

**Issue by Hussainm39** [xmrig/xmrig#2631]
Hello every one can some one help me out I am mining on unmineable app and from yesterday when I want to do mining on cpu it’s say DNS error unknown node or service ,  also before this it’s say Opencl Disabled. But gpu mining working but the app giving me to low MH 
Thanks in advance

**Comment by Hussainm39** [comment]
![A9253C91-D7CB-4B28-AAA0-604EA4E7849B](https://user-images.githubusercontent.com/92572107/137460636-97be223d-a7bd-4a7c-a3b2-8a1bcdf23bb0.jpeg)

**Comment by Spudz76** [comment]
Then something or ISP is filtering DNS for known mining sites.

Switch DNS servers to a public one (not the one your ISP gives you) or investigate new/updated security software and add exceptions/whitelist.
