### ISSUE TITLE
Optimization for 32-bit code

### ISSUE THREAD

**Issue by yuhong** [xmrig/xmrig#264]
Raymond mentions an optimization that can be used:
https://blogs.msdn.microsoft.com/oldnewthing/20171213-00/?p=97575
https://blogs.msdn.microsoft.com/oldnewthing/20141208-00/?p=43453

**Comment by xmrig** [comment]
Thank you looks very interesting, also part 2 now available: https://blogs.msdn.microsoft.com/oldnewthing/20171214-00/?p=97577

**Comment by yuhong** [comment]
For fun, I did a 128-bit add using PCMPGTQ in SSE4.2:
__m128i int128addsse42(__m128i a, __m128i b)
{
	__m128i retval;
	__m128i zeros = _mm_setzero_si128();
	__m128i ones = _mm_cmpeq_epi64(zeros, zeros);
	__m128i constant = _mm_slli_epi64(ones, 63);
	retval = _mm_add_epi64(a, b);
	__m128i result = _mm_cmpgt_epi64(_mm_xor_si128(a, constant), _mm_xor_si128(retval, constant));
	retval = _mm_sub_epi64(retval, _mm_slli_si128(result, 8));
	return retval;
}
Might not be worth using though.
