### ISSUE TITLE
Virus "detected" in this repo. 

### ISSUE THREAD

**Issue by nissaba** [xmrig/xmrig#2666]
hello, just downloaded the zip file for the repo and Forth client flagged the zip file as containing Riskware/Generic.H2 , Riskware/CoinMiner. so pool_mine_example.cmd and solo_mine_example.cmd where quarantined. 

This said I am not saying it is a virus but it as been flagged at possibly containing a malwhere, not sure if you can do any thing about it.

**Comment by snipeTR** [comment]
because of the goddamn botnet admins. they once used people's computers using this software and similar miners. so now all antivirus programs flag miners.
