### ISSUE TITLE
AstroBWT.cpp warning!

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig#2668]
[ 95%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/astrobwt/AstroBWT.cpp.obj
C:/msys32/home/cxz/xmrig-6.15.3/src/crypto/astrobwt/AstroBWT.cpp:80:13: warning: 'void Salsa20_XORKeyStream_AVX256(const void*, void*, size_t)' defined but not used [-Wunused-function]
   80 | static void Salsa20_XORKeyStream_AVX256(const void* key, void* output, size_t size)

**Comment by SChernykh** [comment]
Because it's only enabled in 64-bit builds and you're building 32-bit binary in msys32. It's just a warning, so not a problem.
