### ISSUE TITLE
No jobs when using GPU

### ISSUE THREAD

**Issue by curi0usJack** [xmrig/xmrig#2672]
**Describe the bug**
When running on Linux (Arch) using --cuda and pointing to ethash.unmineable.com, I get no jobs. Brand new to mining, so I'm most certainly missing something obvious.

![image](https://user-images.githubusercontent.com/5608516/140529823-3770de4e-ec36-4058-8ad1-84a9f292fd2e.png)

Things work as expected when using cpu mining on rx. I've confirmed that I can reach the destination hosts on 3333, so I do not believe it to be a network/firewall issue. I've also tried kp and etchash. Same result. It only works with rx.

![image](https://user-images.githubusercontent.com/5608516/140530027-7f52a59c-aa6c-4688-b0e3-62e4ec956bc3.png)

**Comment by curi0usJack** [comment]
Also confirmed it's not a network issue. I see traffic going back and forth between hosts on the target port.

**Comment by SChernykh** [comment]
xmrig doesn't support ethash, try kawpow. Also you need to specify the algorithm in the command line: `-a kawpow`

**Comment by Spudz76** [comment]
T-Rex is what you want, for ethash

**Comment by curi0usJack** [comment]
Perfect. That worked great. 

Thanks guys!
