### ISSUE TITLE
RX 580 Haven Hashrate Low 500h/s

### ISSUE THREAD

**Issue by mk148a** [xmrig/xmrig#2679]
Hello, 
I use xmrig 6.15.3 i mined xhv in hashvault.pro pool. I got around 500h/s hasrate in my card, its low, how to fix it?

![resim](https://user-images.githubusercontent.com/7630189/141193762-974eb5a9-2ff5-4bea-9c2a-09974b76b765.png)

**Comment by Spudz76** [comment]
I get about 460 on an RX480 and probably it's correct for how well Ellesmere does CN-Heavy

**Comment by mk148a** [comment]
Thank you
