### ISSUE TITLE
Hashrate question

### ISSUE THREAD

**Issue by BenBenz** [xmrig/xmrig#268]
Why may hashrate is not constantly at max ? 

speed 2.5s/60s/15m 109.6 132.6 129.3 H/s max: 161.6 H/s

**Comment by darthyvader** [comment]
I noticed this too, my hashrate is half of what I was getting previously back in March.

**Comment by xmrig** [comment]
CPU hashrate highly depends of other cache intensive running apps. Video playback, browsing web, background updates, etc.
Thank you.

**Comment by BenBenz** [comment]
@darthyvader  @xmrig  Thanks for your reply,
But I only use the computer for that this is really strange, I'll investigate on this

**Comment by darthyvader** [comment]
that sounds  good my hashrate is just half of what it was on July same hw
same settings. bytecoin miner works as expected though. 1-1.2kh vs 400h/s
xmrig 28 threads

**Comment by QwertyJack** [comment]
You can setup a static difficulty, which will helps making the hashrate stable.

**Comment by Sgordon123** [comment]
Chechk PowerSettings options on Your computer....
