### ISSUE TITLE
winring0 error 183

### ISSUE THREAD

**Issue by Horizon19999** [xmrig/xmrig#2683]
For some reason no matter what I do with the xmrig miner on nice hash an error will always pop up. “Failed to start WinRing0, error 183” then “failed to apply MSR mod, Hashrage will be low”
I have tried multiple things with a lot of the other users here and on Reddit.
I tried running as administrator that was a no go. 
restarted windows disabling secure boot. This did not work either. I then continued to try to find another way around the error. I tried uninstalling HW monitor and reinstalling it I also tried just leaving it gone as well. (I also did this with MSI afterburner) Restarting the computer each time. Still did not work. Tried to disable all of my RGB programs which I did end them all still was not working correctly. I also do not have aqua the other RGB program that another user was having a issue with. The error still shows up even after trying all of these things. 

Sorry if there is grammar errors writing this at 4 in the morning and have been working on this most of the night. If someone can think of any other possible solutions let me know.

**Comment by SChernykh** [comment]
https://github.com/xmrig/xmrig/pull/2684 will probably help

**Comment by Horizon19999** [comment]
> #2684 will probably help

So basically get rid of the winring0 file? Or am I reading this wrong. There is no other application on the pc that would be using a winring0

**Comment by Horizon19999** [comment]
Yea that sounds like what it could be. Thank you!
