### ISSUE TITLE
gcc not found

### ISSUE THREAD

**Issue by pranshuthegamer** [xmrig/xmrig#2705]
**Describe the bug**
` "c:\Program Files\CMake\bin\cmake.exe" .. -G "Unix Makefiles" -DXMRIG_DEPS=c:/xmrig-deps/gcc/x64
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/Pranshu TG/xmrig/build/CMakeFiles/CMakeOutput.log".
See also "C:/msys64/home/Pranshu TG/xmrig/build/CMakeFiles/CMakeError.log".
`

**Expected behavior**
i should be able to use make to build it

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: Windows 10

**Comment by Titaniumtown** [comment]
did you install gcc?

**Comment by Spudz76** [comment]
Not sure, I have never gotten anything but MSVC compile to work on Windows.  Maybe I will try it again and see.

My guess is you are missing some msys64 packages or it isn't in your Windows PATH environment variable.

[This seems like a decent howto](https://www.devdungeon.com/content/install-gcc-compiler-windows-msys2-cc), see if you've missed some pacman things or the adding to path.

**Comment by pranshuthegamer** [comment]
problem solved btw i did install gcc

**Comment by Spudz76** [comment]
Then it was the PATH?

**Comment by pranshuthegamer** [comment]
i think the tutorial on the xmrig wiki doesnt work but the one you sent me
does work
