### ISSUE TITLE
Large page allocation may fail on Windows booted with non-PAE kernel

### ISSUE THREAD

**Issue by yuhong** [xmrig/xmrig#272]
On non-PAE, the large page size is 4MB instead of 2MB, and it does seem that allocations fail if it is not a multiple. You can use GetLargePageMinimum to determine. The default is that NX is enabled which means that the PAE kernel is used.
You can test on 32-bit Windows Vista or Windows 7 by using:
bcdedit /set pae ForceDisable
bcdedit /set nx AlwaysOff
then rebooting.

**Comment by sergneo** [comment]
And on Windows XP 32 bit may how to enable huge pages ? My miner says that is available but disabled

**Comment by yuhong** [comment]
AFAIK it is not supported in XP, you have to have Server 2003 or later to support them.
