### ISSUE TITLE
怎么去解决这个问题，我重新弄了也不行

### ISSUE THREAD

**Issue by qiuanfu** [xmrig/xmrig#2721]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: [e.g. Windows]
 - For GPU related issues: information about GPUs and driver version.

**Additional context**
![微信截图_20211126192555](https://user-images.githubusercontent.com/95081199/143574005-c59b7e2e-9389-4e32-9890-b051fbdef9b4.png)

**Comment by Lonnegan** [comment]
You can't connect to a rx pool and select BTT as your coin. BTT (Bittorrent) is not a rx coin. You have to use XMR as coin and add your Monero address, not your Bittorrent address.

**Comment by SChernykh** [comment]
It's unmineable.com and that's what they do (mining RandomX/Monero and auto-converting to other coins). Why "operation cancelled" is another question though. Probably ISP blocking.

**Comment by Spudz76** [comment]
DNS is filtered or otherwise blocked for mining pool hosts.  Whitelist and/or bypass ISP censorship using public unfiltered DNS or VPN.

qiuanfu in the command line is not in the right place, it says

**Comment by qiuanfu** [comment]
如何解决呢？我之前都做得好好的

**Comment by felix920506** [comment]
ping看看能不能ping的到矿池
