### ISSUE TITLE
Miner automatically getting disconnected.

### ISSUE THREAD

**Issue by sathish09** [xmrig/xmrig#273]
Miner automatically getting disconnected from the proxy server. but the local API interface is reporting the hashrate. I even tried to restart every 20 minutes. but still, the issue is not resolved. I tried all the pools and proxies. Also tried without using proxy same thing happens. Help me resolve the issue.

**Comment by QwertyJack** [comment]
Try a static diff.

**Comment by sathish09** [comment]
in the miner or in the proxy?

**Comment by QwertyJack** [comment]
How much is your static diff?

**Comment by sathish09** [comment]
5000

**Comment by QwertyJack** [comment]
The diff is fine. Check your network.
