### ISSUE TITLE
Your description of xmrig might not be so clear

### ISSUE THREAD

**Issue by nonopolarity** [xmrig/xmrig#2732]
I saw on your page:

> XMRig is a high performance, open source, cross platform RandomX, KawPow, CryptoNight and AstroBWT unified CPU/GPU miner and RandomX benchmark.

I don't quite get it: how an XMRig be a miner and a "benchmark"?  Benchmark is some number to tell how fast something is...

So if you say: Pokemon Go is a game and a benchmark.  Or Microsoft Word is an app and a benchmark.  What does it mean?

**Comment by Titaniumtown** [comment]
What?

**Comment by nonopolarity** [comment]
XMRig is a miner and a benchmark... 
what does it mean?

**Comment by SChernykh** [comment]
It is a benchmark for CPUs: https://xmrig.com/benchmark

**Comment by Spudz76** [comment]
CPUs and Cache and RAM performance not just CPUs, even better.
