### ISSUE TITLE
Second address for donation

### ISSUE THREAD

**Issue by aekanman** [xmrig/xmrig#274]
Hello @xmrig ,

I've figured your setting your wallet address for donation by this line in the DonateStrategy.cpp: 

`Url *url = new Url("fee.xmrig.com", Options::i()->algo() == Options::ALGO_CRYPTONIGHT_LITE ? 3333 : 443, Options::i()->pools().front()->user(), nullptr, false, true);`

I was wondering if it is possible to add a second donation address. Thanks.

**Comment by Russellx2000** [comment]
A reply would be helpful :)

**Comment by Gill1000** [comment]
I m too looking for this @aekanman  
Have you sort-out this bro?

**Comment by aekanman** [comment]
@Gill1000 unfortunately no. I dug in the code but it looks like @xmrig has their address over a server or that sort of thing. If he can explains it, I'd appreciate too.

**Comment by xmrig** [comment]
About second address for donate it possible to add, but how it should works? Donate is time based, maybe random choice of donation address or round robin?
Thank you.

**Comment by snipeTR** [comment]
Aga nediyon amk sen. İkinci adress için kendi poolunu kurman lazım. Adamın donate sistemi adress tabanlı çalışmıyo. Kendine pool yapmış adam. O poola bağlanıyo o kadar. Kendine pool koy satırı ikiye çıkar bitane random ile seçtir. Oradan kafasına göre bağlansın. Ohhh dahanamadım. İki direksiyonlu araba sormuşsun resmen

**Comment by aekanman** [comment]
for the ones still looking into this issue, you can check #92.

**Comment by ArchLinuxAddict** [comment]
what about for latest versions
