### ISSUE TITLE
PGO support

### ISSUE THREAD

**Issue by Titaniumtown** [xmrig/xmrig#2749]
Is there a possibility of being able to compile xmrig with PGO? PGO should provide a noticeable performance uplift and improve hashrate.

**Comment by Spudz76** [comment]
Tried it a bunch of times and it does nothing.

Maybe makes the unimportant clerical stuff faster (pool comms, other logic, but not in the mining kernels).

**Comment by SChernykh** [comment]
It does nothing because RandomX is 99% assembly code and compiler has no effect there. Cryptonight and Astrobwt are basically a loop without branches and PGO mostly optimizes branches.

**Comment by Titaniumtown** [comment]
Ah ok. Thanks for your input @Spudz76 @SChernykh! I was not aware.
