### ISSUE TITLE
--rig-id not compatible with RTM and flockpool

### ISSUE THREAD

**Issue by duhd1993** [xmrig/xmrig#2756]
**Describe the bug**

When specifying worker name with --rig-id using xmrig, the name is not reflected on flockpool. While using the cpuminer, the name is reflected on flockpool.

**To Reproduce**
Steps to reproduce the behavior.

``./xmrig -a gr -o us.flockpool.com:5555 --tls -u xxxx --rig-id worker1``

**Expected behavior**

The name worker1 is shown on flockpool

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: [e.g. Windows]
 - For GPU related issues: information about GPUs and driver version.

**Additional context**

**Comment by Lonnegan** [comment]
Please read the help section of the pool! Flockpool doesn't support --rig-id. You have to put name worker's name behind the RTM address, separated by a point.

**Comment by duhd1993** [comment]
OK. Thanks. I know that. I thought that's just different command line format of different miners.
