### ISSUE TITLE
Build failed with WITH_OPENCL option disabled (v6.16.1)

### ISSUE THREAD

**Issue by timk74** [xmrig/xmrig#2757]
**To Reproduce**
```
cmake .. -G "Visual Studio 16 2019" -A "x64" -DXMRIG_DEPS="..\xmrig-deps\msvc2019\x64" -DWITH_OPENCL=OFF
cmake --build . --config Release
```
![error](https://user-images.githubusercontent.com/43396824/143965293-45971ef4-7aa7-4328-ac29-1e48a0974c7d.png)

**Comment by Spudz76** [comment]
I just compiled fine under MSVC `19.29.30137.0` (include path version `14.29.30133`) with `-DWITH_OPENCL=OFF`

Unsure how to revert to older `14.24.28314` to attempt to reproduce.  But if you can update from the Visual Studio Installer, it will work due to updated includes.

**Comment by timk74** [comment]
> But if you can update from the Visual Studio Installer, it will work due to updated includes.
Thanks, the latest updates helps.
