### ISSUE TITLE
Cache Value Displayed under VMware is Incorrect

### ISSUE THREAD

**Issue by x86txt** [xmrig/xmrig#2758]
When running XMRig under VMware ESXi, the cache value displayed is incorrect. My (Zen 2) Epyc 7302p reports 256MB of L3 and my 5700G reports 32MB - both are 2x what is actually on the chip. It doesn't seem to affect performance and appears to merely be a cosmetic bug, but I thought I'd report it for completeness.

![7302p](https://user-images.githubusercontent.com/34278354/143969076-c716bcfd-4ca9-4848-92b8-4d7335f7b8d9.png)

![5700G](https://user-images.githubusercontent.com/34278354/143968788-4f1b0219-f210-4dca-a826-2554c39a571b.png)

**Comment by xmrig** [comment]
This is how VMware reports CPU topology and this may affect performance since auto configuration may use more threads than actually optimal which is not issue for recent AMD CPUs since they have enough cache anyway.
Thank you.
