### ISSUE TITLE
Can not connect to pool on ipv6 network

### ISSUE THREAD

**Issue by sam08016** [xmrig/xmrig#276]
Hi,

I am currently on ipv6 network. I check the command ping6 monerohash.com which returns valid packets. I am using the same pool  in config.json file i.e. "url" : stratum+tcp://monerohash.com:3333 and run xmrig. This time, I could not connect to the pool.  xmrig supports ipv6 connections? Is there a way I can connect over my ipv6 network?

Thanks

**Comment by sam08016** [comment]
P.S. I am running ubuntu 16.04

**Comment by xmrig** [comment]
IPv6 support was added in v2.5.
Thank you.
