### ISSUE TITLE
RTM mining on Linux static build 5.16.1 crashes - "Segmentation fault"

### ISSUE THREAD

**Issue by Pavlogal** [xmrig/xmrig#2762]
Running Ubuntu 21.10 and Linux 5.15.5 kernel (so far had no issues with a this recent release)

Downloaded Linux static build 6.16.1 to get VAES optimizations for Zen 3. It failed every single time I tried to mine RTM with a message "Segmentation fault". XMR mining worked flawlessly though.

Switched from static to regular Linux build and now both RTM and XMR mining is working without issues. I don't know if static build has a bug or I'm missing something (probably this)

**Comment by Pavlogal** [comment]
saw that this is a duplicate issue, closing it myself so others don't have to

**Comment by SChernykh** [comment]
> Switched from static to regular Linux build and now both RTM and XMR mining is working without issues

Regular Linux build doesn't have VAES because it's compiled with a very old GCC version. This bug is already fixed in the dev branch, next release will have the fix.
