### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by felix920506** [xmrig/xmrig#2764]
**Describe the bug**
Miner ends with error "Segmentation fault (core dumped)" when ran under linux

**To Reproduce**
1. run the miner

**Expected behavior**
the miner should start mining

**Required data**
 - Miner log
![image](https://user-images.githubusercontent.com/25688628/144087393-b4da5019-f0c3-482a-8da6-76f272d13e1b.png)
 - Config file or command line (without wallets)
https://pastebin.com/0qXn3QXy
 - Ubuntu 21.10 Server

**Comment by SChernykh** [comment]
Fixed in https://github.com/xmrig/xmrig/pull/2751
