### ISSUE TITLE
Cannot Open include file: 'uv.h': No such file or directory

### ISSUE THREAD

**Issue by GrassFire** [xmrig/xmrig#277]
Tons of those when building.  no app created... WTF is it done this way?  Total waste of time.

**Comment by GrassFire** [comment]
This is not a sufficient explanation:
https://github.com/xmrig/xmrig/wiki/Windows-Build You can download prebuilt library's or build it byself.
That communicates very little. Great.  You pointed a finger in the general direction of something but you did not say what to do with it.  If you ever work a helpdesk, you will learn that people cannot read your mind.  I'm sure that sentence is perfectly apparent to you, but I am a developer and it means very little to me.  I have libuv from the libuv source.  I even put it in my path.  I still get the compile errors when I build.  I placed all your folders in my xmrig folder...same result.  Why is this not just simply compiled and linked?

**Comment by rcguy** [comment]
it builds fine on windows if you follow the instructions. your issues smell like PEBCAK
