### ISSUE TITLE
Ghostrider ignores Environmnent Variables in config.json

### ISSUE THREAD

**Issue by becgm** [xmrig/xmrig#2771]
When ghostrider algorithm is used the enviroment variables in config.json are not expanded.

When running randomx the correct worker ID is showed at pool's interface but when running ghostrider the worker is showed as ${HOSTNAME}.

The worker ID is configured at user's variable:
     "user": "XxXxXxXxXxXxXx.${HOSTNAME}"

**Comment by Spudz76** [comment]
Wasn't aware that ever worked.

**Comment by Spudz76** [comment]
Okay, definitely works, and is wired globally in `setPool()` which is called regardless of algorithm.

**Comment by becgm** [comment]
Pool still shows ${HOSTNAME} and it cannot be a bug at pool's interface since this string is sent by the xmrig client.

**Comment by xmrig** [comment]
Fixed in dev branch.
Thank you.

**Comment by Spudz76** [comment]
Oops I forgot GR hides under the EthStratum umbrella.
