### ISSUE TITLE
HUGE PAGES available, disabled Windows XP sp3

### ISSUE THREAD

**Issue by sergneo** [xmrig/xmrig#278]
The 32-bit version says that huge pages are available but disabled. Tried to add to boot.ini /PAE and(or) the /noexecute=AlwaysOn.
Cleaned the memory memreduct still huge pages disabled. On Windows 7 32 I have achieved the result, everything works successfully. What to do to make them work on Windows XP ? Is this even possible?

CPU "Intel(R) Celeron(R) CPU G1610 @ 2.60GHz"
the memory module 4 GB

**Comment by yuhong** [comment]
XP don't support it.

**Comment by sergneo** [comment]
Win Server 2003 Enterprise 32bit works, checked.

**Comment by yuhong** [comment]
Yea, I think that was the first version of Windows to support it.

**Comment by fonix232** [comment]
Why would you even use XP today? Okay, I understand it's a low-resource system, but it's full of security holes. Windows Server Core would be a better option IMO.

**Comment by sergneo** [comment]
This can not be considered, because it is not home computers.

**Comment by fonix232** [comment]
Even worse then. Use a stripped-down version of 7 or 10, or anything but XP. Heck, even a Linux setup would be more secure (albeit more work too). XP has no use nowadays, and apart from embedded, air-gapped systems, it should die out ASAP.
