### ISSUE TITLE
a lot of rejected shares for GR - is it normal?

### ISSUE THREAD

**Issue by musiu** [xmrig/xmrig#2780]
**Describe the bug**
as above, running from HiveOs for 22h and have 19 rejected shares, I didn't notice that when using cpuminer on the same pool

**To Reproduce**
run miner on hiveOs 

**Expected behavior**
reduced number of rejected shares.

**Required data**
![image](https://user-images.githubusercontent.com/8035665/144568486-87ed5e67-97dc-460d-b184-85430e29e728.png)
![image](https://user-images.githubusercontent.com/8035665/144568501-62726dcc-ce87-4e1d-8a59-a8961037431b.png)

 - OS: [HiveOs

if you need anything else, please shout :)
thank you and regards,
Pawel

**Comment by SChernykh** [comment]
"Job not found" is a stale share. XMRig just displays it as rejected because technically it was rejected by the pool.

**Comment by SChernykh** [comment]
From what I can see it's only one of ~650 shares that is stale which is not bad at all. cpuminer probably displays them differently or doesn't display them as rejected at all.

**Comment by Lonnegan** [comment]
As soon as the rejected shares are just due to stale or not found jobs, everything is ok. When you look at your log, it's just a timing problem. The miner tried to send back a result at 08:41:35,219 o'clock. 0.05 s (!) earlier, the pool sent a new job. So sending back and getting a new job just overlapped. No reason to worry.

What would be worrying is when the pool rejects results without a timing problem is not so obvious. In this case instable hardware could be the trigger or a buggy miner.

**Comment by musiu** [comment]
> From what I can see it's only one of ~650 shares that is stale which is not bad at all. cpuminer probably displays them differently or doesn't display them as rejected at all.

ok, thank you very much for quick reply and explanation - wasn't aware of that.
Fingers crossed for future improvements of GR on XMRig!!

**Comment by musiu** [comment]
> As soon as the rejected shares are just due to stale or not found jobs, everything is ok. When you look at your log, it's just a timing problem. The miner tried to send back a result at 08:41:35,219 o'clock. 0.05 s (!) earlier, the pool sent a new job. So sending back and getting a new job just overlapped. No reason to worry.
> 
> What would be worrying is when the pool rejects results without a timing problem is not so obvious. In this case instable hardware could be the trigger or a buggy miner.

"buggy miner" part thats what I was affraid about ;)
