### ISSUE TITLE
v6.16.2 the miner does not see all the RAM

### ISSUE THREAD

**Issue by aim67** [xmrig/xmrig#2781]
Hello. Is this normal? The miner sees only two memory banks.

![screen](https://user-images.githubusercontent.com/38013803/144575066-1517ce3f-a614-428f-aeb9-4cb07950bb6f.png)
.

**Comment by SChernykh** [comment]
XMRig just displays DMI information there, it doesn't affect performance.

**Comment by aim67** [comment]
> XMRig just displays DMI information there, it doesn't affect performance.

ok. thanks for the reply. well, it does not display the information correctly. with up to 32 GB of memory, everything is displayed correctly.

**Comment by Spudz76** [comment]
DMI errors are always the BIOS fault.  Try updating, or it's just a broken manufacturer who doesn't care.

**Comment by aim67** [comment]
Tks.
