### ISSUE TITLE
How to set up a worker name?

### ISSUE THREAD

**Issue by nathanfleight** [xmrig/xmrig#2794]
I prefer using command line when using crypto miners, i don't like having to fiddle with configs as i find them tedious. i like to specify what i want in a single line, so my question is, How do i set up a worker name using command line? is it in wallet.workername format?

**Comment by Spudz76** [comment]
Depends on pool.

**Comment by dastardlyman12** [comment]
yes usually wallet.workername

**Comment by Spudz76** [comment]
Except some take it in the `pass` field.  Like MoneroOcean.

Almost nothing uses the separate/obvious `rig-id` guess that's for proxies only.

**Comment by PengYilong** [comment]
I am sure that it is the `pass` filed.

**Comment by kazmek** [comment]
There is a wizard that will write the command line for you. Spend some time in the wiki as well to learn a bit more about each option. https://xmrig.com/wizard
