### ISSUE TITLE
Color output issue on macOS if config file is used

### ISSUE THREAD

**Issue by fonix232** [xmrig/xmrig#281]
If I start xmrig with just a config file (no matter if it's the default config path or with `-c`, I get the basic, colorless output. The config file specifies that it is indeed intended to be a color output (the property `colors` is set to `true`), however I'm getting colorless output. If I apply the same settings via command line parameters, colors work just fine.

Versions: XMRig/2.4.3 libuv/1.18.0 clang/9.0.0

**Comment by namsur1234** [comment]
I also have a similar problem with no color. Color is present if there is no log file specified in json config file.
VERSIONS:     XMRig/2.4.3-beta2 libuv/1.14.1 OpenCL/2.0 MSVC/2017
Just noticed this is for CPU, not sure if that's an issue for me but it certainly is on AMD cards so I opened an issue there. I'm guessing the same code runs color for everything so i bet they all have an issue. I also noticed that pressing "h" would print the hashrate, pause the output and then it would stop/crash.
