### ISSUE TITLE
[Windows, 6.16.2] Pause-on-active doesn't work without console output

### ISSUE THREAD

**Issue by uz-spark** [xmrig/xmrig#2811]
On Windows, pause-on-active doesn't work (doesn't pause on machine activity) when miner is launched from 'NT Authority/SYSTEM' account, i.e either as a service or from task scheduler using system account as a task starter.

**Comment by uz-spark** [comment]
* or as 'NT Authority/LOCAL SERVICE' or '.../NETWORK SERVICE' eiher.

**Comment by uz-spark** [comment]
Disregard that, it doesn't work when there's no console window. I.e if "background" is enabled or it's ran as service or task.

**Comment by Spudz76** [comment]
The [function being used just doesn't work then](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getlastinputinfo#remarks) and there is no fixing it, by design, thanks Windows.

**Comment by uz-spark** [comment]
> The [function being used just doesn't work then](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getlastinputinfo#remarks) and there is no fixing it, by design, thanks Windows.

Neat ... thanks Windows indeed.
