### ISSUE TITLE
Command the miner to pause/resume with API calls

### ISSUE THREAD

**Issue by CidiRome** [xmrig/xmrig#2813]
Hi there.

Where I find the full set of commands/calls that can be made the API?

I want to pause and resume the operations with it, what I the commands?

Cheers.

**Comment by Spudz76** [comment]
Best you can do via API is send a different config file.

There are no keyboard controls wired into the API.

`/2/summary` or `/2/backends` or `/1/benchmark` or `/2/config` or `/2/dmi` are the only endpoints

**Comment by CidiRome** [comment]
Can it at least load config files with different names from the program folder?
Or
Where can I get examples of sending API instructions and config files with linux wget?
Cheers.

**Comment by Spudz76** [comment]
https://github.com/xmrig/xmrig/blob/master/doc/API.md#put-1config

except now use /2/config otherwise same

**Comment by CidiRome** [comment]
Will it actually overwrite the config.json file in the program folder, or the file will only be in memory until the program shuts down and next time it starts will be with the original file?

**Comment by Spudz76** [comment]
Overwrites.

**Comment by xmrig** [comment]
You can use `POST /json_rpc` with following bodies `{"method":"pause","id":1}` and `{"method":"resume","id":1}`.
Thank you.
