### ISSUE TITLE
RandomX Optimization Guide

### ISSUE THREAD

**Issue by MrSMiTHex** [xmrig/xmrig#2814]
@xmrig, https://xmrig.com/docs/miner/randomx-optimization-guide#memory-size-requirements

```
DDR3 memory is limited to about 1500-2000 H/s per channel (depending on frequency and timings)
DDR4 memory is limited to about 4000-6000 H/s per channel (depending on frequency and timings)
```

We may see dual channel cpu benchmarks above 20kH.
Are these limitations for one miner thread using single channel? or that info is out of date?

**Comment by SChernykh** [comment]
It's out of date.
