### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by narutokhanh** [xmrig/xmrig#284]
Sr, i have issue
![image](https://user-images.githubusercontent.com/34752052/34297460-e243c508-e74a-11e7-98dd-4af3360d71b0.png)
 please fix it

**Comment by nstojanoski** [comment]
it's a copy/paste issue :)

just arrow up and press Y again

**Comment by narutokhanh** [comment]
Sr,
i based on basic example code to created code mine aeoncoin but it was't working
I need you help me!!!

**Comment by narutokhanh** [comment]
Somebody, help me !!!
i based on basic example code to created code mine aeoncoin but it was't working
