### ISSUE TITLE
Ryzen 5 same rate with 2 threads and with 8

### ISSUE THREAD

**Issue by D0nVitalio** [xmrig/xmrig#2849]
**Describe the bug**
Hi. If I run config without --threads=8 or with this setting hash rate is nearly the same. Why and maybe I do smth wrong? Huge pages and MSR is enabled.
[http://dl4.joxi.net/drive/2021/12/30/0052/3914/3428170/70/07ac0b983f.jpg](url)

**Comment by Spudz76** [comment]
Hard to tell without startup output, and maybe some more info (but most of that is in the startup output).

**Comment by SChernykh** [comment]
Ryzen 5 3400G: 4C/4C, only 4 MB L3 cache. Don't try to run more than 2 threads, it won't help.

**Comment by D0nVitalio** [comment]
@SChernykh thanks. Closing.
