### ISSUE TITLE
when using --randomx-mode=light xmrig gets rejected shares on all pools. either remove this feature or fix it.

### ISSUE THREAD

**Issue by sfhdfshdfh** [xmrig/xmrig#2863]
...

**Comment by SChernykh** [comment]
I've just checked latest release builds in `xmrig-6.16.2-msvc-win64.zip`, `xmrig-6.16.2-gcc-win64.zip`, `xmrig-6.16.2-linux-static-x64.tar.gz`, `xmrig-6.16.2-linux-x64.tar.gz` and they all work with `--randomx-mode=light`. What OS and what XMRig version do you use? Show the screenshot of XMRig window right after start until it gets the first rejected share.

**Comment by sfhdfshdfh** [comment]
fixed. i had tested on a custom xmrig. it wasn't an original release. i'm back to original latest version and no problem.
