### ISSUE TITLE
How come cn/gpu is available for windows but not linux. Missing in Algorithms.h (v6.16.2)

### ISSUE THREAD

**Issue by gee1978** [xmrig/xmrig#2866]
Title says it all!?

**Comment by Spudz76** [comment]
cn-gpu was deleted from main xmrig long ago

To obtain it you use the MoneroOcean fork's code.

Or my own restoreCNGPU forks if you only want the CN-GPU in normal vanilla xmrig.

**Comment by gee1978** [comment]
Thnx, i'll give it a go and post mij result

**Comment by gee1978** [comment]
MoneroOcean is working for me.
