### ISSUE TITLE
if 1st --tls pool fails, all non tls backup pools fail too. there is no --notls param to use for backup pools.

### ISSUE THREAD

**Issue by sfhdfshdfh** [xmrig/xmrig#2872]
**Describe the bug**
when using --tls for first pool it expects all backup pools to be tls too, as a result, when 1st one fails the next ones fail too(for not being tls), there is no param such as --notls or --tls=0 to disable it for nontls backup pools individually. 
lack of params to disable tls for every single pool defined in batch file.

**To Reproduce**
i need something like this to work.
xmrig.exe -o tlspool.com:445 -u wallet --TLS -p x   -o backup-pool.com:80 -u wallet --NoTLS -p x ... and next tls & non tls backup pools

or just make xmrig try the pool without tls settings if there is no --tls specified for it. make --tls mandatory for every single pool and backup pools defined in the bat file to use tls mode.

**Expected behavior**

**Required data**

**Additional context**

**Comment by SChernykh** [comment]
You can setup every pool in any way you want in config.json. Don't try to use command line for advance setups.

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
@SChernykh 
so my idea #2564 was not that bad

**Comment by SChernykh** [comment]
No, it's a bad idea. Command line length is not enough for this on some systems. Embedded config is supported if you compile XMRig yourself.
