### ISSUE TITLE
Trying to make sense of this.

### ISSUE THREAD

**Issue by d3nd3** [xmrig/xmrig#2878]
https://github.com/xmrig/xmrig/blob/718c7e0fc1452353bc1361b85c8a2a4c81c1379e/src/base/kernel/config/BaseTransform.cpp#L125

where arg is a const char *
and m_coin is a class Coin instance.

How does this assignment work/compile.  Isn't it illegal to set a class to a const char *

**Comment by SChernykh** [comment]
Type conversion. const char* is converted into Coin via constructor: https://github.com/xmrig/xmrig/blob/718c7e0fc1452353bc1361b85c8a2a4c81c1379e/src/base/crypto/Coin.h#L52

**Comment by d3nd3** [comment]
I see, I didn't know that was possible. Its under "Implicit Conversion" ?

**Comment by SChernykh** [comment]
Yes, see https://en.cppreference.com/w/cpp/language/implicit_conversion
Right side is converted from const char* to Coin and then this temporary Coin object is copied into m_coin.
