### ISSUE TITLE
https://xmrig.com/docs/miner/hugepages spelling error

### ISSUE THREAD

**Issue by projectswastaken** [xmrig/xmrig#2889]
![image](https://user-images.githubusercontent.com/96654146/150685086-36e8e04f-e549-44e4-b7a8-58acac9dd831.png)
says please dont confusing

**Comment by koitsu** [comment]
Proposed change:

Old: XMRig use term **huge pages** on all platforms, please don't confusing.
New: XMRig refers to this feature as **huge pages** regardless of platform.

**Comment by xmrig** [comment]
@koitsu Done. Thank you.

**Comment by koitsu** [comment]
@SChernykh We should be able to resolve/close this ticket.  Thanks for fixing!
