### ISSUE TITLE
Compiling STATIC=ON doesn't produce a static binary -- dep on glibc

### ISSUE THREAD

**Issue by lfaoro** [xmrig/xmrig#2902]
the compiler warns us:
```../scripts/deps/lib/libcrypto.a(b_sock.o): In function `BIO_gethostbyname':
b_sock.c:(.text+0x71): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking```

On older systems the static binary which is not really static may throw errors e.g. `/lib64/libc.so.6: version `GLIBC_2.25'`

**Comment by Spudz76** [comment]
Static builds use non-glibc library that does support full static compilation, like uClibc or such
