### ISSUE TITLE
The xmrig priority setting does not work.

### ISSUE THREAD

**Issue by paolosezart** [xmrig/xmrig#2930]
Version xmrig 6.16.4, when run from the command line with the `--cpu-priority 1` parameter, the priority of the process xmrig.exe it remains "normal", although it should be "very low". The same with the `--cpu-priority 0` parameter
Tested on Windows 7 and windows 10
![CPU_priorety](https://user-images.githubusercontent.com/38177890/153759531-3a23eadd-e4e9-4ccc-8a89-4b6e1637bd2e.jpg)

It also doesn't help to edit the registry to:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\xmrig.exe\PerfOptions]
"CpuPriorityClass"=dword:00000001
```

What could be the problem?

P.S. When setting the parameter 
`"priority": 0`
in config.json process priority setting works correctly

**Comment by SChernykh** [comment]
Your command line options get overridden by config.json if you have it in the same folder.

**Comment by paolosezart** [comment]
> Your command line options get overridden by config.json if you have it in the same folder.

This is logical, but I was asking about the command line. What does config.json have to do with it?

**Comment by SChernykh** [comment]
It has everything to do with it. CPU priority is set in config.json too.

**Comment by paolosezart** [comment]
That is, it is impossible to set a priority via the command line? Although there is such a command

**Comment by SChernykh** [comment]
You can set it via command line if you don't have config.json in the folder. Either use command line, or config.json, but not both.

**Comment by paolosezart** [comment]
Thank you, friend.
But config.I do not use json in this case and it is not in the xmrig folder at all. That's why I asked the question

**Comment by paolosezart** [comment]
It turned out to be very simple. The parameter "--cpu-priority 0" when running from the command line or bat file, must be specified at the very end.
It's strange, it doesn't seem to have happened before

**Comment by Spudz76** [comment]
Oh yeah, that was already known, you just reminded me.
