### ISSUE TITLE
compile xmrig x86

### ISSUE THREAD

**Issue by velosipeds** [xmrig/xmrig#294]
Hello!
Please help me to compile mining client xmrig version for x32 windows always this error
#if !defined(_M_IX86) && !defined(_M_X64)
#error This header is specific to X86 and X64 targets
#endif 

my platform Windows 8.1 x64
Visual Studio 2015

**Comment by xmrig** [comment]
You sure this is the error? Miner should build fine with msvc2015, but is MSYS2 preferred for x86 builds.
Thank you.
