### ISSUE TITLE
File got virus

### ISSUE THREAD

**Issue by kingleo216** [xmrig/xmrig#2945]
**Describe the bug**
File got virus when download to windows

**To Reproduce**
Delete file

**Expected behavior**
The file should be clean.

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: [e.g. Windows]
 - For GPU related issues: information about GPUs and driver version.

**Additional context**

**Comment by Spudz76** [comment]
Eternally will be marked that way since miner-worms exist.  You must override.
