### ISSUE TITLE
Inclusion of cpu speed in xmr benchmark

### ISSUE THREAD

**Issue by heavyarms2112** [xmrig/xmrig#2949]
https://xmrig.com/benchmark is really useful to look up hw performance.
I see we already print out cpu model, mbo and ddr4 info. It would be great to have cpu speed in the benchmark report.

**Comment by Spudz76** [comment]
This requires deeper probing than simple DMI queries.  Maybe possible but would likely also require Ring0 access and another list of per-family MSR locations to read the actual running speed.
