### ISSUE TITLE
cpu.cmake is not properly configured on the arm branch for armv7 and some specification display errors

### ISSUE THREAD

**Issue by limitfan** [xmrig/xmrig#295]
I installed termux which is a great tool for touching the TUI of Linux environment on Android. 
Some minor errors are found when I build xmrig for armv7a and arm64-v8a android devices.
The sub cmakefile cpu.cmake is not properly configured on the arm branch.
The following image is the version without any parameter tuning or further optimization.
 ![nexus 5](https://i.loli.net/2017/12/26/5a41ed55672f7.png)
The following image running on the exynos 8890 variant version of S7 edge displays some erroneous CPU specifications.
 ![s7 edge ](https://i.loli.net/2017/12/26/5a41ed66450a7.png)

And one more question remaining is that how to port this miner on s390x arch when SIMD instructions are not properly available with certain virtualization technology.

**Comment by xmrig** [comment]
It known issue, runtime CPU detection and configuration still lacks for ARM.
About s390x I have no access to such hardware, if mining code available somewhere it might help.
Thank you.

**Comment by limitfan** [comment]
Hi, thank you for your concern about these minor issues.
It's really relatively meaningless to implement a miner on s390x arch which
is surely built for centralized transaction processings.
If you want to have a try on these machines, you can check here:
https://linuxone20.cloud.marist.edu/cloud/#/register
It provides free trials of these virtualized machines with high Unix
benchmark and pystone score.

**Comment by davidtavarez** [comment]
@limitfan can you share how do you did it? thanks.

**Comment by limitfan** [comment]
@davidtavarez I did it by following these steps:

1. Install [Termux ](https://termux.com/)on your android devices.

2. Open Termux and use the same build instruction as [this](https://github.com/xmrig/xmrig/wiki/Ubuntu-Build) with some minor changes.

```
apt update
apt install git  cmake libuv-dev 
git clone https://github.com/xmrig/xmrig.git
cd xmrig
mkdir build
cd build
cmake .. -DWITH_HTTPD=OFF
make
```
If you can build xmrig binary without any problem, you can run it the same way as you did in a Linux environment. Termux just turned headless Linux computing in most cases into a touchable one.

**Comment by davidtavarez** [comment]
Cool, man. It works!

Now I can do something like `Process proc = Runtime.getRuntime().exec("xrmig");`

**Comment by limitfan** [comment]
@davidtavarez You may have a try with this method which maybe is invalid on higher Android versions and ldding xmrig binary reveals its dependency.
The recommended and canonical way is to build with Android's official NDK cross platform toolchain to generate a lib and package it into an apk.

**Comment by cmorsucci** [comment]
@limitfan is there a guide to be able to compile with NDK and be able to put it in my Android app?

**Comment by limitfan** [comment]
@cmorsucci It's currently not available and not profitable for implementing such a miner which will destablize mobile users' experience of your Android apps. Some altcoin uses your cpu model to credit your hashrate without actually hashing anything for a period of time. If your app got numbers of active users, you will easily find more suitable ways for generating additional incomes.

**Comment by cmorsucci** [comment]
I understand .. but I want to try to incorporate it in one of my apps, is there a mini guide on how to compile it with ndk?

**Comment by limitfan** [comment]
@cmorsucci Build it in similar way in accordance with [xmrig's Windows platform build](https://github.com/xmrig/xmrig/wiki/Windows-Build).

**Comment by cmorsucci** [comment]
mmm ok, you're not helping me like that ..

**Comment by limitfan** [comment]
You are causing too much trouble and didn't help me solve my original issue.
Thank you for your reading and I will close this issue for now.
