### ISSUE TITLE
BUG Report , Taskkill wont work with xmrig

### ISSUE THREAD

**Issue by mr-459** [xmrig/xmrig#2950]
**Describe the bug**
when you run taskkill /IM xmrig.exe /T
it wont kill xmrig and you need to force xmrig to kill
witch is not what i want

**To Reproduce**
i have no idea

**Expected behavior**
xmrig gets killed like when you press ctrl+c

**Required data**
 - video of explaining bug : https://ufile.io/jioondsw
 - OS: Windows 11.

**Comment by timk74** [comment]
taskkill /im xmrig.exe /f

**Comment by mr-459** [comment]
> taskkill /im xmrig.exe /f

bro , are you idiot?
i dont want to kill by force
because an upstream will remain on my xmrig-proxy server (because of simple mode)
im not searching for way to kill , im searching for fix of bug

**Comment by Spudz76** [comment]
Connections do not outlive a dead process regardless which way you kill it?

**Comment by mr-459** [comment]
> 

when i exit xmrig.exe by ctrl+c , they outlive
but when i force it , they dont
and i see many many workers on my xmrig-proxy , while they are not really workers
