### ISSUE TITLE
Xmrig for Android

### ISSUE THREAD

**Issue by steph3094** [xmrig/xmrig#2959]
Hello,

I have xmrig for Android, but i have this error.

Tue Mar 08 2022 15:28:13 GMT-0500 [2022-03-08 15:28:12.218] unable to open "/data/app/~~RUPpzDBd4C6BjyXfhZnbvA==/com.xmrigforandroid-XNtTEuxyBxqxayu9JqzSdg==/lib/arm64/config.json".
Tue Mar 08 2022 15:28:14 GMT-0500 [2022-03-08 15:28:12.220] unable to open "/data/.xmrig.json".
Tue Mar 08 2022 15:28:14 GMT-0500 [2022-03-08 15:28:12.220] unable to open "/data/.config/xmrig.json".
Tue Mar 08 2022 15:28:15 GMT-0500 [2022-03-08 15:28:12.220] no valid configuration found, try https://xmrig.com/wizard

Anyone can help me ?

**Comment by uwu-as-a-service** [comment]
Put your config.json in the same directory as the xmrig binary and try
