### ISSUE TITLE
is there any way that after configuring the json file is not edited, or read by others

### ISSUE THREAD

**Issue by kalifan** [xmrig/xmrig#296]
well this is my question thanks.

**Comment by TheUnity** [comment]
edit configuration directly in miner

**Comment by xmrig** [comment]
If I correctly understand your question only one way is embed you config into source and then compile the miner.
Thank you.

**Comment by flymarker** [comment]
can you give a little hint how to embed config into source? thanks in advance.

**Comment by xmrig** [comment]
Check #109 and #136. I think there was more related issues, but quick search found just 2.
Thank you.

**Comment by xmrig** [comment]
Merge with #306
