### ISSUE TITLE
Nicehash XMRig always causing Windows 10 bluescreen every few minutes of mining

### ISSUE THREAD

**Issue by calvinvalerian** [xmrig/xmrig#2966]
Even I have tried reinstall my Windows 10 x64 and install the drivers from orginal CD came from the motherboard.

**Comment by uwu-as-a-service** [comment]
Get a clean install of Windows 10, fully update it, and try using the drivers provided on the manufacturer's website instead

**Comment by Lonnegan** [comment]
And do some stability tests. Run something like Prime95 for a few hours and check if your system is stable at all.

**Comment by calvinvalerian** [comment]
@Lonnegan just for Prime95 for 25 minutes and I got bluescreen Stop code: MEMORY MANAGEMENT

**Comment by calvinvalerian** [comment]
@uwu-as-a-service done what you told me to do and still I get bluescreen stop code: KERNEL SECURITY CHECK FAILURE

**Comment by calvinvalerian** [comment]
With CPU Disabled I never get bluescreen for the entire 30 days
![Screenshot (91)](https://user-images.githubusercontent.com/18316781/158745243-1a8866c3-a070-4cdc-ba7a-255baabf83c2.png)

**Comment by Lonnegan** [comment]
Ok, when you get blue screens running CPU stability tests like Prime95, your PC is NOT stable! Getting MEMORY MANAGEMENT may indicate, you have a defective RAM module, too much overclocked RAM or too much overclocked CPU or the CPU is getting too hot.

Check if your system (CPU clock, DRAM clock) is running as specified and check the CPU temperature with tools like HWMonitor. 

If everything is ok and the bluescreens still occur, take one of the DRAM modules out of your system und check again. If still BSOD, put it in again and take the other one out.

You have to find out where the weak point of your system is.

**Comment by calvinvalerian** [comment]
Wow you are right about the overclock RAM.. I have RAM OC software installed that came with the motherboard CD driver https://www.asrock.com/MB/Intel/H310CM-DVS/index.asp#Download

the name is ASRock A-Tuning utility ver:3.0.220

I have uninstalled it and I have ran NiceHash xmrig for a day without any bluescreen
