### ISSUE TITLE
AV Deleted Exe file

### ISSUE THREAD

**Issue by jagadheesan** [xmrig/xmrig#297]
antivirus programmes deleted the xmrig.exe file..

**Comment by Dhruv420** [comment]
@jagadheesan don't worry its a false positive.Just add xmrig.exe in the exclusion list of your Antivirus.

**Comment by Dhruv420** [comment]
@jagadheesan Mining software is often considered a virus since botnets use them on infected machines.

If you are using it on purpose, you are fine,no need to worry.

**Comment by C0tt0** [comment]
BEWARE : Both Chrome and Malwarebyte reported the 64bit version as infected. "Xmrig-2.6.3-gcc-win64.zip"

Malwarebytes
www.malwarebytes.com
-Log Details-
Scan Date: 6/24/18
Scan Time: 11:54 PM
-Software Information-
Version: 3.5.1.2522
Components Version: 1.0.374
Update Package Version: 1.0.5615

-System Information-
OS: Windows 10 (Build 17134.112)
CPU: x64
File System: NTFS

-Scan Summary-
Scan Type: Custom Scan
Scan Initiated By: Manual
Result: Completed
Objects Scanned: 1
Threats Detected: 2
Threats Quarantined: 2
Time Elapsed: 0 min, 22 sec


-Scan Details-
Process: 0
(No malicious items detected)

Module: 0
(No malicious items detected)

Registry Key: 0
(No malicious items detected)

Registry Value: 0
(No malicious items detected)

Registry Data: 0
(No malicious items detected)
Data Stream: 0
(No malicious items detected)
Folder: 0
(No malicious items detected)
File: 2
Trojan.BitCoinMiner, C:\USERS\DAD\APPDATA\ROAMING\Microsoft\Windows\Recent\xmrig-2.6.3-gcc-win64.zip.lnk, Quarantined, [525], [533042],1.0.5615
Trojan.BitCoinMiner, E:\TMP\XMRIG-2.6.3-GCC-WIN64.ZIP, Quarantined, [525], [533042],1.0.5615
Physical Sector: 0
(No malicious items detected)
WMI: 0
(No malicious items detected)
(end)
