### ISSUE TITLE
Clarification of RandomX + huge pages behaviour on ARMv8

### ISSUE THREAD

**Issue by KodeMunkie** [xmrig/xmrig#2970]
**Describe the bug**
XMRig 6.16.2 on ARMv8 (Raspberry Pi 4 8GB) states that huge pages are available, but appears unable to allocate the huge page memory.

**To Reproduce**
Compile and run XMRig for ARM64 on a Raspberry Pi 4 8GB. Watch the startup output show huge pages supported, then fail to allocate.

**Expected behavior**
Huge page memory is allocated - text for memory allocation is green and showing 100%.

**Required data**
```
 * ABOUT        XMRig/6.16.2 gcc/10.2.1
 * LIBS         libuv/1.40.0 OpenSSL/1.1.1k hwloc/2.4.1
...

 * HUGE PAGES   supported
 * 1GB PAGES    unavailable
 * CPU          ARM Cortex-A72 (1) 64-bit -AES
                L2:0.0 MB L3:0.0 MB 4C/4T NUMA:1
 * MEMORY       0.7/7.6 GB (9%)
...

[2022-03-14 20:22:00.909]  randomx  allocated 2336 MB (2080+256) huge pages 0% 0/1168 +JIT (1 ms)
...
[2022-03-14 20:22:27.465]  cpu      READY threads 2/2 (2) huge pages 0% 0/2 memory 4096 KB (1 ms)
```

**Additional context**
Nb. mostly likely unrelated but the L2 cache isn't recognised either (should be 1MB).

**Comment by Spudz76** [comment]
Does it work when `echo 3 > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages` before running xmrig?

**Comment by Spudz76** [comment]
Also could try forcing early allocation with added kernel args:
```
hugepagesz=1GB hugepages=3
```

Sometimes there aren't 3GB of aligned free memory after boot.

**Comment by Spudz76** [comment]
Oops you meant 2MB hugepages.  ARM doesn't even support 1GB.  Same tips except replace 1084576 with 2048, and number of pages to ~1200

**Comment by xmrig** [comment]
@Spudz76 Technically ARM supports 1GB pages and other sizes too, it can be tested on Amazon instances, but for small boards this statement is true.
