### ISSUE TITLE
XMRig server certificate verification failure

### ISSUE THREAD

**Issue by kamadom** [xmrig/xmrig#2980]
**Describe the bug**

**To Reproduce**
git clone https://github.com/xmrig/xmrig.git

Cloning into 'xmrig'...

fatal: unable to access 'https://github.com/xmrig/xmrig.git/': server certificate verification failed. CAfile: none CRLfile: none

**Expected behavior**
After cloning the XMRig repository from GITHUB, be able to install xmrig from source using cmake 

**Required data**
 - Miner log as text or screenshot (Not Applicable)
 - Config file or command line (without wallets) "git clone https://github.com/xmrig/xmrig.git"
 - OS: [e.g. Windows] "Both Ubuntu 20.04 and ARMv8 return same result"
 - For GPU related issues: information about GPUs and driver version. (Not Applicable)

**Additional context**
"Anyone have a workaround for the XMRig server certificate verification failure?"

**Comment by Spudz76** [comment]
Works fine from here, was just renewed on the 14th.

**Comment by snipeTR** [comment]
Check date, time or timezone

**Comment by kamadom** [comment]
Thanks for the reply.  During that period, I found there was a problem with
my WAN feed, specifically the NTP service, that caused other issues due to
time synchronization problems.  That is fixed now.

Charles
