### ISSUE TITLE
dont run cmd parameter

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig#2982]
input:

> -DWITH_TLS=OFF
-DWITH_ASM=OFF
-DWITH_OPENCL=OFF
-DWITH_CUDA=OFF
-DWITH_NVML=OFF
-DWITH_ADL=OFF
-DWITH_BENCHMARK=OFF
-DWITH_CN_LITE=OFF
-DWITH_CN_HEAVY=OFF
-DWITH_CN_PICO=OFF
-DWITH_CN_FEMTO=OFF
-DWITH_RANDOMX=OFF
-DWITH_ARGON2=OFF
-DWITH_KAWPOW=OFF
-DWITH_GHOSTRIDER=OFF

cmake .. -G "Unix Makefiles" -DXMRIG_DEPS=c:/xmrig-deps/gcc/x86 -DWITH_TLS=OFF -DWITH_ASM=OFF -DWITH_OPENCL=OFF -DWITH_CUDA=OFF -DWITH_NVML=OFF -DWITH_ADL=OFF -DWITH_BENCHMARK=OFF -DWITH_CN_LITE=OFF -DWITH_CN_HEAVY=OFF -DWITH_CN_PICO=OFF -DWITH_CN_FEMTO=OFF -DWITH_RANDOMX=OFF -DWITH_ARGON2=OFF -DWITH_KAWPOW=OFF -DWITH_GHOSTRIDER=OFF
make 

output:

>https://pastebin.com/8dKFv0YW

![image](https://user-images.githubusercontent.com/31975916/159218577-565609bb-14c7-4eb4-877d-1fa4af3392f6.png)

**Comment by SChernykh** [comment]
astrobwt/v2 requires TLS

**Comment by snipeTR** [comment]
> astrobwt/v2 requires TLS

cmake betiğine bence bir uyarı mesajı eklenebilirmi?

**Comment by snipeTR** [comment]
Can a warning message be added to the cmake script? For "-DWITH_TLS=OFF".
