### ISSUE TITLE
Killed process due to oomkiller on ubuntu 21

### ISSUE THREAD

**Issue by Nolzark-Dev** [xmrig/xmrig#2986]
So whenever I boot up xmrig it runs for a few seconds then it stops working with the simple message: Killed. Ive discovered with dmesg that oomkiller has been stopping the process. (Running i5 5th gen, 4GB ram. (old macbook))

**Comment by Spudz76** [comment]
RandomX requires 2.5GB+ so it's probably not lying...

**Comment by WalterWhiteButAProgrammer** [comment]
I have 4GB of ddr3

**Comment by SChernykh** [comment]
And these 4 GB are most likely already taken by OS and other programs. You need 2.5 GB of **free** memory.
