### ISSUE TITLE
无法运行程序，连接被拒绝，log无颜色

### ISSUE THREAD

**Issue by chwncy** [xmrig/xmrig#2992]
![1](https://user-images.githubusercontent.com/31879464/160039581-1ef37d0b-f7fe-47ee-899a-f82e98b573b6.png)

无法连接到pool.supportxmr.com:3333，但是又能ping得通，其他电脑没有问题，就这个不行，而且显示的log没有颜色，还望大佬帮忙解答一下，谢谢！

**Comment by pdxwebdev** [comment]
请确认你能够连接到3333端口的服务。Ping可能工作，但3333端口可能被封锁。

**Comment by chwncy** [comment]
> 请确认你能够连接到3333端口的服务。Ping可能工作，但3333端口可能被封锁。

我用telnet测试了一下，只有80端口没有被封，然后我把端口改成80之后，就显示以下错误
![1](https://user-images.githubusercontent.com/31879464/160044329-5e62fb72-9337-4876-a244-8ccda04b9844.png)

**Comment by pdxwebdev** [comment]
尝试使用3333端口进行telnet。XMRig不能解析从监听端口80的应用程序返回的输出。

**Comment by chwncy** [comment]
> 尝试使用3333端口进行telnet。XMRig不能解析从监听端口80的应用程序返回的输出。

感谢，我尝试了其他端口，貌似均无法使用，感觉是运营商已封了该域名的所有端口，已放弃

**Comment by pdxwebdev** [comment]
端口3333对我来说是有效的。我相信问题出在你的网络上。
![Screenshot from 2022-03-24 20-47-13](https://user-images.githubusercontent.com/490176/160050478-8ec1cf5f-5439-467a-ba0b-dde808a1ab32.png)

**Comment by chwncy** [comment]
是的，应该是网络问题，我其他电脑是没有问题的

发自我的iPhone

在 2022年3月25日，11:47，pdxwebdev ***@***.***> 写道：

﻿

端口3333对我来说是有效的。我相信问题出在你的网络上。
[Screenshot from 2022-03-24 20-47-13]<https://user-images.githubusercontent.com/490176/160050478-8ec1cf5f-5439-467a-ba0b-dde808a1ab32.png>
