### ISSUE TITLE
Optimize for Ryzen platform (5k series)

### ISSUE THREAD

**Issue by mooleshacat** [xmrig/xmrig#2994]
Would like to see optimization for Zen 3 on the 5950x and other 5k series Ryzen

There is no mention of Zen specific optimization. Maybe update the readme to mention whether it is there or not.

**Comment by Spudz76** [comment]
```
      --asm=ASM                 ASM optimizations, possible values: auto, none, intel, ryzen, bulldozer
```

Ryzen is listed right there?

**Comment by Spudz76** [comment]
There were no code-based changes between Zen2 and Zen3

Zen2 is better by slight margin that Zen3 but that was due to some internal/physical changes which can't be coded around.

**Comment by SChernykh** [comment]
RandomX MSR mod has specific settings for Zen3, also cn/heavy has optimized code for Zen3. When something can be made faster on a specific CPU, it is taken care of.

**Comment by mooleshacat** [comment]
> Ryzen is listed right there?

I never saw that, because I was looking at the readme... It would be nice to see this information in the readme, because otherwise you have to git clone, compile, and then execute with --help flag to find it.
