### ISSUE TITLE
SELF THREAS TEST FAILED RTM MINING 

### ISSUE THREAD

**Issue by rap143** [xmrig/xmrig#2995]
when I try to run the miner it always shows a error in which the threads failed to start but when I look on YouTube it shows some other algo popping up while mine shows use profile ghost rider but still not work pls help

**Comment by snipeTR** [comment]
Nobody here is a psychic. Do not expect us to make a futile effort by estimating which parameters, which algorithm, which operating system you are using, and trying to provide solutions for each estimation separately.
