### ISSUE TITLE
Feature Request: panthera algo

### ISSUE THREAD

**Issue by Tohelo101** [xmrig/xmrig#2998]
Hello could be possible to add panthera algo in xmrig ?

**Comment by xmrig** [comment]
You can use third party fork for this algorithm https://github.com/MoneroOcean/xmrig
Thank you.

**Comment by benthetechguy** [comment]
@xmrig @SChernykh, is there a specific reason why panthera support can't be upstreamed into XMRig proper? I've found it to be the most profitable algorithm on many of my devices.

**Comment by SChernykh** [comment]
Because it doesn't work when compiled with MSVC, all shares are invalid.

**Comment by benthetechguy** [comment]
Just tested by compiling with both MSVC and gcc. It doesn't just occur when compiled with MSVC, but running on Windows in general. I've reported the bug to them.
