### ISSUE TITLE
how to use xmrig 2.0 on ubuntu ?

### ISSUE THREAD

**Issue by local139** [xmrig/xmrig#30]
hello, friend, i need your help
i use the old 0.8.2 , but today i find you update, so i have a try, but not work.
simple out, i do not know how to use the new verision (2.0) on ubuntu. 
apt-get install git build-essential cmake libcurl4-openssl-dev
git clone https://github.com/xmrig/xmrig
cd xmrig
then ??????

**Comment by local139** [comment]
or the 2.0 verision is for windows only, it's not for linux?

**Comment by xmrig** [comment]
There updated instructions https://github.com/xmrig/xmrig/wiki/Build only one difference libcurl4-openssl-dev no more required, instead libuv1-dev required.

Also on download page prebuild version for Ubuntu 16.04 available too.
Thank you.

**Comment by local139** [comment]
thanks
does C++ better C ?  OR it(C++) is faster than C ?

**Comment by local139** [comment]
2、am i  must install gcc 7.1 ? dude
3、it is will be faster ? if i install gcc 7.1

**Comment by local139** [comment]
i do not want install gcc-7 g++-7 , does it will be work well ?

**Comment by xmrig** [comment]
gcc 7.1 little be faster, but optional, gcc 5.4 fine too.
C++ more easy for development and libuv nice lib for async io.

**Comment by local139** [comment]
thanks
