### ISSUE TITLE
Am i mining, what does the lines mean

### ISSUE THREAD

**Issue by MaxQiu0108** [xmrig/xmrig#3007]
What does the commands mean, and the lines?
![image](https://user-images.githubusercontent.com/102963434/161941687-121bfd3b-d2dc-4cda-9986-a988953e6bd7.png)

**Comment by Spudz76** [comment]
Yes you're mining, the fixed job difficulty of 50000 is too high for your hashrate though so you will miss payments.  Should be an `accept` every 30 seconds or so.  Proper difficulty would be 30 * 370 = 11100.  At 50000 you might get a result every 50000 / 370 = 135 seconds which is too long (main chain jobs switch every ~120 seconds).

Not sure if minerxmr supports variable diff or custom fixed diff.  But also minexmr is too big you should use literally any other pool (but pick one with adjustable diff).

**Comment by MaxQiu0108** [comment]
really! But I have 0.000042 coins that has not been not drawn

**Comment by Spudz76** [comment]
0.000042XMR is less than one cent USD.  Not a loss?

**Comment by MaxQiu0108** [comment]
oh, ok

**Comment by MaxQiu0108** [comment]
thanks
