### ISSUE TITLE
Why i don't have any acceptions?

### ISSUE THREAD

**Issue by MaxQiu0108** [xmrig/xmrig#3010]
![image](https://user-images.githubusercontent.com/102963434/162138628-d64c3b70-e852-4f56-887e-71df01ed1d5f.png)
I am at us-west-minexmr.com pool

**Comment by MaxQiu0108** [comment]
ok which pool do you recommend?

**Comment by Lonnegan** [comment]
hashcity.org starts at diff 1000 when you connect to port 3100, so you don't even need to use a fixed diff. Besides it is a PPS pool, so you get bucks for every result you return, regardless if the pool finds a block at that moment or not. So it's not so important that you return results regulary to get a part of the reward of the last block found (PROP pool) or to stay within the PPLNS window to get a fraction of the reward.

**Comment by MaxQiu0108** [comment]
But since i have to bypass china's firewall,i have to use ports 443,i cant connect to others
what shall i do?

**Comment by Lonnegan** [comment]
You can try hashvault.pro. They for sure listen to port 443 (SSL) and as far as I can remember they adjust the diff automatically so that your miner can return a result every 30-60 seconds. I don't know if they do it so low that this is possible with just 200 H/s, but it's worth trying.

**Comment by MaxQiu0108** [comment]
ok thx
