### ISSUE TITLE
What Pools to Mine with Low Monero Hashrate of 155.

### ISSUE THREAD

**Issue by MaxQiu0108** [xmrig/xmrig#3013]
I want lower difficulties, i have 0.000045 moneros in minexmr in 3 days, is it worth to switch? if yes, please recommend some pools.

**Comment by Spudz76** [comment]
MoneroOcean

**Comment by MaxQiu0108** [comment]
ok

**Comment by Spudz76** [comment]
Bonus there is also that you can run other algos and still be paid out in XMR at the same value.  With your bad-at-RandomX processors, this will help get max payout (even though you won't directly be mining on the Monero Blockchain).

Other algos don't need 2MB of cache per thread, or good fast memory, or other specs to be as high.  Some will run all four threads as well.  But it will select algo by what the current exchange rates are, whatever usage it picks is worth the most at that time (work smarter not necessarily harder).
