### ISSUE TITLE
Nvidia Kernel Crash 

### ISSUE THREAD

**Issue by AnonJunkie** [xmrig/xmrig#302]
I loaded up Xmrig on my gaming laptop with Dual Geforce GT 965M(x2) it runs for about 2-3 seconds then crashes and windows pops up with a Nvidia kernel error any ideas of how to stop the crash

**Comment by silentj408** [comment]
I tired remove 1 card from the config file but I get the same error unspecified cryptonight error then crashes, then windows pops u with the kernel message

**Comment by silentj408** [comment]
anyone? i loaded up nicehash to see if i was crazy and its working fine idk why i cant get xmrig to mine on my GPUS

**Comment by Dhruv420** [comment]
@silentj408 i think because the one you are using is a cpu miner.You can download Nvidia gpu xmrig miner from here(https://github.com/xmrig/xmrig-nvidia)

**Comment by silentj408** [comment]
i'm definitely using the nvidia program just like on my other machines, only this one has 2 GFX cards in it

**Comment by Dhruv420** [comment]
@silentj408 can you post a screenshot of the error

**Comment by silentj408** [comment]
Is there a log file? It happens so fast

**Comment by btx3** [comment]
Try running it in a Command Prompt window (`Win + R`, type `cmd`) instead of clicking on it from the desktop, that should make it stop once it crashes and show what went wrong.
