### ISSUE TITLE
The CXX compiler identification is unknown

### ISSUE THREAD

**Issue by Xargana** [xmrig/xmrig#3022]
when  i run the command "cmake .." it gives an error saying, The CXX compiler identification is unknown

-- The CXX compiler identification is unknown
   Called from: [3]	/usr/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake
                [2]	/usr/share/cmake-3.16/Modules/CMakeDetermineCXXCompiler.cmake
                [1]	/home/merta/Masaüstü/mine/xmrig/CMakeLists.txt
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

i dont know that much of coding. please help

**Comment by Spudz76** [comment]
`apt install build-essential` and such?

**Comment by Xargana** [comment]
and now its missing HWLOC_LIBRARY HWLOC_INCLUDE_DIR is there a library i need to install?

**Comment by Xargana** [comment]
i found how to do it. thanks for help
