### ISSUE TITLE
Cmakelist.txt no found

### ISSUE THREAD

**Issue by openwrtfirmwarecostum** [xmrig/xmrig#3029]
hy @xmrig 

is there a way to change without creating a build folder inside the xmrig folder? if i run cmake.. in xmrig folder there is no cmake response. and if I create a build folder inside the xmrig folder and enter the cmake command .. the cmake process exists. this is something bad to do with the mkdir build method and i tried to create an xmrig file in openwrt and it seems the openwrt build system can't find Cmakelist.txt because of the mkdir build. can i change that?

[eror.txt](https://github.com/xmrig/xmrig/files/8501841/eror.txt)

**Comment by Spudz76** [comment]
That is just how CMake works.  When you run `cmake` the present working directory should be the build directory, and the argument `..` is the source directory.

If you must launch from the source directory then you could use `cmake --build ./build .` but I think that still requires preparatory `mkdir build`  Notice how since the argument is the source path, and in this example we're in the source directory as present working directory, we gave single `.` rather than `..` and instead specified the build-dir since we're not presently working inside it as normally expected.

**Comment by openwrtfirmwarecostum** [comment]
i tried monero i got no error

https://github.com/monero-project/monero

**Comment by Spudz76** [comment]
What sort of recipe are you using for OpenWRT.  Did you make a whole proper package?

**Comment by openwrtfirmwarecostum** [comment]
yes i made what i need monero which is on github openwrt. this will fail if xmrig build folder has to be created manually and I see monero doesn't create build folder manually

**Comment by openwrtfirmwarecostum** [comment]
i went through cmake but i got a new error

toolchain-aarch64_cortex-a53_gcc-8.4.0_musl/bin/../lib/gcc/aarch64-openwrt-linux-musl/8.4.0/../../../../aarch64-openwrt-linux-musl/bin/ld: /home/admin/66/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_musl/aarch64-openwrt-linux-musl/bin/../../../toolchain-aarch64_cortex-a53_gcc-8.4.0_musl/lib64/libgcc_s.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by predators46** [comment]
@Spudz76 

where can i add this?

`-lgcc_eh`

**Comment by Spudz76** [comment]
[CMakeLists.txt line 240](https://github.com/xmrig/xmrig/blob/master/CMakeLists.txt#L240)

```
target_link_libraries(${CMAKE_PROJECT_NAME} ${XMRIG_ASM_LIBRARY} ${OPENSSL_LIBRARIES} ${UV_LIBRARIES} ${EXTRA_LIBS} ${CPUID_LIB} ${ARGON2_LIBRARY} ${ETHASH_LIBRARY} ${GHOSTRIDER_LIBRARY} gcc_eh)
```

Should do it.

**Comment by predators46** [comment]
> [CMakeLists.txt line 240](https://github.com/xmrig/xmrig/blob/master/CMakeLists.txt#L240)
> 
> ```
> target_link_libraries(${CMAKE_PROJECT_NAME} ${XMRIG_ASM_LIBRARY} ${OPENSSL_LIBRARIES} ${UV_LIBRARIES} ${EXTRA_LIBS} ${CPUID_LIB} ${ARGON2_LIBRARY} ${ETHASH_LIBRARY} ${GHOSTRIDER_LIBRARY} gcc_eh)
> ```
> 
> Should do it.

is this correct i added it?

target_link_libraries(${CMAKE_PROJECT_NAME} ${XMRIG_ASM_LIBRARY} ${OPENSSL_LIBRARIES} ${UV_LIBRARIES} ${EXTRA_LIBS} ${CPUID_LIB} ${ARGON2_LIBRARY} ${ETHASH_LIBRARY} ${GHOSTRIDER_LIBRARY} -lgcc_eh)

**Comment by predators46** [comment]
> [CMakeLists.txt line 240](https://github.com/xmrig/xmrig/blob/master/CMakeLists.txt#L240)
> 
> ```
> target_link_libraries(${CMAKE_PROJECT_NAME} ${XMRIG_ASM_LIBRARY} ${OPENSSL_LIBRARIES} ${UV_LIBRARIES} ${EXTRA_LIBS} ${CPUID_LIB} ${ARGON2_LIBRARY} ${ETHASH_LIBRARY} ${GHOSTRIDER_LIBRARY} gcc_eh)
> ```
> 
> Should do it.

Thanks friend  fix suport openwrt

**Comment by openwrtfirmwarecostum** [comment]
Thanks @Spudz76  @predators46
