### ISSUE TITLE
When does xmr rig deposit money to my wallet?

### ISSUE THREAD

**Issue by machineaaaax** [xmrig/xmrig#3043]
I have added my wallet id and selected a pool. Is there a certain time interval after which I should visit website or do x job to collect xmr or does it automatically mines and deposits to my wallet?

**Comment by machineaaaax** [comment]
My hashrate is 1000H/s and its displaying speed from time to time. When can I expect to get xmr or my hashrate is too low to get any xmr at all?

**Comment by Spudz76** [comment]
Depends completely on what pool.  Their site will have a page about their payout process, such as minimum withdrawal balance required.  If it is the most popular around 0.03XMR then that will take around 6.1 months at your hashrate.

**Comment by machineaaaax** [comment]
@Spudz76 do i need to go to their website and do something to withdraw? Can i run multiple xmrig app in same wallet and pool to reduce 6 months?

**Comment by machineaaaax** [comment]
Is there a process? Can i get link or something like that if there is?

**Comment by machineaaaax** [comment]
@Spudz76

**Comment by Spudz76** [comment]
Nobody knows except your pool FAQ.  Payouts are dictated by the pool and have nothing to do with xmrig (other than that's how you "get to work" but you "work for the pool" so it's their employment rules, which will be on their website).  Some pools allow you to set a lower than default payout level but then payment fees are usually higher, some have manual payout but extra high fees.

Yes you can run multiple xmrigs if they are on separate computers, obviously once one is running it's using every available part of the CPU.

**Comment by machineaaaax** [comment]
One more question does pool automatically send xme to my wallety once I reach certain amount of money?

**Comment by machineaaaax** [comment]
@Spudz76

**Comment by machineaaaax** [comment]
I am using xmr.pool.gntl.co.uk, does it send automatically if not which pools send money automatically after certain threshold?

**Comment by machineaaaax** [comment]
Aslo, if I put multiple pools in my config.json, will xmrig mine each of time over time or will it get stuck with mining one pool infinitely? If would be better if xmrig has option to mine each pool for certain time and change

**Comment by Spudz76** [comment]
Yes you need to run everything to your one chosen pool. Pool hopping would penalize your already low earnings.

[Your pool FAQ](https://github.com/The-GNTL-Project/Documentation/wiki/FAQ#how-payouts-work)

**Comment by machineaaaax** [comment]
thanks @Spudz76
