### ISSUE TITLE
The Small vRam GPU can`t mining Kawpow(opencl)

### ISSUE THREAD

**Issue by xzh767** [xmrig/xmrig#3045]
If the GPU`S Vram<2048MB，It can`t minging Kawpow,but the xmrig will try to mining it
The opencl will dead,but xmrig don`t know it
Xmrig will keep trying
It can lead to a dead cycle

**Comment by Spudz76** [comment]
Yes so when kawpow DAG becomes too large, you disable kawpow.

**Comment by xzh767** [comment]
> Yes so when kawpow DAG becomes too large, you disable kawpow.

But If In Algo-Testing,xmrig will try to mine kawpow
opencl can't produce any hashrate
Xmrig can't break and in a dead cycle

**Comment by xzh767** [comment]
And How can disable Kawpow and run Algo-Testing?

**Comment by SChernykh** [comment]
Algo-Testing is not a part of the official Xmrig, ask this question to whoever added it (MoneroOcean?)

**Comment by xzh767** [comment]
> Algo-Testing is not a part of the official Xmrig, ask this question to whoever added it (MoneroOcean?)

emmmmm
I know
But How can disable Kawpow?

**Comment by Spudz76** [comment]
Compile with `-DWITH_KAWPOW=OFF` and then it won't even know it's a thing (that's what I do).

I have been working on ways to actually disable algorithms because I think the above is the only way it works.  But it may also be able to skip based on DAG size.

**Comment by Spudz76** [comment]
And yes you should be posting MO problems over at [MoneroOcean/xmrig Issues](https://github.com/MoneroOcean/xmrig/issues)

**Comment by xzh767** [comment]
> Compile with `-DWITH_KAWPOW=OFF` and then it won't even know it's a thing (that's what I do).
> 
> I have been working on ways to actually disable algorithms because I think the above is the only way it works. But it may also be able to skip based on DAG size.

I know and search
But...Is not have how to compile on windows

**Comment by xzh767** [comment]
I Knew
Thank You
