### ISSUE TITLE
Intel(R) Xeon(R) CPU E3-1240 wrong Hashrate

### ISSUE THREAD

**Issue by Zelecktor** [xmrig/xmrig#307]
As the title. Im running this procesor on linux debian 8.
I tried to run it with many confugurations to have the best hashrate (when i know that this processor working full full, makes abour 300-350h/s but im getting about 10-15h/s.)

This is the running messaje:

root@mininguser:~/xmrig/build# sudo ./xmrig -a cryptonight -o stratum+tcp://pool.supportxmr.com:3333 -u 4956NVBAzkGA8imVZzLYe7f65xG8HXiERGbbMEHqiqfqdyDFdjwqXVv8U1MHbiki6jjMzMUykNmYQLNUvEbkTJDU9miq5qb -p opk01 -t 8 --av=1 -r 5 --cpu-affinity 0xFF --cpu-priority 5 --max-cpu-usage=80

 * VERSIONS:     XMRig/2.4.3 libuv/1.9.1 gcc/4.9.2
 * HUGE PAGES:   available, disabled
 * CPU:          Intel(R) Xeon(R) CPU E3-1240 V2 @ 3.40GHz (1) x64 AES-NI
 * CPU L2/L3:    1.0 MB/8.0 MB
 * THREADS:      8, cryptonight, av=1, donate=5%, affinity=0xFF
 * POOL #1:      pool.supportxmr.com:3333
 * COMMANDS:     hashrate, pause, resume
[2018-01-01 03:32:35] use pool pool.supportxmr.com:3333 107.178.104.10
[2018-01-01 03:32:35] new job from pool.supportxmr.com:3333 diff 1000
[2018-01-01 03:32:39] speed 2.5s/60s/15m n/a 13.5 n/a H/s max: n/a H/s

Also tried with 2 threats and cpu affinity with 0x5
4 threats and cpu affinity with 0x55
but same results, no more than 10-15H/s

Please help me with the config please!

**Comment by btx3** [comment]
Reduce the threads to 4 (for best performance cryptonight needs 2MB of L3 per core). It also says huge pages are disabled. Enable them by running `sysctl -w "vm.nr_hugepages=128"`.

This command should work just fine:
`./xmrig -a cryptonight -o stratum+tcp://pool.supportxmr.com:3333 -u 4956NVBAzkGA8imVZzLYe7f65xG8HXiERGbbMEHqiqfqdyDFdjwqXVv8U1MHbiki6jjMzMUykNmYQLNUvEbkTJDU9miq5qb -p opk01 --max-cpu-usage=100`

**Comment by Zelecktor** [comment]
Thanks for your answer!
got a problem:

root@mininguser:~/xmrig/build# sysctl -w "vm.nr_hugepages=128"
sysctl: permission denied on key 'vm.nr_hugepages'

and no matter i dont put the affinity or use 4 threads, the result is the same.

**Comment by btx3** [comment]
> sysctl: permission denied on key 'vm.nr_hugepages'

Are you running in a (OpenVZ) VM or Docker container? If you are, you'll need to run that sysctl command on the host.

> and no matter i dont put the affinity or use 4 threads, the result is the same.

I think it might be a process in the background (mostly because of the hashrate being 'n/a'). Try running `top` and `kill`ing the process.

**Comment by Zelecktor** [comment]
Its a dedicated, but yes, its the same config of a OpenVZ. I used to host game servers there but still have the contract for about 7 month, why not use to mine some monero hahaha

No process in background, already check it, also reboot it many times.

**Comment by rtau** [comment]
For those `sysctl -w` commands, they would usually requires running with sudo.

**Comment by Zelecktor** [comment]
> used with sudo su, and sudo but got the same result
i have to contact the support team to fix this issue
