### ISSUE TITLE
How to download the latest xmrig binary from github automatically

### ISSUE THREAD

**Issue by toxicroadkill** [xmrig/xmrig#3071]
not really a issue with xmrig, but with downloading it.

i run a rather large mining farm, and have the miners setup to update the os (debian) on a weekly basis, and do a reboot

is there a way to pull the latest binary xmrig from github

in the install script it does

wget https://github.com/xmrig/xmrig/releases/download/v6.17.0/xmrig-6.17.0-linux-static-x64.tar.gz

I would just like to pull the most recent binary without having to change the filename all the time, and then incorporate this into the update script that runs weekly..

wget https://github.com/xmrig/xmrig/releases/download/linux-static-x64.tar.gz <-- something like this..specify which type of binary i want, and be able to just download the latest version without worrying about what the version number is?

is this possible with github?

**Comment by Spudz76** [comment]
```
wget -q https://github.com/$(wget -qO- https://github.com/xmrig/xmrig/releases/latest | grep -o /xmrig/xmrig/releases/download/v.*/xmrig-.*-linux-static-x64.tar.gz)
```

**Comment by toxicroadkill** [comment]
wow, what a great answer, never thought of doing it that way

thank you very much

**Comment by JacksonChen666** [comment]
@toxicroadkill you may close this issue now (and also rename the issue to "How to download the latest xmrig binary from github automatically" for accuracy reasons, just a suggestion)
