### ISSUE TITLE
Complie Error: operand type mismatch for `vaesenc'

### ISSUE THREAD

**Issue by evasive-stillness** [xmrig/xmrig#3081]
When compiling xmrig using gcc 12.1, I'm getting this error:

```
…
[ 91%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/rx/RxDataset.cpp.o
/tmp/ccm3BGFb.s: Assembler messages:
/tmp/ccm3BGFb.s:388: Error: operand type mismatch for `vaesenc'
…
/tmp/ccm3BGFb.s:1269: Error: operand type mismatch for `vaesenc'
make[2]: *** [CMakeFiles/xmrig.dir/src/crypto/cn/CryptoNight_x86_vaes.cpp.o] Error 1
…
```

I've tried gcc 10.2 as well, but same result.

OS: RHEL Server 7.9 (Maipo)
Kernel: Linux 3.10.0-1160.66.1.el7.x86_64
cmake: 3.18.4
gcc: 12.1.0
libtool: 2.4.6

I'm using the advanced build instructions found [here](https://xmrig.com/docs/miner/build/centos7). I've build this on other systems successfully, but it's just not compiling on this one system for some reason.

**Comment by SChernykh** [comment]
I've tested compilation with GCC 12 on Windows (MSYS2) and Ubuntu 22 and it works fine. It looks like you have incompatible `gas` (GNU Assembler) version which doesn't support VAES instructions properly.

**Comment by evasive-stillness** [comment]
That was it! Using the latest version of [binutils](https://www.gnu.org/software/binutils/) (2.38) solved the problem. I was using 2.27.

Thank you!
