### ISSUE TITLE
System crashes after running xmrig

### ISSUE THREAD

**Issue by AsBenDoge** [xmrig/xmrig#3085]
Logs me out of my system and kills all my processes.
![error](https://user-images.githubusercontent.com/108665518/178128458-2499bd46-c066-4f99-b2ae-b4945a0acd34.png)
OS: Fedora Linux 36 | GNOME 42.2
xmrig 6.18.0 with 1gb-pages enabled
CPU: Intel 9400f

**Comment by Spudz76** [comment]
Nouveau is trash, use nvidia proprietary driver and it will probably not crash.

(this isn't strictly related to xmrig, everything in the crash says nouveau)

**Comment by AsBenDoge** [comment]
You’re right. Installing the nvidia driver solved this. Thank you.
