### ISSUE TITLE
Working Linux Portable binary! 

### ISSUE THREAD

**Issue by davidtavarez** [xmrig/xmrig#309]
Hi! I just create a linux portable binary using Open Build Service to generate AppImages. You can download it here: [https://download.opensuse.org/repositories/home:/davidtavarez:/branches:/OBS:/AppImage:/Templates/AppImage/](https://download.opensuse.org/repositories/home:/davidtavarez:/branches:/OBS:/AppImage:/Templates/AppImage/) download the file `xmrig-latest-x86_64.AppImage`.

This is how you can run it.

![xmrigrunning](https://user-images.githubusercontent.com/337107/34470052-f398506e-eeff-11e7-9e5a-d710810d72a5.png)

You can see the commits https://github.com/davidtavarez/xmrig/commits/master (I guess I did wrong committing on master). Should I open a Pull Request?

**Comment by davidtavarez** [comment]
I will place the apps here https://github.com/davidtavarez/portable-monero-miners

**Comment by adem4ik** [comment]
btw it seems like "HUGE PAGES" is disabled on your Linux, you can enable it as described in xmr-stack-cpu config.txt (https://github.com/fireice-uk/xmr-stak-cpu/blob/master/config.txt):
`On Linux you will need to configure large page support "sudo sysctl -w vm.nr_hugepages=128" and increase your ulimit -l. To do do this you need to add following lines to /etc/security/limits.conf - "* soft memlock 262144"  and "* hard memlock 262144". You can also do it Windows-style and simply run-as-root, but this is NOT recommended for security reasons.`

**Comment by kronoscrasher** [comment]
It's not portable, it still needs GLIBC...

**Comment by davidtavarez** [comment]
@kronoscrasher yep, that's true... it's not recommended to static linking of glibc but I will try to make some test, stay tuned!

**Comment by probonopd** [comment]
> It's not portable, it still needs GLIBC...

Most AppImages assume certain basic libraries (such as glibc) to be present on each target system. As long as the AppImage was compiled on a system no newer than all target systems, this should not be an issue though.

**Comment by knorhaan** [comment]
Here's another binary of xmrig I've built that seems to run fine cross-distro if anyone wants to give it a shot.
    wget https://github.com/knorhaan/xmr-standalone/raw/master/xmrig

**Comment by sthitajena** [comment]
@knorhaan Dude, i don't know how but working fine. Thanks a ton, i was searching like anything for this. Can you publish source code or binary ?

**Comment by knorhaan** [comment]
@sthitajena Anytime! Though I don't think I understand your question, I published a binary built with the code of the repository we're commenting on right now.

**Comment by z3dm4n** [comment]
@knorhaan Could you please provide your build instructions i.e. cmake command line?

**Comment by knorhaan** [comment]
configure libmicrohttpd statically, then run cmake with 
`-DMHD_INCLUDE_DIR=[PATH TO LMHTTPD]/src/include -DMHD_LIBRARY=/[PATH TO LMHTTPD]/src/microhttpd/.libs/libmicrohttpd.a`

**Comment by knorhaan** [comment]
@gjumic now what would you need that for?

**Comment by gjumic** [comment]
@knorhaan 
Uff I just realised how this is sounding. I have personal project to test hash rate of dozen different kind of pc and cpu and i just wanted to make it quicker.... And now im realizing that i can do it as quick with json config.

**Comment by knorhaan** [comment]
Well alright then ;)

Normally the program gets its command line options through the `argv` (argument vector) variable, with the length in the `argc` (argument count) variable, so if we want to hardcode those we need to construct our own. `argv` is an array of char pointers, with the last element a `NULL`, and in this case we need it to land in the call to `getopt_long` in `Options.cpp`.

Our `argv` will look like this:

`    char *harcoded_argv[] = {"./xmrig", "-o",    "[POOL ADDRESS]", "-u",    "[MONERO WALLET]","-p",    "x",    NULL};`

And we can calculate `argc` with this:

`    int harcoded_argc= sizeof(argv2) / sizeof(char*) - 1;`

So before compilation, our `Options.cpp` from line 233 onward would look like this:

`    m_pools.push_back(new Url());

    int key;
    char *harcoded_argv[] = {"./xmrig", "-o",    "[POOL ADDRESS]", "-u",    "[MONERO WALLET]","-p",    "x",    NULL};
    int harcoded_argc = sizeof(argv2) / sizeof(char*) - 1;

    for(int i = 0; i < argc2; ++i){
        fprintf(stderr, argv2[i]);
    }
    while (1) {
        key = getopt_long(harcoded_argc, hardcoded_argv, short_options, options, NULL);
        if (key < 0) {
            break;
        }

        if (!parseArg(key, optarg)) {
            return;
        }
    }`

**Comment by xxoxx** [comment]
@knorhaan  Your file include this
us-backup.supportxmr.com
444bLxV4jojdhJMJHNadHjVsn5pM5EWo499zLZ2tUqcoExFBmDRBmQHTDKdtb82uw

**Comment by knorhaan** [comment]
@xxoxx that is correct, other than the address I have not changed the donation mechanism, the percentage stays the same. If you think this is impolite, I will upload a version without it. The xmrig dev removed the linux portable binary release, once he includes it in his releases there will be no need for my binary. 

If anyone prefers building their own portable binary, simply copy/paste the following inside an Alpine container (thanks untoreh)

	#!/bin/sh

	cd /
	jobs=$(cat /proc/cpuinfo | grep -i "cpu cores" | wc -l)
	apk add alpine-sdk cmake libuv-dev
	wget https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-latest.tar.gz
	tar xf libmicrohttpd-latest.tar.gz
	cd libmicrohttpd-*
	./configure --enable-static --disable-shared
	make -j $jobs install
	cd /
	git clone --depth=1 https://github.com/xmrig/xmrig
	mkdir xmrig/build && cd xmrig/build || exit 1
	mhdpath=$(ls -d /libmicrohttpd-*/)
	sed '/add_executable/iset(CMAKE_EXE_LINKER_FLAGS " -static")' -i ../CMakeLists.txt
	cmake .. -DMHD_INCLUDE_DIR=${mhdpath}/src/include -DMHD_LIBRARY=/${mhdpath}/src/microhttpd/.libs/libmicrohttpd.a
	make -j $jobs

Happy mining! :)

**Comment by xxoxx** [comment]
@knorhaan Thanks.

**Comment by AkKrock** [comment]
Hi, thanks for work.
Great job btw. If you improve  more, it will be age-changing (like mobile mining).

I suggest to make following additions:
- allow HugePages like previously mentioned.
- Add some controls addition to resume, pause and hashrate, like: results, cpu details etc.
- It'd be great to have control on CPU threads but i think it will be asking too much from a mobile miner.

Best luck!

**Comment by gjumic** [comment]
Would love update of this for new coin algos.

**Comment by sergzhukov** [comment]
Hei, is there anybody going to place new monero7 algo miner binary there? :)
Having trouble with compiling  xmr-stak and other new miners on CentOS7 with cmake, is there a binary for some monero7 miner?

**Comment by brandsalazar** [comment]
@sergzhukov I've made a standalone binary for the new algo, you can get it at https://github.com/brandsalazar/xmrig 
It is made with the compile instructions from [issue 238] (https://github.com/xmrig/xmrig/issues/238)

**Comment by GloriousYellow** [comment]
@davidtavarez There are many reports of Minergate being a scam. I would encourage you to switch to a more reputable pool.

Source: https://www.reddit.com/r/Monero/wiki/avoid

**Comment by mlove19** [comment]
https://github.com/mlove19/xmrig

**Comment by mlove19** [comment]
https://github.com/mlove19/xmrig

**Comment by hashyg0d** [comment]
Can this run on Big Endian arch?
