### ISSUE TITLE
After panthera benchmark it said Segmentation fault

### ISSUE THREAD

**Issue by wcw1qqw** [xmrig/xmrig#3090]
im running xmrig on arm
how to disable the panthera
thanks
![Screenshot_20220720_190420](https://user-images.githubusercontent.com/109303568/179967138-d61b07d5-a962-4ee7-98a9-5258edf0d4a4.jpg)

**Comment by SChernykh** [comment]
XMRig doesn't support `panthera` algorithm. This is MoneroOcean version, aks on their github.
