### ISSUE TITLE
Operation error 

### ISSUE THREAD

**Issue by Keegz420mine** [xmrig/xmrig#3097]
**Describe the bug**
Just keep getting connection error operation canceled 
**To Reproduce**
I’ve been trying different pools and everything . Did research and says it’s something to do not responding within 20 seconds and it’s network if things time out with a support. 5555 link that shows “mining pool” and worked for me but not the rig . 

**Expected behavior**
I’ve done this on a MacBook and a shitty windows tablet as well as a work pc and worked fine but after building a good pc it pops up 

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: [e.g. Windows]
 - For GPU related issues: information about GPUs and driver version.

**Additional context**

**Comment by SChernykh** [comment]
Try to generate config.json with https://xmrig.com/wizard and if it doesn't work, show the full config that you used.

**Comment by Keegz420mine** [comment]
Okay I will send it over when I’m home later today . But I do generate the config.json on the wizard no issues then delete the old one and drag and drop my new one in the same folder like I’ve always done . Is it I need to download the wallet ?never had to before maybe with the new update ? But will send the config.json when I’m home

**Comment by SChernykh** [comment]
You don't need to have a wallet on the PC you use for mining. I need to see your config.json to check for common issues like trying to connect to TLS port without TLS enabled in config.

**Comment by Keegz420mine** [comment]
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "colors": true,
    "title": true,
    "randomx": {
        "init": -1,
        "init-avx2": -1,
        "mode": "auto",
        "1gb-pages": false,
        "rdmsr": true,
        "wrmsr": true,
        "cache_qos": false,
        "numa": true,
        "scratchpad_prefetch_mode": 1
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "huge-pages-jit": false,
        "hw-aes": null,
        "priority": null,
        "memory-pool": false,
        "yield": true,
        "asm": true,
        "argon2-impl": null,
        "argon2": [0, 1, 2, 3, 4, 5],
        "cn": [
            [1, 0],
            [1, 1],
            [1, 2],
            [1, 3],
            [1, 4]
        ],
        "cn-heavy": [
            [1, 0],
            [1, 1]
        ],
        "cn-lite": [
            [1, 0],
            [1, 1],
            [1, 2],
            [1, 3],
            [1, 4],
            [1, 5]
        ],
        "cn-pico": [
            [2, 0],
            [2, 1],
            [2, 2],
            [2, 3],
            [2, 4],
            [2, 5]
        ],
        "cn/upx2": [
            [2, 0],
            [2, 1],
            [2, 2],
            [2, 3],
            [2, 4],
            [2, 5]
        ],
        "ghostrider": [
            [8, 0],
            [8, 1],
            [8, 2],
            [8, 3],
            [8, 4]
        ],
        "rx": [0, 1, 2, 3, 4],
        "rx/wow": [0, 1, 2, 3, 4, 5],
        "cn-lite/0": false,
        "cn/0": false,
        "rx/arq": "rx/wow",
        "rx/keva": "rx/wow"
    },
    "opencl": {
        "enabled": false,
        "cache": true,
        "loader": null,
        "platform": "AMD",
        "adl": true
    },
    "cuda": {
        "enabled": false,
        "loader": null,
        "nvml": true
    },
    "log-file": null,
    "donate-level": 1,
    "donate-over-proxy": 1,
    "pools": [
        {
            "algo": null,
            "coin": "XMR",
            "url": "xmr-eu1.nanopool.org:14433",
            "user": "",
            "pass": null,
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "enabled": true,
            "tls": true,
            "tls-fingerprint": null,
            "daemon": false,
            "socks5": null,
            "self-select": null,
            "submit-to-origin": false
        }
    ],
    "retries": 5,
    "retry-pause": 5,
    "print-time": 60,
    "health-print-time": 60,
    "dmi": true,
    "syslog": false,
    "tls": {
        "enabled": false,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "dns": {
        "ipv6": false,
        "ttl": 30
    },
    "user-agent": null,
    "verbose": 0,
    "watch": true,
    "pause-on-battery": false,
    "pause-on-active": false
}

**Comment by Keegz420mine** [comment]
took my wallet address out

**Comment by Spudz76** [comment]
`pools->"tls": true,`

is your problem.  nanopool does not offer SSL on any ports

**Comment by SChernykh** [comment]
This config works fine for me, so your problem is somewhere else. Maybe your ISP or antivirus block the connection. @Spudz76 nanopool offers TLS on port 14433.

**Comment by Keegz420mine** [comment]
Think maybe a vpn would work ?

**Comment by Keegz420mine** [comment]
Which pool do you use @Spudz76 ?

**Comment by Keegz420mine** [comment]
Don't have antivirus just windows defender and recently did an update maybe it's that as I mentioned earlier I used my Mac to mine on the same network via Wi-Fi

**Comment by Spudz76** [comment]
@Keegz420mine MoneroOcean since most of my hardware sucks at RandomX

**Comment by Keegz420mine** [comment]
How did you set up the config?

**Comment by Keegz420mine** [comment]
Sorry I'm pretty noob at this 😂

**Comment by Keegz420mine** [comment]
VPN has got it working good . For now 😂 thank you for your help !

**Comment by Spudz76** [comment]
I just edit the [default config.json](https://raw.githubusercontent.com/xmrig/xmrig/master/src/config.json) since I can speak JSON in my sleep, and am familiar completely with all the options and how to set them.

**Comment by Keegz420mine** [comment]
Hahaha I see ... I have 3 rigs at the moment and I'm struggling to add workers ....

**Comment by Keegz420mine** [comment]
If I'm using the wizard do I add worker iD ar the end of my wallet address ?

**Comment by Spudz76** [comment]
Pools have their own ways of rig-id, the `rig-id` option under `pools` in config.json is technically a protocol extension and some pools don't support (ignore) that, then they use the "old" method of adding it after a dot/colon/etc on the wallet (`user`) field.  Others take it as part of the otherwise mostly unused `pass` field.

It's entirely up to the pool how they choose to do it, what field they parse it from or what separator character they use; check pool FAQ.

`worker-id` under the `api` section is unrelated and is only used for identification within the API responses (if API is enabled) and has nothing to do with the pool or mining in general (only monitoring/data collection).

**Comment by Keegz420mine** [comment]
Ooohh okay yea I'm using xmr pool.eu now after you said Nanopool sucks haha which yea I can see this pool is much better . I tried to adjust worker is on the config and ruined it all has to redo the whole lot but oh well if I can't get it that's okay I'll just have to monitor it individually

**Comment by Spudz76** [comment]
Their "Getting Started" page has all the details of how to encode the rig-id into the `user` field

```
Mining to a Monero wallet with worker id called my_rig1 (+ sign):
  YOUR_XMR_WALLET_ADDRESS+my_rig1
```

**Comment by Keegz420mine** [comment]
Thank you so much ! Going to config this all now .... I just need to open my eyes and I'll see what I'm looking for 😂😂 but an extra set always is a good idea sometimes 😂😂
