### ISSUE TITLE
Avast prevents installation - Trojan alert

### ISSUE THREAD

**Issue by namik-mesic** [xmrig/xmrig#310]
Can't download because Avast detects a Trojan. Anyone else had the issue?

**Comment by Mila432** [comment]
yes dis bad trojan will steal your data \s

**Comment by btx3** [comment]
Probably because of botnets. Try to disable whatever "Real-time protection" Avast has (don't use it, don't know), download it and whitelist the file/folder.

**Comment by namik-mesic** [comment]
It's something worth noting and perhaps investigating / mentioning in docs :P
Thanks
