### ISSUE TITLE
Solo mining to daemon with cn-heavy/xhv gives job error: "Invalid block template received from daemon.

### ISSUE THREAD

**Issue by downystreet** [xmrig/xmrig#3107]
xmrig version. 6.18.0
Mining algo: cn-heavy/xhv
url: 127.0.0.1:17750
daemon: true

When trying to solo mine xhv/haven with the daemon using these settings I get the error job error: "Invalid block template received from daemon. When I mine using a pool I don't run into this issue and the miner works normally. Only when trying to solo mine do I get this error.

**Comment by SChernykh** [comment]
Solo mining is only supported for Monero and Wownero.

**Comment by downystreet** [comment]
Alright, thanks.
