### ISSUE TITLE
Raspberry Pi 4B not able to run the miner

### ISSUE THREAD

**Issue by GYKgamer** [xmrig/xmrig#3111]
**Describe the bug**
The miner fails to start threads, and throws a segmentation error

**To Reproduce**
Install xmrig to raspberry pi 4b 64 bit, set it up, then run the command "xmrig"

**Expected behavior**
The miner is supposed to start

**Required data**
 - ![image](https://user-images.githubusercontent.com/41442793/187068293-34dce8fd-e92b-4577-b712-ddc9c1ff1e92.png)
 - [xmrig.zip](https://github.com/xmrig/xmrig/files/9439487/xmrig.zip)
 - OS: Raspberry Pi 4B

**Comment by Spudz76** [comment]
As you were told in the other thread, this should be posted to https://github.com/MoneroOcean/xmrig/issues

**Comment by GYKgamer** [comment]
Oh sorry, I tried searching but didn't find that reparatory.
