### ISSUE TITLE
大佬们这是什么情况？

### ISSUE THREAD

**Issue by liusainan** [xmrig/xmrig#3115]
![image](https://user-images.githubusercontent.com/94607385/190121990-ea4f2ab2-1ea7-415d-9974-b34b5ad81c1e.png)
![image](https://user-images.githubusercontent.com/94607385/190122098-6bd82862-918c-40b5-b7bc-4ced7e5587f2.png)

**Comment by Spudz76** [comment]
主机在路由或防火墙中列入黑名单

使用安全隧道
