### ISSUE TITLE
PowerPC CPU (PPC) Support

### ISSUE THREAD

**Issue by KaiUL** [xmrig/xmrig#312]
Hi can you and would you please add PowerPC CPU to the list of architectures that this binary supports.
From my understanding PPC CPU's are very good at math and therefore in theory would handle the cryptonight algorithm nicely.

Thanks and have a great day!

**Comment by xmrig** [comment]
You can check this fork for another miner https://www.reddit.com/r/MoneroMining/comments/79wna4/xmrstakpower_port_of_xmrstakcpu_to_power8_little/

For me, hard to add PowerPC support, no hardware available and hashrate/price looks very bad.
Thank you.

**Comment by KaiUL** [comment]
Thanks for the link! I was having no luck finding a Miner for PPC CPU's thanks! Also I know I probably will not be able to really get anywhere with the machines I have it's kinda a for fun thing, partially because my two PPC computers are a iMac G4 and a Nintendo Wii

**Comment by mukesh-610** [comment]
Sorry to respond on a closed issue, but the fork you linked is only good until cn/r. Can you please, please port the current RandomX version to PPC64le? I would really appreciate it.
