### ISSUE TITLE
Neox Invalid address

### ISSUE THREAD

**Issue by dawidmosk** [xmrig/xmrig#3123]
After compile and run I'm getting error:

`[2022-09-18 00:24:21.089]  net      neox.2miners.com:4040 Invalid address`

but when I set xmr it's working?
Any ideas?

**Comment by Spudz76** [comment]
Neoxa appears to use kawpow for its PoW piece.  Set algorithm to `kawpow` and that's only available with a GPU.

**Comment by dawidmosk** [comment]
Not working. I did try to command line and json file. I did tried without coin, only algo, only ip.
Changed to xmr. address and working. 
```

   "pools": [
        {
            "algo": "kawpow",
            "coin": "",
            "url": "162.19.139.119:4040",
            "user": "neoxa:GTJB7yi6rVARh98KH3HMxFEXX5CYWUpuXL",
            "pass": "x",

```

Now i changed to ssl port with disabled option and working. Thank You.
