### ISSUE TITLE
How to stop my xmrig from running on VM (there's no VM on my PC)?

### ISSUE THREAD

**Issue by Jeswin-123** [xmrig/xmrig#3135]

**Comment by Spudz76** [comment]
Windows uses VM mode as a safety sandbox, shut that junk off.

https://github.com/xmrig/xmrig/issues/1891#issuecomment-776180629

**Comment by Spudz76** [comment]
It says how, in the post I linked to?

**Comment by Jeswin-123** [comment]
Oh yeah I found it thanks :))
But it still shows the error failed to apply mod msr, is there any way to fix it too??  I thought it might be coz of the VM, but I guess there's more to it

**Comment by mkhuber1** [comment]
config.json
Under RandomX

        "rdmsr": false,
        "wrmsr": false,

**Comment by Spudz76** [comment]
that only gets rid of the message by disabling the whole thing

run as Administrator...

**Comment by Jeswin-123** [comment]
I am running it as admin, even turned it on through properties > compatibility. But to still not working!

**Comment by Jeswin-123** [comment]
Done everything, but the msr error still persists......Btw is it worth mining on my Celeron N4020 processor?

**Comment by SChernykh** [comment]
Did you try to disable Secure Boot and all other virtualization settings in BIOS? But it will probably not work for you because all benchmarks of this CPU have MSR disabled for some reason https://xmrig.com/benchmark?cpu=Intel%28R%29+Celeron%28R%29+N4020+CPU+%40+1.10GHz

**Comment by Jeswin-123** [comment]
Yeah I did disable all visualisation settings. Ohh is it that's too bad anyways :(

**Comment by Spudz76** [comment]
Celerons don't have the MSRs so disable it to get rid of the message

**Comment by Jeswin-123** [comment]
Ohhh yeah I've done that, the issue is fixed now. Thanks everyone for the valuable inputs :)
