### ISSUE TITLE
How to build a full static executable on MacOS ?

### ISSUE THREAD

**Issue by FSOL06** [xmrig/xmrig#3136]
My goal is to compile XMRIG for ild intel Macs built between 2007 and 2011. I'm running on MacOS 10.5 last release. 

I succeeded - partially - to do it by following the advanced tutorial on the page https://xmrig.com/docs/miner/build/macos

Thanks for that ! 

However, I have a problem. The executable only works on the Mac where the executable was compiled. I get error messages for missing dependencies :

![image](https://user-images.githubusercontent.com/97795464/195136621-85cfdd77-a4e3-4cc4-979b-50fb454d737a.png)

I don't want to install brew & hwloc lib by hand. So I try to build an executable with all the used libraries in static. 

I found an option for CMAKE in the documentation :

![image](https://user-images.githubusercontent.com/97795464/195137068-9277e057-53eb-4d3d-a742-bdd6a5e644a6.png)

Unfortunately, if I use it, it generates a bug at compile time :

![image](https://user-images.githubusercontent.com/97795464/195137765-0b489e25-9706-4804-a792-c902bf7bffbf.png)

How to build a full static executable on MacOS ?

 Thanks for your help.

**Comment by Spudz76** [comment]
Try `scripts/build_deps.sh` to build the exact appropriate versions of the deps, rather than using whatever brew provides (may be incompatible deps versions).

**Comment by FSOL06** [comment]
Where / when I should execute this command ? 

```
1. brew install cmake wget automake libtool autoconf
2. git clone https://github.com/xmrig/xmrig.git
3. mkdir xmrig/build && cd xmrig/scripts
4. ./build.hwloc.sh && cd ../build
5. cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DHWLOC_INCLUDE_DIR=../scripts/deps/include -DHWLOC_LIBRARY=../scripts/deps/lib/libhwloc.a
6. make -j$(sysctl -n hw.logicalcpu)

```
Between which command or instead of which command ?

**Comment by FSOL06** [comment]
I change line 4 by this : 

`4. ./build_deps.sh && cd ../build
`
This is the result : 

![image](https://user-images.githubusercontent.com/97795464/195172734-28c94e39-5685-4bff-b9b6-4ae0e74d3413.png)

**Comment by Spudz76** [comment]
Replace also line 5:

`cmake .. -DXMRIG_DEPS=../scripts/deps`

You can validate the needed dynamic libs with otool once the binary is built:
```
users-iMac-Pro:macos user$ otool -L ./xmrig
./xmrig:
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
        /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 822.37.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1455.255.0)
```

None of those framework libs can be made static, thanks to Apple.  But none of the other things are there, so it's "semi-static" which might be enough portability for your purposes.

**Comment by FSOL06** [comment]
![image](https://user-images.githubusercontent.com/97795464/195435286-47b6a2aa-01fd-4a22-bbd6-cc1b21c851bf.png)

May be I need -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl

**Comment by FSOL06** [comment]
![image](https://user-images.githubusercontent.com/97795464/195441138-a55913e5-432c-4f6f-84e6-471f558e8435.png)

Same :/ Don't know what to do...

**Comment by Spudz76** [comment]
Nope, using the `-DOPENSSL_ROOT_DIR` will definitely block the ability for it to automatically locate the one in `../scripts/deps`.  Use exactly the command I said with just the `XMRIG_DEPS` set to where it should look first.  If that doesn't work you could try `-DCMAKE_PREFIX_PATH=../scripts/deps` which forces it even harder.

Also you must clear the entire build dir (most importantly `CMakeCache.txt`) between new cmake commands, or else it will ignore most newly provided options (because the "old" locations for libs are already set in cache -- see how it still found the brew/system versions of libuv and hwloc...) but that is just how CMake works (cache almost always wins over newly introduced options).

I tested this on a HighSierra VM but I doubt it broke just because of newer OSX.  I don't have any real Apples and HighSierra is the last one that really works on a VM on non-Apple hardware for free.

**Comment by Spudz76** [comment]
Okay I tried it that way on my VM and it also didn't work.

Use:
```
cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../scripts/deps
```

No idea why the relative path doesn't work, it works on every other platform.

Also my shell is bash (installed with brew) this might not work in the default shell.  In such case just put the whole path like:
```
cmake ,. -DCMAKE_PREFIX_PATH=/Users/fsol/xmrig/scripts/deps
```

Then it works.

**Comment by FSOL06** [comment]
![image](https://user-images.githubusercontent.com/97795464/195716108-f961f5aa-1f88-407f-90ba-6a4af5e5a9ec.png)

Make do it's work :) And here is the result with otool : 

![image](https://user-images.githubusercontent.com/97795464/195716738-bb8b2f80-dd15-469c-8ce6-d3f4836442f7.png)

Thanks a lot for your precious help ! I'll try tomorrow on other mac and I'll close this issue if it'll work.

**Comment by Spudz76** [comment]
Looks right!  Should work.

**Comment by FSOL06** [comment]
Thanks again for your help. 

For your information, I compile on MacBookPro mid-2011 running under Mac OS 10.15.7

This is the result on iMac mid-2007 running on Mac OS X 10.11.6 :

![image](https://user-images.githubusercontent.com/97795464/195779721-aa97092c-2f46-4da0-a92c-4680677ea4ec.png)

This is the result on MacMini mid-2010 running on Mac OS X 10.13.6 :  

![image](https://user-images.githubusercontent.com/97795464/195781361-400a00c3-a36e-4fed-98fa-d0c489be7bb5.png)

What's your opinion ? 

Since the build was done on Mac OS 10.15.7, does that mean that earlier versions of MacOS are excluded? 

The compiled version of XMRIG 6.18 stock is a mystery to me, it works perfectly on all my macs.

**Comment by Spudz76** [comment]
I think compiling in one of the older (preferably oldest) OSX releases will avoid that symbol (new in 10.15) and it will still work on newer ones then.  The release binary is probably built on HighSierra (10.13) in a VM, similar to my test environment.

**Comment by FSOL06** [comment]
Ok. Thanks. 

Last question: 

Is there any method to build executable for M1 (ARM) on an intel CPU ? I don't thinks so, but...

**Comment by Spudz76** [comment]
Supported by Apple (the compiler in more recent XCode can target M1) but the xmrig CMake setup is not designed for cross-compiling.  I will see if it's fairly trivial to add, if the newer XCode still works on 10.13

**Comment by FSOL06** [comment]
Thanks a lot !

**Comment by FSOL06** [comment]
I try to build executable on MacBook Pro mid-2009 running on Mac OS 10.11.6. Last step crash.

![Sans titre](https://user-images.githubusercontent.com/97795464/195953918-596dc33d-47d2-474a-8099-0c8537d9c548.png)

Here is all commands I've wrote since the beginning : 

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install cmake wget automake libtool autoconf
git clone --branch xdag https://github.com/swordlet/xmrig.git
mkdir xmrig/build && cd xmrig/scripts
./build_deps.sh && cd ../build
cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../scripts/deps
make -j$(sysctl -n hw.logicalcpu)

```

**Comment by FSOL06** [comment]
I try to build executable on MacBook Pro mid-2009 running on Mac OS 10.11.6. Last step crash.

![Sans titre](https://user-images.githubusercontent.com/97795464/195953918-596dc33d-47d2-474a-8099-0c8537d9c548.png)

Here is all commands I've wrote since the beginning : 

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install cmake wget automake libtool autoconf
git clone --branch xdag https://github.com/swordlet/xmrig.git
mkdir xmrig/build && cd xmrig/scripts
./build_deps.sh && cd ../build
cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../scripts/deps
make -j$(sysctl -n hw.logicalcpu)

```

**Comment by FSOL06** [comment]
I try to build executable on MacBook Pro mid-2009 running on Mac OS 10.11.6. Last step crash.

![Sans titre](https://user-images.githubusercontent.com/97795464/195953918-596dc33d-47d2-474a-8099-0c8537d9c548.png)

Here is all commands I've wrote since the beginning : 

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install cmake wget automake libtool autoconf
git clone --branch xdag https://github.com/swordlet/xmrig.git
mkdir xmrig/build && cd xmrig/scripts
./build_deps.sh && cd ../build
cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../scripts/deps
make -j$(sysctl -n hw.logicalcpu)

```

**Comment by Spudz76** [comment]
Looks like the AMD Zen code is not currently able to be disabled, but could be.

You could maybe succeed for now with `-DWITH_CN_FEMTO=OFF` since that would not include any "UPX2" code, if you aren't going to be using that algorithm anyway.  Then it won't try to compile that particular file anymore (might crash on some others).

Zen should be made more modular so that it can be completely shut off (such as on Apple-x86 which would never ever have an AMD in them anyway).  There is an option for part of the Zen support but it only shuts off the MSR piece and there is no "knob" to turn off the inclusion of kernels for them.  I might take a stab at making it selectable, looks like it shouldn't be too invasive (whether the patch is accepted into mainstream, who knows).

**Comment by Spudz76** [comment]
On some further digging it appears turning off CN-Femto won't actually skip this file, it only skips calling it.  The compiler might then strip the non-referenced code in the link step later, but it will still try to compile it before throwing it away, so it will probably still crash the same with it off.

**Comment by Spudz76** [comment]
It could work with this fairly simple patch (will completely skip the offending file when `-DWITH_CN_FEMTO=OFF`)

[dont-include-upx-asm-when-femto-off.patch.txt](https://github.com/xmrig/xmrig/files/9790704/dont-include-upx-asm-when-femto-off.patch.txt)

**Comment by FSOL06** [comment]
Could you explain me how to use this patch ?

**Comment by Spudz76** [comment]
```
cd /Users/fsol/xmrig
cat dont-include-upx-asm-when-femto-off.patch.txt | patch -p1
```

**Comment by FSOL06** [comment]
Many many thanks ! 

I'll try this in few days.
