### ISSUE TITLE
No active pools, stop mining

### ISSUE THREAD

**Issue by davwheat** [xmrig/xmrig#314]
My GPU miner sometimes says no active pools, stop mining on startup, other times it says connection reset by peer, and sometimes it says nothing at all.

Also if I try to switch from cryptonight-lite to just cryptonight it gives me a CUDA error

It works fine when mining CPU, but not GPU.

GPU: https://puu.sh/yTlL3/93ca6fb92a.png
CPU: https://puu.sh/yTlP2/2578642ab8.png

**Comment by davidtavarez** [comment]
You need to check if your connection with the pool. Maybe is really slow.

**Comment by davwheat** [comment]
But how come it works on the CPU miner, but not the Nvidia GPU miner?
