### ISSUE TITLE
CLear Linux not building XMrig

### ISSUE THREAD

**Issue by agentpatience** [xmrig/xmrig#3150]
I know know where is best to ask but when I try to compile xmrig on Clear Linux I get:
[100%] Linking CXX executable xmrig
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/xmrig.dir/build.make:3854: xmrig] Error 1
make[1]: *** [CMakeFiles/Makefile2:182: CMakeFiles/xmrig.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by Spudz76** [comment]
Tried to make a VM to try it out, but since Clear Linux is a total bitch and I don't have `pclmulqdq` it won't even boot, so good luck with that.

**Comment by Spudz76** [comment]
Nevermind one of my hypervisors did have the silly required instructions, install is progressing now...

**Comment by Spudz76** [comment]
Double nevermind, it just hangs at "Extracting required packs".  Garbage distro gonna garbage.

**Comment by SChernykh** [comment]
> cannot find -lstdc++: No such file or directory

This is a standard C++ library and it should be available in any sane GCC installation. Something is wrong with your distro.

**Comment by Spudz76** [comment]
I got the VM install to finish but now it just locks up trying `swupd bundle-add c-basic`

It appears `libstdcpp` is already installed (server edition).

Really can't help if the crap distro won't even run.  Use Ubuntu like normal.

**Comment by kl1059** [comment]
clear linux bills itself as an optimized intel distro 

they have preloaded CFLAGS and CXXFLAGS with all kinds of interesting foo

so i did this (in addition to installing the dependencies)

export CFLAGS=""
export CXXFLAGS=""

mkdir build ; cd build ; cmake .. ; make

and got a good xmrig build

so the theory would be that there is a conflict between the optimizations that xmrig wants to do and the optimizations that clear linux has burdened everyone with by default.

**Comment by SChernykh** [comment]
Compiler flags do nothing because XMRig already uses its own ASM code for many algorithms.

**Comment by leagueofsoups** [comment]
Hello from 2025

For anyone who wants to experiment with calerlinux, to fix this error, just install the `c-basic-static` bundle, it contains /usr/lib64/libstdc++.a, this is not a .so, but a static library
