### ISSUE TITLE
Change algo donate

### ISSUE THREAD

**Issue by lioncrypter** [xmrig/xmrig#3153]
Is possible change dondete algo? 
for example mining xmr and donate GhostRider?

**Comment by xmrig** [comment]
No, donate try to use the same algorithm as currently mined to avoid unnecessary algorithm switching and possible side effects of it especially if algorithms are very different.
Thank you.

**Comment by lioncrypter** [comment]
> No, donate try to use the same algorithm as currently mined to avoid unnecessary algorithm switching and possible side effects of it especially if algorithms are very different. Thank you.

Then if i want donate ghostrider what i need change? or just mining and change donation wallet for your ghostrider wallet?
