### ISSUE TITLE
xmrig windows close connection

### ISSUE THREAD

**Issue by mubali1987** [xmrig/xmrig#3157]
**Describe the bug**
close connection
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: [e.g. Windows]
 - For GPU related issues: information about GPUs and driver version.

**Additional context**
xmrig windows close connection

**Comment by Spudz76** [comment]
Since you provided no information, let's guess it's that you've used a TLS pool port without enabling TLS, or the opposite you're using a non-TLS port with TLS enabled.  If not that then it could be firewall/antimalware thing blocking it.
