### ISSUE TITLE
Advanced build Install Problem

### ISSUE THREAD

**Issue by k7n2g** [xmrig/xmrig#3158]
[Spudz76]   Advanced build gives this  ERROR: cannot verify github.com's certificate, issued by ‘CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1,O=DigiCert Inc,C=US’:  tried it with --no-check-certificate  no luck
Tried ./build_deps.sh --no-check-certificate. not work.  is there another command  or is the workaround to download individually each package OpenSSL/hwloc/LibUV if so what versions do you recommend don't want to use system devel packages if possible

**Comment by Spudz76** [comment]
Those scripts unfortunately do not take options nor pass them through to the sub-scripts (`build_deps.sh` just calls the three other scripts, `build.uv.sh`/`build.hwloc.sh`/`build.openssl.sh`)

So to get the effect of that option you have to edit `scripts/build.uv.sh` and find the wget command and insert the `--no-check-certificate` there.

I have had to do so before when there were connection problems with the openssl source url.

Once you've edited the files the next `git pull` will complain, simply undo the changes with `git checkout scripts/build.*` and then it will pull clean (and if the cert is still broken put the option back in).

**Comment by Spudz76** [comment]
Also I don't have that error so perhaps your `ca-certificates` is out of date (Ubuntu? and older one?)

**Comment by k7n2g** [comment]
thanks guy I will work my way through that,

**Comment by k7n2g** [comment]
Thanks for that think i have sorted it out now it was my cert, my bad should have realized this may be the problem

**Comment by Spudz76** [comment]
That one is in `build.hwloc.sh` do the same sort of edit there

**Comment by Spudz76** [comment]
And you might as well do the `build.openssl.sh` one too, it'll probably fail since your `ca-certificates` package is very broken.

**Comment by QbitNetwork** [comment]
thanks spudz76 sorted now
