### ISSUE TITLE
./xmrig: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by ./xmrig

### ISSUE THREAD

**Issue by heavydee77** [xmrig/xmrig#3159]
this is the issue I am facing

./xmrig: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by ./xmrig

**Comment by SChernykh** [comment]
What binary are you running? xmrig from `xmrig-6.18.1-linux-static-x64.tar.gz` should work fine.

**Comment by heavydee77** [comment]
https://github.com/XDagger/xmrig2xdag/releases/download/v1.1.2/linux_proxy_v1.1.2+rig_no_fee_v6.18.0.zip

**Comment by SChernykh** [comment]
This is not an official release, ask whoever created it.

**Comment by FSOL06** [comment]
@heavydee77 You'll havee to compile this fork yourself : 

Same process as official XMRIG, except github sources: 

1. sudo apt-get install git build-essential cmake automake libtool autoconf
2. git clone --branch xdag https://github.com/swordlet/xmrig.git
3. mkdir xmrig/build && cd xmrig/scripts
4. ./build_deps.sh && cd ../build
5. cmake .. -DXMRIG_DEPS=scripts/deps
6. make -j$(nproc)
