### ISSUE TITLE
NOT AN ISSUE, just want to modify your awesome source code.

### ISSUE THREAD

**Issue by Gill1000** [xmrig/xmrig#316]
first,you are awesome man ,really appreciate your work, keep it up ,we will always support you.
second ,(the thing i want to modify) i want to give options like mining url, user name, password like this  all the options , in the source code before  compiling this code ....or in one line i mean to say>> double clicking the xmrig.exe and right-away it start mining on my given pool and others 
options..........i already tried couple of times but i fail.......i hope you understand me .
Thanks.

**Comment by btx3** [comment]
Search before asking. Either use a configuration file, or look at #92.

**Comment by Gill1000** [comment]
U

**Comment by Gill1000** [comment]
I accidently miss the #92  let me check that

**Comment by btx3** [comment]
The donate server is specified here: https://github.com/xmrig/xmrig/blob/49b45ddd18461558e80b3e7c0eb741409072fd78/src/net/strategies/DonateStrategy.cpp#L51

So just changing `fee.xmrig.com` to your pool and `443` to your port should work.

**Comment by Gill1000** [comment]
Tried lot of trial & error method to modify the donation address but still failed ,I guess only you @xmrig can guide us!!
Want to add nicehash account as an second donation url!!
Thanks

**Comment by xmrig** [comment]
About donation, duplicate #274
