### ISSUE TITLE
Xmrig can be run on aarch64?

### ISSUE THREAD

**Issue by thiangm** [xmrig/xmrig#3166]
I want to know if I can use these specs to use xmrig, if not in which algorithms can I use them for mining?
![image](https://user-images.githubusercontent.com/94427218/202899475-ba3ba4c6-8904-4654-8c6a-6a2cb9e04d1a.png)

**Comment by SChernykh** [comment]
Yes, you can compile XMRig on it and mine all algorithms.

**Comment by thiangm** [comment]
> 

Could you give me a reference to download, install and run Xmrig on aarch64, I am only familiar with x86_64

All run Xmrig, I get an error

**Comment by SChernykh** [comment]
You'll have to build it from source code yourself, instructions are here: https://xmrig.com/docs/miner/build

**Comment by ajunkdha** [comment]
This very easy , just need install gcc ++ and apt update && upgrade on you ubuntu/or linux 
And folow intruc install .  Xmrig suport all arm include arm8 and other
