### ISSUE TITLE
/home/dodo/xmrig/src/base/net/stratum/Pools.cpp:220:18: error: ‘kMinimumDonateLevel’ was not declared in this scope; did you mean ‘kDonateLevel’?

### ISSUE THREAD

**Issue by Acalann** [xmrig/xmrig#3169]
**Describe the bug**
Not building
**To Reproduce**
Build latest version of xmrig on ubuntu & set donation level to zero
**Expected behavior**
The build to complete
**Required data**
In file included from /home/dodo/xmrig/src/base/net/stratum/Pools.cpp:32:
/home/dodo/xmrig/src/donate.h:41:1: error: expected ‘,’ or ‘;’ before ‘constexpr’
   41 | constexpr const int kMinimumDonateLevel = 0
      | ^~~~~~~~~
/home/dodo/xmrig/src/base/net/stratum/Pools.cpp: In member function ‘int xmrig::Pools::donateLevel() const’:
/home/dodo/xmrig/src/base/net/stratum/Pools.cpp:76:55: error: invalid use of incomplete type ‘using element_type = class xmrig::BenchConfig’ {aka ‘class xmrig::BenchConfig’}
   76 |     return benchSize() || (m_benchmark && !m_benchmark->id().isEmpty()) ? 0 : m_donateLevel;
      |                                                       ^~
In file included from /home/dodo/xmrig/src/base/net/stratum/Pools.h:32,
                 from /home/dodo/xmrig/src/base/net/stratum/Pools.cpp:26:
/home/dodo/xmrig/src/base/net/stratum/Pool.h:37:7: note: forward declaration of ‘using element_type = class xmrig::BenchConfig’ {aka ‘class xmrig::BenchConfig’}
   37 | class BenchConfig;
      |       ^~~~~~~~~~~
/home/dodo/xmrig/src/base/net/stratum/Pools.cpp: In member function ‘void xmrig::Pools::load(const xmrig::IJsonReader&)’:
/home/dodo/xmrig/src/base/net/stratum/Pools.cpp:137:61: error: incomplete type ‘xmrig::BenchConfig’ used in nested name specifier
  137 |     m_benchmark = std::shared_ptr<BenchConfig>(BenchConfig::create(reader.getObject(BenchConfig::kBenchmark), reader.getBool("dmi", true)));
      |                                                             ^~~~~~
/home/dodo/xmrig/src/base/net/stratum/Pools.cpp:137:98: error: incomplete type ‘xmrig::BenchConfig’ used in nested name specifier
  137 |     m_benchmark = std::shared_ptr<BenchConfig>(BenchConfig::create(reader.getObject(BenchConfig::kBenchmark), reader.getBool("dmi", true)));
      |                                                                                                  ^~~~~~~~~~
/home/dodo/xmrig/src/base/net/stratum/Pools.cpp: In member function ‘uint32_t xmrig::Pools::benchSize() const’:
/home/dodo/xmrig/src/base/net/stratum/Pools.cpp:171:37: error: invalid use of incomplete type ‘using element_type = class xmrig::BenchConfig’ {aka ‘class xmrig::BenchConfig’}
  171 |     return m_benchmark ? m_benchmark->size() : 0;
      |                                     ^~
In file included from /home/dodo/xmrig/src/base/net/stratum/Pools.h:32,
                 from /home/dodo/xmrig/src/base/net/stratum/Pools.cpp:26:
/home/dodo/xmrig/src/base/net/stratum/Pool.h:37:7: note: forward declaration of ‘using element_type = class xmrig::BenchConfig’ {aka ‘class xmrig::BenchConfig’}
   37 | class BenchConfig;
      |       ^~~~~~~~~~~
/home/dodo/xmrig/src/base/net/stratum/Pools.cpp: In member function ‘void xmrig::Pools::toJSON(rapidjson::Value&, rapidjson::Document&) const’:
/home/dodo/xmrig/src/base/net/stratum/Pools.cpp:204:46: error: incomplete type ‘xmrig::BenchConfig’ used in nested name specifier
  204 |         out.AddMember(StringRef(BenchConfig::kBenchmark), m_benchmark->toJSON(doc), allocator);
      |                                              ^~~~~~~~~~
/home/dodo/xmrig/src/base/net/stratum/Pools.cpp:204:70: error: invalid use of incomplete type ‘using element_type = class xmrig::BenchConfig’ {aka ‘class xmrig::BenchConfig’}
  204 |         out.AddMember(StringRef(BenchConfig::kBenchmark), m_benchmark->toJSON(doc), allocator);
      |                                                                      ^~
In file included from /home/dodo/xmrig/src/base/net/stratum/Pools.h:32,
                 from /home/dodo/xmrig/src/base/net/stratum/Pools.cpp:26:
/home/dodo/xmrig/src/base/net/stratum/Pool.h:37:7: note: forward declaration of ‘using element_type = class xmrig::BenchConfig’ {aka ‘class xmrig::BenchConfig’}
   37 | class BenchConfig;
      |       ^~~~~~~~~~~
/home/dodo/xmrig/src/base/net/stratum/Pools.cpp: In member function ‘void xmrig::Pools::setDonateLevel(int)’:
/home/dodo/xmrig/src/base/net/stratum/Pools.cpp:220:18: error: ‘kMinimumDonateLevel’ was not declared in this scope; did you mean ‘kDonateLevel’?
  220 |     if (level >= kMinimumDonateLevel && level <= 99) {
      |                  ^~~~~~~~~~~~~~~~~~~
      |                  kDonateLevel
make[2]: *** [CMakeFiles/xmrig.dir/build.make:557: CMakeFiles/xmrig.dir/src/base/net/stratum/Pools.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:158: CMakeFiles/xmrig.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by Acalann** [comment]
It's a variable declaration issue?

**Comment by theaog** [comment]
are you aware that you're asking the developers that work hard on this project to help you remove the reward of their work from their work?

I don't understand if you're stupid or an idiot, maybe both.

**Comment by Acalann** [comment]
I mean like I could have made a donation to them for making it but you assume I didn't?

I mean I respect that they made it but 1% of everything I ever make is just too much for me

**Comment by Acalann** [comment]
Also it's not uncommon for that to happen

**Comment by theaog** [comment]
this is what you should do: send 1XMR to https://github.com/xmrig/xmrig#donations
then contact @SChernykh, and maybe he'll help you compile.

**Comment by Acalann** [comment]
can you just help me please?

**Comment by Spudz76** [comment]
It literally is telling you what's missing.

`error: expected ‘,’ or ‘;’ before ‘constexpr’`

**Comment by theaog** [comment]
> can you just help me please?

no
