### ISSUE TITLE
HTTPS API ?

### ISSUE THREAD

**Issue by MetallianFR68** [xmrig/xmrig#317]
Simple question : 

I'm mining MONERO on every computer of the company I own
Some are mining using XMRIG
Some are mining using javascript miner

I want the javascript miner to turn off if XMRIG is running on the computer.
The easiest way to detect if XMRIG is running from javascript is to check if the API is running on http://localhost

The problem is my website is HTTPS
So he refuses to check the API on insecure HTTP

_The page at 'https://optimus.adaris.org/tools/minage/index.php' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:4446/_

Is there a way to run the API on HTTPS ?

**Comment by snipeTR** [comment]
Use xmrigCC

**Comment by xmrig** [comment]
It complicated, libmicrohttpd must be build with libgnutls support, if it be solved, next trouble will appear, still need valid/trusted certificate for localhost.
Thank you.

**Comment by MetallianFR68** [comment]
You can't get a certificate for localhost. Only qualified domain can. However in Chrome you can set : chrome://flags/#allow-insecure-localhost. Activating HTTPS on the api would then solve the problem.
