### ISSUE TITLE
[s390x]Cannot compile on s390x platform

### ISSUE THREAD

**Issue by wgxsysgirl6** [xmrig/xmrig#3177]
[s390x]Cannot compile on s390x platform

**Comment by wgxsysgirl6** [comment]
You can get an s390x VPS on https://linuxone.cloud.marist.edu/

**Comment by mckaygerhard** [comment]
1.  seems this is a scam account
2. for s390x please provide log compilation
3. the patches from #3174  and #3175  applies on s390 old releases compilers

**Comment by Sstealther0101** [comment]
I found this random code broken down in literary piece's so I tried to
rebuild it I'm not creator or anything it's my first time learning in
coding and sushlike order of service Java json python script in any case
for studying I tried recreation but it was a mess then went back on the
code still it has alot of loops in it I can share site from where it was
published I have no means or reason to deny or abuse system and community
members dev and even the anything in between it's first day on ghub
today.thank alot appreciate in advance

**Comment by mckaygerhard** [comment]
> the code still it has alot of loops in it I can share site from where it was published I have no means or reason to deny or abuse system and community members dev and even the anything in between it's first day on ghub today.thank alot appreciate in advance

A recommendation before trying to learn to code is to read, you should and should always read instructions

before sending information you should always read how it is sent.. is a nature in windows users never READ the information over projects or instructions.. just next time try to find information respect the place you plan to send (in this case the issue) your issue.. so you can follow instructions (like the missing log you never provide)

**Comment by Sstealther0101** [comment]
Totally agreed

**Comment by xmrig** [comment]
s390x is not supported.
Thank you.
