### ISSUE TITLE
XMRig fails to run when using --no-cpu

### ISSUE THREAD

**Issue by neomachiney** [xmrig/xmrig#3178]
```
./xmrig --opencl -o xmrpool.eu:9999 -u 4Ax4xrtEBb386TN9zxYAGVSMjc6zzs4Xqf6B3pNvSYz8U6cA7LCyBxHGsuXbyK7xFmA2a1N8jQAL3aGBzBCE2GgXHB8tRko --algo='rx/0' -k --tls
```
This works but I am not sure if it mines by GPU.
```
./xmrig --no-cpu --opencl -o xmrpool.eu:9999 -u 4Ax4xrtEBb386TN9zxYAGVSMjc6zzs4Xqf6B3pNvSYz8U6cA7LCyBxHGsuXbyK7xFmA2a1N8jQAL3aGBzBCE2GgXHB8tRko --algo='rx/0' -k --tls
```
This gives this error
```
[2022-12-13 10:31:17.098]  net      xmrpool.eu:9999 incompatible/disabled algorithm "rx/0" detected, reconnect
[2022-12-13 10:31:17.098]  net      xmrpool.eu:9999 login error code: 6
```

**Comment by neomachiney** [comment]
```
Also there's this weird ./xmrig: unrecognized option: opencl
```

**Comment by neomachiney** [comment]
```
./xmrig: unrecognized option: opencl
 * ABOUT        XMRig/6.18.1 gcc/9.3.0
 * LIBS         libuv/1.44.1 OpenSSL/1.1.1o hwloc/2.7.1
 * HUGE PAGES   supported
 * 1GB PAGES    disabled
 * CPU          AMD Athlon Silver 3050U with Radeon Graphics (1) 64-bit AES
                L2:1.0 MB L3:4.0 MB 2C/2T NUMA:1
 * MEMORY       4.7/5.7 GB (82%)
                Bottom - Slot 1 (left): <empty>
                Bottom - Slot 2 (right): 8 GB DDR4 @ 2400 MHz M471A1K43EB1-CWE    
 * MOTHERBOARD  HP - 8706
 * DONATE       2%
 * ASSEMBLY     auto:ryzen
 * POOL #1      xmrpool.eu:9999 algo rx/0
 * COMMANDS     hashrate, pause, resume, results, connection
```

**Comment by Sstealther0101** [comment]
Hello good morning I did upload one code that found on net and recreate it
and just uploaded I did apologize I'm not expert it's my literary first day
sundries with people living to seel from social media. I'm sorry if I did
anything wrong but how could I help

**Comment by Sstealther0101** [comment]
What's this all this emails all about can you specify?

**Comment by Sstealther0101** [comment]
It's first day in GitHub and  don't got a nap from social media because of
this condition now what I can resolve

**Comment by SChernykh** [comment]
@neomachiney 
You use invalid wallet address (checksum test fails). Double check it. When I change this wallet address to my own, everything works fine and xmrig mines RandomX on my GPU.

**Comment by Sstealther0101** [comment]
Where should I. Input the address then??(\¢

**Comment by neomachiney** [comment]
@SChernykh Is this wallet address okay: `4Ax2xrtEBb386TN9zxYAGVSMjc6zzs4Xqf6B3pNvSYz8U6cA7LCyBxHGsuXbyK7xFmA2a1N8jQAL3aGBzBCE2GgXHB8tRko` Not sure how 2 got replaced by 4 but I get same `incompatible/disabled algorithm "rx/0" detected, reconnect`

**Comment by SChernykh** [comment]
It looks like you downloaded the static build of xmrig (`xmrig-6.18.1-linux-static-x64.tar.gz`), this version only supports CPU. If you really want to mine RandomX with your GPU and not CPU, download `xmrig-6.18.1-linux-x64.tar.gz`

**Comment by neomachiney** [comment]
Thank you it works @SChernykh
