### ISSUE TITLE
Combining two GPUs' VRAM

### ISSUE THREAD

**Issue by benthetechguy** [xmrig/xmrig#3194]
I have a 4 GB Radeon RX 6400 that I would like to mine kawpow on when I'm not using the computer, but there's not enough VRAM for the DAG. I'm thinking of buying a second one for purposes unrelated to mining, and I was wondering if it would be a possibility to use their combined 8 GBs of VRAM to fit the DAG.

**Comment by SChernykh** [comment]
It will be too slow and limited by PCIe bandwidth which is 100-500 times less than VRAM bandwidth.

**Comment by benthetechguy** [comment]
Alright. Thank you for clarifying.
