### ISSUE TITLE
Issue with HTTP API

### ISSUE THREAD

**Issue by chapst1ck** [xmrig/xmrig#3221]
Trying to make changes in config like this:
`curl -v -d '{"color":false}' -X PUT -H 'Content-Type: application/json' -H "Authorization: Bearer CHERRY" http://127.0.0.1:80/1/config`

In result I get:
```
{
    "status": 400,
    "error": "Bad Request"
}
```
Сan you tell me where I made a mistake?

**Comment by Spudz76** [comment]
You have to send a complete config.json content object not just single entries.  Like the route overwrites the current config.json just like if you scp'd it.

**Comment by chapst1ck** [comment]
Oh, now I understand it. Thanks.
