### ISSUE TITLE
Haiku OS R1 / Can't compile / hwloc issue

### ISSUE THREAD

**Issue by FSOL-XDAG** [xmrig/xmrig#3231]
Hi everybody ! 

G33k challenge : I've try to compile XMRig 6.19.1 on Haiku OS (BeOS fork). Very nice OS if you want to discover something different than Windows & Linux.

Here are the commands I typed:

```
pkgman install cmake automake libtool autoconf
mkdir temp && cd temp
git clone https://github.com/xmrig/xmrig.git
mkdir xmrig/build && cd xmrig/scripts
./build_deps.sh && cd ../build
```

It crash on 'hwloc' : 

![image](https://user-images.githubusercontent.com/128682335/227652171-a1f8fef0-12d2-4926-a448-d2b9edc002ca.png)

Before that, I was informed about this possible issue : 

![image](https://user-images.githubusercontent.com/128682335/227651933-347e676d-c040-4ab2-a331-3bca9089510b.png)

On Haiku forum, someone tell me : 

> You can try to install hwloc from the depot aswell, maybe the build system allows select system provided libs instead of the in-tree version.

Please find complete log beside. 

[haiku_log.txt](https://github.com/xmrig/xmrig/files/11066898/haiku_log.txt)
Does anybody knows ? How to "install hwloc from the deposit" ? 

Thanks for your help ! Best regards.

**Comment by SChernykh** [comment]
If hwloc doesn't support it, it will probably not work even if you manage to compile it. It's better to compile XMRig without hwloc - remove hwloc related lines from build_deps.sh and run `cmake .. -DWITH_HWLOC=OFF` when building XMRig.

**Comment by FSOL-XDAG** [comment]
Ok, hwloc is ignore. But another problem occurent with OpenSSL. 

![image](https://user-images.githubusercontent.com/128682335/227889610-a9528ff9-0c38-4432-8057-a5309efbec72.png)

Don't you have any idea about this ?

**Comment by SChernykh** [comment]
It's OpenSSL config script that fails, so it's not supported too. Remove OpenSSL from build_deps.sh and try `-DWITH_TLS=OFF` when building XMRig.

**Comment by FSOL-XDAG** [comment]
First of all, I sought some help from the Haiku community. Apparently, the hwloc and openssl libs are already installed in the system, although it crashes at compile time (check 's' before their name) : 

![image](https://user-images.githubusercontent.com/128682335/227945636-57a2819c-3ddd-496a-86a9-8a7f6b5f2e92.png)

Nevertheless, I applied your advice. I removed hwloc & openssl from build_deps.sh : 

![image](https://user-images.githubusercontent.com/128682335/227946180-e95a7111-885c-46cb-897c-d5f1d5551b50.png)

Then I run build_deps.sh but something went wrong ...

Check this logfile : [xmrigscripts .build_deps_log.txt](https://github.com/xmrig/xmrig/files/11078890/xmrigscripts.build_deps_log.txt)

Nevertheless, I run `cmake .. -DWITH_TLS=OFF -DWITH_DHWLOC` and it's fails :

![image](https://user-images.githubusercontent.com/128682335/227947769-d98043aa-2711-4338-b9a3-f00485d1b916.png)

May I conclude "mission impossible to compile XMRig on this OS" ?

**Comment by SChernykh** [comment]
But did you also add `-DXMRIG_DEPS=scripts/deps` to cmake command line? It's in the instructions for the advanced build with build_deps.sh

**Comment by SChernykh** [comment]
This is what I expected. XMRig doesn't know this OS, so it defaults to code that has never been compiled before. To remove all references to byteswap.h, add `-DWITH_KAWPOW=OFF -DWITH_HTTP=OFF` to cmake command line.

**Comment by FSOL-XDAG** [comment]
Ok. Last directive seems unknow : 

![image](https://user-images.githubusercontent.com/128682335/227964119-6934a370-ddea-48b8-ae3f-2ef084e50328.png)

**Comment by FSOL-XDAG** [comment]
This is the result : 

[cmake_make_haiku.txt](https://github.com/xmrig/xmrig/files/11079625/cmake_make_haiku.txt)

**Comment by SChernykh** [comment]
It looks like you're out of luck at this point. Basically any OS-dependent code in XMRig fails to compile, and XMRig uses a lot of it to optimize performance.

**Comment by FSOL-XDAG** [comment]
All right, so there's no need to waste time on that. Thanks for trying to help me! Much appreciated. 👍

**Comment by Begasus** [comment]
With latest support by user @user0-07161 it's possible to launch xmrig now on Haiku, thanks for taking a look at us! 👍 

<img width="897" height="549" alt="Image" src="https://github.com/user-attachments/assets/691f84da-1f77-49db-beea-7bbd43b29387" />
