### ISSUE TITLE
Do it support Epic Cash?

### ISSUE THREAD

**Issue by gif12** [xmrig/xmrig#3255]
Does the xmrig program support the Epic cash digital currency that works with the RandomX algorithm

if no ,please add it

**Comment by Spudz76** [comment]
Duplicate of #3248

**Comment by gif12** [comment]
i test it , dont support miner epic cash

**Comment by gif12** [comment]
I tested it, and it doesn't support epic cash

When I enter the address of the epic cash pool and its algorithm and... and run it, it just waits and does not extract

**Comment by gif12** [comment]
I tested it, and it doesn't support epic cash

When I enter the address of the epic cash pool and its algorithm and... and run it, it just waits and does not extract

**Comment by Lexenfermo** [comment]
How to work?

**Comment by SChernykh** [comment]
Epic cash has 3 PoW algorithms, you need to consult with your pool operator on how to only mine RandomX.

**Comment by Spudz76** [comment]
Still a duplicate of #3248, never said it was fixed or worked, but that one was first.

**Comment by bey0ndmo** [comment]
Yeah it looks like randomepic or rx/epic isn't even supported by xmrig, let alone switching to algo 1 when algo 0 isn't available (which is 52% of the time in randomepics case, bit of a shame...
