### ISSUE TITLE
sh: 1: xmrig: not found

### ISSUE THREAD

**Issue by Tahsin75** [xmrig/xmrig#3258]
![20230421_141327](https://user-images.githubusercontent.com/95874393/233581427-80451761-8b64-404f-b520-4a09fdabea6f.png)
![Uploading 20230421_141150.png…]()
              ```
import os
os.system('xmrig --help')
```
bc1qaym5869qeltv3pxra66aclder7z87mv8ce3um7

_Originally posted by @lalanza808 in https://github.com/xmrig/xmrig/issues/3244#issuecomment-1499570658_

**Comment by xmrig** [comment]
#3259
