### ISSUE TITLE
Wiki missing Fedora dependencies

### ISSUE THREAD

**Issue by Maxim-Mazurok** [xmrig/xmrig#326]
On fresh install of CentOS 7, you will need to install `make` and `libuv-static`. But before installing `libuv-static` you should install `epel-release` package to enable Epel repo.
So, the instructions should look like this for CentOS:
```
sudo yum install -y epel-release
sudo yum install -y git make cmake gcc gcc-c++ libuv-static libstdc++-static libmicrohttpd-devel libuv-static
git clone https://github.com/xmrig/xmrig.git
cd xmrig
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib64/libuv.a
make
```
Add to Wiki, please, it seems like I don't have access to editing Wiki.
Thanks!

**Comment by xmrig** [comment]
I added wiki page https://github.com/xmrig/xmrig/wiki/CentOS-Build
Thank you.

**Comment by zhaoyongtao** [comment]
How to `Install` and `Use`  `xmrig` on `CentOS6` ?

**Comment by Maxim-Mazurok** [comment]
@zhaoyongtao I think that instructions will be the same as for CentOS 7. Can you try it?

**Comment by zhaoyongtao** [comment]
@Maxim-Mazurok   It works! Thanks!

**Comment by 330377782** [comment]
[root@vultr build]# cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib64/libuv.a
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found UV: /usr/lib64/libuv.a  
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR) 
CMake Error at cmake/OpenSSL.cmake:17 (message):
  OpenSSL NOT found: use `-DWITH_TLS=OFF` to build without TLS support
Call Stack (most recent call first):
  CMakeLists.txt:201 (include)
这是森么问题？

**Comment by 330377782** [comment]
[root@vultr build]# make
Scanning dependencies of target xmrig-asm
[  1%] Building ASM object CMakeFiles/xmrig-asm.dir/src/crypto/asm/cn_main_loop.S.o
Linking C static library libxmrig-asm.a
[  1%] Built target xmrig-asm
Scanning dependencies of target cpuid
[  3%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
cc1: error: invalid option argument ‘-Ofast’
make[2]: *** [src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o] Error 1
make[1]: *** [src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/all] Error 2
make: *** [all] Error 2

在最后make的时候出错了

**Comment by 330377782** [comment]
你好，安装完毕以后，如何配置他呢？

**Comment by Maxim-Mazurok** [comment]
@330377782, https://github.com/xmrig/xmrig/blob/master/README.md#options

https://github.com/xmrig/xmrig/blob/master/doc/api/1/config.json

https://github.com/xmrig/xmrig/blob/master/README.md#contacts

**Comment by 330377782** [comment]
> @330377782, https://github.com/xmrig/xmrig/blob/master/README.md#options
> 
> https://github.com/xmrig/xmrig/blob/master/doc/api/1/config.json
> 
> https://github.com/xmrig/xmrig/blob/master/README.md#contacts

在centos里面咋启动哈？

**Comment by Maxim-Mazurok** [comment]
> > @330377782, https://github.com/xmrig/xmrig/blob/master/README.md#options
> > https://github.com/xmrig/xmrig/blob/master/doc/api/1/config.json
> > https://github.com/xmrig/xmrig/blob/master/README.md#contacts
> 
> 在centos里面咋启动哈？

你什么意思？(What do you mean?)

**Comment by xerxessss** [comment]
i got some errors.  linux 6.10(final)

[root@localhost build]# make
[  1%] Building C object src/3rdparty/argon2/CMakeFiles/argon2-avx512f.dir/arch/x86_64/lib/argon2-avx512f.c.o
cc1: error: invalid option argument ‘-Ofast’
make[2]: *** [src/3rdparty/argon2/CMakeFiles/argon2-avx512f.dir/arch/x86_64/lib/argon2-avx512f.c.o] Error 1
make[1]: *** [src/3rdparty/argon2/CMakeFiles/argon2-avx512f.dir/all] Error 2
make: *** [all] Error 2

**Comment by exition** [comment]
> @330377782, https://github.com/xmrig/xmrig/blob/master/README.md#options
> 
> https://github.com/xmrig/xmrig/blob/master/doc/api/1/config.json
> 
> https://github.com/xmrig/xmrig/blob/master/README.md#contacts

centos8里面 libstdc++-static  hwloc-devel openssl-devel 这三个yum里面找不到

missing libstdc++-static  hwloc-devel openssl-devel  packages in centos8 yum repository

**Comment by zungtm** [comment]
hi, help me
CMake Error: your ASM_MASM compiler: "ml" was not found.   Please set CMAKE_ASM_MASM_COMPILER to a valid compiler path or name.
thank you!

**Comment by nfcg** [comment]
> hi, help me
> CMake Error: your ASM_MASM compiler: "ml" was not found. Please set CMAKE_ASM_MASM_COMPILER to a valid compiler path or name.
> thank you!

Same error here on CentOs 7.

```
sudo yum install -y cmake3
cmake3 .. 
make
```
Build finishes  no errors.
