### ISSUE TITLE
xmr.nanopool.org Unable to display Worker name!

### ISSUE THREAD

**Issue by worm001** [xmrig/xmrig#3263]
What parameters can be used to display Workers in xmr.nanopool.org mining using the latest version of xmrig.exe? I can't specify the machine name with the [--rig-id] parameter either!

**Comment by Spudz76** [comment]
https://help.nanopool.org/hc/en-us/articles/4898831059101-xmrig

Says you encode your rig name into the wallet/username.

**Comment by worm001** [comment]
> https://help.nanopool.org/hc/en-us/articles/4898831059101-xmrig
> 
> 说你将你的装备名称编码到钱包/用户名中。

Thank You！！！~
