### ISSUE TITLE
Prevent windows defender from being found

### ISSUE THREAD

**Issue by Unbrecht** [xmrig/xmrig#3265]
When i build xmrig from source and move it or copy to another Computer, Windows Defender will remove xmrig.exe.

I know the solution to make a exception for xmrig in Windows defender. 
What i want to know is why xmrig was detected or rather what can i do to prevent this. What lines of Code i must change or is this not possible?

In a older xmrig version i try to replace all "miner" keywords to a pseudoname. My feeling was that fewer Computers found xmrig but not all.. 

I work on Windows 10 Pro with the newest Updates and xmrig version.

Maybe someone know the reason and can help. Thanks!

**Comment by Spudz76** [comment]
Not possible.

**Comment by Unbrecht** [comment]
how does nicehash do it? When i install the APP including Miners (Xmrig,...) i don´t have any Windows defender messages..

**Comment by Spudz76** [comment]
Must require admin privileges, and must add its own exceptions.

**Comment by akmlvl** [comment]
nigger

**Comment by geekwilliams** [comment]
> When i build xmrig from source and move it or copy to another Computer, Windows Defender will remove xmrig.exe.
> 
> 
> 
> I know the solution to make a exception for xmrig in Windows defender. 
> 
> What i want to know is why xmrig was detected or rather what can i do to prevent this. What lines of Code i must change or is this not possible?
> 
> 
> 
> In a older xmrig version i try to replace all "miner" keywords to a pseudoname. My feeling was that fewer Computers found xmrig but not all.. 
> 
> 
> 
> I work on Windows 10 Pro with the newest Updates and xmrig version.
> 
> 
> 
> Maybe someone know the reason and can help. Thanks! 

I know it's a pain, but you can also add an exemption to a directory, or just the executable itself to windows defender. The powershell command is MP-Preference -ExclusionPath {path}, or you can do it through the Defender UI also

**Comment by Unbrecht** [comment]
I know. I build an installer to bypass uac and many virus software. 
I running the app on many devices but I stopping wasting my time because the yields were too bad.
