### ISSUE TITLE
Affinity xmrig or system problem

### ISSUE THREAD

**Issue by dawidmosk** [xmrig/xmrig#3268]
I know system affinity is more important like program but how it work in real life? Which option is more stable/real/correct? For example
1. cpu 8 cores, xmrig using 2,3,4,5,6,7 and system affinity 2,3,4,5,6,7 expected used: 2,3,4,5,6,7 
2. cpu 8 cores, xmrig using 0,1,2,3,4,5,6,7 and system affinity 2,3,4,5,6,7 expected used: 2,3,4,5,6,7 
3. cpu 8 cores, xmrig using 2,3,4,5,6,7 and system affinity 0,1,2,3,4,5,6,7 expected used: 2,3,4,5,6,7 
We talking about win10+. On option 3 notitied using 100% ?!?!

**Comment by SChernykh** [comment]
> On option 3 notitied using 100% ?!?!

100% for xmrig or the whole system? xmrig can't use 100% if it's not running all 8 threads. The best option is to leave it to xmrig to auto configure.

**Comment by SChernykh** [comment]
Option 3 should always leave cores 0,1 unused by XMRig. If they're still used, it's some other program or system itself.
