### ISSUE TITLE
xmrig support Xeon Phi

### ISSUE THREAD

**Issue by dchpantkd** [xmrig/xmrig#327]
Hi,
can xmrig work with Intel Xeon Phi?

Thanks,
Hieu.

**Comment by QwertyJack** [comment]
Definitely NO; not now at least.
You would like to try lukminer.
Google it anyway.

**Comment by yuhong** [comment]
It probably would be possible with only minor modifications.

**Comment by BlackMulch** [comment]
Xeon Phi (x100 and x200) support would be a welcome addition!

**Comment by onweer** [comment]
Xeon Phi (x100 and x200) support would be a welcome addition! Too

**Comment by mechanator** [comment]
Ironic that the major shift to cpu based algorithms like RandomX can't use the Phi cards and CPUs. It would be one way to hedge against a possible FPGA or ASIC attack if there were nodes on the network decentralizing hash or be a seed node for some coins.

**Comment by image28** [comment]
Looking into this over the next week ( however will be for the 5110P model only as that is all I have to work with currently )

**Comment by ps2chiper** [comment]
Did you get anywhere with those 5110P cards?

**Comment by GrauBlitz** [comment]
> Looking into this over the next week ( however will be for the 5110P model only as that is all I have to work with currently )

@image28 Did you get any result from you research? I have multiple 7120P for testing.
