### ISSUE TITLE
Developer's signing   key

### ISSUE THREAD

**Issue by LinuxUser255** [xmrig/xmrig#3279]
Hi, I am trying to locate the gpg signing key  to verify  the xmrig download before  executing it.
Similar to using  binaryfate's GPG when downloading the monero  wallet.

Thanks

**Comment by SChernykh** [comment]
It's in every release description: https://github.com/xmrig/xmrig/releases/tag/v6.19.2 - see "SHA256SUMS.sig" and links below it.
