### ISSUE TITLE
Add algo ‘randomepic’ algorithm (EpicCash RandomX)

### ISSUE THREAD

**Issue by whereveryouare666** [xmrig/xmrig#3282]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: [e.g. Windows]
 - For GPU related issues: information about GPUs and driver version.

**Additional context**

**Comment by koitsu** [comment]
Looks like a duplicate of https://github.com/xmrig/xmrig/issues/3248
