### ISSUE TITLE
32bit exe not found in repo

### ISSUE THREAD

**Issue by DARK-DEVIL-66** [xmrig/xmrig#3354]
Hi My Windows is 32 bit so i need 32bit miner

**Comment by geekwilliams** [comment]
Reinstall windows 64 bit. Its not worth running 32 bit even if there was one available.

**Comment by DARK-DEVIL-66** [comment]
Why ?

**Comment by geekwilliams** [comment]
Your max hash rate will be extremely low, and you will not be able to effectively use huge pages. You will be operating the miner at almost 100% loss so it doesn't make any sense

**Comment by DARK-DEVIL-66** [comment]
thanks
