### ISSUE TITLE
compile xmrig x86

### ISSUE THREAD

**Issue by Fl1x** [xmrig/xmrig#337]
**I install this:**

pacman -Sy
pacman -S mingw-w64-i686-gcc
pacman -S make
pacman -S mingw-w64-i686-cmake
pacman -S mingw-w64-i686-pkg-config

<a href="https://ibb.co/gF9Xgm"><img src="https://preview.ibb.co/mWW0Z6/report.jpg" alt="report" border="0"></a>
**But i dont have this files:**

"c:\<path>\gcc\libuv\x86\include" -DUV_LIBRARY="c:\<path>\gcc\libuv\x86\lib\libuv.a" -DMHD_INCLUDE_DIR="c:\<path>\gcc\libmicrohttpd\x86\include"
"c:\<path>\gcc\libmicrohttpd\x86\lib\libmicrohttpd.a"

**I search this files in folder msys64 but Have not found.Help Me Pls.Thx**

**Comment by Axe-Usa** [comment]
you got to solve it?

**Comment by Fl1x** [comment]
Yeah)
