### ISSUE TITLE
Fuck you for making things harder to get  your 1% donation 

### ISSUE THREAD

**Issue by animencoding** [xmrig/xmrig#3376]
Why can't you write a proper build from source doc so you force people to use your bin's fuck you dude

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/build

**Comment by miqumi** [comment]
lmao

**Comment by ltecheroffical** [comment]
Tbh, it's not a good idea to force a donation amount unless users go out of their way to change it, it's just a change for as far as I see.
