### ISSUE TITLE
2.4.4 32 bit not working on Windows XP

### ISSUE THREAD

**Issue by sergneo** [xmrig/xmrig#338]
Very very sorry, but version 2.4.4 32 bit GCC has stopped working in Windows Xp and 2003, an early version 2.4.3 32 bit successfully works on these versions of Windows . I so liked XMRig CPU because it worked on older versions of Windows, and now I can still keep compatibility with older versions of the OS ?
XMRig 2.4.4
![xmrig-2 4 4](https://user-images.githubusercontent.com/27492679/34935007-742c9d00-f9ed-11e7-9c4f-20e450b88e74.jpg)

XMRig 2.4.3
![xmrig-2 4 3](https://user-images.githubusercontent.com/27492679/34935263-4f6afeac-f9ee-11e7-889b-9494714396a3.jpg)

[ConvertInterfaceIndexToLuid function](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365826(v=vs.85).aspx)
Remarks

The ConvertInterfaceIndexToLuid function is available on Windows Vista and later.

**Comment by xmrig** [comment]
I confirm bug, in version 2.4.4 libuv and libmicrohttpd updated to recent versions, probably it cause the issue.
Thank you.

**Comment by sergneo** [comment]
Yes, the problem is in libuv. I compiled with the previous version libuv/1.14.1 from xmrig-deps-v2 and the new libmicrohttpd/0.9.58 from xmrig-deps-v2_1. Xmrig 2.4.4 works successfully.

**Comment by xmrig** [comment]
I rebuilt and replaced `xmrig-2.4.4-gcc-win32` with older libuv version. 1.15.0 last version with Windows XP/2003 support. Also updated dependencies https://github.com/xmrig/xmrig-deps/releases/tag/v2.2
Thank you.

**Comment by github-donkey** [comment]
libuv 1.15.0 from xmrig-deps also needs ConvertInterfaceIndexToLuid() and so it's unable to start in Windows XP. It's possible to build xmrig 2.5.0 with libuv 1.14.1 from older deps and app runs but instantly fails with message:

Assertion failed!

Program: C:\mingw.exe
File: src/win/timer.c, Line 37

Expression: new_time >= loop->time

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
