### ISSUE TITLE
Segmentation fault on v6.20.0 when API HTTP enabled

### ISSUE THREAD

**Issue by yueehndnx** [xmrig/xmrig#3381]
Linux builds v6.20.0 when HTTP API enabled in JSON config caused to Segmentation fault when Ghostrider algo benchmark started
Reproduced on:

compact build from the repository
Works fine on the original XMRig. So the most obvious thing here is that there is a conflict with benchmarking

**Comment by SChernykh** [comment]
> Works fine on the original XMRig

You should probably report it to MoneroOcean, not here.

**Comment by yueehndnx** [comment]
> > 在原始 XMRig 上运行良好
> 
> 您可能应该将其报告给 MoneroOcean，而不是在这里。

Getting this error in original xmrig

**Comment by SChernykh** [comment]
> Works fine on the original XMRig

> Getting this error in original xmrig

You're contradicting yourself. Can you write how to trigger this error in the original XMRig?
