### ISSUE TITLE
MSR MOD not enabled, Windows 10

### ISSUE THREAD

**Issue by XMRcollector117** [xmrig/xmrig#3395]
I keep getting the "FAILED TO APPLY MSR MOD" text when running the minew on my new Windows 10 pro laptop.
I've disabled all of the visualization, turned off Memory Integrity, and even took off SafeBoot in the BIOS; but I still get this problem. Capped around 140 h/s because of it.
![20231231_113201](https://github.com/xmrig/xmrig/assets/155317548/925e3d82-27e9-4d16-afa5-ee6c5aa650b6)
Is there a way to fix this, or am I f'ed?

**Comment by SChernykh** [comment]
Celeron N4100 doesn't support MSR.

**Comment by XMRcollector117** [comment]
> Celeron N4100 doesn't support MSR.

Really? Darn. Thank you
