### ISSUE TITLE
Compile for 32bit with VS2015

### ISSUE THREAD

**Issue by RemezW** [xmrig/xmrig#34]
Hi! How i can compile 32bit version of xmrig on 64bit windows machine with VS2015? I successfully compiled 64 bit version, but not understand how do it with 32bit.. In Visual Studio available only x64 Release version. Thank you!

**Comment by xmrig** [comment]
When run cmake instead of `-G "Visual Studio 14 2015 Win64"` specify `-G "Visual Studio 14 2015"` and path to 32bit libuv.
Please note 32 bit msvc version noticeably slower than gcc version.
Thank you.

**Comment by RemezW** [comment]
Okay! Thank you. I get it.
I correctly understand that the 32-bit version can work on 32-bit systems and 64-bit systems?

**Comment by xmrig** [comment]
Yes.
