### ISSUE TITLE
Documentation: add daemon-job-timeout

### ISSUE THREAD

**Issue by koitsu** [xmrig/xmrig#3400]
Two simple things to fix:

* The `--daemon-job-timeout` flag is missing from https://xmrig.com/docs/miner/command-line-options  (but it is visible via `--help`)
* The `daemon-job-timeout` parameter is missing from https://xmrig.com/docs/miner/config/pool (please be sure to note that the value is in milliseconds and defaults to 15000)

Thanks SChernykh!

**Comment by xmrig** [comment]
Done. Other missing options also added: `--daemon-zmq-port=N`, `"spend-secret-key"`, `"sni"`, `"daemon-zmq-port"`.
Thank you.

**Comment by koitsu** [comment]
Looks great. Thanks SChernykh!
