### ISSUE TITLE
Client_loop: send disconnect Broken pipe

### ISSUE THREAD

**Issue by schmidtBalint** [xmrig/xmrig#3406]
I'm getting this ssh disconnection. I'm trying to run xmrig on my pi4. I'm connected to it via ssh. I run the program it gets a job etc but it seems to hang up and when I press a command such as h to see the hashrate I get the broken pipe.

**Comment by geekwilliams** [comment]
Are you able to plug in a monitor and run the app to see what's happening?

**Comment by schmidtBalint** [comment]
Not really that's why I use ssh. I don't have a micro hdmi with me now.

**Comment by geekwilliams** [comment]
What version and what OS are you running on the pi? Are you able to log back in using ssh without rebooting the pi?

**Comment by schmidtBalint** [comment]
Im using the 64 bit version pi OS lite. Yes I'm able to log back in without a reboot

**Comment by geekwilliams** [comment]
You may be having an issue with your ssh client not sending keep-alive messages as soon as the server on the pi is expecting. Please add the following to the command you use to log in to the pi 

```
-o ServerAliveInterval=60
```

If this works, you can update your ssh client's settings to fix this. 

Also, if you intend to run xmrig long-term on the pi you may want to look into a utility like Unix's Screen.  That way xmrig doesn't automatically stop when the ssh session is disconnected.

**Comment by SChernykh** [comment]
Also, this is not an XMRig issue.
