### ISSUE TITLE
crashes when DNS resolving temporary failure 

### ISSUE THREAD

**Issue by zzh1996** [xmrig/xmrig#342]
When my network is temporarily not working, xmrig cannot resolve the domain name of my mining pool. It will crash.
```
src/unix/getaddrinfo.c:91: uv__getaddrinfo_translate_error: Assertion `!"u
nknown EAI_* error code"' failed.
Aborted (core dumped)
```

**Comment by xmrig** [comment]
Please provide more details what OS and libuv version did you use, etc.
Thank you.
