### ISSUE TITLE
Integrate ZLUDA for AMD CUDA mining

### ISSUE THREAD

**Issue by GermanAizek** [xmrig/xmrig#3421]
**Describe the feature**
https://github.com/vosen/ZLUDA
it can give higher hashrate on amd video cards if cuda code is optimized

**Comment by SChernykh** [comment]
> ZLUDA is focused on end users
By user we mean someone who uses a CUDA program, e.g. a 3D artist using Blender. Developer developing a CUDA application is not an. While we would like to support developers in the future, right now the time constraints do not allow it

So nothing to integrate, just use it if you want?

**Comment by GermanAizek** [comment]
@SChernykh,
it would be more convenient for users if xmrig itself determined need for use

**Comment by GerrFrog** [comment]
I am developer of MINUX-Miner. I think I will integrate it

**Comment by GerrFrog** [comment]
@SChernykh GermanAizek

**Comment by SChernykh** [comment]
There is nothing to integrate, it's an end-user software. Just follow their instructions, it should already work with XMRig.

**Comment by GerrFrog** [comment]
@SChernykh you mean just compile and run xmrig using this library?

**Comment by ahorek** [comment]
@GerrFrog I've tried it just for fun

download
https://github.com/vosen/ZLUDA/releases
add cuda plugin
https://github.com/xmrig/xmrig-cuda/releases
run it with
**zluda.exe xmrig.exe -- -a cryptonight-upx/2 -o stratum+tcp://xxx:1234 -u xxxxxxxxxxxx -p xxxxxxxxx --cuda --no-cpu**

my results with Radeon 7900 xtx 2Ghz for comparsion
opencl 82000h/s
zluda 67700h/s

performance may vary based on the algorithm, but it just works out of the box and there's nothing to be done on the xmrig's side "to integrate it".
