### ISSUE TITLE
"--cpu-priority=0" still not being honored. 

### ISSUE THREAD

**Issue by realsetvin** [xmrig/xmrig#3422]
After using "--cpu-priority=0" at the end of my command line - however the top command reveals this has done nothing.

after some basic research I saw this issue was referenced in the past and "closed as fixed"

https://github.com/xmrig/xmrig/issues/2351

I am not able to get the command to work.

**Comment by realsetvin** [comment]
Actually after more testing, it is being honored, but --cpu-priority=0 is giving the process NI of 5 when 19 should be expected based on comments in the above mentioned issue.

--cpu-priority=1 gives NI of 0

--cpu-priority=2 gives NI of -5

after testing --cpu-priority=0 NI 5 has proven not sufficient to prevent cpu disruptions to other processes in my usecase. Ideally we want 19, not 5.

**Comment by SChernykh** [comment]
NI 5 is for cpu-priority 1. cpu-priority 0 should be 19, and that value goes directly to `setpriority(PRIO_PROCESS, 0, prio);` system call.

**Comment by realsetvin** [comment]
![image](https://github.com/xmrig/xmrig/assets/117243445/48141856-4243-4c91-a33c-fd78b3c9f612)

Yes I do see that. Would using -n 19 do anything to help my issue? I have another process running which is still online however its not responding fast enough and its causing service disruptions. Since the process itself uses almost no cpu, im hoping to have both the miner and the process running.

So far using --cpu-priority=0 does not seem extreme enough to limit the miner from causing disruptions of the other process.

**Comment by SChernykh** [comment]
Increase priority of that other process? Maybe also use 1 less mining thread, so you always have at least 1 available CPU core.

**Comment by realsetvin** [comment]
I think that is part of the problem. Is it possible to mine with half a core? lol

**Comment by realsetvin** [comment]
thanks for your time and quick assistance, I will close this issue because the parameter seems to be working as intended.
