### ISSUE TITLE
sockets show only one

### ISSUE THREAD

**Issue by xuebinboy** [xmrig/xmrig#343]
os:centos 6.5  cpu:E5-2670v2 *2
run xmrig, sockets show only one

![sockets1](https://user-images.githubusercontent.com/12096247/35020319-69cd7396-fb66-11e7-85f0-73de440c6907.png)
please help me.

**Comment by xmrig** [comment]
If this issue still actual, please check v2.99.2-beta release #1077.
Thank you.
