### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by angousana** [xmrig/xmrig#3432]
I tried building from source using both advanced and basic method but the output binary is always bigger than the binary inside latest static release "xmrig-6.21.1-linux-static-x64.tar.gz", how do i build optimised binary like the one in static release, I'm using Ubuntu amd64 if it matters

**Comment by SChernykh** [comment]
xmrig-6.21.1-linux-static-x64 is built on Alpine Linux, it uses different libraries than Ubuntu.
