### ISSUE TITLE
donate.v2.xmrig.com:3333 DNS error: "no such file or directory"

### ISSUE THREAD

**Issue by ac615223s5** [xmrig/xmrig#3442]
**Describe the bug**

**To Reproduce**
xmrig.exe

**Expected behavior**

**Required data**
[2024-03-13 01:57:28.223]  net      donate.v2.xmrig.com:3333 DNS error: "no such file or directory"

**Additional context**

**Comment by SChernykh** [comment]
Use OpenDNS servers instead of your regular DNS from your internet provider.

**Comment by Pythdevver** [comment]
Try to ping some other server with cmd.exe, maybe it's an accident network failure.

**Comment by itscz-org** [comment]
I just had the same issue with an older and the newest release. "nslookup pool.domain" just worked fine in CMD. However, i tried to disable my piHole and yes, that helped. Seems there are some other lookups beside the pool address and the log info is wrong. Hope that info helps.
