### ISSUE TITLE
Should I active Huge Pages?

### ISSUE THREAD

**Issue by PipeDeveloper** [xmrig/xmrig#346]
Hello.

I just want to know if its recomended to active huge pages or use any specific configuration for this setting.

 * VERSIONS:     XMRig/2.4.4 libuv/1.8.0 gcc/5.4.0
 * HUGE PAGES:   available, disabled
 * CPU:          Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz (3) x64 AES-NI
 * CPU L2/L3:    2.2 MB/120.0 MB
 * THREADS:      3, cryptonight, av=1, donate=1%
 * POOL #1:      pool.supportxmr.com:3333
 * API PORT:     8080
 * COMMANDS:     hashrate, pause, resume

already im using 3 THREADS and getting about 130-160H/s but just in case that i can improve a little more the performance.

Already i tested hugepages with 128 but i lower the hashrate to 20-110 H/s

**Comment by NmxMilk** [comment]
LOL, you have a beast there and you only get 160 H/S out of it !
Before trying huge pages, which might give you 5 to 10% improvement, you should push your thread count to 16 (per cpu) and check your cpu affinity.
You should be getting at least 600H/S out of each cpu and you seam to have 3 of them !

**Comment by PipeDeveloper** [comment]
Thanks for the reply

Its a cloud server and i hired a plan of 3CPUs dedicated. I cant use more. Huge pages also decrease a little bit the performance on this case

**Comment by vekunz** [comment]
Is there a way, to enable huge pages manually? In my case huge pages are randomly sometimes enabled and sometimes disabled. But if huge pages are enabled, I have a bit more hashes (~180H/s instead of ~160H/s).

**Comment by Pythonic-Rainbow** [comment]
Why is this even an issue?

**Comment by renatocamargo** [comment]
@Pythonic-Rainbow you can do it by changing the number of huge pages (vm.nr_hugepages) in the /sysctl.conf on Linux OS.
