### ISSUE TITLE
4way for internal algos

### ISSUE THREAD

**Issue by YetAnotherRussian** [xmrig/xmrig#347]
Some algos used in cryptonight may benefit from 4way, example: 
https://github.com/JayDDee/cpuminer-opt/tree/master/algo/skein
https://github.com/JayDDee/cpuminer-opt/tree/master/algo/keccak
https://github.com/JayDDee/cpuminer-opt/tree/master/algo/blake
https://github.com/JayDDee/cpuminer-opt/tree/master/algo/jh

This cannot be ported directly, but you may take a look at possibilty to have a separate build of xmrig, or add some switches depending on CPU capabilities.

**Comment by 2010phenix** [comment]
and if already have example in clean C, maybe add this one to classic xmrig miner version too.
