### ISSUE TITLE
error in VB Net Application when XMrig run

### ISSUE THREAD

**Issue by shannonoleson1** [xmrig/xmrig#348]
i faced some error in my VB Net Application developed by my office, like below 

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	UMB_UMK.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	5a585c47
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.7.2558.0
  Problem Signature 06:	59d41393
  Problem Signature 07:	3106
  Problem Signature 08:	a2
  Problem Signature 09:	KUTS43RW3WMPE3EWT1R1Z5M5MTM1NR04
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	e948
  Additional Information 2:	e9486f525b83a92608e4ef32d6ebee70
  Additional Information 3:	f6e9
  Additional Information 4:	f6e9e08a154ae9a139b71260062cc304

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

is there something i can do to fix the error??

**Comment by xmrig** [comment]
You need run debug build, to obtain call stack or something like that, don't know much about VB Net.
Thank you.
