### ISSUE TITLE
Cannot build - MHD_LIBRARY (ADVANCED) NOTFOUND

### ISSUE THREAD

**Issue by robme** [xmrig/xmrig#349]
I cannot build the newer versions. I tried with

`cmake .. -DWITH_HTTPD=OFF`

I get the error:

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> MHD_LIBRARY (ADVANCED)
>     linked by target "xmrig" in directory xmrig-2.4.4
>
> -- Configuring incomplete, errors occurred!

This is on Ubuntu. I have installed all the packages as well, including libmicrohttpd-dev.

**Comment by robme** [comment]
I managed to build it by modifying the last line of CMakeLists.txt and removing ${MHD_LIBRARY}:

`target_link_libraries(xmrig ${UV_LIBRARIES} ${EXTRA_LIBS} ${CPUID_LIB})`

**Comment by xmrig** [comment]
Fixed now https://github.com/xmrig/xmrig/pull/324
This issue caused because cmake cache, fresh cmake run (without exists files/previous runs) with `-DWITH_HTTPD=OFF` should work ok anyway.
Thank you.
