### ISSUE TITLE
How to add a second donation address

### ISSUE THREAD

**Issue by ArchLinuxAddict** [xmrig/xmrig#3494]
when i searched for this i found a 2018's code where it was correct but the same wont work for latest so how to add it and if the donations set to 0 will this second donation address work

**Comment by Internetnews1** [comment]
"pool_list": [
    {
        "pool_address": "xmr.zeropool.io:3333",
        "wallet_address": "solo:0x0c1CF28241a7FFC8A81E504Eb0f92b32FdF56AA2",
        "rig_id": "",
        "pool_password": /* Solo Mining set [solo:] */"child-address@xmr@Parrot",
        "use_nicehash": false,
        "use_tls": false, /* Set to true if you are using an SSL port */
        "tls_fingerprint": "",
        "pool_weight": 1
    },
],
"currency": "randomX",
