### ISSUE TITLE
Is there a way to apply msr mod on a .cmd file?

### ISSUE THREAD

**Issue by Fgr-35** [xmrig/xmrig#3496]
Is there a way to apply msr mod on a .cmd file? I couldn't get xmrig to connect with the pool so i made a .cmd file provided by the pool to start but i cannot run it in admin mode so i won't get msr. How can i fix that?

**Comment by geekwilliams** [comment]
Run it in admin mode with right-click-> run as admin

**Comment by Fgr-35** [comment]
I get an error that xmrig.exe is not a command, this is why i asked here

**Comment by Fgr-35** [comment]
It doesn't make sense and i couldn't find anything on the internet

**Comment by geekwilliams** [comment]
Can you post the contents of your .cmd file minus any private info?

**Comment by Fgr-35** [comment]
@echo off
xmrig.exe --donate-level 1 -o de.monero.herominers.com:1111 -u YOUR_MONERO_WALLET_ADDRESS -p YOUR_WORKER_NAME -a rx/0 -k 
pause

This is what is provided by the pool. I only had to configure the wallet address amd the worker name

**Comment by geekwilliams** [comment]
You need to make sure the cmd is in the same folder as xmrig.exe for that to work. Also use .\xmrig.exe at the beginning

**Comment by Fgr-35** [comment]
It is on the same folder and it works, the only issue im encountering is that i cannot run in admin mode to enable msr

**Comment by SChernykh** [comment]
https://github.com/xmrig/xmrig/blob/master/scripts/pool_mine_example.cmd
When you run .cmd as admin, it runs in C:\Windows\system32 by default, so some special commands are needed.

**Comment by Fgr-35** [comment]
Should i run cmd as admin and then use the cd command to locate the folder where xmrig is and from there run the .cmd file, something like that?

**Comment by geekwilliams** [comment]
Sure, that's one way to do it

**Comment by Fgr-35** [comment]
It worked and i get 4,5kH/s. Thank you for the help
