### ISSUE TITLE
invalid block template from daemon when mining salvium to local node

### ISSUE THREAD

**Issue by sfhdfshdfh** [xmrig/xmrig#3511]
**Describe the bug**
it throws an error when trying to mine salvium rx/0 with --daemon flag
error is job error "invalid block template received from daemon"
daemon was run by --add-priority-node seed03.salvium.io flag. xmrig dev claimed it would work fine already for this randomx coin. but it doesnt. 

**To Reproduce**
win 10
xmrig.exe -t 24 -a rx/0 --daemon -o 127.0.0.1:19081 -u SaLxxxx

**Expected behavior**

**Required data**
 - XMRig version 6.21.0

**Comment by SChernykh** [comment]
Salvium is not supported. Use #3508 if you want to mine it.

**Comment by sfhdfshdfh** [comment]
pool does seem to accept the shares from original xmrig with -a rx/0 but neither pool nor the miner ever hit any blocks. that pool went down after it failed finding blocks. i think it should be named rx/sal instead. xmrig will get obsolete if it doesnt get flexible enough with adding more cpu algos and coins.

**Comment by SChernykh** [comment]
Salvium uses exactly the same algorithm, it's rx/0. Pool issues are not xmrig issues - as soon as some pool gets working, xmrig will work when mining to it.
