### ISSUE TITLE
Change display details

### ISSUE THREAD

**Issue by RJansen222** [xmrig/xmrig#352]
I would like to change my display to show all settings used.
Currently shows
* VERSION:
* HUGE PAGES:
* CPU:
* CPU L2/L3
* THREADS:
* POOL #1 
* COMMANDS:

What i would like to do is change it, so it shows all the current values of all the configurable options. 

I know its possible i just don't know how... if someone could guide me... or just point me into the right direction... THAT WOULD BE GREAT!

**Comment by xmrig** [comment]
All information located in one file https://github.com/xmrig/xmrig/blob/master/src/Summary.cpp several `print_*` functions. It can be extended.
Thank you.
