### ISSUE TITLE
Question: View screen

### ISSUE THREAD

**Issue by AngryDragonflyStudios** [xmrig/xmrig#3553]
I'm running Linux, and i been trying to google to find the answer, but i have xmrig running in background, is there a command that i can run when i SSH in to view the console for the running pid process so i can monitor the progress again after running overnight?

**Comment by geekwilliams** [comment]
Why not run xmrig in the foreground, but use a [screen](https://en.wikipedia.org/wiki/GNU_Screen) window to keep an eye on it?  You can detach and reattach to the screen session, even through ssh.   

Another option would be to have xmrig output to a log file, which you can then monitor with tail. [See documentation here.](https://xmrig.com/docs/miner/command-line-options#logging). If you are using config.json, find the line "log-file": null, and change it's value.
