### ISSUE TITLE
Create a Android binary only build 

### ISSUE THREAD

**Issue by shenlo666** [xmrig/xmrig#3563]
Hi, is it possible to build xmrig only for android devices?
I mean, a binary which is not possible to run in Linux OS.
If i build the xmrig binary in Termux, you can launch this on Unix (with some tricks).
So is there a workaround?
Thanks a lot, my best!

**Comment by ahorek** [comment]
> is it possible to build xmrig only for android devices?

yes, Termux works (as far as I know)

> If i build the xmrig binary in Termux, you can launch this on Unix (with some tricks).

no, Android binaries aren't fully compatible with Linux, but you can use UserLAnd on Android

**Comment by shenlo666** [comment]
Thanks @ahorek, yes xmrig works great on Termux, but my question was about "only for android"!
As far as i know, UserLand is for run Linux app on Android, sorry this is not what i want, i want to build Android Only binaries, so i cant run on Linux OS.
So if you said that they aren't fully compatible that's fine i hope.

Another point, somebody knows howto embed (store in binaries) xmrig arguments/command line options like pool, port,...?
So the user dont have to pass the option in the command line.
Thank you.

**Comment by ahorek** [comment]
> So if you said that they aren't fully compatible that's fine i hope.

I'm wondering what your goal is, but yes, binaries built for Android won't work on UserLAnd / Linux or Windows :)

> somebody knows howto embed (store in binaries) xmrig arguments/command line options like pool, port,...?

why do you need it in the binary? isn't a JSON config enough?
https://github.com/xmrig/xmrig?tab=readme-ov-file#usage
