### ISSUE TITLE
Can only be run on 64 - bit computer?

### ISSUE THREAD

**Issue by Li-Xingyu** [xmrig/xmrig#357]
Can only be run on 64 - bit computer?

**Comment by Dhruv420** [comment]
@Li-Xingyu you can download the 32 bit release from here(https://github.com/xmrig/xmrig/releases)

**Comment by Li-Xingyu** [comment]
sorry ,i want now how to build

**Comment by 2010phenix** [comment]
@Li-Xingyu search, no? ))

https://github.com/xmrig/xmrig/wiki/Build
