### ISSUE TITLE
Not using all the potential of the Xeon E5 2698 V4

### ISSUE THREAD

**Issue by jcastro** [xmrig/xmrig#358]
Hello!

I have the Xeon E5-2698 v4 (see https://ark.intel.com/products/91753/Intel-Xeon-Processor-E5-2698-v4-50M-Cache-2_20-GHz) but it seems it's not using all of its potential. In fact I had to decrease the cpu-max-usage to 60 in order to get around an average of 800 H/s... with cpu-max-usage 75 I was getting around 450-500 H/s

This is my command line
`@echo off
xmrig.exe -o pool.supportxmr.com:7777 -u WALLET -p WORKERNAME -k --max-cpu-usage 60 --donate-level 1
pause`

This the console output as soon as I start the miner
![screen shot 2018-01-23 at 11 19 59](https://user-images.githubusercontent.com/190036/35270531-b7927a72-002f-11e8-869d-646dd97c12fd.png)

**Comment by HeDo88TH** [comment]
Use these settings

--max-cpu-usage 95 
--cpu-affinity "0x5555555555" 
--threads 20

let me know

**Comment by jcastro** [comment]
@HeDo88TH thanks! I just tried but I'm getting a bit less, around 680H/s

**Comment by jcastro** [comment]
Actually using 20 threads only uses the "physical" cores but I get the threaded ones at 0% – See htop
![screen shot 2018-02-02 at 14 30 36](https://user-images.githubusercontent.com/190036/35735634-c2c91cc2-0825-11e8-8068-cdc12cbad09e.png)

**Comment by jcastro** [comment]
Seems like the perfect configuration is the one that xmrig itself selects which is 24 threads. Less or more than that gives me less H/s. 24-25 is just perfect

**Comment by HeDo88TH** [comment]
You can set the max-cpu-usage to 100, It will give you +5%
It's useless to use the threaded cores, what is limiting the mining speed is the L2/L3 cache size not the core count. By using the threaded cores you are not adding any of it :)

**Comment by mohammad4u** [comment]
@jcastro, i can see that in the first instance the l3 cache is showing 0 while in the second it shows true value of 50 mb. Did you change any settings other than recommended by @hedo88th?

**Comment by HeDo88TH** [comment]
Yes it will make difference
