### ISSUE TITLE
AMD Geode Support

### ISSUE THREAD

**Issue by Abaita** [xmrig/xmrig#359]
I am running FreeBSD 10.4 on Alix 1.c board which has an AMD Geode LX800 CPU. First i tried to compile the code using gcc but that fail at the final linking step complaining about missing atomic_... constants. Then i tried to compile using clang which worked fine but sadly it is not possible to launch the program, it end in a core.dump.
I know that the performance of the CPU is probably just about 10H/s but i am just curious if it is possible to run xmrig on a Geode CPU. That CPU is/was often used for firewalls because it has an hardware-encryption feature which could also be usefull for mining i hope. See also https://www.twam.info/hardware/alix/using-geodes-aes-engine-on-alix3d3

**Comment by Abaita** [comment]
I have added "-latomic" to build/CMakeFiles/xmrig.dir/link.txt, now it also builds using gcc but it still fails on startup:
Illegal instruction (core dumped)

**Comment by yuhong** [comment]
doesn't look suitable. remember that Monero's AES is slightly different from normal AES.

**Comment by Abaita** [comment]
I know that the performance is weak but it should be possible to run the code, right? Even without support of the integrated crypto-device it should be able to execute the software-aes like some people doing it on their raspberries. How can i find out by myself what that illegal instruction is? is there a debug-mode?

**Comment by yuhong** [comment]
AFAIK the miner requires SSE2 which the Geode don't support.

**Comment by Abaita** [comment]
ok, so basically the same issue like there was for arm in #94 . Since Geode is pretty outdated nobody will add support for it. i will look for some other use for it. thanks.
