### ISSUE TITLE
Fail build on Centos 6.9 Final

### ISSUE THREAD

**Issue by kriwelz** [xmrig/xmrig#364]
its a fresh install, and when i tried to make it shows these errors 

[root@bot build]# make
Scanning dependencies of target cpuid
[  2%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
cc1: error: invalid option argument '-Ofast'
cc1: error: unrecognized command line option "-ftree-loop-if-convert-stores"
make[2]: *** [src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o] Error 1
make[1]: *** [src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/all] Error 2
make: *** [all] Error 2

any help?

**Comment by b0n0** [comment]
cmake options ?you point to libuv?

**Comment by kriwelz** [comment]
Yes, I just follow the instructions. I already update my gcc to 6.4 too,
after reading another post with similar issues, but mine still having
trouble.

**Comment by kriwelz** [comment]
Can you be so kind to point me how to check and make sure which version I
have and how to fix?
I will post my system versions when I got back to it in few hours.

**Comment by xmrig** [comment]
Older version of gcc not support `-Ofast`, you need specify name/path to your gcc/g++ when run cmake.
Thank you.

**Comment by tkalfaoglu** [comment]
try a gcc --version command to see your gcc version.
Yes, Centos 6.x's gcc does not recognise -Ofast..  See my new ticket.. it also does not recognise two other options.

**Comment by tkalfaoglu** [comment]
Ok, here is the solution:
https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/
do this and then you can compile it.. that simple..
Oh yes and update the libuv..
The cmake becomes:
cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/local/lib/libuv.a  -DWITH_HTTPD=OFF

**Comment by cityvigil** [comment]
copy from How can i install on centos 6? #52  

vinchch

I've go also error when compiling with the latest kernel on centos 6
got the same error: version `GLIBC_2.14' not found
btw, I found a binary that works great here

https://cryptodev.one/dev/download-compiled-x86_64-binaries-xmrig-centos-6-x-7-x/
