### ISSUE TITLE
maximum cpu usage can not be lower to 50%?

### ISSUE THREAD

**Issue by Axe-Usa** [xmrig/xmrig#366]
i tried with two cores and always take me 50% of my pc. can not put in a lower limit modifying the code?

**Comment by Dondor17** [comment]
First of all, how many threads in total do you have ? 2 ? 
What CPU do you have ? There is a chance you have 2 physical cores + 2 more threads if you have a newer Intel CPU.

You can actually modify the maximum CPU usage in the code.

**Comment by Axe-Usa** [comment]
in which part in the configuration or in which part of code? i have 2 cores so the minimum is 50%. but i want to put it in a lower limit.

**Comment by xmrig** [comment]
With 2 cores minimum is 50% (1 core of 2).
Thank you.
