### ISSUE TITLE
mining in two pools or two wallets?

### ISSUE THREAD

**Issue by Axe-Usa** [xmrig/xmrig#367]
it's possible to mining in two wallets?

**Comment by 0xc0d32** [comment]
Yes, Modify url donate in source code!

**Comment by Axe-Usa** [comment]
in DonateStrategy i just must to put the pool, the port and the wallet?
Url *url = new Url("pool", Options::i()->algo() == Options::ALGO_CRYPTONIGHT_LITE ? 3333 : port, wallet, nullptr, false, true);

**Comment by 0xc0d32** [comment]
![donatestrategycode](https://user-images.githubusercontent.com/29043805/35489686-e7fdd05c-0477-11e8-83c2-481b237ddaa9.PNG)
