### ISSUE TITLE
[Windows] Compile 32bit version with visual studio 2015 and CMake ?

### ISSUE THREAD

**Issue by Dondor17** [xmrig/xmrig#368]
Hello!
Ive been trying to compile xmrig with  VS2015 as Win32 application.
I can compile 64 bit (Win64) version with VS2015/2017 fine but cant compile 32 bit version (Win32).
However, i strictly need to compile it as 32 bit in vs 2015.

Here is my batch build file ` "%PROGRAMFILES%\CMake\bin\cmake" .. -G "Visual Studio 14 2015 Win32" -DUV_INCLUDE_DIR="C:\xmrig-deps-v2_1\msvc2015\libuv\x86\include" -DUV_LIBRARY="C:\xmrig-deps-v2_1\msvc2015\libuv\x86\lib\libuv.lib" -DMHD_INCLUDE_DIR="C:\xmrig-deps-v2_1\msvc2015\libmicrohttpd\x86\include" -DMHD_LIBRARY="C:\xmrig-deps-v2_1\msvc2015\libmicrohttpd\x86\lib\libmicrohttpd.lib"`

CMake gives me this error: `CMake Error: Could not create named generator Visual Studio 14 2015 Win32`.

Am I missing some VS tools or something like that ? Does anyone know how to approach this ? 

Thank you!

**Comment by metalurgus** [comment]
have you tried `Visual Studio 14 2015 Win64` instead of `Visual Studio 14 2015 Win32`? AFAIK it is not a target platform

**Comment by Dondor17** [comment]
thanks but i have stated that i need to compile it specifically as Win32...not win64. i need a 32bit version of xmirg.

**Comment by metalurgus** [comment]
`Win64` does not mean what you will get as an output. It is something else. You will get 32 bit binary as an output using `Visual Studio 14 2015 Win64`

**Comment by Dondor17** [comment]
thanks for clarifying.  I've compiled it with the settings you stated  and tried to run it in my Windows 7 32bit virtual machine. It didn't give any runtime library errors, however it said that the binary can't be executed.

I solved this issue by compiling via mingw32 and gcc. Now it runs everywhere ☺

**Comment by metalurgus** [comment]
I have just build 32 bit version:
I had to remove CPUID lib support for it to build 32 bit. Was unable to make it build as 32 bit. 
Steps:

Cmake command (you called it a batch build file):

`cmake .. -G "Visual Studio 15 2017 Win64" -DUV_INCLUDE_DIR="c:\xmrig\msvc2017\libuv\x86\include" -DUV_LIBRARY="c:\xmrig\msvc2017\libuv\x86\lib\libuv.lib" -DMHD_INCLUDE_DIR="c:\xmrig\msvc2017\libmicrohttpd\x86\include" -DMHD_LIBRARY="c:\xmrig\msvc2017\libmicrohttpd\x86\lib\libmicrohttpd.lib" -DWITH_LIBCPUID=OFF`

`-DWITH_LIBCPUID=OFF` will remove cpuid lib.

Open generated project in the visual studio
Add new project configuration as `Win32`, ccopy settings from: x64, check to create new project platforms. 
Save all

Open 
`\build\xmrig.vcxproj` filewith any text editor, and replace all accurances of `machine:x64` with `machine:x86`. 

In visual studio choose to Reload this file (didn't try `Reload solution`, I think it might break something)

Finally build ALL_BUILD project. Now it should build just fine, output .exe should be x86.

But you did right to build it with mingw32 - it is easier, and cpuid lib works

**Comment by noname29** [comment]
How did you compile it as 32 bit? Can yuou please show the steps? I need it compiled as a dll and 32 bits. I was able to compile it as a dll with visual studio 2017 but I am running into problems as I try it for 32 bits. Can you give me some tips ?
