### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ptiom1980** [xmrig/xmrig#369]
This occurs randomly and stops xmrig, any ideas?

[2018-01-27 23:14:07] no active pools, stop mining
Segmentation fault (core dumped)

**Comment by xmrig** [comment]
You use CPU miner or GPU (amd or nvidia)?.
Thank you.

**Comment by djdomi** [comment]
Hi

I can confirm this, using amd-gpu miner, i dont know why this happens but maybe you can give me a hint howto debug this.

I try to mine on a Intel GPU (i know its slowly, but having around 10 laptops laying around)

**Comment by ptiom1980** [comment]
Nvidia but I have had this occur with the CPU miner once as well. I am running it on Ubuntu 17.10
