### ISSUE TITLE
tcsetattr: 无效的参数

### ISSUE THREAD

**Issue by blacksirt** [xmrig/xmrig#372]
hello,when i run xmrig in linux,the console echo "tcsetattr: 无效的参数",how to resolv it?

**Comment by Gill1000** [comment]
Thats strange.....i never received that....which is your linux distro..??

**Comment by blacksirt** [comment]
SUSE Linux Enterprise Server 11
linux-kajs 2.6.27.19-5-default

**Comment by xmrig** [comment]
What libuv version did you use? Propably some terminal/ssh related issue. Try remove this line https://github.com/xmrig/xmrig/blob/master/src/Console.cpp#L39
Thank you.

**Comment by blacksirt** [comment]
thank you.
i don't know.... when i remove this: https://github.com/xmrig/xmrig/blob/master/src/Console.cpp#L39,in the begin it's ok,few minutes later still the same problom..............is there other place to modify?

**Comment by Bravoyk** [comment]
@blacksirt hey, Can u tell me how to install this program with “SUSE Linux Enterprise Server 11” .
