### ISSUE TITLE
build xmrig step by step

### ISSUE THREAD

**Issue by omarraom** [xmrig/xmrig#373]
Hello can any one help me by explain how to build xmrig miner step by step with all the programme need it to install once for all

**Comment by Gill1000** [comment]
https://github.com/xmrig/xmrig/wiki/Build
Here bro..everything is step by step and simple .. @omarraom

**Comment by Zelecktor** [comment]
Watch some videos about how to install cmake, thats the difficult part if you ussing windows (add it on path and defining commandline on cmd). Visual basics is very easy to use, dont need tutorial for that. Your result: an .exe file

On linux is more easy. Just sudo install libraries and dependencies, cmake and compile (make). Thats 100% much easier and faster than windows.
Your result: an executable file no extension called "xmrig", just do this command `./xmrig` to run it. (you need to be on the same directory of the file)

All tutorials are on the wiki https://github.com/xmrig/xmrig/wiki/Build

Note: if you using Linux debian 9.2, use the same build as ubuntu. if you are using linux debian 7-8 see #248
