### ISSUE TITLE
Convert console application to the windows service

### ISSUE THREAD

**Issue by persiaitc** [xmrig/xmrig#374]
Hello
Thanks in advanced
I want to convert XMRig to a windows service that works at the background of the Windows with abilities like controlling cpu usage, cpu temperature, etc. Something like Awesome mier!
Do you think it is possible and/or easy?

**Comment by xmrig** [comment]
You can use https://nssm.cc/
Thank you.

**Comment by Dhruv420** [comment]
@persiaitc For creation of windows service you can take a look at #286.I have made a short guide there.

**Comment by persiaitc** [comment]
Thanks
NSSM works great and I'm using it now.
