### ISSUE TITLE
warning: be attacked by xmrig in the disguise of shipyard.

### ISSUE THREAD

**Issue by nagexiucai** [xmrig/xmrig#377]
Not a issue, just give a notice.
From friend of mine:

a docker container with image "[docker.io/dockersdev/shipyard:0.12](https://hub.docker.com/r/dockersdev/shipyard/tags/)", a xmrig in fact, runs "/shipyard-deploy/systemd".

@shipyard @ehazlett @docker

**Comment by ehazlett** [comment]
@nagexiucai thank you.  i've notified our support group.  thanks for the heads up!
