### ISSUE TITLE
Question: How to run xmrig automatically at window start-up......???

### ISSUE THREAD

**Issue by Gill1000** [xmrig/xmrig#378]
I have gone through other issues but still i m out of luck..I want to run xmrig automatically on window start-up when i start my window I have tried other ways to run at start-up and now I want to run start-up by registry keys of current user!!!!!........I mean sort of like(it automatically install itself and run automatically even after shut-down by registry keys)hope you get my point.
Thanks.

**Comment by Dhruv420** [comment]
@Gill1000  You can use task scheduler if you are on windows.

Or you can create a service that will automatically start when the client logs in to windows.I have made a small guide here #286

**Comment by Gill1000** [comment]
Thanks Dhruv420 ..but i have done this.i have gon through all the issues !!!.... But. Now i want to practice with registry keys!!!!!

**Comment by Dhruv420** [comment]
@Gill1000 the above procedure automatically creates registry key at 

**HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Services**

**Comment by Dhruv420** [comment]
Or you can create a .reg file (for the function you want to implement) and export it.

**Comment by Gill1000** [comment]
Again thanks :)
Let me again clear my question!...How to edit or rewrite the source code only in such a way that it automatically install itself without help of additional apps as you mention before.!! And automatically start-up!!! As i log in! (By windows startup)
Thanks.

**Comment by Dhruv420** [comment]
As of now i cannot modify the source code to make the application "install" itself.
But there's another way round too.You just need to add the program you want to run automatically in the registry-
(And it won't require any additional programs too)

You can do this by navigating to the path below-

**[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run]**  

For each program you want to start automatically create a new string value (by right click) using a descriptive name, and set the value of the string to the program executable.

For example, to automatically start Notepad, add a new entry of:

"Notepad"="c:\windows\notepad.exe".

**Comment by Gill1000** [comment]
Where. Are you pal @Zelecktor you have got what exactly i m looking for..plz guide if you are reading this.

**Comment by Zelecktor** [comment]
duplicated issue, related with #293
please close.

**Comment by Zelecktor** [comment]
> How to edit or rewrite the source code only in such a way that it automatically install itself without help of additional apps as you mention before.

Are you thinking in make like a startup registry key persistance? for example, when you launch miner for first time, it will automatically put the register and If the user deletes the startup registry key, the miner will write a new startup key immediately?

I think you want to create a virus hahahaha but interesting, to do it you need to modify severals src to add a fragment of the source code of register injection. Also to bypass admin permision to modify register key if you run as user, thats not easy.

**Comment by sergneo** [comment]
I use xmrig installed as a service using nssm ( http://nssm.cc/download ) . It is very easy to use program.

**Comment by Gill1000** [comment]
Hehehe virus hehaheha..noo way ..this option is not in my checklist.. maybe @xmrig you can help

**Comment by JuanMao1997** [comment]
@sergneo but how to make it startup on other computers? It's impossible to install nssm on every computer.
