### ISSUE TITLE
Improvements: Precisely and strict control max-cpu-usage option

### ISSUE THREAD

**Issue by hgs81** [xmrig/xmrig#381]
Hi, xmrig team!
Thanks for your great effort.
I would like to add this awesome feature.
I found that max-cpu-usage option is only used for thread count calculation.
Is there any way to precisely control maximum CPU usage?
For example, if other processes are using 10% cpu and max-cpu-usage is 50%, then xmrig can be automatically configured to use exactly 40%.
And if current cpu level is 60%, xmrig pauses mining, etc.
So cpu usage could really <= 50%.
Can you control mining algorithm speed or add some sleeps so that it can not exceed desired cpu usage?
Thanks.

**Comment by RansomFuck** [comment]
Set process priority hight from other process
