### ISSUE TITLE
Improvements: Remote configure options through API

### ISSUE THREAD

**Issue by hgs81** [xmrig/xmrig#382]
I would like to add some REST API to set options on-the-fly remotely.
Something like this:
curl -X POST -F "pools.url=xxx" -F "pools.user=xxx" -F "pools.pass=xxx" http://localhost:8080/set_config
Or:
curl -X POST -F "donate-level=5%" -F "max-cpu-usage=80" -F "threads=4" http://localhost:8080/set_config

**Comment by RansomFuck** [comment]
Read xmrigCC thread

**Comment by hgs81** [comment]
Can you send me link please?

**Comment by xmrig** [comment]
Recent versions can change config via API in JSON format.
Thank you.
