### ISSUE TITLE
32 or 64 bit?

### ISSUE THREAD

**Issue by wgx** [xmrig/xmrig#383]
Is there any difference (significant or otherwise) between mining on a 32-bit and 64-bit architecture? If so, will it affect hashrate much?

**Comment by sergneo** [comment]
Yes, at 64 bit speed 1.5 times higher, of course will be affected.

**Comment by xmrig** [comment]
You should always prefer use 64 bit version, 32 bit usable only if impossible run 64 bit version.
Thank you.
