### ISSUE TITLE
Question:NOT AN ISSUE  how to compile xmrig ?

### ISSUE THREAD

**Issue by Gill1000** [xmrig/xmrig#384]
How to compile xmrig except visual studio or cmake ...I mean how to compile with other c++ compilers like code-blocks,dev-c++ or any other.!!

**Comment by xmrig** [comment]
Run `cmake -G` it will show all available generators, take look to
`CodeBlocks - Unix Makefiles`
`CodeBlocks - NMake Makefiles`

For me `CodeBlocks - Unix Makefiles` works fine with Qt Creator (MSYS2).
Thank you.

**Comment by Gill1000** [comment]
I checked that...but thats not what i was looking for..i mean in this we use cmake ..........I dont want to use this..is there another way like open code:block or any other except given above ......open codeblock and select the .cpp and .h files ..like this!!! @xmrig

**Comment by xmrig** [comment]
It hard way, it possible, but you will do all cmake work by hand.
Thank you.
