### ISSUE TITLE
Can't build full statical executable for linux

### ISSUE THREAD

**Issue by mctracker** [xmrig/xmrig#388]
I'am using this command:

 `root@debian:~/monero/xmrig/build# cmake .. -DBUILD_SHARED_LIBS=OFF -DWITH_HTTPD=OFF -DCMAKE_BUILD_TYPE=Release -DUV_INCLUDE_DIR=/usr/local/src/libuv-1.8.0/ -DUV_LIBRARY=/usr/local/lib/libuv.a`

But when trying to run on other maching I've got this message:

> ./xmrig: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./xmrig)

How can I build an independent executable for Linux? Thank you.

**Comment by djdomi** [comment]
I would join your question, since i try to let it run also on others, building onetimes for all...
MAybe this is also a Point why no static binary is avaible from this Project for linux?

**Comment by Mila432** [comment]
use a good compiler and there you have your static bin

**Comment by 2010phenix** [comment]
confirm what to say @Mila432 all good with static build.

**Comment by mctracker** [comment]
> use a good compiler and there you have your static bin
Whats wrong with linux default compilers like gcc? The question is - is what proper flags for Cmake should I use to make full static binary.

**Comment by Mila432** [comment]
@mctracker everything from libc until ..

**Comment by mctracker** [comment]
@Mila432 I need correct flags for CMAKE

**Comment by btx3** [comment]
Either spin up a VM with an older version of CentOS (<7 should work) and build it there, or compile an older version of glibc and link it with xmrig when compiling.

**Comment by djdomi** [comment]
@btx3
ok, but whoxh commands do you THEN suggest to use to build the static binary? cant you give an example for it?
