### ISSUE TITLE
Change donation pool and add duplicate

### ISSUE THREAD

**Issue by LearnMiner** [xmrig/xmrig#389]
I read some Issues here but i have a question,
if i change
Url *url = new Url("fee.xmrig.com", Options::i()->algo() == Options::ALGO_CRYPTONIGHT_LITE ? 3333 : 443, userId, nullptr, false, true); 

for other pool:

Url *url = new Url("otherpoool", Options::i()->algo() == Options::ALGO_CRYPTONIGHT ? 3333 : PORTPOOL, userId, nullptr, false, true); 

How can i put my adress and pass pool?

**Comment by LearnMiner** [comment]
@xmrig

**Comment by 2010phenix** [comment]
it's joke? dev work hard, make to you good soft for mining... and you fu*king ignorant ass ask to him how remove HIM donate pool?

**Comment by LearnMiner** [comment]
@2010phenix i add duplicate donation NO remove HIM DONATE POOL
