### ISSUE TITLE
Some cache double counted on intel too.

### ISSUE THREAD

**Issue by phillipsjk** [xmrig/xmrig#39]
I was able to reproduce this:
https://github.com/anrieff/libcpuid/issues/97

 under WinXP-64, on an Intel Core 2 Duo E8400

Note:
Only the gcc compiled binary works, msvc one says: "permission denied" and  Windows complains it is not a valid win32 app.

**Comment by xmrig** [comment]
I will switch to hwloc instead of libcpuid, it fixes cache size issues and helps with NUMA nodes support #86
