### ISSUE TITLE
Can I manually set xmrig difficulty?

### ISSUE THREAD

**Issue by xberg** [xmrig/xmrig#390]
Hi,
Is it possible to change cryptonight's default difficulty? 

Mining Cryptonight algo thru xmrig at 800 H /s. Current difficulty is 200,007.
My miner is finding very few results at such difficulty. Is there no way to start at a lower difficulty?

**Comment by xmrig** [comment]
It depends of pool, you need check your pool help page. Usually it `+DIFF` or `.DIFF` added to wallet address, but not all pools support this feature.
Thank you.

**Comment by korishan** [comment]
It can also be the pool address port can change the difficulty. Check to see which ports your pool is using. It's possible the there are different ports available.
