### ISSUE TITLE
minexmr.pooldd.com doesn't need password, but in cmd line usage, what does "-p x" means?

### ISSUE THREAD

**Issue by zacario-li** [xmrig/xmrig#393]
Hi,
    minexmr.pooldd.com doesn't need password, but in cmd line usage, what does "-p x" means?

**Comment by bobbieltd** [comment]
For fun 😂

**Comment by bobbieltd** [comment]
It means pass : “x”, most pools/softwares use that as default. It’s not real password.

**Comment by xuxuedong** [comment]
pool_password  - Can be empty in most cases or "x".
from https://github.com/fireice-uk/xmr-stak-cpu/blob/master/config.txt
line 105
