### ISSUE TITLE
Is it possible to lower processor time usage?

### ISSUE THREAD

**Issue by rtpoz** [xmrig/xmrig#394]
I bought some VPS with 2 core, but I can use only 86400 seconds per day.
Is it possible to change code to lower processor usage to about 90% on one core?

**Comment by 2010phenix** [comment]
yes 50%, use option -t 1

**Comment by rtpoz** [comment]
It's not working. I already running only one thread.
Thanks for your answer.

**Comment by xuxuedong** [comment]
"86400 seconds per day", are you kidding, it's 24 hours per day?

**Comment by xuxuedong** [comment]
what's meaning of "to about 90% on one core", you want only one core or each core to about 90% cpu usage? if the latter, you can try option "--max-cpu-usage=N    maximum CPU usage for automatic threads mode (default 75)", if the former, it's a little difficult to use only one core to about 90% cpu usage

**Comment by xuxuedong** [comment]
and the title "processor time usage", what's meaing of it?

**Comment by rtpoz** [comment]
The VPS administrator wrote to me that I exceeded the consumption of time (processor time usage). Theoretically it is possible to use 2x86400 s on two cores but I can use only 1 core on 90% of power :(.
