### ISSUE TITLE
Mingw64 build needs dlls

### ISSUE THREAD

**Issue by cpucoin** [xmrig/xmrig#395]
I have tried building with mingw64 with the newest source and the newest versions of libuv and microhttpd from this repository but when I try to run it needs extra dlls. When I copy the libwinpthread-1.dll to the same directory as the exe, it then crashes. Any ideas?

**Comment by RansomFuck** [comment]
Installed with MSYS64? And you install all step-by-step to you Mingw*version* in wiki?

**Comment by cpucoin** [comment]
Followed instructions on build wiki for windows.
New install of mingw64 on win7
New source and assets from github

**Comment by cpucoin** [comment]
Tried fresh install of msys2-x86_64-20161025, with xmrig-2.4.4, cmake of: cmake .. -G "Unix Makefiles" -DWITH_HTTPD=OFF -DWITH_AEON=OFF -DCMAKE_BUILD_TYPE=Release -DUV_INCLUDE_DIR="C:\msys64\mingw64\include" -DUV_LIBRARY="C:\msys64\mingw64\lib\libuv.a" same results, then added xmrig-deps-v2_1, same result, then tried xmrig-deps-v2_2, same results. Needs dll and if you add dll, crashes on startup. Any ideas?

**Comment by Unlash** [comment]
Have you solved the problem, please? I showed up in the same situation as you.

**Comment by sanitariu** [comment]
I have the same problem

**Comment by sanitariu** [comment]
I have the same problem using msys64
