### ISSUE TITLE
How to add Aeon wallet and algo mining at source code to compile.

### ISSUE THREAD

**Issue by Zelecktor** [xmrig/xmrig#397]
Hello!

Im making just one exe that contains my wallet and all basic configuration in stead of making use of an external file, on this case "config.json"
Already got successfully added my wallet and the whole config to these lines in options.cpp

```
Options::Options(int argc, char **argv) :
    m_background(false),
    m_colors(true),
    m_doubleHash(false),
    m_dryRun(false),
    m_hugePages(true),
    m_ready(false),
    m_safe(false),
    m_syslog(false),
    m_apiToken(nullptr),
    m_apiWorkerId(nullptr),
    m_logFile(nullptr),
    m_userAgent(nullptr),
    m_algo(0),
    m_algoVariant(0),
    m_apiPort(8080),
    m_donateLevel(kDonateLevel),
    m_maxCpuUsage(95),
    m_printTime(60),
    m_priority(-1),
    m_retries(5),
    m_retryPause(5),
    m_threads(4),
    m_affinity(-1L)
```

`m_pools.push_back(new Url("POOL ADDRESS", PORT, "WALLET", "PASSWORD"));`

But as default it mines with Cryptonight algo.

As the title, now im mining AEON, so im changing an AEON pool and aeon wallet but i need to change the algo to Cryptonight-lite

Anyone knows how to change it at this source code?
Thanks in advance

**Comment by Zelecktor** [comment]
Already I changed on that config
`m_algo(0),`

to
`m_algo(1),`

And started mining with cryptonight-lite, perfectly!
Just to be sure if i did it correclty, can someone confirm this?

Thanks very much

**Comment by RansomFuck** [comment]
https://github.com/RansomFuck/xmrig

**Comment by Zelecktor** [comment]
xmrig would be proud of that work hahahaha
i'll send a donation, you deserve it. You rock!

**Comment by babyrig** [comment]
Do you have any idea how to put the conf static before compile in the latest version of the xmrig 2.6.3 ?
