### ISSUE TITLE
windows rebuild

### ISSUE THREAD

**Issue by PQFitz** [xmrig/xmrig#4]
Hi Bro,
I was in trouble when compiling

Configure options for libcurl:
$ ./configure --disable-shared --enable-optimize --enable-threaded-resolver --disable-libcurl-option --disable-ares --disable-rt --disable-ftp --disable-file --disable-ldap --disable-ldaps --disable-rtsp --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --disable-manual --disable-ipv6 --disable-sspi --disable-crypto-auth --disable-ntlm-wb --disable-tls-srp --disable-unix-sockets --without-zlib --without-winssl --without-ssl --without-libssh2 --without-nghttp2 --disable-cookies --without-ca-bundle --without-librtmp
bash: ./configure: No such file or directory

Windows compiler can be more detailed? thank you !

**Comment by esfomeado** [comment]
Have you installed MSYS2 with the required packages?
Then just download curl:
https://curl.haxx.se/download/curl-7.54.0.zip

And execute that command followed by
make
make install

**Comment by PQFitz** [comment]
build xmrig
1120KB

why?
you upload release 400kb?
thank you

**Comment by xmrig** [comment]
@PQFitz just run `strip xmrig.exe`. Thank you.

**Comment by Hector555** [comment]
Can someone please make a "total noob tutorial- how to build miner" , please ?

**Comment by androspotter** [comment]
@Hector555 @xmrig I would love to ! I m on Windows7 , tried to build with Mingw and failed for missing libuv
I need just a quick start guide : "What to install" with a list of links please !

**Comment by JKLHJ** [comment]
@androspotter me too. please

**Comment by JKLHJ** [comment]
@Hector555 how to use VS2015 bulid？
