### ISSUE TITLE
Crash on close

### ISSUE THREAD

**Issue by BiTOk** [xmrig/xmrig#40]
I get segfault on xmrig close on linux with gcc 7.1.1. I tried 2.0.2 and 2.1.0-dev#e00c568ae xmrig versions.
In console:
SEGINT received, exiting
no active pools, pause mining
SEGFAULT

**Comment by xmrig** [comment]
Thank you, I know, working on it.

**Comment by xmrig** [comment]
I fixed crash, please verify.

**Comment by BiTOk** [comment]
@xmrig It looks good, thank you for fix.
