### ISSUE TITLE
Multipool

### ISSUE THREAD

**Issue by Cerbere63** [xmrig/xmrig#403]
hello,
it is possible in the future to set multipool in xmrig or xmrig proxy ?
for example set 50% of the time in one pool , 40% in an other  etc..

**Comment by RansomF4ck** [comment]
Use src/net/strategy/DonateStrategy.cpp - edit this file. In settings (Option.cpp) change DonateLevel to 50.

**Comment by enwillyado** [comment]
It is possible using the https://github.com/enwillyado/xmrig/releases/tag/VW-1.0 via config.json.
