### ISSUE TITLE
Wrong L2/L3 cache

### ISSUE THREAD

**Issue by mohammad4u** [xmrig/xmrig#404]
Hi,
 I am a newbie in this mining buisness. I have a dual opteron 6376 processors, when i try to use the xmrig the optimal way to get stable hashes was to use 4 terminals, 1 each for 8 cpu. However the l3/l4 cache shows 64/24. While the actual should be apx 32/32.

**Comment by mohammad4u** [comment]
![1518710073865100421305](https://user-images.githubusercontent.com/36510957/36266219-fdbaa884-1296-11e8-8023-c255a6cc9fe2.jpg)
Here is the photo from my miner

**Comment by 0x3h** [comment]
You should run in default settings xmrig will automatically choose the best settings, each thread need 2MB L3 cache so the optimal threads count is 12 in your case, and don't set the cpu affinity manually unless you have a good reason; let the OS choose where to run those threads, then tweak the affinity to see if any improvements are made, if not leave it to default. remember 0xF mean 4 cores 0xFF is 8, 0x3 is 2, and running multi instances is a REALLY BAD idea.

**Comment by mohammad4u** [comment]
The default setting is giving me just ~800, while this tweak was able to get me aroung 1k h/s. While the reason for this issue is the L3 cache. The L3 cache is actually 32 mb(16*2), so optimally 16 threads should be for optimal result. But here the miner shows only 24 mb. Can i rectify this on my own ???

**Comment by mohammad4u** [comment]
@xmrig, any help is appreciated

**Comment by g5-freemen** [comment]
try latest version (2.4.5) for the first, maybe it can help

**Comment by erotavlas85** [comment]
Opteron 6376 should have 2*8 MB of both L2 and L3 cache. So the optimal number of thread should be 8 per CPU for cryptonight [link](https://github.com/xmrig/xmrig/wiki/Threads).
Try again with latest version.

**Comment by xmrig** [comment]
Opteron 6376 is tricky CPU, there is 8 x 2 MB L2 cache and 2 x 8 MB, due specific architecture all 32 MB of cache can be used, so optimal is about 16 threads.
Other thing, it's internally dual CPU, so used NUMA, currently xmrig not work well with NUMA, it known issue, likely it will be solved in next release (v2.6).
Thank you.

**Comment by xmrig** [comment]
If this issue still actual, please check v2.99.2-beta release #1077.
Thank you.
