### ISSUE TITLE
Doubt hard fork

### ISSUE THREAD

**Issue by minerteam** [xmrig/xmrig#408]
I have read that there is going to be a change in the cryptonight algorithm. Does it mean that a new version of xmrig will have to be changed? What happens if I continue using a previous one to the hard fork?

**Comment by xmrig** [comment]
https://github.com/monero-project/monero/pull/3253 pull request with PoW change still not merged ant potentially has undefined side effects. But if PoW change will happen, I will need make changes too, so all users will need use new version to continue mine Monero. Old versions anyway can continue works with other cryptonight coins without changes.
Thank you,

**Comment by minerteam** [comment]
From what I have read in the link of the project it would be very fast to make the change in March. I have also read in other sites that this hard fork will forge monero (xmr) creating monerov (xmv), but in official threads I have not read anything about it, so it is scam?

**Comment by xmrig** [comment]
Monero hard fork happens every 6 mouth, but better call it major update and it was not affect miners, so upcoming March update can be first with that requirement. Current monero network is v6, March update will be v7.

xmv it different kind it's real fork, like Bitcoin Cash, it may be scam or not, unclear at this moment.
Thank you.

**Comment by minerteam** [comment]
In only 20 days the bifurcation monerov (xmv) will be produced and my momero (xmr) will be automatically converted to xmv, right?
If you do not know if it is a scam, how can I avoid the conversion?
Thank you

**Comment by xmrig** [comment]
You can't stop they, but you can ignore xmv, don't use your xmr private keys for xmv.

**Comment by minerteam** [comment]
I understand.
Thank you

**Comment by xmrig** [comment]
New Monero PoW implemented in version 2.5. More details #434
