### ISSUE TITLE
nicehash and minergate

### ISSUE THREAD

**Issue by walruzperil** [xmrig/xmrig#41]
Hello, i try connect to: 
nicehash - xmring say 50h/s and cpu usage 90%, but on website nicehash -workers:0 (xmrig -o stratum+tcp://cryptonight.eu.nicehash.com:3355 -u 35zDPhc7Uz3qKmkfoGQELoq6rMAFDVqtC7 -p x -t 4)

minergate - xmring say n/a h/s (xmrig -o stratum+tcp://xmr.pool.minergate.com:45560 -u email@gmail.com -p x -t 4)
what i do wrong?

**Comment by walruzperil** [comment]
upd: works on nicehas, but I can not understand why there are share for so long ..
minergate still not work..

**Comment by xmrig** [comment]
Nicehash diff to high for slow miners, I check now it give me 40000 diff, it can take a while (depends of luck) before share accepted.

Strange should work did you see messages like `use pool xmr.pool.minergate.com:45560` and `new job from xmr.pool.minergate.com:45560`?

Also what your CPU 50 h/s for 4 threads does not sound right.
Thank you.

**Comment by walruzperil** [comment]
minergate now works, i thing this was local problems. Thank you

**Comment by leovarmak** [comment]
@walruzperil Never use minergate. They scam.
