### ISSUE TITLE
logs are not working

### ISSUE THREAD

**Issue by fireheadman** [xmrig/xmrig#410]
OSX version, 
miner is running on macmini.   The log gets 1 line of input and stops logging.

Trying to use `tail -f <logfile>`

```
[fireheadman@hostname logs]$ tail -f monero.log
[2018-02-22 01:44:22] speed 2.5s/60s/15m 43.5 43.7 n/a H/s max: 45.6 H/s
00

ity=0x5
64 AES-NI
```

**Comment by enwillyado** [comment]
A standard implementation using std iostream are implemented in:
https://github.com/enwillyado/xmrig/commit/86f0d9d944b99eb1fd20a4e4be32a92388450e90#diff-fe21862032a22a919410f85011c2fe73
