### ISSUE TITLE
Ryzen 2400G 

### ISSUE THREAD

**Issue by yangsystem** [xmrig/xmrig#413]
I am unable to mine with the GPU. If I start xmrig-amd system crushes after 5 seconds.
I have all latest drivers from amd website. video chip is vega11.

**Comment by g5-freemen** [comment]
try diffent miner, use Nicehash miner legacy for example just to check which miners can work with your GPU

**Comment by xmrig** [comment]
This CPU bad choice for CPU and/or GPU mining, low amount of CPU cache, blue screen of death with high intensity, recent versions of xmrig-amd skip this GPU from autoconfig.
