### ISSUE TITLE
--max-cpu-usage=N

### ISSUE THREAD

**Issue by walruzperil** [xmrig/xmrig#42]
Hello, can you explain how works --max-cpu-usage=N 
if i set --max-cpu-usage=10 it mean cpu load only 10%?

**Comment by xmrig** [comment]
This option limit number of threads can be used in automatic mode. Has no effect if you manually specify thread count.

Some examples for 4C CPU:
* 75% = 3 threads
* 50% = 2 threads.
* 25% = 1 thread.
* 10% = 1 thread too, CPU usage about 25%.
