### ISSUE TITLE
unauthenticated Error

### ISSUE THREAD

**Issue by foadrm** [xmrig/xmrig#420]
Hi dear , i have a problem, in mining ETN from spacepools i get a unauthenticated error and show this message “ rejected , unauthenticated,no active pools stop mining, this error show on programs every about 7 minutes, how can i resolve it?

**Comment by foadrm** [comment]
I checked from two PCs with separate Rig ID and with diffrence difficulty

**Comment by xmrig** [comment]
`Unauthenticated` it's error message from pool, happens when pool forgot about miner after some time without shares, but usually timeout for this is more than 1 hour. Probably some pool issue.
Thank you.

**Comment by foadrm** [comment]
I checked with 2 or 3 pools and get this error in all,thank you , i will check from another pool
