### ISSUE TITLE
xmrig-2.4.4-gcc-win64 dual xeon e5-2679 40core/80threads

### ISSUE THREAD

**Issue by mzik91** [xmrig/xmrig#423]
👋 hello to all, I tried to start the mines with autoconfiguration, it works only a 50% processor (only 20core physical of one, the other 20 threads 0%) i use the graphics cards with nicehash, but the program does not support. can anyone help me with the configuration?

**Comment by g5-freemen** [comment]
"algo": "cryptonight",
"av": 0,
"background": false,
"colors": true,
"cpu-affinity": null,
"cpu-priority": null,
"donate-level": 5,
"log-file": null,
"max-cpu-usage": 100,
"print-time": 60,
"retries": 5,
"retry-pause": 5,
"safe": false,
"syslog": false,
"threads": 20,

try this and you can experiment with "threads", can try to set it to 40, but i think you get performance loss.
also you can try HODL algorithm with hodlminer-avx2, but it's really heavy for CPU

**Comment by mzik91** [comment]
Thanks, i try your config, if i change only "threads" hs drops to 750 to 500..it's not stable, with default value it's stable to 750/770..I think we need to change cpu affinity or cpu priority, but i don't know how..

**Comment by g5-freemen** [comment]
Cpu priority doesn't important I think

**Comment by g5-freemen** [comment]
And really read about HODL, nicehash server shows that it is most profitable cpu algorithm

**Comment by mzik91** [comment]
I'm trying hodl optimized, uses only one processor, but uses the ht (20core + 20threads) 1700hs..any idea to make the second work?

**Comment by grafptitsyn** [comment]
@mzik91 try next:
A)
```
"cpu-affinity": "0xFFFFFF80010000000000"
"cpu-priority": 5
"threads": null
```
B)
```
"cpu-affinity": "0xFFFFF000010000000000"
"cpu-priority": 5
"threads": null
```

Variant A uses 25 threads (20 physical and 5 virtual), because your CPU has L3 50MB, so 25 threads can be used theoretically. But HT can slow down your total hash rate, then try Variant B.

**Comment by rtau** [comment]
In addition to that mentioned by grafptitsyn, you may try using the low power algorithm variant (-av 2), and use only 12 threads.

In low power variants, each thread will require double amount of cache, but will have a higher hash rate per thread.

**Comment by mzik91** [comment]
thanks for help me, I tried to change cpu affinity copying and pasting both code, I put null in threads. uses 25threads of a single CPU. hs remains the same as before (but when I launch xmr, is it normal that the "huge page" is unavailable?)

**Comment by grafptitsyn** [comment]
@mzik91 no, it's not normal if you enabled it.

**Comment by g5-freemen** [comment]
Huge page requires reboot system to enable

**Comment by mzik91** [comment]
I have enabled a huge page, now the HS is 950. but the operation of the processor is the same ... boh I have no other ideas ..

**Comment by grafptitsyn** [comment]
@mzik91 "the operation of the processor is the same" - what do you mean?

**Comment by mzik91** [comment]
Windows 10 64bit...(sorry i''m italian) the processor work with 25threads

**Comment by grafptitsyn** [comment]
@mzik91 
1) "cpu-affinity": "0xAAAAAAAAAAAAA8000000"
2) In case of NUMA nodes check #86

**Comment by jamieturnough** [comment]
Not sure if it will help, but I'm running dual Xeon 8176 ES chips (28core each, but ES chips reduced to 1800-2200mhz with turbo). 
Setting the threads to 28 gives me around 1140 h/s. but I run at 26 and 80% power so I can still use the machine, which reduces down to around 1040 each.

To get both CPU's running I have to run 2 instances of XMRIG, which brings my combined hashrate up to 2000-2200 h/s depending on other loading.

**Comment by xmrig** [comment]
If this issue still actual, please check v2.99.2-beta release #1077.
Thank you.
