### ISSUE TITLE
xmr-stak copyright notice

### ISSUE THREAD

**Issue by fireice-uk** [xmrig/xmrig#425]
Can you please add our copyright notice to your list in places where you use our code?

Don't worry I won't do frivolous DMCA takedowns  ;)

**Comment by xmrig** [comment]
```
Copyright 2017-2018 XMR-Stak    <https://github.com/fireice-uk>, <https://github.com/psychocrypt>`
```
Line above, added to every h/cpp/cu/cl file with yours code, looks good?

* 2017 is year of first commit in xmr-stak-cpu repository.
* I think links to github profiles is good, because yours emails is not public.

Thank you.

**Comment by fireice-uk** [comment]
Yes, that's more than enough. Thanks!

**Comment by xmrig** [comment]
Done.
