### ISSUE TITLE
Wrong CPU L2 cache size detection

### ISSUE THREAD

**Issue by VSergey** [xmrig/xmrig#428]
Before in version 2.4.4 size detection is right
* VERSIONS:     XMRig/2.4.4 libuv/1.18.0 MSVC/2017
 * HUGE PAGES:   available, enabled
 * CPU:          Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (1) x64 AES-NI
 * CPU L2/L3:    1.5 MB/12.0 MB

Current version is wrong
* VERSIONS:     XMRig/2.4.5 libuv/1.19.0 MSVC/2017
 * HUGE PAGES:   available, enabled
 * CPU:          Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (1) x64 AES-NI
 * CPU L2/L3:    0.8 MB/12.0 MB

CPU-Z utility show L2 cache as 6x256 KBytes
![image](https://user-images.githubusercontent.com/4030018/36939456-7a69841a-1f42-11e8-9fa0-3b742a710bb3.png)

**Comment by xmrig** [comment]
@Foudge looks like cache fix need be fixed again, same family and model with older CPUs.
Thank you.

**Comment by Foudge** [comment]
Maybe just check CPU have no L3 to be sure that all Core i3/5/7 not touched by the fix.
I will see that closer.

**Comment by Foudge** [comment]
@xmrig It should be ok with this commit : https://github.com/Foudge/xmrig/commit/b95041710c1f639ec7af53b7078fb96660a9cf9c
You can graft it in your repository ?

**Comment by 2010phenix** [comment]
@Foudge it can be problem with VMware things... most of all "don't have" L3

**Comment by 2010phenix** [comment]
@Foudge it can be problem with VMware VDS things.. most of them "don't have" L3

**Comment by 2010phenix** [comment]
PS @Foudge maybe find some useful hint in hwloc integration made by sebastianstolzenberg in: https://github.com/Bendr0id/xmrigCC/pull/24/commits/f05ee0d9e7b1d3d2756b6926cda448a1ed30b4d6

**Comment by Foudge** [comment]
@2010phenix See my comment commit, I use now **ext_**family and **ext_**model, what I should have done from the beginning. Those ext versions were added because all values were already used with family and model (only 4 bits!), so they extend them to 8 bits.

But this current bug has no impact at all : the only important cache information is LLC (last level cache), so L2 or L3 depending on the processor, because it's used to calculate the number of thread in automatic mode. And to have best results, it's recommended to set number of threads and cpu affinity.

**Comment by xmrig** [comment]
@Foudge thank you, added your changes.
@VSergey @2010phenix Anyway for this issue (modern CPUs) as mentioned above, it just cosmetic, no negative impact.

**Comment by xmrig** [comment]
Fixed in v2.5.0.

**Comment by snipeTR** [comment]
this v2.4.3 **right CPU** info.: https://prnt.sc/j0z2t4
![indir](https://user-images.githubusercontent.com/31975916/38336992-70994194-386c-11e8-986b-9feb27ef6e9e.png)

this v2.5.2 **wrong CPU** info: https://prnt.sc/j0z2zn
![indir 1](https://user-images.githubusercontent.com/31975916/38337007-772593f0-386c-11e8-9eea-2c3e427b2fc5.png)

this v2.6.0 **wrong CPU** info: https://prnt.sc/j0z34l
![indir 2](https://user-images.githubusercontent.com/31975916/38337012-7bec8808-386c-11e8-82ee-560b66f5823e.png)

**Comment by Foudge** [comment]
The C2D E7400 has 3MB L2 cache ;)
https://ark.intel.com/fr/products/36500/Intel-Core2-Duo-Processor-E7400-3M-Cache-2_80-GHz-1066-MHz-FSB

**Comment by snipeTR** [comment]
OK. but the old version gives 25 h / s. It gives 14 h / s including 2.6 version.

**Comment by snipeTR** [comment]
Automatic thread detection not working

**Comment by snipeTR** [comment]
Is not the "thread" parameter automatic?

**Comment by snipeTR** [comment]
yes 32bit windows and not a auto threads count. please help

**Comment by Foudge** [comment]
I don't understand. You use command line or config file ?
-  Command line: add `--threads=2`
- config.json file : replace `"threads": null` by `"threads": 2` (if `null`, automatic mode is used)
