### ISSUE TITLE
error: ‘uv_loop_close’ was not declared in this scope      uv_loop_close(uv_default_loop());

### ISSUE THREAD

**Issue by Liddll** [xmrig/xmrig#43]
make get fail - I have no idea what is wrong :(

[  2%] Building C object src/3rdparty/jansson/CMakeFiles/jansson.dir/memory.c.o
[  4%] Building C object src/3rdparty/jansson/CMakeFiles/jansson.dir/dump.c.o
[  6%] Building C object src/3rdparty/jansson/CMakeFiles/jansson.dir/value.c.o
[  8%] Building C object src/3rdparty/jansson/CMakeFiles/jansson.dir/utf.c.o
[ 10%] Building C object src/3rdparty/jansson/CMakeFiles/jansson.dir/pack_unpack.c.o
[ 12%] Building C object src/3rdparty/jansson/CMakeFiles/jansson.dir/error.c.o
[ 14%] Building C object src/3rdparty/jansson/CMakeFiles/jansson.dir/hashtable_seed.c.o
[ 16%] Building C object src/3rdparty/jansson/CMakeFiles/jansson.dir/hashtable.c.o
[ 18%] Building C object src/3rdparty/jansson/CMakeFiles/jansson.dir/strconv.c.o
[ 20%] Building C object src/3rdparty/jansson/CMakeFiles/jansson.dir/strbuffer.c.o
[ 22%] Building C object src/3rdparty/jansson/CMakeFiles/jansson.dir/load.c.o
Linking C static library libjansson.a
[ 22%] Built target jansson
[ 24%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
[ 26%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/asm-bits.c.o
[ 28%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_amd.c.o
[ 30%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_intel.c.o
[ 32%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/libcpuid_util.c.o
Linking C static library libcpuid.a
[ 32%] Built target cpuid
[ 34%] Building CXX object CMakeFiles/xmrig.dir/src/App.cpp.o
/root/xmrig/src/App.cpp: In member function ‘int App::exec()’:
/root/xmrig/src/App.cpp:113:5: error: ‘uv_loop_close’ was not declared in this scope
     uv_loop_close(uv_default_loop());
     ^~~~~~~~~~~~~
/root/xmrig/src/App.cpp:113:5: note: suggested alternative: ‘uv_fs_close’
     uv_loop_close(uv_default_loop());
     ^~~~~~~~~~~~~
     uv_fs_close
make[2]: *** [CMakeFiles/xmrig.dir/src/App.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/xmrig.dir/all] Fehler 2
make: *** [all] Fehler 2

**Comment by jpascal** [comment]
+1

**Comment by xmrig** [comment]
What libuv version do you use? only version 1 supported, minimum tested version is 1.8.0.
Thank you.

**Comment by jpascal** [comment]
I try build version from github. And all build success!
