### ISSUE TITLE
Academic purposes

### ISSUE THREAD

**Issue by yangsystem** [xmrig/xmrig#430]
Hello guys.
Can someone help me with the crypto algorithm.
I want to make a paper in witch I want to explain step by step how this algorithm works.
Can you point me to some doc's or maybe make me a diagram with step by step implementation.

Something like:
1. packet to work with size 128Kb 
2. apply formula
3.  result 010101d11a...

something like this a step by step procedure so I can explain to other and play with calculations on paper.
I don't need all the sophisticated codes you use for detecting CPU/GPU comunications with pools and all other things.

10Q.

**Comment by 2010phenix** [comment]
google help you answer to all your question. 
THIS IS ISSUE tracker
