### ISSUE TITLE
DNS error

### ISSUE THREAD

**Issue by bay1ts** [xmrig/xmrig#431]
DNS error: "unknown node or service",using pool pool.minexmr.com:7777.  Any suggestion?

**Comment by bay1ts** [comment]
sometimes it may be: connect error: "connection timed out"

**Comment by xmrig** [comment]
Your ISP may block connection to pool. For DNS errors, check `ping pool.minexmr.com` or `nslookup pool.minexmr.com` if IP can't resolved, miner can't work too.

You can try use one of IP address of pool:
```
          94.130.164.60
          188.165.199.78
          176.9.50.126
          94.130.206.79
          94.23.212.204
          37.59.44.93
          91.121.87.10
          94.23.41.130
          78.46.91.134
          78.46.89.102
          37.59.45.174
          178.63.48.196
          176.31.117.82
          176.9.63.166
          176.9.53.68
          188.165.214.95
          37.59.54.205
          37.59.44.193
          91.121.2.76
          37.59.43.136
```

**Comment by bay1ts** [comment]
That is not good.thanks for your work
