### ISSUE TITLE
Idle/dynamic mining

### ISSUE THREAD

**Issue by wilburforce666** [xmrig/xmrig#432]
Does this support idle/dynamic mining?

**Comment by wilburforce666** [comment]
If so how?

**Comment by dunklesToast** [comment]
What do you mean with this?
That the Miner pauses when you use your PC and continues when you do not use it or the CPU has many resources free? If you mean that take a look at #141

**Comment by wilburforce666** [comment]
Yes that is what I mean. That task schudele thing that was linked. How could I implement it into a silent miner?

**Comment by grafptitsyn** [comment]
@wilburforce666 why don't use task priority? Linux has `nice`, Windows has `start`. Give the lower priority to miner, and that's a deal.

**Comment by xmrig** [comment]
Duplicate #141
