### ISSUE TITLE
Monero v7 PoW change status

### ISSUE THREAD

**Issue by xmrig** [xmrig/xmrig#434]
Monero will [change PoW](https://getmonero.org/2018/02/11/PoW-change-and-key-reuse.html) on April 6, that means Monero `cryptonight` will not compatible with other `cryptonight` based coins. Also small hashrate drop expected.

**You will require update miners to continue mine Monero.** As soon as version 2.5 released you can update miners don't need do it on April 6, new version fully compatible with current Monero network.

New miner also can be continue use with other `cryptonight` coins without changes, I checked `ETN`, `SUMO` and `ITNS`. If you get compatible issues please report it, also you have 2 ways to disable new algorithm:

1. Use new option `"variant": 0` or `--variant 0` on each pool. Example:
```json
        {
            "url": "YOUR_POOL:3333",
            "user": "YOUR_WALLET",
            "pass": "x",
            "keepalive": true,
            "nicehash": false,
            "variant": 0
        },
```
2. Use [xmrig-proxy](https://github.com/xmrig/xmrig-proxy) to override `variant` option, in proxy config for each pool set `variant` option. This option will be supported in proxy v2.5, this version currently available in [dev](https://github.com/xmrig/xmrig-proxy/tree/dev) branch. Example:
```json
        {
            "url": "YOUR_POOL:3333",
            "user": "YOUR_WALLET",
            "pass": "x",
            "coin": "SUMO",
            "variant": 0
        },
```

####  Current progress:
- [x] Implement changes in [xmrig](https://github.com/xmrig/xmrig/commits/dev).
  - [x] AEON.
- [x] Implement changes in [xmrig-amd](https://github.com/xmrig/xmrig-amd/commits/dev).
  - [x] AEON.
- [x] Implement changes in [xmrig-nvidia](https://github.com/xmrig/xmrig-nvidia/commits/dev).
  - [x] AEON.
- [x] Implement changes in [classic xmrig](https://github.com/xmrig/xmrig/commits/classic) (C version).
- [x] Add new options to https://config.xmrig.com
- [x] Release v2.5
- [x] Proxy release v2.5

**Comment by Umiiii** [comment]
Is that means when I use xmrig and xmrig-proxy v2.5 before March 28 and it will automatically changed its mining strategy when March 28 Monero hard fork come and after that?

**Comment by xmrig** [comment]
That right, xmrig v2.5 will work before and after hard fork without changes, algorithm will change automatically no need do anything. Actually proxy update is not mandatory, old version continue work, but in v2.5 many new features added.
Thank you.

**Comment by 2010phenix** [comment]
and that all be nice.... i think need some love and to classic C miner too ;)

**Comment by xmrig** [comment]
Added classic miner to checklist.
Thank you.

**Comment by xmrig** [comment]
Monero v7 implemented in all miners (in dev branches currently) and in classic C miner (classic branch).

**Comment by xmrig** [comment]
Release delayed, AEON will change PoW too https://github.com/xmrig/xmrig/pull/426
Thank you.

**Comment by xmrig** [comment]
Instead of option `monero` will be added more flexible option `variant`.
Possible values:
 - `-1`  Autodetect, should work fine with Monero, AEON and others coins until their network not updated to v7. Used by default.
- `0` Force use original  `cryptonight` algorithm.
- `1` Force use new Monero v1 PoW.

Please note, this option applied on each pool separately. When use xmrig-proxy, miner can switch between `0` and `1` on each job.

**Comment by tarris034** [comment]
How often will the new version check which algo to use ? on every work ? what will be the overhead of this checking procedure ? will it have impact on the hashrate ?

**Comment by xmrig** [comment]
Depends of miner, on each platform checking is different, but overhead for this is near zero. When use old algorithm hashrate should be same as before. But new algorithm itself is a few % slower.
Thank you.

**Comment by jsonnentag** [comment]
Will mining for MoneroV option be added as well?

**Comment by xmrig** [comment]
I don't know what will be use MoneroV, it they will use new PoW with same version with Monero, anything should work fine.
Thank you.

**Comment by xmrig** [comment]
[GRAFT](https://www.graft.network/) already use v7 network, but original algorithm, so you must use option `"variant": 0` on each GRAFT pool. Algorithm detection will not work on this coin.

Example:
```json
{
    "url": "pool.graft.hashvault.pro:7777",
    "user": "WALLET_ADDRESS",
    "pass": "x",
    "keepalive": true,
    "nicehash": false,
    "variant": 0
},
```

**Comment by serisman** [comment]
Can you build/push a new version of your docker image (https://hub.docker.com/r/xmrig/xmrig/) that contains these changes?

**Comment by xmrig** [comment]
It not my docker image, I not related to https://hub.docker.com/r/xmrig/ in any way.
Thank you.

**Comment by serisman** [comment]
Interesting.  Thanks for the reply.  I assumed it was yours based on the name.  I'll look around for a suitable replacement or create one.

**Comment by sebseb7** [comment]
it there a v7 testpool already?

**Comment by xmrig** [comment]
http://killallasics.moneroworld.com/

**Comment by sebseb7** [comment]
and is there a testnet with v7 also?

**Comment by sterkederk** [comment]
On testpool mining works, but my hashrate dropped by half?

**Comment by xmrig** [comment]
@sebseb7 Not sure, latest Monero daemon was use v8 when I last check it, mentioned pool use v7.
@sterkederk Please open separated issue with proper details about your hardware, old and new hashrate.
Thank you.

**Comment by oliverw** [comment]
@xmrig May I ask where you got the information about the necessary changes to the PoW algorithm to support V7?

**Comment by oliverw** [comment]
@xmrig Thanks a lot!

**Comment by 2010phenix** [comment]
@xmrig thx for some love to classic one...
 Implement changes in classic xmrig (C version).

they to have autodetect V7 version already or only first version support from Mar 11?

**Comment by xmrig** [comment]
Since this commit https://github.com/xmrig/xmrig/commit/33944595a2049427a5f19d18e1a475485727d927 V7 supported, autodetect work too.

**Comment by guigeddos** [comment]
@xmrig  Why some of them have 2 CPU. Xmrig can only recognize and read 1 CPU. How to solve this. Stak mining tools can be identified. But xmrig can't recognize it. There are a lot of problems. Is there a way to solve it

**Comment by nssy** [comment]
Works fine for me on the testpool. No noticeable change in Hash Rate. Thanks for patching things up early.

**Comment by 2010phenix** [comment]
@guigeddos i think it can be next to fix... look on https://github.com/xmrig/xmrig/issues/86

@xmrig thx, add by hands in few day and try to check

**Comment by guigeddos** [comment]
![tim 20180316221500](https://user-images.githubusercontent.com/35347058/37525610-4f35c90e-2968-11e8-9fd5-a0d84f6607ed.png)
@xmrig  2.5.0   This is the case? What's the matter

**Comment by xmrig** [comment]
@guigeddos such errors can happen by a lot of reasons, includes troubles with pool. Not issue in this case.
Thank you.

**Comment by SQZSoft** [comment]
Is that possible to include binary file in the new release for both armv7 and armv8? (rep to 32bit and 64bit)

**Comment by xmrig** [comment]
Binary ARM build is complicated, different platforms and many different hardware especially for ARMv7, build from source for target platform is not too hard.
Thank you.

**Comment by xmrig** [comment]
https://github.com/monero-project/monero/pull/3424 PoW change delayed to around April 6.
Thank you.

**Comment by xmrig** [comment]
I close this issue, use #482 for future details.
Thank you.

**Comment by xmrig** [comment]
If you have plans to mine Monero or other coins in list #482 you should update miner.
Thank you.

**Comment by svoutlokk** [comment]
qual versão do Xmring esta atualizado com a versão cryptonightv7?

**Comment by globeone** [comment]
The current master is still 2.4 and many pools are demanding 2.5 because of this bug report. would it be possible to please edit the bug report to say 2.4 as this change was already performed in 2.3
![schermafdruk van 2018-08-20 00-46-38](https://user-images.githubusercontent.com/10052587/44313990-90c50e00-a412-11e8-9c39-96d5c83bcc5b.png)

**Comment by xmrig** [comment]
@globeone but current master is v2.6.4 https://github.com/xmrig/xmrig/blob/master/src/version.h#L30
Thank you.
