### ISSUE TITLE
Change Console to Windows

### ISSUE THREAD

**Issue by MaxMarkMuster** [xmrig/xmrig#443]
I'm trying to stop the console pop up.
I changed >Linker >System >SubSystem from Console to Windows and get the following error.

- Error LNK2001	unresolved external symbol   WinMain xmrig   C:\xmrig-master\build\LIBCMT.lib(exe_winmain.obj)	1	

- Error LNK1120 1 unresolved externals	xmrig  C:\xmrig-master\build\Release\xmrig.exe	1

Any ideas on how to resolve this. Thanks.

**Comment by Virinom** [comment]
What about using hidden option included in xmrig?

**Comment by MaxMarkMuster** [comment]
That works, but it blinks on start up. I would like to make it less noticeable. Thanks for helping though.

**Comment by xmrig** [comment]
Equivalent for this:
`Linker >System >SubSystem from Console to Windows` is add `WIN32` after xmrig https://github.com/xmrig/xmrig/blob/master/CMakeLists.txt#L213 but if you use MSVC you need also change entry point.
Thank you.

**Comment by xmrig** [comment]
Anyway it not a issue, I close it.
