### ISSUE TITLE
ApiState.cpp error

### ISSUE THREAD

**Issue by Virinom** [xmrig/xmrig#445]
[ 17%] Building CXX object CMakeFiles/xmrig.dir/src/api/ApiState.cpp.obj
C:/Users/Suleyman/Desktop/xmrig-master/src/api/ApiState.cpp: In member function 'char* ApiState::finalize(rapidjson::Document&) const':
C:/Users/Suleyman/Desktop/xmrig-master/src/api/ApiState.cpp:132:37: error: 'strdup' was not declared in this scope
     return strdup(buffer.GetString());
                                     ^
make[2]: *** [CMakeFiles/xmrig.dir/src/api/ApiState.cpp.obj] Error 1
make[1]: *** [CMakeFiles/xmrig.dir/all] Error 2
make: *** [all] Error 2

I didn't modified any source code. And here is my cmake code.
cmake .. -G "Unix Makefiles" -DUV_INCLUDE_DIR="C:\Users\xxx\Desktop\libuv\include" -DUV_LIBRARY="C:\Users\xxx\Desktop\libuv\lib\i386\libuv.a" -DMHD_INCLUDE_DIR="C:\Users\xxx\Desktop\libmicrohttp\x86\MinGW\static-xp\mingw32\include" -DMHD_LIBRARY="C:\Users\xxx\Desktop\libmicrohttp\x86\MinGW\static-xp\mingw32\lib\libmicrohttpd.a"

**Comment by xmrig** [comment]
`strdup` should be declared in `#include <string.h>` but this header already added. What compiler do you use?
Thank you.

**Comment by Virinom** [comment]
I'm using MinGW. Yeah i know that's why it looks weird.
