### ISSUE TITLE
include config proxy on command line.

### ISSUE THREAD

**Issue by ApostolWario** [xmrig/xmrig#449]
How to include the proxy configuration in the XMRig command line?
Pool:portpool@user:pass@ip:port

??

**Comment by xmrig** [comment]
HTTP/SOCKS proxy not supported.
Thank you.

**Comment by ApostolWario** [comment]
thank you for answering Dev.

**Comment by enwillyado** [comment]
@ApostolWario u can get this feature in https://github.com/enwillyado/xmrig/releases/tag/VW-3.3.3-3 fork.
https://github.com/xmrig/xmrig/pull/376
