### ISSUE TITLE
(LINUX CPU mining) HTTP Daemon failed to start

### ISSUE THREAD

**Issue by survivor303** [xmrig/xmrig#451]
When i start xmrig, first line is:
HTTP Daemon failed to start.
I dont find any documentation for this error, so what it is and can i just ignore it?

**Comment by xmrig** [comment]
This error means port used to HTTP API already used (most likely) or other error occurred. HTTP API disabled by default, so that means you already enable it by choice some port for it, until this error exists you can't use API. Mining functions not affected.
Thank you.
