### ISSUE TITLE
any problem I user xmrig 2.5.0 mine ETN and other cryptonight coin?

### ISSUE THREAD

**Issue by qqxiaochen** [xmrig/xmrig#452]
Hello，
if i user xmrig-2.5.0 to miner Etn，is there any problem when monero Change Monero V7。

**Comment by xmrig** [comment]
v2.5 supports ETN without any additional setup.
Thank you.

**Comment by pikomule** [comment]
From day 28, XMRIG will automatically change the algorithm or will we have to configure the "config.json" file?

Now (config.json): "algo": "cryptonight"
After 28?

thanks

**Comment by xmrig** [comment]
Don't need to change any settings or restart miner, new PoW will be detected automatically.
Thank you.

**Comment by pikomule** [comment]
thanks

**Comment by qqxiaochen** [comment]
thank you
