### ISSUE TITLE
(LINUX CPU mining)  /data/xmrig/src/api/Httpd.cpp: In member function ‘bool Httpd::start()’: /data/xmrig/src/api/Httpd.cpp:49:34: error: ‘MHD_FEATURE_EPOLL’ was not declared in this scope

### ISSUE THREAD

**Issue by asdj07** [xmrig/xmrig#454]

**Comment by xmrig** [comment]
Too old libmicrohttpd version, what Linux distro you use?
Thank you.

**Comment by asdj07** [comment]
/usr/lib64/libmicrohttpd.so.10.22.0
It's a   centos7  virtual machine，I need to update the libmicrohttpd ?

**Comment by xmrig** [comment]
You have 3 options:

- Update libmicrohttpd
- Build without libmicrohttpd `-DWITH_HTTPD=OFF` for `cmake`
- Make some quick fix to change this part of code, I will add version checks later.

**Comment by asdj07** [comment]
OK, Thank you

**Comment by gadingpideksa** [comment]
![er](https://user-images.githubusercontent.com/37467346/37552535-f7fdda32-29e9-11e8-9050-201cd163d0b6.PNG)
 how about this?

**Comment by xmrig** [comment]
Fixed. Epoll, IPv6 and feature checking was added in libmicrohttpd 0.9.35, CentOS shipped with 0.9.33.
Thank you.
