### ISSUE TITLE
Monero old and new algo on fly autoswitch question

### ISSUE THREAD

**Issue by bobbieltd** [xmrig/xmrig#455]
I have a question. For example, if a miner connect to a pool, for first 30 minutes the pool mines Electroneum so xmrig uses old algo for the miner, then the pool switches to Monero mining (after hard fork), will xmrig autoswitch to new algo without reconnection ?
This pool mines multiple coins.
Thanks.

**Comment by xmrig** [comment]
It will work fine, miner can switch PoW on every job.
Thank you.

**Comment by bobbieltd** [comment]
It’s great. Thank you.
