### ISSUE TITLE
duplicated job receiveed 

### ISSUE THREAD

**Issue by zhouzuoji** [xmrig/xmrig#459]
when using xmr.f2pool.com:13531, miner report "duplicated job receiveed, reconnect...", it can't work

**Comment by xmrig** [comment]
I confirm issue, pool really send duplicated jobs, first one in login response, second as regular notification, no one other pool do it in that way, but I little confused, previous versions should no work too, but works.
Thank you.

**Comment by xmrig** [comment]
Fixed, it will be included to next bugfix release v2.5.1.
Thank you.
