### ISSUE TITLE
-c, --config=FILE option doesn't work

### ISSUE THREAD

**Issue by vcambur** [xmrig/xmrig#46]
First of all thank you very much for such optimized miner
Do you plan to implement the option in subject ?

**Comment by xmrig** [comment]
In next release (2.2.0), actually I had plan to restore it in current release, but... delay it again)
Related #26
Thank you.

**Comment by xmrig** [comment]
Config support need rewritten it not just backport from C version, for example now possibly specify multiple --url options, in JSON it need wrap to array and add new option.
Maybe something like:
```json
{
"pools": [
    {
      "url": "pool1:3333",
      "user": "user1",
      "pass": "x",
      "keepalive": true,
      "nicehash": false
    },
    {
      "url": "pool2:5555",
      "user": "user2",
      "pass": "x",
      "keepalive": true,
      "nicehash": false
    }
  ]
}
```

**Comment by vcambur** [comment]
I see
yes this way it looks good

**Comment by xmrig** [comment]
Example config file https://github.com/xmrig/xmrig/blob/dev/src/config.json
Can load multiple config files and combine with command line options.
If no pool specified by command line options will try load config.json from directory with executable.

**Comment by vcambur** [comment]
Thanks, going to try from the dev branch
