### ISSUE TITLE
Can I modify the number of threads or maximum CPU usage without exiting?

### ISSUE THREAD

**Issue by webees** [xmrig/xmrig#464]
Hi, I hope the program will modify the number of threads during operation. Now I can only exit the program and reset the thread number and run. Thank you for your efforts. My Internet cafe running this software, but it should not affect the normal use of the computer, so i need to dynamically adjust the number of threads.

I tried App::close() and then recreated the thread to run, but it always went wrong.

**Comment by xmrig** [comment]
Dynamic config reload will be added in next release v2.6 if not something big like recent Monero PoW change happen again.
Thank you.

**Comment by jvds123** [comment]
love the idea, was just about to ask about the same but on max-cpu-usage
tumbs up

**Comment by webees** [comment]
@xmrig @jvds123 For example, when playing games (such as PUBG, LOL), the CPU reduces the usage rate because I don't want to affect my customers' normal use of public computers. With my current technical capabilities, I can only solve this problem by exiting the program or always maintaining a 25% usage rate to ensure the normal use of the user. I have 400 computers and I hope to further increase my computing power. We also hope that more donations will make this program better.
