### ISSUE TITLE
Error while compiling arm

### ISSUE THREAD

**Issue by JonyTester** [xmrig/xmrig#468]
Hi, only for fun I´m trying to compile your ARM branch for my Android but I have this error.. 

After executing cmake . -DWITH_HTTPD=OFF && make VERBOSE=1

I get this: 

usr/lib/clang/5.0.1/include/x86intrin.h:27:
/data/data/com.termux/files/usr/lib/clang/5.0.1/include/ia32intrin.h:48:10: error: use of undeclared identifier '__builtin_ia32_readeflags_u32'
  return __builtin_ia32_readeflags_u32();

Note: I´m not cross-compiling I´m compiling in the device using a termux terminal.

any clue of what is going on?

thanks in advance

**Comment by JonyTester** [comment]
Error fixed with the last update :-)

**Comment by hozachief** [comment]
I have a similar issue. I have an error that reads, "Use of undeclared identifier '__builtin_ia32_readeflags_u32'". @JonyTester would you mind elaborating how you solved this error?
