### ISSUE TITLE
Unstable hashrate

### ISSUE THREAD

**Issue by g5-freemen** [xmrig/xmrig#469]
Maybe somebody can help to understand why my hashrate usually around 300-330 h/s, but sometimes (1 run of 10 for example) it sets to 400-430 and works fine.

![xmrig1](https://user-images.githubusercontent.com/36886126/37738370-d2210cfe-2d67-11e8-8f50-d9601dc65ee4.png)

**Comment by Gill1000** [comment]
Sometimes, window start its background process ...that can be the cause of this.
