### ISSUE TITLE
Merged/ Dual Mining?

### ISSUE THREAD

**Issue by calvintam236** [xmrig/xmrig#47]
Is it too much to request that?

**Comment by xmrig** [comment]
Can you please provide more details as I know merged mining with Monero possible only with XDN/FCN. but looks like these coins controlled by Minergate (51% attack), community don't trust Minergate so these coins has no point. Correct me if I'm wrong.

**Comment by calvintam236** [comment]
I understand that. Even community doesn't trust them, they are still have tiny profit. I don't plan to keep those currencies. I would sell them right away.
As merged mining with them won't affect XMR hashrate, why not take advantage of their money?

**Comment by AnythingTechPro** [comment]
I agree completely, they generate free extra bit of money without effecting the overall hash rate of monero.

**Comment by rtau** [comment]
As far as I know, merged mining is more a setup of the pool which you use rather than a setting on the mining client. So, for example, if you use the pool of minergate then it would be possible to do merged mining already.

Please correct me if I'm wrong.

**Comment by Kukunin** [comment]
Dual mining is set on a pool's side in case of Monero. Contrary to the bitcoin's stratum, monero's one shares only a final blob with no extra information about blocks/transactions, thus a miner has no way to mix it with a different coin for the merged mining.
