### ISSUE TITLE
custom log file

### ISSUE THREAD

**Issue by mk148a** [xmrig/xmrig#470]
Hi, i want to custom log file.
i need only hashrate,but i dont need history only need now hashrate. I use 3rd party apps, this apps need read this log file but current log is not accessible always usable from xmrig

**Comment by djfinch** [comment]
1. (with API) Parse hashrate from API?
2. (without API) OS? If Linux/OSX/BSD - what about tail with watch? Last line of log, then pipe to awk with regex to extract hashrate?

**Comment by mk148a** [comment]
@djfinch how to use api for hashrate?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/wiki/API

**Comment by dunklesToast** [comment]
Hey!
A very simple Shell script which just returns the Hashrate:
`curl -s 'http://localhost:9090' | python -c "import sys, json; print json.load(sys.stdin)['hashrate']['total'][0]"`

Tested with:
- Python 2.7
- XMRIG API running at Port 9090

You could create a cron job which echos the Hashrate into a file:
`*/5 * * * * /path/to/script >> /path/to/your/log.txt`

**Comment by mk148a** [comment]
@xmrig  its not work for me i use this command line:
C:\Users\Murat\Desktop\safefolder>wupdate -a cryptonight-light -o stratum+tcp://
mine.aeon-pool.com:80 -u WmtxkwCXij3cEx6xU2t2teTpUQq6h8tdE7DoGKW9rPPrSK3pEsF7WTB
hFaaEttMUt9c61Em6dP1WeHkyDtyRgWf11Q6Qi2B1j -p x -l log --api-port=9999 --api-acc
ess-token=1234  --api-worker-id=hdtv

and i use http:://localhost:9999 but its not work on firefox

**Comment by djfinch** [comment]
API serving JSON, not webpage... (I suppose, not using it)

**Comment by dunklesToast** [comment]
@djfinch What do you mean with that? The API returns JSON which the little python script parses and prints

**Comment by djfinch** [comment]
Read his comment once again. He is on windows and trying to access api endpoint with firefox over http...
