### ISSUE TITLE
Linker error compiling on Windows (MSYS2)

### ISSUE THREAD

**Issue by Detuner** [xmrig/xmrig#471]
I'm past quite a few errors trying to compile on mingw64, can't figure out how to solve this:
`
[ 15%] Linking CXX executable xmrig
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lrt
`

**Comment by xmrig** [comment]
Something wrong with your MSYS2 instalation, `rt` used only on Linux, you can remove `rt` from this line https://github.com/xmrig/xmrig/blob/master/CMakeLists.txt#L140 but you likely get other errors.
Thank you.

**Comment by Detuner** [comment]
All right, it compiles now, was totally my fault. It's the first time I tried compiling something using MSYS2 and cmake. I accidentally installed 'cmake' instead of 'mingw-w64-x86_64-cmake', then ignored cmake telling me it cannot recognize platform, and then tried messing around with CMakeLists.txt to get it working :)
Thanks a lot!
