### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by plastkort** [xmrig/xmrig#472]
would love a nice solution on how to set a static config filename to the build setup so there is no need to modify the platform.cpp file on every new release. im keeping two miners in the same folder and config.json for both makes a conflict for cpu and gpu mining together

**Comment by xmrig** [comment]
Why just not use `--config` option?
Thank you.

**Comment by plastkort** [comment]
I can, but some settings i would like to keep as few parameters as possible, i think config.json can still be a default, but an alternative default would be nice as well which could be hardcoded in the cmake option part :)

**Comment by calvintam236** [comment]
A suggestion: run the docker image of xmrig.
