### ISSUE TITLE
why 2.5.0 not support f2pool?

### ISSUE THREAD

**Issue by k7k7k7** [xmrig/xmrig#473]
Hi,I'm a Chinese miner,I found that the 2.5.0 not support f2pool (www.f2pool.com).
URL of mining server is:xmr.f2pool.com:13531
ERROR shows that:
![error](https://user-images.githubusercontent.com/37268086/37860023-868bca70-2f58-11e8-9400-706a39cf37f2.png)

can you help me to fix it? thanks~

**Comment by xmrig** [comment]
It already fixed and will be available in next bugfix release v2.5.1 #459
Thank you.

**Comment by k7k7k7** [comment]
Thank you~hope v2.5.1 coming soon~~

**Comment by xmrig** [comment]
v2.5.1 released.
