### ISSUE TITLE
xmrig 2.5 unable to open config.json: no such file or directory

### ISSUE THREAD

**Issue by DediCATeD20** [xmrig/xmrig#474]
Using a freshly installed xmrig 2.5 on debian linux. I would like to use the config file option, but everything i try gives me unable to open config.json: no such file or directory.

I tried https, http, and wget download with local file.

**Examples:**

**Web**
/opt/xmrig/build/xmrig -c https://server/uploads/conf/xmrig-1-config.json

**Local**
rm /opt/xmrig/build/config.json
wget https://server//uploads/conf/xmrig-1-config.json -O /opt/xmrig/build/config.json
/opt/xmrig/build/xmrig

**Config**

{
    "algo": "cryptonight",
    "background": false,
    "colors": true,
    "retries": 5,
    "retry-pause": 5,
    "donate-level": 5,
    "syslog": false,
    "log-file": null,
    "print-time": 60,
    "av": 0,
    "safe": false,
    "max-cpu-usage": 90,
    "cpu-priority": 3,
    "threads": null,
    "pools": [
        {
            "url": "cryptonight.eu.nicehash.com:3355",
            "user": "xxx",
            "pass": "xxx",
            "keepalive": true,
            "nicehash": false
        }
    ],
    "api": {
        "port": 8080,
        "access-token": null,
        "worker-id": "W1"
    }
}

**Comment by xmrig** [comment]
Load config via http/https not supported, but with local file should no any troubles, newer reported issues with it.

* If not specify `-c` config should located in same directory with executable, if not you will get error with absolute path to config.json (starts with `/`).
* Same with `-c /opt/xmrig/build/config.json`
* If just `-c config.json` miner will looks for file in current working directory, for `/opt/xmrig/build/xmrig` it will be `/`.

Thank you.

**Comment by DediCATeD20** [comment]
Ok this clarifys it for me. Thank you very much. wget and -c config.json working.
