### ISSUE TITLE
asic resistant and compatibility for sumo algo

### ISSUE THREAD

**Issue by 2010phenix** [xmrig/xmrig#476]
for few day not have much time.. anyone test already?
link for who registered: https://bitcointalk.org/index.php?topic=1905086.msg33080011#msg33080011

-- cut --
Cryptonight-heavy, Sumokoin's asic resistant algo is finalised and under testing. 
Feel free to test/report and produce patches for miners other than xmr-stak. 
Feedback would be much appreciated.
Exact fork block height and writeup will follow soon
https://github.com/curie-kief/pow_test
-- cut --

and why only xmr-stak....

**Comment by xmrig** [comment]
fireice-uk just released new version with cryptonight-heavy support, so they just waited when Monero team tags the release. Welcome to PoW war.

**Comment by ZeGermanSumo** [comment]
Who waited for what mate?

**Comment by bluemelatonin** [comment]
I hope that XMRIG will be compatible with sumo. it's planned ?

**Comment by ZeGermanSumo** [comment]
Will it be @xmrig?

**Comment by curie-kief** [comment]
We are not looking to go to war with anyone @xmrig . The reference implementation is public https://github.com/curie-kief/pow_test If you want to implement it and need help, we would be delighted to help you.

**Comment by ProfDD** [comment]
xmrig could also update for SUMO's update? Thanks

**Comment by xmrig** [comment]
I will support it, but can't tell when, I need some time. Some big changes scheduled for v2.6 and I don't like delay it again. Anyway good to know about 4MB scratchpad now, before start implementing other things.

* When is estimated date of the fork?
* Will be nice have test pool like this http://killallasics.moneroworld.com/ before the fork.

Thank you.

**Comment by sergneo** [comment]
@xmrig To test SUMO is better on the pool https://sumokoin.hashvault.pro this is the only quick pool

**Comment by xmrig** [comment]
https://github.com/sumoprojects/sumokoin/commit/57daf6365b6c981bf53589bb85cfe0ebcda0eed7 April 4, so disappointing, secretly implement new PoW, not give time for others.

**Comment by ZeGermanSumo** [comment]
How is the implementation secret? We said it will happen soon (after testing is done). It was clear we will fork soon, since the issue allowed us no bigger delay. We announced the final date today:

Fork Block Height set at 117600 (on abt April 4th). Binaries will be released soon. Following the fork the light Qt GUI wallet will be released featuring remote node connection ability (it is ready for release). Web wallet is expected to be released soon as well. #sumokoin $sumo

**Comment by xmrig** [comment]
Announce of new PoW and xmr-stak 2.3 with fully finished cryptonight-heavy support in same day, okay no secret here, just spontaneously happen. I believe.

**Comment by fireice-uk** [comment]
Secret? Feel free to pull our code if you have implementation troubles and you will be up and running tomorrow.

**Comment by xmrig** [comment]
I will do. Thank you.

**Comment by bluemelatonin** [comment]
@xmrig yes xmr-stak implement cryptonight-heavy , but i love xmrig  and I do not want to change ;-) 

good luck

**Comment by sergneo** [comment]
@xmrig Testnet pool:
http://92.53.67.18
Testnet wallets:
Sutoe6DuhQJVR2RWKDWtC3YWGaTVeemBZVUYizBirBzK6ecaock4LNyZD6QUYy9Fwvb5MSD6VLFGiHijRhU4AdbzCc2j355X8Yv

**Comment by ZeGermanSumo** [comment]
Sumo's HF is going to happen sooner (block 11652).

Binaries are released (0.3.0.0) and ready to dowbload.

**Comment by xmrig** [comment]
CryptoNight-Heavy added in [dev](https://github.com/xmrig/xmrig/tree/dev) branch. [Full changelog](https://github.com/xmrig/xmrig/blob/dev/CHANGELOG.md#v260-beta1).

* **v2.6.0-beta1** release will be available soon.
* Use `"algo": "cryptonight-heavy",` in config file or `-a cryptonight-heavy` in command line to use new algorithm after the fork happen.
* OpenCL/CUDA miners will be updated later.

**Comment by sergneo** [comment]
@xmrig 
            "variant": -1                    // algorithm PoW variant
what were the options. how to enable PoW Sumo ?

**Comment by xmrig** [comment]
About variant https://github.com/xmrig/xmrig/issues/434#issuecomment-372360213
For SUMO this option silency ignored.
Thank you.

**Comment by NEK2018** [comment]
Please, add graceful reload support in xmrig-amd.
Thanks for all what you do!

**Comment by xmrig** [comment]
AMD miner now ready too https://github.com/xmrig/xmrig-amd/releases/tag/v2.6.0-beta1

**Comment by xmrig** [comment]
AMD miner is ready https://github.com/xmrig/xmrig-nvidia/releases/tag/v2.6.0-beta1

**Comment by xmrig** [comment]
Fixed, nvidia of course, thank you.
