### ISSUE TITLE
Prevent sleep mode

### ISSUE THREAD

**Issue by dunklesToast** [xmrig/xmrig#480]
Hey!

On macOS the Miner does not prevent the System from sleep mode.
I don't know if its a needed feature, but it would be pretty cool!

**Comment by tarris034** [comment]
I don't know much about macOS but I'm sure there are power settings in system like in windows that you can set to always on.

**Comment by dunklesToast** [comment]
Sure! But I want to have sleep enabled. Programs can prevent macOS from going into the sleep mode (Spotify does this for example). I just don’t want sleep mode when the Miner is running!
