### ISSUE TITLE
PoW change for Monero/Aeon/Sumokoin and others

### ISSUE THREAD

**Issue by xmrig** [xmrig/xmrig#482]
### :heavy_check_mark: Monero
 * **Successfully forked** on **April 6**, block height 1546000.
 * Miners v2.5+ will switch PoW automatically no additional setup or miner restart required.
 * Test pool http://killallasics.moneroworld.com/
 * Previous issue #434 with more Monero related details.

###  :clock5: Aeon
* Estimated date: **April 7**, not fixed yet as I know.
* Miners v2.5+ will switch PoW automatically no additional setup or miner restart required.
* Test pool https://aeonrebase.supportcryptonight.com from [reddit](https://www.reddit.com/r/Aeon/comments/877kmj/aeon_rebase_testnet_pool_pow/)

### :heavy_check_mark: Sumokoin
* **Successfully forked** at block height 116520.
* Sumokoin will use new algorithm named **Cryptonight-Heavy**, currently only CPU and AMD miner (**v2.6.0-beta1**) support it.
* Manual action required, `algo` option should changed to `cryptonight-heavy` and threads count should reduced twice (for CPU miners).
* More details in #476

### :heavy_check_mark: Turtlecoin
* **Successfully forked** on **April 8**, block height 350000.
* Manual action required, `algo` option should changed to `cryptonight-lite`, on each Turtlecoin pool option `variant` should set to `1`.
* Test pool https://trtltest.mine2gether.com/ from https://github.com/fireice-uk/xmr-stak/issues/1227

### :heavy_check_mark: Stellite
 * **Successfully forked** at block height 100800.
* Manual action required, on each Stellite pool option `variant` should set to `1`.
* Test pool https://cryptoknight.cc/v3/ from https://github.com/fireice-uk/xmr-stak/issues/1241

###  :heavy_check_mark: GRAFT
* **Successfully forked** at block height 65110.
* Manual action required now due version conflict https://github.com/xmrig/xmrig/issues/434#issuecomment-373184425
* Manual action required, if you was change `variant` option, on each GRAFT pool option `variant` should set to `1` or `-1`.

### :heavy_check_mark: Haven Protocol
 * **Successfully forked**.
* Manual action required, `algo` option should changed to `cryptonight-heavy` and threads count should reduced twice, only v2.6+ support it.

### :heavy_check_mark: IPBC
* **Successfully forked** on **April 16** at block height 54881.
* Manual action will required, `algo` option should changed to `cryptonight-ipbc`
* Support status: **Pending**.

###  :clock5: Masari
* Estimated date: **[May 1](https://github.com/masari-project/masari/commit/918b3b309b4bd51ced9e33a9e944bbdda503c1fd)**, at block height 170000.
* Manual action required, on each Masari pool option `variant` should set to `1` after the fork.

**Comment by qusstem** [comment]
POW war is started. Thanks Bitmain and baikal...

**Comment by 2010phenix** [comment]
@xmrig for Graft about update: https://www.graft.network/2018/03/27/upcoming-graft-software-release-major-network-update/

**Comment by esfomeado** [comment]
@xmrig What about KRB? https://github.com/seredat/karbowanec/issues/29

**Comment by xmrig** [comment]
@2010phenix thank you, I will update info later, according their github, will be used Monero v7 PoW https://github.com/graft-project/GraftNetwork/pull/100
@esfomeado It just a **new difficulty algorithm**, not a new PoW, this change not directly affect miners.

**Comment by sergneo** [comment]
@xmrig 
Sumokoin
‏ @sumokoin

Due to recent network's hashrate high fluctuations (our best guess is ASICs trying to get their last blocks) stalling the network, we decided to bring the fork's blockheight closer at block 116520. Binaries will be released shortly.
Thank you

**Comment by Zambi9** [comment]
What happens if I just continue using version 2.4.4?

**Comment by DuyQuang06** [comment]
@xmrig IPBC coin update new Cryptonight "Variant" 

https://ipbc.io/eng/announcements/ipbc-fork-available-in-testnet/

**Comment by DrStein99** [comment]
Scratchpad to 4k !?!? oh no!

**Comment by telebog** [comment]
I have a Ryzen 1700 Cpu. Tried on Sumokoin and works only on 4 threads ~230 H/s If I configure Json to use 8 Threads it works only with ~130 H/s. Any idea what settings to use to work normally ~500H/s?

**Comment by xmrig** [comment]
@DuyQuang06 Thank you for link.
@DrStein99 Now I'm confused how name this thing, maybe `cryptonight-ipbc` or `cryptonight-v7-jumbo-crazy`, because just `variant` not enough... 4 MB  scratchpad.
@ipbc-dev Reward most crazy PoW change now moved from Sumokoin to you.

**Comment by Sayyiditow** [comment]
haven protocol did not work for me, i keep getting rejected share, even with @cryptonight-heavy change on config.json. @xmrig

**Comment by ipbc-dev** [comment]
@xmrig 

Call it cryptonight ultraheavy ? 

We have forked your repo and implemented the new algo, CPU, AMD and Nvidia are working, we are testing and optimizing it, when we are done we can do a pull request.

**Comment by xmrig** [comment]
@Sayyiditow You should use only version **v2.6.0-beta1** for it, I was checked mine Haven, it works.
@ipbc-dev I think `cryptonight-ipbc` is good, pull request would be nice, please use dev branch for it.
Thank you.

**Comment by rhlug** [comment]
>> Manual action required, algo option should changed to cryptonight-heavy and threads count should reduced twice.

Can intensity be halved and keep same # of threads?

OLD
```
    "threads": [
        { "index": 0,  "intensity": 1920, "worksize": 8, "affine_to_cpu": false },
        { "index": 0,  "intensity": 1600, "worksize": 8, "affine_to_cpu": false },
    ],
```
NEW
```
    "threads": [
        { "index": 0,  "intensity": 960, "worksize": 8, "affine_to_cpu": false },
        { "index": 0,  "intensity": 800, "worksize": 8, "affine_to_cpu": false },
    ],
```

OR is this required?
```
    "threads": [
        { "index": 0,  "intensity": 1920, "worksize": 8, "affine_to_cpu": false },
    ],
```

Or does it matter?

**Comment by xmrig** [comment]
@rhlug it related only to CPU miners and it was written when only CPU version was available, so if you was run 2 threads you should run 2 too, but about `intensity` no need reduce it twice, optimal values should be above 1000 but lesser previous intensity, only experimenting may suggest you now.
Thank you.

**Comment by Sajo811** [comment]
TurtleCoin has successfully forked on April 8, at block height 350000

**Comment by pejuangbitco** [comment]
how changed algo to cryptonight-heavy? i use cpu

**Comment by Sayyiditow** [comment]
@ipbc-dev any idea when you will fork?

**Comment by 2010phenix** [comment]
@xmrig Graft add pool for test... and strange, only NVIDIA and AMD miner, link: https://bitcointalk.org/index.php?topic=2115188.msg34305644#msg34305644
-- cut --
The team completed an update to the public testnet. 
A new pool for mining functionality test is available here : http://pooltest.graft.network
-- cut --

**Comment by 2010phenix** [comment]
@xmrig Graft move update date: 
-- cut --
PATCH 1.1.1 HAS BEEN RELEASED – MAJOR NETWORK UPDATE ON BLOCK 65110
We decided to make the major network update sooner in order to minimize the possibility of hashrate attacks. Patch version 1.1.1 is now released and available for download from master. The major network update itself is rescheduled for block height 65110, around April 14th.
-- cut --

**Comment by felipe-vvoosh** [comment]
ETN is doing what? Such a slow team...

**Comment by ipbc-dev** [comment]
@Sayyiditow yes on monday 16.04.2018 at height 54881 (cryptonight light custum version)
more details here:  https://ipbc.io/eng/announcements/ipbc-fork-april-2018/

**Comment by xmrig** [comment]
@ipbc-dev guys are you serious? naturally one line added in code.
Hashrate drop is only 10 H/s only because this single line not optimized. (i7-4770 8 threads 1100 H/s on aeon7 vs 1090 H/s on ipbc). But this change makes your algorithm not compatible with exists miners.

**Comment by xmrig** [comment]
@ipbc-dev if someone will make ASICs for Aeon in next 6 months, they can implement your XOR just for fun.
@fireice-uk Look at this https://github.com/ipbc-dev/ipbc-miner/blob/master/xmrstak/backend/cpu/crypto/cryptonight_aesni.h#L515

**Comment by mcnih** [comment]
Hai xmrig, is Bytecoin (BCN), Intensecoin and some other coins will fork their algo also?

Thanks.

**Comment by xmrig** [comment]
@ipbc-dev Aeon still not fork to v7.

**Comment by ipbc-dev** [comment]
@xmrig ups sorry my bad, i supposed is already done, just taked a look here https://www.cryptunit.com

**Comment by sibero** [comment]
intensecoin fork to v7 PoW - May 14, 2018 https://intensecoin.com/2018/04/15/april-15th-update/

**Comment by felipe-vvoosh** [comment]
ETN is just playing with the devil now, the network is at 650 MH/s and the fan boys are saying that ASIC miners are fine as the team keeps struggling to fork and become ASIC resistant. It’s a blind trusting.

**Comment by marki555** [comment]
@sibero That is not accurate. 2 days ago ITNS released new plan for emergency fork in the following few days - https://intensecoin.com/2018/04/16/imminent-hard-fork-and-network-attack/

**Comment by cmorsucci** [comment]
aeon v7 is supported?

**Comment by xmrig** [comment]
Masari will fork too, information updated.

**Comment by 2010phenix** [comment]
almost all coin use or monero v7 clean, or option variant should set to 1
maybe OLD monero change to variant 1 and all other new-NEW-nEW altcoin simple work with autodetect or we can't detect?

**Comment by xmrig** [comment]
`variant` should set to 1, autodetection is useless since all other coins use block version below 7, except GRAFT, but actually good idea change default to `1` sometime later. I think you already saw https://github.com/xmrig/xmrig-proxy/issues/168 it allow pool explicitly inform miner about what exactly algorithm needed.

Now `cryptonight-lite` has 3 possible variants and `cryptonight` will have 3 variants soon, total 7 algorithms now.

**Comment by MoneroOcean** [comment]
Does xmrig already reacts to algo change provided by pool/proxy?

**Comment by bobbieltd** [comment]
@MoneroOcean Under my tests with xmrig 2.6.0 beta 3 / xmrig 2.5.3, xmrig doesn’t change algo.

**Comment by 2010phenix** [comment]
@xmrig Yes for proxy very good and simple idea send variant and algo data and even more, no other solution....
but look on miner, we have already  programmable algo-Terminator )) , demand more and more time for you(with not clarify itself algo Devs) and for ppl who used xmrig..
autodetect all this things(most like new algo fork from monero) solve and save time.

@MoneroOcean us say xmrig detect be in 2.6 stable master (for now only beta)

**Comment by 2010phenix** [comment]
@randing89  Hashrate(Network Hash Rate: 267.77 KH/sec) not to low for IN ?

**Comment by bobbieltd** [comment]
@MoneroOcean 
if (algorithm.isValid()) {
        LOG_ERR("Incompatible algorithm \"%s\" detected, reconnect", algorithm.name());
    }
    else {
        LOG_ERR("Unknown/unsupported algorithm detected, reconnect");
    }

No algorithm switching 😂 only for variant.
@xmrig Do you plan to make algo switch (lite, normal, heavy) in the future ? Scratchpad size issue ?

**Comment by Zambi9** [comment]
Do I understand correctly, that for Monero we will potentially need to change the miner every 6 months?

**Comment by sergneo** [comment]
@Zambi9  in the future it is expected that Yes it is necessary

**Comment by stoffu** [comment]
@xmrig Aeon is forking on June 3rd: https://github.com/aeonix/aeon/releases/tag/v0.12.0.0

**Comment by QwertyJack** [comment]
@xmrig Etn is gonna fork these days: [etn update](https://electroneum.com/2018/04/25/blockchain-update/)

**Comment by Mikanoshi** [comment]
IPBC should be supported now?
"algo": "cryptonight-lite",
"variant": "ipbc",
Pool rejects shares, says they are low diff...

**Comment by xmrig** [comment]
Recent information about algorithms/coins https://xmrig.com/docs/supported-currencies this issue not updated for a while, and not actual anymore.
