### ISSUE TITLE
Systemd service - SIGTERM received, exiting

### ISSUE THREAD

**Issue by DrStein99** [xmrig/xmrig#485]
I try setup xmrig as a system service, like the rest of my applications.  Unfortunately, I fail to get this to work.

`[2018-03-28 21:20:05] SIGTERM received, exiting`

Here is my service:

```
[Unit]
Description=xmrig miner
After=network.target

[Service]
Type=simple
GuessMainPID=no
ExecStart=/usr/src/xmrig25/build/xmrig -B -c /usr/src/xmrig25/build/config.json 
#Restart=on-failure
User=drstein99
LimitMEMLOCK=infinity

[Install]
WantedBy=multi-user.target

```

Does anyone have advice on what I am doing wrong?

**Comment by qusstem** [comment]
remove -B option

**Comment by DrStein99** [comment]
Ok.  I replace

`ExecStart=/usr/src/xmrig25/build/xmrig -B -c /usr/src/xmrig25/build/config.json`

with

`ExecStart=/usr/src/xmrig25/build/xmrig -c /usr/src/xmrig25/build/config.json`

Same issue - no change in the result.
