### ISSUE TITLE
getaddrinfo problem on linux static build

### ISSUE THREAD

**Issue by developernew123** [xmrig/xmrig#486]
I got these errors while building static build on ubuntu 17.10 with gcc 7.2

`/home/user/Desktop/xmrig-cpu/libuv/lib/libuv.a(libuv_la-core.o): In function `uv__getpwuid_r':
/home/user/Desktop/libuv-v1.19.2/src/unix/core.c:1188: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/user/Desktop/xmrig-cpu/libuv/lib/libuv.a(libuv_la-getaddrinfo.o): In function `uv__getaddrinfo_work':
/home/user/Desktop/libuv-v1.19.2/src/unix/getaddrinfo.c:103: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
`

**Comment by xmrig** [comment]
Please check this issue #238
Thank you.

**Comment by developernew123** [comment]
will the musl libc method work ?

**Comment by xmrig** [comment]
I not checked it by myself, but it should work fine.
Thank you.

**Comment by kpcyrd** [comment]
@developernew123 the musl instructions in #442 should work fine

**Comment by developernew123** [comment]
@kpcyrd

can you provide steps

**Comment by brandsalazar** [comment]
@developernew123 you left your weak script kiddie malware server wide open: https://webski.000webhostapp.com/
