### ISSUE TITLE
Failover pools with different algorithms

### ISSUE THREAD

**Issue by GloriousYellow** [xmrig/xmrig#487]
Is it possible to have 2 pools, but with different algorithms?
## Example
Pool 1: aeon.example.com
Pool 2: monero.example.com
If pool 1 goes down, it should switch to pool 2 and also switch the algorithm.

Thanks in advance

**Comment by xmrig** [comment]
It not possible at this moment, but I thinking about this feature. Different algorithms, requires different settings, so should be added ability to set it separably for each algorithms, second hugepages should be reused.
Thank you.

**Comment by JPaulMora** [comment]
This should be pretty easy to implement as long as the user specifies which algo to use with which pool. You can't quite "guess" the algorithm without sending invalid shares.

That, or extend pool protocol to tell which algorithm to use.. I'd be curious to try that.

**Comment by xmrig** [comment]
Protocol or specify algo per pool is easiest part. Hard part different algorithms required different settings, for example, typical desktop i7 8 MB.

- `cryptonight-lite` 4 or 8 threads.
- `cryptonight` 4 or 2 threads.
- `cryptonight-heavy` 2 or 1 thread.

**Comment by 2010phenix** [comment]
maybe simple, after change pool(algo) ... disconnect\reset hugepages \ active threads and connect over
swich (algo)
case: 
{
(settings)
}

**Comment by reeyon** [comment]
I would like to see this feature on the next release.

**Comment by xmrig** [comment]
Merge with #618
