### ISSUE TITLE
What's the difference between Windows Versions (MSVC&GCC)

### ISSUE THREAD

**Issue by elkader1983** [xmrig/xmrig#492]
Can you please tell me what's the difference between the two windows versions MSVC and GCC?

Thanks.

L

**Comment by pikomule** [comment]
I also have that doubt

**Comment by xmrig** [comment]
Different compilers gcc 7.3 (from MSYS2) or MSVC 2017, performance very close, usually msvc little bit faster, you can try both. For 32 bit situation is different, msvc always slower and I not release it.
Thank you.

**Comment by pikomule** [comment]
thanks
