### ISSUE TITLE
connect to xmrig-proxy using ipv6

### ISSUE THREAD

**Issue by adi3yz** [xmrig/xmrig#496]
"pools": [
	{
            "url": "fe80::c132:2c9b:7794:38c3%10:7777",
            "user": "XMRig",
            "pass": "x",
            "keepalive": true,
            "nicehash": true,
	},

XMRig\config.json:532: Invalid value.
No pool URL supplied. Exiting.

how can i connect to xmrig-proxy using ipv6?

**Comment by xmrig** [comment]
Url should looks like `"[fe80::c132:2c9b:7794:38c3%10]:7777"` or `"[fe80::c132:2c9b:7794:38c3]:7777"`.
But in your config some other error at offset 532 from file start, you can use https://config.xmrig.com/ to generate config file.
Thank you.
