### ISSUE TITLE
Remote control issue

### ISSUE THREAD

**Issue by ghost** [xmrig/xmrig#497]
I write a script to remote control my Linux machines like this
```
function start(){
    for i in hosts;do
        ssh $i "/root/xmrig/xmrig"
    done
}
```
I've done ssh-key import and it needs no password to use SSH

BUT the xmrig won't run in the background even if I use '&'.

I had to quit with 'ctrl + c' for every machine manually.

Hope this issue could be solved.

Thanks a lot.

**Comment by 0xc0d32** [comment]
I believe you should run it in the background and monitor its functioning via api.

> -B, --background          run the miner in the background
