### ISSUE TITLE
I can not make

### ISSUE THREAD

**Issue by Nivoyash** [xmrig/xmrig#5]
**Installed**:
- MVS17
- CMake (and TDM-GCC-64)
- cURL

**Source on**: C:\Users\user\Downloads\xmrig-master\xmrig-master
**Build dir**: C:\Users\user\Downloads\xmrig-master\xmrig-master\build
**Command**: cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCURL_INCLUDE_DIR="C:\curl-7.54.0\include" -DCURL_LIBRARY="C:\curl-7.54.0\lib" -DCMAKE_C_COMPILER="C:\MinGW\bin\c++.exe"

**Output**: 
`
C:\Users\user\Downloads\xmrig-master\xmrig-master\build>cmake .. -G "Unix Makefi
les" -DCMAKE_BUILD_TYPE=Release -DCURL_INCLUDE_DIR="C:\curl-7.54.0\include" -DCU
RL_LIBRARY="C:\curl-7.54.0\lib" -DCMAKE_C_COMPILER="C:\MinGW\bin\c++.exe"
-- The C compiler identification is unknown
CMake Error at build/CMakeFiles/3.8.1/CMakeCCompiler.cmake:1 (set):
  Syntax error in cmake code at

    C:/Users/user/Downloads/xmrig-master/xmrig-master/build/CMakeFiles/3.8.1/CMa
keCCompiler.cmake:1

  when parsing string

    C:\MinGW\bin\c++.exe

  Invalid escape sequence \M
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Users/user/Downloads/xmrig-master/xmrig-master/build/CMakeFiles/CMa
keOutput.log".
See also "C:/Users/user/Downloads/xmrig-master/xmrig-master/build/CMakeFiles/CMa
keError.log".

C:\Users\user\Downloads\xmrig-master\xmrig-master\build>`

Maby you have .sln MVS2017?

**Comment by xmrig** [comment]
You need a C compiler (gcc) not C++
MSVC (any version) not supported.
