### ISSUE TITLE
version 2.5.x stellite Low diffficulty share error

### ISSUE THREAD

**Issue by exceler55** [xmrig/xmrig#500]
Hi, 
I set "variant" as 1 for Stellite, but the program returns the error "Low difficulty share" rejected. 
What's wrong?

**Comment by pikomule** [comment]
only change "-1" for "1"

**Comment by pikomule** [comment]
2.6.0 beta 1 ok for stellite

**Comment by xmrig** [comment]
Both 2.5 and 2.6 should work fine for stellite.
@exceler55 `variant` is not global option, it applied for each pool separately.

**Comment by exceler55** [comment]
Ah, I understand. It works fine. 
Sorry and thank you.
