### ISSUE TITLE
static build issue..!!??

### ISSUE THREAD

**Issue by Gill1000** [xmrig/xmrig#508]
this is my first lines of cmakelist.

option(WITH_LIBCPUID "Use Libcpuid" ON)
option(WITH_AEON     "CryptoNight-Lite support" ON)
option(WITH_HTTPD    "HTTP REST API" OFF)
option(BUILD_STATIC  "Build static binary" ON)

i want to build static  ..i m using xmrig2.5.2 building by gcc in window8.1
in cmakelist "build static binary" is ON but still i m getting  libwinpthread-1.dill missing.!!

**Comment by xmrig** [comment]
You trying build with wrong libuv version, please use https://github.com/xmrig/xmrig-deps
Thank you.

**Comment by Gill1000** [comment]
yes ..you were right ..now its working 
thanks
