### ISSUE TITLE
add amd and nvida gpu suport

### ISSUE THREAD

**Issue by jonsee** [xmrig/xmrig#51]
hi , can u add the amd and nvida gpu version , it can control gpu usage 50%  75% and full
there has an example https://github.com/fireice-uk/xmr-stak-amd

**Comment by xmrig** [comment]
I working on it, but there no estimated date when it will be finished.
Thank you.

**Comment by xmrig** [comment]
NVIDIA is here https://github.com/xmrig/xmrig-nvidia

**Comment by calvintam236** [comment]
I'd love to see AMD version come out soon as well. I like your miner. Clean & lightweight. For me, it is better than `sgminer` or `xmr-stak` :D

**Comment by xmrig** [comment]
AMD version development not started yet. I will create it as soon as possible.
Thank you.

**Comment by calvintam236** [comment]
Great to hear that. It's a crucial time because XMR  is more profitable the last few days, and there isn't many miners we can use for AMD GPUs.

**Comment by xmrig** [comment]
I create roadmap for next releases #106

**Comment by xmrig** [comment]
AMD version now available https://github.com/xmrig/xmrig-amd
It stable, all features from v2.4.2 included, but still beta version.
Thank you.
