### ISSUE TITLE
hash????

### ISSUE THREAD

**Issue by guigeddos** [xmrig/xmrig#512]
****
![tim 20180407101458](https://user-images.githubusercontent.com/35347058/38450206-899de8b6-3a4c-11e8-87c9-517f580d8d5c.png)
E7 4820 4CPU    198h/s
@xmrig

**Comment by 4Reallive** [comment]
mine restores after a reboot, then drops again to a similar rate. worked fine for SUMO.
XMR is throwing it off. will continue monitoring.
