### ISSUE TITLE
Windows binaries are not extracting!

### ISSUE THREAD

**Issue by jodobear** [xmrig/xmrig#515]
The windows binaries are not being extracted! How is this possible (!)
I downloaded MSVC & GCC64, same issue!

**Comment by Gill1000** [comment]
I too face this issue ...your chrome is blocking this...allow him!!!!
your chrome thinks these are might be dangerous files!!

**Comment by radbud** [comment]
I am using firefox and i can download the zip file like `xmr-stak` for example and run them. When i open `xmrig` zip file i do see the three files: `config, start & xmrig` . BUT, when i try to extract them, nothing happens. So, i tried to manually drag and drop them in a new folder, all files get copied except the `xmrig` application. How can this be explained?

**Comment by Zambi9** [comment]
It's possible the file does get copied / extracted, but quickly gets identified by Windows Defender or your AV and gets deleted. Check your Defender logs. Sometimes its just being done silently with no notification to user.

**Comment by radbud** [comment]
Ok! So I did find it in my Defender's log by the name of `Coinminer!bit` with 'Severe` tagged to it. One question before i actually do try to white list it (which i don't know yet) is why is `xmrig` detected as threat and not `xmr-stak`?

Thanks @Zambi9

**Comment by xmrig** [comment]
Windows Defender is very funny, some long time ago block xmrig-proxy only for word Monero in file description. It can stop blocking file after few days or start and... stop again. Also it was detect xmrig and xmr-stak with same name including letters after `!`. So is today xmr-stak not detected it not meant anything it can start detected tomorrow or not. Personally I add folder where I build miner to exclusion list after Windows Defender start remove freshly complied exe, after release with minor changes was published on github.

Anyway av description `Coinminer` is pretty good for coin miner.
Thank you.
