### ISSUE TITLE
2.5.2 "Incorrect hashing protocol in use.  Please upgrade/fix your miner"  & "Low difficulty share"

### ISSUE THREAD

**Issue by Maibaosoul** [xmrig/xmrig#516]
Xmrig 2.5.2
Xmr-proxy version 2.5.2

"Incorrect hashing protocol in use.  Please upgrade/fix your miner"  
 "Low difficulty share"

How to resolve?

proxy config:
{
    "access-log-file": null,
    "algo": "cryptonight",
    "api": {
        "port": 0,
        "access-token": null,
        "worker-id": null,
        "ipv6": true,
        "restricted": true
    },
    "background": false,
    "bind": [
        "0.0.0.0:9998",
        "[::]:9998"
    ],
    "colors": true,
    "custom-diff": 0,
    "donate-level": 1,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "url": "hk01.supportxmr.com:7777",
            "user": "guess",
            "pass": "hk",
            "variant": 0
        }
    ],
    "retries": 2,
    "retry-pause": -1,
    "reuse-timeout": 0,
    "user-agent": null,
    "verbose": true,
    "watch": true,
    "workers": true
}

xmrig config:

{
    "algo": "cryptonight",  // cryptonight (default) or cryptonight-lite
    "av": 0,                // algorithm variation, 0 auto select
    "background": false,    // true to run the miner in the background
    "colors": true,         // false to disable colored output    
    "cpu-affinity": null,   // set process affinity to CPU core(s), mask "0x3" for cores 0 and 1
    "cpu-priority": null,   // set process priority (0 idle, 2 normal to 5 highest)
    "donate-level": 1,      // donate level, mininum 1%
    "log-file": null,       // log all output to a file, example: "c:/some/path/xmrig.log"
    "max-cpu-usage": 50,    // maximum CPU usage for automatic mode, usually limiting factor is CPU cache not this option.  
    "print-time": 60,       // print hashrate report every N seconds
    "retries": 5,           // number of times to retry before switch to backup server
    "retry-pause": 5,       // time to pause between retries
    "safe": false,          // true to safe adjust threads and av settings for current CPU
    "threads": null,        // number of miner threads
    "pools": [
        {
            "url": "hk01.supportxmr.com:9998", // URL of mining server
            "user": "near",           // username for mining server
            "pass": "x",                     // password for mining server
            "keepalive": true,               // send keepalived for prevent timeout (need pool support)
            "nicehash": true,               // enable nicehash/xmrig-proxy support
            "variant": 0                    // algorithm PoW variant
        }
    ],
    "api": {
        "port": 0,                             // port for the miner API https://github.com/xmrig/xmrig/wiki/API
        "access-token": null,                  // access token for API
        "worker-id": null                      // custom worker-id for API
    }
}

**Comment by JustHoldit** [comment]
+1
[2018-04-07 23:30:45] new job from 127.0.0.1:5556 diff 5000
[2018-04-07 23:31:03] speed 2.5s/60s/15m 148.4 151.4 n/a H/s max: 157.9 H/s
[2018-04-07 23:31:05] rejected (0/6) diff 5000 "Incorrect hashing protocol in use.  Please upgrade/fix your miner" (100 ms)
[2018-04-07 23:31:09] rejected (0/7) diff 5000 "Incorrect hashing protocol in use.  Please upgrade/fix your miner" (99 ms)
[2018-04-07 23:31:12] new job from 127.0.0.1:5556 diff 5000
[2018-04-07 23:31:49] rejected (0/8) diff 5000 "Bad gateway" (0 ms)
[2018-04-07 23:31:51] new job from 127.0.0.1:5556 diff 5000
[2018-04-07 23:32:00] accepted (1/8) diff 5000 (32 ms)
[2018-04-07 23:32:02] new job from 127.0.0.1:5556 diff 15000
[2018-04-07 23:32:03] speed 2.5s/60s/15m 152.5 151.0 n/a H/s max: 157.9 H/s
[2018-04-07 23:32:11] accepted (2/8) diff 15000 (0 ms)
[2018-04-07 23:33:02] new job from 127.0.0.1:5556 diff 15000
[2018-04-07 23:33:03] speed 2.5s/60s/15m 149.2 150.0 n/a H/s max: 157.9 H/s

**Comment by MoonGem** [comment]
We need auto variant

**Comment by xmrig** [comment]
@Maibaosoul Why you set `"variant": 0`? For Monero you don't need touch this option at all, if you remove this option from file or set it to `-1` anything will work. Valid values for Monero is `-1` (autodetect) or `1`.

@JustHoldit You use proxy with custom diff, accepted shares in your log not really accepted by pool.

@MoonGem `variant=-1` not work in one case, if you don't mine Monero.

**Comment by Maibaosoul** [comment]
I set variant values -1, but nothing changed.

**Comment by ego008** [comment]
I also encountered the same error,  it works fine in the past 30 days.

**Comment by tkalfaoglu** [comment]
same here.. :(  

[2018-04-09 08:39:10] new job from pool.supportxmr.com:3333 diff 5000
[2018-04-09 08:39:37] speed 2.5s/60s/15m 78.6 78.7 n/a H/s max: 78.7 H/s
[2018-04-09 08:39:50] rejected (7/1) diff 5000 "IP Address currently banned for using an invalid mining protocol, please check your miner" (84 ms)
[2018-04-09 08:39:50] no active pools, stop mining
[2018-04-09 08:39:56] use pool pool.supportxmr.com:3333 94.130.12.27
[2018-04-09 08:39:56] new job from pool.supportxmr.com:3333 diff 5000
[2018-04-09 08:40:09] new job from pool.supportxmr.com:3333 diff 6977
[2018-04-09 08:40:37] speed 2.5s/60s/15m 78.7 71.0 n/a H/s max: 78.7 H/s

**Comment by tkalfaoglu** [comment]
SOLVED: Simply install the current git version, then set the algorithm to:
"algo": "cryptonight-heavy"

**Comment by Nuend0** [comment]
running 2.6.0 beta2 miners on 2.5.2 proxy - all set to cryptonight-heavy and still getting this errors

[2018-04-11 20:18:14] rejected (104/63) diff 60000 "Incorrect hashing protocol in use.  Please upgrade/fix your miner" (2 ms)
&

[2018-04-11 20:10:06] rejected (90/58) diff 60000 "Incorrect hashing protocol in use.  Please upgrade/fix your miner" (3 ms)

proxy setup:
**************************************************************
{
    "access-log-file": null,
    "algo": "cryptonight-heavy",
    "api": {
        "port": 8888,
        "access-token": null,
        "worker-id": null,
        "ipv6": true,
        "restricted": true
    },
    "background": false,
    "bind": [
        "0.0.0.0:3333",
        "[::]:3333"
    ],
    "colors": true,
    "custom-diff": 0,
    "donate-level": 2,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
			"url": "pool.supportxmr.com:7777",
			"user": "******************+60000",
			"pass": "Proxy:**************************",
            "variant": -1
        }
    ],
    "retries": 5,
    "retry-pause": 3,
    "reuse-timeout": 0,
    "user-agent": null,
    "verbose": true,
    "watch": true,
    "workers": true
}
**********************************************************************************
miner setup:
**********************************************************************************
{
    "algo": "cryptonight-heavy",  // cryptonight (default) or cryptonight-lite
    "av": 0,                // algorithm variation, 0 auto select
    "background": false,    // true to run the miner in the background
    "colors": true,         // false to disable colored output    
    "cpu-affinity": null,   // set process affinity to CPU core(s), mask "0x3" for cores 0 and 1
    "cpu-priority": null,   // set process priority (0 idle, 2 normal to 5 highest)
    "donate-level": 1,      // donate level, mininum 1%
    "log-file": null,       // log all output to a file, example: "c:/some/path/xmrig.log"
    "max-cpu-usage": 100,    // maximum CPU usage for automatic mode, usually limiting factor is CPU cache not this option.  
    "print-time": 60,       // print hashrate report every N seconds
    "retries": 5,           // number of times to retry before switch to backup server
    "retry-pause": 5,       // time to pause between retries
    "safe": false,          // true to safe adjust threads and av settings for current CPU
    "threads": null,        // number of miner threads
    "pools": [
        {
            "url": "<PROXY ADDRESS>",   // URL of mining server
            "user": "*******************",                        // username for mining server
            "pass": "x",                     // password for mining server
            "keepalive": true,               // send keepalived for prevent timeout (need pool support)
            "nicehash": true,               // enable nicehash/xmrig-proxy support
            "variant": -1                    // algorithm PoW variant
        }
    ],
    "api": {
        "port": 0,                             // port for the miner API https://github.com/xmrig/xmrig/wiki/API
        "access-token": null,                  // access token for API
        "worker-id": null                      // custom worker-id for API
    }
}
****************************************************************
Anyone got any ideas??

**Comment by Nuend0** [comment]
bugger - thanks

**Comment by johannes-see** [comment]
+1

**Comment by snipeTR** [comment]
Firewall, router, wrong diff, or banned poll for your ip
