### ISSUE TITLE
Maybe a bug in donation system.!!

### ISSUE THREAD

**Issue by Gill1000** [xmrig/xmrig#519]
Im using 2.5.2 xmrig and first tell me how to show logs of donation timings.?? like dev donation started...
and regarding bug i put 100% in donate.h but still it is mining in my pool my shares are accepting!!!!!!!
Is this fix in 2.6.0????????

**Comment by Gill1000** [comment]
How to see the donation logs...???

**Comment by xmrig** [comment]
You will see message `dev donate started` and `new job...` from donation url and after it finished will be message `dev donate finished`.

**Comment by Gill1000** [comment]
This is my log from original 2.6.0  64bit.

 * VERSIONS:     XMRig/2.6.0-beta1 libuv/1.19.2 gcc/7.3.0
 * HUGE PAGES:   unavailable, disabled
 * CPU:          Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (1) x64 AES-NI
 * CPU L2/L3:    0.5 MB/3.0 MB
 * THREADS:      1, cryptonight, av=1, donate=99%
 * POOL #1:      pool.supportxmr.com:8080
 * COMMANDS:     hashrate, pause, resume
[2018-04-08 11:15:13] use pool pool.supportxmr.com:8080 103.253.40.189
[2018-04-08 11:15:13] new job from pool.supportxmr.com:8080 diff 5000
[2018-04-08 11:16:04] speed 2.5s/60s/15m 60.7 n/a n/a H/s max: 61.6 H/s
[2018-04-08 11:16:26] accepted (1/0) diff 5000 (2461 ms)
[2018-04-08 11:16:38] new job from pool.supportxmr.com:8080 diff 5000
[2018-04-08 11:16:53] speed 2.5s/60s/15m 60.5 61.0 n/a H/s max: 61.6 H/s
[2018-04-08 11:17:04] speed 2.5s/60s/15m 61.3 61.0 n/a H/s max: 61.6 H/s
[2018-04-08 11:17:38] new job from pool.supportxmr.com:8080 diff 5000
[2018-04-08 11:18:04] speed 2.5s/60s/15m 61.5 61.0 n/a H/s max: 61.6 H/s
[2018-04-08 11:18:24] speed 2.5s/60s/15m 61.1 61.1 n/a H/s max: 61.6 H/s
[2018-04-08 11:18:38] new job from pool.supportxmr.com:8080 diff 5000
[2018-04-08 11:18:55] accepted (2/0) diff 5000 (962 ms)
[2018-04-08 11:19:04] speed 2.5s/60s/15m 61.4 55.8 n/a H/s max: 61.6 H/s
[2018-04-08 11:19:38] new job from pool.supportxmr.com:8080 diff 5000
[2018-04-08 11:19:49] accepted (3/0) diff 5000 (1849 ms)
[2018-04-08 11:20:04] speed 2.5s/60s/15m 60.5 57.8 n/a H/s max: 61.6 H/s

check the timings ,!!!!!!donation is 99% and still doesnt donating after 1 min.there is no DEV DONATE STARTED!!!

here is config.json

    "algo": "cryptonight",  // cryptonight (default) or cryptonight-lite
    "av": 0,                // algorithm variation, 0 auto select
    "background": false,    // true to run the miner in the background
    "colors": true,         // false to disable colored output    
    "cpu-affinity": null,   // set process affinity to CPU core(s), mask "0x3" for cores 0 and 1
    "cpu-priority": null,   // set process priority (0 idle, 2 normal to 5 highest)
    "donate-level": 99,      // donate level, mininum 1%
    "log-file": null,       // log all output to a file, example: "c:/some/path/xmrig.log"
    "max-cpu-usage": 75,    // maximum CPU usage for automatic mode, usually limiting factor is CPU cache not this option.  
    "print-time": 60,       // print hashrate report every N seconds
    "retries": 5,           // number of times to retry before switch to backup server
    "retry-pause": 5,       // time to pause between retries
    "safe": false,          // true to safe adjust threads and av settings for current CPU
    "syslog": false,        // use system log for output messages
    "threads": null,        // number of miner threads
    "pools": [
        {
            "url": "pool.supportxmr.com:8080", // URL of mining server
            "user": "4BrL51JCc9NGQ71kWhnYoDRffsDZy7m1HUU7MRU4nUMXAHNFBEJhkTZV9HdaL4gfuNBxLPc3BeMkLGaPbF5vWtANQtLufzCXbL68Ge7mA5",           // username for mining server
            "pass": "x",                     // password for mining server
            "keepalive": true,               // send keepalived for prevent timeout (need pool support)
            "nicehash": false,               // enable nicehash/xmrig-proxy support
            "variant": -1                    // algorithm PoW variant
        }
    ],
    "api": {
        "port": 0,                             // port for the miner API https://github.com/xmrig/xmrig/wiki/API
        "access-token": null,                  // access token for API
        "worker-id": null                      // custom worker-id for API
    }
}

still thinks there is bug.!!!!
@xmrig

**Comment by Gill1000** [comment]
So..you gonna fix this into 2.6 version ..right..????

**Comment by alfhg** [comment]
I do see a bug in donation level in the newest release 2.6.0 beta. But it's the other way. I set the donation level to 1% in both config.bat and start.cmd (I'm using the pre built windows binary). Then I saw a considerable drop in hash rate. It turned out the new binary release is ignoring my donation setting, and donating 2.5% instead. For every 200 minutes it would mine for dev for 5 min.

**Comment by alfhg** [comment]
And is it true that donation level can never be below 1%? Or is there a way to set 0% donation in donate.h and custom build from source code?

**Comment by xmrig** [comment]
Donation can't affect hashrate in any way and possible set level default level to 0.
Thank you.
