### ISSUE TITLE
Slow Hash Rate for Cryptonight-Heavy

### ISSUE THREAD

**Issue by codeorcode** [xmrig/xmrig#520]
I try to mine Sumokoin using 2.6.0-beta1 version.
I got hashrate of **80 Hh/s** on an AMD FX 6300 CPU where on the same suokoin but old fork that used cryptonight I got **270 Hs/s**.

So it's a drop from **270** to **80** Hs/s when using **cryptonight heavy** instead of **cryptonight**.

**Comment by jasbe-schermer** [comment]
I'm afraid that's by design of cryptonight-heavy, a 60% drop on hashrate on CPU is unfortunately normal.

**Comment by xmrig** [comment]
@codeorcode don't forget, threads count should be reduced twice if you set it manually before.
Thank you.

**Comment by codeorcode** [comment]
I've set it to three (instead of 6 but then only 3 cores are used).
