### ISSUE TITLE
compiled binary wont run on computers that dont have libmicrohttpd

### ISSUE THREAD

**Issue by prismspecs** [xmrig/xmrig#531]
on MacOS, get this:

dyld: Library not loaded: /usr/local/opt/libmicrohttpd/lib/libmicrohttpd.12.dylib
  Referenced from: /Applications/Bail Bloc.app/Contents/Resources/app/miner_binaries/./bailbloc_worker
  Reason: image not found

can we package that into the compiled binary somehow?

**Comment by djfinch** [comment]
You're compile xmrig with dynamic compile. you can either:
- compile as static (explicitly point cmake to libs)
```
-DMHD_LIBRARY=/usr/local/opt/libmicrohttpd/lib/libmicrohttpd.a
```
- copy missing .dilyb on place
- install homebrew + deps on that machine
- compile with HTTPD OFF (if you don't need it)
```
-DWITH_HTTPD=OFF
```
Best solution is static recompile. Easiest is copy lib on place but its *****.

**Comment by prismspecs** [comment]
oh wow, thank you! this makes sense.

may i ask--it seems as though the Visual Studio Windows instructions account for this, so that should work as is? and then for Linux, I will need to include static versions of both libmicrohttpd and libuv much like what you describe for mac above?

thanks!

**Comment by djfinch** [comment]
You're welcome. In case of Unix-like OS it's OK to use dynamic binaries as long as they are present in the system (native compile, miner is maybe a bit faster) but if you need them "portable" then static compile is mandatory (or provide dynamic libs (*.so) on target system via homebrew on osx or apt/yum/pacman on linux). Linux steps are similar but locations of static libs (.a) are quite different. It's very well described in WIKI pages. Regarding Windows - you need [these](https://github.com/xmrig/xmrig-deps/releases) pre-build static libs or make your own (I wouldn't recommend that as this is very time-consuming process).

**Comment by prismspecs** [comment]
Great, it worked across the board, thank you again!

our project, www.bailbloc.com is very grateful for your help

**Comment by djfinch** [comment]
It's all right. ;) Please close this issue if soled. Thanks!
