### ISSUE TITLE
PUT config

### ISSUE THREAD

**Issue by cupertank** [xmrig/xmrig#534]
How does it work "PUT /1/config".
What you need to send in the request.

My Python code
>>> data = {'threads':4}
>>> put('http://127.0.0.1:3222/1/config', headers={'Authorization':'Bearer 123'}, data=data)
<Response [415]>

**Comment by xmrig** [comment]
Whole JSON config, for convenient, config can be obtained by `GET /1/config`. Please note this feature is not fully implemented and tested, only some base settings now can changed in runtime. This feature was first introduced in xmrig-proxy v2.5.
Thank you.

**Comment by cupertank** [comment]
Does this function now work in 2.6.0?
"Added API endpoint PUT /1/config to update current config."
@xmrig

**Comment by xmrig** [comment]
It works, config can changed, but some major functions eg change pools or threads not work at this moment.
Thank you.

**Comment by cupertank** [comment]
I wrote a bot to track the work of the miner and would like to add a functional change to the configuration of the miner using PUT /1/config, but I do not understand why I get the 415 error.
By the way, I wrote to you on the mail about the bot, but so I did not answer, maybe you'll fix it on your GitHub?
https://t.me/Miner_checker_bot

**Comment by cupertank** [comment]
And what functions are available at the moment?
@xmrig

**Comment by oOTnTOo** [comment]
i put config json with JS，but its return 403 Forbidden，why？

**Comment by oOTnTOo** [comment]
@xmrig
