### ISSUE TITLE
Ubuntu --threads not working

### ISSUE THREAD

**Issue by intechmo** [xmrig/xmrig#539]
i try to adding --threads=60 (for cpu 64 core) but always set threads 6 ..
please fix

**Comment by RBlaine95** [comment]
What happens if you use `--numthreads=60`?

**Comment by intechmo** [comment]
for faster maybe .. 64 core, 6 threads .. i just got 480 h/s ..

**Comment by intechmo** [comment]
* CPU:          Intel(R) Xeon(R) CPU E5-2699C v4 @ 2.20GHz (1) x64 AES-NI
 * CPU L2/L3:    16.0 MB/55.0 MB

**Comment by RBlaine95** [comment]
Ok, you've got 55MB of L3 cache
So, the recommended number of threads is

**Comment by RBlaine95** [comment]
Ok, you've got 55MB of L3 cache
So, the recommended number of threads is 27 for optimal performance.

You'll be able to get a more accurate number of threads by running these lines in a terminal:
```
cache=$(cat /proc/cpuinfo | grep "cache size" | awk 'NR==1{print $4}')
echo Recommended Cryptonight Threads: $(expr $cache / 4096) threads
```

**Comment by xmrig** [comment]
If this issue still actual, please check v2.99.2-beta release #1077.
Thank you.
