### ISSUE TITLE
STOPS MINING

### ISSUE THREAD

**Issue by tremmorkeep** [xmrig/xmrig#541]
Every now and then I get a status of 'Dev donation complete' and my miner(s) go idle...I dont have money wrapped up into hardware to have the not mine....please advise

**Comment by qusstem** [comment]
version miner? 2.6.0 beta 1 have "bug" with donation

**Comment by tremmorkeep** [comment]
2.5.2 ...and it happens on all my hardware, CPU and GPU.

**Comment by xmrig** [comment]
Please show log or make screenshot, it's pretty strange. When donation active, connection to user pool is still active and switching happen immediately, for mining part it's like usual job.
Thank you.

**Comment by tremmorkeep** [comment]
K, next time it happens I’ll grab the screen.

Mining on 5 different boxes.  Main box is a threadripper 1950x with 2x Nvidia GeForce 1070ti’s

**Comment by tremmorkeep** [comment]
![image](https://user-images.githubusercontent.com/31779426/39084645-16319f86-4536-11e8-8f4d-f6dffadfe263.png)
so...I know its a low hashrate...congratulations it hit your hashes..and didnt mine for me all night...thanks...thats awesome

**Comment by xmrig** [comment]
Looks like https://github.com/xmrig/xmrig/issues/478 not complete fixed in 2.5.2, connection to your pool died before donation start, hashare **n/a**, try use v2.5.0.
Thank you.

**Comment by tremmorkeep** [comment]
Yes using 2.5.0 now. On vacation. Switching to dual miner upon return
