### ISSUE TITLE
Fluctuation in hashrate

### ISSUE THREAD

**Issue by septuig** [xmrig/xmrig#545]
CPU: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz (2) x64 AES-NI
CPU L2/L3: 10.0 MB/50.0 MB
I am mining Monero with CN7, but fluctuation in hashrate is large, from 500 to 1.3k at different time. How to config  "config.json" correctly?  Now all items are default , thank you.

"cpu-affinity": null,
"cpu-priority": null,

**Comment by lisergey** [comment]
@septuig, your CPU has 10 cores, 20 threads each. 
try
"threads": 24,
if this would increase and stabilize hashrate, then I would count affinity mask for this threads number to make it even better.

**Comment by septuig** [comment]
Ok, I will try, fyi, now default "threads" is 25. thank you.

**Comment by lisergey** [comment]
25 threads is more then your CPUs are capable without overlapping in L3 cache.
each CPU should run 12 threads x 2MB L3 cache = 24 MB, to be the most effective.

**Comment by septuig** [comment]
"av": 2,
"threads": 12,
"cpu-affiinity": "0xAAA00AAA00",
 
The above setting is workable, the hashrate is obviously improved and stable. 
 "cpu-affiinity": "0x5550055500" is worse than "0xAAA00AAA00" 
Thank you very much

Another question,  how to config the "config.json" to improve the mining of SUMO with CN H by the same CPU E5-2680v2 x2. Now the config is default as below, hashrate is about 400-500h:
"av": 1,
"threads": 12,
"cpu-affiinity": null,

Thank you in advance.

**Comment by lisergey** [comment]
for Sumokoin, it takes 4MB of L3 cache per thread to maximize performance.
thus same affiinity with twice less threads:
```
"algo": "cryptonight-heavy",
"av": 1,
"threads": 12,
"cpu-affiinity": "0xAAA00AAA00",
```

I wonder what gives most rate for MoneroV7, 12 threads with av=2 or 24 threads with av=1?
for `"av": 1` affinity would be
`"cpu-affiinity": "0xFAAAAFAAAA",`

**Comment by septuig** [comment]
Tested.
"av": 2,"threads": 12,"cpu-affiinity": "0xAAA00AAA00", is better than "av": 1,"threads": 12,"cpu-affiinity": "0xFAAAAFAAAA", for me.

**Comment by septuig** [comment]
Tested.

"av": 1,"threads": 24,"cpu-affiinity": "0xFAAAAFAAAA", is better than "av": 2,"threads": 12,"cpu-affiinity": "0xAAA00AAA00",

Thank you so much

**Comment by septuig** [comment]
Tested.

"av": 1,"threads": 24,"cpu-affiinity": "0xFAAAAFAAAA", is better than "av": 2,"threads": 12,"cpu-affiinity": "0xAAA00AAA00", for me.

Thank you so much

**Comment by chimchi** [comment]
What is the meaning of "cpu-affiinity": "0xFAAAAFAAAA".

Thanks in advance.

**Comment by septuig** [comment]
Afer upgraded to CN v8, the fluctuation in hashrate occurs again, the hash rate range is from 900+ to 1100+, can you please help fix this problem, thanks in advance.

**Comment by xmrig** [comment]
#1077
