### ISSUE TITLE
NiceHash rejected 

### ISSUE THREAD

**Issue by welj** [xmrig/xmrig#549]
Hi, sometime have errors in NiceHash:
rejected (139/9) diff 100001 "Invalid nonce; is miner not compatible with NiceHash?" (69 ms)

xmrig 2.5.2

**Comment by xmrig** [comment]
Please provide all possible details. What exactly url used on nicehash, information about miner, etc.
Thank you.

**Comment by welj** [comment]
start in >> xmrig -o 159.8.13.236:3363 -u MY_WALLET.MY_WORKER -p x -t 12 --av=2 --variant 1
linux ubuntu 16.04

**Comment by adem4ik** [comment]
@welj I think you should use "cryptonightv7.LOCATION.nicehash.com:3363" instead of IP.

**Comment by bmatthewshea** [comment]
If using the command line, have you added the `--nicehash` option per the README/`--help`?

If using a config file - something like this will do:
```
    "pools": [
        {
            "url": "cryptonightv7.usa.nicehash.com:3363",
            "user": "xxxxxxxxxxyour_walletxxxxxxxxxx",
            "pass": "x",
            "rig-id": CPUrig1,
            "nicehash": true,
            "keepalive": false,
            "variant": 1
        }
    ],
```
