### ISSUE TITLE
 HUGE PAGES

### ISSUE THREAD

**Issue by Alijamali** [xmrig/xmrig#552]
HUGE PAGES:   unavailable, disabled
but
[2018-04-14 13:40:04] new job from pool.bytecoin.party:3333 diff 1000
[2018-04-14 13:40:10] accepted (1/0) diff 1000

now 
i dont know 
hash accept in pool ?
or not ?

**Comment by 2010phenix** [comment]
yes accept.. us you can see in log...
but why you open issue with Huge page?

you need start miner with Admin right.
after that restart windows
and if Huge page available - it's enabled and you can have MORE Hashrate ;)
