### ISSUE TITLE
xmrig-2.6.0-beta2 doesn't care of print-time setting

### ISSUE THREAD

**Issue by adem4ik** [xmrig/xmrig#554]
**Preconditions:**
xmrig-2.6.0-beta2-gcc-win64.zip or xmrig-2.6.0-beta2-msvc-win64.zip
Windows 10 x64

1) Set `print-time` to non-standard inside config.json, i.e. `"print-time": 30,`
2) Start the miner

**Result:** Speed is printed every 60 seconds
**Expected result:** Speed is printed every 30 seconds

**Comment by xmrig** [comment]
Fix will be included to next beta3 version.
Thank you.

**Comment by xmrig** [comment]
Changes now in dev branch, if no critical bugs will be found I release beta3 tomorrow.
