### ISSUE TITLE
Where i can find libuv.a?

### ISSUE THREAD

**Issue by Omnividente** [xmrig/xmrig#56]
Hi, i try compiled x32 version on win 10x64
I installed msys64, installed Libuv x32 (libuv-x86-v1.13.1.build12.exe), then
pacman -Sy
pacman -S mingw-w64-i686-gcc
pacman -S make
pacman -S mingw-w64-i686-cmake
pacman -S mingw-w64-i686-pkg-config

cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DUV_INCLUDE_DIR="c:\libuvx32\include" -DUV_LIBRARY="c:\libuvx32\libuv.lib"
make

And i get error 
https://farm5.staticflickr.com/4386/35575418664_407eb9845d_o.png

Where i can find libuv.a 1.13.1? i find it in version libuv 1.8.0, but it very old version.

**Comment by sk3lk0** [comment]
ты нашел?
