### ISSUE TITLE
No hashes. 

### ISSUE THREAD

**Issue by auroracoin** [xmrig/xmrig#560]
No hashes. Trying to do turtle coin. For that fact any cryptonight coin. <a href="https://imgur.com/EPD3RaE"><img src="https://i.imgur.com/EPD3RaE.jpg" title="source: imgur.com" /></a>

**Comment by Jomtek** [comment]
change algorithm and check your wallet

**Comment by auroracoin** [comment]
Algo is cryptonight-lite. Why check my wallet?
