### ISSUE TITLE
Pool says 0 workers

### ISSUE THREAD

**Issue by Jomtek** [xmrig/xmrig#561]
Minergate says 0 workers when 'im mining.
I tried to refresh, but it stills 0 workers.

![bienvenidos](https://user-images.githubusercontent.com/26415769/38938906-fe110e48-4326-11e8-9c22-83862e0bce0e.PNG)

**Comment by 2010phenix** [comment]
this is tooooooo laaag pool. Need long long refresh...
Try another pool
