### ISSUE TITLE
Advanced threads mode

### ISSUE THREAD

**Issue by xmrig** [xmrig/xmrig#563]
In **v2.6.0-beta3** added **advanced threads mode** and extended low power modes.

## Advanced threads mode
Now `threads` field in config can accept object with individual threads configuration:
```json
"threads": [
        {"low_power_mode": true,  "affine_to_cpu": 0 },
        {"low_power_mode": false, "affine_to_cpu": 1 },
        {"low_power_mode": 1,     "affine_to_cpu": 2 },
        {"low_power_mode": 3,     "affine_to_cpu": false }
],
```

**low_power_mode** number between `1` and `5` or boolean, `false` equal to `1` and `true` equal to `2`. When set to a number N greater than 1, this mode will increase the cache usage and single thread performance by N times.
**affine_to_cpu** This can be either false (no affinity), or the CPU core number.

Changed huge pages allocation strategy, now each thread allocate huge pages by self.

### Backward compatibility
* Miner can work with config from previous versions, where is threads set as number or `null`.
* Options `av` and `cpu-affinity` has no effect in advanced mode.
* New option `hw-aes` works only in advanced mode.
* Threads array compatible with xmr-stak.

### New --av modes
* `--av=5` Triple hash mode
* `--av=6` Quard hash mode
* `--av=7` Penta hash mode
* `--av=8` Triple hash mode (Software AES)
* `--av=9` Quard hash mode  (Software AES)
* `--av=10` Penta hash mode  (Software AES)

## Known issues
* [ ] Don't use **v2.6.0-beta3** for ARM CPUs. ARM support now partially broken.

**Comment by septuig** [comment]
How to config "Advanced threads mode". 
My CPUs: 
CPU: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz (2) x64 AES-NI
CPU L2/L3: 10.0 MB/50.0 MB
Thank you.

**Comment by sergneo** [comment]
the beta3 version does not have AES CPU like Core2 Duo Quad Xeon running a bit slower

**Comment by 2010phenix** [comment]
Who extremely want Advanced threads mode for big L3 cache and without L4 cache
Any test and good Hashrate up ?

**Comment by nsummy** [comment]
I want to personally thank you for adding in the pentahash mode.  I am testing it out right now.  The XMR-Stak version has an issue where it will eventually dip down to half the hash rate.  Stopping and starting the miner fixes it immediately.  They claim its throttling or overheating, but I know its not.  I'll update here as to whether the same thing happens.  Thank you!

**Comment by artcannibal** [comment]
Hi, 
how to set "affine_to_cpu":  to CPU socket 2 or 3 or 4 in multiprocessor platform?
And additiona question:
New Intel CPU (like Xeon Silver 4114) has a lot of L2 cache +L3 cache (20Mb+28Mb in dual platform), will new versions of xmrig support to use them for more prefomance?

**Comment by DarthMiner88** [comment]
Guyz, what should be the instruction for cpu-affinity, if i want to start xmrig from the 5th core, i have a Ryzen 5 2600, but the first 4th cores im planning to use another miner for a different algo

**Comment by bitcoin981** [comment]
Hola buenas noches quisiera saber ya obtener mis criptomonedas ethereum y bitcóin USDT. Att Julio Cesar Mena Diaz 
Juliocesarmenadiaz03@gmail.com
+524774807526

**Comment by makhamakha** [comment]
makhamakha colbertmakhale@gmail.com +27734308622
