### ISSUE TITLE
libmicrohttpd.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wsm3** [xmrig/xmrig#567]
Hi!

```
root@server:~//xmrig/build# ./xmrig
./xmrig: error while loading shared libraries: libmicrohttpd.so.10: cannot open shared object file: No such file or directory
```

What is the problem?

**Comment by rexsllemel** [comment]
I got same problem using kali linux but there is no error in ubuntu ,what could cause the problem? should I rebuild also the xmrig? how can it be done?

**Comment by keith24** [comment]
> how can it be done?

The instructions at [github.com/xmrig/xmrig/wiki/Build](https://github.com/xmrig/xmrig/wiki/Build) worked for me
