### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by wsm3** [xmrig/xmrig#568]
Hello!

I build with 
`cmake .. -DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libuv.a`
but after run 
`./xmrig: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./xmrig)`

It is possible to compile with GLIBC_2.14 static?

**Comment by wsm3** [comment]
CMakeLists.txt

`option(WITH_LIBCPUID **"Use Libcpuid" OFF)**
option(WITH_AEON     "CryptoNight-Lite support" ON)
option(WITH_HTTPD    "HTTP REST API" OFF)
option(BUILD_STATIC  "Build static binary" OFF)`

`./xmrig: /lib64/libc.so.6: versionGLIBC_2.14' not found (required by ./xmrig)``

**Comment by JKLHJ** [comment]
![qq 20180421120332](https://user-images.githubusercontent.com/30529699/39080174-18c7e77a-455c-11e8-9888-7a0968149dcb.png)
Yes, I also encountered the same problem, how to statically link libraries? Make it run in any version of GLIBC?

**Comment by wsm3** [comment]
I decided like this

`cmake .. -DWITH_LIBCPUID=OFF -DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libuv.so -DBUILD_STATIC=ON`


/usr/lib/x86_64-linux-gnu/libuv.so - is static link
