### ISSUE TITLE
Homebrew XMRig version is behind (2.5.1)

### ISSUE THREAD

**Issue by borzaka** [xmrig/xmrig#569]
Version
2.5.1
[http://www.brewformulas.org/Xmrig](http://www.brewformulas.org/Xmrig)

I think the latest stable is 2.5.2, which was released 25 days ago.

**Comment by ilovezfs** [comment]
I've now shipped 2.5.2 in Homebrew:
https://github.com/Homebrew/homebrew-core/pull/25819
https://github.com/Homebrew/homebrew-core/commit/875a10345e9b26f27437a260a8e486621495879b
