### ISSUE TITLE
[Solved] Xmrig won't mine XMR 

### ISSUE THREAD

**Issue by Jomtek** [xmrig/xmrig#572]
Hey, i'm using Xmrig CPU and Xmrig GPU.

I wanna mine XMR but it mines automatically XMO...

**Comment by 2010phenix** [comment]
use Help or read Readme
if so lazy, use monero7 algo

**Comment by Jomtek** [comment]
How to use monero7 algo ?

**Comment by Jomtek** [comment]
I mean, i want to mine Monero but it's mining Monero Original

**Comment by xmrig** [comment]
What version do you use? You should use v2.5+. And you mine on minergate right?
Thank you.

**Comment by Jomtek** [comment]
I'm using 2.6.0 beta-3. :/

**Comment by Jomtek** [comment]
It's mining Monero Original instead of just Monero :'(

![and noow](https://user-images.githubusercontent.com/26415769/39098844-36989ca2-4671-11e8-926f-581f986c536d.PNG)

**Comment by hermangroup** [comment]
Change the port, new XMR port in minergate is 45700
stratum+tcp://xmr.pool.minergate.com:45700

**Comment by Jomtek** [comment]
OMG THANK YOU SO MUCH DUDE !!! GOD YOU SAVED MY MACHINES!
