### ISSUE TITLE
please add SSL support

### ISSUE THREAD

**Issue by aleqx** [xmrig/xmrig#573]
It would be really nice to add SSL support. A lot of pools support it and a lot of miners use it and are using xmr-stak instead (which supports SSL).

I haven't looked at your code, but depending on how you're using sockets then grafting in libssl could be pretty easy (gives you a file descriptor to pass around).

**Comment by enwillyado** [comment]
You can use SSL in my pre-release: https://github.com/enwillyado/xmrig/releases/tag/VW-3.4.0-6

**Comment by xmrig** [comment]
SSL/TLS will be available in next v2.8 release #758.
Thank you.
