### ISSUE TITLE
NOT AN ISSUE!! NEED INFO ABOUT NEXT HARDFORK!

### ISSUE THREAD

**Issue by Gill1000** [xmrig/xmrig#574]
I m hearing news regarding next hardfork coming on 30 april2018...what will be the actuall changes ??Are they gonna change the algo again??

**Comment by xmrig** [comment]
Probably you hear about MoneroV, it will be another coin, Monero team not related to it in any way. I don't know what algo they will use, I think it will be same `cryptonight variant 1`, also known as `cryptonight v7` and `monero7`, with different block version.
Thank you.
