### ISSUE TITLE
Is the older version 2.5.0 affected by recent critical bug ?

### ISSUE THREAD

**Issue by tarris034** [xmrig/xmrig#576]
> Fixed critical bug, in some cases miner was can't recovery connection and switch to failover pool, version 2.5.2 affected. If you use v2.6.0-beta3 this issue doesn't concern you.

So the older 2.5.0 version is not affected ? 

Sorry for asking this but want to be 100% sure as I'm using your great miner on many machines and don't want to bother with updating if not needed. I only update when there's critical bug or change in the algo.

Already updated the proxy to 2.5.3, Thank You for your great work!

**Comment by xmrig** [comment]
> So the older 2.5.0 version is not affected ?

Exactly right. Thank you.
