### ISSUE TITLE
Doesn't compile on raspberry pi zero. 

### ISSUE THREAD

**Issue by dcherrera** [xmrig/xmrig#578]
I believe its ARMv6 but I'm not sure I'm a shade tree programmer. I have spend 8+ hours trying. can anyone either make the changes necessary to the source or create a binary? raspberry pi zero runs rasbian which is a ubuntu port running gcc 6.3

Error code it gives is
[  2%] Building CXX object CMakeFiles/xmrig.dir/src/api/Api.cpp.o
c++: error: unrecognized command line option ‘-maes’; did you mean ‘-mapcs’?
CMakeFiles/xmrig.dir/build.make:62: recipe for target 'CMakeFiles/xmrig.dir/src/api/Api.cpp.o' failed
make[2]: *** [CMakeFiles/xmrig.dir/src/api/Api.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig.dir/all' failed
make[1]: *** [CMakeFiles/xmrig.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I added armv61 to cmake/cpu.make. I'm kinda at a loss for what to do next

similar to issue 216 but nothing there gives the answer since they did a bug fix and it was for ARMv7

**Comment by dcherrera** [comment]
1000. I live off grid and putting this together is cheaper than running the 100+ laptops i have sitting around. I also have investors lined up. I can run 1000 zeros on 700watts. If i have a 2kw solar setup it would be more than enough.

**Comment by dcherrera** [comment]
How do i add armv61 to the cpu.cmake file?

**Comment by BlackMulch** [comment]
@DrStein99 The Pi's (Pi-zero, Pi-2, and Pi-3) total hashrate is low, but hashes per watt is actually not terrible, ~10h/s per watt I think, with some configuration tuning.

**Comment by dcherrera** [comment]
Thats why im trying to get xmrig on  the zero. I live off grid and solar is my only option and even low h/s add up when you put up multiples. I want to set miners to run 24/7 because where I live its next to impossible to make a living. I already have a set of laptops running over 1kh/s and iff i add pi0's to each usb and then start adding them to the array i could start seeing some returns. right now i make ~-$3 a day meaning im loosing money. so once i get solar set up i should make $2 a day and the solar will be payed off in a year or less because I'm building the arrays myself for ~$.20 per watt. I already own and use the batteries needed and they payed for themselfs long ago. so at about $600 invested I will shortly have a 2.5kw setup and i want to push as many hashes as possible to get it payed for and be in the clear :) Any help would be appreciated to get this running on the pi0.

**Comment by BlackMulch** [comment]
I have not had success with xmrig on the Pi-zero. Previously, I've had cpuminer-multi running on the zero, but I'm not sure if it's been updated for the new xmr pow. Support for ARMv6 would be nice, but might run into issues similar to some older devices since the new proof of work: https://github.com/xmrig/xmrig/issues/446

I'll be excited if ARMv6 support comes for my fleet of Pi-zeros, but I think there are probably higher priority items for the devs at the moment.
