### ISSUE TITLE
Can't compile x64 in VS 2017

### ISSUE THREAD

**Issue by Leo1906** [xmrig/xmrig#58]
I have no problem compiling the project in x86 (different project file, created with cmake and VS 2017 (32 Bit) compiler).
But as soon as it gets to x64 it fails. I build libuv correctly and gave the correct path when using cmake. When trying to build the release in Visual Studio I get 44 errors saying:

C:\Users\root\Downloads\xmrig-master\build\Release\xmrig.exe : fatal error LNK1120: 44 nicht aufgel÷ste Externe Symbole

or 

App.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "uv_signal_start".

That means that it can't find the libuv, right? Or where's the error?
But why does it work for 32 bit application and not for 64 bit?

Only XMRig can't be build. The rest of the project can be build without any problem.
How do I fix this error?

Thanks a lot! :)

**Comment by xmrig** [comment]
Looks like you point cmake to wrong libuv version, maybe 32bit. You need 2 libuv one for 64bit one for 32bit.
Thank you.

**Comment by Leo1906** [comment]
Yeah of course I compiled libuv for x64 and for x32. For building the x64 XMRig I pointed to libuv (x64). Do I need to point to x32 as well?

**Comment by xmrig** [comment]
64bit build required 64bit libuv
How do you build libuv? Did you use `vcbuild.bat`? If yes was you add `x64` param?

This error mean linker not found suitable symbols, wrong lib/arch. CMake check only existence of .lib file.

**Comment by Leo1906** [comment]
I thought I did so .. I have done everything aggain from scratch now and it works! :)
Thanks for your help :)
