### ISSUE TITLE
Feature Request - Support Stellite's algorithm change from CryptonightV1 to a slightly modified variant

### ISSUE THREAD

**Issue by stellitedev** [xmrig/xmrig#581]
# Summary  

After forking to V7 without the presence of nicehash our network was stable, now since that V7 works for all block versions on it we're making a small change to the V7 variant.  

# Details 
You can see the simple modification we've done in [this](https://github.com/stellitecoin/Stellite/tree/V4) branch on our main repo   

# Testing the new variant  
For convenience we have already set up a testnet pool [here](https://testxtl.anypool.net/#), you can use the following address for testing purposes.  

```
Se3EkZfYDpXhaVqyBnAkkjfM1D3RWKeEECMJtAMjCuDE1qaQyEVUqcpXg6b49fCFSeKUD7Xvtzp5nFNPrFrFBVCG1C91AmN8d 
```

Hope you take our request into consideration soon as we plan to implement this onto our mainnet as soon as possible and a good amount of our miners are fond of your miners.  Thank you.

**Comment by stellitedev** [comment]
cryptonight_xtl, sounds well and good

**Comment by bobbieltd** [comment]
I hope xmrig will support both syntaxes : algo cryptonight variant xtl and algo crypronight-xtl no variant like IPBC.

**Comment by xmrig** [comment]
@stellitedev Would be nice if Stellite pools will support [extended job object](https://github.com/xmrig/xmrig-proxy/blob/dev/doc/STRATUM_EXT.md#12-extended-job-object) on each job object should added one field `"algo":"cn/xtl"`. Miner will use this hint to set proper variant automatically.
Thank you.

**Comment by ahmyi** [comment]
https://testnet.xtlpool.com has added the extended job object. This test pool is also using the cryptonight xtl variant changes

**Comment by xmrig** [comment]
I added Stellite support in feature-algo branch https://github.com/xmrig/xmrig/commit/3df99fbcedb0d736e7c16e51b5d988e92518fe6d for CPU miner.
It will be included in next CPU miner/proxy release after all in **Wave 1** will done https://github.com/xmrig/xmrig-proxy/issues/168

@ahmyi just `algo` enough, no need send `variant`. Thank you.

**Comment by ahmyi** [comment]
@xmrig noted. I have made the changes to the pool removing the variant and will test from given branch...

**Comment by ahmyi** [comment]
The new miner looks awesome btw..kudos..shows the correct algo when mining to stratum+tcp://testnet.xtlpool.com:3333 
![image](https://user-images.githubusercontent.com/630603/39338630-84e188dc-49f6-11e8-8e3a-561a53b15df4.png)

**Comment by xmrig** [comment]
My bad, I missed that `table` changed too, but now I'm confused, because `testxtl.anypool.net:3333` successfully accept wrong shares https://i.imgur.com/ZmGZztm.png

**Comment by xmrig** [comment]
@stellitedev Please provide reference hashes, preferably for these 5 inputs https://github.com/xmrig/xmrig/blob/feature-algo/src/crypto/CryptoNight_test.h#L29 but other hashed is ok too. Also look like your changes in table has no effect, so @ahmyi something not ok with your pool.

**Comment by hayzamjs** [comment]
Our team has added a few tests for the second variant in [this](https://github.com/stellitecoin/Stellite/commit/b4710260a9dd746d06617b315aa9d001efe9f783) commit, and one more thing, we hope there will be a way to manually specify the cn/xtl variant for the pools that don't have the auto detect feature too?

**Comment by xmrig** [comment]
Thank you for test hashes. Of course variant can set manually, I added documentation how it works https://github.com/xmrig/xmrig/blob/dev/doc/ALGORITHMS.md
Also I added block version check, so variant `xtl` will work after new version of miner released. No need change it after the fork.
