### ISSUE TITLE
Errors Windows  on a computer

### ISSUE THREAD

**Issue by DaiziOuyang** [xmrig/xmrig#583]
I'm sorry, there was an error in the compilation of Windows. Can Error: could not load cache solve this problem? I'm a beginner who wants to learn and study very much.

**Comment by Gill1000** [comment]
Plz upload photo of it....I guess delete the all files in build folder and again start cmake

**Comment by DaiziOuyang** [comment]
![yx4rwk 9u i9 9x 5502mgs](https://user-images.githubusercontent.com/38435398/39228438-d0e816fe-4890-11e8-80a4-f28840a6e6a8.png)

**Comment by DaiziOuyang** [comment]
源码下载错了？？
The source download is wrong??

**Comment by DaiziOuyang** [comment]
xmrig-master 怎么编译 ？？有没有教程
How does xmrig-master compile?? There are no tutorials

**Comment by DaiziOuyang** [comment]
Compile directly with the cmake tool?

**Comment by DaiziOuyang** [comment]
There are tutorials for msys.？
