### ISSUE TITLE
how can i   use xmrig  over the http-proxy 

### ISSUE THREAD

**Issue by wayne3407** [xmrig/xmrig#585]
my servers is using http-proxy connecting to the internet, I can ping success to the pool,but the xmrig  say ,can out connceting the pool ,time out .
any one can help me ?

**Comment by 2010phenix** [comment]
interesting question... on few computer have same problem....
any solution or temp solution?
Thanks

**Comment by sv0** [comment]
@wayne3407 Also you can use proxychains for this purpose https://github.com/rofl0r/proxychains-ng

**Comment by wayne3407** [comment]
@sv0  hi ,i have already try this way,but it doesn't work
