### ISSUE TITLE
XMrig not working for CryptoNightLite V1 coins

### ISSUE THREAD

**Issue by vlad230** [xmrig/xmrig#586]
I have been trying to mine a coin using xmrig-2.6.0-beta3-gcc-win64 that is based on CryptoNightLite V1 but I get all my shares rejected. 

I have been using xmrig for some time with other coins and is working fine.

Are you going to support this new algo?

**Comment by xmrig** [comment]
What coin? I know only one `CryptoNightLite V1` at this moment and this is Turtlecoin and it work fine.

* Set global option algo: `"algo": "cryptonight-lite",`
* Set variant on each pool: `"variant": 1`  https://github.com/xmrig/xmrig/blob/master/src/config.json#L24

**Comment by vlad230** [comment]
Thanks a lot for the fats reply! I wasn't using the **"variant": 1** setting. It's working fine now.

Is there a detailed list of all the parameters, values & what they do, other than the comments in the config.json file?
