### ISSUE TITLE
Unable to get Max CPU

### ISSUE THREAD

**Issue by diggles9991** [xmrig/xmrig#59]
I cannot get XMRig to use Max CPU, keeps stopping around 37%.
My config file is below.

{
    "algo": "cryptonight",
    "av": 0,
    "background": true,
    "colors": true,
    "cpu-affinity": null,
    "donate-level": 1,
    "log-file": null,
    "max-cpu-usage": 100,
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "safe": false,
    "syslog": false,
    "threads": null,
    "pools": [
        {
            "url": "xmr.pool.minergate.com:45560",
            "user": "diggles9991@gmail.com",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        }
    ]
}

**Comment by stewis** [comment]
What CPU model are you using?

**Comment by xmrig** [comment]
`max-cpu-usage` is option to limit maximum thread count and visible CPU load as well. Doesn't mater how many threads support your CPU, only matters how many cache in it. On most desktop CPUs 100% visible load impossibility, except AMD FX series.

Example: typical i7 8 threads, 8 MB cache, no need use more than 4 threads (50%) for `--av=1` and more than 2 (25%) for `--av=2`.
