### ISSUE TITLE
Deploy on multible machines

### ISSUE THREAD

**Issue by ggexplorer** [xmrig/xmrig#590]
Anyone that has succesfully managed to deploy xmrig on 500+ machines? Contact me: ggexplorer on telegram with info and $$ for ur time

**Comment by ggexplorer** [comment]
Sorry, I wasnt clear enough. I have admin access to pcs servers and everything...

**Comment by 2010phenix** [comment]
use xmrig-proxy as server and connect other pc as client

**Comment by ggexplorer** [comment]
The problem is the connection.. how to execute the miner on the pc remotely..?

**Comment by 2010phenix** [comment]
login on remote PC if you are owner and start miner
