### ISSUE TITLE
Compiling error on Arch

### ISSUE THREAD

**Issue by darutse** [xmrig/xmrig#591]
Having difficulties compiling on Arch Linux
I tried to compile with gcc-6 just in case:
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/gcc-6 -DCMAKE_CXX_COMPILER=/usr/bin/g++-6
all libs are found:
> -- The C compiler identification is GNU 6.4.1
> -- The CXX compiler identification is GNU 6.4.1
> -- Check for working C compiler: /usr/bin/gcc-6
> -- Check for working C compiler: /usr/bin/gcc-6 -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/g++-6
> -- Check for working CXX compiler: /usr/bin/g++-6 -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found UV: /usr/lib/libuv.so  
> -- Looking for syslog.h
> -- Looking for syslog.h - found
> -- Configuring done
> -- Generating done
> -- Build files have been written to:...

But when I do make it gives me 
> ld: cannot find -luv
> make[2]: *** [CMakeFiles/xmrig.dir/build.make:1111: xmrig] Error 1
> make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/xmrig.dir/all] Error 2
> make: *** [Makefile:84: all] Error 2

and a bunch of garbage on top of that.

**Comment by kpcyrd** [comment]
```
pacman -S libuv
```

**Comment by donovansolms** [comment]
I'm also on Arch but can't replicate your issue. `which libuv` also shows not found as yours, but I can compile just fine. My cmake output is identical to yours.

I previously set my environment up for xmr-stak by installing the following `sudo pacman -S --needed base-devel hwloc openssl cmake libmicrohttpd`, no sure if that might help in this case

**Comment by darutse** [comment]
It compiles without -DCMAKE_BUILD_TYPE=Release

**Comment by k0ste** [comment]
[aur/xmrig](https://aur.archlinux.org/packages/xmrig/)
