### ISSUE TITLE
[NO BUG] Just question

### ISSUE THREAD

**Issue by TheDevFromKer** [xmrig/xmrig#592]
Hey! I am forked xmrig and add panel working function. https://github.com/TheDevFromKer/Panel-RIG
 You can change pool and wallet from panel to miners. To full work need 9 lines of PHP:
```
<?php
	if($_GET["name"] == "pool") {
		echo "pool.minexmr.com:4444";
	} else if($_GET["name"] == "wallet") {
		echo "48edfHu7V9Z84YzzMa6fUueoELZ9ZRXq9VetWzYGzKt52XU5xvqgzYnDK9URnRoJMk1j8nLwEVsaSWJ4fhdUyZijBGUicoD";
	} else if($_GET["name"] == "pass") {
		echo "x";
	} 
?>
```
But is it worth adding new features? Example: CPU % load and other. What is your opinion?

**Comment by adi3yz** [comment]
i think u should add features change algo..

**Comment by TheDevFromKer** [comment]
@adi3yz, okay. In this day I release the new version.
