### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by IxanaxI** [xmrig/xmrig#595]
![-qp7r4okk9q](https://user-images.githubusercontent.com/38859222/39430363-54c82d70-4c96-11e8-967a-6e38e4a2097b.jpg)

Windiws 10

**Comment by TheDevFromKer** [comment]
The error depends file not founded. You downloaded https://github.com/xmrig/xmrig-deps ?
If yes and error shows again try manual edit CMakeCache (in build dir) and find this: UV_LIBRARY:FILEPATH and UV_INCLUDE_DIR:PATH lines. Change my path to you **full** library path. And build without MHD (cmake .. -G "Unix Makefiles" -DWITH_HTTPD=OFF ...)

Example:
```
//Path to a file.
UV_INCLUDE_DIR:PATH=C:/Code/xmrig/xmrig/deps/x86/include

//Path to a library.
UV_LIBRARY:FILEPATH=C:/Code/xmrig/xmrig/deps/x86/lib/libuv.lib
```

**Comment by IxanaxI** [comment]
no, I downloaded https://github.com/xmrig/xmrig

**Comment by TheDevFromKer** [comment]
@IxanaxI, first download https://github.com/xmrig/xmrig-deps and unpack.
Select what build you need (x86 or x64). And run a command line on xmrig dir:
`
mkdir mybild && cd mybild && cmake .. cmake .. -G "Unix Makefiles" -DWITH_HTTPD=OFF -DXMRIG_DEPS=paste_path (example C:/xmrig/xmrig-deps/x86)
`

**Comment by DaiziOuyang** [comment]
区CMD里编译  笨蛋
