### ISSUE TITLE
Donation problem

### ISSUE THREAD

**Issue by DaiziOuyang** [xmrig/xmrig#597]
Xmrig how to remove the donation, how to pay to you once

**Comment by TheDevFromKer** [comment]
Just read https://github.com/xmrig/xmrig/blob/master/src/donate.h#L37
And:
```
constexpr const int kDonateLevel = 0; 
```
Remove donate.

**Comment by DaiziOuyang** [comment]
In that folder? I haven't found it yet.

**Comment by TheDevFromKer** [comment]
@DaiziOuyang in `src` dir

**Comment by DaiziOuyang** [comment]
I can run on win10, but I report this error on the 2008 server. I want to ask for help. I want to know why.
![1](https://user-images.githubusercontent.com/38435398/39483573-7324c3f4-4da5-11e8-845b-c3ad26012a84.png)

**Comment by grafptitsyn** [comment]
@DaiziOuyang, what error message tells you?

**Comment by DaiziOuyang** [comment]
Lose MSVCP140D.dll

**Comment by grafptitsyn** [comment]
@DaiziOuyang, so that’s why xmrig won’t start.

**Comment by xmrig** [comment]
@DaiziOuyang You didn't change build type to `Release`. Change it and rebuild again.
Thank you.

**Comment by DaiziOuyang** [comment]
I changed it and changed to Release at the beginning.

**Comment by DaiziOuyang** [comment]
![o 0_ 3s sv r0wqv2rv pe](https://user-images.githubusercontent.com/38435398/39485951-099f6288-4dad-11e8-8b09-ce086fe2eda8.png)

**Comment by DaiziOuyang** [comment]
现在重新编译又出现了>>CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles". CMAKE_MAKE_PROGRAM is not set. You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
现在重新编译又出现了>>CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
>>CMake Error: CMake was unable to find a build program corresponding to.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
- Configuring incomplete, errors occurred!

**Comment by TheDevFromKer** [comment]
If you want to build in Visual Studio - don`t use "Unix Makefiles" use "Visual Studio 15 2017 Win64" (to x64 ) and "Visual Studio 15 2017" (to x32)

**Comment by adi3yz** [comment]
if u dont know what u doing then just use release version from dev, and pls support dev.. 1 minute from 100 minute not to much. dev also human which need drink and food.

**Comment by enwillyado** [comment]
@DaiziOuyang u can use my version, it is compatible with VS natively.

**Comment by focaeppe** [comment]
@enwillyado 
Thank you
I did try your virsion but after the compilation the miner doesn't work SSL error even when i change  "ssl": true,   to false nothing change

**Comment by DaiziOuyang** [comment]
I've been wrong, but I found that the compiling absenteeism is only 15h/s (i7 7700hq) and you can use your absenteeism to reach 300h/s. Is it a compiler where to forget to modify it?
