### ISSUE TITLE
Best miner yet : request for a additional featire

### ISSUE THREAD

**Issue by Guilty-King** [xmrig/xmrig#6]
Hello sir 
I am very thankful to you for creating this miner it's gives double the hashrate on av 2 mode with hugepages enabled tested on xeon processor 
Double hashrate compared to cpumulti ccminer xmr-stak-cpu 
About 25% extra compared to yam 
All testing done on xeon vm with exact same config 
Tho I request you to add in the http webpage like in xmr-stak-cpu miner 
It really is helpful and saves the effort of ssh into machine 
I hope you are it soon and sorry for being selfish 
Thank you

**Comment by xmrig** [comment]
You right web interface it's good and useful feature, I will think about it.
Thank you.

**Comment by anandanand84** [comment]
@xmrig @Guilty-King I can help with webinterface. what should be done?

**Comment by fpgablr** [comment]
Hi Anand,
I have been tracking this thread as well. Where are you based?

Regards

Ranganath

**Comment by xmrig** [comment]
I have idea for web interface;

* On miner side just REST API, no HTML/JS/CSS only pure data.
* Web interface will be a SPA React.js application, will be open sourced as well.

Benefits:
* Can monitor multiple miner in one page.
* Web interface updates, wont need miner update (until API comparable).
* Anybody can add own web interface/monitoring/etc.

**Comment by anandanand84** [comment]
@xmrig Is there a rest endpoint currently available in the released miners?

**Comment by xmrig** [comment]
No, it currently not available.

**Comment by xmrig** [comment]
In dev branch added HTTP API to both cpu and nvidia versions.
Working miners instances with publicly available API:
http://94.130.19.186:4455/
http://94.130.19.186:4456/

Sample HTML page to get data from API https://gist.github.com/xmrig/c75fdd1f8e0f3bac05500be2ab718f8e

Authorization supported by optional Bearer token.

**Comment by hetmann** [comment]
@xmrig can you make a list of information for the web SPA interface or should we use the API information list?

**Comment by xmrig** [comment]
http://workers.xmrig.info/
