### ISSUE TITLE
FreeBSD super pages support

### ISSUE THREAD

**Issue by vcambur** [xmrig/xmrig#60]
Hi,

Is it possible to add super pages support for FreeBSD (similar to huge pages in Linux) ?
Will there be any benefit ?
Currently without some hacks xmrig won't even compile on FreeBSD

Thanks again for your hard work

**Comment by xmrig** [comment]
Sorry I has zero knowledge about FreeBSD, pull request with fixed build are welcome. If you make short tutorial how build miner on FreeBSD I appreciate that, will try make it. Thank you.

**Comment by lisergey** [comment]
I've tried to compile XMRig on FreeBSD 11.1 with no luck.
But it runs with linux_base-c7 compaitibilty emulator with minor bugs, like refusing to run background if no-root, and ignoring kill signal.
I'd like to help with testing on FreeBSD.

**Comment by vcambur** [comment]
I was able to compile with gcc5 after some tweaks and hacks regarding huge pages and cpu affinity (I have no real knowledge of FreeBSD internals). 
I want to try to compile with gcc7 and find some time to make it go on github..

**Comment by lisergey** [comment]
Hello @vcambur !
any progress on how-to?
How can I help you with it?

**Comment by vcambur** [comment]
Hi,

patch agains master for FreeBSD (tested on 10.3-RELEASE both with clang and gcc7) attached.
to apply after git clone or unzip, cd to xmrig directory and do
`patch -p1 < fbsd-xmrig.txt`
then (per wiki)
`mkdir build
cd build`
(for clang)
`cmake -DUV_LIBRARY=/usr/local/lib/libuv.a -DMHD_LIBRARY=/usr/local/lib/libmicrohttpd.a ..`
(for gcc7)
`cmake -DUV_LIBRARY=/usr/local/lib/libuv.a -DMHD_LIBRARY=/usr/local/lib/libmicrohttpd.a -DCMAKE_C_COMPILER=gcc7 -DCMAKE_CXX_COMPILER=g++7 ..`

@xmrig, can you please review the patch
[fbsd-xmrig.txt](https://github.com/xmrig/xmrig/files/1398218/fbsd-xmrig.txt)

**Comment by xmrig** [comment]
Better if you make this path via pull request, your name also will be appear in commit history.
Anyway thank you, I will check it tomorrow.
