### ISSUE TITLE
How to change default CPU usage

### ISSUE THREAD

**Issue by zyjsuper** [xmrig/xmrig#600]
Please tell me,Thx.

**Comment by zyjsuper** [comment]
I set m_maxCpuUsage(25) 
but it run use 100% of cpu usage always.
how to solve it.

**Comment by BearBang7** [comment]
@zyjsuper how many core have your cpu ?

**Comment by TheDevFromKer** [comment]
maxCpuUsage - this option only to set how miner can use one CPU in percent from 1% to 100%.
If you need usage of CPU not at full capacity just don`t use all threads.
"max-cpu-usage": 75 - load one CPU in percent
"threads": - loading of CPU (simple if have 4 CPUs and use 4 -> get 100% loading.)

**Comment by zyjsuper** [comment]
1core and 2core,all have

**Comment by Meyer01** [comment]
As i know, if you set "threads": 0 than xmrig will calculate the optimal number of cores for use based on CPU cache. 
You can manualy set number of cores for mining by set the number in "threads": 
Xmrig cant use percents of core. If you have 1 core it would be 100% always. If you have 4 cores for example you can choose 25%,50%.75% and 100% of CPU. If 2 cores you have only 50% or 100% options.
