### ISSUE TITLE
Arm

### ISSUE THREAD

**Issue by GodzSoldiers** [xmrig/xmrig#601]
Does This support arm mining like with a home raspberry pi server ?

**Comment by calvintam236** [comment]
I don't think it is effective mining on pi. It is too slow.

https://monero.stackexchange.com/questions/6862/could-i-use-a-raspberry-pi-to-mine-monero

**Comment by GodzSoldiers** [comment]
So its possible  ?

**Comment by BlackMulch** [comment]
Raspberry Pi can get about 10h/s per watt, which is actually pretty good for 'per watt' performance... But the total hashes are still pretty low (despite being efficient): For cryptonight algo, Pi 2 and 3 get about 8-10 h/s, Pi 1 and zero get about 0.75-1 h/s. For cryptonight-lite, triple the hashes.

**Comment by lunhg** [comment]
I could get  14 H/s, up to 21Hs with CPU mining in a ArchLinux (aarch64) with cryptonight-lite.

The only issue i found is that you need to connect with a port that accept low diffs. Generally solves hashes with 300-500 diff, but sometimes solves 1000-1200 diff.

There are any way to use GPU?
