### ISSUE TITLE
donation not working

### ISSUE THREAD

**Issue by focaeppe** [xmrig/xmrig#607]
Hello,
![2018-05-06_23-57-29](https://user-images.githubusercontent.com/34982607/39672163-38e5c5f2-5125-11e8-9646-113474f7dcc6.jpg)
levels 99% donation don't start
donation is 97%  doesnt donating after 6 min.

**Comment by dunklesToast** [comment]
I think the donation system got some randomization some versions ago so it takes some time for it to start. What happens, if you wait ~10 min?

**Comment by Gill1000** [comment]
Check #519

**Comment by xmrig** [comment]
It really epic bug, so v2.6.1 is donation free, because algorithm validation broken for donations.
Thank you.

**Comment by xmrig** [comment]
I make release v2.6.2 with the fix.
Start time is randomized, but only +/- 50%, so for level 99% it from 30 to 90 seconds, for 97% it from 1.5 minutes to 4.5 minutes.
Thank you.
