### ISSUE TITLE
hello, dude

### ISSUE THREAD

**Issue by local139** [xmrig/xmrig#61]
close

**Comment by xmrig** [comment]
s390x cpu it mean IBM System z?

**Comment by local139** [comment]
Yes,IBM System z. like this:
https://github.com/Max-Coin/cpuminer/blob/master/config.sub      for scrypt
https://launchpad.net/ubuntu/xenial/s390x/cgminer      may be for bitcoin miner
hope this 2 link have usefull for you if xmrig add s390x cpu.
i hope xmrig can add s390x cpu in the feature. 
when will be add? dude .
