### ISSUE TITLE
Add StartUp XMRIG

### ISSUE THREAD

**Issue by LearnMiner** [xmrig/xmrig#611]
How can i add StartUp XMRIG in Regedit? I tried 

void Startup(TCHAR* path) {
	HKEY hKey = NULL;
	RegOpenKey(HKEY_CURRENT_USER, L"Software\\Microsoft\\Windows\\CurrentVersion\\Run", &hKey);
	RegSetValueEx(hKey, L"xmrig miner", 0, REG_SZ, (PBYTE)path, lstrlen(path) * sizeof(TCHAR) + 1);
	RegCloseKey(hKey);
}

But when i compile and open exe no add in regedit :(

**Comment by snipeTR** [comment]
your bestard hacker (lamer)
