### ISSUE TITLE
new format for huge pages diag - pls describe meaning of fields after READY (CPU) threads

### ISSUE THREAD

**Issue by lisergey** [xmrig/xmrig#614]
@xmrig, pls describe what each number in each field in the string means:
`READY (CPU) threads 6(12) huge pages 0/12 0.000000% memory 24.0 MB`
what is good sign and what is not?
thank you

**Comment by xmrig** [comment]
`threads 6(12)` you run 6 double hash threads, so it 12 virtual threads.
`huge pages 0/12 0.000000%` 0 of 12 (0%) huge pages allocated, it's bad.
`memory 24.0 MB` threads require 24 (6 * 2 * 2) MB of memory, it should fit into CPU cache.
