### ISSUE TITLE
Unspecified launch faillure

### ISSUE THREAD

**Issue by Qurmo** [xmrig/xmrig#621]
![xmrig error](https://user-images.githubusercontent.com/32374369/39829401-984f51ac-53be-11e8-9345-757717f6f85d.jpg)
I get message as displayed in the picture.  both with CUDA 8 as CUDA 9 version on Windows 10.  What am I doing wrong?

**Comment by aka-lex** [comment]
reduce threads and / or boost bfactor

**Comment by Qurmo** [comment]
and how do I do that?  sorry kinda a beginner in this :s

**Comment by aka-lex** [comment]
```
    "threads": [
        {
            "index": 0,
            "threads": 30,
            "blocks": 24,
            "bfactor": 6,
            "bsleep": 25,
            "affine_to_cpu": false
        }
    ], 
```
change the values in the configuration file of the miner.
in the threads section

**Comment by Qurmo** [comment]
do you have to equally downgrade them or just 1 is enough?  ex: only the number off threads?
