### ISSUE TITLE
v2.6.2 Low Difficulty Share Rejected (AEON)

### ISSUE THREAD

**Issue by DeadManWalkingTO** [xmrig/xmrig#623]
OS: Ubuntu 16.04 / Win7
CPU: Intel x64 / Arm x64
Xmrig: v2.6.2
Coin: AEON
Low Difficulty Share Rejected

Downgrade to v2.5.3 works fine!

Any suggestions?

Thank you!

**Comment by xmrig** [comment]
Algorithm options for AEON:
```json
{
    "algo": "cryptonight-lite",
    ...
    "pools": [
        {
            ...
            "variant": -1
        }
    ]
}
```
v2.6 supports config files from v2.5, if breaking changes in config file happen, major miner version will change to v3.
Thank you.

**Comment by 2010phenix** [comment]
khm, strange... try 2.6.2 with TurtleCoin on (stratum+tcp://trtl.pool.mine2gether.com:1115)
used cn-lite/1 and try cn-lite/0 - confirm Share Rejected
