### ISSUE TITLE
"virus detected" on downloading releases

### ISSUE THREAD

**Issue by khavernathy** [xmrig/xmrig#626]
Downloading any of the recent .zip releases on multiple browsers (chrome, edge) gives me a "virus detected" error and my OS (windows10 64bit) deletes the file automatically every time.

**Comment by khavernathy** [comment]
It's detected on Windows10 as a Trojan virus

**Comment by Rafficer** [comment]
It's a miner, they get flagged as Virus by pretty much any AV. Just whitelist it.

**Comment by khavernathy** [comment]
Firefox download worked.

This doesn't happen for any other miner in my experience, and I've downloaded many.

**Comment by Pythonic-Rainbow** [comment]
I dont think miners that are flagged  by AVs are resolvable
