### ISSUE TITLE
2.6.2:  supportxmr.com:3333: low difficulty share

### ISSUE THREAD

**Issue by tkalfaoglu** [xmrig/xmrig#638]
With 2.6.2 and cn-heavy, I'm getting low difficulty share errors:

rejected (0/3) diff 4999 "Low Difficulty share" (254ms)

Windows 8.1.. 
in config:  av:0 , huge-pages: true, variant:0

**Comment by xmrig** [comment]
For Monero algorithm should be `cn` not `cn-heavy` and variant is `1`. https://github.com/xmrig/xmrig/blob/master/doc/ALGORITHMS.md
Thank you.

**Comment by tkalfaoglu** [comment]
great help thank you.. The machine instantly became unresponsive after the changes.. Now I know it's working correctly! :)
