### ISSUE TITLE
xmrig using all pagefile, even with huge pages disabled

### ISSUE THREAD

**Issue by shigutso** [xmrig/xmrig#642]
After leaving xmrig (cpu) mining for a while, I realized that the pagefile.sys file in windows got very large (10GB+) and the computer hangs after ~48h.

I thought that it was a problem with huge pages and then tried to disable it, but the issue persisted

Is there anything else I can do to stop xmrig from using a lot of the windows pagefile?

Thanks

**Comment by xmrig** [comment]
Sounds like memory leak, can you make screenshot of Task Manager where I can see miner process really eats memory and please provide all possible information, including config files (without wallets).
Thank you.

**Comment by shigutso** [comment]
Thanks, I'll be updating to the latest version to see if it fixes the problem, if it doesn't I'll be posting here my full specs and config files

The task manager shows xmrig using as low as 10MB of RAM, but the pagefile on Windows just keeps getting bigger and bigger until the OS crashes, it's very odd, and if I just restart xmrig, the pagefile frees up memory and the process of growing slowly starts again

**Comment by xmrig** [comment]
Any updates? Is issue solved by updating to latest version?
Thank you.
