### ISSUE TITLE
Put config.json inside xmrig.exe without getting "no config.json file found error"

### ISSUE THREAD

**Issue by ariadarkkkis** [xmrig/xmrig#643]
Hi
I've done some edits and added my URL and username and password to CommonConfig.cpp and Config.cpp but still getting "No config.json file found".
I dont want to have config.json
any help?

**Comment by Yaropolkgh** [comment]
Hi ariadarkkkis bro
me also trying to do this but i dont know how add that 
Can u explain how did u add the url, username and password into that cpp files bro

**Comment by ariadarkkkis** [comment]
No one knows??

**Comment by ariadarkkkis** [comment]
@xmrig what should I do?

**Comment by Gill1000** [comment]
Check out previous issues there is your answer..or maybe closed one.

**Comment by xmrig** [comment]
Duplicate #608 also older closed issues.
Thank you.
