### ISSUE TITLE
Config Help for VM

### ISSUE THREAD

**Issue by hierdem** [xmrig/xmrig#645]
For various reasons I'm forced to run xmrig on a Hyper-V VM with x2 E5-2660 v2 CPU.

Any recommendations about what should be ideal CPU config for the VM? Right now, I'm running 30 (15x2) cores for VM, since each CPU comes with 25 MB cache, it seems sufficient.

What should be the affinity configuration? From what I could test best performance comes when first 12 cores of both of the CPUs are used. It tested using cores 0-11 and 15-26 on xmr-stak, how should it be set on xmrig? Of course I'm open for suggestions for different configs.

I can get around 1 KH/s while using xmr-stak but really wish to try xmrig with optimal configuration. Not sure if this is a good score for this kind of CPU combination or not, so I would appreciate all the input.

**Comment by QwertyJack** [comment]
1 KH/s is the limit of this kind of cpu. Any optimization would not increase the hashrate from my point of view.
