### ISSUE TITLE
--background doesn't work on FreeBSD

### ISSUE THREAD

**Issue by avidmills** [xmrig/xmrig#651]
Hi,

When I run my config without -B set, it works fine. When I set -B, xmrig never gets running. The log shows that it makes it up to the point of printing out the COMMANDS: line, but never prints the READY line after that. The web interface never loads either.

**Comment by lisergey** [comment]
@avidmills you can use xmrig from ports
`/usr/ports/net-p2p/xmrig`
it is equipped with good startup script which allows to run xmrig in background in FreeBSD-way

**Comment by avidmills** [comment]
I have installed xmring both from ports and from pkg, the startup script did not change behavior. I will do a more thorough check just to verify though.

Thanks,
Dillan
________________________________

**Comment by trasherdk** [comment]
I am confused.
Is this a code issues thing, or a general newbie "please help me" thing?
Maybe a note about, directing general help/support/FAQ to stackoverflow,
while questions towards the code, goes here.
I don't understand questions like "why doesn't this software support XYZ coins" ?
Please educate me.

**Comment by avidmills** [comment]
@lisergey you are right, when I previously tried running with the sysrc startup script, I also had background:true set, which broke it I think. Removing that now shows it working properly. 

Perhaps a note could be added to the freeBSD section of the wiki concerning using sysrc for background operation instead of the xmrig background flag.

**Comment by asmaek91** [comment]
u should put background true in config...
when config file is used the comand line options don t work!
