### ISSUE TITLE
Create config option

### ISSUE THREAD

**Issue by trasherdk** [xmrig/xmrig#652]
As I understand, XMRIG is pretty good at detecting the hardware it's running on,
and set some sane defaults. All good so far.

Why not give the option to create a config file, with those detected defaults,
so one could experiment with some tuning of those, not so default parameters.
Affinity comes to mind.

Just a thought.

Thanks for your work.

**Comment by lisergey** [comment]
go to config.xmrig.com
it is already!

**Comment by trasherdk** [comment]
Why is this closed without a response?
