### ISSUE TITLE
how to change xmrig cpu miner process name

### ISSUE THREAD

**Issue by lighttech1** [xmrig/xmrig#654]
hello, i would like to change xmrig cpu miner process name in task manager can anyone help me please

**Comment by k0ste** [comment]
`mv xmrig not_xmrig`

**Comment by xmrig** [comment]
Change it in [version.h](https://github.com/xmrig/xmrig/blob/master/src/version.h) and recompile or use alternative way, tools like Resource Hacker can change it too without compilation.
Thank you.

**Comment by emailyc** [comment]
how to change the name of the compiled .exe file?
