### ISSUE TITLE
我想换一个图标 伪装成

### ISSUE THREAD

**Issue by xiaoyueraymond** [xmrig/xmrig#661]
伪装成 WINdows 命令处理程序

**Comment by 2010phenix** [comment]
write on English or use translate

**Comment by QwertyJack** [comment]
He wanna change the icon.
Just compile yourself.

**Comment by xiaoyueraymond** [comment]
i want to
Disguised as a system program ，what should I do

**Comment by xiaoyueraymond** [comment]
i want to
Disguised as a system program ，what should I do

**Comment by xiaoyueraymond** [comment]
@QwertyJack   我想换一个名字和图标 我要怎么做？现在是xmirg cpu miner  我想换个图标换个名字，普通人就不知道是挖矿程序

**Comment by xiaoyueraymond** [comment]
@2010phenix  i want to
Disguised as a system program ，what should I do

**Comment by xmrig** [comment]
Duplicate #654

**Comment by QwertyJack** [comment]
@xiaoyueraymond 你这样不好吧
很简单啊 编译好的那个包，用vs打开替换图标即可
