### ISSUE TITLE
Ryzen 2 2200g with Vega 8: mine with iGPU

### ISSUE THREAD

**Issue by emailyc** [xmrig/xmrig#662]
Can XMRig CPU miner mine with both the CPU and the iGPU, or do I need run the CPU + GPU miner separately?

**Comment by QwertyJack** [comment]
Seperately with xmrig and xmrig-amd.
Or you can move to xmr-stak.

**Comment by xmrig** [comment]
So previous comment exactly right, I close issue now.
Thank you.
