### ISSUE TITLE
Can I set up XMRig without connecting to the pool but mine fake coins through localhost as a pool?

### ISSUE THREAD

**Issue by mikegscott** [xmrig/xmrig#663]
I am trying to set up XMRig miner but mining is blocked in my network. What I at least need to do is to set up XMRig mining but mine fake coins or just run mining algorithm without mining anything real (without pool username etc).

**Comment by QwertyJack** [comment]
Is that testing mode?
BTW Why to do that？

**Comment by mrganapathy** [comment]
Yeah you can say testing mode. I just want to simulate a local pool (or simulate mining) to see how does it affect computer resources.

**Comment by QwertyJack** [comment]
As far as I know, xmrig does not support testing mode. Without instructions from a pool, the worker may not work at all.

**Comment by du0ngpv** [comment]
Are you a hacker ? Yes you can !
You must capture TCP message from miner to pool then replay it , something like that :
Step 1 : run `nc -nlvp 5555`
Step 2 : run xmrig with pool address point to 127.0.0.1:5555
As soon as xmrig send login data, paste pool message you captured to `nc`
Some thing like ...
```
{"id":1,"jsonrpc":"2.0","error":null,"result":{"id":"469034036669300","job":{"blob":"0707bab9bad8055c251f7e881ec59bd1f0dbaacc48e3d1891d18ec563a7e6267f6790f35b76ab200000000adda882ee51010cf471542312801822bad8ddaf781dd02ff36442a66da05b5c60a","job_id":"782489939570474","target":"7b5e0400"},"status":"OK"}}
```
Sorry for my bad English

**Comment by mrganapathy** [comment]
Can you elaborate a bit more? I will be using windows operating system for mining. 

is there another option where I can download an entire blockchain of monero and start computing based on that? what would be the best way to go?

**Comment by du0ngpv** [comment]
hmm , you should make a new cryptonight coin instead
