### ISSUE TITLE
Not able to run and create a release Visual Studio 2015

### ISSUE THREAD

**Issue by mikegscott** [xmrig/xmrig#664]
I built the XMRig in visual studio 2015. I did both debug and release. When I clicked "F5" or "Local Windows Debugger" I get an error saying "Unable to start the program C: ... \ALL_BUILD.   Access is  Denied." 

How can I resolve this issue?

**Comment by 2010phenix** [comment]
add miner to Exclusion in Antivirus... and all be good ;-)

**Comment by mrganz** [comment]
I disabled all the antiviruses and deactivated Windows Firewall. But it still says "Access Denied". I rand the visual studio as an administrator.

**Comment by xmrig** [comment]
Right click on xmrig in Solution Explorer and choice `Set as StartUp Project`.
Thank you.

**Comment by mrganz** [comment]
Worked! thanks...

**Comment by mrganz** [comment]
Great ! it did compile. But when I ran it said 

> The thread 0x66c has exited with code 2 (0x2).
> The thread 0x43c has exited with code 2 (0x2).
> The thread 0x4b0 has exited with code 2 (0x2).
> The thread 0xa50 has exited with code 2 (0x2).
> The thread 0x1da4 has exited with code 2 (0x2).
> The program '[6856] xmrig.exe' has exited with code 2 (0x2).

Is it possible to set up a local mining pool with the generated XMRig solution?
