### ISSUE TITLE
Can't compile after making changes in the code

### ISSUE THREAD

**Issue by fauxcompteg** [xmrig/xmrig#665]
Hey, hope all is going well, when I change something in the code like variables declaration order, or the order where libraries are called, I get errors on cmake or on visual studio, I think changes like this wont affect the program, could you please help me out with this, or correct me if I'm wrong?

Thanks.

**Comment by xmrig** [comment]
What is question actually? c++ has strict syntax so if you get errors it means only you make errors in code.
Thank you.
