### ISSUE TITLE
is xmrig can buid for ios platform？

### ISSUE THREAD

**Issue by riverlj** [xmrig/xmrig#666]
is xmrig can buid for ios platform？

**Comment by xmrig** [comment]
It can be possible, since ARM CPUs is supported, but I can't help with how exactly do it.
Thank you.

**Comment by riverlj** [comment]
I had completed buid for iOS, thanks.

**Comment by snipeTR** [comment]
Linux=unix. Unix=ios

**Comment by Mila432** [comment]
@resistor4u what you need theos for?

**Comment by resistor4u** [comment]
@Mila432 using iphone as the build host and build target

**Comment by resistor4u** [comment]
Can we re-open this issue?

**Comment by xmrig** [comment]
Sure, but I can't help you much, compile for ARM CPUs is possible, but without cmake it very complicated.
Thank you.

**Comment by snipeTR** [comment]
If build docker and use this app :) 
https://tugboat-app.com
maybe your luck goes

**Comment by resistor4u** [comment]
torture. how about building xmrig for ios from ubuntu 18?

**Comment by Mila432** [comment]
its very easy to compile xmrig for iOS
''' MacBook-Pro:build root$ ls -lat
total 1176
drwxr-xr-x  16 vasilyerfurt  staff     512 Nov 12 09:31 CMakeFiles
-rwxr-xr-x   1 vasilyerfurt  staff  533784 Nov 12 09:31 xmrig
drwxr-xr-x   7 vasilyerfurt  staff     224 Nov 12 09:31 .
-rw-r--r--   1 vasilyerfurt  staff    1409 Nov 12 09:31 cmake_install.cmake
-rw-r--r--   1 vasilyerfurt  staff   44818 Nov 12 09:31 Makefile
-rw-r--r--   1 vasilyerfurt  staff   15493 Nov 12 09:31 CMakeCache.txt
drwxr-xr-x  14 vasilyerfurt  staff     448 Nov 12 09:30 ..
MacBook-Pro:build root$ otool -Vh xmrig 
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   ARM64        ALL  0x00     EXECUTE    17       1912   NOUNDEFS DYLDLINK TWOLEVEL WEAK_DEFINES BINDS_TO_WEAK PIE

**Comment by Mila432** [comment]
its very easy to compile xmrig for iOS
```
MacBook-Pro:build root$ ls -lat
total 1176
drwxr-xr-x  16 root  staff     512 Nov 12 09:31 CMakeFiles
-rwxr-xr-x   1 root  staff  533784 Nov 12 09:31 xmrig
drwxr-xr-x   7 root  staff     224 Nov 12 09:31 .
-rw-r--r--   1 root  staff    1409 Nov 12 09:31 cmake_install.cmake
-rw-r--r--   1 root  staff   44818 Nov 12 09:31 Makefile
-rw-r--r--   1 root  staff   15493 Nov 12 09:31 CMakeCache.txt
drwxr-xr-x  14 root  staff     448 Nov 12 09:30 ..
MacBook-Pro:build root$ otool -Vh xmrig 
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   ARM64        ALL  0x00     EXECUTE    17       1912   NOUNDEFS DYLDLINK TWOLEVEL WEAK_DEFINES BINDS_TO_WEAK PIE

**Comment by Mila432** [comment]
compile libuv for ios , then just set host flag and use cmake .. and make

**Comment by snipeTR** [comment]
is it possible to explain in more detail and simplicity? Which interface in which mode which interface. can you write a manual?

**Comment by resistor4u** [comment]
@Mila432 FML, i thought for some reason it would pull in those functions during processing.

**Comment by resistor4u** [comment]
@Mila432 @xmrig @snipeTR  I am attaching two pastebins.

The first (https://pastebin.com/5ixV0Lcj) is of my cmake compilation; the second is the `make` output (https://pastebin.com/MvEdRiDV).

This is for latest `git clone` of xmrig. I use the leetal's [ios-cmake](https://github.com/leetal/ios-cmake). I am using `libuv` v. 1.9 from mapbox's [mason ](https://github.com/mapbox/mason), and used sinofool's [build-openssl-ios](https://github.com/sinofool/build-openssl-ios).

I cannot get the build to move past what you see in the pastebin. Please advise.

**Comment by resistor4u** [comment]
@Mila432 @xmrig do you have any further guidance (or hints?) on this? i've tried multiple environments with different versions of `clang`, but everything fails.

**Comment by resistor4u** [comment]
@Mila432 @xmrig @snipeTR ZOMFG why didn't you say it was simply setting `-DCMAKE_HOST_SYSTEM_PROCESSOR=aarch64 -DCMAKE_SYSTEM_PROCESSOR=aarch64`?!

I've successfully built and tested the dev branch of xmrig for iOS 10.2.1.
```
 * ABOUT        XMRig/2.8.5-dev clang/9.1.0
 * LIBS         libuv/2.0.0-dev
 * CPU          Unknown (1) x64 AES
 * THREADS      2, cryptonight, av=0, donate=2%
 * POOL #1      xmr.pool.minergate.com:45700 variant 2
 * COMMANDS     hashrate, pause, resume
[2018-11-25 13:11:20] READY (CPU) threads 2(2) huge pages 0/2 0% memory 4.0 MB
[2018-11-25 13:11:20] use pool xmr.pool.minergate.com:45700  136.243.102.157
[2018-11-25 13:11:20] new job from xmr.pool.minergate.com:45700 diff 1063 algo cn/2
[2018-11-25 13:11:44] new job from xmr.pool.minergate.com:45700 diff 1063 algo cn/2
[2018-11-25 13:11:47] accepted (1/0) diff 1063 (250 ms)
[2018-11-25 13:11:56] accepted (2/0) diff 1063 (176 ms)
| THREAD | AFFINITY | 10s H/s | 60s H/s | 15m H/s |
|      0 |       -1 |    25.3 |    25.2 |     n/a |
|      1 |       -1 |    25.3 |    25.3 |     n/a |
[2018-11-25 13:12:21] speed 10s/60s/15m 50.6 50.5 n/a H/s max 50.6 H/s
```
I have to run now, but I'll be back later and give the `cmake` settings, if you all will find this useful.

**Comment by Nakamoto-san** [comment]
@Mila432 @ resistor4u Could either of you provide a more friendly tutorial of this build from the beginning up until `make`? Would be greatly appreciated. Cheers.

Greatly appreciated, cheers

**Comment by Nakamoto-san** [comment]
@Mila432 @ resistor4u Could either of you provide a more friendly tutorial of this build from the beginning up until make? Would be greatly appreciated

**Comment by dankokp** [comment]
Is it possible to reopen it please? There's still people having this problem 😅
@resistor4u could you please share the detailed instructions? It would be awesome, because I have exactly the same issues as you used to...

**Comment by ktalebian** [comment]
@resistor4u can you provide a step by step instruction please?

**Comment by UnixCro** [comment]
> @Mila432 @xmrig @snipeTR ZOMFG why didn't you say it was simply setting `-DCMAKE_HOST_SYSTEM_PROCESSOR=aarch64 -DCMAKE_SYSTEM_PROCESSOR=aarch64`?!
> 
> I've successfully built and tested the dev branch of xmrig for iOS 10.2.1.
> 
> ```
>  * ABOUT        XMRig/2.8.5-dev clang/9.1.0
>  * LIBS         libuv/2.0.0-dev
>  * CPU          Unknown (1) x64 AES
>  * THREADS      2, cryptonight, av=0, donate=2%
>  * POOL #1      xmr.pool.minergate.com:45700 variant 2
>  * COMMANDS     hashrate, pause, resume
> [2018-11-25 13:11:20] READY (CPU) threads 2(2) huge pages 0/2 0% memory 4.0 MB
> [2018-11-25 13:11:20] use pool xmr.pool.minergate.com:45700  136.243.102.157
> [2018-11-25 13:11:20] new job from xmr.pool.minergate.com:45700 diff 1063 algo cn/2
> [2018-11-25 13:11:44] new job from xmr.pool.minergate.com:45700 diff 1063 algo cn/2
> [2018-11-25 13:11:47] accepted (1/0) diff 1063 (250 ms)
> [2018-11-25 13:11:56] accepted (2/0) diff 1063 (176 ms)
> | THREAD | AFFINITY | 10s H/s | 60s H/s | 15m H/s |
> |      0 |       -1 |    25.3 |    25.2 |     n/a |
> |      1 |       -1 |    25.3 |    25.3 |     n/a |
> [2018-11-25 13:12:21] speed 10s/60s/15m 50.6 50.5 n/a H/s max 50.6 H/s
> ```
> 
> I have to run now, but I'll be back later and give the `cmake` settings, if you all will find this useful.

____

It looks like you're one of the few who got it right.  It would be really nice of you if you write a manual about it.  Every time I start xmrig `Illegal Instructions` I get nothing else.  No further information, which doesn't help me at all.
