### ISSUE TITLE
Android (ARM) Support

### ISSUE THREAD

**Issue by iranagame** [xmrig/xmrig#669]
Any news for android (arm) support? It's shame that MinerGate providing complete android support but XMRIG with 1M users not!

**Comment by qusstem** [comment]
u can try build with termux.

**Comment by qusstem** [comment]
now i'm build in termux xmrig and it work

**Comment by iranagame** [comment]
@qusstem May I know your xmrig version and your device spec?

**Comment by qusstem** [comment]
htc m8 arm7l

**Comment by iranagame** [comment]
I'm fully tuned it into an Android App (will add the source & repo once it completed) through NDK, works great on arm64-v8 but on arm7 got bus error!
Trying to fix that...

**Comment by mike2001** [comment]
@qusstem hi, i have install cmake and clang on termux , i dont know how to build next step , can you tell me ? my device is android arm64

**Comment by NanoBytesInc** [comment]
Keep us posted

**Comment by mssc89** [comment]
Another solution is to install app "Linux deploy" from play store, create XUbuntu ARM64 container, connect thru ssh/vnc, and simply build xmrig from git. Works like a charm, achieving around 60-70h/s on all 8 cores of my galaxy s8.
