### ISSUE TITLE
algo: cryptonight-lite ignored when variant:1 specified.

### ISSUE THREAD

**Issue by cryptonote-social** [xmrig/xmrig#672]
In my v.2.5 config files for Aeon and TRTL I had specified "algo: cryptonight-lite" at the top, and "variant: 1" in the pools section.   When I ran it with v2.6.2, it defaulted to cryptonight algorithm instead of cryptonight lite.  The fix was to change algo to "cn-lite/1",  but ideally it would be backwards compatible.  Perhaps "variant: 1" in the pools section is overriding the algo: field inappropriately?

**Comment by cryptonote-social** [comment]
After a bit more debugging it appears a combination of user error and software change.

I had actually specified "algo: cryptonight-light" (light vs lite) and that *used* to work but no longer does.  Perhaps xmrig can be made to complain when an invalid algo is specified instead of fall back silently to regular cryptonight?

**Comment by xmrig** [comment]
`cryptonight-light` is invalid algorithm name, but for some reason it used too, better use `cryptonight-lite` or `cn-lite`.

Anyway I fixed it, name `cryptonight-light` now supported again, it was a bug, and miner show error message and exit if invalid algorithm specified.
Thank you.

**Comment by xmrig** [comment]
Fixed in v2.6.3.
