### ISSUE TITLE
памогите 

### ISSUE THREAD

**Issue by SheetsBook** [xmrig/xmrig#673]
i just wanted to moine som maney from manero, but t they r not mining wher i shud click i was tried to moine from my phone but thesis nut working halp ;-;

**Comment by SheetsBook** [comment]
i just wanted to moine som maney from manero, but t they r not mining wher i shud click i was tried to moine from my phone but thesis nut working halp ;-;

**Comment by exceler55** [comment]
You should correct the sentense before your submission.

**Comment by SheetsBook** [comment]
наxнй пашол я xачy парy шекелей поднять на маем xсияоми xачy себе дом на гаваяx и бледжек и тд

**Comment by SheetsBook** [comment]
y тебя ибало как y дерево

**Comment by SheetsBook** [comment]
;-;
