### ISSUE TITLE
Huge Pages available but not enabled.

### ISSUE THREAD

**Issue by aragornarathon** [xmrig/xmrig#677]
I am using windows 10. I compiled and built XMRig miner but the huge pages are available and there is no enable next to the available. 

I started xmrig as an admin. Rebooted the computer after first start. 

![capture](https://user-images.githubusercontent.com/7914346/40932658-eb8785b8-67e3-11e8-8eb1-fb3cc3e78832.PNG)

**Comment by rtau** [comment]
From  2.6, the hugepages are allocated by each thread, thus it's not a simple yes/no toggle. Take a look on the statistics line then you'll find something like "2/2", which indicates both threads have hugepages enabled.

**Comment by xmrig** [comment]
#614
