### ISSUE TITLE
Nothing print on console

### ISSUE THREAD

**Issue by calvintam236** [xmrig/xmrig#68]
I made your binary into a [docker image](https://hub.docker.com/r/calvintam236/xmrig/). It has no problem printing logs on console on v2.2.1.

sample command: ```docker run -d --name cpu0_xmr calvintam236/xmrig -a cryptonight -o POOL_URL -u USERNAME --donate-level=1 --print-time=2 --max-cpu-usage=100 --cpu-affinity=0xAAAA```

I tried with and without ```--no-huge-pages```, same result.

Docker host is Ubuntu 16.04.3 with kernel 4.10.0-32-generic.

**Comment by xmrig** [comment]
Please checkout to **bug-68** branch, probably it helps. I debug printf in code, it little spam output, will looks like `uv_is_writable: 1, uv_guess_handle: 14` I need this line from your logs.
Im not familiar with docker containers, so can't do it by myself.
Thank you.

**Comment by calvintam236** [comment]
Thanks for getting back so fast. I used the binary in the release in the docker image. Tested on my macOS docker host as well, with same problem.
By building `bug-68` branch in the docker image and run it in my macOS docker host, it do have some console output (probably debug).

![screen shot 2017-08-21 at 10 41 08 pm](https://user-images.githubusercontent.com/6436149/29550299-eacec8e2-86c1-11e7-9fa3-6b9eeda1e050.png)

**Comment by xmrig** [comment]
I fixed it in master branch.
Surprising console in docker not true console it named pipe.
Thank you.

**Comment by calvintam236** [comment]
Thanks for fixing that. Are you planned to have a new release anytime soon?

**Comment by xmrig** [comment]
It already in master branch or for docker need tagged release? I can create bugfix release later today.

**Comment by calvintam236** [comment]
it requires me to trigger the image build. Currently, I am using your binary release in the `Dockerfile` instead of compiling.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v2.3.1

**Comment by calvintam236** [comment]
Fix confirmed on v2.3.1. Thanks! :D
