### ISSUE TITLE
How and where to provide test hash input to the cryptonight algorithm to run without pool information?

### ISSUE THREAD

**Issue by aragornarathon** [xmrig/xmrig#681]
I found few hash inputs here: https://github.com/monero-project/monero/tree/master/tests/hash and I want to give them as inputs to CryptoNight algorithms and test the algorithm in action without pool information. 

Where and how can I provide these inputs in the XMRig code?

**Comment by xmrig** [comment]
Test vectors defined there https://github.com/xmrig/xmrig/blob/master/src/crypto/CryptoNight_test.h and self check located there https://github.com/xmrig/xmrig/blob/dev/src/workers/MultiWorker.cpp#L51
Thank you,

**Comment by aragornarathon** [comment]
How can I input hashes like this: https://github.com/monero-project/monero/blob/master/tests/hash/tests-extra-blake.txt ?

**Comment by xmrig** [comment]
Read file, parse it, feed result to cryptonight hash function and verify hashes, should not be a big deal with C/C++ knowledge.
Thank you.

**Comment by mrganapathy** [comment]
Ok Thank you. From my network, its not possible to connect to poo.something.com:port. Is it possible to by bass it and just do the hash calculations? get the hash rate and stuff?

**Comment by xmrig** [comment]
No, but you can create fake pool on any language, just need implement reply to login request, protocol is really simple https://github.com/xmrig/xmrig-proxy/blob/master/doc/STRATUM.md
Thank you.
