### ISSUE TITLE
mining for 2 wallet and 2 mining pool

### ISSUE THREAD

**Issue by XliveStudios** [xmrig/xmrig#688]
i want to mine for 2 wallet (70% and 30%) and with 2 mining pool. How i can do it wiht xmrig?

**Comment by snipeTR** [comment]
Run 2 process one cpu percent set %20. One processs cpu percent %70.
--max-cpu-usage=20
--max-cpu-usage=70

**Comment by XliveStudios** [comment]
ok thanks
