### ISSUE TITLE
Add a new algo

### ISSUE THREAD

**Issue by maoxs2** [xmrig/xmrig#689]
The webchain project has a new algo which was modified from the cryptonight_monerov7.

This is their [miner](https://github.com/webchain-network/webchain-miner), and it's based on XMRig.

So, can you considering add this algo into the XMRig?

**Comment by reeyon** [comment]
Please add the upcoming Masari algo fork as well.

**Comment by bananajamma** [comment]
MSR PoW change (aka cn-fast) is in this commit: https://github.com/xmrig/xmrig/commit/8908c2c027ec4adcb6fecf80b401bd4435a635cc

**Comment by xmrig** [comment]
Merge with #692
