### ISSUE TITLE
masari fork

### ISSUE THREAD

**Issue by leonlumsden** [xmrig/xmrig#690]
will you be supporting the coming masari fork on 16/6/18?

**Comment by 2010phenix** [comment]
don't be lazy.... already did:
https://github.com/xmrig/xmrig/commit/8908c2c027ec4adcb6fecf80b401bd4435a635cc

**Comment by leonlumsden** [comment]
ah sorry, i meant a compiled executable version

**Comment by xmrig** [comment]
cpu/proxy will release tomorrow.
amd few days later.
nvidia no ETA.
Thank you.

**Comment by leonlumsden** [comment]
thankyou
