### ISSUE TITLE
Unable to mine MSR

### ISSUE THREAD

**Issue by gnock** [xmrig/xmrig#692]
Hi,

I was going to submit a PR to add support for the Masari variant, but i saw you did. I gave it a run and wasn't able to mine (test pool:testnet.masaricoin.com, already on the variant, accept even invalid address).

I tracked the problem to the worker not selecting the right variant (falling back to VARIANT_1).
Looking more closely at the code, pool.setAlgo is never called (only way i found to set the variant).
One solution is to modify CommonConfig.cpp (function finalize) and replace 

`pool.adjust(m_algorithm.algo());`
by
`pool.setAlgo(m_algorithm);
pool.adjust(m_algorithm.algo());`

Not sure it's the way you would have done it but it works.

If you need more info i can provide some.

Xmrig-proxy (with xmrig patched as above) works

**Comment by gnock** [comment]
Hi,

Effectively with --variant it works, i couldn't make it work yesterday, weird.
If you write `-a cn/msr` it doesn't. Is it the expected behaviour ? 

Eithercase, sorry for the inconvenience

**Comment by xmrig** [comment]
Yes it is expected behavior, but you are right it's good to allow user specify global variant if per pool variant option not specified or set to automatic. I will fix it soon.
Thank you.

**Comment by xmrig** [comment]
Next version will support syntax like: `xmrig.exe -a cn/msr --url testnet.masaricoin.com:3333`
Thank you.

**Comment by DrStein99** [comment]
I was mining version 2.6.2, received:

`rejected (0/1) diff 21000 "Low difficulty share" (147 ms)`

all over the place.  Just upgraded to version "2.6.4-dev".  Still the same thing.  Here's my pool config:

`{       
 "url": "masari.superpools.net:5555",
"user": "myWalletAddress.21000",
 "pass": "x",
 "variant": "msr"
  },`

Is there something else I need to set somewhere else ?  is the "algo": "cryptonight", or should that be different too?

**Comment by gnock** [comment]
I think this discussion should continue on the discord of Masari (https://discord.gg/eSb9ZdM).
Also, the admin of superpools he had no time to handle the pool anymore, so maybe use another pool. There is a list (unofficial) at masaripools.org

**Comment by DrStein99** [comment]
I tried to connect to discord, and it's bugging out.  I get a blank screen "Masari" and looks like my typed "hello" messages go nowhere.  Not sure what is going on - my browser cache ?  I tried twice, and will continue again to try.

**Comment by DrStein99** [comment]
It started working when I put "cn/msr" in my "algo": field, for the JSON config file I was using.  If I wanted to fail-over to a pool that was mining a different algo, but I can see that is probably more complicated.  I can work with this at least.
