### ISSUE TITLE
Release v2.6.3 does not work with latest haven fork

### ISSUE THREAD

**Issue by acca** [xmrig/xmrig#693]
Just installed release v2.6.3 but I got bad shares from the pool mining haven protocol. I'm using https://cryptoknight.cc/haven/#. Cannot understand if it is a pool issue or a miner one?

**Comment by postalman** [comment]
Same Thing. Its not autoswitching and cn-heavy/xhv doesnt work. non of heavy algo works for XHV

**Comment by xmrig** [comment]
Haven forked and changed PoW, so you need change `variant` option to `"variant": "xhv"`
Key options:
```json
{
    "algo": "cryptonight-heavy",
    "pools": [
        {
            "url": "haven.ingest.cryptoknight.cc:5831",
            "variant": "xhv"
        }
    ]
}
```

@postalman Autoswitching between `cn-heavy` and `cn-heavy/xhv` not possible if pool not support this feature. With config above and v2.6.3 anything should work fine.
Thank you.

**Comment by postalman** [comment]
Thanks. Now its works.

**Comment by acca** [comment]
Many Thanks, it is working also for me now.
