### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by CorrM** [xmrig/xmrig#695]
CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find UV (missing: UV_LIBRARY UV_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindUV.cmake:25 (find_package_handle_standard_args)
  CMakeLists.txt:175 (find_package)

**Comment by xmrig** [comment]
Specify paths to libuv or use xmrig-deps https://github.com/xmrig/xmrig/wiki/Windows-Build
Thank you.

**Comment by CorrM** [comment]
can u give me example for VS2017 CMD Command
libuv: C:\Users\CorrM\Downloads\Compressed\libuv-1.20.3\Debug\lib
