### ISSUE TITLE
old glibc compatibility

### ISSUE THREAD

**Issue by xc85** [xmrig/xmrig#70]
Can it be compiled for old glibc 2.5 ?

I download compiled file from releases and got this error:

```
./xmrig: /lib64/libc.so.6: version `GLIBC_2.6' not found (required by ./xmrig)
./xmrig: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./xmrig)
./xmrig: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by ./xmrig)
./xmrig: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./xmrig)
```

**Comment by xmrig** [comment]
Probable yes, until you can install gcc 4.9+ and libuv1 on this system, if that requirements satificated, you can build binary.
Thank you.

**Comment by xc85** [comment]
Thanks for your answer. I try to do this...

**Comment by lexphor** [comment]
@xc85  just wondering if you've succeeded to compile for old glibc?

**Comment by xc85** [comment]
@lexphor, yes I did it. Need link "rt" library and wrap function for memcpy.
But i still try to compile libuv static.
