### ISSUE TITLE
"-a=cryptonight" not work in 2.6.3

### ISSUE THREAD

**Issue by Quake4** [xmrig/xmrig#702]
from command line -a switch not work
if specify `--algo=cryptonight` - work fine

command not work:
xmrig.exe -o cryptonightv7.eu.nicehash.com:3363 -u xxx.Home -p x --api-port=4045 --variant 1 --donate-level=1 --cpu-priority 0 -R 5 -a=cryptonight

command work fine:
xmrig.exe -o cryptonightv7.eu.nicehash.com:3363 -u xxx.Home -p x --api-port=4045 --variant 1 --donate-level=1 --cpu-priority 0 -R 5 --algo=cryptonight

**Comment by lisergey** [comment]
And it should not work in format
`-a=cryptonight`

There are two different formats of command line string: 
short with single dash before param: `-<param> <space> <value>`
and long with double dash: `--<param>=<value>`

do not mix them up :)

**Comment by Quake4** [comment]
thanks. sorry.
