### ISSUE TITLE
Enhancement - Miner take "algo" and "variant" settings from proxy or http link

### ISSUE THREAD

**Issue by borodamd** [xmrig/xmrig#708]
If i want to switch mining from Cryptonight-lite to Cryptonight, i need to reconfigure proxy and all miners one by one.

If will be an great option to take this options direct from proxy or use whole config from http link - will be easier to change coin to mine.

**Comment by xmrig** [comment]
cn/cn-lite/cn-heavy require different memory amount, so different settings, threads, etc, it require new config format and ability to restart threads. On protocol level proxy can tell miner what algorithm and variant used.
Thank you.

**Comment by xmrig** [comment]
Merge with #618
