### ISSUE TITLE
donate level 0 is ignored

### ISSUE THREAD

**Issue by trashhalo** [xmrig/xmrig#71]
when I change the config to set the donate level to 0 it boots ` cryptonight, av=1, donate=5%` I thought it was just a cosmetic issue until I hit a dns error on my box today and low and behold fee.xmrig.com was being hit
![2017-08-27 16_28_17-](https://user-images.githubusercontent.com/177491/29753731-b63c1fb6-8b45-11e7-8693-a2ab29aa2699.png)

**Comment by xmrig** [comment]
Donate can set to 0 only if you compile miner by yourself from source, need change single line in `donate.h` file.
Thank you.
