### ISSUE TITLE
removing config.json

### ISSUE THREAD

**Issue by Alias321** [xmrig/xmrig#710]
hey
i want to remove config.json to xmrig pool, user,.... be unchangable 

what should i do?

**Comment by mardarfar** [comment]
Get a job

**Comment by Alias321** [comment]
anyone!?!?!????

**Comment by bobbieltd** [comment]
You can hard code pool and wallet in the source code.

**Comment by Alias321** [comment]
im an amateur
how exactly should i change code?

**Comment by Alias321** [comment]
@xmrig
helpppp
