### ISSUE TITLE
Is XMRIG going to support Cryptonightv7?

### ISSUE THREAD

**Issue by asanchez500** [xmrig/xmrig#711]
Title says it all.. I am not to sure if they forked yet. Is it just going to be a newer coin or something? Will the old XMR coin still survive?

**Comment by bananajamma** [comment]
It does already.

`--algorithm cryptonight --variant 1`

https://github.com/xmrig/xmrig/blob/master/doc/ALGORITHMS.md

**Comment by asanchez500** [comment]
Cool. Thanks. Do you know if the old coin is still going to be around?
