### ISSUE TITLE
uptime is reset, but stats appear to keep

### ISSUE THREAD

**Issue by DrStein99** [xmrig/xmrig#712]
The UPTIME appears to get reset on a connection fail, yet the hash total  and other stats save.  This throws off my stat-keeping.  Once the rig is up for and have accumulated stats, then the uptime zero's out, makes a big mess.  I am trying analyze my performance on any calculation of per-hour uptime.

Is there any solutions outside of me modifying the code myself?  I figure I would ask since it is possible I am overlooking a simple solution, and welcome to entertain replies for advice please.

**Comment by xmrig** [comment]
Recent versions also provide global uptime in API.
Thank you
