### ISSUE TITLE
CN-Heavy-Italo

### ISSUE THREAD

**Issue by swa74** [xmrig/xmrig#714]
There will be a new CN-Heavy-Italo ?

**Comment by xmrig** [comment]
Any information about this algorithm?
Thank you.

**Comment by swa74** [comment]
https://github.com/italocoin-project/xmrig

**Comment by xmrig** [comment]
Looks like It should work already as `cn-heavy/xhv`.
```json
{
  "algo": "cryptonight-heavy",
  ...
  "pools": [
        {
            "url": "...",
            ...
            "variant": "xhv"
        }
  ]
}
```

**Comment by swa74** [comment]
![default](https://user-images.githubusercontent.com/34404806/42375628-c5c3166c-8124-11e8-8eae-c492f491b93b.JPG)
![1](https://user-images.githubusercontent.com/34404806/42375629-c5decf10-8124-11e8-888a-bd20ae1b6025.JPG)

**Comment by xmrig** [comment]
nvidia miner not support variant `xhv` yet.

**Comment by swa74** [comment]
![2](https://user-images.githubusercontent.com/34404806/42376073-8335e8ea-8126-11e8-9135-a541adf32caf.JPG)

**Comment by xmrig** [comment]
You should use v2.6.3 also is they already forked?

**Comment by italocoin-project** [comment]
Hello,

the difference between italo and xhv is this

XHV has `idx0 = (~d) ^ q` and italo has `idx0 = ~(d ^ q)` could you please add it?

Regards.

**Comment by xmrig** [comment]
Okay, look at this line https://github.com/italocoin-project/xmrig/commit/c2c0c7c5ba2bff012c981c5b78cf89ec25ed61ee#diff-b279619f2bf01fd93a78050a584f96eeL177 in your fork, reference hashes are equal to `cn-heavy/xhv`.
Thank you.

**Comment by italocoin-project** [comment]
Those must be remade, i haven't touched them, you think you can add heavy/ITA?

**Comment by xmrig** [comment]
`idx0 = (~d) ^ q` equal to `idx0 = ~(d ^ q)`, so `cn-heavy/ita` not exists, self test additionally confirm it.

**Comment by italocoin-project** [comment]
U sure bro?

**Comment by xmrig** [comment]
Yep, if algorithm really changed miner threads won't start and you will see red error messages like
`thread 0 error: "hash self-test failed".`

**Comment by italocoin-project** [comment]
Thank you for letting me know :) Really apreciate it
