### ISSUE TITLE
Command line parameters not working

### ISSUE THREAD

**Issue by UselessGuru** [xmrig/xmrig#715]
As it seems  XMRig/2.6.3 libuv/1.20.3 MSVC/2017 is completely ignoring the command lines parameters and always uses config.json:

```
xmrig.exe --api-port=3334 -a cryptonightV7 -o stratum+tcp://us-east.cryptonight-hub.miningpoolhub.com:20580 -u MyUser:Name -p x --keepalive --nicehash --donate-level 1
 * VERSIONS     XMRig/2.6.3 libuv/1.20.3 MSVC/2017
 * HUGE PAGES   available
 * CPU          Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (1) x64 AES-NI
 * CPU L2/L3    1.5 MB/9.0 MB
 * THREADS      5, cryptonight, av=0, donate=5%
 * POOL #1      proxy.fee.xmrig.com:9999 variant 1
 * COMMANDS     hashrate, pause, resume
[2018-07-09 01:46:02] READY (CPU) threads 5(5) huge pages 5/5 100% memory 10.0 MB
[2018-07-09 01:46:02] use pool proxy.fee.xmrig.com:9999 108.61.164.63
[2018-07-09 01:46:02] new job from proxy.fee.xmrig.com:9999 diff 20000 algo cn/1
```

**Comment by Smeagol001** [comment]
have same problem aparantly even if i fall back to the 2.6.2 it does the same just ignoring everything i have configured in awesomeminer and is defaulting to proxy.fee.xmrig.com:9999

**Comment by UselessGuru** [comment]
>  even if i fall back to the 2.6.2 

Yep, so do I

**Comment by xmrig** [comment]
`cryptonightV7` is not valid algorithm name, so miner ignore all command line params and try failback to config.json in same directory with exe file, more details https://github.com/xmrig/xmrig-amd/issues/135#issuecomment-399905956

**Comment by Smeagol001** [comment]
for me its not working with "cryptonight" which is default value in awesomeminer and cant be changed from my side it seems

**Comment by xmrig** [comment]
@Smeagol001 Is it possible somehow get full command line?
Thank you.

**Comment by Smeagol001** [comment]
What do you mean

xmrig <notifications@github.com> schrieb am Mo., 9. Juli 2018, 09:08:

**Comment by xmrig** [comment]
@Smeagol001 I don't use awesome miner, so don't know how it works, if it use command line to run miner, that command line params can help to understand what exactly wrong.
Thank you.

**Comment by UselessGuru** [comment]
> cryptonightV7 is not valid algorithm name

For me this is working well when I use the correct algos as listed here: xmrig/xmrig-amd#135 (comment)
