### ISSUE TITLE
is it right? ch-heavy

### ISSUE THREAD

**Issue by qbsncwliprrelf** [xmrig/xmrig#718]
https://github.com/xmrig/xmrig-proxy/blob/dev/doc/STRATUM_EXT.md#15-xmr-stak-algorithm-names

bottom of the table
cryptonight_heavy | c**h**-heavy
-- | --
cryptonight_haven | c**h**-heavy/xhv

may be cn?

**Comment by xmrig** [comment]
Fixed. Thank you.
