### ISSUE TITLE
Settings for bytecoin

### ISSUE THREAD

**Issue by Sveeeeeen** [xmrig/xmrig#723]
Since I upgraded to the very current version I just receive only "Low difficulty share" errors.
Whats the problem with it?

**Comment by Sveeeeeen** [comment]
Push

**Comment by xmrig** [comment]
As I know Bytecoin still use original cryptonight, so key options:
```json
{
  "algo": "cryptonight",
  ...
  "pools": [
    {
      "url": "...",
      "variant": 0,
      ...
    }
 ],
 ...
}
```

**Comment by xmrig** [comment]
You must set `"variant": 0` for newer versions, default variant changed from `0` to `1`.
Thank you.
