### ISSUE TITLE
Mining 2 pools same time?

### ISSUE THREAD

**Issue by LearnMiner** [xmrig/xmrig#724]
Its possible mining 2 pools at same time inside code? and how can i do?

Or change pool every 1 accept share for example

**Comment by DrCrw** [comment]
The principle you ask for is somewhat similar to how the donation fee works - which has been tested thoroughly. You can increase the fee to 50% while changing the donation target to your (own) second pool.

If you do it this way you should consider making manual donations to support the dev.
