### ISSUE TITLE
What happened to options.cpp?

### ISSUE THREAD

**Issue by lolcocks123** [xmrig/xmrig#726]
Hello,

I am coming back to this project after a long time.

I remember there was an options.cpp file where in I used to add multiple pools as follows:

```
m_pools.push_back(new Url("monerohash.com", 3333, "ExampleAddress", "x", false, true));

m_pools.push_back(new Url("pool.minexmr.com", 4444, "ExampleAddress", "x", false, true));

m_pools.push_back(new Url("xmr.prohash.net", 2222, "ExampleAddress", "x", false, true));

```

How can I achieve this once again?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/issues/608#issuecomment-386882513
Also instead of `new Url(` use just `Pool(`. Thank you.
