### ISSUE TITLE
XMrig + Stellite = reject shares? please Help

### ISSUE THREAD

**Issue by nicsan85** [xmrig/xmrig#731]
Dear XMrig owner & Friends, 
i need help please, 
is it possible to mining Stellite (XTL) with XMrig Amd 2.7.3 ?

or did i put the wrong algo?
already put :
cryptonight
cryptonight-lite
cn-lite
cn-litev7
stellite
stellitev7

and the shares always reject : https://ibb.co/j345GK

heres the config :

    "algo": "cryptonight-lite",
    "api": {
        "port": 0,
        "access-token": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "background": false,
    "cache": true,
    "colors": true,
    "donate-level": 1,
    "log-file": null,
    "opencl-platform": 0,
    "opencl-loader": "OpenCL.dll",
    "pools": [
        {
            "url": "xtl.miningpool.id:8805",
            "user": "SEiStP7SMy1bvjkWc9dd1t2v1Et5q2DrmaqLqFTQQ9H7JKdZuATcPHUbUL3bRjxzxTDYitHsAPqF8Ee CLw3bW8ARe8rYc1eGiRC4Kww3e37HP",
            "pass": "JANGKRIKBOSS!!",
            "rig-id": null,
            "nicehash": false,
            "keepalive": true,
            "variant": 1
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "threads": [
        {
            "index": 0,
            "intensity": 1430,
            "worksize": 8,
            "strided_index": 1,
            "mem_chunk": 2,
            "comp_mode": true,
            "affine_to_cpu": false
        },

can anybody help me?

thanks in advance

**Comment by snipeTR** [comment]
first please cencored adress and pass and pool adress.

**Comment by snipeTR** [comment]
"intensity": 1430,
change
"intensity": 1024,

**Comment by xmrig** [comment]
Key options for mine Stellite `algo` and `variant`:
```json
{
  "algo": "cryptonight",
  ...
  "pools": [
    {
      "url": "...",
      "variant": "xtl",
      ...
    }
 ],
 ...
}
```
More details https://github.com/xmrig/xmrig/blob/master/doc/ALGORITHMS.md
Thank you.

**Comment by nicsan85** [comment]
ok problm solved!! many thanks Xmrig & dear friends!!
