### ISSUE TITLE
Bloc not mine, rejected. 

### ISSUE THREAD

**Issue by pikomule** [xmrig/xmrig#733]
https://bloc-mining.eu/#getting_started
https://bitcointalk.org/index.php?topic=4108831.0

Bloc uses heavy XHV variant, but it does not work with xmrig

**Comment by xmrig** [comment]
According information on links you provide algorithm is original cn-heavy not XHV variant, so option variant should be `0`.
Thank you.

**Comment by pikomule** [comment]
only heavy not work. in the pool indicate that now uses XHV variant

**Comment by xmrig** [comment]
Please provide full config. bloc-mining.eu not work for me with exchange wallet address, sent invalid target.
Thank you.

**Comment by pikomule** [comment]
with xmrstak and "currency": "cryptonight haven" if it works
