### ISSUE TITLE
ERR While building Xmrig - CPU Miner

### ISSUE THREAD

**Issue by D3xt3r-UK** [xmrig/xmrig#736]
hello.
i got this isssues in compiler while compiling
1 - C1007 unrecognized flag '-Ot' in 'p2'
2 - LNK1257 code generation failed
i try to using both of msvc2017 and 2015, but no thing become diffrent
how to fix it please?
thanks.

**Comment by Donovant** [comment]
I'm getting the same errors.

**Comment by D3xt3r-UK** [comment]
download deps v3.0 
it's working for me.
