### ISSUE TITLE
setting config.json to work with ip address instead of url

### ISSUE THREAD

**Issue by artemide601** [xmrig/xmrig#738]
it cn be a silly question, but how i can tell to config.json to use ip address:

in my config.json i have this entry
            "url": "gulf.moneroocean.stream:80", // URL of mining server
I want to replace the url with ip, so i set
            "url": "104.207.130.172:80", // URL of mining server
but this does not work... miner will close immediatelly

any suggestion?

thank you

**Comment by artemide601** [comment]
@organizmo why a thumb down ????  :-(

**Comment by artemide601** [comment]
no one can answer?
so it's not so a easy question....

**Comment by Spudz76** [comment]
Otherwise put into hosts file:
```
104.207.130.172 blahpool
```
and then use
```
 "url": "blahpool:80", // URL of mining server
```
which would go around the bug if it is truly a bug, and hosts file returns the IP without any Internet DNS hits.

**Comment by xmrig** [comment]
Syntax like `"url": "104.207.130.172:80",` is fully correct, there may be another error in the configuration file.
Thank you.

**Comment by snipeTR** [comment]
Please paste both json file
