### ISSUE TITLE
xmrig on FPGA or Jetson or Raspberry

### ISSUE THREAD

**Issue by gigahashes** [xmrig/xmrig#74]
Has anyone tried running xmrig on Nvidia Jetson TK1? or any other FPGA or Raspberry Pi boards? Please share your experience? Is it worth while? The whole idea is to bring down the mining cost. thanks

**Comment by atarate** [comment]
Require 2 MB L3 cache per thread to run the miner along with the support for AES-NI Instruction set.
This is very uncommon in FPGAs and Rasberry Pi Boards. Don't Know about Nvidia Jetson TK1 as never used it.
CPU Mining with ARM is possible but requires a lot of work.
