### ISSUE TITLE
number of threads

### ISSUE THREAD

**Issue by mahmoodn** [xmrig/xmrig#742]
By changing the number of threads in the json file, the hash rate is increased. It is expected then to see more cpu utilization. Isn't that?

However, a 90% cpu utilized process (one thread) is increased to 94% with four threads. Is that normal?

**Comment by 2010phenix** [comment]
if you ask question and open issues.... write complete info

**Comment by mahmoodn** [comment]
I want to know what is the effect of the number of threads? If the number of threads is 4, then should I see 400% cpu utilization for one process? or 4 processes each 100% utilization? The following image shows the output of top command when xmrig is configured with 4 threads.

https://pasteboard.co/HBgJkfV.png

**Comment by mmahmoudian** [comment]
@mahmoodn So clearly you are using xmrig-nvidia which runs on GPU and therefore the process is not detectable by `top` command. the CPU usage you see is most probably the process that distributes and aggregates the data to and from GPUs. In case you use the amrig CPU version, you will see 400% in the `top`.

Having that said, you should have open such thing in the [xmrig-nvidia](https://github.com/xmrig/xmrig-nvidia) repository.

**Comment by rtau** [comment]
For your information, to see the GPU utilization, you may use `nvidia-smi`

**Comment by mahmoodn** [comment]
Thank you.
