### ISSUE TITLE
unable to build on arch linux

### ISSUE THREAD

**Issue by dash042** [xmrig/xmrig#76]
hi!

make[2]: *** no rule for target „/usr/lib/x86_64-linux-gnu/libuv.a“...

libuv is installed in version 1.14.0-1

thank you!

**Comment by xmrig** [comment]
You can build with dynamic libuv.so, in that case cmake probably find it without help, no need explicitly specify path.
libuv.a for static link, that path valid for Ubuntu, but in Arch looks like it different.

**Comment by dash042** [comment]
got it working:
pacman -S libuv
cmake .. -DCMAKE_BUILD_TYPE=Release
make

**Comment by lachesis** [comment]
I hit this issue again on 22.04 Jammy. The fix for me was:
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libuv_a.a
```
