### ISSUE TITLE
Mine just when i inactive

### ISSUE THREAD

**Issue by LearnMiner** [xmrig/xmrig#760]
How can start mining just when i inactive ?

**Comment by TheDevFromKer** [comment]
By scheduled tasks.
Cmd:
`schtasks /create /tn "<app>" /tr <what> /sc onidle /i <time>`
If it is does work, create task manually.

**Comment by LearnMiner** [comment]
thanks but have 1 ask..

/tr <what> idk what i need write there

**Comment by TheDevFromKer** [comment]
<what> - command or path to file.
Example: schtasks /create /tn "Miner" /tr "C:\miner.exe" /sc onidle /i 10

**Comment by LearnMiner** [comment]
ok is working good, this have startup or i need open always?

**Comment by TheDevFromKer** [comment]
Have startup. Please close issues.
