### ISSUE TITLE
Question: How can I debug the code in Visual Studio? 

### ISSUE THREAD

**Issue by comsians123** [xmrig/xmrig#765]
I have followed the build process mentioned in document and everything is working fine. But I want to debug the code to understand the actual working of the code. (I have read the cryptonight [doc](https://cryptonote.org/cns/cns008.txt) and understand the algorithm but here I wanna understand the code) 

From where should I begin? 
Where is the main function?

Thanks  ###

**Comment by NineWoranop** [comment]
Yes, you could. I also try to search this answer. I discover that. If you do [the steps](https://xmrig.com/docs/miner/build/windows) for compile code with Visual Studio 19. If we already got the generated solution and project. You need to use those projects. Not need to create your own project. You could debug on xmrig project.
This is the screenshop from mine.
![image](https://user-images.githubusercontent.com/9558241/112740947-42555400-8fab-11eb-898d-e8be95ffbafe.png)
