### ISSUE TITLE
visual c++ 2015 : MASM : error A2070: invalid instruction operands

### ISSUE THREAD

**Issue by adevelopcr** [xmrig/xmrig#768]
I got several of this error during build for x64 release and thus the linker failed at the the end of compilation to link against xmrig-asm.lib

these are some of the errors : 

    1>------ Build started: Project: xmrig-asm, Configuration: Release x64 ------
    1>  Assembling E:\fx\xmrig-project\xmrig-2.8.0\src\crypto\asm\cnv2_main_loop.asm...
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2150: word register cannot be first operand
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2070: invalid instruction operands
    1>MASM : error A2150: word register cannot be first operand
    1>MASM : error A2150: word register cannot be first operand
    1>MASM : error A2150: word register cannot be first operand
    1>6) : fatal error A1012: error count exceeds 100; stopping assembly

    2>LINK : fatal error LNK1181: cannot open input file 'Release\xmrig-asm.lib'

**Comment by adevelopcr** [comment]
I built it successfully with mingw-w64 but it doesn't build with visual studio 2015
what happened ! have anything changed in 2.8 release or should I do anything special ?

**Comment by adevelopcr** [comment]
I checked the old releases and it didn't have the asm folder or the asm files and didn't use the assembler
so is the new version incompatible with visual studio 2015 ?

**Comment by adevelopcr** [comment]
@xmrig

**Comment by xmrig** [comment]
I will check it tomorrow, likely need add some workarounds for MSVC 2015. asm code successfully compiled with MSVC 2017.

**Comment by adevelopcr** [comment]
Can I build with option WITH_ASM=OFF

**Comment by adevelopcr** [comment]
yes it built but I think I'll lose some performance , am I right ?

**Comment by xmrig** [comment]
Fixed in [dev](https://github.com/xmrig/xmrig/commits/dev) branch.
Your are right, without ASM you lose performance for `cn/2` with single and double modes. More about `asm` option https://github.com/xmrig/xmrig/issues/753#issuecomment-424243330.
Thank you.
