### ISSUE TITLE
Why do I have this?

### ISSUE THREAD

**Issue by roscopwnz** [xmrig/xmrig#772]
Hey,

I have no idea why this is on my system but I don't want it, and keep deleting the files but they keep coming back...

How was it installed and how can I remove it permanently, it's using 70%+ CPU and causing CPU to at 100% all the time

**Comment by snipeTR** [comment]
Xmrig legal miner. If your computer is infected with malicious software, delete it. use malware, downloader or software to detect other pests. eset internet security suggest

**Comment by el00ruobuob** [comment]
@roscopwnz go to malware response workgroup site mrw.getmonero.org and  IRC channel #monero-mrw and the community will help you to remove the malware you're infected with.
