### ISSUE TITLE
Error compile 2.8 xmrig 

### ISSUE THREAD

**Issue by LearnMiner** [xmrig/xmrig#773]
Bat:
mkdir build
cd build
cmake .. -G "Visual Studio 15 2017" -DXMRIG_DEPS=c:\xmrig-deps-3.3\msvc2017\x86
pause

![image](https://user-images.githubusercontent.com/34003340/46424325-1b4e9c00-c739-11e8-8005-8fd17518f184.png)

**Comment by xmrig** [comment]
Make sure your update your Visual Studio to recent version, 15.8.6 at this moment. xmrig-deps compatible only with MSVC 2017 15.8+.
Thank you.

**Comment by xmrig** [comment]
Generally bad idea use x86 miner, it much slower that x64, especially for upcoming `cn/2`.

**Comment by LearnMiner** [comment]
@xmrig I know but i test always all miners 32 and 64 for see % lose

**Comment by xmrig** [comment]
@LearnMiner Sorry, I missed you was edit your comment, because of TLS support, it can be disabled `-DWITH_TLS=OFF`.
