### ISSUE TITLE
xmrig 2.8.0 Error on Linux platform

### ISSUE THREAD

**Issue by rocke** [xmrig/xmrig#779]
CentOS release 6.5 (Final)
2.6.32-431.23.3.el6.x86_64
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC)

False hints：/lib64/libc.so.6: version `GLIBC_2.15' not found

**Comment by xmrig** [comment]
Binary build, from releases page works on Ubuntu 16.04 or newer, so your need build miner from source it required gcc 4.9+.
Thank you.

**Comment by DeadManWalkingTO** [comment]
Required gcc 4.9+.

I think this issue can be closed.
Thank you!
