### ISSUE TITLE
build error on linux centos

### ISSUE THREAD

**Issue by 0xman** [xmrig/xmrig#783]
Hey can you explain to me what this error means http://prntscr.com/l3oqx0

**Comment by xmrig** [comment]
What your compiler version? Minimum reported working version is gcc 4.9. You compiler too old and not support `-Ofast`, you can edit this file https://github.com/xmrig/xmrig/blob/master/cmake/flags.cmake#L16 and replace `-Ofast` to `-O2` and try again, but better use newer compiler.
Thank you.

**Comment by 0xman** [comment]
how do i compile with out microhttpd/0.9.44
OpenSSL/1.0.2g
?

**Comment by xmrig** [comment]
`-DWITH_HTTPD=OFF -DWITH_TLS=OFF`

**Comment by 0xman** [comment]
what's this av=0 ? http://prntscr.com/l4mxvq isnt supposed to be av=1 ?

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
Thank you!
