### ISSUE TITLE
Static build

### ISSUE THREAD

**Issue by 0xman** [xmrig/xmrig#789]
How do i make a static build ? So i can use it on all my Servers with and needing to install extra dependencies.

**Comment by xmrig** [comment]
It not trivial, keyword **musl** https://github.com/xmrig/xmrig/search?q=musl&type=Issues
Thank you.

**Comment by lotus1313** [comment]
> 
> 
> How do i make a static build ? So i can use it on all my Servers with and needing to install extra dependencies.

https://github.com/lotus1313/xmrig

**Comment by kn1f4** [comment]
> > How do i make a static build ? So i can use it on all my Servers with and needing to install extra dependencies.
> 
> https://github.com/lotus1313/xmrig
> But without http server and SSL/TLS

this page is 404...
