### ISSUE TITLE
Can't get speed on android

### ISSUE THREAD

**Issue by n4cg** [xmrig/xmrig#791]
Hello!
I built it on android,and it's work.But the speed always show n/a.
How to fix it?

**Comment by DeadManWalkingTO** [comment]
Please give more details.
OS Version
Program Version
Hardware
Thank you!

**Comment by n4cg** [comment]
@DeadManWalkingTO 
Thank you. Please forgive me for asking a silly question.
The reason is that there is something wrong with the pool,so actually it's not work
I close this issue now

**Comment by HyperSimon** [comment]
How do you build it?
