### ISSUE TITLE
change name of compiled exe

### ISSUE THREAD

**Issue by emailyc** [xmrig/xmrig#793]
Is there a way to change the name of the compiled .exe file? Changing the name after compiling will still have the original file name shown in the properties details page.

**Comment by xmrig** [comment]
No need compile to change this, tools like Resource Hacker can change this name.
Anyway name defined there https://github.com/xmrig/xmrig/blob/master/res/app.rc#L27

**Comment by sharik987** [comment]
![image](https://user-images.githubusercontent.com/61291956/217835937-5eb2637a-c238-4e34-b12d-e50ab2422eb2.png)
Not work
