### ISSUE TITLE
libssl.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by welj** [xmrig/xmrig#795]
After update to latest xmrig i nave an error:

`xmrig: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory`

`openssl version
OpenSSL 1.1.0f  25 May 2017
`
Ubuntu 16.04

**Comment by xmrig** [comment]
Please provide all possible information, you compile miner from source (how?) or use prebuilt binary.
Thank you.

**Comment by welj** [comment]
Like this:
git clone https://github.com/xmrig/xmrig.git
cd xmrig
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib64/libuv.a -DWITH_HTTPD=OFF -DWITH_AEON=OFF
make

If i make like:

cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib64/libuv.a -DWITH_HTTPD=OFF -DWITH_AEON=OFF -DWITH_TLS=OFF  -- its okay

**Comment by xmrig** [comment]
Ubuntu 16.04 shipped with OpenSSL 1.0.2g and miner compiled and works fine with this version. So this issue related how OpenSSL 1.1.0f installed on your system and what version found cmake.
Thank you.

**Comment by welj** [comment]
all time im compiled  miner at Centos 7 with
openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

and send miner on my server Ubunte 16.04 - and fine works, now not. Only with -DWITH_TLS=OFF works.

**Comment by xmrig** [comment]
OpenSSL support added in v2.8, if you no need SSL/TLS support, you can compile with `-DWITH_TLS=OFF` it's ok. If need SSL/TLS support AND binary compatibility with CentOS and Ubuntu you should build own static OpenSSL.

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
Thank you!
