### ISSUE TITLE
Issues Building [Complete Newbie]

### ISSUE THREAD

**Issue by lolcocks123** [xmrig/xmrig#80]
Sorry for being a complete newbie in here.

I have been trying to build this project since yesterday. The Visual Studio 15 2017 solution.

I installed cmake from the link below:
https://cmake.org/download/

and the latest version of libuv from the link below:
https://dist.libuv.org/dist/

After which I ran the command stated inserting the path of the libuv.lib file.
Below is the error I am getting.

**Command:**
cmake .. -G "Visual Studio 15 2017 Win64" -T v140_xp -DCMAKE_BUILD_TYPE=Release -DUV_INCLUDE_DIR=c:\Program Files\libuv\include -DUV_LIBRARY=c:\Program Files\libuv\libuv.lib

**Error:**
CMake Error: The source directory "C:/Users/Test Server/Desktop/xmrig-master/Files/libuv/libuv.lib" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

What exactly am I doing wrong?

Sorry for the newbie troubles, first time I am building something.

**Comment by therealseeku** [comment]
Try using quotes for paths with spaces:

`cmake .. -G "Visual Studio 15 2017 Win64" -T v140_xp -DCMAKE_BUILD_TYPE=Release  DUV_INCLUDE_DIR="c:\Program Files\libuv\include" -DUV_LIBRARY="c:\Program Files\libuv\libuv.lib"`

**Comment by lolcocks123** [comment]
Thank you for your help @therealseeku but if I use the quotes then the path doesn't get recognized properly it seems.

C:\Users\Test Server\Desktop\xmrig-master\build>cmake .. -G "Visual Studio 15 2017 Win64" -T v140_xp -DCMAKE_BUILD_TYPE=Release DUV_INCLUDE_DIR="C:\Program Files\libuv\include"  -DUV_LIBRARY="C:\Program Files\libuv\libuv.lib"


CMake Error: The source directory "C:/Users/Test Server/Desktop/xmrig-master/build/DUV_INCLUDE_DIR=C:/Program Files/libuv/include" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.



Have you tried building it yourself? Did it work?
I have no idea what I am doing wrong. 
Maybe something to do with the libuv libraries?

**Comment by therealseeku** [comment]
Sorry, in my Answer the - before DUV... was missing

`cmake .. -G "Visual Studio 15 2017 Win64" -T v140_xp -DCMAKE_BUILD_TYPE=Release -DUV_INCLUDE_DIR="c:\Program Files\libuv\include" -DUV_LIBRARY="c:\Program Files\libuv\libuv.lib"`

**Comment by lolcocks123** [comment]
@therealseeku , 
Ah, well that was probably my bad as well, I should have properly looked into the command before executing it.
Thank you.


So I built it using the 141 Toolchain.
I have a few questions if you can answer them.

1. I used the 64 bit libuv library, so will my project work, once built through Visual Studio, work on 32 bit Windows?

2. The command states v140_xp of the toolchain but I used v141. What did the '_xp' part stand for?

**Comment by xmrig** [comment]
1. 64 bit builds works only on 64 bit operating systems.
2. _xp enables support for older systems like Windows XP and 2003, required old platform SDK installed.

Anyway I don't use _xp trick for release build, for 32 bit, better use MSYS2 it faster and supports old systems as well.

**Comment by lolcocks123** [comment]
@xmrig Thank you. 

I will give MSYS2 a shot later. I am still at a pretty noob stage. I will try it after I am successful with the cmake builds.

One small question (and probably the last one, sorry for these entire series of noob questions).

`cmake .. -G "Visual Studio 15 2017 Win64" -T v141 -DCMAKE_BUILD_TYPE=Release -DUV_INCLUDE_DIR="C:\libuv-msvc2017-x86\include" -DUV_LIBRARY="C:\libuv-msvc2017-x86\lib\libuv.lib"`

I built it using the 32 bit libuv, however the command states "Win64". It builds a 64 bit application
How can I build a 32 bit application?

**Comment by xmrig** [comment]
Just remove Win64, like `-G "Visual Studio 15 2017"`.

**Comment by lolcocks123** [comment]
@xmrig Ah, cool, thank you.

Dumb me was trying `-G "Visual Studio 15 2017 Win32"`

**Comment by lolcocks123** [comment]
@xmrig, can you help me out with building xmrig using MSYS2?

I have never used MSYS2 before.
I installed all the packages mentioned in your build instructions but don't know how to build, can you help me out with that one?

Thank you.

**Comment by foxx3n** [comment]
The same questions for me, few days ago I just tried xmr-stak and it caused me many headaches and depression xD, but at the end we got an EXE file. Is there other steps to follow? In my case: Windows 10 and Visual Studio 17. Thanks.
