### ISSUE TITLE
About -DBUILD_STATIC=ON

### ISSUE THREAD

**Issue by rocke** [xmrig/xmrig#801]
OS: Centos 7

I have the following error after using the -DBUILD_STATIC=ON parameter:

> cc1plus: 警告：无法识别的命令行选项“-Wno-class-memaccess” [默认启用]
> [ 94%] Building CXX object CMakeFiles/xmrig.dir/src/common/api/Httpd.cpp.o
> [ 96%] Building CXX object CMakeFiles/xmrig.dir/src/common/api/HttpRequest.cpp.o
> [ 98%] Building CXX object CMakeFiles/xmrig.dir/src/common/net/Tls.cpp.o
> [100%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/Asm.cpp.o
> Linking CXX executable xmrig
> /usr/bin/ld: 找不到 -lssl
> /usr/bin/ld: 找不到 -lcrypto
> collect2: 错误：ld 返回 1
> make[2]: *** [xmrig] 错误 1
> make[1]: *** [CMakeFiles/xmrig.dir/all] 错误 2
> make: *** [all] 错误 2
>

**Comment by srwx666** [comment]
You are missing static openssl library.

**Comment by lotus1313** [comment]
> 
> 
> OS: Centos 7
> 
> I have the following error after using the -DBUILD_STATIC=ON parameter:
> 
> > cc1plus: 警告：无法识别的命令行选项“-Wno-class-memaccess” [默认启用]
> > [ 94%] Building CXX object CMakeFiles/xmrig.dir/src/common/api/Httpd.cpp.o
> > [ 96%] Building CXX object CMakeFiles/xmrig.dir/src/common/api/HttpRequest.cpp.o
> > [ 98%] Building CXX object CMakeFiles/xmrig.dir/src/common/net/Tls.cpp.o
> > [100%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/Asm.cpp.o
> > Linking CXX executable xmrig
> > /usr/bin/ld: 找不到 -lssl
> > /usr/bin/ld: 找不到 -lcrypto
> > collect2: 错误：ld 返回 1
> > make[2]: *** [xmrig] 错误 1
> > make[1]: *** [CMakeFiles/xmrig.dir/all] 错误 2
> > make: *** [all] 错误 2

https://github.com/lotus1313/xmrig
