### ISSUE TITLE
config.xmrig.com not available in all options.

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig#803]
for example
"threads": "all",
"safe": true,
"huge-pages": true,

**Comment by xmrig** [comment]
`safe` and `huge-pages` available in simple threads mode https://i.imgur.com/Y7LqWah.png for `safe` it's right place, but yes `huge-pages` should available for all modes.
About `"threads": "all"` don't think it much useful for GUI.
Thank you.

**Comment by snipeTR** [comment]
I think, however, all of the options must have all settings on the site. with no exceptions. I don't think it will be very difficult.
your program is excellent, but the documentation is bad.

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/config
