### ISSUE TITLE
Is this proof that it has passed?

### ISSUE THREAD

**Issue by rocke** [xmrig/xmrig#804]
> [2018-10-16 11:00:05] configuration saved to: "/var/tmp/config.json"
> [2018-10-16 11:00:05] READY (CPU) threads 4(4) huge pages 0/4 0% memory 8.0 MB
> [2018-10-16 11:00:05] use pool killallasics.moneroworld.com:3333  66.85.74.134 
> [2018-10-16 11:00:05] new job from killallasics.moneroworld.com:3333 diff 100 algo cn/2
> [2018-10-16 11:00:05] accepted (1/0) diff 100 (284 ms)
> [2018-10-16 11:00:06] accepted (2/0) diff 100 (278 ms)
> [2018-10-16 11:00:09] accepted (3/0) diff 100 (284 ms)
> [2018-10-16 11:00:10] accepted (4/0) diff 100 (280 ms)
> [2018-10-16 11:00:10] accepted (5/0) diff 100 (360 ms)
> [2018-10-16 11:00:10] accepted (6/0) diff 100 (284 ms)
> [2018-10-16 11:00:11] accepted (7/0) diff 100 (284 ms)
> [2018-10-16 11:00:12] accepted (8/0) diff 100 (286 ms)
> [2018-10-16 11:00:12] accepted (9/0) diff 100 (284 ms)
> [2018-10-16 11:00:13] accepted (10/0) diff 100 (284 ms)
> [2018-10-16 11:00:14] accepted (11/0) diff 100 (280 ms)
> [2018-10-16 11:00:15] accepted (12/0) diff 100 (204 ms)
> [2018-10-16 11:00:15] accepted (13/0) diff 100 (209 ms)
> [2018-10-16 11:00:16] new job from killallasics.moneroworld.com:3333 diff 200 algo cn/2
> [2018-10-16 11:00:16] accepted (14/0) diff 200 (285 ms)
> [2018-10-16 11:00:17] accepted (15/0) diff 200 (446 ms)
> [2018-10-16 11:00:18] accepted (16/0) diff 200 (203 ms)
> [2018-10-16 11:00:24] accepted (17/0) diff 200 (284 ms)
> [2018-10-16 11:00:25] accepted (18/0) diff 200 (203 ms)
> [2018-10-16 11:00:26] accepted (19/0) diff 200 (280 ms)
> [2018-10-16 11:00:26] accepted (20/0) diff 200 (307 ms)
> [2018-10-16 11:00:26] accepted (21/0) diff 200 (282 ms)
> [2018-10-16 11:00:30] accepted (22/0) diff 200 (205 ms)
> [2018-10-16 11:00:30] accepted (23/0) diff 200 (237 ms)
> [2018-10-16 11:00:30] accepted (24/0) diff 200 (421 ms)
> [2018-10-16 11:00:30] accepted (25/0) diff 200 (383 ms)
> [2018-10-16 11:00:31] accepted (26/0) diff 200 (284 ms)
> [2018-10-16 11:00:33] accepted (27/0) diff 200 (203 ms)
> [2018-10-16 11:00:33] accepted (28/0) diff 200 (203 ms)
> [2018-10-16 11:00:34] accepted (29/0) diff 200 (203 ms)
> [2018-10-16 11:00:34] accepted (30/0) diff 200 (203 ms)
> [2018-10-16 11:00:36] accepted (31/0) diff 200 (284 ms)
>

**Comment by xmrig** [comment]
* `algo cn/2` <- algorithm `cn/2` aka `cryptonight/2`.
* `accepted (1/0) diff 100 (284 ms)` <- share accepted by pool.
