### ISSUE TITLE
Command line option for -l, --log-file=FILE donesn't work after 2.5

### ISSUE THREAD

**Issue by JustHoldit** [xmrig/xmrig#806]
The command line option for log to file does not work in the last few releases. I have not tested all versions but it looks to have appeared in 2.6.

-l, --log-file=FILE      log all output to a file

xmrrig seems to ignore it

**Comment by welj** [comment]
works that me  -lstats.log

**Comment by JustHoldit** [comment]
does:   --log-file=lstats.log work for you?

**Comment by JustHoldit** [comment]
I have confirmed that:  /usr/rig/xmrig -l/path/to/filename.log  --background 
works for me. 

This however does not work
/usr/rig/xmrig --log-file=/path/to/filename.log --background

**Comment by xmrig** [comment]
`./xmrig --url donate.v2.xmrig.com:3333 --log-file=xmrig.log --background` works fine for me, however mixed configuration config file + command line seems broken.
Thank you.

**Comment by snipeTR** [comment]
./xmrig --url donate.v2.xmrig.com:3333 --log-file=./xmrig.log --background
