### ISSUE TITLE
How to add config datas into xmrig.exe file 

### ISSUE THREAD

**Issue by Yaropolkgh** [xmrig/xmrig#807]
Hi 

I need to add the config datas (config.json) into Xmrig.exe as single file

Thank you

**Comment by 2010phenix** [comment]
first of all this is not issue
second use search man...

**Comment by adevelopcr** [comment]
Why ? Are you packaging a virus ?

**Comment by snipeTR** [comment]
if it builds a virus. I don't think he asked here.

**Comment by adevelopcr** [comment]
@snipeTR then think again . You probably don't know how small hackers (they aren't programmers) manage to do what they want

**Comment by snipeTR** [comment]
Yeah i know. I'm :)

**Comment by adevelopcr** [comment]
what is this : "I'm :)" ? are you admitting on public hhhhh

**Comment by mrleduck** [comment]
> Why ? Are you packaging a virus ?

or he is intrested in mining on multiple pc's/devices managed via 1 network if you are a owner of a internet gaming center. and you wanna mine when the pc's idle and you dont want the customers to fuck with the config IF they find it on there, or any other business mining on large amount of pc's with a fixed config its eassier like that

**Comment by adevelopcr** [comment]
@Yaropolkgh if someone else still needs this I can help . But the config will be hardcoded in the binary so you won't be able to change it , or you had better write the config on some online server then retrieve it from the device you are mining on so you can update it
