### ISSUE TITLE
Please add -DWITH_TLS=OFF into wiki's build instructions

### ISSUE THREAD

**Issue by adem4ik** [xmrig/xmrig#812]
2.8.1 added TSL support, but this increases binary size for 2 MB, some people may not need it at all, so there is possibility to build w/o TLS. So my suggestion is simple - please add `-DWITH_TLS=OFF` into wiki: https://github.com/xmrig/xmrig/wiki/Build inside `Additional CMake options`.

**Comment by xmrig** [comment]
Done.

**Comment by adem4ik** [comment]
@xmrig thank you!
