### ISSUE TITLE
win64 cmake error

### ISSUE THREAD

**Issue by passwordhhh** [xmrig/xmrig#815]
When I used cmake to generate vs projects, I made a mistake, and added - DWITH_ASM = OFF, the mistake disappeared, and I figured out how to fix it.
![e gb e9sj _gmuf 4sm9](https://user-images.githubusercontent.com/37529845/47194149-d3f71b00-d388-11e8-96a7-8bd743606c4f.png)

**Comment by passwordhhh** [comment]
vs2015，cmake3.4.3

**Comment by xmrig** [comment]
Update your cmake to recent version.
Thank you.

**Comment by passwordhhh** [comment]
@xmrig ok，Thank you. I solved it.
