### ISSUE TITLE
Wrong algo for minergate

### ISSUE THREAD

**Issue by TomskDiver** [xmrig/xmrig#816]
xmrig v2.8.1

I set in pool config *"variant": 2,* but xmrig choose variant 1 (cn/1). Pls, fix it!

![image](https://user-images.githubusercontent.com/2425151/47197687-022d2880-d392-11e8-8fb8-89f5ad36c49c.png)

I try set -1 for autoselect, but it select variant 1 too.

**Comment by xmrig** [comment]
Duplicate #813 Fixed in v2.8.3.
Thank you.
