### ISSUE TITLE
Please look for libmicrohttpd.a instead of libmicrohttpd.so when STATIC option is used

### ISSUE THREAD

**Issue by ehaupt** [xmrig/xmrig#818]
Currently when you're building the static version and want to build with microhttpd, cmake is looking for libmicrohttpd.so instead of libmicrohttpd.a.

**Comment by xmrig** [comment]
Bad idea, usually system libmicrohttpd build with GnuTLS, so static linking with GnuTLS required too. For static build should build own libmicrohttpd without additional unused dependencies.

For example next command give you libmicrohttpd.a usable for static linking.
`./configure --disable-shared --disable-doc --disable-examples --disable-curl --enable-https=no --disable-bauth --disable-dauth --disable-httpupgrade`

**Comment by ehaupt** [comment]
Sure. Works for me.
