### ISSUE TITLE
GPU #1: an illegal memory access was encountered cryptonight_extra_cpu_final line 247

### ISSUE THREAD

**Issue by kolet** [xmrig/xmrig#82]
![image](https://user-images.githubusercontent.com/17353839/29970238-762d56a2-8f2c-11e7-9b91-fd71ba659b01.png)

cant get it started ..

config file is this

`{
    "algo": "cryptonight",
    "background": false,
    "colors": true,
    "donate-level": 5,
    "log-file": null,
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "threads": [
        {
            "index": 0,
            "threads": 32,
            "blocks": 45,
            "bfactor": 6,
            "bsleep": 25
        },
        {
            "index": 1,
            "threads": 32,
            "blocks": 45,
            "bfactor": 6,
            "bsleep": 25
        }
    ],
    "pools": [
        {
            "url": "pool.minexmr.com:4444",
            "user": "xxxxxxxx.xxxxx",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        }
    ]
}`

installed latest driver at the time 385.41
and tested out 384.76 

the card is a super jetstream from palit 1070 8GB, with micron memory

**Comment by xmrig** [comment]
Very strange should work fine with these options, please check work with single card and try change `threads` count. There no others miners working in same time?

**Comment by kolet** [comment]
not working with 1 or 6 or 2..
and no other miners is runing at the same time
