### ISSUE TITLE
AMD Opteron's 62XX series  hashrate dropped bitterly by 30% on v8

### ISSUE THREAD

**Issue by nuriyevn** [xmrig/xmrig#823]
Opteron's 6234, 6276 dropped not for 10%.
for 6276 the max what I can get now is 702 H/s, before it was 995-1002 . minus 30%
6234 dropped from 800 to 600  minus 25%. The same setting, the same environment.

**Comment by 2010phenix** [comment]
@nuriyevn and where is problem? where issue?
already write what CPU optimizzzze and what not... use search...

**Comment by nuriyevn** [comment]
Thank you for your answer.
"already write what CPU optimizzzze and what not... use search..."
You speak like a drunk russian man, lol :))
Using the search isn't the worst idea in the  world, however this reference is covering only small number of CPU-s as for reference.
https://github.com/SChernykh/xmr-stak-cpu/blob/master/README.md
So I am asking if someone can confirm  this is the normal hashrate or can provide an instruction  regarding optimization according to the changes that happened  in the recent update? That's a question.

**Comment by 2010phenix** [comment]
as write before @SChernykh work on optimization... and search is very good things man ;-) https://github.com/SChernykh/xmr-stak-cpu/commit/f4dfc2b36d11a7271948c3c7858f93c58f209852

**Comment by fantforever** [comment]
I also confirm 30% hashrate drop with all Opterons 62xx series

**Comment by madscientist159** [comment]
The Bulldozer core is old and very weak on the integer math that CNv8 relies on.  I shut my Opteron miners down as they are no longer profitable; the only ones left are driving GPUs that are doing the real heavy lifting.

**Comment by nuriyevn** [comment]
> The Bulldozer core is old and very weak on the integer math that CNv8 relies on. I shut my Opteron miners down as they are no longer profitable; the only ones left are driving GPUs that are doing the real heavy lifting.

I think the reason is simpler, no one asked to optimize it for Bulldozer before CNv8? :)

**Comment by BlackFury** [comment]
Hashrate drop too with Buldozer gen since v8.
This gen isn't weak but now need opti !

**Comment by xmrig** [comment]
Current dev branch include ASM for such CPUs https://github.com/xmrig/xmrig/pull/834, but it can bring back only few %. cryptonight/2 designed to iluminate any hardware cheats, Buldozer use hardware cheats it's 1 FPU for 2 cores because of this perfomance drop much more than other CPUs.

**Comment by nuriyevn** [comment]
Hm.  Before update it was 2.43 years to start making it profitable with amazing price of energy (0.03$ per kilo) now those servers  can only start making profit after 5.7 years.
I am not including the cost of energy accumulators because that energy price is available only at the night.
Thanks for eliminating hardware cheats! :dancer: 
I hope monero will be at least 36000$  otherwise...
At least I can heat my two apartment with 13 servers, lol. 
Could you make this fork earlier before I spent 3000$ on shitty AMD servers?  lol.
