### ISSUE TITLE
RunTime Error 64x 86x

### ISSUE THREAD

**Issue by AhmedZeus** [xmrig/xmrig#826]
i get this error for 64x  , 86x release 

Updated MSYS2 , Using last Deps. and Using this command for 64x

cmake .. -G "Unix Makefiles" -DWITH_HTTPD=OFF  -DWITH_AEON=OFF -DCMAKE_BUILD_TYPE=Release -DUV_INCLUDE_DIR="C:\Users\xxx\Downloads\lib\gcc\x64\include" -DUV_LIBRARY="C:\Users\xxx\Downloads\lib\gcc\x64\lib\libuv.a" 

https://image.ibb.co/nOSA1L/asdsad.png

https://image.ibb.co/fHXcgL/ewqeqwewqrbb.png

**Comment by xmrig** [comment]
Follow instructions https://github.com/xmrig/xmrig/wiki/Windows-Build use xmrig-deps or build static libuv.
Thank you.
