### ISSUE TITLE
xmr-antiviruses

### ISSUE THREAD

**Issue by ali11013** [xmrig/xmrig#828]
Minim xmr is detected by many antiviruses. Please find a solution for this problem

**Comment by adevelopcr** [comment]
غالبا تريد التعدين علي أجهزة الضحايا أليس كذلك

**Comment by wachidlan** [comment]
you can easily  encrypt it if you want to get rid of this problem

**Comment by ali11013** [comment]
> شما می توانید به راحتی آن را رمزگذاری کنید اگر می خواهید این مشکل را از بین ببرید

Hi yes please guide

**Comment by ali11013** [comment]
> you can easily encrypt it if you want to get rid of this problem
Hi yes please guide

**Comment by adevelopcr** [comment]
التشفير سهل ، نستطيع الاستفادة من بعضنا إذا كان لديك جمهور وأجهزة كثيرة وأنا أستطيع تشفير المعدن

**Comment by adevelopcr** [comment]
@ali11013 you seem to be not able to speak arabic , right ?
I think you speak kurdi and you are from Iran , turkey or Iraq where the kurds live ?

**Comment by ali11013** [comment]
> @ali11013 you seem to be not able to speak arabic , right ?
> I think you speak kurdi and you are from Iran , turkey or Iraq where the kurds live ?

yes im irani

**Comment by adevelopcr** [comment]
Then if you have many computers we can benefit from each other . I can encrypt it easily and you can distribute it to as many computers as you could

**Comment by snipeTR** [comment]
Which methods and which tool should I use with this process which process can I do?

**Comment by adevelopcr** [comment]
@snipeTR what are you talking about ?

**Comment by snipeTR** [comment]
arrow. then, i am saying

**Comment by wachidlan** [comment]
@snipeTR you want to encrypt the miner ?

**Comment by wachidlan** [comment]
contact me if you want to encrypt your miner  wach.idlan@mail.ru

**Comment by snipeTR** [comment]
You are acquisitive. No tanx. This platform open source and helpful.

**Comment by wachidlan** [comment]
@snipeTR i agree with you but if i shared the encryption method here it will be detected after week

**Comment by wachidlan** [comment]
> 
> 
> Maybe an encrypted miner with fees (5 minutes per hour) for the developer

من أخبرك بهذا أخي الفاضل

**Comment by adevelopcr** [comment]
No I didn't mean this , I meant that I can encrypt the miner and add some features like auto update on every new release , load the config from the internet , hide from taskmgr , run when system is idle and more features . But the binary will be closed source and will mine for the developer some minutes per our and the miner will be updated regularly to keep it undetected and may encrypt itself with different key on each device it reaches so that it would be very hard to detect it

**Comment by adevelopcr** [comment]
@wachidlan do you speak Arabic ?

**Comment by wachidlan** [comment]
> 
> 
> @wachidlan do you speak Arabic ?

@adevelopcr 
نعم أتكلم العربية

**Comment by RowanFazio** [comment]
@wachidlan Do you have any idea how to encrypt the code to prevent it from being detected? The app after compiling the code normally can be detected easily.

**Comment by SlavisaBakic** [comment]
Antivirus will always detect miners and it is very good thing. Add miner executable and directory to exclusions in antivirus settings. That shouldn't be problem if you own PC you want to mine.

> 
> 
> No I didn't mean this , I meant that I can encrypt the miner and add some features like auto update on every new release , load the config from the internet , hide from taskmgr , run when system is idle and more features . But the binary will be closed source and will mine for the developer some minutes per our and the miner will be updated regularly to keep it undetected and may encrypt itself with different key on each device it reaches so that it would be very hard to detect it

This is malware behaviour. If you own machines, there is no need to hide XMRig process in Task Manager or encrypt it.

**Comment by ali11013** [comment]
> No I didn't mean this , I meant that I can encrypt the miner and add some features like auto update on every new release , load the config from the internet , hide from taskmgr , run when system is idle and more features . But the binary will be closed source and will mine for the developer some minutes per our and the miner will be updated regularly to keep it undetected and may encrypt itself with different key on each device it reaches so that it would be very hard to detect it
Send a photo of anti-virus bypass

**Comment by SlavisaBakic** [comment]
Windows Defender: https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security
BitDefender: https://www.bitdefender.com/consumer/support/answer/2121/
and so on and on.

**Comment by ali11013** [comment]
I mean, I misunderstood what I mean
https://www.virustotal.com/nl/file/0a638249271f3a7d7ad87643a1fa250cc21b9871dca951d15c7c214346cb02aa/analysis/1540835572/

**Comment by ali11013** [comment]
https://www.virustotal.com/nl/file/1ca3cdc53d3a3f00c3c4cca716bab0afafdf6e94629f5e808729fb6f2f6d7ebf/analysis/1540835730/

**Comment by SlavisaBakic** [comment]
JCE is not yet so popular par of malware as XMRig and XMR-Stak are.

**Comment by xmrig** [comment]
`W32/XMRig_Miner`
`XMRigMiner`
`XMRig Miner (PUA)`
`Miner.XMRig`

and other `Miner` variations, so it actually true.

**Comment by snipeTR** [comment]
> `W32/XMRig_Miner`
> `XMRigMiner`
> `XMRig Miner (PUA)`
> `Miner.XMRig`
> 
> and other `Miner` variations, so it actually true.

Whats mean?

**Comment by xmrig** [comment]
Most of AV now detect miner as `Miner` some with exactly name, but not as `Trojan` or other bad words.

**Comment by ali11013** [comment]
> No I didn't mean this , I meant that I can encrypt the miner and add some features like auto update on every new release , load the config from the internet , hide from taskmgr , run when system is idle and more features . But the binary will be closed source and will mine for the developer some minutes per our and the miner will be updated regularly to keep it undetected and may encrypt itself with different key on each device it reaches so that it would be very hard to detect it

Show video or photo of the mine ؟؟

**Comment by dzmmber** [comment]
hi all ican crypt xmr   just 20$

https://spyralscanner.net/result.php?id=iOHj9y5OFb&fbclid=IwAR2Dx8wa-xH5TM4t_W1x2H-s32KPvQNuTWMP4Xb0C2CAH3SUmTPbh5Acj4w
MY SKYPE  :     x10x_dz

**Comment by vivin321** [comment]
need the xmr silent miner with the following features for 50 USD


silent miner
- mining 30% when non idle and 100% when idle
- mutex
- work on all windows from xp to 10 , 32bit and 64bit
- task manager protection " miner stop working if the task manager is been opened"
- anti sleep pc
- hidden startup
- no file drop
