### ISSUE TITLE
Minergate issue Procedure not found

### ISSUE THREAD

**Issue by Afapa** [xmrig/xmrig#83]
Hello, im getting this issue "code": -32601, "message": "Procedure not found." then timeout error, when i mining via xmr.pool.minergate.com:45560, this issue happens sometimes, so i'm losing my h/s while xmrig trying to decide this problem... It doesn't happens on same pc when i'm mining via minemonero.

**Comment by xmrig** [comment]
minergate doesn't support keepalived method (ping pool if miner long time not submit shares), remove `-k` command line option or set `"keepalive": false,` in config file.
Thank you.

**Comment by Afapa** [comment]
Thank you :)
