### ISSUE TITLE
run xmrig but cpu not start

### ISSUE THREAD

**Issue by tarxzvf** [xmrig/xmrig#833]
run xmrig on different pc  but no all start cpu , where is problem .. thanks

**Comment by snipeTR** [comment]
Share config.json

**Comment by tarxzvf** [comment]
{
    "algo": "cryptonight",
    "api": {
        "port": 0,
        "access-token": null,
        "id": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "asm": true,
    "autosave": true,
    "av": 0,
    "background": false,
    "colors": true,
    "cpu-affinity": null,
    "cpu-priority": null,
    "donate-level": 1,
    "huge-pages": true,
    "hw-aes": null,
    "log-file": null,
    "max-cpu-usage": 50,
    "pools": [
        {
            "url": "ca.minexmr.com:5555",
            "user": "474jo9QWGxLde8ohapGQLrfxxhARmAR421FjSpWGbx2x4fWH3USyVhYaanWVCH7nV8ZBWp4uxVjw1g7FpcvFCy9PQ4s3sht",
            "pass": "x",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "variant": -1,
            "tls": false,
            "tls-fingerprint": null
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "safe": false,
    "threads": null,
    "user-agent": null,
    "watch": false
}


 * ABOUT        XMRig/2.8.1 gcc/8.2.0
 * LIBS         libuv/1.23.1 microhttpd/0.9.59
 * HUGE PAGES   unavailable
 * CPU          Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz (2) x64 AES
 * CPU L2/L3    4.0 MB/30.0 MB
 * THREADS      4, cryptonight, donate=1%
 * ASSEMBLY     auto:intel
 * POOL #1      ca.minexmr.com:5555 variant auto
 * COMMANDS     hashrate, pause, resume
[2018-10-21 07:05:58] READY (CPU) threads 4(4) huge pages 0/4 0% memory 8.0 MB
[2018-10-21 07:05:59] [ca.minexmr.com:5555] connect error: "connection refused"




 * ABOUT        XMRig/2.8.1 gcc/8.2.0
 * LIBS         libuv/1.23.1 microhttpd/0.9.59
 * HUGE PAGES   unavailable
 * CPU          Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz (2) x64 AES
 * CPU L2/L3    4.0 MB/30.0 MB
 * THREADS      4, cryptonight, donate=1%
 * ASSEMBLY     auto:intel
 * POOL #1      ca.minexmr.com:5555 variant auto
 * COMMANDS     hashrate, pause, resume
[2018-10-21 07:05:58] READY (CPU) threads 4(4) huge pages 0/4 0% memory 8.0 MB
[2018-10-21 07:05:59] [ca.minexmr.com:5555] connect error: "connection refused"


thanks for reply man ... any pool i use said that .. on some pc works .. 

on pc work config is same .. where not work config change auto

**Comment by tarxzvf** [comment]
if you can help me or have ideea , appreciate , thanks

**Comment by gboelter** [comment]
Only an idea, try 3333 instead 5555 ...

**Comment by 2010phenix** [comment]
confirm...
Have same problem and on classic C miner....
Check on few pools with few algo that used cn/1 cn/2
In first look, somewhere lost check about variant or wrong work variant auto
@tarxzvf try manual set  variant 2(cn/2)

**Comment by tarxzvf** [comment]
thanks for reply , i try nothing .. same no connect to pool

**Comment by xmrig** [comment]
`"connection refused"` it's network issue, likely your ISP block connection our you banned on pool. `ca.minexmr.com:5555` works fine for me right now, it resolved to 3 address `158.69.25.62`, `158.69.25.71`, `158.69.25.77` you can try check use IP address instead of domain name.

Also try TLS port `ca.minexmr.com:6666` (don't forget about `"tls": true,`) but you need rebuild miner with OpenSSL support for it.

If all above not help, try smaller pools.

**Comment by tarxzvf** [comment]
still same man .. i think need rebuild miner with OpenSSL like you said .. but me not know make ...thanks

**Comment by tarxzvf** [comment]
if someone want lost time with me , i pay for his time ..

**Comment by srwx666** [comment]
"connection refused"
is a network problem, not xmrig itself
check Your ISP, check Your firewall
try doing telnet to 
ca.minexmr.com 5555
ca.minexmr.com 6666
or whatever port minexmr supports

easyest way for You to check will be to connect to port 80 or 443, to bypass firewall problem

**Comment by snipeTR** [comment]
I tink firewall.

**Comment by tarxzvf** [comment]
hi ,  i turn off firewall but same ..

[2018-10-23 01:07:54] Huge pages support was successfully enabled, but reboot required to use it
 * ABOUT        XMRig/2.8.1 gcc/8.2.0
 * LIBS         libuv/1.23.1 OpenSSL/1.1.1 microhttpd/0.9.59
 * HUGE PAGES   unavailable
 * CPU          Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz (4) x64 AES
 * CPU L2/L3    12.0 MB/60.0 MB
 * THREADS      6, cryptonight, donate=1%
 * ASSEMBLY     auto:intel
 * POOL #1      ca.minexmr.com:5555 variant auto
 * COMMANDS     hashrate, pause, resume
[2018-10-23 01:07:54] READY (CPU) threads 6(6) huge pages 0/6 0% memory 12.0 MB
[2018-10-23 01:07:55] [ca.minexmr.com:5555] connect error: "connection refused"
[2018-10-23 01:08:02] [ca.minexmr.com:5555] connect error: "connection refused"
[2018-10-23 01:08:09] [ca.minexmr.com:5555] connect error: "connection refused"
[2018-10-23 01:08:16] [ca.minexmr.com:5555] connect error: "connection refused"
[2018-10-23 01:08:23] [ca.minexmr.com:5555] connect error: "connection refused"

how try telnet see if works , thanks ppl

**Comment by snipeTR** [comment]
Please debug mod enable.

**Comment by NmxMilk** [comment]
What system are you running on ?
On unix you can test with:
# telnet ca.minexmr.com 5555
Here is what I get:
#telnet ca.minexmr.com 5555
Trying 158.69.25.71...
Connected to ca.minexmr.com.
Escape character is '^]'.

**Comment by NmxMilk** [comment]
By the way, with the four 2630 you got, you should be running 60/2 --> 30 threads.
What hashrate are you getting ? I guess such a system can give about 1kH/s.
