### ISSUE TITLE
[solved] cannot build on FreeBSD 10

### ISSUE THREAD

**Issue by codeorcode** [xmrig/xmrig#839]
When I run:

```
cmake .. -DCMAKE_C_COMPILER=gcc6 -DCMAKE_CXX_COMPILER=g++6
make
```

I got:

```
Linking CXX executable xmrig
/usr/local/bin/ld: cannot find -ldl
collect2: error: ld returned 1 exit status
*** Error code 1
```

xmrig-.2.6 compiled ok.

I've also tried:

`cmake .. -DCMAKE_C_COMPILER=gcc6 -DCMAKE_CXX_COMPILER=g++6 -DCMAKE_EXE_LINKER_FLAGS=-L/usr/local/lib -DCMAKE_SHARED_LINKER_FLAGS=-L/usr/local/lib`

gcc is version: gcc6-6.4.0_3

Any hint?

**Update:** I've managed to compile by removing **-ldl** from _./build/CMakeFiles/xmrig.dir/link.txt_

**Comment by xmrig** [comment]
Please check this commit https://github.com/xmrig/xmrig/commit/acd042c23454c2be617cbdf4d1b562b7c542a2c1 in dev branch, it should solve this issue.
Thank you.
