### ISSUE TITLE
 "Incorrect hashing protocol in use.  Please upgrade/fix your miner"

### ISSUE THREAD

**Issue by omidnavy** [xmrig/xmrig#842]
Hi
I can't use xmrig anymore since the new update.
Already downloaded the latest release and also compiled the code but the result is this:
 "Incorrect hashing protocol in use.  Please upgrade/fix your miner"
or
"error: "Low difficulty share"

So whats going on here ?

**Comment by xmrig** [comment]
At least config or log/screenshot required.
Thank you.

**Comment by krumblez** [comment]
I am getting the same with 2.8.3 on pool.supportxrm.com - whatever difficulty I set 

![image](https://user-images.githubusercontent.com/11175971/47508911-e2ec3a80-d86c-11e8-8ac1-7470129df993.png)

--

my config is:

{
    "algo": "cryptonight",
    "api": {
        "port": 0,
        "access-token": null,
        "id": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "asm": true,
    "autosave": true,
    "av": 0,
    "background": false,
    "colors": true,
    "cpu-affinity": null,
    "cpu-priority": null,
    "donate-level": 1,
    "huge-pages": true,
    "hw-aes": null,
    "log-file": null,
    "max-cpu-usage": 65,
    "pools": [
        {
            "url": "pool.supportxmr.com:5555",
            "user": "463tWEBn5XZJSxLU6uLQnQ2iY9xuNcDbjLSjkn3XAXHCbLrTTErJrBWYgHJQyrCwkNgYvyV3z8zctJLPCZy24jvb3NiTcTJ.d079df2b9d6f4873b873dbd624b5d7614eee4faf473a45bc902e2bb283600cb1",
            "pass": "LittleBlu",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "variant": 1,
            "tls": false,
            "tls-fingerprint": null
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "safe": false,
    "threads": [
        {
            "low_power_mode": 1,
            "affine_to_cpu": false,
            "asm": true
        },
        {
            "low_power_mode": 1,
            "affine_to_cpu": false,
            "asm": true
        },
        {
            "low_power_mode": 1,
            "affine_to_cpu": false,
            "asm": true
        },
        {
            "low_power_mode": 1,
            "affine_to_cpu": false,
            "asm": true
        },
        {
            "low_power_mode": 1,
            "affine_to_cpu": false,
            "asm": true
        },
        {
            "low_power_mode": 1,
            "affine_to_cpu": false,
            "asm": true
        },
        {
            "low_power_mode": 1,
            "affine_to_cpu": false,
            "asm": true
        },
        {
            "low_power_mode": 1,
            "affine_to_cpu": false,
            "asm": true
        },
        {
            "low_power_mode": 1,
            "affine_to_cpu": false,
            "asm": true
        },
        {
            "low_power_mode": 1,
            "affine_to_cpu": false,
            "asm": true
        },
        {
            "low_power_mode": 1,
            "affine_to_cpu": false,
            "asm": true
        }
    ],
    "user-agent": null,
    "watch": false
}

-

I hope this info helps :) 

I will watch for updates so can start mining again. Thank you!

**Comment by krumblez** [comment]
Ok, quick update... I used the cold config.json file, I just copied across to new miner..

So I then used the config in 2.8.3 and added details.. It works now..

Maybe this is the same instance for the other user with protocol mining errors :)

Thank you for the miner, keep up the good work!

**Comment by xmrig** [comment]
supportxmr doesn't support algorithm protocol negotiation, so you should set `""variant": -1,"`, current value `1` is cryptonight variant 1 also known as cryptonight v7.
Thank you.

**Comment by NaikDK** [comment]
Hi,
I am facing similar issue and variant value is -1 itself.
please find below my config.

{
    "algo": "cryptonight",
    "api": {
        "port": 0,
        "access-token": null,
        "id": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "background": false,
    "colors": true,
    "cuda-bfactor": 6,
    "cuda-bsleep": 25,
    "cuda-max-threads": 64,
    "donate-level": 1,
    "log-file": null,
    "pools": [
        {
            "url": "monerohash.com:7777",
            "user": "49E1tmUFVg4BUPSZCBpEqJgkUb59M6utrPETpSU9nhjYFjFepEqZgPNd8rPByR9PAzFUYbG5ArkjoW5iUDx9tWZ5H4snQir",
            "pass": "Darhk:deepknaik642@gmail.com",
            "rig-id": null,
            "nicehash": false,
            "keepalive": true,
            "variant": -1,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "threads": [
        {
            "index": 0,
            "threads": 4,
            "blocks": 40,
            "bfactor": 8,
            "bsleep": 25,
            "sync_mode": 3,
            "affine_to_cpu": false
        }
    ],
    "user-agent": null,
    "syslog": false,
    "watch": true
}

**Comment by SChernykh** [comment]
@NaikDK use https://xmrig.com/wizard to create new config, this one looks like from an ancient version.

**Comment by NaikDK** [comment]
I tried creating the config but it seems there are some issues in the pool's config.
@SChernykh can you please help me out here?

**Comment by NaikDK** [comment]
@xmrig Please help

**Comment by xmrig** [comment]
Current Monero algorithm is RandomX, this is not a cryptonight variant, you can't use XMRig-Nvidia for it. Seems you missed a lot and need to do research again.
Thank you.

**Comment by NaikDK** [comment]
@xmrig Can you please suggest any website fr the same?
