### ISSUE TITLE
Low hashrate on win32  xmrig

### ISSUE THREAD

**Issue by jiaxu2000** [xmrig/xmrig#846]
I found that the 2.8.x version of the win32 program is a lot slower.
I did an interesting test
Same computer , windows 7 64 bit , intel i7 2600k CPU 
delete config.json file

xmrig.exe -o stratum+tcp://pool.supportxmr.com:5555 -u ****************************** -p x 

xmrig-2.8.3-gcc-win32.zip  speed 10s/60s/15m 54.0 51.8 n/a H/s max 54.7 H/s
xmrig-2.8.3-gcc-win64.zip speed 10s/60s/15m 103.1 n/a n/a H/s max 107.5 H/s

I used the options av=1/2/3/4/5, hw-aes, asm=none/intel/auto, etc., but the speed of win32 is not optimized.

I understand that the new CN2 algo will slow down, but the 32-bit xmrig program on the G4560, G4400, i5 6500 and other CPUs is 100%-300% slower than before, while the 64-bit xmrig is only 30%-50% slower than before 

I don't expect win32 to be as fast as win64, but win32 is much slower than before.

**Comment by jiaxu2000** [comment]
I use av=3 parameter in win64, forcing soft AES, the speed is exactly the same as win32.

From this it can be concluded that win32 cannot use the Hardware AES function.

I hope fix in next versions

**Comment by xmrig** [comment]
1. Assembly only available for 64 bit (av 1 and av2), it not available for 32 bit builds at all.
2. Hardware AES supported by 32 bit builds, but not all registers available and some 64 bit instructions emulated, it always slower.

**Comment by sailei00** [comment]
I found that too,and is there any way to make it as fast as before?

**Comment by jiaxu2000** [comment]
> 1. Assembly only available for 64 bit (av 1 and av2), it not available for 32 bit builds at all.
> 2. Hardware AES supported by 32 bit builds, but not all registers available and some 64 bit instructions emulated, it always slower.

I read the source code of xmrig carefully.
in cmake/asm.cmake file

if (WITH_ASM AND NOT XMRIG_ARM AND CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(XMRIG_ASM_LIBRARY "xmrig-asm")
    ...........................................
    .............................................
else()
    set(XMRIG_ASM_SOURCES "")
    set(XMRIG_ASM_LIBRARY "")
    add_definitions(/DXMRIG_NO_ASM)
endif()

From the condition of CMAKE_SIZEOF_VOID_P EQUAL 8, it is easy to see that win32 does not get any optimization, win64 and win32 are not treated the same, I guess win32 will not use any Hard AES instructions.

**Comment by xmrig** [comment]
`ASM` not equal `AES`.

**Comment by 123456789vgkeine** [comment]
very bad that no x32

**Comment by postubsla** [comment]
for me it is also inconvenient that there is no x32, I ask to make x32

**Comment by hantokokume** [comment]
> `ASM` not equal `AES`.

в чем ваша выгода что нету x32 очень очень жаль что вы не хотите сделать x32

**Comment by yarigoyaosu** [comment]
> `ASM` not equal `AES`.

nonsense that no x32? why didn't you do MSVC 32 bit

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
Thank you!
