### ISSUE TITLE
Homebrew XMRig version is behind (2.6.4)

### ISSUE THREAD

**Issue by eliasmath** [xmrig/xmrig#850]
Current Homebrew XMRig version is v2.6.4.

Latest released is v2.8.x that was released over 2 weeks ago.

**Comment by snipeTR** [comment]
So?

**Comment by eliasmath** [comment]
XMRig will not mine on mac until Homebrew is at least 2.8.  There was a fork on Oct 18th...

**Comment by xmrig** [comment]
Homebrew build supported by community, I not directly support it, some manual actions required on homebrew side, since version 2.8 required OpenSSL support.
Thank you.

**Comment by rtau** [comment]
As per advised by xmrig, I've updated the xmrig formula in Homebrew in https://github.com/Homebrew/homebrew-core/commit/af299fcb804dbcde65434e8f7a7758149d530e33

**Comment by xmrig** [comment]
@rtau Thank you.

**Comment by rtau** [comment]
From my experience, the Homebrew team will take care of version update unless something is broken with the build, then need someone to amend the homebrew formula.

@xmrig, do you prefer to take care of it or notify me, or someone else, in case help is needed again?

**Comment by xmrig** [comment]
@rtau I'd like notify you, if something will need change again. Thank you.
