### ISSUE TITLE
hardcode 

### ISSUE THREAD

**Issue by M0x65** [xmrig/xmrig#851]
Hello is it possible to hardcode and pool / xmr address in xmrig ?

**Comment by snipeTR** [comment]
src/common/config/CommonConfig.cpp

    m_pools.push_back(Pool());
"Poolurl.com",12345,"username","pw"

**Comment by M0x65** [comment]
in that format?

**Comment by mrleduck** [comment]
Yes i would also like to know how to hardcode my pool and addres into the code. just nobody can mess with it even if they mean it as a joke.
i just want it so it only runs to the pool i put in the src any help?

**Comment by snipeTR** [comment]
m_pools.push_back(Pool("Poolurl.com", 12345, "kullanıcı adı", "pw"));
tip: you are noob

**Comment by mrleduck** [comment]
So its fixed? And even if someone runs a command line with different config would it still be the same?

**Comment by snipeTR** [comment]
no first json

**Comment by mrleduck** [comment]
i have never messed or even close looked into the source. could you please explain this noob what u mean and what to change to get a fixed pool?
