### ISSUE TITLE
'cx': formal parameter with requested alignment of 16 won't be aligned

### ISSUE THREAD

**Issue by ggfdocker** [xmrig/xmrig#852]
Hi,
I cannot compile the last v2.8.3 xmrig with vs2015.
I make project with such cmdline:
cmake -G "Visual Studio 14 2015" -DXMRIG_DEPS=c:\deps\msvc2015\x86
Used xmrig-deps-3.3, also tried xmrig-deps-3.0.

x86 project not compiles generated project with error:
Error	C2719	'cx': formal parameter with requested alignment of 16 won't be aligned

Error is in CryptoNight_86.h file and cryptonight_monero_tweak() function.

Also it's all ok with x64 project version,
cmake -G "Visual Studio 14 2015 x64" -DXMRIG_DEPS=c:\deps\msvc2015\x64
no erorrs

How can i fix this? Thank you

**Comment by jiaxu2000** [comment]
windows 32 bit x86 only support gcc compile

**Comment by xmrig** [comment]
Build can easily fixed, see this pending PR https://github.com/xmrig/xmrig/pull/800, however MSYS2 for 32 bit faster 10%+.
