### ISSUE TITLE
License issue distributing XMRig binary linked with OpenSSL

### ISSUE THREAD

**Issue by Low-power** [xmrig/xmrig#855]
XMRig is under `GPL-3+`, which is incompatible with the OpenSSL license; without an OpenSSL linking exception from the copyright holder, then it seems that I have no right to distribute the XMRig binary if that is linked with OpenSSL libraries.

**Comment by xmrig** [comment]
Seems OpenSSL licensing is complicated thing, so what exactly I should do?
Thank you.

**Comment by Low-power** [comment]
According to https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs the copyright holder can add a 'linking exception' via 'Additional Terms' in section 7 of GPL-3; thus allowing others to distribute binaries linked with OpenSSL.
However from 'README.md' I learned this program may be fork of cpuminer-multi (license GPL-2); if so and the original author isn't you, all authors must agree as well to add such an additional term.

**Comment by xmrig** [comment]
cpuminer-multi fork available in [classic](https://github.com/xmrig/xmrig/commits/classic) branch, since v1 miner was rewritten on C++/libuv instead of plain C.

**Comment by Low-power** [comment]
So assume you are the only copyright holder of program, things now easier.

> If you wrote the whole program yourself, then assuming your employer or school does not claim the copyright, you are the copyright holder—so you can authorize the exception.

You can put the following texts to the license header of all sources files that you license under GPL-3 and/or the program's license information output:

> Additional permission under GNU GPL version 3 section 7

> If you modify this Program, or any covered work, by linking or combining it with OpenSSL, containing parts covered by the terms of OpenSSL license and SSLeay license, the licensors of this Program grant you additional permission to convey the resulting work. Corresponding Source for a non-source form of such a combination shall include the source code for the parts of OpenSSL used as well as that of the covered work.

Anyways it is your decision on how to grant this additional permission to others. See https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs for more information.

**Comment by Low-power** [comment]
But still, make sure everyone in the copyright lines in all GPL licensed source files agree, before add such text.
