### ISSUE TITLE
Proper NUMA nodes support

### ISSUE THREAD

**Issue by xmrig** [xmrig/xmrig#86]
Need proper NUMA nodes support, for example add ability to pin threads to specific node.

- [x] Use **hwloc** instead of **libcpuid**.
- [x] Add optional per thread configuration in config file. #563

**Comment by 2010phenix** [comment]
-- cut --
Need proper NUMA nodes support, for example add ability to pin threads to specific node.
 Use hwloc instead of libcpuid.
-- cut --

am too have this problem.....
can i build hwloc myself with xmrig or need redone much things for this ?

**Comment by xmrig** [comment]
Yep it need redone much things.

**Comment by pioruns** [comment]
Any progress on this? I am mining with Dual CPU Xeon E5-2620, 320H/s, how to improve that?

**Comment by kimats** [comment]
hope we can deliver this soon...

**Comment by xmrig** [comment]
Implemented, future details #1077.
