### ISSUE TITLE
close issue

### ISSUE THREAD

**Issue by Unlash** [xmrig/xmrig#861]

**Comment by snipeTR** [comment]
#266 issue

**Comment by Unlash** [comment]
> 
> 
> #266 issue

I am using MSYS2

**Comment by Unlash** [comment]
> 
> 
> #266 issue

thx

**Comment by Unlash** [comment]
> 
> 
> #266 issue

Execute exe prompt
Lost libmicrohttod-12.dll libwinpthread-1.dll libstdc++-6.dll
 cmake .. -G "Unix Makefiles" -DXMRIG_DEPS=C:\msys64\home\Aloof\xmrig-deps-3.3\gcc\x64
