### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Hacker-One** [xmrig/xmrig#862]
### cmake
![image](https://user-images.githubusercontent.com/14013299/47806387-9f199980-dd74-11e8-8fa5-45066beeb1ef.png)

### Make Error
![image](https://user-images.githubusercontent.com/14013299/47806457-cbcdb100-dd74-11e8-9121-1adb7f63a1cc.png)

**Comment by snipeTR** [comment]
![image](https://user-images.githubusercontent.com/31975916/47822535-8958a400-dd75-11e8-94f8-a77e794507d9.png)
![image](https://user-images.githubusercontent.com/31975916/47822687-113eae00-dd76-11e8-9c56-04704453e862.png)

**Comment by xmrig** [comment]
Follow instructions https://github.com/xmrig/xmrig/wiki/Windows-Build use MSYS2.
Thank you.
