### ISSUE TITLE
hardcoded Add logFile error

### ISSUE THREAD

**Issue by luxig** [xmrig/xmrig#864]
hardcoded Add logFile error
Ex: m_pools.push_back(Pool("Poolurl.com", 12345, "username", "pw"));    success

Ex: m_pools.push_back(Pool("Poolurl.com", 12345, "username", "pw", "-l /root/xmrig/build/log"));    error

Add logFile What is the specific format?

**Comment by xmrig** [comment]
Oh, you should learn C++ a little. Add new line after `m_pools.push_back`: `m_logFile = "/root/xmrig/build/log";`
