### ISSUE TITLE
Api https support

### ISSUE THREAD

**Issue by mk148a** [xmrig/xmrig#867]
Hi, xmrig is have https secure api support?
Can you make it for data security?

**Comment by lisergey** [comment]
@mk148mk you can use nginx in front of xmrig http.
with Nginx it is superbous https.

There is no need to overload wonderful xmrig with that is already well done by others.

**Comment by xmrig** [comment]
libmicrohttpd required GnuTLS, but miner itself use OpenSSL, so for https in API need use 2 different SSL libraries, so right now answer is no.

**Comment by xmrig** [comment]
Duplicate #317
