### ISSUE TITLE
E5 2680V2 mining error

### ISSUE THREAD

**Issue by netmebtc** [xmrig/xmrig#868]
E52680V2 win7 xmrig 2.8.3
xmrig-proxy 2.8.1
Mining algo cn_v8

 when mining , often error, then  stop xmrig , start xmrig again, still cannot mining.  only restart the E52680V2 ,then it is working, what is the problem ?

![image](https://user-images.githubusercontent.com/32667839/47959363-ffcaff80-e01c-11e8-960c-0e86452c7a2c.png)

**Comment by snipeTR** [comment]
192.168.0.252 proxy?
İnfo the proxy

**Comment by netmebtc** [comment]
It is xmrig-proxy2.8.1

**Comment by netmebtc** [comment]
> Network issue, but no other issues, connection recovered, mining too.
> Thank you.

No,no.
When connection recovered , the rig cannot mining, restart xmrig, cannot mining,  only restart rig power,then can mining

**Comment by netmebtc** [comment]
> 192.168.0.252 proxy?
> İnfo the proxy

It  is xmrig-proxy 2.8.1

**Comment by netmebtc** [comment]
Hi, this is not a question,It is realy a issue

**Comment by xmrig** [comment]
Missed your second screenshot, looks really strange, please provide all possible details, especially about network.

It's plain wired local network or something more complicated eg VPN. Also I confusing with 3 different IP address on your screenshot `192.168.0.252`, `192.168.1.250`, `192.168.88.250`.

Is there any firewall (local or network) or AV blocking traffic?

**Comment by netmebtc** [comment]
This problem occurs in three farms, all of which are the same issue. After the problem occurs, CPU rigs must restart the power supply before they can continue to mine.   There is no firewall.
If rigs connect to the pool directly, the problem  also happen.

**Comment by xmrig** [comment]
Okay let's start investigate it from direct connection to pool.
You from China (I guess it from your screenshots)?, so your pool located in Singapore (if it one of major pools) in this case there is already big firewall on the way.

Try use SSL/TLS to hide your traffic:
1. `"tls": true` in config.
2. SSL port on your pool.

One thing strange, if it miner issue, just simple miner restart should help.
