### ISSUE TITLE
How to make the compiled executable file smaller?

### ISSUE THREAD

**Issue by ttsite** [xmrig/xmrig#869]
2.8x version of the compiled executable file is much larger than before, can you make the compiled executable file smaller?

**Comment by xmrig** [comment]
Use builds without SSL/TLS support, `-notls.exe`.

**Comment by ttsite** [comment]
Will there be any effect on mining if there is no SSL / TLS support? Thank you!

**Comment by xmrig** [comment]
Answered multiple times, without SSL/TLS you can't connect to SSL/TLS ports on pool, all versions before 2.8 not support it.
Thank you.

**Comment by ttsite** [comment]
thanks!!
