### ISSUE TITLE
speed 10s/60s/15m n/a n/a n/a H/s max n/a H/s

### ISSUE THREAD

**Issue by zaferweb** [xmrig/xmrig#872]
I have problem The following results are available on my 2 PCs. I've changed the settings in the config.json file many times, but the result is still unchanged. How can I solve this?

CPU : Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (1) x64 AES
[2018-xx-xx xx:xx:xx] speed 10s/60s/15m n/a n/a n/a H/s max n/a H/s

CPU : Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (2) x64 AES
[2018-xx-xx xx:xx:xx] speed 10s/60s/15m n/a n/a n/a H/s max n/a H/s

**Comment by 2010phenix** [comment]
and where is problem?
not receive from pool shares and no H/s stat )

**Comment by zaferweb** [comment]
2010phenix Thank you for reply.

I have 2 computers which are same CPU Xeon. Although the options in the config.json file of the 2 computers are the same, there are two different results. Computer-1 is connected to the pool and working properly. Computer-2 cannot connect to the pool. The screen shot is below. Why is this problem caused?

![xeon-1](https://user-images.githubusercontent.com/25661901/48332859-717efb00-e666-11e8-86b8-a76198380499.jpg)

**Comment by zaferweb** [comment]
Hi snipeTR,
If you're asking for the firewall I'm using. I am using Cyberoam as firewall. There is open all web sites and services  on the firewall for Computer-1 like Computer-2 too. So there is no any blocking in the firewall.

**Comment by snipeTR** [comment]
setup a proxy on a local machine. its connected to the pool. I'm sure the problem is related to the security system.

**Comment by zaferweb** [comment]
I found the solution. Symantec is blocking the virus program. When i change some setting in Symantec it is working.
