### ISSUE TITLE
huge size of xmrig binary after last fork

### ISSUE THREAD

**Issue by vivin321** [xmrig/xmrig#873]
need help 
after compiling the xmrig 32bit and xmrig 64bit 
I got huge sizes 
how can I minimize the size 
some friend told me that's because openssl 
I do not know how to delete openssl or is that may damage the miner 
need help in details please

**Comment by 2010phenix** [comment]
first of all use SEARCH - is very good things!
second, no any damage
third, you can use miner without tls for not so big size

**Comment by vivin321** [comment]
2010phenix your comment is useless 
I searched and found nothing
I'm newbie and don not know how to remove openssl

**Comment by 2010phenix** [comment]
@vivin321 your question not issue, only lazy cry about HOW make money and you even not read what write to you. Answer one or two time given in tracker - USE search.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/wiki/Windows-Build#additional-cmake-options
