### ISSUE TITLE
Adding new algo for $XWP - swap

### ISSUE THREAD

**Issue by reeyon** [xmrig/xmrig#878]
working product - https://github.com/Bendr0id/xmrigCC/commit/128550a66289a18156dfa29e918c4f903f06e404

~~ANN: https://bitcointalk.org/index.php?topic=5071178~~
New ANN: https://bitcointalk.org/index.php?topic=5083455.0
Thanks.

**Comment by 2010phenix** [comment]
:) you are funny....

NETWORK HASH RATE
3.32 MH/sec

**Comment by reeyon** [comment]
https://miningpoolstats.stream/freehaven

5MH today. 
Hoping xmrig can add this algo in the next release. Thanks.

**Comment by DeadManWalkingTO** [comment]
Maybe enhancement.

**Comment by reeyon** [comment]
Swap had been forked to cuckaroo pow, I will close this issue now.
Thanks.
