### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by boodal** [xmrig/xmrig#879]
i've been searching for this problem for quiet while seems no one has solved yet 

i've tried every possible driver they have back to 2017 driver and its the same issue  

see attached picture 

[](url)https://ibb.co/eWEhpq

**Comment by trasherdk** [comment]
Explain your problem.

**Comment by boodal** [comment]
thread #0 compute error 
thread #1 compute error

that's why i include picture for more clear understanding

**Comment by xmrig** [comment]
Working drivers well known https://github.com/xmrig/xmrig-amd/blob/master/doc/DRIVERS.md
Thank you.

**Comment by DeadManWalkingTO** [comment]
Does the issue still exist?
Feedback please.
Thank you!

**Comment by boodal** [comment]
yes but you can move/delete the post thanks

**Comment by DeadManWalkingTO** [comment]
If the issue still exist please report it to [xmrig-amd/issues](https://github.com/xmrig/xmrig-amd/issues/new).
I think this issue can be closed.
Thank you!
