### ISSUE TITLE
CPU Affinity Help

### ISSUE THREAD

**Issue by Prefinity** [xmrig/xmrig#88]
Not very sure how to get the binary codes for entering the proper affinity into config, will appreciate some assistance! E5 2686 V4 64 cores but it seems like only 70% of cpu is used even when i entered 100 in config, and only 45 cores are displayed in the window when i start the program.
![image](https://user-images.githubusercontent.com/7398235/30009143-9abeef20-9158-11e7-8e24-0a18e8d3f023.png)

**Comment by xmrig** [comment]
Each thread required 2 MB of CPU cache for optimal performance. If you try use more threads it will decrease hashrate. About 22-23 threads per single CPU should be better config.
Sorry for late reply.

**Comment by Prefinity** [comment]
thanks for the response. so how should i calculate the bitmask for this? or just leave null on affinity and let the program automatically set it up?

**Comment by xmrig** [comment]
Set proper affinity maybe not work, because of 2 NUMA nodes see #86
If affinity option not set it means leave OS choice where place threads.

**Comment by xmrig** [comment]
#86
