### ISSUE TITLE
Avast antivirus block xmrig github page

### ISSUE THREAD

**Issue by DeadManWalkingTO** [xmrig/xmrig#883]
Avast antivirus block xmrig github page (https://github.com/xmrig/xmrig)!

**Comment by ordtrogen** [comment]
Interesting. I use Avast too, but nothing is blocked when I follow that link.  (using the Avast Secure Browser)

I can't reproduce it with any browser on my Windows 10 machine (Brave, Opera, Google Chrome, Mozilla Firefox)

**Comment by DeadManWalkingTO** [comment]
**OS**: Win7 64bit
**Browser**: Firefox Quantum 63.0.3 64bit
**Antivirus**: 18.8.2356 (build 18.8.4484.408)
**Antivirus DB**: 181130-4
**Url**: https://github.com/xmrig/xmrig
**Result**: Win32:Cryptominer-L [Trj]
