### ISSUE TITLE
Question: XMRig GCC vs MSVC

### ISSUE THREAD

**Issue by SBSeed** [xmrig/xmrig#885]
so what is the difference between the GCC and MSVC versions of the MXRig Win-64?

edit:
is there any difference, or is just one takes up slightly less HDD space than the other...
differences in blockchain verification?
differences in processing/verification speeds?
is one meant for specific hardware?
anything?

**Comment by 2010phenix** [comment]
@SBSeed good question for mew version xmrig... 
download, make some test and tell to us ;-)

**Comment by SBSeed** [comment]
i have both of the XMRig GUIs, once the blockchain data is fully downloaded i think i will start with one core and work up to 4 cores on my main computer....

if i can i will test both out on my server, so much to do so little time in a day to do them all....
i will try to be as detailed as possible, if i can (not having used any of this stuff till a few days ago)
track:
- speeds (both XMRig's and Hardware, 4 stats)
- ease of setup on gaming PC vs Server hardware
- time to download blockchain data on server using both XMRig's and the Monero Wallet (monderod.exe/deamon)
- transactions speeds (process of sending monero/XMR to wallet)
- validating mined monero/XMR in the wallet

this could take a week to a month to setup and test everything, need to get some more hardware for the server... i was hoping one of the people working on the XMRig/Monero wallet project might know and give some feedback.

**Comment by SBSeed** [comment]
this is now on hold, till i can get monero stuff figured out...
