### ISSUE TITLE
Compiling For ARMv7

### ISSUE THREAD

**Issue by DarrenRainey** [xmrig/xmrig#886]
Has anyone got a guide on how to compile for ARMv7 looking through the issues I've been other people seem to have been able to compile it for the raspberry pi but I'm having issues as I get errors relating to -maes which is ARMv8 specific. Thanks

EDIT: I've noticed people talking about an ARM branch but I can't seem to find it.

**Comment by 0xman** [comment]
I have a fully static miner for armv7 if you want it just lmk

**Comment by DarrenRainey** [comment]
Yeah if you could share that would be great although I would prefer to compile it myself for future reference incase I need to update the source code.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/issues/744#issuecomment-460080494

**Comment by Studo123** [comment]
> I have a fully static miner for armv7 if you want it just lmk

please tell me you're still offering this!!! been looking forever!
