### ISSUE TITLE
A FULLY VIRUS 

### ISSUE THREAD

**Issue by Atom-Hydra-7** [xmrig/xmrig#896]
# VIRUS!
## IT DESTROYED MY ALL APPS

**Comment by snipeTR** [comment]
Loool.
man, what the fuck are you talking about? This is an open source application. no harm. You infected your computer. The virus is also using the codes of this program. this program here is completely harmless with the state.

**Comment by snipeTR** [comment]
U r noob

**Comment by snipeTR** [comment]
#85

**Comment by Atom-Hydra-7** [comment]
Hmm are you saying the truth
 or Again you updated your VIRUS definitions
________________________________

**Comment by Atom-Hydra-7** [comment]
OK give me .svg of your logo.😊😊😊😊😊😊😎
And give me some good css loaders😂😊😊😊😊😊😊😊😊
________________________________

**Comment by Atom-Hydra-7** [comment]
What is "noob"
________________________________

**Comment by snipeTR** [comment]
Can u use google?
