### ISSUE TITLE
"safe": false, ==> CRASH

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig#897]
hello my cpu x9650
windows 7 use.
my build xmrig 2.8.3 and 2.8.1 x86
my config file `"safe": true,` thats all **OK**
but `"safe": false,` CRASH error level return code=`-1073741795`

**Comment by DeadManWalkingTO** [comment]
Try [latest XMRig version](https://github.com/xmrig/xmrig/releases/latest).
Does the issue still exist?
Feedback please.
Thank you!
