### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by boymafia** [xmrig/xmrig#90]
Hi,

I'd like to know how to configure more mine URL in config.json file.

Thanks!

**Comment by xmrig** [comment]
Like that:
```
    "pools": [
        {
            "url": "pool.minemonero.pro:5555",
            "user": "",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        },
       {
            "url": "failover.pool",
            "user": "",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        }
    ]
```
Syntax standard JSON array, first element will be primary pool, any others are backup pools.
Thank you.

**Comment by minerteam** [comment]
Adding another pool in config.json gives me this error: [pool.xxxxxx.com:5555] "No login / password especified", code -1 
Never connect to the primary pool, connect to the backup pool.

**Comment by minerteam** [comment]
It was my fault, I solved it

**Comment by davidenoto** [comment]
hi!
I want change URL pool with MoneroOcean, but "config.json:1260: Invalid escape character in string.
No pool URL supplied. Exiting."
the URL is gulf.moneroocean.stream:80
Help me

**Comment by gtimeg77** [comment]
where is this file located

**Comment by xmrig** [comment]
Please show your config.
