### ISSUE TITLE
[Feature Request]  Add support for 'Cryptonight_Turtle' for upcoming TRTL fork

### ISSUE THREAD

**Issue by lost-bro** [xmrig/xmrig#904]
Sorry for the bother, just wanted to verify if we can expect an updated release of XMRIG compatible  with the upcoming TRTL coin fork in 21 days.
Thanks in advance

**Comment by lost-bro** [comment]
Sorry for the bother, just wanted to verify if we can expect an updated release of XMRIG compatible  with the upcoming TRTL coin fork in 21 days.
Thanks in advance

**Comment by xmrig** [comment]
Please provide information/announce about these changes.
Thank you.

**Comment by lost-bro** [comment]
https://blog.turtlecoin.lol/archives/proof-of-work-algorithm-change/

**Comment by lost-bro** [comment]
Just wanted to comment the STAK has already released his "crytponight_turtle" variant, but I would prefer to use XMRIG for auto-algo switching purposes.
Thanks

**Comment by fexra** [comment]
https://github.com/turtlecoin/trtlrig

**Comment by brandonlehmann** [comment]
https://github.com/turtlecoin/turtlecoin/issues/674

Release candidate for the fork is pending. Will complete and release any day now.

**Comment by xmrig** [comment]
@brandonlehmann As I understand new algorithm is cn/2 with different scratchpad size and iterations? or miner need support for all 12 algorithms, this part is unclear in blog. In any case test pool required and pull request is preferred even if it partially done.

@fexra this fork not contain any related changes.
@lost-bro `crytponight_turtle` is just alias to `crytponight-lite` variant `1`, currently also no support for upcoming fork.

**Comment by lost-bro** [comment]
![cn-trtl](https://user-images.githubusercontent.com/37913805/51076075-8b828d00-1659-11e9-8a25-eefbcb5324ac.png)
"Cryptonight_Turtle" is the algo name used in the *TRTL-forked* version of XMRIG.  Please see Screen shot from *TRTL-forked* version of XMRIG attached.

**Comment by brandonlehmann** [comment]
@xmrig  For reference, xmrigCC has support for the algo via https://github.com/Bendr0id/xmrigCC/commit/4c995ea44357aa5bfec0d38dda8356dbb6fe0c0e

I've also submitted a PR on xmr-stak via https://github.com/fireice-uk/xmr-stak/pull/2178 including test pool data

I'll see if we're able to apply the update to xmrig and open a PR; however, if we can't, your assistance is appreciated :)

**Comment by xmrig** [comment]
I saw, due date for this issue is 23rd I will be unavailable after this date for about a week, some things eg ASM patching already prepared.

Smooth algorithm changing while fork will not possible, because memory requirements changed, also it means block version after fork doesn't mater for miner.
Thank you.

**Comment by SChernykh** [comment]
Interesting. Smaller memory access time may mean different asm code is optimal, I can check it this week.

**Comment by xmrig** [comment]
@YetAnotherRussian  Please provide details, CPU, config, hashrate, etc.
@Bendr0id

**Comment by SChernykh** [comment]
I couldn't get better hashrate than with 2 single threads per core (asm=ryzen) no matter what I tried. asm=ryzen is 10% faster than asm=off on Ryzen 5 2600.

**Comment by YetAnotherRussian** [comment]
Ryzen7 2700X stock, no overclock (mem 2666MHz dual-channel 2x16Gb 2rank plates)

Best performance with:
"algo": "cryptonight-ultralite",
"aesni": 0,  
"threads": 32, 
"multihash-factor": 1,
"multihash-thread-mask" : null, 
"pow-variant" : "turtle",  
"asm-optimization" : "off", 
"background": false,
"cpu-affinity": null,
"cpu-priority": null,
"max-cpu-usage": 100, 

Total: 14250 h/s

If "asm-optimization" is set to "auto" or "ryzen" => 13800 h/s

**Comment by xmrig** [comment]
It might be xmrig-CC only related issue, I get exactly same hashrate (about 14250) on Ryzen7 2700X with same hardware config, only difference is Ubuntu 18.04 and asm `bulldozer`. Asm `ryzen` is slowest (about 13600).

Pure C++ version always slower, only about 10000 H/s.

**Comment by Bendr0id** [comment]
Here are my results with XMRigCC 1.8.10. 
Ubuntu is for me on Ryzen always slower than MVC. For Intel i can't see a difference.

Tests are performed under Windows 10. 

Configuration | Ryzen 1600 3.8GHz | Ryzen 2600 3.85GHz | Ryzen 2700 4.1GHz
-- | -- | -- | --
threads:12 , ASM: Ryzen , hf:1 | 9,560 h/s | 10,065 h/s | 11,003 h/s
threads:16 , ASM: Ryzen , hf:1 | 9,542 h/s | 10,022 h/s | 14,041 h/s
threads:24 , ASM: Ryzen , hf:1 | 9,521 h/s | 10,035 h/s | 14,010 h/s
threads:32 , ASM: Ryzen , hf:1 | 9,532 h/s | 10,060 h/s | 14,009 h/s
threads:12 , ASM: off , hf:1 | 8,861 h/s | 9420 h/s | 10,068 h/s

Hashfactor 2, was always slower.

**Comment by xmrig** [comment]
v2.10.0 released
https://github.com/xmrig/xmrig/releases/tag/v2.10.0
https://github.com/xmrig/xmrig-amd/releases/tag/v2.10.0
https://github.com/xmrig/xmrig-nvidia/releases/tag/v2.10.0
https://github.com/xmrig/xmrig-proxy/releases/tag/v2.10.0

New algorithm name is `cn-pico/trtl`, alternative names `cryptonight-turtle`, `cn-trtl`, `cryptonight-ultralite`, `cn-ultralite`, `cryptonight_turtle` also supported.

**Comment by brandonlehmann** [comment]
Thanks! @xmrig

**Comment by lost-bro** [comment]
@xmrig , Much appreciated

**Comment by snipeTR** [comment]
Please paste json to code

**Comment by asylum119** [comment]
After having no luck with the aliases on command I tried the config.json already posted ^. Again algo was not recognised

**Comment by asylum119** [comment]
Might have been a compile issue, I recompiled and all is good.

**Comment by browolf** [comment]
I had  "no valid configuration found" until I realized variant needs to be "-1"
