### ISSUE TITLE
Built using MSYS2, where is the exe file?

### ISSUE THREAD

**Issue by lolcocks123** [xmrig/xmrig#91]
I built using MSYS2.

It compiled successfully, but where is the final compiled exe file?

I see a "a.exe" but it doesn't seem to be the miner?
Sorry, I am new to building.

**Comment by xmrig** [comment]
You compiled hello word? cmake create anything to run make, including correct file name.

**Comment by abdoubied** [comment]
disable the antivirus

**Comment by abdoubied** [comment]
the antivirus deleat the exe
