### ISSUE TITLE
Cryptonight SuperFast

### ISSUE THREAD

**Issue by cryptominesetting** [xmrig/xmrig#916]
any plan for support cryptonight superfast?

**Comment by xmrig** [comment]
What is this? any information please. Too many ultra/super/fast tweaks out here.
Thank you.

**Comment by cryptominesetting** [comment]
sample coin :
https://fury-coin.com/
https://github.com/FuryCoin/Fury

miner :
https://github.com/fireice-uk/xmr-stak/blob/master/xmrstak/backend/cryptonight.hpp
algo num 12

**Comment by reeyon** [comment]
#878

**Comment by cryptominesetting** [comment]
please add
my mobile miners are waiting for this algo :D

tnx
