### ISSUE TITLE
Is there any way to write my mine address to the source code?

### ISSUE THREAD

**Issue by Likelym** [xmrig/xmrig#92]
Is there any way to write my mine address in the source code? Build, which does not require additional instructions, open xmrig.exe can start working?

**Comment by lolcocks123** [comment]
Hmmmm, interesting.
I too am interested in this.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/blob/master/src/Options.cpp#L204 can override default (empty) pool url.

**Comment by Likelym** [comment]
I am sorry, I am a code novice, I want my wallet address and mine pool address integrated into the binary file (xmrig.exe)! Can you give me a case? Thank you!

**Comment by Valke88** [comment]
I also would like to know how to integrate my pool and wallet address into the xmrig.exe

https://github.com/xmrig/xmrig/blob/master/src/Options.cpp#L204 can override default (empty) pool url.

It is not clear for me where to put the pool and and address

**Comment by Valke88** [comment]
I also would like to know how to integrate my pool and wallet address into xmrig.exe

"https://github.com/xmrig/xmrig/blob/master/src/Options.cpp#L204 can override default (empty) pool url."

For me it is not clear where to put my pool and wallet address in options.ccp

**Comment by lolcocks123** [comment]
Is it also possible to override the username (wallet address)?

**Comment by Valke88** [comment]
@lolcocks123 how do you integrate wallet and pool url? Can you post it here?

Thanks

**Comment by xmrig** [comment]
The line need changed to something like that:
```cpp
m_pools.push_back(new Url("pool.example.com", 3333, "WALLET", "PASSWORD"));
```

@lolcocks123 yep just add more lines, it supports multiple failover pools.

**Comment by Valke88** [comment]
Thx, already tried something like that :)

**Comment by lolcocks123** [comment]
Thank you again @xmrig.

I will surely give you a nice donation once I have enough. :)

**Comment by hi0x0** [comment]
chinaes:
请问：是把m_pools.push_back(new Url("pool.example.com", 3333, "WALLET", "PASSWORD")); 替换到 https://github.com/xmrig/xmrig/blob/master/src/Options.cpp#L204 吗？

就像是这样：

    return algo_names[m_algo];
}

m_pools.push_back(new Url("pool.example.com", 3333, "WALLET", "PASSWORD"));
Options::Options(int argc, char **argv) :
    m_background(false),
    m_colors(true),
    m_doubleHash(false),
    m_hugePages(true),
    m_ready(false),
    m_safe(false),
    m_syslog(false),
    m_apiToken(nullptr),
    m_apiWorkerId(nullptr),
    m_logFile(nullptr),

但是无法编译，请问具体应该如何修改？
