### ISSUE TITLE
Cryptonite-turtle threads not working

### ISSUE THREAD

**Issue by Cexitime** [xmrig/xmrig#924]
Hi, 

Using -t --threads=1 on cryptonite-turtle doesnt work, when I changed algo back to -lite just to check, it started working, is the -t option broken for turtle?

looks like -max-cpu-usage=25 works

**Comment by asylum119** [comment]
You did not set any threads for -t and are also using --threads=1 creating a conflict

Use -t 1 or --threads=1 but not both together in the same command

--algo=cn-pico/trtl works fine in latest release

Also I could be wrong but from memory max-cpu-usage is now depreciated

**Comment by DeadManWalkingTO** [comment]
> 
> 
> You did not set any threads for -t and are also using --threads=1 creating a conflict
> 
> Use -t 1 or --threads=1 but not both together in the same command
> 
> --algo=cn-pico/trtl works fine in latest release
> 
> Also I could be wrong but from memory max-cpu-usage is now depreciated

Does the issue still exist?
Feedback please.
Thank you!

**Comment by asylum119** [comment]
OP was using commands incorrectly, I would say after this amount of time that this issue can be squashed

**Comment by asylum119** [comment]
> Does the issue still exist?
> Feedback please.
> Thank you!

OP was using commands incorrectly, I would say after this amount of time that this issue can be squashed
