### ISSUE TITLE
config.json <29> keeps sending missing colonafter a name object?

### ISSUE THREAD

**Issue by johnsix12** [xmrig/xmrig#930]
what am i doing wrong?

**Comment by johnsix12** [comment]
"algo": { "cryptonight"},
    "api": {,
        "port": 0,
        "access-token": null,
        "id": null,
        "worker-id":,
        "ipv6": false,
        "restricted": true,
    }
    "asm": true,
    "autosave": true,
    "av": 0,
    "background": false,
    "colors": true,
    "cpu-affinity": null,
    "cpu-priority": null,
    "donate-level": 5,
    "huge-pages": true,
    "hw-aes": null,
    "log-file": null,
    "max-cpu-usage": 75,
    "pools": [
        {
            "url": { "xmr.2miners.com:2222" },
            "user": { "44C4NkPKi8Jiu8oSZ6kV8VGhEu1T6KWVVdn1mHa15B73DpAes9XGzYZRknwy3u3sszEBXwZtUa6wgP8g3GSvyVoxGaQwHBf" },
            "pass": "x",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "variant": -1,
            "tls": false,
            "tls-fingerprint": null,
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "safe": false,
    "threads": [
        {
            "low_power_mode": 1,
            "affine_to_cpu": false,
            "asm": true,
        }
    ],
    "user-agent": null,
    "watch": false,
}

**Comment by 2010phenix** [comment]
in first line you missing - {

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
Thank you!
