### ISSUE TITLE
Does v2.12.0 support the new algorithm of March 9?

### ISSUE THREAD

**Issue by ttsite** [xmrig/xmrig#937]
Will v2.12.0 support the new algorithm of March 9, and if so, will the replacement be automatically replaced by the new algorithm? The software does not need to be restarted (CPU mining software). Thank you!!?

**Comment by xmrig** [comment]
v2.13 will support March hardfork.

Same as before miner will switch algorithm on fly, both for CPU/GPU in 2 cases:

* `variant` option set to `-1` (automatic)
* Pool supports algorithm negotiation, in this case `variant` option doesn't mater.

**Comment by ttsite** [comment]
> v2.13
When will this edition be issued, thank you!!

**Comment by xmrig** [comment]
Exact date not decided yet, but in dev branch support for new algorithm already added.
Thank you.

**Comment by minhng99** [comment]
any test pool for the new algorithm?

**Comment by xmrig** [comment]
Traditional http://killallasics.moneroworld.com/ already updated.
Thank you.

**Comment by minhng99** [comment]
it looks like that pool is broken, the " Mining Pool Address:" is empty, do you know what it is?

**Comment by xmrig** [comment]
v2.13.0 released.
