### ISSUE TITLE
Direct reading of mining information in v2.13.0

### ISSUE THREAD

**Issue by ttsite** [xmrig/xmrig#941]
How do v2.13.0 want to write its own mine information directly in the source code? Where should it be written? Are there any specific samples? Thank you!

**Comment by xmrig** [comment]
Please better explain what exactly you need.
Thank you.

**Comment by ttsite** [comment]
I want to write my mine wallet and other information directly into the source code where to write in the new version, the previous version I remember written in commonconfig. CPP format as follows
M_pools. push_back (new Url ("POOL ADDRESS", "PORT", "WALLET", "PASSWORD");
Now the new v2.13.0 does not know how to write, thank you!!!

**Comment by ttsite** [comment]
> Please better explain what exactly you need.
> Thank you.

I want to write my mine wallet and other information directly into the source code where to write in the new version, the previous version I remember written in commonconfig. CPP format as follows
M_pools. push_back (new Url ("POOL ADDRESS", "PORT", "WALLET", "PASSWORD");
Now the new v2.13.0 does not know how to write, thank you!!!

**Comment by xmrig** [comment]
I forgot about that use case, now code should looks like:
`m_data.push_back(Pool("POOL ADDRESS", 3333, "WALLET", "PASSWORD"));` m_pools replaced to m_data and located into Pools.cpp https://github.com/xmrig/xmrig/blob/master/src/base/net/Pools.cpp#L36

**Comment by ttsite** [comment]
Thanks very much!!

**Comment by MasterDeflate** [comment]
I tried this but fail i replace m_data.push_back as you said to Pools.cpp but when i run the xmrig after compile finish it ask me for config.json

**Comment by sailei00** [comment]
> I tried this but fail i replace m_data.push_back as you said to Pools.cpp but when i run the xmrig after compile finish it ask me for config.json

I have the same problem. Have you solved it?
