### ISSUE TITLE
Startup message not consitant on xmrig

### ISSUE THREAD

**Issue by lhirlimann** [xmrig/xmrig#943]
* CPU          ARMv8 (1) x64 -AES -AVX2

ARMV8 should be enough :)

**Comment by xmrig** [comment]
Actually you are right `x64` and `AVX2` can be removed, but AES is still useful information, in your case CPU lacks hardware AES support.
Thank you.

**Comment by lhirlimann** [comment]
can you point me where that part of the code lies so I can do patch/PR ?
