### ISSUE TITLE
v2.13.0 What is the default CPU occupation?

### ISSUE THREAD

**Issue by ttsite** [xmrig/xmrig#945]
How much CPU does v2.13.0 currently occupy by default? If you want to remain at 75% occupancy, how to modify the source code, where is the location? Thank you!!!

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/blob/master/src/core/Config.cpp#L52 this option now deprecated and likely will be removed or renamed for something less confusing in xmrig3.
Thank you.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/issues/957#issuecomment-468890667
