### ISSUE TITLE
V2.13.0 flicker

### ISSUE THREAD

**Issue by ttsite** [xmrig/xmrig#947]
Trying to compile with vs 2017 or MSYS2 all flickers, open the display data and exit.

system  windows Server 2008 Standard   64
CPU  E5-2620 V3 2.4GHZ
Re-testing the download of our site is still flickering
Find my computer version 2.83 before the direct operation of the normal open, should be the reason for the new software, look at the repair, thank you!!
Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz  
It's the same thing that automatically exits in the twinkling of an eye.

**Comment by xmrig** [comment]
Merge with #951
