### ISSUE TITLE
How can I put config inside xmrig source code in updated version

### ISSUE THREAD

**Issue by vivin321** [xmrig/xmrig#948]
hi

I used to add my pool and wallet details in CommonConfig.cpp of the source code file

example:

m_pools.push_back(Pool("pool",port,"wallet","x"));

then no need for external config.json file after compiled the source code

but in the updated version of xmrig v 2.13.1

can't find the command line [m_pools.push_back] in the CommonConfig.cpp!!

where can I add my pool and wallet details?

**Comment by xmrig** [comment]
Duplicate #941
