### ISSUE TITLE
after update to 2.13.x I have got all my shares rejected

### ISSUE THREAD

**Issue by vivin321** [xmrig/xmrig#951]
hi
working with https://minexmr.com
and I have downloaded xmrig v 2.13.x
the result : all my shares are invaild and got rejected by the pool
any explain ?
check please 
https://ibb.co/JvFF2NQ

2- I tried to compile the source code but I just get xmrig.notle.exe instead of xmrig.exe
and the xmrig.notle.exe does not mining

**Comment by 2010phenix** [comment]
new algo no back support?

**Comment by ttsite** [comment]
> hi
> working with https://minexmr.com
> and I have downloaded xmrig v 2.13.x
> the result : all my shares are invaild and got rejected by the pool
> any explain ?
> check please
> https://ibb.co/JvFF2NQ
> 
> 2- I tried to compile the source code but I just get xmrig.notle.exe instead of xmrig.exe
> and the xmrig.notle.exe does not mining
V2.13.x seems to be a problem, and I also have many machines that automatically quit and do not work after running, and can work normally before replacing the new algorithm.
V2.13.x seems to be a problem, and many of my machines automatically quit working after running, and can work normally before replacing the new algorithm. And I found that 75% of the original CPU default warfare machines will increase CPU occupancy to 100% as long as they can work after replacing the V2.13x version.

**Comment by vivin321** [comment]
- I solved this issue by edited the json file and typing "variant": "auto",
to replace the cn/r algo with cn/2 automatically 
and I reduced the max-cpu usage to 75%,  "max-cpu-usage": 75

- but the other issue can not be solved which is about  compiling the source code 
the output binary is xmrig.notle.exe and as you said it quit as soon as run it

**Comment by xmrig** [comment]
`-notls` suffix for builds without OpenSSL support, but it enabled by default, if OpenSSL not found you will see message `OpenSSL NOT found: use `-DWITH_TLS=OFF` to build without TLS support` when run cmake, if you earlier disable OpenSSL, run cmake again with option `-DWITH_TLS=ON`.
Thank you.

**Comment by ttsite** [comment]
Excuse me, the new version will automatically quit after some machines are running. How to solve this problem? Thank you!!

**Comment by ttsite** [comment]
> `-notls` suffix for builds without OpenSSL support, but it enabled by default, if OpenSSL not found you will see message `OpenSSL NOT found: use `-DWITH_TLS=OFF` to build without TLS support` when run cmake, if you earlier disable OpenSSL, run cmake again with option `-DWITH_TLS=ON`.
> Thank you.

How to solve the problem that the new version will automatically quit after some machines are running? I mentioned it in the post. Thank you!!

**Comment by xmrig** [comment]
Create .cmd file with `pause` at end, sample file included into each zip archive, probably some missconfiguration or in worst case miner crashed.
Thank you.

**Comment by ttsite** [comment]
> Create .cmd file with `pause` at end, sample file included into each zip archive, probably some missconfiguration or in worst case miner crashed.
> Thank you.

This situation has not appeared before, the machine has been working on the software before the new algorithm, replacing the v2.13x version of the new algorithm is not feasible, replacing the previous normal use. Whether downloaded and compiled from the website or compiled by myself manually using vs2015 vs2017 gcc, it can not run. It will automatically exit after running. It will start from the new software release. Tested. This has always been the case. I broke down. I really don't know how to do it. It's March 9. I can't find the reason. Thank you.

**Comment by 2010phenix** [comment]
@ttsite start miner over cmd on this machines  and if you say 
> new version will automatically quit after some machines are running
in console be some info... make screenshot or send here...

**Comment by xmrig** [comment]
@ttsite What exactly means it not run:
1. Exit without any output
2. Show summary and exit.
3. ...

Please provide all possible information, miner config, hardware information, etc, If miner crashed on same machine where you use vs2015/vs2017/gcc you can create debug build, and try to debug it, if miner really crashed call stack information will be very useful.
Thank you.

**Comment by vivin321** [comment]
> Create .cmd file with `pause` at end, sample file included into each zip archive, probably some missconfiguration or in worst case miner crashed.
> Thank you.

No sir it's not missconfiguration issues. I followed your instractions on how to build the miner and I just added the pool and wallet's data into pools.cpp as you mentioned in another topic
and the output failed to mining and exit without any summary
alot of guys faced the same bug 
here is my binary. check it please 
http://rgho.st/6h9wbzrBd

**Comment by vivin321** [comment]
@xmrig Why do you ignor my question and do not help me?

**Comment by ttsite** [comment]
Every time I just want to connect to the mine address, when I see that the CPU is occupied, I automatically quit. This situation did not appear in the previous version of the new algorithm. Just now, I tested the version of v2.12.0, which is also automatic exit. Because the original version of 2.83 is stable and has not been replaced, I saw that the version of v2.13X appeared automatic exit and tested the version of v2.12x under this situation. It should start from this version, I hope the author can see from here. Look for the reasons above the version. Think about where the major changes were made at that time. Thank you!!
Test System and Processor
Windows Server 2008
CPU E5-2620 V3
CPU E5-2620 V4
CPU E5-2690 V2

**Comment by vivin321** [comment]
solved via xmrig-dev 
thank you

**Comment by xmrig** [comment]
@ttsite Can you try build without `cn/gpu` algorithm support, `-DWITH_CN_GPU=OFF` for cmake.
Thank you.

**Comment by ttsite** [comment]
> @ttsite Can you try build without `cn/gpu` algorithm support, `-DWITH_CN_GPU=OFF` for cmake.
> Thank you.

In this way, 64-bit components can run normally on the E5 26XX CPU. Why?

**Comment by ttsite** [comment]
> @ttsite Can you try build without `cn/gpu` algorithm support, `-DWITH_CN_GPU=OFF` for cmake.
> Thank you.

Thank you very much for your answer. Finally, it can work properly. Does it have any effect on calculation?

**Comment by xmrig** [comment]
This is only disable `cn/gpu` algorithm and don't affect others algorithms. Thank you for confirming, need investigate what wrong with `cn/gpu`.

**Comment by xmrig** [comment]
Finally fixed in dev branch.

Why this bug happen:
* AVX can be disabled on OS level by command `bcdedit /set xsavedisable 1` (reboot required).
* cpuid still report AVX is available.
* Miner perform algorithm self test using AVX implementation of `cn/gpu` algorithm.
* Miner crashed with `illegal instruction` since AVX not available.

Solution is simple, also check `OSXSAVE` cpuid flag.
@psychocrypt you need fix it too.

**Comment by psychocrypt** [comment]
good job!

@xmrig thank you for the notifycation. I will look into it as soon I have
asm cnR ready for cpu.

**Comment by xmrig** [comment]
Fixed in v2.14.0 https://github.com/xmrig/xmrig/releases/tag/v2.14.0
