### ISSUE TITLE
Entry.cpp:52:16: error: ‘printf’ was not declared in this scope

### ISSUE THREAD

**Issue by kl1059** [xmrig/xmrig#952]
xmrig-2.13.1/src/base/kernel/Entry.cpp: In function ‘int showVersion()’:
xmrig-2.13.1/src/base/kernel/Entry.cpp:52:16: error: ‘printf’ was not declared in this scope
     " with GCC");
                ^
xmrig-2.13.1/src/base/kernel/Entry.cpp: In static member function ‘static int xmrig::Entry::exec(const xmrig::Process&, xmrig::Entry::Id)’:
xmrig-2.13.1/src/base/kernel/Entry.cpp:109:21: error: ‘printf’ was not declared in this scope
         printf(usage);

(this fixed it in my case)

$ diff -C 2 Entry.cpp.1 Entry.cpp
*** Entry.cpp.1 2019-02-25 08:23:59.000000000 -0600
--- Entry.cpp   2019-02-26 12:40:47.798949824 -0600
***************
*** 42,45 ****
--- 42,46 ----
  #include "version.h"

+ #include <stdio.h>

  static int showVersion()

fedora 24 gcc version 6.3.1 20161221 (Red Hat 6.3.1-1) (GCC)

**Comment by marcel1974** [comment]
I had to add #include <cstdio> to  src/base/kernel/Entry.cpp
I still need Ubuntu 15.10 support. It was building fine up to xmrig-2.8.3

**Comment by xmrig** [comment]
Fixed in [dev](https://github.com/xmrig/xmrig/commits/dev) branch.
Thank you.

**Comment by xmrig** [comment]
Fixed in v2.14.0 https://github.com/xmrig/xmrig/releases/tag/v2.14.0
