### ISSUE TITLE
How to config(2.13)

### ISSUE THREAD

**Issue by smzwsz** [xmrig/xmrig#955]
Just set as:
"algo": "cn/r"
"variant": -1

same as xmrig-proxy?

**Comment by xmrig** [comment]
* `"algo": "cn"`, but miner/proxy also understand `"cn/r"`.
* `"variant"` `-1` for auto detect or `"r"`.

If connect miner to the proxy, variant option in miner config doesn't matter.
Thank you.

**Comment by smzwsz** [comment]
Thank u.
BY the way?  I used proxy,miner config must use:
"nicehash": false,
"keepalive": false,
I find "true" may take  a mistake

**Comment by xmrig** [comment]
`"true"` it's string value and it not valid for these options, it expected Boolean value, just `true`.

**Comment by smzwsz** [comment]
like as this :"nicehash": true,？
It seems not very useful

**Comment by xmrig** [comment]
Okay, then:

1. Show full miner output including configs
2. Show config file, wallets can be omitted.

**Comment by smzwsz** [comment]
Sorry。
I have got it wrong,and solved it.
