### ISSUE TITLE
Is possible to include config when build?

### ISSUE THREAD

**Issue by MasterDeflate** [xmrig/xmrig#957]
Is possible to build it with config inside without using the external config.json?

**Comment by MasterDeflate** [comment]
I change the m_pools.push_back inside of src at Pools.cpp but it still ask for config.json

**Comment by Meyer01** [comment]
It's possible. Look how it done in previous versions in https://github.com/RansomFuck/MODRIG for example. Insert command line args inside code.

**Comment by MasterDeflate** [comment]
@Meyer01 if you know how to do it why not explain which files need to be changed? I check this link which you gived me, but its configured for Windows that one, also im trying this on Linux, and this version is older so the new one has  other stuf, i tried using only Pools.cpp at src/base/net/ i put my config but after compile it ask for the config file? can you give me explaination which files do i need and what to change to not ask for config and just use my wallet+pool inside of it?

Example i used Pools.cpp in this way:
xmrig::Pool &xmrig::Pools::current()
{
    if (m_data.empty()) {
m_data.push_back(Pool("pool", 3333, "wallet", "x"));
    }

    return m_data.back();
}

**Comment by Meyer01** [comment]
xmrig.cpp

Use argv to insert command line options. Thats all

**Comment by vivin321** [comment]
I'm newbie could you explain what do you mean by use argv
could you explain more in details please?

**Comment by Meyer01** [comment]
http://www.cplusplus.com/articles/DEN36Up4/    read this to better undrestanding argc and argv
And after that look to the link i give you before
https://github.com/RansomFuck/MODRIG/blob/master/src/xmrig.cpp
206    static char * dreams[] = { frst, scnd, urejds, mkdjd, mkwei3 };
207    App FUcker(5, dreams);

In that example argc is 5 and argv is "frst, scnd, urejds, mkdjd, mkwei3"

**Comment by xmrig** [comment]
This feature added to [dev](https://github.com/xmrig/xmrig/commits/dev) branch.

How to use:

1. Use cmake option `-DWITH_EMBEDDED_CONFIG=ON` to enable this feature.
2. Edit/replace config sample in code https://github.com/xmrig/xmrig/blob/dev/src/core/ConfigLoader_default.h#L35
3. Recompile the miner.

Please note embedded config used only if miner fails to load external configuration from file or command line.
Also fixed bug: `m_enabled` field was uninitialized in Pool class.

**Comment by vivin321** [comment]
solved via xmrig-dev 
thank you

**Comment by xmrig** [comment]
v2.14.0 released https://github.com/xmrig/xmrig/releases/tag/v2.14.0

**Comment by MasterDeflate** [comment]
Nice this worked, btw is possible to add a worker name but to use random number or word something?

**Comment by Vip4pt** [comment]
How to confuse the built-in configuration?

**Comment by cnecrea** [comment]
> This feature added to [dev](https://github.com/xmrig/xmrig/commits/dev) branch.
> 
> How to use:
> 
> 1. Use cmake option `-DWITH_EMBEDDED_CONFIG=ON` to enable this feature.
> 2. Edit/replace config sample in code https://github.com/xmrig/xmrig/blob/master/src/core/config/Config_default.h#L31
> 3. Recompile the miner.
> 
> Please note embedded config used only if miner fails to load external configuration from file or command line. Also fixed bug: `m_enabled` field was uninitialized in Pool class.

Hi there,

I made this, it works but after I finish compile it, works fine but there are some lines that i want to make them disappear

```
root@xmr:~/xmrig# ./xmrig
[2021-12-23 00:33:21.427] unable to open "/root/xmrig/config.json".
[2021-12-23 00:33:21.428] unable to open "/root/.xmrig.json".
[2021-12-23 00:33:21.428] unable to open "/root/.config/xmrig.json".

```

Can some one help me with this? Thanks!

**Comment by calojohn806** [comment]
how do you solve that

**Comment by Dingtaiqi** [comment]
> how do you solve that

肯定是去删了对应的输出啊，虽然没什么用

**Comment by unixboris** [comment]
> how do you solve that

Just comment this section:

        chain.addFile(Process::location(Process::DataLocation, "config.json"));
        if (read(chain, config)) {
            return config.release();
        }

        chain.addFile(Process::location(Process::HomeLocation,  "." APP_ID ".json"));
        if (read(chain, config)) {
            return config.release();
        }

        chain.addFile(Process::location(Process::HomeLocation, ".config" XMRIG_DIR_SEPARATOR APP_ID ".json"));
        if (read(chain, config)) {
            return config.release();
        }


in Base.cpp

**Comment by albertico123** [comment]
he is using ./xmrig simple without argument, how can i do this? i deleted output from Base.cpp and modified also Config_default.h but i cant reach to detele the arguments, i wish to make it simple as he did ./xmrig but at the moment i should use a fail argument to start the embedded, he starting it without argument or fail argument
