### ISSUE TITLE
Enable Nice Hash

### ISSUE THREAD

**Issue by AhmedZeus** [xmrig/xmrig#965]
Where to enable NiceHash for proxy on XMRIG source ?

**Comment by 2010phenix** [comment]
in config file if use json 
for proxy enable already: https://github.com/xmrig/xmrig/blob/9685496ce0698e860f3ae375c33b181e302a13af/src/common/config/CommonConfig.cpp#L231

**Comment by AhmedZeus** [comment]
That's awesome. Thanks
