### ISSUE TITLE
config inside new version

### ISSUE THREAD

**Issue by locdz** [xmrig/xmrig#966]
I tried this but fail i replace m_data.push_back   as you said to Pools.cpp but when i run the xmrig after compile finish it ask me for config.json

**Comment by 2010phenix** [comment]
build and check alredy done what you ask from DEV branch
https://github.com/xmrig/xmrig/commits/dev

**Comment by xmrig** [comment]
Duplicate https://github.com/xmrig/xmrig/issues/957#issuecomment-468890667
