### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by molrwwdajas** [xmrig/xmrig#967]
Hi,

is there a way to improve perfomerance of xmrig x86 on Windows OS? The hashrate drop of xmrig x86 in comparison with xmrig x64 the same machine is almost a half, even more than just a half, 20 H/s against 60 H/s, speaking about the same machine and cnv2 algo. The new CryptonightR algo in the latest xmrig release is not solving the issue of hashrate drop, which i was hoping for. 

Is there a chance that the problem of hashrate drop is going to be solved in the future xmrig releases?

For examle, the JCE miner (already mentioned in #631  has also both 32 and 64 bit versions. The 32 version of  JCE miner gives twice more hashrate than 32 version of xmrig  - JCE x86 gives 48 H/s while xmrig x86 20 H/s (speaking about the same machine and cnv2 algo)

**Comment by SChernykh** [comment]
Then maybe don't run 32-bit version and run 64-bit instead? CPUs support 64-bit mode since 2003-2004.
