### ISSUE TITLE
Don't use keepalive option with minergate and nicehash.com

### ISSUE THREAD

**Issue by dexametazon** [xmrig/xmrig#97]
hi 
mining is working but dont connect to the pool 
i try in two different server but have problem to connection 
![1](https://user-images.githubusercontent.com/23564495/30155901-5c2d164c-93d3-11e7-8e05-c9e61de43eb2.JPG)

**Comment by xmrig** [comment]
Don't use keepalive option with minergate, 
Remove `-k` or `--keepalive` from command line options or set `"keepalive": false,` in config file.

- [ ] Ignore keepalive option for minergate.com and nicehash.com

**Comment by dexametazon** [comment]
remove --keepalive from command line in config file but still have issue 
![capture](https://user-images.githubusercontent.com/23564495/30206862-b64856f8-94a2-11e7-81c6-1dde862eb126.JPG)

**Comment by xmrig** [comment]
Looks like minergate now use aggressive timeouts and close connection after 2 minutes after last accepted share. Nothing can do on miner side, it only minergate issue also this pool untrusted by community.
Only if you see green **accepted** messages you shares calculated by pool.

**Comment by dorimanx** [comment]
Question, xmrig proxy using nicehash structure to work, do i need to disable keep alive on miners directed to your proxy? Nicehash is ON on miners and no visible issues.

**Comment by xmrig** [comment]
Proxy supports keepalive, but the nicehash.com not. Nicehash is must be ON if you use the proxy.
keepalive not standard extension, but widely supported, prevent to prevent slow workers timeouts. As I know only minergate.com, nicehash.com and some old pool software like cryptonote-universal-pool not support it.

**Comment by xmrig** [comment]
Fixed

**Comment by sunk818** [comment]
@xmrig - I thought cryptonote-universal-pool added support for KeepAlive last year?
 https://github.com/zone117x/node-cryptonote-pool/pull/100

Hard to know what is official repo though...

**Comment by xmrig** [comment]
[cryptonote-universal-pool](https://github.com/fancoder/cryptonote-universal-pool) != node-cryptonote-pool. universal fork does't support keepalve, it trivial change but not present in code.

cryptonote-universal-pool looks abandoned.
Thank you.

**Comment by sunk818** [comment]
So, fancoder is the original cryptonote-universal-pool?

I found another repo that seems to have keep-alive implemented?

https://github.com/clintar/cryptonote-universal-pool/blob/master/lib/pool.js#L1245-L1249

https://github.com/clintar/cryptonote-universal-pool/blob/master/lib/pool.js#L276-L299

I'm not a programmer, so I don't really know for sure.
