### ISSUE TITLE
Issue with new CPU  Intel® Core™ i7-8850H Processor

### ISSUE THREAD

**Issue by vasssek** [xmrig/xmrig#976]
Hi @xmrig,

I have an issue with new notebook which has Intel® Core™ i7-8850H Processor inside. On Intel page and also in the task manager there are shown 6 cores and 12 threads. But when I run xmrig there are shown only 5 cores instead of 6. Where can be the problem ?
![capture](https://user-images.githubusercontent.com/33999902/53957265-32295e00-40de-11e9-99bb-3db5e98da163.PNG)

Thank you.

**Comment by DeadManWalkingTO** [comment]
CPU memory is the limit!!!

**Comment by vasssek** [comment]
Hmm, you mean CPU cache ?

**Comment by DeadManWalkingTO** [comment]
Yes, cache memory limit.
