### ISSUE TITLE
Double algorithm variations has no effect on Cryptonight/R

### ISSUE THREAD

**Issue by Ronnier33** [xmrig/xmrig#981]
when use av=2 option, the hashrate is no difference than av=1. though it worked fine on v8. has this feature be nuked by the new algorithm?

**Comment by slavab73** [comment]
...and triplehash drop down to 15 h/s (from 80 h/s - 1 thread, av=0, core i5, 6mb cache). someone knows the reason?

**Comment by slavab73** [comment]
xmrstack fixed this bug in 2.10.1 release 13 hours ago. 
https://github.com/fireice-uk/xmr-stak/pull/2309

**Comment by xmrig** [comment]
Double hash now much slower that before, thanks to `cn/r`, it new sad reality, in additional triple and more hash mode lacks ASM acceleration.

@slavab73 xmr-stak bug was never exists in xmrig.
Thank you.

**Comment by slavab73** [comment]
@xmrig 
xmrstack 
- get 124h/s in low_power_mode=true (1 thread)
- get   75h/s in low_power_mode=false (1 thread)
so...

**Comment by xmrig** [comment]
Okay my quick test, low_power_mode=false, 1 thread, i7-7700, Ubuntu 18.04:
xmr-stak 2.10.0 = ~78 h/s
xmr-stak 2.10.1 = **~97 h/s**
xmrig 2.14.1 = **~97 h/s**
xmrig 2.13.0 = **~97 h/s**

So? nothing to fix.

**Comment by slavab73** [comment]
@xmrig very sorry! my mistake!! wrong config for xmrstack! testing by proxy :(
best regards...
