### ISSUE TITLE
Add all descriptions cmake options

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig#982]
![image](https://user-images.githubusercontent.com/31975916/54108676-aa996300-43ed-11e9-871d-52f967a50622.png)
![image](https://user-images.githubusercontent.com/31975916/54108697-b71dbb80-43ed-11e9-8a71-cc2dc8ee6232.png)

please add https://github.com/xmrig/xmrig/wiki/Windows-Build descriptions

**Comment by snipeTR** [comment]
> ![image](https://user-images.githubusercontent.com/31975916/54108676-aa996300-43ed-11e9-871d-52f967a50622.png)
> ![image](https://user-images.githubusercontent.com/31975916/54108697-b71dbb80-43ed-11e9-8a71-cc2dc8ee6232.png)
> 
> please add https://github.com/xmrig/xmrig/wiki/Windows-Build descriptions

-DWITH_LIBCPUID=OFF Disable libcpuid. Auto configuration of CPU after this will be very limited.

-DWITH_AEON=OFF Disable CryptoNight-Lite support.

-DWITH_SUMO=OFF disable CryptoNight-Heavy support

-DWITH_CN_PICO=OFF DİSABLE "CryptoNight-Pico support"

-DWITH_CN_GPU=OFF disable CryptoNight-GPU support

-DWITH_HTTPD=OFF Build without built in http server and API.

-DWITH_DEBUG_LOG=OFF disable debug log output

-DWITH_TLS=OFF Disable SSL/TLS support.

-DWITH_ASM=OFF Disable ASM accelerated cryptonight/2.

-DBUILD_STATIC=OFF Disable Build static binary

-DWITH_EMBEDDED_CONFIG=OFF Enable internal embedded JSON config

**Comment by xmrig** [comment]
Done. Thank you.
