### ISSUE TITLE
Issue with v2.14.1 (32bit)

### ISSUE THREAD

**Issue by DeadManWalkingTO** [xmrig/xmrig#993]
Windows XP
-------------

![001](https://user-images.githubusercontent.com/34924727/54465767-8939cd80-4785-11e9-8f2c-98b765645547.png)

Entry point error:
GetTicCount64 at KERNEL32.dll

*Compile to 64bit system with MSYS2 (32bit).
*On Windows 7 32bit works fine.
*Original exe (xmrig-2.14.1-gcc-win32.zip) working fine both Windows XP & Windows 7 32bit.

Any idea?

**Comment by DeadManWalkingTO** [comment]
It's MSYS2 issue after update.
Standard version works fine.

**Comment by codeyee** [comment]
How did you solve it?

**Comment by DeadManWalkingTO** [comment]
> 
> 
> How did you solve it?

1. Backup MSYS2.
2. Download the new MSYS2 Installer.
3. Fresh install.
4. Copy my "user" folder.
5. After that Issue Solved.
