### ISSUE TITLE
Where to take the description of teams for this miner?

### ISSUE THREAD

**Issue by ZeroCool-NT** [xmrig/xmrig#995]

**Comment by ORGaniZMo** [comment]
Teams? Имел ввиду команды? =)

**Comment by ZeroCool-NT** [comment]
Yes

вт, 19 мар. 2019 г. в 08:12, >ORG@niZM< <notifications@github.com>:

**Comment by ORGaniZMo** [comment]
> Yes

> -h, --help               display ... help and exit
