### ISSUE TITLE
please add a full list of algorithms syntax to --help

### ISSUE THREAD

**Issue by aleqx** [xmrig/xmrig#996]
Could you please add the full list of algorithm syntax to --help? ... it's hard to keep track of all the algos that are being added (hunt down the correct syntax in the code or separate files).

**Comment by sergneo** [comment]
really, I also faced this, it is unknown where to see the desired algorithm for a particular coin

**Comment by ORGaniZMo** [comment]
sergneo, https://github.com/xmrig/xmrig-proxy/blob/dev/doc/STRATUM_EXT.md#1-mining-algorithm-negotiation

**Comment by asylum119** [comment]
This would be handy to have locally but I assume would also clutter --help

**Comment by xmrig** [comment]
Done in v2.99.x.
Thank you.
