### ISSUE TITLE
Please add Conceal (CCX) correct support 

### ISSUE THREAD

**Issue by Dr-Hard** [xmrig/xmrig#998]
Please add correct support cn (cn/r) "conceal" algo for CCX new fork to xmrig, xmrig-amd & xmrig proxy.

**Comment by gr8form** [comment]
I second this request!  The conceal team had an amazingly smooth fork, very responsive/accessible devs and really have a unique product contribution.  Would also request addition of xmrig-nvidia.  Thank you!

**Comment by Dr-Hard** [comment]
Please add correct support cn (cn/r) "conceal" algo for CCX new fork to xmrig, xmrig-amd & xmrig proxy. Conceal dev group given you all info for it.

**Comment by Dr-Hard** [comment]
Please add correct and WORKING support cn (cn/r) "conceal" algo for CCX new fork to xmrig, xmrig-amd & xmrig proxy. Conceal dev group given you all info for it.

**Comment by UnclWish** [comment]
Connect to request. Miner needs Conceal CCX support (cn/conceal)

**Comment by krypt0x** [comment]
inline __m128 _mm_set1_ps_epi32(uint32_t x)
{
	return _mm_castsi128_ps(_mm_set1_epi32(x));
}

inline void cryptonight_conceal_tweak(__m128i& cx, __m128& conc_var)
{
	__m128 r = _mm_cvtepi32_ps(cx);
	__m128 c_old = conc_var;
	r = _mm_add_ps(r, conc_var);
	r = _mm_mul_ps(r, _mm_mul_ps(r, r));
	r = _mm_and_ps(_mm_set1_ps_epi32(0x807FFFFF), r);
	r = _mm_or_ps(_mm_set1_ps_epi32(0x40000000), r);
	conc_var = _mm_add_ps(conc_var, r);

	c_old = _mm_and_ps(_mm_set1_ps_epi32(0x807FFFFF), c_old);
	c_old = _mm_or_ps(_mm_set1_ps_epi32(0x40000000), c_old);
	__m128 nc = _mm_mul_ps(c_old, _mm_set1_ps(536870880.0f));
	cx = _mm_xor_si128(cx, _mm_cvttps_epi32(nc));
}

**Comment by krypt0x** [comment]
https://github.com/ConcealNetwork/conceal-xmrig/commit/5160534cf143ab3b17983b8418476e8617147b0c

**Comment by aefefgrg** [comment]
Mİners need this support.

**Comment by TheDevMinerTV** [comment]
+1 from me!

**Comment by system-overflow** [comment]
CN_Conceal is missing!!! Please add the most energy efficient CN algo out there. I can send you some $CCX mate. Should we raise a bounty on CCX Discord?

**Comment by system-overflow** [comment]
> inline __m128 _mm_set1_ps_epi32(uint32_t x)
> {
> return _mm_castsi128_ps(_mm_set1_epi32(x));
> }
> 
> inline void cryptonight_conceal_tweak(__m128i& cx, __m128& conc_var)
> {
> __m128 r = _mm_cvtepi32_ps(cx);
> __m128 c_old = conc_var;
> r = _mm_add_ps(r, conc_var);
> r = _mm_mul_ps(r, _mm_mul_ps(r, r));
> r = _mm_and_ps(_mm_set1_ps_epi32(0x807FFFFF), r);
> r = _mm_or_ps(_mm_set1_ps_epi32(0x40000000), r);
> conc_var = _mm_add_ps(conc_var, r);
> 
> ```
> c_old = _mm_and_ps(_mm_set1_ps_epi32(0x807FFFFF), c_old);
> c_old = _mm_or_ps(_mm_set1_ps_epi32(0x40000000), c_old);
> __m128 nc = _mm_mul_ps(c_old, _mm_set1_ps(536870880.0f));
> cx = _mm_xor_si128(cx, _mm_cvttps_epi32(nc));
> ```
> 
> }

It looks good mate

**Comment by TheHungryRaccoon** [comment]
How come no CN_Conceal? Please add this algo.

https://medium.com/@ConcealNetwork/new-cn-conceal-pow-algorithm-f68e2159cab0

https://miningpoolstats.stream/conceal

https://www.cryptunit.com/coin/CCX

**Comment by realityworks** [comment]
I could add this in the fork. What's the job? Happy to take Monero as payment.

**Comment by system-overflow** [comment]
> I could add this in the fork. What's the job? Happy to take Monero as payment.

The bounty is to integrate CPU & GPU support on xmrig for CN_Conceal. It would be better to contact the CCX team on their Discord. I am just an user... Thanks

http://discord.conceal.network

**Comment by okanist** [comment]
Conceal algo is one of the most popular one, please add this algo as well. Miners have been asking for it for a long time. They deserve it!

**Comment by SChernykh** [comment]
XMRig's main purpose is Monero mining, so we're concentrated on RandomX (and its variants) support now. Adding new Cryptonight variant is not that easy, don't forget there is also GPU code both for AMD and NVIDIA. But if someone creates a PR here, it can be merged.

**Comment by realityworks** [comment]
> XMRig's main purpose is Monero mining, so we're concentrated on RandomX (and its variants) support now. Adding new Cryptonight variant is not that easy, don't forget there is also GPU code both for AMD and NVIDIA. But if someone creates a PR here, it can be merged.

I'm talking with the CN team at the moment to confirm the change in an update. Need to review the workload and see what I can contribute to the community time wise.

**Comment by system-overflow** [comment]
> XMRig's main purpose is Monero mining, so we're concentrated on RandomX (and its variants) support now. Adding new Cryptonight variant is not that easy, don't forget there is also GPU code both for AMD and NVIDIA. But if someone creates a PR here, it can be merged.

CCX community has the biggest heart. CCX support will be sorted out but you are depreciating all the GPU miners that have supported you all these years. I can't mine XMR with my GPU rigs, period. :thinking:

**Comment by TheHungryRaccoon** [comment]
> XMRig's main purpose is Monero mining, so we're concentrated on RandomX (and its variants) support now. Adding new Cryptonight variant is not that easy, don't forget there is also GPU code both for AMD and NVIDIA. But if someone creates a PR here, it can be merged.

No worries. We came here for respect to the authors. IT's good to know you will merge the CCX support PR. Thanks.

**Comment by system-overflow** [comment]
> > XMRig's main purpose is Monero mining, so we're concentrated on RandomX (and its variants) support now. Adding new Cryptonight variant is not that easy, don't forget there is also GPU code both for AMD and NVIDIA. But if someone creates a PR here, it can be merged.
> 
> @SChernykh I'm talking with the CN team at the moment to confirm the change in an update on my fork. Need to review the workload and see what I can contribute to the community time wise.

Fantastic!

**Comment by vasssek** [comment]
Hi, is there intention to add CCX algo ?

**Comment by krypt0x** [comment]
@xmrig we need your help with this. Thanks

**Comment by LithyRiolu** [comment]
+1 for the support of this hashing algorithm!

**Comment by ChrisfromNM** [comment]
Mİners need this support.  @xmrig we need your help with this. Thanks

**Comment by SChernykh** [comment]
It will be added in the next release.
https://github.com/xmrig/xmrig/pull/1717
https://github.com/xmrig/xmrig-cuda/pull/52

**Comment by BKdilse** [comment]
@SChernykh for Cuda only, or OpenCL too?

**Comment by SChernykh** [comment]
For everything, even ARM CPUs.

**Comment by BKdilse** [comment]
> For everything, even ARM CPUs.

Brilliant thanks

**Comment by xmrig** [comment]
[v6.2.0](https://github.com/xmrig/xmrig/releases/tag/v6.2.0-beta) with Conceal support just released.
Thank you.

**Comment by krypt0x** [comment]
Flawless. Great job! Thank you.
