### ISSUE TITLE
the correct way to stop from the program

### ISSUE THREAD

**Issue by Boklazhenko** [xmrig/xmrig#999]
Hi, is exist the correct way to stop xmrig using programming? thx

**Comment by timk74** [comment]
PostMessage(xmrigwnd, WM_CLOSE, 0, 0);

**Comment by Boklazhenko** [comment]
unfortunately, it doesn't work. xmrig does not process WM_CLOSE

**Comment by timk74** [comment]
It's working.
`PostMessage(FindWindow('ConsoleWindowClass', 'C:\xmrig\xmrig.exe'), WM_CLOSE, 0, 0);`
Your program should have the same (or higher) security privileges as xmrig. If xmrig started from the administrator, then your program must also be started from the administrator.
